
@interface PRWidgetGridViewController : UIViewController <BSInvalidatable, CHSWidgetDescriptorProviderObserver, CHUISWidgetHostViewControllerDelegate, SBHIconModelDelegate, SBIconDelegate, SBIconDragManagerDelegate, SBIconListLayoutObserver, SBIconListModelObserver, SBIconListViewDragDelegate, SBIconModelStore, SBIconViewDelegate, SBIconViewObserver, SBIconViewProviding, SBRecycledViewsContainerProviding, SBReusableViewMapDelegate> {
    NSArray * _complicationDescriptors;
    NSMutableDictionary * _complicationDescriptorsByUniqueIdentifier;
    <PRWidgetGridViewControllerDelegate> * _delegate;
    SBIconDragManager * _dragManager;
    bool  _focused;
    NSDictionary * _iconLayout;
    SBHIconModel * _iconModel;
    SBReusableViewMap * _iconViewMap;
    <SBIconViewProviding> * _iconViewProvider;
    SBIconListView * _listView;
    UIView * _recycledViewsContainerView;
    bool  _requiresFocusForLaunchRequests;
    BSUIVibrancyConfiguration * _vibrancyConfiguration;
    bool  _widgetInteractionDisabled;
}

@property (nonatomic, retain) NSArray *complicationDescriptors;
@property (nonatomic, retain) NSMutableDictionary *complicationDescriptorsByUniqueIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <PRWidgetGridViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SBIconDragManager *dragManager;
@property (getter=isEditing, nonatomic) bool editing;
@property (getter=isFocused, nonatomic) bool focused;
@property (readonly) unsigned long long hash;
@property (getter=isIconContentPossiblyVisibleOverApplication, nonatomic, readonly) bool iconContentPossiblyVisibleOverApplication;
@property (nonatomic) double iconContentScale;
@property (nonatomic, retain) NSDictionary *iconLayout;
@property (nonatomic, retain) SBHIconModel *iconModel;
@property (nonatomic) <SBIconViewProviding> *iconViewProvider;
@property (nonatomic, retain) SBIconListView *listView;
@property (getter=isMainDisplayLibraryViewVisible, nonatomic) bool mainDisplayLibraryViewVisible;
@property (getter=isOverlayTodayViewVisible, nonatomic) bool overlayTodayViewVisible;
@property (nonatomic, readonly) UIView *recycledViewsContainer;
@property (nonatomic) bool requiresFocusForLaunchRequests;
@property (getter=isRootFolderContentVisible, nonatomic, readonly) bool rootFolderContentVisible;
@property (getter=isScrolling, nonatomic) bool scrolling;
@property (readonly) Class superclass;
@property (getter=isTrackingScroll, nonatomic) bool trackingScroll;
@property (nonatomic, retain) BSUIVibrancyConfiguration *vibrancyConfiguration;
@property (getter=isWidgetInteractionDisabled, nonatomic) bool widgetInteractionDisabled;

- (void).cxx_destruct;
- (void)_addIconForDescriptor:(id)arg1 animated:(bool)arg2;
- (bool)_canShowWhileLocked;
- (void)_iconModelDidLayoutIconState:(id)arg1;
- (void)_removeIconForDescriptor:(id)arg1 animated:(bool)arg2;
- (void)_removeIconsForUnavailableWidgets;
- (bool)_shouldDisableWidgetInteraction;
- (void)_tapGestureRecognized:(id)arg1;
- (id)_widgetIconForComplicationDescriptor:(id)arg1;
- (id)_widgetIconViewControllerForIcon:(id)arg1;
- (bool)allowsSnappingIconsToGridForIconDragManager:(id)arg1;
- (bool)canAddComplicationDescriptor:(id)arg1;
- (long long)closeBoxTypeForIconView:(id)arg1;
- (id)complicationDescriptors;
- (id)complicationDescriptorsByUniqueIdentifier;
- (void)configureIconView:(id)arg1 forIcon:(id)arg2;
- (bool)containsIconsInRow:(unsigned long long)arg1;
- (id)customImageViewControllerForIconView:(id)arg1;
- (id)delegate;
- (bool)deleteCurrentIconStateWithOptions:(unsigned long long)arg1 error:(id*)arg2;
- (bool)deleteDesiredIconStateWithOptions:(unsigned long long)arg1 error:(id*)arg2;
- (id)dequeueReusableIconViewOfClass:(Class)arg1;
- (void)descriptorsDidChangeForDescriptorProvider:(id)arg1;
- (id)dragItemsForIconView:(id)arg1;
- (id)dragManager;
- (void)ensureContentWithTimeout:(double)arg1 completion:(id /* block */)arg2;
- (struct SBHIconGridSizeClassSizes { struct SBHIconGridSize { unsigned short x_1_1_1; unsigned short x_1_1_2; } x1; struct SBHIconGridSize { unsigned short x_2_1_1; unsigned short x_2_1_2; } x2; struct SBHIconGridSize { unsigned short x_3_1_1; unsigned short x_3_1_2; } x3; struct SBHIconGridSize { unsigned short x_4_1_1; unsigned short x_4_1_2; } x4; struct SBHIconGridSize { unsigned short x_5_1_1; unsigned short x_5_1_2; } x5; })gridSizeClassSizesForIconModel:(id)arg1;
- (void)icon:(id)arg1 launchFromLocation:(id)arg2 context:(id)arg3;
- (void)iconCloseBoxTapped:(id)arg1;
- (double)iconContentScale;
- (bool)iconDragManager:(id)arg1 canMakeIconViewDragRecipient:(id)arg2;
- (bool)iconDragManager:(id)arg1 canSnapIconsToGridInLocation:(id)arg2;
- (id)iconLayout;
- (void)iconList:(id)arg1 didRemoveIcon:(id)arg2;
- (bool)iconListView:(id)arg1 canHandleIconDropSession:(id)arg2;
- (id)iconListView:(id)arg1 customSpringAnimationBehaviorForDroppingItem:(id)arg2;
- (void)iconListView:(id)arg1 iconDragItem:(id)arg2 willAnimateDropWithAnimator:(id)arg3;
- (void)iconListView:(id)arg1 iconDropSession:(id)arg2 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg3;
- (void)iconListView:(id)arg1 iconDropSessionDidEnter:(id)arg2;
- (void)iconListView:(id)arg1 iconDropSessionDidExit:(id)arg2;
- (id)iconListView:(id)arg1 iconDropSessionDidUpdate:(id)arg2;
- (id)iconListView:(id)arg1 iconViewForDroppingIconDragItem:(id)arg2 proposedIconView:(id)arg3;
- (void)iconListView:(id)arg1 performIconDrop:(id)arg2;
- (id)iconListView:(id)arg1 previewForDroppingIconDragItem:(id)arg2 proposedPreview:(id)arg3;
- (bool)iconListView:(id)arg1 shouldAllowSpringLoadedInteractionForIconDropSession:(id)arg2 onIconView:(id)arg3;
- (void)iconListView:(id)arg1 springLoadedInteractionForIconDragDidCompleteOnIconView:(id)arg2;
- (void)iconListView:(id)arg1 willUseIconView:(id)arg2 forDroppingIconDragItem:(id)arg3;
- (id)iconModel;
- (unsigned long long)iconModel:(id)arg1 allowedGridSizeClassesForFolderClass:(Class)arg2;
- (id)iconModel:(id)arg1 customInsertionIndexPathForIcon:(id)arg2 inRootFolder:(id)arg3;
- (void)iconModel:(id)arg1 didAddIcon:(id)arg2;
- (void)iconModel:(id)arg1 launchIcon:(id)arg2 fromLocation:(id)arg3 context:(id)arg4;
- (struct SBHIconGridSize { unsigned short x1; unsigned short x2; })iconModel:(id)arg1 listGridSizeForFolderClass:(Class)arg2;
- (long long)iconModel:(id)arg1 listsFixedIconLocationBehaviorForFolderClass:(Class)arg2;
- (unsigned long long)iconModel:(id)arg1 listsIconLayoutBehaviorForFolderClass:(Class)arg2;
- (id)iconModel:(id)arg1 localizedFolderNameForDefaultDisplayName:(id)arg2;
- (unsigned long long)iconModel:(id)arg1 maxColumnCountForListInRootFolderWithInterfaceOrientation:(long long)arg2;
- (unsigned long long)iconModel:(id)arg1 maxRowCountForListInRootFolderWithInterfaceOrientation:(long long)arg2;
- (bool)iconView:(id)arg1 canAddDragItemsToSession:(id)arg2;
- (void)iconView:(id)arg1 didChangeCustomImageViewController:(id)arg2;
- (void)iconView:(id)arg1 didEndDragSession:(id)arg2 withOperation:(unsigned long long)arg3;
- (void)iconView:(id)arg1 dragLiftAnimationDidChangeDirection:(long long)arg2;
- (id)iconView:(id)arg1 dragPreviewForItem:(id)arg2 session:(id)arg3 previewParameters:(id)arg4;
- (void)iconView:(id)arg1 item:(id)arg2 willAnimateDragCancelWithAnimator:(id)arg3;
- (void)iconView:(id)arg1 willAnimateDragLiftWithAnimator:(id)arg2 session:(id)arg3;
- (id)iconViewMap;
- (id)iconViewProvider;
- (id)iconViewQueryableForIconDragManager:(id)arg1;
- (void)iconViewWillBeginDrag:(id)arg1 session:(id)arg2;
- (id)initWithComplicationDescriptors:(id)arg1 iconLayout:(id)arg2;
- (id)initWithComplicationDescriptors:(id)arg1 iconLayout:(id)arg2 iconViewProvider:(id)arg3;
- (bool)interpretsViewAsContent:(id)arg1;
- (void)invalidate;
- (bool)isEditing;
- (bool)isFocused;
- (bool)isIconViewRecycled:(id)arg1;
- (bool)isWidgetInteractionDisabled;
- (id)listView;
- (id)loadCurrentIconState:(id*)arg1;
- (id)loadDesiredIconState:(id*)arg1;
- (void)loadView;
- (unsigned long long)maxIconCountForDockForIconModel:(id)arg1;
- (unsigned long long)maxListCountForFoldersForIconModel:(id)arg1;
- (void)recycleIconView:(id)arg1;
- (id)recycledViewsContainer;
- (id)recycledViewsContainerProviderForViewMap:(id)arg1;
- (bool)requiresFocusForLaunchRequests;
- (id)rootFolderForIconDragManager:(id)arg1;
- (id)rootViewForIconDragManager:(id)arg1;
- (bool)saveCurrentIconState:(id)arg1 error:(id*)arg2;
- (bool)saveDesiredIconState:(id)arg1 error:(id*)arg2;
- (void)setComplicationDescriptors:(id)arg1;
- (void)setComplicationDescriptors:(id)arg1 animated:(bool)arg2;
- (void)setComplicationDescriptorsByUniqueIdentifier:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDragManager:(id)arg1;
- (void)setFocused:(bool)arg1;
- (void)setFocused:(bool)arg1 animated:(bool)arg2;
- (void)setFocused:(bool)arg1 animationSettings:(id)arg2;
- (void)setIconContentScale:(double)arg1;
- (void)setIconLayout:(id)arg1;
- (void)setIconModel:(id)arg1;
- (void)setIconViewProvider:(id)arg1;
- (void)setListView:(id)arg1;
- (void)setRequiresFocusForLaunchRequests:(bool)arg1;
- (void)setVibrancyConfiguration:(id)arg1;
- (void)setWidgetInteractionDisabled:(bool)arg1;
- (bool)shouldNonDefaultGridSizeClassesUseClusterAnimationForIconDragManager:(id)arg1;
- (id)vibrancyConfiguration;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (unsigned long long)viewMap:(id)arg1 maxRecycledViewsOfClass:(Class)arg2;
- (void)widgetHostViewController:(id)arg1 requestsLaunchWithAction:(id)arg2;

@end
