
@interface HUMobileTimerObjectTableViewController : UITableViewController <HFHomeKitAccessorySettingsDataSourceDelegate, HUPresentationDelegateHost, HUQuickControlContentRequiringHelper> {
    HMAccessory * _accessory;
    unsigned long long  _accessoryAccessState;
    NSTimer * _accessoryActivationTimer;
    NAFuture * _checkAccessAndFetchDataFuture;
    bool  _createNewMTObjectPendingSidekickActivation;
    NSString * _headerCellTitle;
    NSUUID * _headerUUID;
    NSString * _identifier;
    bool  _itemShouldDisplaySpinner;
    NSString * _loadingItemsTitle;
    <HFMediaProfileContainer> * _mediaProfileContainer;
    NSMutableArray * _mobileTimerObjects;
    HUMobileTimerContentUnavailableView * _noItemsView;
    NAFuture * _outstandingMobileTimerObjectsFuture;
    bool  _redrawSpinnerCell;
    UITableViewDiffableDataSource * _tableViewDataSource;
    NSString * _unavailableText;
    NSString * _unavailableTitle;
    NSArray * _updatedMobileTimerObjects;
    bool  _wasControllableAtLastCheck;
    <HUPresentationDelegate> * presentationDelegate;
    <HUQuickControlContentHelper> * quickControlContentHelper;
}

@property (nonatomic, retain) HMAccessory *accessory;
@property (nonatomic) unsigned long long accessoryAccessState;
@property (nonatomic, retain) NSTimer *accessoryActivationTimer;
@property (nonatomic, retain) NAFuture *checkAccessAndFetchDataFuture;
@property (nonatomic) bool createNewMTObjectPendingSidekickActivation;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *headerCellTitle;
@property (nonatomic, readonly) NSUUID *headerUUID;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic) bool itemShouldDisplaySpinner;
@property (nonatomic, retain) NSString *loadingItemsTitle;
@property (nonatomic, retain) <HFMediaProfileContainer> *mediaProfileContainer;
@property (nonatomic, retain) NSMutableArray *mobileTimerObjects;
@property (nonatomic, retain) HUMobileTimerContentUnavailableView *noItemsView;
@property (nonatomic, readonly) unsigned long long numberOfMobileTimerObjects;
@property (nonatomic, retain) NAFuture *outstandingMobileTimerObjectsFuture;
@property (nonatomic) <HUPresentationDelegate> *presentationDelegate;
@property (nonatomic) <HUQuickControlContentHelper> *quickControlContentHelper;
@property (nonatomic) bool redrawSpinnerCell;
@property (readonly) Class superclass;
@property (nonatomic, retain) UITableViewDiffableDataSource *tableViewDataSource;
@property (nonatomic, retain) NSString *unavailableText;
@property (nonatomic, retain) NSString *unavailableTitle;
@property (nonatomic, retain) NSArray *updatedMobileTimerObjects;
@property (nonatomic) bool wasControllableAtLastCheck;

- (void).cxx_destruct;
- (void)_accessoryActivationTimerFinished:(id)arg1;
- (bool)_activateAccessoryForMobileTimerCreation;
- (id)_baseMobileTimerObjectsFuture;
- (struct CGSize { double x1; double x2; })_calculatePreferredContentSize;
- (id)_canManagerControlAccessory;
- (bool)_canShowWhileLocked;
- (void)_checkAccessFetchDataAndReloadTable;
- (void)_checkAndAddTimerObject;
- (id)_checkAndFetchTimerObjects;
- (void)_configureNoItemsViewAnimated:(bool)arg1;
- (id)_findTimerObjectForID:(id)arg1;
- (bool)_isSiriEndpointActive;
- (id)_newCellForHeaderTitle:(id)arg1;
- (id)_newCellForMTTimerObjectUUID:(id)arg1;
- (void)_quickDeleteMobileTimerObjectFromTable:(id)arg1;
- (void)_reloadTableViewWithExistingData;
- (void)_removeTimerObjectAtIndexPath:(id)arg1;
- (bool)_shouldAllowCellSelection;
- (void)_showSpinner:(bool)arg1;
- (id)accessory;
- (unsigned long long)accessoryAccessState;
- (id)accessoryActivationTimer;
- (id)checkAccessAndFetchDataFuture;
- (bool)createNewMTObjectPendingSidekickActivation;
- (void)dealloc;
- (void)didReceiveSettingsUpdatesForAccessoryWithIdentifier:(id)arg1 settings:(id)arg2;
- (id)headerCellTitle;
- (id)headerUUID;
- (id)identifier;
- (id)initWithMediaProfileContainer:(id)arg1;
- (bool)itemShouldDisplaySpinner;
- (id)loadingItemsTitle;
- (id)mediaProfileContainer;
- (id)mobileTimerObjects;
- (id)noItemsView;
- (unsigned long long)numberOfMobileTimerObjects;
- (id)outstandingMobileTimerObjectsFuture;
- (struct CGSize { double x1; double x2; })preferredContentSize;
- (void)presentAddMobileTimerObjectViewControllerOnMainThread;
- (id)presentationDelegate;
- (id)quickControlContentHelper;
- (bool)redrawSpinnerCell;
- (void)setAccessory:(id)arg1;
- (void)setAccessoryAccessState:(unsigned long long)arg1;
- (void)setAccessoryActivationTimer:(id)arg1;
- (void)setCheckAccessAndFetchDataFuture:(id)arg1;
- (void)setCreateNewMTObjectPendingSidekickActivation:(bool)arg1;
- (void)setHeaderCellTitle:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setItemShouldDisplaySpinner:(bool)arg1;
- (void)setLoadingItemsTitle:(id)arg1;
- (void)setMediaProfileContainer:(id)arg1;
- (void)setMobileTimerObjects:(id)arg1;
- (void)setNoItemsView:(id)arg1;
- (void)setOutstandingMobileTimerObjectsFuture:(id)arg1;
- (void)setPresentationDelegate:(id)arg1;
- (void)setQuickControlContentHelper:(id)arg1;
- (void)setRedrawSpinnerCell:(bool)arg1;
- (void)setTableViewDataSource:(id)arg1;
- (void)setUnavailableText:(id)arg1;
- (void)setUnavailableTitle:(id)arg1;
- (void)setUpdatedMobileTimerObjects:(id)arg1;
- (void)setWasControllableAtLastCheck:(bool)arg1;
- (id)tableView:(id)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(id)arg2;
- (id)tableViewDataSource;
- (id)unavailableText;
- (id)unavailableTitle;
- (id)updatedMobileTimerObjects;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (bool)wasControllableAtLastCheck;

@end
