
@interface PKPayLaterFinancingOption : NSObject <NSCopying, NSSecureCoding> {
    NSDecimalNumber * _apr;
    PKCurrencyAmount * _authAmount;
    unsigned long long  _autoPayment;
    PKPayLaterFinancingAmount * _dueNow;
    NSDictionary * _financingOptionData;
    bool  _hasAPR;
    NSString * _identifier;
    PKPayLaterFinancingAmount * _installmentAmount;
    long long  _installmentCount;
    PKPayLaterFinancingAmount * _installmentFees;
    NSArray * _installments;
    unsigned long long  _merchantCapabilities;
    unsigned long long  _productType;
    NSString * _selectionIdentifier;
    NSSet * _supportedRepaymentCountries;
    NSSet * _supportedRepaymentFundingSourceIdentifiers;
    NSArray * _supportedRepaymentNetworks;
    unsigned long long  _supportedRepaymentTypes;
    PKPayLaterFinancingOptionTermsDetails * _termsDetails;
    PKPayLaterFinancingAmount * _totalAmount;
    PKPayLaterFinancingAmount * _totalFees;
    PKPayLaterFinancingAmount * _totalInterest;
    PKPayLaterFinancingAmount * _totalPrincipal;
}

@property (nonatomic, copy) NSDecimalNumber *apr;
@property (nonatomic, retain) PKCurrencyAmount *authAmount;
@property (nonatomic) unsigned long long autoPayment;
@property (nonatomic, retain) PKPayLaterFinancingAmount *dueNow;
@property (nonatomic, copy) NSDictionary *financingOptionData;
@property (nonatomic) bool hasAPR;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, retain) PKPayLaterFinancingAmount *installmentAmount;
@property (nonatomic) long long installmentCount;
@property (nonatomic, retain) PKPayLaterFinancingAmount *installmentFees;
@property (nonatomic, retain) NSArray *installments;
@property (nonatomic) unsigned long long merchantCapabilities;
@property (nonatomic) unsigned long long productType;
@property (nonatomic, copy) NSString *selectionIdentifier;
@property (nonatomic, copy) NSSet *supportedRepaymentCountries;
@property (nonatomic, copy) NSSet *supportedRepaymentFundingSourceIdentifiers;
@property (nonatomic, copy) NSArray *supportedRepaymentNetworks;
@property (nonatomic) unsigned long long supportedRepaymentTypes;
@property (nonatomic, retain) PKPayLaterFinancingOptionTermsDetails *termsDetails;
@property (nonatomic, retain) PKPayLaterFinancingAmount *totalAmount;
@property (nonatomic, retain) PKPayLaterFinancingAmount *totalFees;
@property (nonatomic, retain) PKPayLaterFinancingAmount *totalInterest;
@property (nonatomic, retain) PKPayLaterFinancingAmount *totalPrincipal;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)analyticsValueForAPR;
- (id)analyticsValueForInstallmentCount;
- (id)apr;
- (id)authAmount;
- (unsigned long long)autoPayment;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dueNow;
- (void)encodeWithCoder:(id)arg1;
- (id)financingOptionData;
- (bool)hasAPR;
- (unsigned long long)hash;
- (id)identifier;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1 productType:(unsigned long long)arg2;
- (id)installmentAmount;
- (long long)installmentCount;
- (id)installmentFees;
- (id)installments;
- (bool)isAmountDetailsEqualToFinancingOption:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToFinancingOption:(id)arg1;
- (unsigned long long)merchantCapabilities;
- (unsigned long long)productType;
- (id)selectionIdentifier;
- (void)setApr:(id)arg1;
- (void)setAuthAmount:(id)arg1;
- (void)setAutoPayment:(unsigned long long)arg1;
- (void)setDueNow:(id)arg1;
- (void)setFinancingOptionData:(id)arg1;
- (void)setHasAPR:(bool)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setInstallmentAmount:(id)arg1;
- (void)setInstallmentCount:(long long)arg1;
- (void)setInstallmentFees:(id)arg1;
- (void)setInstallments:(id)arg1;
- (void)setMerchantCapabilities:(unsigned long long)arg1;
- (void)setProductType:(unsigned long long)arg1;
- (void)setSelectionIdentifier:(id)arg1;
- (void)setSupportedRepaymentCountries:(id)arg1;
- (void)setSupportedRepaymentFundingSourceIdentifiers:(id)arg1;
- (void)setSupportedRepaymentNetworks:(id)arg1;
- (void)setSupportedRepaymentTypes:(unsigned long long)arg1;
- (void)setTermsDetails:(id)arg1;
- (void)setTotalAmount:(id)arg1;
- (void)setTotalFees:(id)arg1;
- (void)setTotalInterest:(id)arg1;
- (void)setTotalPrincipal:(id)arg1;
- (id)supportedRepaymentCountries;
- (id)supportedRepaymentFundingSourceIdentifiers;
- (id)supportedRepaymentNetworks;
- (unsigned long long)supportedRepaymentTypes;
- (id)termsDetails;
- (id)totalAmount;
- (id)totalFees;
- (id)totalInterest;
- (id)totalPrincipal;

@end
