
@interface PKSecureElementPass : PKPass <NSCopying, NSSecureCoding> {
    NSString * _appURLScheme;
    unsigned long long  _associatedAccountFeatureIdentifier;
    NSString * _associatedAccountServiceAccountIdentifier;
    NSSet * _associatedApplicationIdentifiers;
    NSSet * _associatedWebDomains;
    PKPassAuxiliaryRegistrationRequirements * _auxiliaryRegistrationRequirements;
    NSArray * _availableActions;
    long long  _cardType;
    NSString * _cobrandName;
    bool  _cobranded;
    NSString * _customerServiceIdentifier;
    NSSet * _deviceInAppPaymentApplications;
    NSSet * _devicePaymentApplications;
    PKPaymentApplication * _devicePrimaryBarcodePaymentApplication;
    PKPaymentApplication * _devicePrimaryContactlessPaymentApplication;
    PKPaymentApplication * _devicePrimaryInAppPaymentApplication;
    PKPaymentApplication * _devicePrimaryPaymentApplication;
    bool  _hasAssociatedPeerPaymentAccount;
    NSString * _issuerAdministrativeAreaCode;
    NSString * _issuerCountryCode;
    NSString * _localizedSuspendedReason;
    NSString * _messagePushTopic;
    NSURL * _messageServiceRegistrationURL;
    NSURL * _messageServiceURL;
    NSDate * _originalProvisioningDate;
    NSString * _partnerAccountIdentifier;
    NSSet * _paymentApplications;
    bool  _paymentOptionSelectable;
    NSString * _primaryAccountIdentifier;
    NSString * _primaryAccountNumberSuffix;
    PKPassProvisioningMetadata * _provisioningMetadata;
    bool  _requiresTransferSerialNumberBasedProvisioning;
    NSString * _sanitizedPrimaryAccountName;
    NSString * _sanitizedPrimaryAccountNumber;
    bool  _shellPass;
    NSString * _shippingAddressSeed;
    NSString * _speakableMake;
    NSString * _speakableModel;
    PKSiriIntentsConfiguration * _supportedSiriIntents;
    bool  _supportsDPANNotifications;
    bool  _supportsDefaultCardSelection;
    bool  _supportsFPANNotifications;
    bool  _supportsPeerPayment;
    bool  _supportsSerialNumberBasedProvisioning;
    NSString * _topLeftBackgroundTitle;
    NSString * _topRightBackgroundTitle;
    NSString * _transactionPushTopic;
    NSURL * _transactionServiceRegistrationURL;
    NSURL * _transactionServiceURL;
    NSString * _transactionSourceIdentifier;
}

@property (nonatomic, readonly) long long accessType;
@property (nonatomic, copy) NSString *appURLScheme;
@property (nonatomic) unsigned long long associatedAccountFeatureIdentifier;
@property (nonatomic, copy) NSString *associatedAccountServiceAccountIdentifier;
@property (nonatomic, copy) NSSet *associatedApplicationIdentifiers;
@property (nonatomic, copy) NSSet *associatedWebDomains;
@property (nonatomic, copy) PKPassAuxiliaryRegistrationRequirements *auxiliaryRegistrationRequirements;
@property (nonatomic, copy) NSArray *availableActions;
@property (nonatomic) long long cardType;
@property (nonatomic, copy) NSString *cobrandName;
@property (getter=isCobranded, nonatomic) bool cobranded;
@property (nonatomic, copy) NSString *customerServiceIdentifier;
@property (readonly) NSString *deviceAccountIdentifier;
@property (readonly) NSString *deviceAccountNumberSuffix;
@property (nonatomic, retain) NSSet *deviceInAppPaymentApplications;
@property (nonatomic, readonly, copy) NSString *devicePassIdentifier;
@property (nonatomic, copy) NSSet *devicePaymentApplications;
@property (nonatomic, retain) PKPaymentApplication *devicePrimaryBarcodePaymentApplication;
@property (nonatomic, retain) PKPaymentApplication *devicePrimaryContactlessPaymentApplication;
@property (nonatomic, retain) PKPaymentApplication *devicePrimaryInAppPaymentApplication;
@property (nonatomic, retain) PKPaymentApplication *devicePrimaryPaymentApplication;
@property (nonatomic) bool hasAssociatedPeerPaymentAccount;
@property (nonatomic, readonly) long long identityType;
@property (nonatomic, readonly) bool isUserDeletable;
@property (nonatomic, copy) NSString *issuerAdministrativeAreaCode;
@property (nonatomic, copy) NSString *issuerCountryCode;
@property (nonatomic, copy) NSString *localizedSuspendedReason;
@property (nonatomic, copy) NSString *messagePushTopic;
@property (nonatomic, copy) NSURL *messageServiceRegistrationURL;
@property (nonatomic, copy) NSURL *messageServiceURL;
@property (nonatomic, readonly) NSSet *npkSubcredentials;
@property (nonatomic, retain) NSDate *originalProvisioningDate;
@property (nonatomic, readonly, copy) NSString *pairedTerminalIdentifier;
@property (nonatomic, copy) NSString *partnerAccountIdentifier;
@property (nonatomic, readonly) long long passActivationState;
@property (nonatomic, copy) NSSet *paymentApplications;
@property (getter=isPaymentOptionSelectable, nonatomic) bool paymentOptionSelectable;
@property (nonatomic, retain) PKCurrencyAmount *peerPaymentBalance;
@property (nonatomic, readonly) bool preventsWalletDeletion;
@property (nonatomic, copy) NSString *primaryAccountIdentifier;
@property (nonatomic, copy) NSString *primaryAccountNumberSuffix;
@property (getter=isPrivateLabel, nonatomic, readonly) bool privateLabel;
@property (nonatomic, retain) PKPassProvisioningMetadata *provisioningMetadata;
@property (nonatomic) bool requiresTransferSerialNumberBasedProvisioning;
@property (nonatomic, copy) NSString *sanitizedPrimaryAccountName;
@property (nonatomic, copy) NSString *sanitizedPrimaryAccountNumber;
@property (getter=isShellPass, nonatomic) bool shellPass;
@property (nonatomic, copy) NSString *shippingAddressSeed;
@property (nonatomic, copy) NSString *speakableMake;
@property (nonatomic, copy) NSString *speakableModel;
@property (nonatomic, readonly) unsigned long long supportedRadioTechnologies;
@property (nonatomic, copy) PKSiriIntentsConfiguration *supportedSiriIntents;
@property (nonatomic) bool supportsDPANNotifications;
@property (nonatomic) bool supportsDefaultCardSelection;
@property (nonatomic) bool supportsFPANNotifications;
@property (nonatomic, readonly) bool supportsOnlyTransit;
@property (nonatomic) bool supportsPeerPayment;
@property (nonatomic) bool supportsSerialNumberBasedProvisioning;
@property (nonatomic, copy) NSString *topLeftBackgroundTitle;
@property (nonatomic, copy) NSString *topRightBackgroundTitle;
@property (nonatomic, copy) NSString *transactionPushTopic;
@property (nonatomic, copy) NSURL *transactionServiceRegistrationURL;
@property (nonatomic, copy) NSURL *transactionServiceURL;
@property (nonatomic, copy) NSString *transactionSourceIdentifier;
@property (nonatomic, readonly, copy) PKTransitPassProperties *transitProperties;
@property (nonatomic, readonly) NSArray *upgradeRequests;

// Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore

+ (unsigned long long)defaultSettings;
+ (id)displayableErrorForAction:(id)arg1 andReason:(unsigned long long)arg2;
+ (id)displayableErrorForTransitAction:(id)arg1 andReason:(unsigned long long)arg2;
+ (id)displayableNoPaymentNetworkErrorMessageForAction:(id)arg1 isTransit:(bool)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (unsigned long long)_activationStateForApplicationState:(long long)arg1;
- (id)_launchURLForPassAction:(id)arg1;
- (id)_localizedSuspendedReasonForAID:(id)arg1;
- (id)_passSubcredentialFilesWithPrefix:(id)arg1 extension:(id)arg2 forSecureElementIdentifiers:(id)arg3;
- (id)_transactionServiceURLOverride;
- (long long)accessType;
- (id)actionGroups;
- (id)addValueURL;
- (id)appURLScheme;
- (bool)areCredentialsStoredInKML;
- (unsigned long long)associatedAccountFeatureIdentifier;
- (id)associatedAccountServiceAccountIdentifier;
- (id)associatedApplicationIdentifiers;
- (id)associatedWebDomains;
- (id)autoTopUpBalanceIdentifiers;
- (id)autoTopUpMerchantTokenIdentifier;
- (id)auxiliaryRegistrationRequirements;
- (id)availableActions;
- (bool)availableForAutomaticPresentationUsingBeaconContext;
- (bool)availableForAutomaticPresentationUsingInAppOrWebContext;
- (bool)availableForAutomaticPresentationUsingVASContext;
- (bool)canPerformAction:(id)arg1 unableReason:(unsigned long long*)arg2 displayableError:(id*)arg3;
- (long long)cardType;
- (id)cobrandName;
- (unsigned long long)contactlessActivationState;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)customerServiceIdentifier;
- (id)deviceAccountIdentifier;
- (id)deviceAccountNumberSuffix;
- (id)deviceContactlessPaymentApplications;
- (id)deviceInAppPaymentApplications;
- (id)devicePassIdentifier;
- (id)devicePaymentApplications;
- (id)devicePrimaryBarcodePaymentApplication;
- (id)devicePrimaryContactlessPaymentApplication;
- (id)devicePrimaryInAppPaymentApplication;
- (id)devicePrimaryPaymentApplication;
- (id)deviceTransactionSourceIdentifiers;
- (id)dynamicLayerConfiguration;
- (long long)effectiveContactlessPaymentApplicationState;
- (id)eligibleExpressUpgradeRequestsForDeviceClass:(id)arg1 deviceSEIDs:(id)arg2 deviceVersion:(id)arg3 technologyTest:(id /* block */)arg4;
- (void)encodeWithCoder:(id)arg1;
- (bool)hadMerchantTokens;
- (bool)hasActiveVirtualCard;
- (bool)hasActiveVirtualCardAccordingToWebService:(id)arg1;
- (bool)hasAssociatedPeerPaymentAccount;
- (bool)hasContactlessDevicePaymentApplicationsAvailable;
- (bool)hasCredentials;
- (bool)hasDeviceTransactionSourceIdentifier:(id)arg1;
- (bool)hasImmediateAutomaticSelectionCriterion;
- (bool)hasLegacyBalanceModel;
- (bool)hasMerchantTokens;
- (long long)identityType;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1 bundle:(id)arg2;
- (bool)isAccessPass;
- (bool)isAppleBalancePass;
- (bool)isAppleCardPass;
- (bool)isAutoTopEnabled;
- (bool)isAutoTopUpBalance:(id)arg1;
- (bool)isCarKeyPass;
- (bool)isChinaTransitCredential;
- (bool)isCobranded;
- (bool)isContactlessPaymentSupportedForTransitNetworks:(id)arg1;
- (bool)isDevicePrimaryPaymentApplicationPersonalized;
- (bool)isEMoneyPass;
- (bool)isEqualToPassIncludingMetadata:(id)arg1;
- (bool)isHomeKeyPass;
- (bool)isIdentityPass;
- (bool)isOctopusPass;
- (bool)isPayLaterPass;
- (bool)isPaymentOptionSelectable;
- (bool)isPeerPaymentPass;
- (bool)isPrepaidPass;
- (bool)isPrivateLabel;
- (bool)isShellPass;
- (bool)isStoredValuePass;
- (bool)isSuicaPass;
- (bool)isTransitPass;
- (bool)isUserDeletable;
- (id)iso18013BlobsForSecureElementIdentifiers:(id)arg1;
- (id)iso18013BlobsMetdataForSecureElementIdentifiers:(id)arg1;
- (id)issuerAdministrativeAreaCode;
- (id)issuerCountryCode;
- (id)localizedSuspendedReason;
- (id)longTermPrivacyKeyGroupIdentifier;
- (id)messagePushTopic;
- (id)messageServiceRegistrationURL;
- (id)messageServiceURL;
- (bool)needsHardcodedReminderOptions;
- (id)notificationCenterTitle;
- (id)originalProvisioningDate;
- (id)pairedTerminalIdentifier;
- (id)partnerAccountIdentifier;
- (long long)passActivationState;
- (id)paymentApplicationForAID:(id)arg1;
- (id)paymentApplications;
- (id)paymentApplicationsForSecureElementIdentifiers:(id)arg1;
- (long long)paymentType;
- (id)peerPaymentBalance;
- (bool)preventsWalletDeletion;
- (id)primaryAccountIdentifier;
- (id)primaryAccountNumberSuffix;
- (id)primaryPaymentApplicationForSecureElementIdentifiers:(id)arg1;
- (id)provisioningMetadata;
- (bool)requiresFelicaSecureElement;
- (bool)requiresTransferSerialNumberBasedProvisioning;
- (void)sanitizePaymentApplications;
- (id)sanitizedDeviceAccountNumber;
- (id)sanitizedPrimaryAccountName;
- (id)sanitizedPrimaryAccountNumber;
- (id)seBlobsForSecureElementIdentifiers:(id)arg1;
- (void)setAppURLScheme:(id)arg1;
- (void)setAssociatedAccountFeatureIdentifier:(unsigned long long)arg1;
- (void)setAssociatedAccountServiceAccountIdentifier:(id)arg1;
- (void)setAssociatedApplicationIdentifiers:(id)arg1;
- (void)setAssociatedWebDomains:(id)arg1;
- (void)setAuxiliaryRegistrationRequirements:(id)arg1;
- (void)setAvailableActions:(id)arg1;
- (void)setCardType:(long long)arg1;
- (void)setCobrandName:(id)arg1;
- (void)setCobranded:(bool)arg1;
- (void)setCustomerServiceIdentifier:(id)arg1;
- (void)setDeviceInAppPaymentApplications:(id)arg1;
- (void)setDevicePaymentApplications:(id)arg1;
- (void)setDevicePrimaryBarcodePaymentApplication:(id)arg1;
- (void)setDevicePrimaryContactlessPaymentApplication:(id)arg1;
- (void)setDevicePrimaryInAppPaymentApplication:(id)arg1;
- (void)setDevicePrimaryPaymentApplication:(id)arg1;
- (void)setHasAssociatedPeerPaymentAccount:(bool)arg1;
- (void)setIssuerAdministrativeAreaCode:(id)arg1;
- (void)setIssuerCountryCode:(id)arg1;
- (void)setLocalizedSuspendedReason:(id)arg1;
- (void)setMessagePushTopic:(id)arg1;
- (void)setMessageServiceRegistrationURL:(id)arg1;
- (void)setMessageServiceURL:(id)arg1;
- (void)setOriginalProvisioningDate:(id)arg1;
- (void)setPartnerAccountIdentifier:(id)arg1;
- (void)setPaymentApplications:(id)arg1;
- (void)setPaymentOptionSelectable:(bool)arg1;
- (void)setPeerPaymentBalance:(id)arg1;
- (void)setPrimaryAccountIdentifier:(id)arg1;
- (void)setPrimaryAccountNumberSuffix:(id)arg1;
- (void)setProvisioningMetadata:(id)arg1;
- (void)setRequiresTransferSerialNumberBasedProvisioning:(bool)arg1;
- (void)setSanitizedPrimaryAccountName:(id)arg1;
- (void)setSanitizedPrimaryAccountNumber:(id)arg1;
- (void)setShellPass:(bool)arg1;
- (void)setShippingAddressSeed:(id)arg1;
- (void)setSpeakableMake:(id)arg1;
- (void)setSpeakableModel:(id)arg1;
- (void)setSupportedSiriIntents:(id)arg1;
- (void)setSupportsDPANNotifications:(bool)arg1;
- (void)setSupportsDefaultCardSelection:(bool)arg1;
- (void)setSupportsFPANNotifications:(bool)arg1;
- (void)setSupportsPeerPayment:(bool)arg1;
- (void)setSupportsSerialNumberBasedProvisioning:(bool)arg1;
- (void)setTopLeftBackgroundTitle:(id)arg1;
- (void)setTopRightBackgroundTitle:(id)arg1;
- (void)setTransactionPushTopic:(id)arg1;
- (void)setTransactionServiceRegistrationURL:(id)arg1;
- (void)setTransactionServiceURL:(id)arg1;
- (void)setTransactionSourceIdentifier:(id)arg1;
- (id)shippingAddressSeed;
- (bool)shouldDisplayDeviceAssessmentEducationAccordingToService:(id)arg1;
- (bool)shouldIgnoreTransactionUpdatesSwitch;
- (bool)shouldSuppressNoChargeAmount;
- (id)sortedPaymentApplications:(id)arg1 ascending:(bool)arg2;
- (id)speakableMake;
- (id)speakableModel;
- (unsigned long long)supportedRadioTechnologies;
- (id)supportedSiriIntents;
- (bool)supportsBarcodePayment;
- (bool)supportsDPANNotifications;
- (bool)supportsDefaultCardSelection;
- (bool)supportsDeviceAssessmentAccordingToService:(id)arg1;
- (bool)supportsFPANNotifications;
- (bool)supportsFeatureForCurrentDevice:(unsigned long long)arg1;
- (bool)supportsOnlyTransit;
- (bool)supportsPeerPayment;
- (bool)supportsSerialNumberBasedProvisioning;
- (bool)supportsVirtualCardNumber;
- (bool)supportsVirtualCardNumberAccordingToWebService:(id)arg1;
- (bool)supportsWebPaymentMode:(long long)arg1 withExclusionList:(id)arg2;
- (bool)supportsWebPaymentMode:(long long)arg1 withExclusionList:(id)arg2 clientOSVersion:(id)arg3;
- (id)topLeftBackgroundTitle;
- (id)topRightBackgroundTitle;
- (id)transactionPushTopic;
- (id)transactionServiceRegistrationURL;
- (id)transactionServiceURL;
- (id)transactionSourceIdentifier;
- (unsigned long long)transitCommutePlanType;
- (id)transitCommutePlans;
- (id)transitProperties;
- (void)updateDevicePaymentApplicationsWithSecureElementIdentifiers:(id)arg1;
- (id)upgradeRequests;
- (id)virtualCardSuffix;

// Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit

- (bool)npkExclusivelyTransactsOverBluetooth;
- (bool)npkExclusivelyTransactsOverNFC;
- (unsigned long long)npkLinkedAccountFeatureIdentifier;
- (bool)npkProvidesLinkedAccountFeatureIdentifier;
- (id)npkSubcredentials;
- (bool)npkSupportUWBSecureRanging;
- (bool)npkSupportsBluetooth;
- (bool)npkSupportsNFC;

@end
