
@interface _SFAccountPickerTableViewController : _SFAccountTableViewController <PMGeneratedPasswordsLogDelegate, SFAccountDetailViewControllerDelegate, SFAccountTableViewCellDelegate, SFAddSavedAccountViewControllerDelegate, SFAppAutoFillOneTimeCodeProviderObserver, _SFTableLinkableFooterViewDelegate> {
    UIBarButtonItem * _addNavigationBarItem;
    SFAddSavedAccountViewController * _addPasswordViewController;
    LAContext * _authenticatedContext;
    WBSAuthenticationServicesAgentProxy * _authenticationServicesAgentProxy;
    NSArray * _autoFillPasskeys;
    SFAccountPickerConfiguration * _configuration;
    <_SFAccountPickerTableViewControllerDelegate> * _delegate;
    SFAccountDetailViewController * _detailViewController;
    bool  _didPresentAddAccountViewControllerFromGeneratedPasswords;
    WBSGeneratedPassword * _generatedPasswordBeingTransformedIntoSavedAccount;
    bool  _hasMatchingGeneratedPasswords;
    NSIndexPath * _indexPathOfRowShowingDetailView;
    NSMutableArray * _matchingSavedAccounts;
    WBSPasskeyAutoFillFromNearbyDeviceOptions * _passkeyNearbyDeviceOptions;
    NSMutableArray * _savedAccountWithUsablePasskeys;
    NSMutableArray * _savedAccounts;
    NSMutableArray * _savedAccountsMatchingHintStrings;
    long long  _sectionForAllPasswords;
    long long  _sectionForPasskeys;
    long long  _sectionForPasswordsMatchingHintStrings;
    long long  _sectionForVerificationCodes;
    SFAppAutoFillOneTimeCodeProvider * _verificationCodeProvider;
    NSArray * _verificationCodes;
}

@property (nonatomic, retain) LAContext *authenticatedContext;
@property (nonatomic, readonly) SFAccountPickerConfiguration *configuration;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <_SFAccountPickerTableViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) WBSSavedAccount *savedAccountToRemoveAfterCompletedUpgradeInDetailView;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_accountStoreDidChange;
- (void)_addNavigationBarItemTapped:(id)arg1;
- (id)_appIconForVerificationCode:(id)arg1;
- (id)_bundleIdentifierForVerificationCodeSource:(long long)arg1;
- (void)_cancel;
- (id)_cellConfigurationForVerificationCodeAtIndexPath:(id)arg1;
- (void)_consumeAndFillVerificationCode:(id)arg1;
- (void)_deleteSavedAccountAtIndexPath:(id)arg1;
- (void)_didPickSavedAccountForPassword:(id)arg1;
- (void)_fillPasswordForSavedAccount:(id)arg1;
- (void)_fillUsernameForSavedAccount:(id)arg1;
- (void)_fillVerificationCodeForSavedAccount:(id)arg1;
- (id)_generatedPasswordsDomainHintString;
- (void)_generatedPasswordsStoreDidChange;
- (void)_presentAddPasswordViewController;
- (void)_presentAlertToConfirmDeletingAccountsAtIndexPath:(id)arg1;
- (void)_presentErrorAlertWithString:(id)arg1;
- (void)_presentGeneratedPasswordsViewController;
- (void)_reloadSavedAccountsWithCompletionHandler:(id /* block */)arg1;
- (void)_reloadVerificationCodesIfNeeded;
- (void)_removeSavedAccount:(id)arg1 modifyingAccountStore:(bool)arg2;
- (long long)_rowTypeForIndexPath:(id)arg1;
- (id)_savedAccountForIndexPath:(id)arg1;
- (bool)_shouldShowAutoFillPasskeys;
- (bool)_shouldShowPasswordsMatchingHintStringsSection;
- (bool)_shouldUseEmptyHeaderFooterHeightInSection:(long long)arg1;
- (void)_showAccountDetailsForSavedAccountAtIndexPath:(id)arg1;
- (void)_updateMatchingGeneratedPasswordsState;
- (void)_updateMatchingPasswords;
- (void)_updateNavigationItemTitleAndPrompt;
- (void)_updateSections;
- (void)accountDetailViewController:(id)arg1 didMoveSavedAccountToRecentlyDeleted:(id)arg2;
- (void)accountDetailViewController:(id)arg1 fillPasswordForSavedAccount:(id)arg2;
- (void)accountDetailViewController:(id)arg1 fillUsernameForSavedAccount:(id)arg2;
- (void)accountDetailViewController:(id)arg1 fillVerificationCodeForSavedAccount:(id)arg2;
- (void)addSavedAccountViewControllerDidFinish:(id)arg1 withSavedAccount:(id)arg2;
- (id)authenticatedContext;
- (id)configuration;
- (void)dealloc;
- (id)delegate;
- (void)handleContextMenuDeleteForIndexPath:(id)arg1;
- (void)handleIconDidUpdateForDomain:(id)arg1;
- (id)iconControllerForAddSavedAccountDetailViewController:(id)arg1;
- (id)initWithConfiguration:(id)arg1;
- (void)linkableFooterViewDidInteractWithLink:(id)arg1;
- (void)newAutoFillablePasskeysAvailable:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)oneTimeCodeProviderReceivedCode:(id)arg1;
- (void)passwordManagerLogViewControllerWantsToDismiss;
- (void)passwordManagerLogViewControllerWantsToSaveGeneratedPassword:(id)arg1;
- (void)reloadTable;
- (void)searchPatternDidUpdate;
- (void)setAuthenticatedContext:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
