
@interface SFFormAutocompleteState : NSObject <CNContactPickerDelegate, SFAppAutoFillOneTimeCodeProviderObserver, SFContactAutoFillViewControllerFiller, _ASCredentialAuthenticationViewControllerDelegate, _ASCredentialListViewControllerDelegate, _SFCreditCardCaptureViewControllerDelegate> {
    bool  _URLIsAllowedByWhiteList;
    long long  _action;
    WBSAuthenticationServicesAgentProxy * _authenticationServicesAgentProxy;
    _SFFormAutoFillController * _autoFillController;
    NSArray * _cachedCredentialMatches;
    NSArray * _cachedExternalCredentialIdentities;
    NSArray * _cachedRelatedCredentialMatches;
    id /* block */  _credentialMatchesCompletionHandler;
    id /* block */  _creditCardCaptureCompletionHandler;
    SFCreditCardFillingViewController * _creditCardViewController;
    id /* block */  _customAutoFillContactCompletionHandler;
    _SFFormDataController * _dataController;
    id /* block */  _displayOtherContactsCompletionHandler;
    UIView * _emptyInputView;
    id /* block */  _externalCredentialListCompletionHandler;
    _ASCredentialAuthenticationViewController * _externalCredentialViewController;
    bool  _fetchingLoginCredentialSuggestions;
    WBSFormMetadata * _formMetadata;
    unsigned long long  _formType;
    NSDictionary * _formValues;
    SFFormAutoFillFrameHandle * _frame;
    bool  _gatheringFormValues;
    bool  _hasDeterminedIfURLIsAllowedByWhiteList;
    bool  _hasNotedThatTextDidChangeInPasswordField;
    WBSHideMyEmailRecord * _hideMyEmailRecord;
    _SFFormAutoFillInputSession * _inputSession;
    bool  _invalidated;
    WBSFormAutoFillMetadataCorrector * _metadataCorrector;
    WBSMultiRoundAutoFillManager * _multiRoundAutoFillManager;
    bool  _performingPageLevelAutoFill;
    NSString * _prefixForSuggestions;
    long long  _quickTypeBarTrailingButtonPurpose;
    bool  _submitExternalCredential;
    WBSFormControlMetadata * _textFieldMetadata;
}

@property (nonatomic) long long action;
@property (nonatomic, readonly) bool currentTextFieldLooksLikeCardSecurityCodeFieldButNotCardNumberOrCardholderField;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) SFFormAutoFillFrameHandle *frame;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) _SFFormAutoFillInputSession *inputSession;
@property (nonatomic, readonly) WBSMultiRoundAutoFillManager *multiRoundAutoFillManager;
@property (nonatomic, readonly) bool shouldOfferToAutoFillCreditCardData;
@property (readonly) Class superclass;
@property (nonatomic, readonly) WBSFormControlMetadata *textFieldMetadata;

+ (void)_getMatchesFromFormProtectionSpace:(id)arg1 matchesFromOtherProtectionSpaces:(id)arg2 withFormURL:(id)arg3 credentialMatches:(id)arg4 lastGeneratedPassword:(id)arg5 currentUser:(id)arg6 currentPassword:(id)arg7 forUserNamesOnly:(bool)arg8;
+ (bool)_shouldSaveCredentialsInProtectionSpace:(id)arg1 savedAccountContext:(id)arg2;

- (void).cxx_destruct;
- (long long)_actionForLoginForm;
- (id)_actionForPresentingPasswordManagerExtension:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)_addHideMyEmailSuggestionsIfNecessary:(id)arg1 hideMyEmailRecord:(id)arg2;
- (void)_addPasswordsAutoFillSuggestionToSuggestions:(id)arg1 forPurpose:(long long)arg2;
- (void)_autoFillDisplayData:(id)arg1 setAutoFilled:(bool)arg2;
- (void)_autoFillFormWithUsername:(id)arg1;
- (void)_autoFillHideMyEmailRecord:(id)arg1;
- (void)_autoFillSingleCreditCardData:(long long)arg1;
- (void)_autoFillWithSet:(id)arg1;
- (id)_bestTextFieldMetadataForMetadata:(id)arg1;
- (id)_cachedPotentialCredentialMatches;
- (bool)_canAutoFillCreditCardData;
- (void)_clearAutoFilledCreditCardFieldsAndShowAllCreditCards;
- (void)_clearCachedCredentials;
- (void)_completePasskeyAssertionWithCredential:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)_correctedFormMetadata:(id)arg1;
- (id)_createCreditCardHeaderViewControllerForEscapeHatchAlertControllerForCard:(id)arg1;
- (void)_fetchPotentialCredentialMatchesWithCompletion:(id /* block */)arg1;
- (void)_fillASPasswordCredential:(id)arg1 needsAuthentication:(bool)arg2 setAutoFilled:(bool)arg3 submitForm:(bool)arg4;
- (void)_fillCredential:(id)arg1 setAutoFilled:(bool)arg2 setAsDefaultCredential:(bool)arg3 focusFieldAfterFilling:(bool)arg4 submitForm:(bool)arg5;
- (void)_fillCredentialAfterAuthenticationIfNeeded:(id)arg1 setAsDefaultCredential:(bool)arg2 submitForm:(bool)arg3;
- (void)_fillCredentialIdentity:(id)arg1 submitForm:(bool)arg2;
- (void)_fillCreditCardData:(id)arg1;
- (void)_fillCreditCardDataAfterAuthenticationIfNeeded:(id)arg1;
- (void)_fillOneTimeCodeAfterAuthenticationIfNeeded:(id)arg1 inFrame:(id)arg2 shouldSubmit:(bool)arg3;
- (void)_fillSavedAccount:(id)arg1 setAutoFilled:(bool)arg2 setAsDefaultCredential:(bool)arg3 focusFieldAfterFilling:(bool)arg4 submitForm:(bool)arg5;
- (void)_fillSavedAccountMatchAfterAuthenticationIfNeeded:(id)arg1 setAsDefaultCredential:(bool)arg2 submitForm:(bool)arg3;
- (void)_fillSingleCreditCardDataValue:(id)arg1 creditCardDataType:(long long)arg2;
- (void)_finishPageLevelAutoFillWithResult:(long long)arg1;
- (void)_gatherAndShowAddressBookAutoFillSuggestions;
- (void)_gatherAndShowAddressBookAutoFillSuggestionsWithCorrections;
- (void)_gatherFormValues;
- (void)_gatherFormValuesWithCompletionHandler:(id /* block */)arg1;
- (void)_generateAndSuggestPasswordWithCompletionHandler:(id /* block */)arg1;
- (void)_getLoginFormUser:(id*)arg1 password:(id*)arg2 userIsAutoFilled:(bool*)arg3 passwordIsAutoFilled:(bool*)arg4;
- (void)_getMatchingKeychainCredentialsIncludingCredentialsWithEmptyUsernames:(bool)arg1 withCompletion:(id /* block */)arg2;
- (void)_getShouldOfferForgetPassword:(bool*)arg1 savePassword:(bool*)arg2;
- (bool)_hasMatchWithUser:(id)arg1 password:(id)arg2;
- (id)_hideMyEmailCreationSuggestion;
- (id)_hideMyEmailSuggestionForRecord:(id)arg1;
- (id)_messageForPageLevelAutoFillNotAvailableAlertForResult:(long long)arg1;
- (void)_offerToAutoFillContact;
- (void)_offerToAutoFillFromAvailableOneTimeCodes;
- (void)_offerToAutoFillFromPotentialCredentialMatches;
- (void)_offerToForgetSavedAccount:(id)arg1 completionHandler:(id /* block */)arg2;
- (long long)_passwordGenerationAssistanceAction;
- (bool)_passwordGenerationAssistanceAutoFillButtonEnabled;
- (void)_performAutoFill;
- (void)_performPageLevelContactAutoFill;
- (void)_performPageLevelCredentialAutoFill;
- (void)_presentContactsAccessSettingsAlert;
- (void)_presentCredentialListForExtension:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)_presentViewController:(id)arg1 presentingViewController:(id)arg2 animated:(bool)arg3 completion:(id /* block */)arg4;
- (void)_provisionHideMyEmailRecord;
- (void)_setShowingKeyboardInputView:(bool)arg1;
- (void)_setUpMultiRoundAutoFillManagerIfNecessary;
- (void)_setUserAndPasswordFieldsAutoFilled:(bool)arg1 clearPasswordField:(bool)arg2;
- (bool)_shouldAllowExternalPasswordAutoFillOnURL:(id)arg1;
- (bool)_shouldAllowGeneratedPassword;
- (bool)_shouldOfferCreditCardDataAfterUserHasFilledCreditCardData:(id)arg1;
- (bool)_shouldShowPasswordOptions;
- (bool)_shouldUsePasswordGenerationAssistanceForTextField;
- (void)_showCreditCardDataSuggestionsAfterUserHasFilledCreditCardData;
- (void)_showOtherContactOptions;
- (void)_showPageLevelAutoFillNotAvailableAlertForResult:(long long)arg1;
- (id)_sortedSingleCreditCardDataArray:(id)arg1;
- (void)_startHideMyEmailRecordUpdate;
- (void)_suggestLoginCredentialsShowingQuickTypeKey:(bool)arg1;
- (void)_suggestPasswordForNewAccountOrChangePasswordForm;
- (bool)_suggestUsernamesForRegistrationIfPossible:(unsigned long long)arg1;
- (id)_suggestionsForAutoFillDisplayData:(id)arg1;
- (void)_switchToCustomInputViewWithMatches:(id)arg1 contact:(id)arg2;
- (void)_textDidChangeInForm:(id)arg1 textField:(id)arg2;
- (bool)_textFieldIsEmptyPasswordField;
- (id)_textSuggestionForCredentialDisplayData:(id)arg1 submitForm:(bool)arg2;
- (id)_textSuggestionForExternalCredentialIdentity:(id)arg1 submitForm:(bool)arg2;
- (id)_titleForPageLevelAutoFillNotAvailableAlertForResult:(long long)arg1;
- (void)_updateAutoFillActionToCaptureCreditCardAndFill;
- (void)_updateCreditCardAutoFillAction;
- (void)_updateSuggestions:(unsigned long long)arg1;
- (id)_viewControllerToPresentFrom;
- (long long)action;
- (void)autoFill;
- (void)autoFillTextSuggestion:(id)arg1;
- (void)captureCreditCardDataWithCameraAndFill;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (void)credentialAuthenticationViewController:(id)arg1 didFinishWithCredential:(id)arg2 error:(id)arg3 completion:(id /* block */)arg4;
- (void)credentialAuthenticationViewController:(id)arg1 didFinishWithPasskeyAssertionCredential:(id)arg2 error:(id)arg3 completion:(id /* block */)arg4;
- (void)credentialAuthenticationViewController:(id)arg1 didFinishWithPasskeyRegistrationCredential:(id)arg2 error:(id)arg3 completion:(id /* block */)arg4;
- (void)credentialListViewController:(id)arg1 didFinishWithCredential:(id)arg2 completion:(id /* block */)arg3;
- (void)credentialListViewController:(id)arg1 didFinishWithPasskeyAssertionCredential:(id)arg2 completion:(id /* block */)arg3;
- (void)creditCardCaptureViewController:(id)arg1 didCaptureCreditCard:(id)arg2;
- (void)creditCardCaptureViewControllerDidCancel:(id)arg1;
- (bool)currentTextFieldLooksLikeCardSecurityCodeFieldButNotCardNumberOrCardholderField;
- (void)dealloc;
- (void)dismissCustomAutoFill;
- (id)externalCredentialIdentities;
- (id)frame;
- (void)getTextSuggestionForStreamlinedAutoFillWithCredentialIdentity:(id)arg1 completion:(id /* block */)arg2;
- (id)initWithFrame:(id)arg1 form:(id)arg2 textField:(id)arg3 inputSession:(id)arg4 autoFillController:(id)arg5;
- (id)inputSession;
- (void)invalidate;
- (id)multiRoundAutoFillManager;
- (void)newAutoFillablePasskeysAvailable:(id)arg1;
- (void)oneTimeCodeProviderReceivedCode:(id)arg1;
- (void)performAutoFillWithMatchSelections:(id)arg1 doNotFill:(id)arg2 contact:(id)arg3;
- (void)performPageLevelAutoFill;
- (void)presentUIForPasswordCredentialAuthenticationViewController:(id)arg1;
- (void)presentUnavailableVirtualCardAlert;
- (void)setAction:(long long)arg1;
- (bool)shouldOfferToAutoFillCreditCardData;
- (void)showAllPasswordsButtonTapped;
- (void)textDidChangeInFrame:(id)arg1 form:(id)arg2 textField:(id)arg3;
- (id)textFieldMetadata;
- (void)updateAutoFillButton;
- (void)updateCachedFormMetadataAfterFilling:(id)arg1;
- (void)updateSuggestions;

@end
