
@interface CUSystemMonitor : NSObject {
    bool  _activateCalled;
    bool  _activateCompleted;
    id /* block */  _bluetoothAddressChangedHandler;
    id /* block */  _callChangedHandler;
    id /* block */  _clamshellModeChangedHandler;
    id /* block */  _consoleUserChangedHandler;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id /* block */  _familyUpdatedHandler;
    id /* block */  _firstUnlockHandler;
    id /* block */  _foregroundAppChangedHandler;
    bool  _invalidateCalled;
    bool  _invalidateCalled2;
    id /* block */  _invalidationHandler;
    NSBundle * _locationVisitsBundle;
    id /* block */  _locationVisitsChangedHandler;
    id /* block */  _manateeChangedHandler;
    id /* block */  _meDeviceChangedHandler;
    id /* block */  _motionHandler;
    id /* block */  _netFlagsChangedHandler;
    id /* block */  _netInterfacesChangedHandler;
    id /* block */  _powerUnlimitedChangedHandler;
    id /* block */  _primaryAppleIDChangedHandler;
    id /* block */  _primaryIPChangedHandler;
    id /* block */  _primaryNetworkChangedHandler;
    id /* block */  _regionChangedHandler;
    id /* block */  _rotatingIdentifierChangedHandler;
    id /* block */  _screenLockedChangedHandler;
    id /* block */  _screenOnChangedHandler;
    id /* block */  _screenSaverChangedHandler;
    id /* block */  _systemLockStateChangedHandler;
    id /* block */  _systemNameChangedHandler;
    id /* block */  _systemUIChangedHandler;
    id /* block */  _wifiStateChangedHandler;
}

@property (readonly) int activeCallCount;
@property (readonly) struct { unsigned char x1[6]; } bluetoothAddress48;
@property (copy) id /* block */ bluetoothAddressChangedHandler;
@property (readonly, copy) NSData *bluetoothAddressData;
@property (copy) id /* block */ callChangedHandler;
@property (readonly) int callCountIncomingConnected;
@property (readonly) int callCountIncomingUnconnected;
@property (readonly) int callCountOutgoingConnected;
@property (readonly) int callCountOutgoingUnconnected;
@property (readonly) unsigned int callFlags;
@property (readonly) bool clamshellMode;
@property (copy) id /* block */ clamshellModeChangedHandler;
@property (readonly) int connectedCallCount;
@property (copy) id /* block */ consoleUserChangedHandler;
@property (readonly) unsigned int consoleUserID;
@property (readonly, copy) NSString *consoleUserName;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (readonly, copy) NSArray *familyMembers;
@property (copy) id /* block */ familyUpdatedHandler;
@property (copy) id /* block */ firstUnlockHandler;
@property (nonatomic, readonly) bool firstUnlocked;
@property (nonatomic, readonly) bool firstUnlockedSync;
@property (readonly, copy) NSString *foregroundAppBundleID;
@property (copy) id /* block */ foregroundAppChangedHandler;
@property (nonatomic, copy) id /* block */ invalidationHandler;
@property (retain) NSBundle *locationVisitsBundle;
@property (copy) id /* block */ locationVisitsChangedHandler;
@property (readonly) unsigned int locationVisitsFlags;
@property (readonly) bool manateeAvailable;
@property (copy) id /* block */ manateeChangedHandler;
@property (readonly) int manateeState;
@property (copy) id /* block */ meDeviceChangedHandler;
@property (readonly, copy) NSString *meDeviceFMFDeviceID;
@property (readonly, copy) NSString *meDeviceIDSDeviceID;
@property (readonly) bool meDeviceIsMe;
@property (readonly, copy) NSString *meDeviceName;
@property (readonly) bool meDeviceValid;
@property (readonly) unsigned int motionFlags;
@property (copy) id /* block */ motionHandler;
@property (readonly) int motionOrientation;
@property (readonly) unsigned int netFlags;
@property (copy) id /* block */ netFlagsChangedHandler;
@property (copy) id /* block */ netInterfacesChangedHandler;
@property (readonly) bool powerUnlimited;
@property (copy) id /* block */ powerUnlimitedChangedHandler;
@property (readonly, copy) NSString *primaryAppleID;
@property (copy) id /* block */ primaryAppleIDChangedHandler;
@property (readonly) bool primaryAppleIDIsHSA2;
@property (copy) id /* block */ primaryIPChangedHandler;
@property (nonatomic, readonly) union { struct sockaddr { unsigned char x_1_1_1; unsigned char x_1_1_2; BOOL x_1_1_3[14]; } x1; struct sockaddr_in { unsigned char x_2_1_1; unsigned char x_2_1_2; unsigned short x_2_1_3; struct in_addr { unsigned int x_4_2_1; } x_2_1_4; BOOL x_2_1_5[8]; } x2; struct sockaddr_in6 { unsigned char x_3_1_1; unsigned char x_3_1_2; unsigned short x_3_1_3; unsigned int x_3_1_4; struct in6_addr { union { unsigned char x_1_3_1[16]; unsigned short x_1_3_2[8]; unsigned int x_1_3_3[4]; } x_5_2_1; } x_3_1_5; unsigned int x_3_1_6; } x3; } primaryIPv4Addr;
@property (nonatomic, readonly) union { struct sockaddr { unsigned char x_1_1_1; unsigned char x_1_1_2; BOOL x_1_1_3[14]; } x1; struct sockaddr_in { unsigned char x_2_1_1; unsigned char x_2_1_2; unsigned short x_2_1_3; struct in_addr { unsigned int x_4_2_1; } x_2_1_4; BOOL x_2_1_5[8]; } x2; struct sockaddr_in6 { unsigned char x_3_1_1; unsigned char x_3_1_2; unsigned short x_3_1_3; unsigned int x_3_1_4; struct in6_addr { union { unsigned char x_1_3_1[16]; unsigned short x_1_3_2[8]; unsigned int x_1_3_3[4]; } x_5_2_1; } x_3_1_5; unsigned int x_3_1_6; } x3; } primaryIPv6Addr;
@property (copy) id /* block */ primaryNetworkChangedHandler;
@property (readonly, copy) NSString *primaryNetworkSignature;
@property (copy) id /* block */ regionChangedHandler;
@property (readonly, copy) NSString *regionISOCountryCode;
@property (readonly, copy) NSString *regionMobileCountryCode;
@property (readonly, copy) NSString *regionRoutineCountry;
@property (readonly, copy) NSString *regionRoutineState;
@property (readonly) struct { unsigned char x1[6]; } rotatingIdentifier48;
@property (copy) id /* block */ rotatingIdentifierChangedHandler;
@property (readonly, copy) NSData *rotatingIdentifierData;
@property (readonly) bool screenLocked;
@property (copy) id /* block */ screenLockedChangedHandler;
@property (readonly) bool screenLockedSync;
@property (readonly) bool screenOn;
@property (copy) id /* block */ screenOnChangedHandler;
@property (readonly) bool screenSaverActive;
@property (copy) id /* block */ screenSaverChangedHandler;
@property (nonatomic, readonly) int systemLockState;
@property (copy) id /* block */ systemLockStateChangedHandler;
@property (nonatomic, readonly) int systemLockStateSync;
@property (readonly, copy) NSString *systemName;
@property (copy) id /* block */ systemNameChangedHandler;
@property (copy) id /* block */ systemUIChangedHandler;
@property (readonly) unsigned int systemUIFlags;
@property (nonatomic, readonly) unsigned int wifiFlags;
@property (nonatomic, readonly) int wifiState;
@property (copy) id /* block */ wifiStateChangedHandler;

- (void).cxx_destruct;
- (void)activateWithCompletion:(id /* block */)arg1;
- (int)activeCallCount;
- (struct { unsigned char x1[6]; })bluetoothAddress48;
- (id /* block */)bluetoothAddressChangedHandler;
- (id)bluetoothAddressData;
- (id /* block */)callChangedHandler;
- (int)callCountIncomingConnected;
- (int)callCountIncomingUnconnected;
- (int)callCountOutgoingConnected;
- (int)callCountOutgoingUnconnected;
- (unsigned int)callFlags;
- (bool)clamshellMode;
- (id /* block */)clamshellModeChangedHandler;
- (int)connectedCallCount;
- (id /* block */)consoleUserChangedHandler;
- (unsigned int)consoleUserID;
- (id)consoleUserName;
- (id)dispatchQueue;
- (id)familyMembers;
- (id /* block */)familyUpdatedHandler;
- (id /* block */)firstUnlockHandler;
- (bool)firstUnlocked;
- (bool)firstUnlockedSync;
- (void)forceManateeStateRefresh;
- (id)foregroundAppBundleID;
- (id /* block */)foregroundAppChangedHandler;
- (id)init;
- (void)invalidate;
- (id /* block */)invalidationHandler;
- (id)locationVisitsBundle;
- (id /* block */)locationVisitsChangedHandler;
- (unsigned int)locationVisitsFlags;
- (bool)manateeAvailable;
- (id /* block */)manateeChangedHandler;
- (int)manateeState;
- (id /* block */)meDeviceChangedHandler;
- (id)meDeviceFMFDeviceID;
- (id)meDeviceIDSDeviceID;
- (bool)meDeviceIsMe;
- (id)meDeviceName;
- (bool)meDeviceValid;
- (unsigned int)motionFlags;
- (id /* block */)motionHandler;
- (int)motionOrientation;
- (unsigned int)netFlags;
- (id /* block */)netFlagsChangedHandler;
- (id /* block */)netInterfacesChangedHandler;
- (bool)powerUnlimited;
- (id /* block */)powerUnlimitedChangedHandler;
- (id)primaryAppleID;
- (id /* block */)primaryAppleIDChangedHandler;
- (bool)primaryAppleIDIsHSA2;
- (id /* block */)primaryIPChangedHandler;
- (union { struct sockaddr { unsigned char x_1_1_1; unsigned char x_1_1_2; BOOL x_1_1_3[14]; } x1; struct sockaddr_in { unsigned char x_2_1_1; unsigned char x_2_1_2; unsigned short x_2_1_3; struct in_addr { unsigned int x_4_2_1; } x_2_1_4; BOOL x_2_1_5[8]; } x2; struct sockaddr_in6 { unsigned char x_3_1_1; unsigned char x_3_1_2; unsigned short x_3_1_3; unsigned int x_3_1_4; struct in6_addr { union { unsigned char x_1_3_1[16]; unsigned short x_1_3_2[8]; unsigned int x_1_3_3[4]; } x_5_2_1; } x_3_1_5; unsigned int x_3_1_6; } x3; })primaryIPv4Addr;
- (union { struct sockaddr { unsigned char x_1_1_1; unsigned char x_1_1_2; BOOL x_1_1_3[14]; } x1; struct sockaddr_in { unsigned char x_2_1_1; unsigned char x_2_1_2; unsigned short x_2_1_3; struct in_addr { unsigned int x_4_2_1; } x_2_1_4; BOOL x_2_1_5[8]; } x2; struct sockaddr_in6 { unsigned char x_3_1_1; unsigned char x_3_1_2; unsigned short x_3_1_3; unsigned int x_3_1_4; struct in6_addr { union { unsigned char x_1_3_1[16]; unsigned short x_1_3_2[8]; unsigned int x_1_3_3[4]; } x_5_2_1; } x_3_1_5; unsigned int x_3_1_6; } x3; })primaryIPv6Addr;
- (id /* block */)primaryNetworkChangedHandler;
- (id)primaryNetworkSignature;
- (id /* block */)regionChangedHandler;
- (id)regionISOCountryCode;
- (id)regionMobileCountryCode;
- (id)regionRoutineCountry;
- (id)regionRoutineState;
- (struct { unsigned char x1[6]; })rotatingIdentifier48;
- (id /* block */)rotatingIdentifierChangedHandler;
- (id)rotatingIdentifierData;
- (bool)screenLocked;
- (id /* block */)screenLockedChangedHandler;
- (bool)screenLockedSync;
- (bool)screenOn;
- (id /* block */)screenOnChangedHandler;
- (bool)screenSaverActive;
- (id /* block */)screenSaverChangedHandler;
- (void)setBluetoothAddressChangedHandler:(id /* block */)arg1;
- (void)setCallChangedHandler:(id /* block */)arg1;
- (void)setClamshellModeChangedHandler:(id /* block */)arg1;
- (void)setConsoleUserChangedHandler:(id /* block */)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setFamilyUpdatedHandler:(id /* block */)arg1;
- (void)setFirstUnlockHandler:(id /* block */)arg1;
- (void)setForegroundAppChangedHandler:(id /* block */)arg1;
- (void)setInvalidationHandler:(id /* block */)arg1;
- (void)setLocationVisitsBundle:(id)arg1;
- (void)setLocationVisitsChangedHandler:(id /* block */)arg1;
- (void)setManateeChangedHandler:(id /* block */)arg1;
- (void)setMeDeviceChangedHandler:(id /* block */)arg1;
- (void)setMotionHandler:(id /* block */)arg1;
- (void)setNetFlagsChangedHandler:(id /* block */)arg1;
- (void)setNetInterfacesChangedHandler:(id /* block */)arg1;
- (void)setPowerUnlimitedChangedHandler:(id /* block */)arg1;
- (void)setPrimaryAppleIDChangedHandler:(id /* block */)arg1;
- (void)setPrimaryIPChangedHandler:(id /* block */)arg1;
- (void)setPrimaryNetworkChangedHandler:(id /* block */)arg1;
- (void)setRegionChangedHandler:(id /* block */)arg1;
- (void)setRotatingIdentifierChangedHandler:(id /* block */)arg1;
- (void)setScreenLockedChangedHandler:(id /* block */)arg1;
- (void)setScreenOnChangedHandler:(id /* block */)arg1;
- (void)setScreenSaverChangedHandler:(id /* block */)arg1;
- (void)setSystemLockStateChangedHandler:(id /* block */)arg1;
- (void)setSystemNameChangedHandler:(id /* block */)arg1;
- (void)setSystemUIChangedHandler:(id /* block */)arg1;
- (void)setWifiStateChangedHandler:(id /* block */)arg1;
- (int)systemLockState;
- (id /* block */)systemLockStateChangedHandler;
- (int)systemLockStateSync;
- (id)systemName;
- (id /* block */)systemNameChangedHandler;
- (id /* block */)systemUIChangedHandler;
- (unsigned int)systemUIFlags;
- (unsigned int)wifiFlags;
- (int)wifiState;
- (id /* block */)wifiStateChangedHandler;

@end
