
@interface LiveFSFPClusterItem : NSObject <NSFileProviderItem_Private> {
    LiveFSFPExtensionHelper * _extension;
    NSString * _filename;
    NSString * _fp_domainIdentifier;
}

@property (nonatomic, readonly) unsigned long long capabilities;
@property (nonatomic, readonly, copy) NSNumber *childItemCount;
@property (readonly, copy) NSArray *conflictingVersions;
@property (readonly, copy) NSString *containerDisplayName;
@property (nonatomic, readonly, copy) NSDate *contentModificationDate;
@property (nonatomic, readonly) long long contentPolicy;
@property (nonatomic, readonly, copy) UTType *contentType;
@property (nonatomic, readonly, copy) NSDate *creationDate;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *displayName;
@property (nonatomic, readonly, copy) NSNumber *documentSize;
@property (getter=isDownloadRequested, readonly, copy) NSNumber *downloadRequested;
@property (getter=isDownloaded, nonatomic, readonly) bool downloaded;
@property (getter=isDownloading, nonatomic, readonly) bool downloading;
@property (nonatomic, readonly, copy) NSError *downloadingError;
@property (getter=isExcludedFromSync, nonatomic, readonly) bool excludedFromSync;
@property (nonatomic, readonly) NSDictionary *extendedAttributes;
@property (readonly, retain) LiveFSFPExtensionHelper *extension;
@property (nonatomic, readonly, copy) NSNumber *favoriteRank;
@property (readonly, copy) NSString *fileSystemFilename;
@property (nonatomic, readonly) unsigned long long fileSystemFlags;
@property (readonly, copy) NSURL *fileURL;
@property (readonly, copy) NSString *filename;
@property (getter=fp_isAddedByCurrentUser, nonatomic, readonly) bool fp_addedByCurrentUser;
@property (nonatomic, readonly) NSPersonNameComponents *fp_addedByNameComponents;
@property (readonly, copy) NSSet *fp_cloudContainerClientBundleIdentifiers;
@property (readonly, copy) NSString *fp_cloudContainerIdentifier;
@property (readonly, copy) NSString *fp_domainIdentifier;
@property (readonly) bool fp_isCloudDocsContainer;
@property (readonly) bool fp_isContainer;
@property (readonly) bool fp_isContainerPristine;
@property (getter=fp_isLastModifiedByCurrentUser, nonatomic, readonly) bool fp_lastModifiedByCurrentUser;
@property (readonly, copy) NSString *fp_parentDomainIdentifier;
@property (readonly, copy) NSString *fp_spotlightDomainIdentifier;
@property (readonly, copy) NSString *fp_spotlightSubDomainIdentifier;
@property (getter=fp_isUbiquitous, readonly) bool fp_ubiquitous;
@property (readonly, copy) NSNumber *hasUnresolvedConflicts;
@property (readonly) unsigned long long hash;
@property (getter=isHidden, readonly) bool hidden;
@property (readonly) bool isCollaborationInvitation;
@property (nonatomic, readonly, copy) NSString *itemIdentifier;
@property (nonatomic, readonly) NSFileProviderItemVersion *itemVersion;
@property (nonatomic, readonly, copy) NSDate *lastUsedDate;
@property (nonatomic, readonly) NSPersonNameComponents *mostRecentEditorNameComponents;
@property (getter=isMostRecentVersionDownloaded, nonatomic, readonly) bool mostRecentVersionDownloaded;
@property (nonatomic, readonly) NSData *originatorInfo;
@property (nonatomic, readonly) NSPersonNameComponents *ownerNameComponents;
@property (nonatomic, readonly, copy) NSString *parentItemIdentifier;
@property (nonatomic, readonly) NSString *preformattedMostRecentEditorName;
@property (nonatomic, readonly) NSString *preformattedOwnerName;
@property (readonly, copy) NSString *providerIdentifier;
@property (nonatomic, readonly, copy) NSData *quarantineBlob;
@property (getter=isShared, nonatomic, readonly) bool shared;
@property (getter=isSharedByCurrentUser, nonatomic, readonly) bool sharedByCurrentUser;
@property (readonly, copy) NSString *sharingPermissions;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSString *symlinkTargetPath;
@property (getter=isSyncRoot) bool syncRoot;
@property (nonatomic, readonly, copy) NSData *tagData;
@property (getter=isTopLevelSharedItem, nonatomic, readonly) bool topLevelSharedItem;
@property (getter=isTrashed, nonatomic, readonly) bool trashed;
@property (nonatomic, readonly) struct NSFileProviderTypeAndCreator { unsigned int x1; unsigned int x2; } typeAndCreator;
@property (nonatomic, readonly, copy) NSString *typeIdentifier;
@property (getter=isUploaded, nonatomic, readonly) bool uploaded;
@property (getter=isUploading, nonatomic, readonly) bool uploading;
@property (nonatomic, readonly, copy) NSError *uploadingError;
@property (nonatomic, readonly) NSDictionary *userInfo;
@property (nonatomic, readonly) NSData *versionIdentifier;

+ (id)newWithName:(id)arg1 extension:(id)arg2;

- (void).cxx_destruct;
- (id)contentType;
- (id)extension;
- (id)filename;
- (id)fp_domainIdentifier;
- (id)fp_parentDomainIdentifier;
- (id)initWithName:(id)arg1 extension:(id)arg2;
- (id)itemIdentifier;
- (id)parentItemIdentifier;

@end
