
@interface WBUFormDataController : WBSFormDataController <MCProfileConnectionObserver, WBSFormAutoFillCorrectionManagerDelegate, WBSFormFieldClassificationCorrectorDelegate> {
    WBSFormAutoFillCorrectionManager * _autoFillCorrectionManager;
    WBSFormAutoFillParsecFeedbackProcessor * _autoFillFeedbackProcessor;
    int  _cachedAutoFillRestrictionValue;
    WBSGeneratedPassword * _generatedPassword;
    WBSCreditCardData * _lastFilledCreditCardData;
    bool  _savePending;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) WBSGeneratedPassword *generatedPassword;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) WBSCreditCardData *lastFilledCreditCardData;
@property (nonatomic, readonly) CNContact *me;
@property (nonatomic) bool shouldAutoFillFromAddressBook;
@property (nonatomic) bool shouldAutoFillFromCreditCardData;
@property (nonatomic) bool shouldAutoFillPasswords;
@property (readonly) Class superclass;

+ (id)_meCard;
+ (id)_stringForCNContactObject:(id)arg1 contactObjectComponent:(id)arg2;
+ (bool)contactIsMe:(id)arg1;
+ (bool)contactStoreHasMeCard:(id)arg1;
+ (bool)keychainSyncEnabled;
+ (id)localizedLowercaseContactProperty:(id)arg1;
+ (id)valueStringForMatch:(id)arg1;

- (void).cxx_destruct;
- (id)_addressBookMatchesForFamilyNameForContact:(id)arg1;
- (id)_addressBookMatchesForFullNameForContact:(id)arg1;
- (id)_addressBookMatchesForGivenNameForContact:(id)arg1;
- (id)_addressBookMatchesForMiddleNameForContact:(id)arg1;
- (void)_applicationWillEnterForeground:(id)arg1;
- (id)_autoFillCorrectionManager;
- (id)_credentialMatchesEligibleForUpdateForURL:(id)arg1 username:(id)arg2 oldPassword:(id)arg3;
- (id)_detailTextForPromptToSaveCard:(id)arg1;
- (void)_processCorrectionsForFormWithDomain:(id)arg1 formMetadata:(id)arg2 uniqueIDsOfControlsThatWereAutoFilled:(id)arg3;
- (void)_promptToUpdateRelatedCredentials:(id)arg1 urlHost:(id)arg2 relatedCredentialsHighLevelDomain:(id)arg3 webView:(id)arg4 completionHandler:(id /* block */)arg5;
- (id)_relatedCredentialMatchesToUpdateForUser:(id)arg1 protectionSpace:(id)arg2 oldSavedAccount:(id*)arg3 matchesForCurrentHost:(id*)arg4 matchesForAssociatedDomains:(id*)arg5;
- (id)_relatedCredentialMatchesToUpdateForUser:(id)arg1 protectionSpace:(id)arg2 oldSavedAccount:(id*)arg3 matchesForCurrentHost:(id*)arg4 matchesForAssociatedDomains:(id*)arg5 haveExistingCredentialWithSameUsernameAndDifferentPassword:(bool*)arg6;
- (bool)_saveUser:(id)arg1 password:(id)arg2 isGeneratedPassword:(bool)arg3 forURL:(id)arg4 inContext:(id)arg5 formType:(unsigned long long)arg6 promptingPolicy:(long long)arg7 webView:(id)arg8 completionHandler:(id /* block */)arg9;
- (bool)_shouldSaveCreditCardDataInWebView:(id)arg1 frame:(id)arg2;
- (bool)_shouldSaveUsernamesAndPasswordsForURL:(id)arg1 inWebView:(id)arg2;
- (bool)_shouldTryToSaveCredentialsFromLastForm:(id)arg1 currentFormMetadata:(id)arg2 frame:(id)arg3;
- (void)_showCreditCardPromptForWebView:(id)arg1 creditCard:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)_showPasswordPromptForWebView:(id)arg1 formType:(unsigned long long)arg2 username:(id)arg3 host:(id)arg4 hasCredentialForCurrentHost:(bool)arg5 existingCredentialMatchesForCurrentHost:(id)arg6 otherSubdomainCredentialMatches:(id)arg7 haveExistingCredentialWithSameUsernameAndDifferentPassword:(bool)arg8 completionHandler:(id /* block */)arg9;
- (void)_showPromptToSaveCreditCardSecurityCodeForWebView:(id)arg1 cardNumber:(id)arg2 securityCode:(id)arg3 completionHandler:(id /* block */)arg4;
- (id)_titleTextForWarning:(id)arg1;
- (bool)_updateCredentialsWithGeneratedPasswordForForm:(id)arg1 inWebView:(id)arg2 frame:(id)arg3 context:(id)arg4;
- (void)_warnAboutWeakPasswordIfNecessaryWithWebView:(id)arg1 savedAccount:(id)arg2 protectionSpace:(id)arg3;
- (bool)_webView:(id)arg1 formSubmission:(bool)arg2 willSubmitNewAccountOrChangePasswordFormWithMetadata:(id)arg3 shouldPreferAnnotatedCredentials:(bool)arg4 fromFrame:(id)arg5 inContext:(id)arg6 submissionHandler:(id /* block */)arg7;
- (bool)_webView:(id)arg1 saveCredentialsForURL:(id)arg2 formSubmission:(bool)arg3 formWithMetadata:(id)arg4 fromFrame:(id)arg5 username:(id)arg6 password:(id)arg7 inContext:(id)arg8 submissionHandler:(id /* block */)arg9;
- (bool)_webView:(id)arg1 saveUsernameAndPasswordForURL:(id)arg2 formType:(unsigned long long)arg3 inFrame:(id)arg4 username:(id)arg5 password:(id)arg6 isGeneratedPassword:(bool)arg7 confirmOverwritingCurrentPassword:(bool)arg8 inContext:(id)arg9 submissionHandler:(id /* block */)arg10;
- (bool)_webView:(id)arg1 saveUsernameAndPasswordFromForm:(id)arg2 inFrame:(id)arg3 context:(id)arg4 confirmOverwritingCurrentPassword:(bool)arg5 shouldPreferAnnotatedCredentials:(bool)arg6 submissionHandler:(id /* block */)arg7;
- (bool)_webView:(id)arg1 willSubmitFormContainingCreditCardData:(id)arg2 fromFrame:(id)arg3 submissionHandler:(id /* block */)arg4;
- (bool)_webView:(id)arg1 willSubmitLoginFormWithMetadata:(id)arg2 formSubmission:(bool)arg3 fromFrame:(id)arg4 inContext:(id)arg5 submissionHandler:(id /* block */)arg6;
- (bool)_webView:(id)arg1 willSubmitStandardFormWithMetadata:(id)arg2 fromFrame:(id)arg3 submissionHandler:(id /* block */)arg4;
- (id)addressBookMatchesForProperty:(id)arg1 key:(id)arg2 label:(id)arg3;
- (id)addressBookMatchesForProperty:(id)arg1 key:(id)arg2 label:(id)arg3 contact:(id)arg4;
- (id)addressBookMatchesForProperty:(id)arg1 key:(id)arg2 label:(id)arg3 partialString:(id)arg4 contact:(id)arg5 allowingIdentifiedAddressBookLabelToOverridePreferredIdentifier:(bool)arg6;
- (bool)autoFillCorrectionManagerShouldProcessFeedback:(id)arg1;
- (void)clearAllFormCredentials;
- (id)completionDBPath;
- (void)dealloc;
- (void)didFillFieldWithGeneratedPassword:(id)arg1 inFrame:(id)arg2 webView:(id)arg3;
- (void)didFillFormWithGeneratedPassword:(id)arg1 inWebView:(id)arg2 frame:(id)arg3 context:(id)arg4;
- (id)feedbackProcessorForAutoFillCorrectionManager:(id)arg1;
- (id)formAutoFillCorrectionManagerForFormFieldClassificationCorrector:(id)arg1;
- (id)formFieldClassificationCorrector:(id)arg1 bestAddressBookLabelForControlValue:(id)arg2;
- (bool)formFieldClassificationCorrector:(id)arg1 hasAddressBookDataForAddressBookLabel:(id)arg2;
- (void)gatherAutoFillDisplayDataWithTextField:(id)arg1 displayedInQuickType:(bool)arg2 prefix:(id)arg3 contact:(id)arg4 completionHandler:(id /* block */)arg5;
- (void)gatherValuesForForm:(id)arg1 focusedTextFieldMetadata:(id)arg2 inFrame:(id)arg3 multiRoundAutoFillManager:(id)arg4 completionHandler:(id /* block */)arg5;
- (id)generatedPassword;
- (id)initWithAggressiveKeychainCaching:(bool)arg1;
- (id)lastFilledCreditCardData;
- (bool)mayFillCreditCardDataInFrame:(id)arg1;
- (bool)mayPreFillInFrame:(id)arg1;
- (id)me;
- (void)performWhenReady:(id /* block */)arg1;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)saveCompletionDBSoon;
- (void)saveUnsubmittedGeneratedPasswordInFrame:(id)arg1 form:(id)arg2 context:(id)arg3 closingWebView:(bool)arg4;
- (void)saveUser:(id)arg1 password:(id)arg2 forURL:(id)arg3 inContext:(id)arg4 andPromptToUpdateRelatedCredentialsWithWebView:(id)arg5;
- (id)savedAccountFromMatches:(id)arg1 completingPartialUserInLoginForm:(id)arg2;
- (void)setGeneratedPassword:(id)arg1;
- (void)setLastFilledCreditCardData:(id)arg1;
- (void)setShouldAutoFillFromAddressBook:(bool)arg1;
- (void)setShouldAutoFillFromCreditCardData:(bool)arg1;
- (void)setShouldAutoFillPasswords:(bool)arg1;
- (bool)shouldAllowPasswordAutoFillOnURL:(id)arg1 allowExternalCredentials:(bool)arg2;
- (bool)shouldAutoFillFromAddressBook;
- (bool)shouldAutoFillFromCreditCardData;
- (bool)shouldAutoFillFromCreditCardDataInFrame:(id)arg1;
- (bool)shouldAutoFillFromPreviousData;
- (bool)shouldAutoFillPasswords;
- (bool)shouldAutoGeneratePasswordsForURL:(id)arg1 inWebView:(id)arg2;
- (void)textDidChangeInForm:(id)arg1 inWebView:(id)arg2 frame:(id)arg3 context:(id)arg4;
- (id)uniqueIDOfContact:(id)arg1;
- (bool)webView:(id)arg1 frame:(id)arg2 willNavigateFromForm:(id)arg3 inContext:(id)arg4 bySubmitting:(bool)arg5 processMetadataCorrections:(bool)arg6 uniqueIDsOfControlsThatWereAutoFilled:(id)arg7 submissionHandler:(id /* block */)arg8;
- (bool)whiteListAllowsURL:(id)arg1;

@end
