
@interface STSSearchModel : NSObject <PARSessionDelegate> {
    NSArray * _categoryList;
    unsigned long long  _categoryListRequestQueryId;
    NSString * _conversationID;
    NSString * _currentQuery;
    PARTask * _currentTask;
    <STSSearchModelDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _mutableSectionsQueue;
    PARSession * _parsecSession;
    NSArray * _predictedSuggestions;
    NSObject<OS_dispatch_queue> * _queryQueue;
    NSArray * _querySuggestions;
    <STSSearchModelQuerySuggestionsDelegate> * _querySuggestionsDelegate;
    NSArray * _recentResults;
    <STSRecentsDelegate> * _recentsDelegate;
    NSMutableArray * _recentsToDedup;
    NSMutableDictionary * _reportConcernStore;
    NSMutableDictionary * _searchResultStore;
    NSArray * _searchResults;
    NSArray * _sections;
    NSMutableDictionary * _zkwResultStore;
}

@property (nonatomic, retain) NSArray *categoryList;
@property unsigned long long categoryListRequestQueryId;
@property (nonatomic, retain) NSString *conversationID;
@property (nonatomic, readonly) NSString *currentQuery;
@property (nonatomic, retain) PARTask *currentTask;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <STSSearchModelDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *mutableSectionsQueue;
@property (nonatomic, retain) PARSession *parsecSession;
@property (nonatomic, retain) NSArray *predictedSuggestions;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queryQueue;
@property (nonatomic, retain) NSArray *querySuggestions;
@property (nonatomic) <STSSearchModelQuerySuggestionsDelegate> *querySuggestionsDelegate;
@property (nonatomic, retain) NSArray *recentResults;
@property (nonatomic) <STSRecentsDelegate> *recentsDelegate;
@property (nonatomic, retain) NSMutableArray *recentsToDedup;
@property (nonatomic, retain) NSMutableDictionary *reportConcernStore;
@property (nonatomic, retain) NSMutableDictionary *searchResultStore;
@property (nonatomic, retain) NSArray *searchResults;
@property (nonatomic, retain) NSArray *sections;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSMutableDictionary *zkwResultStore;

+ (unsigned long long)clientQueryId;
+ (void)incrementClientQueryId;
+ (id)serverURLString;

- (void).cxx_destruct;
- (void)_clearQuerySuggestionsAndNotifyDelegate;
- (void)_clearSectionsAndNotifyDelegate;
- (void)_performParsecdSearchQuery:(id)arg1 requestType:(long long)arg2 completion:(id /* block */)arg3;
- (void)_updateSearchProviderImageForResult:(id)arg1;
- (void)addSearchResultToReportConcernStore:(id)arg1;
- (void)appendQueryItemsForRequest:(id)arg1 type:(long long)arg2;
- (id)categoryList;
- (unsigned long long)categoryListRequestQueryId;
- (id)conversationID;
- (id)createQuerySession;
- (id)currentQuery;
- (id)currentTask;
- (id)defaultCategoryList;
- (id)delegate;
- (void)fetchMoreResults;
- (id)init;
- (void)loadReportConcernStoreFromDefaults;
- (id)mockQuerySuggestions;
- (id)mutableSectionsQueue;
- (unsigned long long)numberOfReportedResults;
- (id)parsecSession;
- (void)performCategoryListRequest:(id /* block */)arg1;
- (void)performSearchWithQueryString:(id)arg1 requestType:(long long)arg2 completion:(id /* block */)arg3;
- (void)performZKWSearchQueryWithCompletion:(id /* block */)arg1;
- (id)predictedSuggestions;
- (void)prefetchRecentsWithCompletion:(id /* block */)arg1;
- (id)queryQueue;
- (id)querySuggestions;
- (id)querySuggestionsDelegate;
- (id)recentResults;
- (id)recentsDelegate;
- (id)recentsToDedup;
- (void)removeAllSections;
- (id)removeOutdatedReportedResults:(id)arg1;
- (void)removeQuerySuggestions;
- (void)removeResultAtIndexPath:(id)arg1;
- (id)reportConcernStore;
- (id)resultsWithReportedImagesRemoved:(id)arg1;
- (void)saveReportConcernStoreToUserDefaults;
- (id)searchResultStore;
- (id)searchResults;
- (id)sections;
- (void)session:(id)arg1 bag:(id)arg2 didLoadWithError:(id)arg3;
- (void)setCategoryList:(id)arg1;
- (void)setCategoryListRequestQueryId:(unsigned long long)arg1;
- (void)setConversationID:(id)arg1;
- (void)setCurrentTask:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMutableSectionsQueue:(id)arg1;
- (void)setParsecSession:(id)arg1;
- (void)setPredictedSuggestions:(id)arg1;
- (void)setQueryQueue:(id)arg1;
- (void)setQuerySuggestions:(id)arg1;
- (void)setQuerySuggestionsDelegate:(id)arg1;
- (void)setRecentResults:(id)arg1;
- (void)setRecentsDelegate:(id)arg1;
- (void)setRecentsToDedup:(id)arg1;
- (void)setReportConcernStore:(id)arg1;
- (void)setSearchResultStore:(id)arg1;
- (void)setSearchResults:(id)arg1;
- (void)setSections:(id)arg1;
- (void)setZkwResultStore:(id)arg1;
- (id)zkwResultStore;

@end
