
@interface MRUViewServiceRoutingViewController : UIViewController <MRUNowPlayingControllerObserver, MRURoutingViewControllerDelegate, MediaControlsEndpointsManagerDelegate, UITableViewDelegate, UITableViewDelegatePrivate> {
    UIViewController * _alertViewController;
    bool  _canShowRemoteDevices;
    MPMediaControlsConfiguration * _configuration;
    UITableViewDiffableDataSource * _dataSource;
    <MRUViewServiceRoutingViewControllerDelegate> * _delegate;
    MediaControlsEndpointsManager * _endpointsManager;
    NSMutableDictionary * _nowPlayingControllers;
    bool  _onScreen;
    MRUOutputDeviceRoutingDataSource * _outputDeviceRoutingDataSource;
    id /* block */  _replaceRoutes;
    MRURoutingViewController * _routingViewController;
    MRUNowPlayingController * _selectedNowPlayingController;
    MRUVisualStylingProvider * _stylingProvider;
    bool  _supportsQueueHandoff;
    MRUVendorSpecificDeviceManager * _vendorSpecificManager;
}

@property (nonatomic, retain) UIViewController *alertViewController;
@property (nonatomic) bool canShowRemoteDevices;
@property (nonatomic, retain) MPMediaControlsConfiguration *configuration;
@property (nonatomic, retain) UITableViewDiffableDataSource *dataSource;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <MRUViewServiceRoutingViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) MediaControlsEndpointsManager *endpointsManager;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableDictionary *nowPlayingControllers;
@property (getter=isOnScreen, nonatomic) bool onScreen;
@property (nonatomic, retain) MRUOutputDeviceRoutingDataSource *outputDeviceRoutingDataSource;
@property (nonatomic, copy) id /* block */ replaceRoutes;
@property (nonatomic, retain) MRURoutingViewController *routingViewController;
@property (nonatomic, retain) MRUNowPlayingController *selectedNowPlayingController;
@property (nonatomic, retain) MRUVisualStylingProvider *stylingProvider;
@property (readonly) Class superclass;
@property (nonatomic) bool supportsQueueHandoff;
@property (nonatomic, retain) MRUVendorSpecificDeviceManager *vendorSpecificManager;
@property (nonatomic, retain) MRUViewServiceRoutingView *view;
@property (nonatomic, retain) MRUViewServiceRoutingView *viewIfLoaded;

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (id)alertViewController;
- (bool)canShowMoreButton;
- (bool)canShowRemoteDevices;
- (id)configuration;
- (id)dataSource;
- (void)dealloc;
- (id)delegate;
- (void)didSelectListState:(id)arg1;
- (void)didSelectQuickControl:(id)arg1;
- (id)endpointsManager;
- (void)endpointsManager:(id)arg1 activeSystemRouteDidChange:(id)arg2;
- (void)endpointsManager:(id)arg1 defersRoutesReplacement:(id /* block */)arg2;
- (id)init;
- (bool)isOnScreen;
- (void)loadView;
- (void)nowPlayingController:(id)arg1 didChangeQuickControlItem:(id)arg2;
- (void)nowPlayingController:(id)arg1 endpointController:(id)arg2 didChangeRoute:(id)arg3;
- (void)nowPlayingController:(id)arg1 metadataController:(id)arg2 didChangeArtwork:(id)arg3;
- (void)nowPlayingController:(id)arg1 metadataController:(id)arg2 didChangeNowPlayingInfo:(id)arg3;
- (bool)nowPlayingControllerShouldAutomaticallyUpdateResponse:(id)arg1;
- (id)nowPlayingControllers;
- (id)outputDeviceRoutingDataSource;
- (id /* block */)replaceRoutes;
- (id)routingViewController;
- (void)routingViewController:(id)arg1 didSelectRoutingViewItem:(id)arg2;
- (void)routingViewControllerDidUpdateItems:(id)arg1;
- (id)selectedIdentifier;
- (id)selectedNowPlayingController;
- (void)setAlertViewController:(id)arg1;
- (void)setCanShowRemoteDevices:(bool)arg1;
- (void)setConfiguration:(id)arg1;
- (void)setDataSource:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setEndpointsManager:(id)arg1;
- (void)setNowPlayingControllers:(id)arg1;
- (void)setOnScreen:(bool)arg1;
- (void)setOutputDeviceRoutingDataSource:(id)arg1;
- (void)setReplaceRoutes:(id /* block */)arg1;
- (void)setRoutingViewController:(id)arg1;
- (void)setSelectedNowPlayingController:(id)arg1;
- (void)setState:(long long)arg1;
- (void)setStylingProvider:(id)arg1;
- (void)setSupportsQueueHandoff:(bool)arg1;
- (void)setVendorSpecificManager:(id)arg1;
- (id)stylingProvider;
- (bool)supportsQueueHandoff;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (bool)tableView:(id)arg1 shouldHaveFullLengthBottomSeparatorForSection:(long long)arg2;
- (void)updateCell:(id)arg1 forIdentifier:(id)arg2;
- (void)updateCellForIdentifier:(id)arg1;
- (void)updateDiscoveryMode;
- (void)updateMoreButtonVisibility;
- (void)updateNowPlayingControllers;
- (void)updateRoutingViewController;
- (void)updateRoutingViewControllerScrollIndicatorInsets;
- (void)updateSelectedViewController;
- (id)vendorSpecificManager;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
