
@interface MRUWaveformView : UIView <MRUVisualStylingProviderObserver> {
    CALayer * _artworkDimLayer;
    UIImage * _artworkImage;
    CALayer * _artworkLayer;
    CALayer * _artworkLightenLayer;
    NSArray * _bars;
    UIView * _barsContainerView;
    UIView * _barsView;
    CALayer * _contentLayer;
    unsigned long long  _context;
    bool  _dimmed;
    CALayer * _fallbackLayer;
    UIColor * _fillColor;
    NSString * _remoteRouteSymbol;
    UIImageView * _routeImageView;
    MRUWaveformSettings * _settings;
    MRUVisualStylingProvider * _stylingProvider;
    NSTimer * _transitionTimer;
    MRUWaveformData * _waveformData;
}

@property (nonatomic, retain) CALayer *artworkDimLayer;
@property (nonatomic, retain) UIImage *artworkImage;
@property (nonatomic, retain) CALayer *artworkLayer;
@property (nonatomic, retain) CALayer *artworkLightenLayer;
@property (nonatomic, retain) NSArray *bars;
@property (nonatomic, retain) UIView *barsContainerView;
@property (nonatomic, retain) UIView *barsView;
@property (nonatomic, retain) CALayer *contentLayer;
@property (nonatomic) unsigned long long context;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isDimmed, nonatomic) bool dimmed;
@property (nonatomic, retain) CALayer *fallbackLayer;
@property (nonatomic, retain) UIColor *fillColor;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *remoteRouteSymbol;
@property (nonatomic, retain) UIImageView *routeImageView;
@property (nonatomic, retain) MRUWaveformSettings *settings;
@property (nonatomic, retain) MRUVisualStylingProvider *stylingProvider;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSTimer *transitionTimer;
@property (nonatomic, retain) MRUWaveformData *waveformData;

- (void).cxx_destruct;
- (void)applyContext:(unsigned long long)arg1;
- (id)artworkDimLayer;
- (id)artworkImage;
- (id)artworkLayer;
- (id)artworkLightenLayer;
- (id)bars;
- (id)barsContainerView;
- (id)barsView;
- (id)contentLayer;
- (unsigned long long)context;
- (id)fallbackLayer;
- (id)fillColor;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 context:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 context:(unsigned long long)arg2 settings:(id)arg3;
- (bool)isDimmed;
- (void)layoutSubviews;
- (id)remoteRouteSymbol;
- (id)routeImageView;
- (void)setArtworkDimLayer:(id)arg1;
- (void)setArtworkImage:(id)arg1;
- (void)setArtworkLayer:(id)arg1;
- (void)setArtworkLightenLayer:(id)arg1;
- (void)setBars:(id)arg1;
- (void)setBarsContainerView:(id)arg1;
- (void)setBarsView:(id)arg1;
- (void)setContentLayer:(id)arg1;
- (void)setContext:(unsigned long long)arg1;
- (void)setDimmed:(bool)arg1;
- (void)setFallbackLayer:(id)arg1;
- (void)setFillColor:(id)arg1;
- (void)setRemoteRouteSymbol:(id)arg1;
- (void)setRouteImageView:(id)arg1;
- (void)setSettings:(id)arg1;
- (void)setStylingProvider:(id)arg1;
- (void)setTransitionTimer:(id)arg1;
- (void)setWaveformData:(id)arg1;
- (id)settings;
- (id)stylingProvider;
- (id)transitionTimer;
- (void)updateArtworkFilters;
- (void)updateLayers;
- (void)updateVisualStyle;
- (void)visualStylingProviderDidChange:(id)arg1;
- (id)waveformData;

@end
