
@interface PCSShareProtectionObject : NSObject {
    struct _PCSIdentityData { } * _identity;
    struct _OpaquePCSShareProtection { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct _PCSIdentitySetData {} *x2; struct _PCSIdentitySetData {} *x3; struct _PCSIdentitySetData {} *x4; struct __CFDictionary {} *x5; struct __CFArray {} *x6; struct __CFDictionary {} *x7; struct __CFData {} *x8; struct __CFData {} *x9; struct __CFData {} *x10; struct _PCSKeyData {} *x11; struct __CFData {} *x12; struct _PCSKeyData {} *x13; struct __CFDictionary {} *x14; unsigned int x15; unsigned int x16; struct PCSAttributes { unsigned int x_17_1_1; struct PCSTypeValue {} *x_17_1_2; } x17; struct _PCSPublicIdentityData {} *x18; struct _PCSPublicIdentityData {} *x19; struct _PCSPublicIdentityData {} *x20; struct _PCSPublicIdentityData {} *x21; struct _PCSIdentityData {} *x22; struct _PCSIdentityData {} *x23; unsigned int x24; int x25; struct { bool x_26_1_1; bool x_26_1_2; bool x_26_1_3; bool x_26_1_4; bool x_26_1_5; bool x_26_1_6; bool x_26_1_7; } x26; unsigned int x27; } * _shareProtection;
}

@property (nonatomic, readonly) struct _OpaquePCSShareProtection { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct _PCSIdentitySetData {} *x2; struct _PCSIdentitySetData {} *x3; struct _PCSIdentitySetData {} *x4; struct __CFDictionary {} *x5; struct __CFArray {} *x6; struct __CFDictionary {} *x7; struct __CFData {} *x8; struct __CFData {} *x9; struct __CFData {} *x10; struct _PCSKeyData {} *x11; struct __CFData {} *x12; struct _PCSKeyData {} *x13; struct __CFDictionary {} *x14; unsigned int x15; unsigned int x16; struct PCSAttributes { unsigned int x_17_1_1; struct PCSTypeValue {} *x_17_1_2; } x17; struct _PCSPublicIdentityData {} *x18; struct _PCSPublicIdentityData {} *x19; struct _PCSPublicIdentityData {} *x20; struct _PCSPublicIdentityData {} *x21; struct _PCSIdentityData {} *x22; struct _PCSIdentityData {} *x23; unsigned int x24; int x25; struct { bool x_26_1_1; bool x_26_1_2; bool x_26_1_3; bool x_26_1_4; bool x_26_1_5; bool x_26_1_6; bool x_26_1_7; } x26; unsigned int x27; }*shareProtection;

- (void)dealloc;
- (id)exportAcceptedSharingRequestWithError:(id*)arg1;
- (id)initWithShareProtectionRef:(struct _OpaquePCSShareProtection { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct _PCSIdentitySetData {} *x2; struct _PCSIdentitySetData {} *x3; struct _PCSIdentitySetData {} *x4; struct __CFDictionary {} *x5; struct __CFArray {} *x6; struct __CFDictionary {} *x7; struct __CFData {} *x8; struct __CFData {} *x9; struct __CFData {} *x10; struct _PCSKeyData {} *x11; struct __CFData {} *x12; struct _PCSKeyData {} *x13; struct __CFDictionary {} *x14; unsigned int x15; unsigned int x16; struct PCSAttributes { unsigned int x_17_1_1; struct PCSTypeValue {} *x_17_1_2; } x17; struct _PCSPublicIdentityData {} *x18; struct _PCSPublicIdentityData {} *x19; struct _PCSPublicIdentityData {} *x20; struct _PCSPublicIdentityData {} *x21; struct _PCSIdentityData {} *x22; struct _PCSIdentityData {} *x23; unsigned int x24; int x25; struct { bool x_26_1_1; bool x_26_1_2; bool x_26_1_3; bool x_26_1_4; bool x_26_1_5; bool x_26_1_6; bool x_26_1_7; } x26; unsigned int x27; }*)arg1;
- (id)initWithSharingRequestData:(id)arg1 identitySet:(struct _PCSIdentitySetData { }*)arg2 error:(id*)arg3;
- (struct _OpaquePCSShareProtection { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct _PCSIdentitySetData {} *x2; struct _PCSIdentitySetData {} *x3; struct _PCSIdentitySetData {} *x4; struct __CFDictionary {} *x5; struct __CFArray {} *x6; struct __CFDictionary {} *x7; struct __CFData {} *x8; struct __CFData {} *x9; struct __CFData {} *x10; struct _PCSKeyData {} *x11; struct __CFData {} *x12; struct _PCSKeyData {} *x13; struct __CFDictionary {} *x14; unsigned int x15; unsigned int x16; struct PCSAttributes { unsigned int x_17_1_1; struct PCSTypeValue {} *x_17_1_2; } x17; struct _PCSPublicIdentityData {} *x18; struct _PCSPublicIdentityData {} *x19; struct _PCSPublicIdentityData {} *x20; struct _PCSPublicIdentityData {} *x21; struct _PCSIdentityData {} *x22; struct _PCSIdentityData {} *x23; unsigned int x24; int x25; struct { bool x_26_1_1; bool x_26_1_2; bool x_26_1_3; bool x_26_1_4; bool x_26_1_5; bool x_26_1_6; bool x_26_1_7; } x26; unsigned int x27; }*)shareProtection;
- (id)sharingRequestDataForIdentity:(struct _PCSPublicIdentityData { }*)arg1 error:(id*)arg2;
- (id)sharingRequestDataForIdentity:(struct _PCSPublicIdentityData { }*)arg1 flags:(unsigned int)arg2 error:(id*)arg3;
- (id)sharingRequestDataForIdentity:(struct _PCSPublicIdentityData { }*)arg1 owner:(void*)arg2 flags:(unsigned int)arg3 error:(id*)arg4;

@end
