
@interface CKOnboardingController : NSObject <AVTAvatarEditorViewControllerDelegate, CKCNSharingProfileOnboardingFlowManagerDelegate, CKSyndicationOnboardingPageViewControllerDelegate, CNMeCardSharingPickerViewControllerDelegate, IMCNMeCardSharingOnboardingAudienceViewControllerDelegate, IMCNMeCardSharingOnboardingEditViewControllerDelegate, UIAdaptivePresentationControllerDelegate, UINavigationControllerDelegate> {
    CNSharingProfileAvatarItemProviderConfiguration * _avatarItemProviderConfiguration;
    <AVTAvatarRecord> * _avatarRecord;
    AVTAvatarStore * _avatarStore;
    OBButtonTray * _buttonTray;
    <CKOnboardingControllerDelegate> * _delegate;
    bool  _isUserInitiatedEditNameAndPhoto;
    OBWelcomeFullCenterContentController * _memojiCreationController;
    AVPlayer * _memojiVideoPlayer;
    AVPlayerLooper * _memojiVideoPlayerLooper;
    int  _micLayout;
    UINavigationController * _navigationController;
    CKCNSharingProfileOnboardingFlowManager * _nicknameFlowManager;
    <IMCNMeCardSharingResult> * _pendingMeCardSharingResult;
    bool  _presentingFromPrefs;
    CKCNSharedProfileOnboardingController * _sharedProfileOnboardingController;
    IMCloudKitSyncState * _syncState;
    OBWelcomeController * _syndicationIntroController;
}

@property (nonatomic, retain) CNSharingProfileAvatarItemProviderConfiguration *avatarItemProviderConfiguration;
@property (nonatomic, retain) <AVTAvatarRecord> *avatarRecord;
@property (nonatomic, retain) AVTAvatarStore *avatarStore;
@property (nonatomic, retain) OBButtonTray *buttonTray;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <CKOnboardingControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isUserInitiatedEditNameAndPhoto;
@property (getter=_memojiCreationController, nonatomic, retain) OBWelcomeFullCenterContentController *memojiCreationController;
@property (nonatomic, retain) AVPlayer *memojiVideoPlayer;
@property (nonatomic, retain) AVPlayerLooper *memojiVideoPlayerLooper;
@property (nonatomic) int micLayout;
@property (nonatomic, retain) UINavigationController *navigationController;
@property (nonatomic, retain) CKCNSharingProfileOnboardingFlowManager *nicknameFlowManager;
@property (nonatomic, retain) <IMCNMeCardSharingResult> *pendingMeCardSharingResult;
@property (nonatomic) bool presentingFromPrefs;
@property (nonatomic, retain) CKCNSharedProfileOnboardingController *sharedProfileOnboardingController;
@property (readonly) Class superclass;
@property (nonatomic, retain) IMCloudKitSyncState *syncState;
@property (nonatomic, retain) OBWelcomeController *syndicationIntroController;

- (void).cxx_destruct;
- (void)_beginMOCFlowForState:(id)arg1 rampState:(id)arg2;
- (void)_beginMiCWelcomeScreen;
- (void)_fetchMemojiWithCompletionBlock:(id /* block */)arg1;
- (id)_introController;
- (bool)_isRunningTest;
- (unsigned long long)_meCardSharingAudience;
- (bool)_meCardSharingEnabled;
- (unsigned long long)_meCardSharingNameFormat;
- (id)_meCardSharingState;
- (id)_memojiCreationController;
- (id)_micController;
- (id)_nameAndPhotoSharingIntroController;
- (id)_nicknameController;
- (void)_onClickMiCNotNow;
- (void)_onClickMiCOnboard;
- (void)_presentMemojiCreationIfNeeded:(id /* block */)arg1 skipAction:(id /* block */)arg2;
- (void)_pushOnboardingViewController:(id)arg1 animated:(bool)arg2;
- (bool)_readyToShowNextScreenWithTimeout:(unsigned long long)arg1;
- (bool)_shouldOnboardCollaborationApps;
- (bool)_shouldPresentMiCWelcome;
- (bool)_shouldPresentNewInMessages;
- (bool)_shouldShowNicknameOnboardingFlow;
- (bool)_shouldShowNicknameOnboardingFlowIgnoringVersion:(bool)arg1;
- (bool)_shouldShowNicknameOnboardingFlowOnLaunch;
- (bool)_shouldShowSyndicationOnboardingFlowOnLaunch;
- (void)_tryToEnableHSA2;
- (void)_tryToEnableMOC;
- (id)_userDefaults;
- (long long)_whatsNewLatestShippingVersion;
- (long long)_whatsNewVersion;
- (void)_writeDefaultCollaborationOnboardingVersion;
- (void)_writeDefaultMiCWelcome;
- (void)_writeDefaultNicknameOnboardingVersion;
- (void)_writeDefaultSyndicationOnboardingVersion;
- (void)_writeDefaultWhatsNewDidShow;
- (bool)accountCanCreateNickname;
- (bool)alwaysShowNicknameOnboarding;
- (bool)alwaysShowSyndicationOnboarding;
- (void)avatarEditorViewController:(id)arg1 didFinishWithAvatarRecord:(id)arg2;
- (void)avatarEditorViewControllerDidCancel:(id)arg1;
- (id)avatarItemProviderConfiguration;
- (id)avatarRecord;
- (id)avatarStore;
- (id)buttonTray;
- (void)completedOnboarding;
- (void)completedOnboardingWithCompletion:(id /* block */)arg1;
- (id)contactForNicknameOnboarding;
- (long long)currentCollaborationOnboardingVersion;
- (id)delegate;
- (void)enableSyndication;
- (void)flowManager:(id)arg1 didFinishWithResult:(id)arg2;
- (void)flowManagerDidSelectSetupLater:(id)arg1;
- (id)getButtonTray;
- (void)initializeBundleIDsInAppPreferences:(bool)arg1;
- (bool)isUserInitiatedEditNameAndPhoto;
- (void)meCardSharingOnboardingAudienceViewControllerDidFinish:(id)arg1 withSharingAudience:(unsigned long long)arg2;
- (void)meCardSharingOnboardingEditController:(id)arg1 didFinishWithOnboardingResult:(id)arg2;
- (id)memojiVideoPlayer;
- (id)memojiVideoPlayerLooper;
- (int)micLayout;
- (id)navigationController;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(bool)arg3;
- (unsigned long long)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (id)nicknameFlowManager;
- (unsigned long long)nicknameOnboardingLastShownVersion;
- (void)onboardCollaborationApps;
- (id)pendingMeCardSharingResult;
- (void)prepareForOnboarding;
- (void)prepareForSuspend;
- (void)presentFromPrefsPresentationController:(id)arg1 resizeToFitContent:(bool)arg2;
- (void)presentMemojiSetup;
- (void)presentNicknameOnboardingOrEditFlow;
- (bool)presentNicknameSharingSetupFlow;
- (bool)presentNicknameSharingSetupFlowWithMemoji:(bool)arg1 forUserInitiatedEdit:(bool)arg2;
- (void)presentOnboarding:(id)arg1;
- (bool)presentOnboardingIfNeeded;
- (void)presentationControllerDidDismiss:(id)arg1;
- (bool)presentingFromPrefs;
- (void)pushMemojiCreationStep;
- (void)pushMemojiCreationStepIfNeeded;
- (void)pushNameAndPhotoSharingConfigDataStep;
- (void)pushNameAndPhotoSharingConfigSharingPreferenceStep;
- (void)pushNameAndPhotoSharingIntroStep;
- (void)pushNameAndPhotoSharingIntroStepIfNeeded;
- (void)pushSyndicationIntroStep;
- (bool)readyToShowNextScreen;
- (void)reportMoCLayoutShown:(int)arg1;
- (void)setAvatarItemProviderConfiguration:(id)arg1;
- (void)setAvatarRecord:(id)arg1;
- (void)setAvatarStore:(id)arg1;
- (void)setButtonTray:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setIsUserInitiatedEditNameAndPhoto:(bool)arg1;
- (void)setMemojiCreationController:(id)arg1;
- (void)setMemojiVideoPlayer:(id)arg1;
- (void)setMemojiVideoPlayerLooper:(id)arg1;
- (void)setMicLayout:(int)arg1;
- (void)setNavigationController:(id)arg1;
- (void)setNicknameFlowManager:(id)arg1;
- (void)setPendingMeCardSharingResult:(id)arg1;
- (void)setPresentingFromPrefs:(bool)arg1;
- (void)setSharedProfileOnboardingController:(id)arg1;
- (void)setSyncState:(id)arg1;
- (void)setSyndicationIntroController:(id)arg1;
- (void)setUpSyndicationLater;
- (id)sharedProfileOnboardingController;
- (void)sharingPicker:(id)arg1 didChangeSharingState:(bool)arg2;
- (void)sharingPicker:(id)arg1 didSelectNameFormat:(unsigned long long)arg2;
- (void)sharingPicker:(id)arg1 didSelectSharingAudience:(unsigned long long)arg2;
- (void)sharingPickerDidFinish:(id)arg1;
- (bool)shouldPresentOnboarding;
- (void)startNicknameOnboardingIfNeeded;
- (id)syncState;
- (id)syndicationIntroController;
- (unsigned long long)syndicationOnboardingLastShownVersion;
- (void)viewIssues:(id)arg1;

@end
