
@interface CKRecipientSelectionController : CKViewController <CKComposeRecipientViewDelegate, CKDetailsContactsManagerDelegate, CKRecipientSearchListControllerDelegate, CNAutocompleteGroupDetailViewControllerDelegate, CNComposeRecipientTextViewDelegate, CNContactPickerDelegate, CoreTelephonyClientDelegate> {
    CKManualUpdater * _addressBookNotificationUpdater;
    bool  _allowedByScreenTime;
    CKAlertController * _alternateAddressesAlertController;
    CNContactPickerViewController * _contactPickerViewController;
    CNContactStore * _contactStore;
    CKDetailsContactsManager * _contactsManager;
    CKPendingConversation * _conversation;
    CoreTelephonyClient * _coreTelephonyClient;
    STConversationContext * _currentConversationContext;
    <CKRecipientSelectionControllerDelegate> * _delegate;
    bool  _didShowOneTimeErrorAlert;
    bool  _editable;
    bool  _forceMMS;
    id /* block */  _gameCenterPickerBlock;
    UIView * _headerDecorationView;
    bool  _homogenizePreferredServiceForiMessage;
    bool  _isDisambiguating;
    double  _keyboardHeightWithAccessoryView;
    unsigned long long  _numberOfRowsInToField;
    bool  _peoplePickerHidden;
    bool  _preventAtomization;
    CNComposeRecipient * _recentContactForPresentedCNCard;
    NSMutableDictionary * _recipientAvailabilities;
    NSMutableDictionary * _recipientAvailibityTimers;
    CKRecipientSearchListController * _searchListController;
    UIView * _separator;
    bool  _shouldSuppressSearchResultsTable;
    CKComposeRecipientView * _toField;
    UIView * _toFieldContainerView;
    UILabel * _toFieldPlaceholderLabel;
    UIScrollView * _toFieldScrollingView;
}

@property (nonatomic, retain) CKManualUpdater *addressBookNotificationUpdater;
@property (nonatomic) bool allowedByScreenTime;
@property (nonatomic, retain) CKAlertController *alternateAddressesAlertController;
@property (nonatomic, readonly) double collapsedHeight;
@property (nonatomic, retain) CNContactPickerViewController *contactPickerViewController;
@property (nonatomic, retain) CNContactStore *contactStore;
@property (nonatomic, retain) CKDetailsContactsManager *contactsManager;
@property (nonatomic, retain) CKPendingConversation *conversation;
@property (nonatomic, retain) CoreTelephonyClient *coreTelephonyClient;
@property (nonatomic, retain) STConversationContext *currentConversationContext;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <CKRecipientSelectionControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool didShowOneTimeErrorAlert;
@property (getter=isEditable, nonatomic) bool editable;
@property (nonatomic) bool forceMMS;
@property (nonatomic, copy) id /* block */ gameCenterPickerBlock;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIView *headerDecorationView;
@property (nonatomic, readonly) bool homogenizePreferredServiceForiMessage;
@property (nonatomic) bool isDisambiguating;
@property (nonatomic) double keyboardHeightWithAccessoryView;
@property (nonatomic) unsigned long long numberOfRowsInToField;
@property (getter=isPeoplePickerHidden, nonatomic) bool peoplePickerHidden;
@property (nonatomic) bool preventAtomization;
@property (nonatomic, retain) CNComposeRecipient *recentContactForPresentedCNCard;
@property (nonatomic, retain) NSMutableDictionary *recipientAvailabilities;
@property (nonatomic, retain) NSMutableDictionary *recipientAvailibityTimers;
@property (nonatomic, retain) CKRecipientSearchListController *searchListController;
@property (getter=isSearchResultsHidden, nonatomic) bool searchResultsHidden;
@property (nonatomic, retain) UIView *separator;
@property (nonatomic, readonly) bool shouldSuppressSearchResultsTable;
@property (readonly) Class superclass;
@property (nonatomic, retain) CKComposeRecipientView *toField;
@property (nonatomic, readonly) UIView *toFieldAsUIView;
@property (nonatomic, readonly) UIView *toFieldContainerView;
@property (nonatomic, readonly) bool toFieldIsFirstResponder;
@property (nonatomic, retain) UILabel *toFieldPlaceholderLabel;
@property (nonatomic, retain) UIScrollView *toFieldScrollingView;

- (void).cxx_destruct;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_additionalSearchResultsEdgeInsets;
- (void)_adjustToFieldPositionIfNecessary;
- (void)_adjustToFieldSeparatorInsetsIfNecessary;
- (id)_alternateAddressesForRecipient:(id)arg1;
- (id)_alternateiMessagableAddressesForRecipient:(id)arg1;
- (unsigned long long)_atomPresentationOptionsForRecipient:(id)arg1;
- (BOOL)_availibilityForRecipient:(id)arg1 onService:(id)arg2;
- (id)_canonicalRecipientAddresses;
- (bool)_configureSearchListControllerAsAPopover;
- (void)_dismissPeoplePicker;
- (void)_handleAddressBookChangedNotification:(id)arg1;
- (void)_handleAddressBookPartialChangedNotification:(id)arg1;
- (void)_handleConversationPreferredServiceDidChangeNotification:(id)arg1;
- (void)_handleIDSResultsWhenSearchTableIsHidden:(id)arg1;
- (void)_handleRecipientAvailabilityTimeout:(id)arg1;
- (void)_handleRecipientViewChanged:(id)arg1;
- (void)_hideSearchField;
- (bool)_isToFieldPushedUp;
- (void)_keyboardWillShowOrHide:(id)arg1;
- (double)_macToFieldHeight;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_navigationBarInsets;
- (bool)_openStewieAppForEmergencyIfRequired;
- (bool)_openStewieAppForRoadsideIfRequired;
- (void)_presentBusinessChatNotSupportedError;
- (id)_recipientCausingTooManyRecipientsError;
- (void)_refreshActionSheet;
- (void)_removeAvailabilityTimeoutTimerForRecipient:(id)arg1;
- (void)_removeRecent;
- (void)_resetSearchResultsInsets;
- (bool)_shouldEnableScrolling;
- (void)_showActionSheetForRecipient:(id)arg1 animated:(bool)arg2;
- (void)_showContactCardForRecipient:(id)arg1 sourceView:(id)arg2;
- (void)_showDetailsForGroup:(id)arg1;
- (void)_showDetailsForRecipient:(id)arg1 canDelete:(bool)arg2;
- (void)_showOneTimeErrorAlertForAddedRecipient:(id)arg1 service:(id)arg2 withError:(BOOL)arg3;
- (void)_showSearchField;
- (void)_startAvailabilityTimeoutTimerForRecipient:(id)arg1;
- (bool)_systemUnderLock;
- (id)_toFieldCollapsedTextColor;
- (double)_toolbarHeightForNumberOfRows:(unsigned long long)arg1;
- (void)_updateAddressBookProperties;
- (void)_updateRecipientViewLayouts;
- (void)_updateSearchListControllerPopOverSizing;
- (void)_updateSearchResultsTable;
- (void)_updateShowingSearch;
- (void)_updateToField;
- (void)_updateToFieldRecipientsData;
- (void)_updateYOriginSearchListController;
- (long long)_userInterfaceStyleOverride;
- (void)addRecipient:(id)arg1;
- (void)addRecipients:(id)arg1;
- (double)additionalCatalystTopInset;
- (id)addressBookNotificationUpdater;
- (bool)allowedByScreenTime;
- (id)alternateAddressesAlertController;
- (void)autocompleteGroupDetailViewController:(id)arg1 didAskToRemoveGroup:(id)arg2;
- (void)autocompleteGroupDetailViewController:(id)arg1 didTapComposeRecipient:(id)arg2;
- (void)autocompleteGroupDetailViewControllerDidCancel:(id)arg1;
- (void)autocompleteResultsController:(id)arg1 didCollapseSelectedRecipient:(id)arg2;
- (void)autocompleteResultsController:(id)arg1 didExpandSelectedRecipient:(id)arg2;
- (void)autocompleteResultsController:(id)arg1 didRequestInfoAboutRecipient:(id)arg2;
- (void)autocompleteResultsController:(id)arg1 didSelectRecipient:(id)arg2 atIndex:(unsigned long long)arg3;
- (id)autocompleteResultsController:(id)arg1 preferredRecipientForRecipients:(id)arg2;
- (void)autocompleteResultsController:(id)arg1 tintColorForRecipient:(id)arg2 completion:(id /* block */)arg3;
- (bool)autocompleteResultsController:(id)arg1 willOverrideImageDataForRecipient:(id)arg2 completion:(id /* block */)arg3;
- (void)bringComposeRecipientViewToFront;
- (id)chatForIMHandle:(id)arg1;
- (bool)chooseSelectedSearchResultForComposeRecipientView:(id)arg1 context:(unsigned long long)arg2;
- (bool)collapseSelectedSearchResultForComposeRecipientView:(id)arg1;
- (double)collapsedHeight;
- (void)colorTypeForRecipient:(id)arg1 completion:(id /* block */)arg2;
- (id)composeRecipientView:(id)arg1 composeRecipientForAddress:(id)arg2;
- (id)composeRecipientView:(id)arg1 composeRecipientForContact:(id)arg2;
- (id)composeRecipientView:(id)arg1 contextMenuConfigurationForAtom:(id)arg2;
- (void)composeRecipientView:(id)arg1 didAddRecipient:(id)arg2;
- (void)composeRecipientView:(id)arg1 didChangeSize:(struct CGSize { double x1; double x2; })arg2;
- (void)composeRecipientView:(id)arg1 didFinishEnteringAddress:(id)arg2;
- (void)composeRecipientView:(id)arg1 didRemoveRecipient:(id)arg2;
- (void)composeRecipientView:(id)arg1 didSelectRecipients:(id)arg2;
- (void)composeRecipientView:(id)arg1 disambiguateRecipientForAtom:(id)arg2;
- (void)composeRecipientView:(id)arg1 showPersonCardForAtom:(id)arg2;
- (void)composeRecipientView:(id)arg1 textDidChange:(id)arg2;
- (double)composeRecipientViewOriginY;
- (void)composeRecipientViewRequestAddRecipient:(id)arg1;
- (void)composeRecipientViewReturnPressed:(id)arg1;
- (bool)composeRecipientViewShowingSearchResults:(id)arg1;
- (void)composeRecipientViewTabPressed:(id)arg1;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPicker:(id)arg1 didSelectContactProperty:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (id)contactPickerViewController;
- (id)contactStore;
- (id)contactsManager;
- (void)contactsManagerViewModelsDidChange:(id)arg1;
- (id)conversation;
- (id)conversationForRecipients:(id)arg1;
- (void)conversationPreferredServiceDidChange;
- (id)coreTelephonyClient;
- (id)currentConversationContext;
- (void)dealloc;
- (id)delegate;
- (void)didMoveToParentViewController:(id)arg1;
- (bool)didShowOneTimeErrorAlert;
- (void)dismissSearchResultsForComposeRecipientView:(id)arg1;
- (bool)expandSelectedSearchResultForComposeRecipientView:(id)arg1;
- (id)expandedRecipientsForGroupRecipient:(id)arg1;
- (double)fieldHeightOffset;
- (bool)finishedComposingRecipients;
- (bool)forceMMS;
- (id /* block */)gameCenterPickerBlock;
- (id)handleForRecipientNormalizedAddress:(id)arg1;
- (void)handlePendingRecipient:(id)arg1;
- (id)handlesForScreenTimePolicyCheck;
- (bool)hasEmailRecipientsInAddresses:(id)arg1;
- (bool)hasFailediMessageRecipients;
- (bool)hasIDSResultsForAllRecipients:(id)arg1;
- (bool)hasPendingiMessageRecipients;
- (bool)hasTimedOutRecipients;
- (bool)hasUnreachableEmergencyRecipient;
- (id)headerDecorationView;
- (bool)homogenizePreferredServiceForiMessage;
- (id)init;
- (id)initWithConversation:(id)arg1;
- (void)invalidateOutstandingIDStatusRequests;
- (bool)isBeingPresentedInMacDetailsView;
- (bool)isDisambiguating;
- (bool)isEditable;
- (bool)isGameCenterRecipient:(id)arg1;
- (bool)isMAIDGroupsEnabled;
- (bool)isPeoplePickerHidden;
- (bool)isSearchResultsHidden;
- (double)keyboardHeightWithAccessoryView;
- (bool)lastSentMessageWasNotDeliveredForConversation:(id)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })layoutMarginsForComposeRecipientView:(id)arg1;
- (void)loadView;
- (unsigned long long)numberOfRowsInToField;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)parentControllerDidResume:(bool)arg1 animating:(bool)arg2;
- (id)preferredColorTypeForExistingConversation:(id)arg1;
- (double)preferredMacToolbarHeight;
- (id)preferredRecipientForExistingConversationOfRecipients:(id)arg1;
- (id)preferredRecipientForNewContact:(id)arg1;
- (id)preferredRecipientForPendingUnifiedContact:(id)arg1;
- (id)preferredRecipientForRecipients:(id)arg1 forServiceType:(BOOL)arg2;
- (void)presentAlternateAddressesAlertForRecipient:(id)arg1;
- (bool)presentSearchResultsForComposeRecipientView:(id)arg1;
- (unsigned long long)presentationOptionsForRecipient:(id)arg1;
- (bool)preventAtomization;
- (id)recentContactForPresentedCNCard;
- (id)recipientAvailabilities;
- (void)recipientAvailibilitiesDidUpdate;
- (id)recipientAvailibityTimers;
- (id)recipientIsDuetSuggestion:(id)arg1;
- (void)recipientSelectionControllerDidChange;
- (void)recipientViewDidBecomeFirstResponder:(id)arg1;
- (void)recipientViewDidResignFirstResponder:(id)arg1;
- (bool)recipientViewShouldIgnoreFirstResponderChanges:(id)arg1;
- (id)recipients;
- (void)refreshComposeSendingServiceForAddresses:(id)arg1 withCompletionBlock:(id /* block */)arg2;
- (void)removeRecipient:(id)arg1;
- (void)reset;
- (void)resetSearchResults;
- (void)scrollSearchListControllerToTop:(bool)arg1;
- (struct CGPoint { double x1; double x2; })scrollSearchListControllerToTopContentOffset;
- (id)searchListController;
- (void)searchListController:(id)arg1 destinationsUpdated:(id)arg2;
- (long long)searchListController:(id)arg1 idStatusForIDSID:(id)arg2;
- (void)searchListControllerDidFinishSearch:(id)arg1;
- (void)searchListControllerDidScroll:(id)arg1;
- (void)selectNextSearchResultForComposeRecipientView:(id)arg1;
- (void)selectPreviousSearchResultForComposeRecipientView:(id)arg1;
- (void)sendUpdateRecipientForAtom:(id)arg1;
- (id)separator;
- (BOOL)serviceColorForRecipientAddresses:(id)arg1;
- (BOOL)serviceTypeForRecipient:(id)arg1;
- (void)setAddressBookNotificationUpdater:(id)arg1;
- (void)setAllowedByScreenTime:(bool)arg1;
- (void)setAlternateAddressesAlertController:(id)arg1;
- (void)setContactPickerViewController:(id)arg1;
- (void)setContactStore:(id)arg1;
- (void)setContactsManager:(id)arg1;
- (void)setConversation:(id)arg1;
- (void)setCoreTelephonyClient:(id)arg1;
- (void)setCurrentConversationContext:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDidShowOneTimeErrorAlert:(bool)arg1;
- (void)setEditable:(bool)arg1;
- (void)setForceMMS:(bool)arg1;
- (void)setGameCenterPickedHandles:(id)arg1 playerNames:(id)arg2;
- (void)setGameCenterPickerBlock:(id /* block */)arg1;
- (void)setHeaderDecorationView:(id)arg1;
- (void)setIsDisambiguating:(bool)arg1;
- (void)setKeyboardHeightWithAccessoryView:(double)arg1;
- (void)setNumberOfRowsInToField:(unsigned long long)arg1;
- (void)setPeoplePickerHidden:(bool)arg1;
- (void)setPreventAtomization:(bool)arg1;
- (void)setRecentContactForPresentedCNCard:(id)arg1;
- (void)setRecipientAvailabilities:(id)arg1;
- (void)setRecipientAvailibityTimers:(id)arg1;
- (void)setSearchListController:(id)arg1;
- (void)setSearchResultsHidden:(bool)arg1;
- (void)setSeparator:(id)arg1;
- (void)setToField:(id)arg1;
- (void)setToFieldPlaceholderLabel:(id)arg1;
- (void)setToFieldScrollingView:(id)arg1;
- (bool)shouldShowVerifiedIconForRecipient:(id)arg1;
- (bool)shouldSuppressSearchResultsTable;
- (void)stopCheckingRecipientAvailabilityAndRemoveAllTimers;
- (id)toField;
- (id)toFieldAsUIView;
- (id)toFieldContainerView;
- (bool)toFieldIsFirstResponder;
- (id)toFieldPlaceholderLabel;
- (id)toFieldScrollingView;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateScreenTimePolicy;
- (void)viewDidAppearDeferredSetup;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;

@end
