
@interface CSUSceneNetV5Configuration : NSObject {
    NSString * _aestheticsAttributeVocabularyName;
    NSString * _aestheticsAttributesTensorName;
    NSString * _aestheticsGlobalScoreVocabularyName;
    NSString * _aestheticsGlobalScoresTensorName;
    CSUSceneNetV5AestheticsTaxonomy * _aestheticsTaxonomy;
    NSString * _aestheticsTaxonomyPath;
    NSString * _detectionCoordinateOffsetMapName;
    bool  _detectionHeadIsSoftmax;
    float  _detectionNMSThreshold;
    NSString * _detectionScoreHeatMapName;
    CSUSceneNetV5DetectionTaxonomy * _detectionTaxonomy;
    NSString * _detectionTaxonomyPath;
    NSString * _detectionVocabularyName;
    NSString * _entityNetClassificationTensorName;
    NSString * _entityNetVocabularyName;
    NSString * _espressoNetworkPath;
    int  _executionEngine;
    NSString * _fingerprintEmbeddingTensorName;
    NSString * _fingerprintModelPath;
    NSString * _hierarchicalSceneClassificationVocabularyName;
    NSString * _inputImageTensorName;
    CSUPixelBufferDescriptor * _inputPixelBufferDescriptor;
    NSString * _leafSceneClassificationVocabularyName;
    long long  _revision;
    CSUPixelBufferDescriptor * _saliencyAttentionMapBufferDescriptor;
    NSString * _saliencyAttentionTensorName;
    CSUPixelBufferDescriptor * _saliencyObjectnessMapBufferDescriptor;
    NSString * _saliencyObjectnessTensorName;
    NSString * _sceneClassificationTensorName;
    NSString * _scenePrintTensorName;
    CSUSceneNetV5SceneTaxonomy * _sceneTaxonomy;
    NSString * _sceneTaxonomyPath;
}

@property (nonatomic, readonly) NSString *aestheticsAttributeVocabularyName;
@property (nonatomic, readonly, copy) NSString *aestheticsAttributesTensorName;
@property (nonatomic, readonly) NSString *aestheticsGlobalScoreVocabularyName;
@property (nonatomic, readonly, copy) NSString *aestheticsGlobalScoresTensorName;
@property (nonatomic, readonly) CSUSceneNetV5AestheticsTaxonomy *aestheticsTaxonomy;
@property (nonatomic, readonly, copy) NSString *aestheticsTaxonomyPath;
@property (nonatomic, readonly, copy) NSString *detectionCoordinateOffsetMapName;
@property (nonatomic, readonly) bool detectionHeadIsSoftmax;
@property (nonatomic, readonly) float detectionNMSThreshold;
@property (nonatomic, readonly, copy) NSString *detectionScoreHeatMapName;
@property (nonatomic, readonly) CSUSceneNetV5DetectionTaxonomy *detectionTaxonomy;
@property (nonatomic, readonly, copy) NSString *detectionTaxonomyPath;
@property (nonatomic, readonly) NSString *detectionVocabularyName;
@property (nonatomic, readonly, copy) NSString *entityNetClassificationTensorName;
@property (nonatomic, readonly) NSString *entityNetVocabularyName;
@property (nonatomic, readonly, copy) NSString *espressoNetworkPath;
@property int executionEngine;
@property (nonatomic, readonly, copy) NSString *fingerprintEmbeddingTensorName;
@property (nonatomic, readonly, copy) NSString *fingerprintModelPath;
@property (nonatomic, readonly) NSString *hierarchicalSceneClassificationVocabularyName;
@property (nonatomic, readonly, copy) NSString *inputImageTensorName;
@property (nonatomic, readonly) CSUPixelBufferDescriptor *inputPixelBufferDescriptor;
@property (nonatomic, readonly) NSString *leafSceneClassificationVocabularyName;
@property (nonatomic, readonly) long long revision;
@property (nonatomic, readonly) CSUPixelBufferDescriptor *saliencyAttentionMapBufferDescriptor;
@property (nonatomic, readonly, copy) NSString *saliencyAttentionTensorName;
@property (nonatomic, readonly) CSUPixelBufferDescriptor *saliencyObjectnessMapBufferDescriptor;
@property (nonatomic, readonly, copy) NSString *saliencyObjectnessTensorName;
@property (nonatomic, readonly, copy) NSString *sceneClassificationTensorName;
@property (nonatomic, readonly, copy) NSString *scenePrintTensorName;
@property (nonatomic, readonly) CSUSceneNetV5SceneTaxonomy *sceneTaxonomy;
@property (nonatomic, readonly, copy) NSString *sceneTaxonomyPath;

+ (long long)_resolvedRevision:(long long)arg1;
+ (id)availableRevisions;
+ (id)sceneNetV5ConfigurationForRevision:(long long)arg1 error:(id*)arg2;

- (void).cxx_destruct;
- (id)aestheticsAttributeVocabularyName;
- (id)aestheticsAttributesTensorName;
- (id)aestheticsGlobalScoreVocabularyName;
- (id)aestheticsGlobalScoresTensorName;
- (id)aestheticsTaxonomy;
- (id)aestheticsTaxonomyPath;
- (id)detectionCoordinateOffsetMapName;
- (bool)detectionHeadIsSoftmax;
- (float)detectionNMSThreshold;
- (id)detectionScoreHeatMapName;
- (id)detectionTaxonomy;
- (id)detectionTaxonomyPath;
- (id)detectionVocabularyName;
- (id)entityNetClassificationTensorName;
- (id)entityNetVocabularyName;
- (id)espressoNetworkPath;
- (int)executionEngine;
- (id)fingerprintEmbeddingTensorName;
- (id)fingerprintModelPath;
- (id)hierarchicalSceneClassificationVocabularyName;
- (id)initSceneNetV5ConfigurationForRevision:(long long)arg1 espressoNetPath:(id)arg2 inputImageTensorName:(id)arg3 inputImageDimension:(unsigned long long)arg4 inputImageBytesPerRowAlignment:(unsigned long long)arg5 scenePrintTensorName:(id)arg6 sceneClassificationTensorName:(id)arg7 sceneTaxonomyPath:(id)arg8 aestheticsAttributesTensorName:(id)arg9 aestheticsGlobalScoresTensorName:(id)arg10 aestheticsTaxonomyPath:(id)arg11 detectionScoreHeatMapName:(id)arg12 detectionCoordinateOffsetMapName:(id)arg13 detectionTaxonomyPath:(id)arg14 detectionHeadIsSoftmax:(bool)arg15 detectionNMSThreshold:(float)arg16 saliencyAttentionTensorName:(id)arg17 saliencyAMapDimension:(unsigned long long)arg18 saliencyObjectnessTensorName:(id)arg19 saliencyOMapDimension:(unsigned long long)arg20 fingerprintEmbeddingTensorName:(id)arg21 fingerprintModelPath:(id)arg22 entityNetClassificationTensorName:(id)arg23 leafSceneClassificationVocabularyName:(id)arg24 hierarchicalSceneClassificationVocabularyName:(id)arg25 entityNetVocabularyName:(id)arg26 aestheticsAttributeVocabularyName:(id)arg27 aestheticsGlobalScoreVocabularyName:(id)arg28 detectionVocabularyName:(id)arg29;
- (id)inputImageTensorName;
- (id)inputPixelBufferDescriptor;
- (id)leafSceneClassificationVocabularyName;
- (id)newCityNatureConfigurationAndReturnError:(id*)arg1;
- (id)newClassifierAlphaConfigurationAndReturnError:(id*)arg1;
- (id)newClassifierBetaConfigurationAndReturnError:(id*)arg1;
- (id)newJunkHierarchicalConfigurationAndReturnError:(id*)arg1;
- (id)newJunkLeafConfigurationAndReturnError:(id*)arg1;
- (long long)revision;
- (id)saliencyAttentionMapBufferDescriptor;
- (id)saliencyAttentionTensorName;
- (id)saliencyObjectnessMapBufferDescriptor;
- (id)saliencyObjectnessTensorName;
- (id)sceneClassificationTensorName;
- (id)scenePrintTensorName;
- (id)sceneTaxonomy;
- (id)sceneTaxonomyPath;
- (void)setExecutionEngine:(int)arg1;

@end
