
@interface KGMemoryGraphStore : NSObject <KGGraphStore> {
    NSMutableDictionary * _edgeIdentifiersByLabel;
    KGMutableDirectedBinaryAdjacency * _edgeIdentifiersBySourceNodeIdentifier;
    KGMutableDirectedBinaryAdjacency * _edgeIdentifiersByTargetNodeIdentifier;
    NSUUID * _graphIdentifier;
    unsigned long long  _graphVersion;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSMutableDictionary * _memoryEdgeByIdentifier;
    NSMutableDictionary * _memoryNodeByIdentifier;
    unsigned long long  _nextEdgeIdentifier;
    unsigned long long  _nextNodeIdentifier;
    NSMutableDictionary * _nodeIdentifiersByLabel;
    NSURL * _url;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSMutableDictionary *edgeIdentifiersByLabel;
@property (nonatomic, readonly) KGMutableDirectedBinaryAdjacency *edgeIdentifiersBySourceNodeIdentifier;
@property (nonatomic, readonly) KGMutableDirectedBinaryAdjacency *edgeIdentifiersByTargetNodeIdentifier;
@property (nonatomic, readonly) NSUUID *graphIdentifier;
@property (nonatomic) unsigned long long graphVersion;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) struct os_unfair_lock_s { unsigned int x1; } lock;
@property (nonatomic, readonly) NSMutableDictionary *memoryEdgeByIdentifier;
@property (nonatomic, readonly) NSMutableDictionary *memoryNodeByIdentifier;
@property (nonatomic) unsigned long long nextEdgeIdentifier;
@property (nonatomic) unsigned long long nextNodeIdentifier;
@property (nonatomic, readonly) NSMutableDictionary *nodeIdentifiersByLabel;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSURL *url;

+ (bool)copyFromURL:(id)arg1 toURL:(id)arg2 error:(id*)arg3;
+ (bool)destroyAtURL:(id)arg1 error:(id*)arg2;
+ (bool)migrateFromURL:(id)arg1 toURL:(id)arg2 error:(id*)arg3;
+ (id)persistentStoreFileExtension;

- (void).cxx_destruct;
- (id)_edgeIdentifiersForNodeIdentifier:(unsigned long long)arg1;
- (id)_lock_allEdgeIdentifiers;
- (id)_lock_allNodeIdentifiers;
- (id)_lock_arrayOfEdgesWithIdentifiers:(id)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (id)_lock_arrayOfNodesWithIdentifiers:(id)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (id)_lock_edgeIdentifiersMatchingFilter:(id)arg1 intersectingIdentifiers:(id)arg2 error:(id*)arg3;
- (id)_lock_edgeIdentifiersWithStartNodeIdentifiers:(id)arg1 edgeDirection:(unsigned long long)arg2 error:(id*)arg3;
- (id)_lock_intersectionOfEdgesWithLabels:(id)arg1;
- (id)_lock_intersectionOfNodesWithLabels:(id)arg1;
- (id)_lock_nodeIdentifiersOfEdgesWithIdentifiers:(id)arg1 edgeDirection:(unsigned long long)arg2 error:(id*)arg3;
- (id)_lock_snapshotEdgeForIdentifier:(unsigned long long)arg1 reusableNode:(id)arg2 entityFactory:(id)arg3;
- (id)_lock_snapshotNodeForIdentifier:(unsigned long long)arg1 entityFactory:(id)arg2;
- (id)_lock_sourcesByTargetWithEdgeIdentifiers:(id)arg1 error:(id*)arg2;
- (id)_lock_targetsBySourceWithEdgeIdentifiers:(id)arg1 error:(id*)arg2;
- (id)_lock_unionOfEdgesWithLabels:(id)arg1;
- (id)_lock_unionOfNodesWithLabels:(id)arg1;
- (bool)_removeEdgesForMemoryNode:(id)arg1 error:(id*)arg2;
- (bool)_removeMemoryEdge:(id)arg1 error:(id*)arg2;
- (bool)_removeNode:(unsigned long long)arg1 error:(id*)arg2;
- (bool)addEdges:(id)arg1 error:(id*)arg2;
- (bool)addNodes:(id)arg1 error:(id*)arg2;
- (id)arrayOfEdgesWithIdentifiers:(id)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (id)arrayOfNodesWithIdentifiers:(id)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (bool)beginTransactionWithError:(id*)arg1;
- (id)changesAfterToken:(id)arg1 transactionLimit:(long long)arg2 error:(id*)arg3;
- (void)close;
- (bool)commitTransactionWithError:(id*)arg1;
- (bool)copyToURL:(id)arg1 error:(id*)arg2;
- (id)edgeChangesAfterToken:(id)arg1 transactionLimit:(long long)arg2 edgeFilter:(id)arg3 error:(id*)arg4;
- (id)edgeForIdentifier:(unsigned long long)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (id)edgeIdentifiers:(id)arg1 sortedByFloatPropertyForName:(id)arg2 ascending:(bool)arg3 limit:(long long)arg4 error:(id*)arg5;
- (id)edgeIdentifiers:(id)arg1 sortedByIntegerPropertyForName:(id)arg2 ascending:(bool)arg3 limit:(long long)arg4 error:(id*)arg5;
- (id)edgeIdentifiers:(id)arg1 sortedByStringPropertyForName:(id)arg2 ascending:(bool)arg3 limit:(long long)arg4 error:(id*)arg5;
- (id)edgeIdentifiersBetween:(id)arg1 endNodeIdentifiers:(id)arg2 edgeFilter:(id)arg3 edgeDirection:(unsigned long long)arg4 error:(id*)arg5;
- (id)edgeIdentifiersByLabel;
- (id)edgeIdentifiersBySourceNodeIdentifier;
- (id)edgeIdentifiersByTargetNodeIdentifier;
- (id)edgeIdentifiersForNodeIdentifier:(unsigned long long)arg1 error:(id*)arg2;
- (id)edgeIdentifiersMatchingFilter:(id)arg1 intersectingIdentifiers:(id)arg2 error:(id*)arg3;
- (id)edgeIdentifiersWithStartNodeIdentifiers:(id)arg1 edgeDirection:(unsigned long long)arg2 error:(id*)arg3;
- (id)edgeIdentifiersWithStartNodeIdentifiers:(id)arg1 intersectingEdgeIdentifiers:(id)arg2 edgeDirection:(unsigned long long)arg3 error:(id*)arg4;
- (id)edgeLabels;
- (id)graphIdentifier;
- (unsigned long long)graphVersion;
- (id)init;
- (id)initForSubclasses;
- (id)insertEdgeWithIdentifier:(unsigned long long)arg1 labels:(id)arg2 properties:(id)arg3 sourceNodeIdentifier:(unsigned long long)arg4 targetNodeIdentifier:(unsigned long long)arg5 error:(id*)arg6;
- (id)insertNodeWithIdentifier:(unsigned long long)arg1 labels:(id)arg2 properties:(id)arg3 error:(id*)arg4;
- (id)labelsOfEdgesForIdentifiers:(id)arg1;
- (id)labelsOfNodesForIdentifiers:(id)arg1;
- (struct os_unfair_lock_s { unsigned int x1; })lock;
- (id)memoryEdgeByIdentifier;
- (id)memoryNodeByIdentifier;
- (id)neighborNodeIdentifiersWithStartNodeIdentifiers:(id)arg1 edgeDirection:(unsigned long long)arg2 edgeFilter:(id)arg3 error:(id*)arg4;
- (unsigned long long)nextEdgeIdentifier;
- (unsigned long long)nextNodeIdentifier;
- (bool)noFatalError;
- (id)nodeChangesAfterToken:(id)arg1 transactionLimit:(long long)arg2 nodeFilter:(id)arg3 error:(id*)arg4;
- (id)nodeForIdentifier:(unsigned long long)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (id)nodeIdentifiers:(id)arg1 sortedByFloatPropertyForName:(id)arg2 ascending:(bool)arg3 limit:(long long)arg4 error:(id*)arg5;
- (id)nodeIdentifiers:(id)arg1 sortedByIntegerPropertyForName:(id)arg2 ascending:(bool)arg3 limit:(long long)arg4 error:(id*)arg5;
- (id)nodeIdentifiers:(id)arg1 sortedByStringPropertyForName:(id)arg2 ascending:(bool)arg3 limit:(long long)arg4 error:(id*)arg5;
- (id)nodeIdentifiers:(id)arg1 sortedByUnsignedIntegerPropertyForName:(id)arg2 ascending:(bool)arg3 limit:(long long)arg4 error:(id*)arg5;
- (id)nodeIdentifiersByLabel;
- (id)nodeIdentifiersMatchingFilter:(id)arg1 intersectingIdentifiers:(id)arg2 error:(id*)arg3;
- (id)nodeIdentifiersOfEdgesWithIdentifiers:(id)arg1 edgeDirection:(unsigned long long)arg2 error:(id*)arg3;
- (id)nodeLabels;
- (bool)openWithMode:(unsigned long long)arg1 error:(id*)arg2;
- (id)orderedArrayOfEdgesWithIdentifiers:(id)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (id)orderedArrayOfNodesWithIdentifiers:(id)arg1 entityFactory:(id)arg2 error:(id*)arg3;
- (id)propertiesForEdgesWithIdentifiers:(id)arg1 propertyName:(id)arg2 error:(id*)arg3;
- (id)propertiesForNodesWithIdentifiers:(id)arg1 propertyName:(id)arg2 error:(id*)arg3;
- (bool)removeEdgeForIdentifier:(unsigned long long)arg1 error:(id*)arg2;
- (bool)removeEdgesForIdentifiers:(id)arg1 error:(id*)arg2;
- (bool)removeNodeForIdentifier:(unsigned long long)arg1 error:(id*)arg2;
- (bool)removeNodesForIdentifiers:(id)arg1 error:(id*)arg2;
- (bool)rollbackTransactionWithError:(id*)arg1;
- (void)setGraphVersion:(unsigned long long)arg1;
- (void)setNextEdgeIdentifier:(unsigned long long)arg1;
- (void)setNextNodeIdentifier:(unsigned long long)arg1;
- (id)sourcesByTargetWithEdgeIdentifiers:(id)arg1 error:(id*)arg2;
- (id)targetsBySourceWithEdgeIdentifiers:(id)arg1 error:(id*)arg2;
- (id)transitiveClosureNeighborNodeIdentifiersWithStartNodeIdentifiers:(id)arg1 edgeDirection:(unsigned long long)arg2 edgeFilter:(id)arg3 error:(id*)arg4;
- (bool)updateEdgeForIdentifier:(unsigned long long)arg1 withProperties:(id)arg2 error:(id*)arg3;
- (bool)updateNodeForIdentifier:(unsigned long long)arg1 withProperties:(id)arg2 error:(id*)arg3;
- (id)url;

@end
