
@interface SBIconDragManager : NSObject <SBFolderControllerDragDelegate, SBHIconDragAutoScrollAssistantDelegate, SBHUndoObserving, SBIconListViewDragDelegate, SBIconListViewDragObserver, SBIconViewDragDelegate> {
    SBHIconDragAutoScrollAssistant * _autoScrollAssistant;
    <SBIconDragManagerDelegate> * _delegate;
    SBIconDraggingEditContext * _draggingEditContext;
    NSMapTable * _iconDrags;
    bool  _modifyingRootFolder;
    NSHashTable * _registeredUndoManagers;
    NSMutableDictionary * _revertingReplacementIndexPaths;
    NSMutableArray * _runLoopWaitBlocks;
    NSMutableArray * _singleUseDragWindows;
    NSMapTable * _uniqueIdentifiersPerDragSession;
    NSMapTable * _uniqueIdentifiersPerDropSession;
    struct __CFRunLoopObserver { } * _waitRunLoopObserver;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBIconDragManagerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SBIconDraggingEditContext *draggingEditContext;
@property (readonly) unsigned long long hash;
@property (getter=isIconDragging, nonatomic, readonly) bool iconDragging;
@property (getter=isModifyingRootFolder, nonatomic) bool modifyingRootFolder;
@property (readonly) Class superclass;
@property (getter=isTrackingActiveOrDroppingIconDrags, nonatomic, readonly) bool trackingActiveOrDroppingIconDrags;
@property (getter=isTrackingDroppingIconDrags, nonatomic, readonly) bool trackingDroppingIconDrags;
@property (getter=isTrackingMultipleIconDrags, nonatomic, readonly) bool trackingMultipleIconDrags;
@property (getter=isTrackingMultipleItemIconDrags, nonatomic, readonly) bool trackingMultipleItemIconDrags;
@property (getter=isTrackingUserActiveIconDrags, nonatomic, readonly) bool trackingUserActiveIconDrags;

+ (void)cancelAllDrags;
+ (void)enumerateAppDragContextsInDragItems:(id)arg1 usingBlock:(id /* block */)arg2;
+ (void)enumerateMedusaPlatterDragPreviewsInDragItems:(id)arg1 usingBlock:(id /* block */)arg2;

- (void).cxx_destruct;
- (long long)_animationTypeForGridSizeClass:(unsigned long long)arg1;
- (id)_applicationBundleIdentifierForDragItem:(id)arg1;
- (void)_cleanUpAllDraggingState;
- (void)_handleScaleAdjustmentForDropSession:(id)arg1 currentListView:(id)arg2;
- (id)_iconForDragItem:(id)arg1 inIconListView:(id)arg2;
- (id)_iconIdentifierForDragItem:(id)arg1;
- (id)_iconViewForDragItem:(id)arg1 inIconListView:(id)arg2;
- (void)_invalidateAutoScrollAssistant;
- (bool)_isTrackingDrag:(id)arg1;
- (bool)_isTrackingDragWithIdentifier:(id)arg1;
- (void)_removeDraggedIconViewFromLayout:(id)arg1 dragIdentifier:(id)arg2;
- (id)_replaceDraggedIconViewWithPlaceholder:(id)arg1;
- (bool)_shouldPerformRippleAnimationForInsertingDragItem:(id)arg1 toIconListView:(id)arg2;
- (void)_startTrackingDragWithIdentifier:(id)arg1 session:(id)arg2;
- (void)_stopTrackingDragIfPossibleWithIdentifier:(id)arg1;
- (void)_stopTrackingDragWithIdentifier:(id)arg1;
- (void)_teardownWaitRunloopObserverIfNeeded;
- (void)_updateAutoScrollAssistantForDropSession:(id)arg1;
- (void)_updateDragPreviewIconViewForDropSession:(id)arg1 inIconListView:(id)arg2;
- (void)_updateDragPreviewsForEditingState:(bool)arg1 animated:(bool)arg2;
- (id)_windowForDragPreviewsForPlatterView:(id)arg1 forWindowScene:(id)arg2;
- (void)addAppLocalContextsFromDragItems:(id)arg1 session:(id)arg2 toDragWithIdentifier:(id)arg3;
- (void)addIcons:(id)arg1 intoFolderIcon:(id)arg2 openFolderOnFinish:(bool)arg3;
- (void)addPlatterViewToMedusaDragOffscreenWindow:(id)arg1 forWindowScene:(id)arg2;
- (void)addPlatterViewToMedusaDragOffscreenWindow:(id)arg1 forWindowScene:(id)arg2 interfaceOrientation:(long long)arg3;
- (double)additionalDragLiftScaleForIconView:(id)arg1;
- (id)allDragIdentifiers;
- (bool)allowsNestedFolders;
- (id)appDragLocalContextForDragItem:(id)arg1;
- (void)autoScrollAssistant:(id)arg1 triggeredAutoScrollInDirection:(long long)arg2;
- (void)beginModifyingRootFolder;
- (bool)canAcceptDropInSession:(id)arg1 inIconListView:(id)arg2;
- (bool)canHandleIconDropSession:(id)arg1 inIconListView:(id)arg2;
- (bool)canMakeIconViewRecipient:(id)arg1;
- (bool)canSnapToGridInIconLocation:(id)arg1;
- (void)cancelAllDrags;
- (void)cancelEditingAndAllDrags;
- (void)captureInitialIconStateToDragContext:(id)arg1;
- (void)changeStateOfDragWithIdentifier:(id)arg1 toState:(long long)arg2;
- (void)clearAllUndoRegistrations;
- (void)compactAndLayoutRootIconLists;
- (void)compactAndLayoutRootIconListsWithDuration:(double)arg1;
- (void)concludeIconDrop:(id)arg1;
- (unsigned long long)countOfTrackedDragsOriginatingFromOrDroppingIntoIconView:(id)arg1;
- (void)createIconsFromDragItemsIfNecessary:(id)arg1 withDragIdentifier:(id)arg2;
- (id)createNewFolderFromRecipientIcon:(id)arg1 grabbedIcon:(id)arg2;
- (void)dealloc;
- (double)defaultIconLayoutAnimationDuration;
- (double)delayAfterAfterLiftPreviewToBeginEditing;
- (id)delegate;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)didUndo;
- (bool)doesIconLocationRepresentRealIconPosition:(id)arg1;
- (bool)doesIconViewRepresentRealIconPosition:(id)arg1;
- (id)dragPlaceholderGridPathForDragWithIdentifier:(id)arg1;
- (id)dragPlaceholderPathForDragWithIdentifier:(id)arg1;
- (id)draggedIconForIdentifier:(id)arg1;
- (id)draggedIconIdentifiersForDragDropSession:(id)arg1;
- (id)draggedIconsForIdentifiers:(id)arg1;
- (id)draggingEditContext;
- (bool)dragsSupportSystemDragsForIconView:(id)arg1;
- (void)endModifyingRootFolder;
- (void)enumerateIconDragContextsUsingBlock:(id /* block */)arg1;
- (void)enumerateIconDragIdentifiersUsingBlock:(id /* block */)arg1;
- (id)firstHiddenIconIdentifierInDrag:(id)arg1;
- (void)folderController:(id)arg1 draggedIconShouldDropFromListView:(id)arg2;
- (bool)folderController:(id)arg1 iconListView:(id)arg2 canHandleIconDropSession:(id)arg3;
- (id)folderController:(id)arg1 iconListView:(id)arg2 customSpringAnimationBehaviorForDroppingItem:(id)arg3;
- (void)folderController:(id)arg1 iconListView:(id)arg2 iconDragItem:(id)arg3 willAnimateDropWithAnimator:(id)arg4;
- (void)folderController:(id)arg1 iconListView:(id)arg2 iconDropSession:(id)arg3 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg4;
- (void)folderController:(id)arg1 iconListView:(id)arg2 iconDropSessionDidEnter:(id)arg3;
- (void)folderController:(id)arg1 iconListView:(id)arg2 iconDropSessionDidExit:(id)arg3;
- (id)folderController:(id)arg1 iconListView:(id)arg2 iconDropSessionDidUpdate:(id)arg3;
- (id)folderController:(id)arg1 iconListView:(id)arg2 iconViewForDroppingIconDragItem:(id)arg3 proposedIconView:(id)arg4;
- (void)folderController:(id)arg1 iconListView:(id)arg2 performIconDrop:(id)arg3;
- (id)folderController:(id)arg1 iconListView:(id)arg2 previewForDroppingIconDragItem:(id)arg3 proposedPreview:(id)arg4;
- (bool)folderController:(id)arg1 iconListView:(id)arg2 shouldAllowSpringLoadedInteractionForIconDropSession:(id)arg3 onIconView:(id)arg4;
- (void)folderController:(id)arg1 iconListView:(id)arg2 springLoadedInteractionForIconDragDidCompleteOnIconView:(id)arg3;
- (void)folderController:(id)arg1 iconListView:(id)arg2 willUseIconView:(id)arg3 forDroppingIconDragItem:(id)arg4;
- (id)fullIndexPathForRevertingIcon:(id)arg1 context:(id)arg2;
- (id)iconDragContextForDragDropSession:(id)arg1;
- (id)iconDragContextForDragItem:(id)arg1;
- (id)iconDragContextForDragSession:(id)arg1;
- (id)iconDragContextForDragWithIdentifier:(id)arg1;
- (id)iconDragContextForDropSession:(id)arg1;
- (void)iconDropSession:(id)arg1 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg2 inIconListView:(id)arg3;
- (void)iconDropSessionDidEnd:(id)arg1;
- (void)iconDropSessionDidEnd:(id)arg1 identifier:(id)arg2 draggedIconIdentifiers:(id)arg3;
- (void)iconDropSessionDidEnter:(id)arg1 identifier:(id)arg2 draggedIconIdentifiers:(id)arg3 inIconListView:(id)arg4;
- (void)iconDropSessionDidEnter:(id)arg1 inIconListView:(id)arg2;
- (void)iconDropSessionDidExit:(id)arg1 fromIconListView:(id)arg2;
- (void)iconDropSessionDidExitWithIdentifier:(id)arg1 fromIconListView:(id)arg2;
- (id)iconDropSessionDidUpdate:(id)arg1 inIconListView:(id)arg2;
- (void)iconDropSessionWithIdentifier:(id)arg1 draggedIconIdentifiers:(id)arg2 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg3 inIconListView:(id)arg4;
- (id)iconLayoutHider;
- (unsigned long long)iconLayoutHidingOptions;
- (bool)iconListView:(id)arg1 canHandleIconDropSession:(id)arg2;
- (void)iconListView:(id)arg1 concludeIconDrop:(id)arg2;
- (id)iconListView:(id)arg1 customSpringAnimationBehaviorForDroppingItem:(id)arg2;
- (void)iconListView:(id)arg1 iconDragItem:(id)arg2 willAnimateDropWithAnimator:(id)arg3;
- (void)iconListView:(id)arg1 iconDropSession:(id)arg2 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg3;
- (void)iconListView:(id)arg1 iconDropSessionDidEnd:(id)arg2;
- (void)iconListView:(id)arg1 iconDropSessionDidEnter:(id)arg2;
- (void)iconListView:(id)arg1 iconDropSessionDidExit:(id)arg2;
- (id)iconListView:(id)arg1 iconDropSessionDidUpdate:(id)arg2;
- (id)iconListView:(id)arg1 iconViewForDroppingIconDragItem:(id)arg2 proposedIconView:(id)arg3;
- (void)iconListView:(id)arg1 performIconDrop:(id)arg2;
- (id)iconListView:(id)arg1 previewForDroppingIconDragItem:(id)arg2 proposedPreview:(id)arg3;
- (bool)iconListView:(id)arg1 shouldAllowSpringLoadedInteractionForIconDropSession:(id)arg2 onIconView:(id)arg3;
- (void)iconListView:(id)arg1 springLoadedInteractionForIconDragDidCompleteOnIconView:(id)arg2;
- (void)iconListView:(id)arg1 willUseIconView:(id)arg2 forDroppingIconDragItem:(id)arg3;
- (id)iconListViewForIndexPath:(id)arg1;
- (bool)iconView:(id)arg1 canAddDragItemsToSession:(id)arg2;
- (void)iconView:(id)arg1 didEndDragSession:(id)arg2 withOperation:(unsigned long long)arg3;
- (void)iconView:(id)arg1 dragLiftAnimationDidChangeDirection:(long long)arg2;
- (id)iconView:(id)arg1 dragPreviewForItem:(id)arg2 session:(id)arg3 previewParameters:(id)arg4;
- (long long)iconView:(id)arg1 draggingStartLocationWithProposedStartLocation:(long long)arg2;
- (void)iconView:(id)arg1 item:(id)arg2 willAnimateDragCancelWithAnimator:(id)arg3;
- (void)iconView:(id)arg1 session:(id)arg2 willEndWithOperation:(unsigned long long)arg3;
- (void)iconView:(id)arg1 willAddDragItems:(id)arg2 toSession:(id)arg3;
- (void)iconView:(id)arg1 willAnimateDragLiftWithAnimator:(id)arg2 session:(id)arg3;
- (void)iconView:(id)arg1 willUsePreviewForCancelling:(id)arg2 targetIconView:(id)arg3;
- (bool)iconViewCanBeginDrags:(id)arg1;
- (void)iconViewWillBeginDrag:(id)arg1 session:(id)arg2;
- (id)iconViewWillCancelDrag:(id)arg1;
- (void)informQuickActionPlatterDidFinishPresentation:(id)arg1;
- (id)init;
- (bool)isEditing;
- (bool)isEditingAllowedForListView:(id)arg1;
- (bool)isEditingForListView:(id)arg1;
- (bool)isIconContentPossiblyVisibleOverApplication;
- (bool)isIconDragging;
- (bool)isManagingTemporarilyRemovedIcon:(id)arg1;
- (bool)isModifyingRootFolder;
- (bool)isPredictableDraggingEnabled;
- (bool)isRootFolderContentVisible;
- (bool)isSnapToGridAllowed;
- (bool)isSnapToGridEnabledForDragWithIdentifier:(id)arg1 iconLocation:(id)arg2 listModel:(id)arg3 placeholderGridSizeClass:(unsigned long long)arg4;
- (bool)isTrackingActiveDragOfIcon:(id)arg1;
- (bool)isTrackingActiveOrDroppingIconDrags;
- (bool)isTrackingDragInUserActiveLiftPreviewOriginatingFromIconView:(id)arg1;
- (bool)isTrackingDragMatchingPredicate:(id /* block */)arg1;
- (bool)isTrackingDragOfIcon:(id)arg1;
- (bool)isTrackingDragOriginatingFromIconView:(id)arg1;
- (bool)isTrackingDragOriginatingFromOrDroppingIntoIconView:(id)arg1 otherThanDragWithIdentifier:(id)arg2;
- (bool)isTrackingDragWithGhostTreatmentForIcon:(id)arg1;
- (bool)isTrackingDropIntoDestinationIconView:(id)arg1;
- (bool)isTrackingDroppingIconDrags;
- (bool)isTrackingMultipleIconDrags;
- (bool)isTrackingMultipleItemIconDrags;
- (bool)isTrackingUserActiveDragOriginatingFromIconView:(id)arg1;
- (bool)isTrackingUserActiveIconDrags;
- (bool)isTrackingWidgetIconDrags;
- (bool)isTrackingWidgetStackIconDrags;
- (bool)isUndoSupportEnabled;
- (id)launchActionsForIconView:(id)arg1;
- (id)launchURLForIconView:(id)arg1;
- (void)layoutIconListsWithAnimationType:(long long)arg1 forceRelayout:(bool)arg2;
- (id)leafIconForIdentifier:(id)arg1;
- (id)leafIconsInList:(id)arg1 matchingApplicationBundleIdentifierOfIcons:(id)arg2;
- (unsigned long long)listGridCellInfoOptions;
- (id)localizedFolderNameForCombiningIcon:(id)arg1 withIcon:(id)arg2;
- (unsigned long long)maximumAllowedIconDroppingAnimationsForListView:(id)arg1;
- (id)model;
- (void)noteDragItemWasConsumedExternallyForDropSession:(id)arg1;
- (void)noteFolderBeganScrolling;
- (void)noteFolderControllerDidClose:(id)arg1;
- (void)noteFolderControllerWillClose:(id)arg1;
- (void)noteFolderControllerWillOpen;
- (void)noteIconManagerEditingDidChange;
- (void)noteIconTapped;
- (void)noteRootFolderDidMutate;
- (void)old_iconDropSessionWithIdentifier:(id)arg1 draggedIconIdentifiers:(id)arg2 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg3 inIconListView:(id)arg4;
- (void)old_performIconDrop:(id)arg1 identifier:(id)arg2 draggedIconIdentifiers:(id)arg3 inIconListView:(id)arg4;
- (void)performBeforeRunLoopWaitsUsingBlock:(id /* block */)arg1;
- (void)performBlocksBeforeRunLoopWait;
- (void)performIconDrop:(id)arg1 identifier:(id)arg2 draggedIconIdentifiers:(id)arg3 inIconListView:(id)arg4;
- (void)performIconDrop:(id)arg1 inIconListView:(id)arg2;
- (void)performSpringLoadedInteractionForIconDragOnIconView:(id)arg1;
- (long long)placeholderMovementForDragHitRegion:(unsigned long long)arg1 onGridCellIndex:(unsigned long long)arg2 iconIndex:(unsigned long long)arg3 inListView:(id)arg4 forDragWithIdentifier:(id)arg5 draggedIconIdentifiers:(id)arg6;
- (void)predictable_iconDropSessionWithIdentifier:(id)arg1 draggedIconIdentifiers:(id)arg2 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg3 inIconListView:(id)arg4;
- (void)predictable_performIconDrop:(id)arg1 identifier:(id)arg2 draggedIconIdentifiers:(id)arg3 inIconListView:(id)arg4;
- (void)pushExpandedIcon:(id)arg1 location:(id)arg2 context:(id)arg3 animated:(bool)arg4 completionHandler:(id /* block */)arg5;
- (void)pushExpandedIconView:(id)arg1 context:(id)arg2 animated:(bool)arg3 completionHandler:(id /* block */)arg4;
- (void)registerUndoWithUndoManager:(id)arg1 preparation:(id)arg2 draggedIcons:(id)arg3;
- (bool)removeAllDragPlaceholders;
- (bool)removeAllDragPlaceholdersInFolder:(id)arg1 passingTest:(id /* block */)arg2;
- (void)removeAllGrabbedIconViews;
- (bool)removeDragPlaceholdersForDragWithIdentifier:(id)arg1;
- (bool)removeDragPlaceholdersForDragWithIdentifier:(id)arg1 placeholderPath:(out id*)arg2;
- (void)removeEmptyFolders;
- (void)removeEmptyFoldersInFolder:(id)arg1;
- (void)removeNearestLeafIconsMatchingIcons:(id)arg1 inList:(id)arg2 dragContext:(id)arg3;
- (void)removePlatterViewFromMedusaDragOffscreenWindow:(id)arg1;
- (void)replaceAllBouncedIconsInContext:(id)arg1;
- (bool)replaceAllDragPlaceholdersWithReferencedIcons;
- (bool)replaceDragPlaceholderWithReferencedIcons:(id)arg1;
- (bool)replaceDragPlaceholdersWithReferencedIconsInDragWithIdentifier:(id)arg1;
- (void)resetWatchdogTimerForDragWithIdentifier:(id)arg1 timeout:(double)arg2;
- (void)revertActiveDragChanges;
- (void)revertDragChangesForDragWithIdentifier:(id)arg1;
- (bool)revertLocationForIcon:(id)arg1 toGridPath:(id)arg2;
- (bool)revertLocationForIcon:(id)arg1 toPath:(id)arg2;
- (bool)revertLocationsForIcons:(id)arg1 dragIdentifier:(id)arg2;
- (void)revertLocationsForIconsInAllListsForDragWithIdentifier:(id)arg1;
- (void)revertLocationsForIconsInList:(id)arg1 dragIdentifier:(id)arg2;
- (void)revertLocationsForUnplacedIconsInDragWithIdentifier:(id)arg1;
- (id)rootFolder;
- (void)setDelegate:(id)arg1;
- (void)setDraggingEditContext:(id)arg1;
- (void)setIndexPath:(id)arg1 whenRevertingIconsWithPathPrefix:(id)arg2;
- (void)setModifyingRootFolder:(bool)arg1;
- (bool)shouldAllowSpringLoadedInteractionForIconDropSession:(id)arg1 onIconView:(id)arg2;
- (bool)shouldBeginEditingWhenAddingDragItems;
- (bool)shouldBeginEditingWhenDragBegins;
- (bool)shouldBeginEditingWhenLiftPreviewBegins;
- (bool)shouldCancelDragsWhenEditingEnds;
- (bool)shouldDisallowBumpingIconsFromCurrentList;
- (bool)shouldUseGhostIconForIconView:(id)arg1;
- (id)simulateDragStartedFromIconView:(id)arg1;
- (void)simulateIconDragWithIdentifier:(id)arg1 didPauseAtLocation:(struct CGPoint { double x1; double x2; })arg2 inIconListView:(id)arg3;
- (void)simulateIconDraggingEndedWithIdentifier:(id)arg1;
- (id)simulateIconDropSessionDidEnterWithIconIdentifiers:(id)arg1 inIconListView:(id)arg2;
- (void)simulateIconDropSessionWithIdentifier:(id)arg1 didEnterWithIconIdentifiers:(id)arg2 inIconListView:(id)arg3;
- (void)simulatePerformIconDropWithIdentifier:(id)arg1 inIconListView:(id)arg2;
- (void)startTrackingDragLocationForEditingFromDropSession:(id)arg1 orDragSession:(id)arg2;
- (void)stopTrackingDragLocationForEditingForDragWithIdentifier:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (bool)swapTrackedIconWithIdentifier:(id)arg1 withIcon:(id)arg2;
- (id)undoProvider;
- (id)uniqueIdentifierForIconDragSession:(id)arg1;
- (id)uniqueIdentifierForIconDropSession:(id)arg1;
- (void)updateExistingIconPlaceholderForDragWithIdentifier:(id)arg1;
- (void)watchdogDragWithIdentifier:(id)arg1;
- (void)watchdogTimerDidFire:(id)arg1;
- (void)willUndo;
- (void)windowSceneDidDisconnect:(id)arg1;

@end
