
@interface SBRootFolderController : SBFolderController <SBFramewiseInteractiveTransitionAnimatorDelegate, SBHAddWidgetSheetViewControllerDelegate, SBHIconRootViewProviding, SBHStackConfigurationInteractionDelegate, SBHStackConfigurationViewControllerAppearanceDelegate, SBHWidgetDragHandling, SBHWidgetSheetViewControllerPresenter, SBIconWidgetIntroductionDelegate, SBRootFolderPageStateTransitioning, SBRootFolderViewDelegate, SBSearchGestureObserver, SBViewControllerTransitionContextDelegate, UIGestureRecognizerDelegate> {
    <SBRootFolderControllerAccessoryViewControllerDelegate> * _accessoryViewControllerDelegate;
    UIViewController<SBHMainAddSheetViewControlling> * _addSheetViewController;
    SBFramewiseInteractiveTransitionAnimator * _currentTransitionAnimator;
    SBViewControllerTransitionContext * _currentTransitionContext;
    _SBRootFolderPageTransitionHandle * _currentTransitionHandle;
    SBPercentPassthroughInteractiveTransition * _currentTransitionInteractor;
    unsigned long long  _hiddenListCountWhenPageManagementPresented;
    SBHomeScreenDefaults * _homeScreenDefaults;
    <SBRootFolderPageTransition> * _implicitScrollTransition;
    UIViewController<SBHRootFolderCustomViewPresenting> * _leadingCustomViewController;
    bool  _managesStatusBarWidth;
    long long  _pageState;
    NSHashTable * _pageStateObservers;
    unsigned long long  _presentationSource;
    UIViewController * _pullDownSearchViewController;
    SBHRecentsDocumentExtensionProvider * _recentsDocumentExtensionProvider;
    SBSearchGesture * _searchGesture;
    <BSInvalidatable> * _searchGestureIconViewTouchCancellationAssertion;
    <SBRootFolderPageTransition> * _searchGestureTransition;
    UIViewController<SBHSearchPresentable> * _searchPresentableViewController;
    <SBHSearchPresenting> * _searchPresenter;
    unsigned long long  _showsAddWidgetButtonWhileEditingAllowedOrientations;
    bool  _showsDoneButtonWhileEditing;
    SBHStackConfigurationViewController * _stackConfigurationViewController;
    bool  _suppressesExtraEditingButtons;
    bool  _todayViewPageHidden;
    UIViewController<SBHRootFolderCustomViewPresenting> * _trailingCustomViewController;
    struct os_activity_scope_state_s { 
        unsigned long long opaque[2]; 
    }  _widgetAddSheetActivityState;
    NSMapTable * _widgetAddSheetObservers;
}

@property (nonatomic) <SBRootFolderControllerAccessoryViewControllerDelegate> *accessoryViewControllerDelegate;
@property (nonatomic, retain) UIViewController<SBHMainAddSheetViewControlling> *addSheetViewController;
@property (nonatomic) bool allowsAutoscrollToLeadingCustomView;
@property (getter=isAnySearchVisible, nonatomic, readonly) bool anySearchVisible;
@property (getter=isAnySearchVisibleOrTransitioning, nonatomic, readonly) bool anySearchVisibleOrTransitioning;
@property (nonatomic, readonly) UIView *contentView;
@property (nonatomic) unsigned long long contentVisibility;
@property (nonatomic) long long currentPageIndex;
@property (nonatomic, retain) _SBRootFolderPageTransitionHandle *currentTransitionHandle;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) UIViewController *deepestFolderController;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) long long destinationPageState;
@property (nonatomic) unsigned long long dockEdge;
@property (getter=isDockExternal, nonatomic, readonly) bool dockExternal;
@property (nonatomic, readonly) double dockHeight;
@property (getter=isEditing, nonatomic) bool editing;
@property (nonatomic, retain) SBRootFolder *folder;
@property (nonatomic, readonly, copy) NSArray *folderControllers;
@property (nonatomic) <SBRootFolderControllerDelegate> *folderDelegate;
@property (nonatomic, retain) SBFolderIconImageCache *folderIconImageCache;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long hiddenListCountWhenPageManagementPresented;
@property (nonatomic, readonly) SBHomeScreenDefaults *homeScreenDefaults;
@property (nonatomic, retain) SBHIconImageCache *iconImageCache;
@property (nonatomic, retain) <SBRootFolderPageTransition> *implicitScrollTransition;
@property (getter=isOnLeadingCustomPage, nonatomic, readonly) bool leadingCustomPage;
@property (nonatomic, readonly) UIViewController<SBHRootFolderCustomViewPresenting> *leadingCustomViewController;
@property (getter=isLeadingCustomViewPageHidden, nonatomic) bool leadingCustomViewPageHidden;
@property (nonatomic, readonly) long long leadingCustomViewPageIndex;
@property (getter=isLeadingCustomViewSearchTransitioning, nonatomic, readonly) bool leadingCustomViewSearchTransitioning;
@property (getter=isLeadingCustomViewSearchVisible, nonatomic, readonly) bool leadingCustomViewSearchVisible;
@property (getter=isLeadingCustomViewSearchVisibleOrTransitioning, nonatomic, readonly) bool leadingCustomViewSearchVisibleOrTransitioning;
@property (getter=isLeadingCustomViewTransitioning, nonatomic, readonly) bool leadingCustomViewTransitioning;
@property (getter=isLeadingCustomViewVisible, nonatomic, readonly) bool leadingCustomViewVisible;
@property (getter=isLeadingCustomViewVisibleOrTransitionDestination, nonatomic, readonly) bool leadingCustomViewVisibleOrTransitionDestination;
@property (nonatomic, retain) _UILegibilitySettings *legibilitySettings;
@property (nonatomic) bool managesStatusBarWidth;
@property (nonatomic, readonly, copy) NSSet *nonDockPresentedIconLocations;
@property (getter=isOccludedByOverlay, nonatomic) bool occludedByOverlay;
@property (getter=isPageManagementUIVisible, nonatomic, readonly) bool pageManagementUIVisible;
@property (nonatomic) long long pageState;
@property (nonatomic, readonly) SBFParallaxSettings *parallaxSettings;
@property (nonatomic) unsigned long long presentationSource;
@property (nonatomic, readonly, copy) NSSet *presentedIconLocations;
@property (getter=isPullDownSearchTransitioning, nonatomic, readonly) bool pullDownSearchTransitioning;
@property (nonatomic, readonly) UIViewController *pullDownSearchViewController;
@property (getter=isPullDownSearchVisible, nonatomic, readonly) bool pullDownSearchVisible;
@property (getter=isPullDownSearchVisibleOrTransitioning, nonatomic, readonly) bool pullDownSearchVisibleOrTransitioning;
@property (getter=isPullDownSearchVisibleOrTransitioningToVisible, nonatomic, readonly) bool pullDownSearchVisibleOrTransitioningToVisible;
@property (nonatomic, retain) SBHRecentsDocumentExtensionProvider *recentsDocumentExtensionProvider;
@property (nonatomic, readonly) SBRootFolderView *rootFolderView;
@property (getter=isScrollTracking, nonatomic, readonly) bool scrollTracking;
@property (getter=isScrolling, nonatomic, readonly) bool scrolling;
@property (nonatomic, readonly) UIView *searchBackdropView;
@property (nonatomic, retain) SBSearchGesture *searchGesture;
@property (nonatomic, retain) <BSInvalidatable> *searchGestureIconViewTouchCancellationAssertion;
@property (nonatomic, retain) <SBRootFolderPageTransition> *searchGestureTransition;
@property (nonatomic, readonly) UIViewController<SBHSearchPresentable> *searchPresentableViewController;
@property (nonatomic, readonly) <SBHSearchPresenting> *searchPresenter;
@property (nonatomic, readonly) UIView *searchableLeadingCustomWrapperView;
@property (nonatomic, readonly) unsigned long long showsAddWidgetButtonWhileEditingAllowedOrientations;
@property (nonatomic, readonly) bool showsDoneButtonWhileEditing;
@property (nonatomic, readonly) double spotlightFirstIconRowOffset;
@property (nonatomic) SBHStackConfigurationViewController *stackConfigurationViewController;
@property (readonly) Class superclass;
@property (nonatomic) bool suppressesExtraEditingButtons;
@property (nonatomic) double titledButtonsAlpha;
@property (nonatomic, readonly) UIViewController<SBHLegibility> *todayViewController;
@property (getter=isTodayViewPageHidden, nonatomic) bool todayViewPageHidden;
@property (nonatomic, readonly) UIViewController<SBHRootFolderCustomViewPresenting> *trailingCustomViewController;
@property (nonatomic, readonly) long long trailingCustomViewPageIndex;
@property (getter=isTransitioningPageState, nonatomic, readonly) bool transitioningPageState;
@property (nonatomic, readonly) <SBHWidgetDragHandling> *widgetDragHandler;

+ (Class)_contentViewClass;
+ (bool)_shouldForwardViewWillTransitionToSize;
+ (Class)configurationClass;
+ (id)dockIconLocation;
+ (id)iconLocation;
+ (struct SBRootFolderPageStateTransitionSnapshot { long long x1; long long x2; double x3; })pageStateTransitionSnapshotForScrollOffset:(double)arg1 pageWidth:(double)arg2 pageSpacing:(double)arg3 pages:(const long long*)arg4 pageCount:(unsigned long long)arg5 userInterfaceLayoutDirection:(long long)arg6 currentPageState:(long long)arg7;

- (void).cxx_destruct;
- (id)_addWidgetSheetConfigurationManager;
- (unsigned long long)_addWidgetSheetStyle;
- (double)_additionalMinimumOffsetForSheetPresentation;
- (double)_anySearchVisibilityProgress;
- (void)_cancelTouchesForSearchGestureOnIconView:(id)arg1;
- (void)_checkForImproperScrollOffsetForPageState;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (unsigned long long)_currentHomeScreenEditingGridSize;
- (unsigned long long)_defaultEditingSuggestedWidgetItemsFamilyMask;
- (unsigned long long)_depth;
- (void)_dismissPageManagementIfPresented:(id /* block */)arg1;
- (void)_doPageManagementEducation;
- (void)_handleWidgetSheetViewControllerDidAppear:(id)arg1;
- (void)_handleWidgetSheetViewControllerDidDisappear:(id)arg1;
- (void)_handleWidgetSheetViewControllerWillAppear:(id)arg1;
- (void)_handleWidgetSheetViewControllerWillDisappear:(id)arg1;
- (bool)_internalDismissWidgetAddSheet:(bool)arg1 clearAddSheetViewController:(bool)arg2 notifyObservers:(bool)arg3;
- (void)_invalidateSearchGestureIconViewTouchCancellationAssertion;
- (double)_leadingCustomViewVisibilityProgress;
- (bool)_listIndexIsVisible:(unsigned long long)arg1;
- (id)_makeContentViewWithConfiguration:(id)arg1;
- (void)_presentPageManagement:(id /* block */)arg1;
- (void)_reduceTransparencyChanged;
- (void)_refreshGalleryContentForHomeScreenEditingIfNecessary;
- (void)_setupDebugTapGestureRecognizerForDockIconListView:(id)arg1;
- (unsigned long long)_stackConfigurationGridSize;
- (double)_trailingCustomViewVisibilityProgress;
- (void)_updateAddWidgetSheetIconCache;
- (void)_updateFolderRequiredTrailingEmptyListCount;
- (void)_updateStatusBarHiddenForWidgetSheetViewController:(id)arg1 visible:(bool)arg2;
- (id)_viewControllersToNotifyForViewObscuration;
- (void)acceptWidgetIntroduction;
- (id)accessoryViewControllerDelegate;
- (void)addPageStateObserver:(id)arg1;
- (id)addSheetViewController;
- (id)addWidgetAddSheetObserver:(id /* block */)arg1;
- (void)addWidgetSheetViewController:(id)arg1 didSelectWidgetIconView:(id)arg2;
- (void)addWidgetSheetViewControllerDidAppear:(id)arg1;
- (void)addWidgetSheetViewControllerDidCancel:(id)arg1;
- (void)addWidgetSheetViewControllerDidDisappear:(id)arg1;
- (void)addWidgetSheetViewControllerWillAppear:(id)arg1;
- (void)addWidgetSheetViewControllerWillDisappear:(id)arg1;
- (bool)allowsAutoscrollToLeadingCustomView;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)applicationWidgetCollectionsForEditingViewController:(id)arg1 withAllowedSizeClasses:(unsigned long long*)arg2 allowingNonStackableItems:(bool)arg3;
- (id)backgroundViewForDockForRootFolderView:(id)arg1;
- (id)backgroundViewForEditingDoneButtonForRootFolderView:(id)arg1;
- (id)beginModifyingDockOffscreenFractionForReason:(id)arg1;
- (id)beginPageStateTransitionToState:(long long)arg1 reason:(id)arg2 animated:(bool)arg3 interactive:(bool)arg4;
- (void)bringWidgetIntroductionPopoverToFront;
- (bool)canAcceptFolderIconDrags;
- (bool)canShowWidgetIntroduction;
- (bool)canTransitionPageStateToState:(long long)arg1;
- (bool)closesAfterDragExits;
- (id)currentTransitionHandle;
- (void)dealloc;
- (id)defaultTransitionForTransitioningFromPageState:(long long)arg1 toPageState:(long long)arg2 animated:(bool)arg3 interactive:(bool)arg4;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (long long)destinationPageState;
- (void)didBeginDraggingWidgetIcon:(id)arg1;
- (void)didContinueTransitionToState:(long long)arg1 progress:(double)arg2;
- (void)didEndDraggingWidgetIcon:(id)arg1;
- (void)didEndTransitionFromState:(long long)arg1 toState:(long long)arg2 successfully:(bool)arg3;
- (bool)disablesScrollingWhileIconDragIsDropping;
- (void)dismissSpotlightAnimated:(bool)arg1 completionHandler:(id /* block */)arg2;
- (bool)dismissWidgetAddSheetIfPresentedAndClearAnimated:(bool)arg1;
- (void)dismissWidgetEditingViewControllerIfPresentedAnimated:(bool)arg1;
- (double)distanceToTopOfSpotlightIconsForRootFolderView:(id)arg1;
- (unsigned long long)dockEdge;
- (double)dockHeight;
- (id)dockIconListView;
- (id)dockListView;
- (void)enterPageManagementUIWithCompletionHandler:(id /* block */)arg1;
- (void)enumerateDisplayedIconViewsForIcon:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)enumerateDisplayedIconViewsUsingBlock:(id /* block */)arg1;
- (void)enumerateDisplayedIconViewsWithOptions:(unsigned long long)arg1 usingBlock:(id /* block */)arg2;
- (void)enumeratePageStateObserversUsingBlock:(id /* block */)arg1;
- (void)enumerateWidgetAddSheetObserversUsingBlock:(id /* block */)arg1;
- (void)exitPageManagementUIWithCompletionHandler:(id /* block */)arg1;
- (double)externalDockHeightForRootFolderView:(id)arg1;
- (id)firstIconViewForIcon:(id)arg1 options:(unsigned long long)arg2;
- (void)folderController:(id)arg1 didBeginEditingTitle:(id)arg2;
- (void)folderController:(id)arg1 didEndEditingTitle:(id)arg2;
- (id)folderControllers;
- (void)folderView:(id)arg1 currentPageIndexDidChange:(long long)arg2;
- (void)folderView:(id)arg1 currentPageIndexWillChange:(long long)arg2;
- (void)folderView:(id)arg1 didBeginEditingTitle:(id)arg2;
- (void)folderView:(id)arg1 didEndEditingTitle:(id)arg2;
- (void)folderView:(id)arg1 willAnimateScrollToPageIndex:(long long)arg2;
- (void)folderViewDidEndScrolling:(id)arg1;
- (void)folderViewDidScroll:(id)arg1;
- (void)folderViewWillUpdatePageDuringScrolling:(id)arg1;
- (unsigned long long)hiddenListCountWhenPageManagementPresented;
- (id)homeScreenDefaults;
- (bool)iconListViewContainsWidget:(unsigned long long)arg1;
- (bool)iconListViewsContainWidget;
- (id)iconLocationForListsWithNonDefaultSizedIconsForRootFolderView:(id)arg1;
- (id)iconViewForIcon:(id)arg1 location:(id)arg2;
- (id)iconViewForIcon:(id)arg1 location:(id)arg2 options:(unsigned long long)arg3;
- (id)implicitScrollTransition;
- (id)initWithConfiguration:(id)arg1;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (bool)isAnySearchTransitioning;
- (bool)isAnySearchVisible;
- (bool)isAnySearchVisibleOrTransitioning;
- (bool)isDisplayingEditingButtons;
- (bool)isDisplayingIcon:(id)arg1;
- (bool)isDisplayingIcon:(id)arg1 inLocation:(id)arg2;
- (bool)isDisplayingIcon:(id)arg1 inLocation:(id)arg2 options:(unsigned long long)arg3;
- (bool)isDisplayingIcon:(id)arg1 options:(unsigned long long)arg2;
- (bool)isDisplayingIconView:(id)arg1 inLocation:(id)arg2;
- (bool)isDisplayingIconView:(id)arg1 options:(unsigned long long)arg2;
- (bool)isDisplayingWidgetIntroductionOnPage:(long long)arg1;
- (bool)isDockExternal;
- (bool)isDockVisible;
- (bool)isLeadingCustomViewOrLeadingCustomViewSearchVisible;
- (bool)isLeadingCustomViewPageHidden;
- (bool)isLeadingCustomViewSearchTransitioning;
- (bool)isLeadingCustomViewSearchVisible;
- (bool)isLeadingCustomViewSearchVisibleOrTransitioning;
- (bool)isLeadingCustomViewTransitioning;
- (bool)isLeadingCustomViewVisible;
- (bool)isLeadingCustomViewVisibleOrTransitionDestination;
- (bool)isOccludedByOverlay;
- (bool)isOnLeadingCustomPage;
- (bool)isPageManagementUIVisible;
- (bool)isPresentingIconLocation:(id)arg1;
- (bool)isPullDownSearchTransitioning;
- (bool)isPullDownSearchVisible;
- (bool)isPullDownSearchVisibleOrTransitioning;
- (bool)isPullDownSearchVisibleOrTransitioningToVisible;
- (bool)isTodayViewPageHidden;
- (bool)isTransitioningBetweenHorizontalPageStates;
- (bool)isTransitioningBetweenIconAndLeadingCustomView;
- (bool)isTransitioningBetweenIconAndTrailingCustomView;
- (bool)isTransitioningBetweenIconPageAndLeadingCustomPage;
- (bool)isTransitioningBetweenIconPageAndTrailingCustomPage;
- (bool)isTransitioningBetweenPageStateVerticalGroups;
- (bool)isTransitioningPageState;
- (id)leadingCustomViewController;
- (long long)leadingCustomViewPageIndex;
- (bool)managesStatusBarWidth;
- (double)maxExternalDockHeightForRootFolderView:(id)arg1;
- (id)nonDockPresentedIconLocations;
- (long long)pageState;
- (struct SBRootFolderPageStateTransitionSnapshot { long long x1; long long x2; double x3; })pageStateTransitionSnapshotForScrollOffset:(double)arg1;
- (void)pageTransitionHandle:(id)arg1 endPageStateTransitionSuccessfully:(bool)arg2;
- (void)pageTransitionHandle:(id)arg1 updateCurrentPageStateTransitionToProgress:(double)arg2;
- (double)pageTransitionProgress;
- (id)parallaxSettings;
- (void)performDefaultPageStateTransitionToState:(long long)arg1 reason:(id)arg2 animated:(bool)arg3 completionHandler:(id /* block */)arg4;
- (void)performPageStateTransitionToState:(long long)arg1 reason:(id)arg2 animated:(bool)arg3 completionHandler:(id /* block */)arg4;
- (double)preferredExternalDockVerticalMarginForRootFolderView:(id)arg1;
- (void)presentSpotlightAnimated:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)presentWidgetEditingViewControllerFromViewController:(id)arg1;
- (void)presentWidgetEditingViewControllerFromViewController:(id)arg1 withAllowedSizeClasses:(unsigned long long)arg2 allowingNonStackableItems:(bool)arg3;
- (unsigned long long)presentationSource;
- (id)presentedIconLocations;
- (unsigned long long)presenterType;
- (id)pullDownSearchViewController;
- (id)recentsDocumentExtensionProvider;
- (void)rejectWidgetIntroduction;
- (void)removePageStateObserver:(id)arg1;
- (void)removeWidgetAddSheetObserverForHandle:(id)arg1;
- (id)rootFolderView;
- (void)rootFolderView:(id)arg1 didDismissPageManagementWithLayoutManager:(id)arg2 context:(id)arg3;
- (void)rootFolderView:(id)arg1 didEndOverscrollOnFirstPageWithVelocity:(double)arg2 translation:(double)arg3;
- (void)rootFolderView:(id)arg1 didEndOverscrollOnLastPageWithVelocity:(double)arg2 translation:(double)arg3;
- (void)rootFolderView:(id)arg1 didOverscrollOnFirstPageByAmount:(double)arg2;
- (void)rootFolderView:(id)arg1 didOverscrollOnLastPageByAmount:(double)arg2;
- (void)rootFolderView:(id)arg1 wantsToAdjustLeadingCustomContentForEdgeBounceForScrollOffset:(struct CGPoint { double x1; double x2; })arg2;
- (void)rootFolderView:(id)arg1 willDismissPageManagementUsingAnimator:(id)arg2 context:(id)arg3;
- (void)rootFolderView:(id)arg1 willPresentPageManagementWithLayoutManager:(id)arg2 animator:(id)arg3 context:(id)arg4;
- (void)rootFolderViewDidChangeSuppressesEditingStateForListViews:(id)arg1;
- (id)rootFolderViewIfLoaded;
- (void)rootFolderViewWantsSearchPresented:(id)arg1;
- (void)rootFolderViewWantsToEndEditing:(id)arg1;
- (void)rootFolderViewWantsWidgetEditingViewControllerPresented:(id)arg1;
- (id)searchBackdropView;
- (id)searchGesture;
- (void)searchGesture:(id)arg1 changedPercentComplete:(double)arg2;
- (void)searchGesture:(id)arg1 completedShowing:(bool)arg2;
- (void)searchGesture:(id)arg1 resetAnimated:(bool)arg2;
- (void)searchGesture:(id)arg1 startedShowing:(bool)arg2;
- (id)searchGestureIconViewTouchCancellationAssertion;
- (id)searchGestureTransition;
- (id)searchPresentableViewController;
- (id)searchPresenter;
- (id)searchableLeadingCustomWrapperView;
- (void)setAccessoryViewControllerDelegate:(id)arg1;
- (void)setAddSheetViewController:(id)arg1;
- (void)setAllowsAutoscrollToLeadingCustomView:(bool)arg1;
- (bool)setCurrentPageIndex:(long long)arg1 animated:(bool)arg2;
- (void)setCurrentTransitionHandle:(id)arg1;
- (void)setDockEdge:(unsigned long long)arg1;
- (void)setEditing:(bool)arg1 animated:(bool)arg2;
- (void)setFolderDelegate:(id)arg1;
- (void)setHiddenListCountWhenPageManagementPresented:(unsigned long long)arg1;
- (void)setIdleText:(id)arg1;
- (void)setImplicitScrollTransition:(id)arg1;
- (void)setLeadingCustomViewController:(id)arg1;
- (void)setLeadingCustomViewPageHidden:(bool)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)setManagesStatusBarWidth:(bool)arg1;
- (void)setOccludedByOverlay:(bool)arg1;
- (void)setPageState:(long long)arg1;
- (void)setParallaxDisabled:(bool)arg1 forReason:(id)arg2;
- (void)setPresentationSource:(unsigned long long)arg1;
- (void)setPullDownSearchViewController:(id)arg1;
- (void)setRecentsDocumentExtensionProvider:(id)arg1;
- (void)setSearchGesture:(id)arg1;
- (void)setSearchGestureIconViewTouchCancellationAssertion:(id)arg1;
- (void)setSearchGestureTransition:(id)arg1;
- (void)setStackConfigurationViewController:(id)arg1;
- (void)setSuppressesEditingStateForListView:(bool)arg1;
- (void)setSuppressesExtraEditingButtons:(bool)arg1;
- (void)setTitledButtonsAlpha:(double)arg1;
- (void)setTodayViewPageHidden:(bool)arg1;
- (bool)shouldOpenFolderIcon:(id)arg1;
- (unsigned long long)showsAddWidgetButtonWhileEditingAllowedOrientations;
- (bool)showsDoneButtonWhileEditing;
- (unsigned long long)snapshotTypeForIconImageViewControllersUnderWidgetAddSheet;
- (double)spotlightFirstIconRowOffset;
- (bool)stackConfigurationInteraction:(id)arg1 allowsRemovalOfIconDataSource:(id)arg2;
- (id)stackConfigurationInteraction:(id)arg1 dragPreviewForIconView:(id)arg2;
- (id)stackConfigurationInteraction:(id)arg1 draggedIconForIdentifier:(id)arg2;
- (void)stackConfigurationInteraction:(id)arg1 isConsumingDropSession:(id)arg2;
- (void)stackConfigurationInteraction:(id)arg1 noteDidRemoveSuggestedWidgetIcon:(id)arg2;
- (id)stackConfigurationInteraction:(id)arg1 promoteSuggestedWidget:(id)arg2 withinStack:(id)arg3;
- (void)stackConfigurationInteraction:(id)arg1 requestsPresentAddWidgetSheetFromPresenter:(id)arg2;
- (void)stackConfigurationInteractionWillAnimateWidgetInsertion:(id)arg1;
- (id)stackConfigurationViewController;
- (void)stackConfigurationViewControllerDidAppear:(id)arg1;
- (void)stackConfigurationViewControllerDidDisappear:(id)arg1;
- (void)stackConfigurationViewControllerWillAppear:(id)arg1;
- (void)stackConfigurationViewControllerWillDisappear:(id)arg1;
- (bool)suppressesExtraEditingButtons;
- (bool)suspendsWallpaperAnimationWhileOpen;
- (double)titledButtonsAlpha;
- (id)todayViewController;
- (id)trailingCustomViewController;
- (long long)trailingCustomViewPageIndex;
- (void)transitionContext:(id)arg1 updateTransitionProgress:(double)arg2;
- (void)transitionDidFinish:(id)arg1;
- (void)transitionWillBegin:(id)arg1;
- (void)transitionWillFinish:(id)arg1;
- (void)transitionWillReverse:(id)arg1;
- (void)updateExtraButtonVisibilityAnimated:(bool)arg1;
- (void)updatePresentedWidgetEditingViewController;
- (void)updatePronouncedContainerViewVisibilityIfPossible:(bool)arg1 vertical:(bool)arg2;
- (id)updateStateTransitionsDuringScrollingScrollView:(id)arg1 pageBounceComparator:(int (*)arg2;
- (id)viewControllerForPageState:(long long)arg1;
- (id)viewControllerForTransitioningFromPageState:(long long)arg1 toPageState:(long long)arg2;
- (id)viewControllersForPageIndex:(long long)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 forOperation:(long long)arg2 withTransitionCoordinator:(id)arg3;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (double)visibilityProgressTowardPageStateMatchingTest:(id /* block */)arg1;
- (id)widgetDragHandler;
- (id)widgetIconForDescriptor:(id)arg1 sizeClass:(long long)arg2;
- (id)widgetIconForDescriptors:(id)arg1 sizeClass:(long long)arg2;
- (id)widgetIconForGalleryItem:(id)arg1 sizeClass:(long long)arg2;
- (void)willBeginTransitionToState:(long long)arg1 animated:(bool)arg2 interactive:(bool)arg3;
- (void)willEndTransitionToState:(long long)arg1 successfully:(bool)arg2;
- (id)windowForIconDragPreviewsForStackConfigurationInteraction:(id)arg1 forWindowScene:(id)arg2;

@end
