
@interface TSXgPTPClock : TSXKernelClock <TSXgPTPClockClientProtocol> {
    unsigned char  _clockAccuracy;
    unsigned char  _clockClass;
    unsigned char  _clockPriority1;
    unsigned char  _clockPriority2;
    NSArray * _gptpPath;
    unsigned long long  _grandmasterIdentity;
    int  _internalLockState;
    struct { 
        bool syncInfoValid; 
        unsigned char syncFlags; 
        unsigned long long timeSyncTime; 
        struct IOTS_U128 { 
            unsigned long long lo; 
            unsigned long long hi; 
        } domainTime; 
        unsigned long long cumulativeScaledRate; 
        unsigned long long inverseCumulativeScaledRate; 
        unsigned long long grandmasterID; 
        unsigned short localPortNumber; 
    }  _timeInfo;
    TSClock * _timeSyncClock;
    TSClock * _translationClock;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _updateLock;
    unsigned int  _validIndex;
}

@property (nonatomic) unsigned char clockAccuracy;
@property (nonatomic) unsigned char clockClass;
@property (nonatomic, readonly) unsigned long long clockIdentity;
@property (nonatomic) unsigned char clockPriority1;
@property (nonatomic) unsigned char clockPriority2;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSArray *gptpPath;
@property (nonatomic) unsigned long long grandmasterIdentity;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSArray *ports;
@property (readonly) Class superclass;

+ (id)clientProtocol;
+ (id)serverProtocol;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_getInitialSyncInfo;
- (bool)addLinkLayerPortOnInterfaceNamed:(id)arg1 allocatedPortNumber:(unsigned short*)arg2 error:(id*)arg3;
- (bool)addReverseSyncOnInterfaceNamed:(id)arg1 withDomainNumner:(unsigned char)arg2 syncInterval:(unsigned int)arg3 error:(id*)arg4;
- (bool)addUnicastLinkLayerEtEPortOnInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 allocatedPortNumber:(unsigned short*)arg3 error:(id*)arg4;
- (bool)addUnicastLinkLayerPtPPortOnInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 allocatedPortNumber:(unsigned short*)arg3 error:(id*)arg4;
- (bool)addUnicastUDPv4EtEPortOnInterfaceNamed:(id)arg1 withDestinationAddress:(unsigned int)arg2 allocatedPortNumber:(unsigned short*)arg3 error:(id*)arg4;
- (bool)addUnicastUDPv4PtPPortOnInterfaceNamed:(id)arg1 withDestinationAddress:(unsigned int)arg2 allocatedPortNumber:(unsigned short*)arg3 error:(id*)arg4;
- (bool)addUnicastUDPv6EtEPortOnInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 allocatedPortNumber:(unsigned short*)arg3 error:(id*)arg4;
- (bool)addUnicastUDPv6PtPPortOnInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 allocatedPortNumber:(unsigned short*)arg3 error:(id*)arg4;
- (void)beginGrandmasterChangeWithGrandmasterID:(unsigned long long)arg1 localPort:(unsigned short)arg2;
- (void)changeLocalPortGrandmasterChangeWithGrandmasterID:(unsigned long long)arg1 localPort:(unsigned short)arg2;
- (unsigned char)clockAccuracy;
- (unsigned char)clockClass;
- (unsigned long long)clockIdentity;
- (id)clockName;
- (unsigned char)clockPriority1;
- (unsigned char)clockPriority2;
- (unsigned long long)convertFrom128BitgPTPTimeToMachAbsoluteTime:(struct { unsigned long long x1; unsigned long long x2; })arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (unsigned long long)convertFrom128BitgPTPTimeToTimeSyncTime:(struct { unsigned long long x1; unsigned long long x2; })arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (bool)convertFrom32BitASTime:(unsigned int*)arg1 toMachAbsoluteTime:(unsigned long long*)arg2 withCount:(unsigned int)arg3;
- (bool)convertFrom32BitASTime:(unsigned int*)arg1 toTimeSyncTime:(unsigned long long*)arg2 withCount:(unsigned int)arg3;
- (unsigned long long)convertFrom32BitASToMachAbsoluteTime:(unsigned int)arg1;
- (unsigned long long)convertFrom32BitASToTimeSyncTime:(unsigned int)arg1;
- (unsigned long long)convertFromDomainIntervalToMachAbsoluteInterval:(unsigned long long)arg1;
- (unsigned long long)convertFromDomainIntervalToTimeSyncTimeInterval:(unsigned long long)arg1;
- (bool)convertFromDomainTime:(unsigned long long*)arg1 toMachAbsoluteTime:(unsigned long long*)arg2 withCount:(unsigned int)arg3;
- (bool)convertFromDomainTime:(unsigned long long*)arg1 toTimeSyncTime:(unsigned long long*)arg2 withCount:(unsigned int)arg3;
- (unsigned long long)convertFromDomainTimeToTimeSyncTime:(unsigned long long)arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (unsigned long long)convertFromDomainToMachAbsoluteTime:(unsigned long long)arg1;
- (unsigned long long)convertFromDomainToMachAbsoluteTime:(unsigned long long)arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (unsigned long long)convertFromDomainToTimeSyncTime:(unsigned long long)arg1;
- (unsigned long long)convertFromMachAbsoluteIntervalToDomainInterval:(unsigned long long)arg1;
- (bool)convertFromMachAbsoluteTime:(unsigned long long*)arg1 toDomainTime:(unsigned long long*)arg2 withCount:(unsigned int)arg3;
- (struct { unsigned long long x1; unsigned long long x2; })convertFromMachAbsoluteTo128BitgPTPTime:(unsigned long long)arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (unsigned long long)convertFromMachAbsoluteToDomainTime:(unsigned long long)arg1;
- (unsigned long long)convertFromMachAbsoluteToDomainTime:(unsigned long long)arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (bool)convertFromTimeSyncTime:(unsigned long long*)arg1 toDomainTime:(unsigned long long*)arg2 withCount:(unsigned int)arg3;
- (unsigned long long)convertFromTimeSyncTimeIntervalToDomainInterval:(unsigned long long)arg1;
- (struct { unsigned long long x1; unsigned long long x2; })convertFromTimeSyncTimeTo128BitgPTPTime:(unsigned long long)arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (struct { unsigned long long x1; unsigned long long x2; })convertFromTimeSyncTimeTo128BitgPTPTime:(unsigned long long)arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3 flags:(unsigned long long*)arg4;
- (unsigned long long)convertFromTimeSyncTimeToDomainTime:(unsigned long long)arg1 grandmasterUsed:(unsigned long long*)arg2 portNumber:(unsigned short*)arg3;
- (unsigned long long)convertFromTimeSyncToDomainTime:(unsigned long long)arg1;
- (void)endGrandmasterChangeWithGrandmasterID:(unsigned long long)arg1 localPort:(unsigned short)arg2;
- (id)exportedObject;
- (id)gPTPTimeFromMachAbsoluteTime:(unsigned long long)arg1;
- (id)gPTPTimeFromTimeSyncTime:(unsigned long long)arg1;
- (bool)getMachAbsoluteRateRatioNumerator:(unsigned long long*)arg1 denominator:(unsigned long long*)arg2 machAnchor:(unsigned long long*)arg3 andDomainAnchor:(unsigned long long*)arg4 forGrandmasterIdentity:(unsigned long long*)arg5 portNumber:(unsigned short*)arg6 withError:(id*)arg7;
- (bool)getMachAbsoluteRateRatioNumerator:(unsigned long long*)arg1 denominator:(unsigned long long*)arg2 machAnchor:(unsigned long long*)arg3 andDomainAnchor:(unsigned long long*)arg4 withError:(id*)arg5;
- (bool)getTimeSyncTimeRateRatioNumerator:(unsigned long long*)arg1 denominator:(unsigned long long*)arg2 timeSyncAnchor:(unsigned long long*)arg3 andDomainAnchor:(unsigned long long*)arg4 forGrandmasterIdentity:(unsigned long long*)arg5 portNumber:(unsigned short*)arg6 withError:(id*)arg7;
- (bool)getTimeSyncTimeRateRatioNumerator:(unsigned long long*)arg1 denominator:(unsigned long long*)arg2 timeSyncAnchor:(unsigned long long*)arg3 andDomainAnchor:(unsigned long long*)arg4 withError:(id*)arg5;
- (id)gptpPath;
- (unsigned long long)grandmasterIdentity;
- (id)initWithEndpoint:(id)arg1 clockIdentifier:(unsigned long long)arg2;
- (unsigned long long)machAbsoluteFromgPTPTime:(id)arg1;
- (id)portWithPortNumber:(unsigned short)arg1;
- (id)ports;
- (bool)removeLinkLayerPortFromInterfaceNamed:(id)arg1 error:(id*)arg2;
- (bool)removeReverseSyncFromInterfaceNamed:(id)arg1 withDomainNumner:(unsigned char)arg2 error:(id*)arg3;
- (bool)removeUnicastLinkLayerEtEPortFromInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 error:(id*)arg3;
- (bool)removeUnicastLinkLayerPtPPortFromInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 error:(id*)arg3;
- (bool)removeUnicastUDPv4EtEPortFromInterfaceNamed:(id)arg1 withDestinationAddress:(unsigned int)arg2 error:(id*)arg3;
- (bool)removeUnicastUDPv4PtPPortFromInterfaceNamed:(id)arg1 withDestinationAddress:(unsigned int)arg2 error:(id*)arg3;
- (bool)removeUnicastUDPv6EtEPortFromInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 error:(id*)arg3;
- (bool)removeUnicastUDPv6PtPPortFromInterfaceNamed:(id)arg1 withDestinationAddress:(const char *)arg2 error:(id*)arg3;
- (void)setClockAccuracy:(unsigned char)arg1;
- (void)setClockClass:(unsigned char)arg1;
- (void)setClockPriority1:(unsigned char)arg1;
- (void)setClockPriority2:(unsigned char)arg1;
- (void)setGptpPath:(id)arg1;
- (void)setGrandmasterIdentity:(unsigned long long)arg1;
- (unsigned long long)timeSyncTimeFromgPTPTime:(id)arg1;
- (void)updateGrandmasterIdentity:(unsigned long long)arg1 andgPTPPath:(id)arg2;
- (void)updateLockState:(int)arg1;
- (void)updateWithSyncInfoValid:(bool)arg1 syncFlags:(unsigned char)arg2 timeSyncTime:(unsigned long long)arg3 domainTimeHi:(unsigned long long)arg4 domainTimeLo:(unsigned long long)arg5 cumulativeScaledRate:(unsigned long long)arg6 inverseCumulativeScaledRate:(unsigned long long)arg7 grandmasterID:(unsigned long long)arg8 localPortNumber:(unsigned short)arg9;

@end
