
@interface NCNotificationSummaryExpandedHeaderView : NCNotificationListBaseContentView <BSUIDateLabelDelegate, NCNotificationListCoalescingControlsHandler, NCToggleControlDelegate> {
    bool  _animateCollapseButtonLayout;
    NCToggleControl * _clearControl;
    PLGlyphControl * _collapseControl;
    UIView * _controlsView;
    NSDate * _date;
    long long  _dateFormatStyle;
    <NCNotificationSummaryExpandedHeaderViewDelegate> * _delegate;
    UIView * _dividerView;
    <NCNotificationListCoalescingControlsHandlerDelegate> * _handlerDelegate;
    bool  _onboarding;
    UIButton * _onboardingAcceptButton;
    UIButton * _onboardingRejectButton;
    UILabel * _subtitleLabel;
    UILabel<BSUIDateLabel> * _timeStampLabel;
    NSTimeZone * _timeZone;
    UILabel * _titleLabel;
}

@property (nonatomic, copy) NSDate *date;
@property (nonatomic) long long dateFormatStyle;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <NCNotificationSummaryExpandedHeaderViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) <NCNotificationListCoalescingControlsHandlerDelegate> *handlerDelegate;
@property (readonly) unsigned long long hash;
@property (getter=isOnboarding, nonatomic) bool onboarding;
@property (nonatomic, copy) NSString *subtitle;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSTimeZone *timeZone;
@property (nonatomic, copy) NSString *title;

- (void).cxx_destruct;
- (double)_allowedWidthForButtonInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_configureControlsViewIfNecessary;
- (void)_configureDividerViewIfNecessary;
- (void)_configureOnboardingButtonsIfNecessary;
- (void)_configureTimeStampLabel;
- (void)_configureTimeStampLabelIfNecessary;
- (void)_handleClearAll:(id)arg1;
- (void)_handleClearControlPrimaryAction:(id)arg1;
- (void)_handleClearControlTouchUpInside:(id)arg1;
- (void)_handleCollapseControlPrimaryAction:(id)arg1;
- (void)_layoutControlsView;
- (void)_layoutDividerView;
- (void)_layoutOnboardingButtons;
- (void)_layoutSubtitleLabel;
- (void)_layoutTimeStampLabel;
- (void)_layoutTitleLabel;
- (unsigned long long)_maximumNumberOfLinesForTitleText;
- (id)_newOnboardingButtonWithTitle:(id)arg1;
- (unsigned long long)_numberOfLinesForSubtitleTextInFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (unsigned long long)_numberOfLinesForTitleTextInFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_recycleTimeStampLabel;
- (void)_summaryOnboardingAccepted:(id)arg1;
- (void)_summaryOnboardingRejected:(id)arg1;
- (void)_tearDownTimeStampLabel;
- (void)_updateTextAttributes;
- (void)_updateTextAttributesForButtonLabel:(id)arg1;
- (void)_updateTextAttributesForDateLabel;
- (void)_updateTextAttributesForSubtitleTextLabel;
- (void)_updateTextAttributesForTitleTextLabel;
- (void)_visualStylingProviderDidChange:(id)arg1 forCategory:(long long)arg2 outgoingProvider:(id)arg3;
- (bool)adjustForContentSizeCategoryChange;
- (id)containerViewForToggleControlClickInteractionPresentedContent:(id)arg1;
- (id)date;
- (long long)dateFormatStyle;
- (void)dateLabelDidChange:(id)arg1;
- (id)delegate;
- (bool)dismissModalFullScreenIfNeeded;
- (id)handlerDelegate;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isOnboarding;
- (void)layoutSubviews;
- (void)resetClearButtonStateAnimated:(bool)arg1;
- (void)setDate:(id)arg1;
- (void)setDateFormatStyle:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setHandlerDelegate:(id)arg1;
- (void)setOnboarding:(bool)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setTimeZone:(id)arg1;
- (void)setTitle:(id)arg1;
- (bool)shouldReceiveTouchAtPointInWindowSpace:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)subtitle;
- (id)timeZone;
- (id)title;
- (void)toggleControlDidBeginClickInteraction:(id)arg1;
- (void)toggleControlDidDismssClickInteractionPresentedContent:(id)arg1;
- (void)toggleControlDidPresentClickInteractionPresentedContent:(id)arg1;

@end
