
@interface HMDPersonManager : HMFObject <HMBLocalZoneModelObserver, HMDDatabaseZoneManagerDataSource, HMDDatabaseZoneManagerDelegate, HMDPersonCoreDataManagerDelegate, HMDPersonDataSource, HMFLogging, HMFTimerDelegate> {
    NSUUID * _UUID;
    HMBCloudZone * _cloudZone;
    NSSet * _dataInterfaces;
    unsigned long long  _fetchBatchLimit;
    HMBLocalZone * _localZone;
    NSString * _logIdentifier;
    bool  _syncsPersonData;
    HMFTimer * _unassociatedFaceCropsCleanupTimer;
    id /* block */  _unassociatedFaceCropsCleanupTimerFactory;
    NSObject<OS_dispatch_queue> * _workQueue;
    HMDDatabaseZoneManager * _zoneManager;
}

@property (readonly, copy) NSUUID *UUID;
@property (retain) HMBCloudZone *cloudZone;
@property (getter=isCurrentDeviceAvailableResident, readonly) bool currentDeviceAvailableResident;
@property (getter=isDataAvailable, readonly) bool dataAvailable;
@property (readonly) NSSet *dataInterfaces;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property unsigned long long fetchBatchLimit;
@property (readonly) unsigned long long hash;
@property (retain) HMBLocalZone *localZone;
@property (readonly, copy) NSString *logIdentifier;
@property (readonly, copy) <HMDPersonManagerSettings> *settings;
@property (readonly) bool sharesFaceClassifications;
@property (readonly) Class superclass;
@property (readonly) bool syncsPersonData;
@property (retain) HMFTimer *unassociatedFaceCropsCleanupTimer;
@property (copy) id /* block */ unassociatedFaceCropsCleanupTimerFactory;
@property (readonly) NSObject<OS_dispatch_queue> *workQueue;
@property (readonly) HMDDatabaseZoneManager *zoneManager;

+ (id)logCategory;
+ (id)zoneNameForZoneUUID:(id)arg1;

- (void).cxx_destruct;
- (id)UUID;
- (void)_cleanUpExpiredUnassociatedFaceCrops;
- (void)_createOrRemoveZonesForSettings:(id)arg1;
- (void)_createZones;
- (id)_faceCropsModelsWithUUIDs:(id)arg1;
- (void)_handleCreatedOrUpdatedModel:(id)arg1 mirrorOutputFuture:(id)arg2;
- (void)_handleDeletedModel:(id)arg1 mirrorOutputFuture:(id)arg2;
- (void)_notifyDataInterfacesOfCurrentIsCurrentDeviceAvailableResident;
- (void)_notifyDataInterfacesOfCurrentIsDataSyncInProgress;
- (id)_removeFaceprintsForFaceCropsWithUUIDs:(id)arg1;
- (id)_removePersonZones;
- (id)_unassociatedFaceCropsModelsWithUUIDs:(id)arg1;
- (id)addOrUpdateFaceCrops:(id)arg1;
- (id)addOrUpdateFaceprints:(id)arg1;
- (id)addOrUpdatePersons:(id)arg1;
- (id)addOrUpdatePersons:(id)arg1 andRemovePersonsWithUUIDs:(id)arg2;
- (id)addUnassociatedFaceCropWithData:(id)arg1;
- (id)associateFaceCropsWithUUIDs:(id)arg1 toPersonWithUUID:(id)arg2 forSource:(long long)arg3;
- (id)attributeDescriptions;
- (id)cloudZone;
- (void)configureWithHome:(id)arg1;
- (void)coreDataManager:(id)arg1 didRemovePersonsWithUUIDs:(id)arg2;
- (void)coreDataManager:(id)arg1 didUpdatePersons:(id)arg2;
- (id)createBatchChange;
- (id)dataInterfaces;
- (void)dealloc;
- (id)disassociateFaceCropsWithUUIDs:(id)arg1;
- (void)enumerateFaceCropsUsingBlock:(id /* block */)arg1;
- (void)enumerateFaceprintsUsingBlock:(id /* block */)arg1;
- (void)enumeratePersonFaceCropsUsingBlock:(id /* block */)arg1;
- (void)enumeratePersonsUsingBlock:(id /* block */)arg1;
- (void)enumerateUnassociatedFaceCropsUsingBlock:(id /* block */)arg1;
- (id)faceCropUUIDsForPersonWithUUID:(id)arg1;
- (id)faceCropsForPersonWithUUID:(id)arg1;
- (id)faceCropsForPersonsWithUUIDs:(id)arg1;
- (id)faceCropsWithUUIDs:(id)arg1;
- (id)faceprintsForFaceCropsWithUUIDs:(id)arg1;
- (unsigned long long)fetchBatchLimit;
- (void)handleDataSyncInProgressChangedNotification:(id)arg1;
- (void)handleFaceMisclassificationForFaceCropData:(id)arg1 personUUID:(id)arg2;
- (void)handleResidentWasAddedNotification:(id)arg1;
- (void)handleResidentWasRemovedNotification:(id)arg1;
- (void)handleResidentWasUpdatedNotification:(id)arg1;
- (void)handleUserPrivilegeDidChangeNotification:(id)arg1;
- (id)initWithUUID:(id)arg1 zoneManager:(id)arg2 dataInterfaces:(id)arg3 workQueue:(id)arg4;
- (bool)isCurrentDeviceAvailableResident;
- (bool)isDataAvailable;
- (bool)isDataSyncInProgress;
- (id)localZone;
- (id)localZone:(id)arg1 didProcessModelCreation:(id)arg2;
- (id)localZone:(id)arg1 didProcessModelDeletion:(id)arg2;
- (id)localZone:(id)arg1 didProcessModelUpdate:(id)arg2;
- (id)logIdentifier;
- (bool)manager:(id)arg1 shouldShareWithUser:(id)arg2;
- (id)performCloudPull;
- (id)personFaceCropWithUnassociatedFaceCropUUID:(id)arg1;
- (id)personWithUUID:(id)arg1;
- (id)personsWithUUIDs:(id)arg1;
- (id)removeAllAssociatedDataDueToHomeGraphObjectRemoval:(bool)arg1;
- (id)removeFaceCropsWithUUIDs:(id)arg1;
- (id)removeFaceprintsWithUUIDs:(id)arg1;
- (id)removePersonsWithUUIDs:(id)arg1;
- (void)setCloudZone:(id)arg1;
- (void)setFetchBatchLimit:(unsigned long long)arg1;
- (void)setLocalZone:(id)arg1;
- (void)setUnassociatedFaceCropsCleanupTimer:(id)arg1;
- (void)setUnassociatedFaceCropsCleanupTimerFactory:(id /* block */)arg1;
- (id)settings;
- (bool)sharesFaceClassifications;
- (bool)syncsDataToAllUsers;
- (bool)syncsPersonData;
- (void)timerDidFire:(id)arg1;
- (id)unassociatedFaceCropWithUUID:(id)arg1;
- (id)unassociatedFaceCropsCleanupTimer;
- (id /* block */)unassociatedFaceCropsCleanupTimerFactory;
- (id)workQueue;
- (id)zoneManager;
- (void)zoneManagerDidStart:(id)arg1;
- (void)zoneManagerDidStop:(id)arg1;

@end
