
@interface SBAppLayout : NSObject <BSDescriptionProviding, NSCopying, SBSwitcherLayoutElementProviding> {
    long long  _cachedAppLayoutType;
    NSDictionary * _cachedDisplayItemLayoutAttributesForNonPreferredDisplay;
    unsigned long long  _cachedHash;
    SBContinuousExposeAutoLayoutSpace * _cachedLastAutoLayoutSpace;
    SBAppLayoutAutoLayoutSpaceCacheKey * _cachedLastOverlappingModelKey;
    long long  _centerConfiguration;
    SBDisplayItem * _centerItem;
    long long  _configuration;
    long long  _environment;
    SBDisplayItem * _floatingItem;
    bool  _hidden;
    NSArray * _items;
    NSDictionary * _itemsToLayoutAttributesMap;
    NSArray * _itemsWithoutCenterOrFloatingItems;
    long long  _preferredDisplayOrdinal;
}

@property (nonatomic, retain) NSDictionary *cachedDisplayItemLayoutAttributesForNonPreferredDisplay;
@property (nonatomic, retain) SBContinuousExposeAutoLayoutSpace *cachedLastAutoLayoutSpace;
@property (nonatomic, retain) SBAppLayoutAutoLayoutSpaceCacheKey *cachedLastOverlappingModelKey;
@property (nonatomic, readonly) long long centerConfiguration;
@property (nonatomic, readonly) SBDisplayItem *centerItem;
@property (nonatomic, readonly) long long configuration;
@property (nonatomic, readonly, copy) NSString *continuousExposeIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) long long environment;
@property (nonatomic, readonly) SBDisplayItem *floatingItem;
@property (readonly) unsigned long long hash;
@property (getter=isHidden, nonatomic, readonly) bool hidden;
@property (getter=isInsetForHomeAffordance, nonatomic, readonly) bool insetForHomeAffordance;
@property (nonatomic, readonly) NSDictionary *itemsToLayoutAttributesMap;
@property (nonatomic, readonly) long long preferredDisplayOrdinal;
@property (readonly) Class superclass;
@property (nonatomic, readonly) long long type;

+ (id)appLayoutWithProtobufRepresentation:(id)arg1;
+ (id)homeScreenAppLayout;

- (void).cxx_destruct;
- (id)_leafAppLayoutForItem:(id)arg1 role:(long long)arg2;
- (id)_preferredWindowScene;
- (id)allItems;
- (id)anyLeafAppLayout;
- (id)appLayoutByAdjustingCenterWindowItemsForChamois;
- (id)appLayoutByAdjustingFloatingItemsForChamois;
- (id)appLayoutByInsertingItem:(id)arg1 withLayoutAttributes:(id)arg2 inLayoutRole:(long long)arg3;
- (id)appLayoutByInsertingLeafAppLayout:(id)arg1 inRole:(long long)arg2;
- (id)appLayoutByModifyingConfiguration:(long long)arg1;
- (id)appLayoutByModifyingEnvironment:(long long)arg1;
- (id)appLayoutByModifyingHiddenState:(bool)arg1;
- (id)appLayoutByModifyingLayoutAttributes:(id)arg1 forItem:(id)arg2;
- (id)appLayoutByModifyingLayoutAttributes:(id)arg1 forItemInRole:(long long)arg2;
- (id)appLayoutByModifyingLayoutAttributesForItems:(id)arg1;
- (id)appLayoutByModifyingPreferredDisplayOrdinal:(long long)arg1;
- (id)appLayoutByRemovingItemInLayoutRole:(long long)arg1;
- (id)appLayoutWithItemsPassingTest:(id /* block */)arg1;
- (id)appLayoutsBySplittingMedusaIncompatibleItemsWithApplicationController:(id)arg1 multitaskingSupported:(bool)arg2;
- (id)cachedDisplayItemLayoutAttributesForNonPreferredDisplay;
- (id)cachedLastAutoLayoutSpace;
- (id)cachedLastOverlappingModelKey;
- (long long)centerConfiguration;
- (id)centerItem;
- (long long)compare:(id)arg1;
- (long long)configuration;
- (bool)containsAllItemsFromAppLayout:(id)arg1;
- (bool)containsAllItemsFromSet:(id)arg1;
- (bool)containsAnyItemFromAppLayout:(id)arg1;
- (bool)containsAnyItemFromSet:(id)arg1;
- (bool)containsItem:(id)arg1;
- (bool)containsItemWithBundleIdentifier:(id)arg1;
- (bool)containsItemWithUniqueIdentifier:(id)arg1;
- (id)continuousExposeIdentifier;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)enumerate:(id /* block */)arg1;
- (long long)environment;
- (id)flippedAppLayout;
- (id)floatingItem;
- (bool)hasSameItemsInLayoutRoles:(unsigned long long)arg1 asAppLayout:(id)arg2;
- (unsigned long long)hash;
- (id)init;
- (id)initWithItems:(id)arg1 centerItem:(id)arg2 floatingItem:(id)arg3 configuration:(long long)arg4 itemsToLayoutAttributes:(id)arg5 centerConfiguration:(long long)arg6 environment:(long long)arg7 hidden:(bool)arg8 preferredDisplayOrdinal:(long long)arg9;
- (id)initWithItemsForLayoutRoles:(id)arg1 configuration:(long long)arg2 centerConfiguration:(long long)arg3 environment:(long long)arg4 hidden:(bool)arg5 preferredDisplayOrdinal:(long long)arg6;
- (id)initWithItemsForLayoutRoles:(id)arg1 configuration:(long long)arg2 environment:(long long)arg3 hidden:(bool)arg4 preferredDisplayOrdinal:(long long)arg5;
- (id)initWithItemsForLayoutRoles:(id)arg1 configuration:(long long)arg2 environment:(long long)arg3 preferredDisplayOrdinal:(long long)arg4;
- (id)initWithItemsForLayoutRoles:(id)arg1 configuration:(long long)arg2 itemsToLayoutAttributes:(id)arg3 centerConfiguration:(long long)arg4 environment:(long long)arg5 hidden:(bool)arg6 preferredDisplayOrdinal:(long long)arg7;
- (id)initWithPlistRepresentation:(id)arg1;
- (bool)isCenterOverFull;
- (bool)isCenterOverSplit;
- (bool)isEqual:(id)arg1;
- (bool)isFullScreen;
- (bool)isHidden;
- (bool)isInsetForHomeAffordance;
- (bool)isOrContainsAppLayout:(id)arg1;
- (bool)isSplitConfiguration;
- (id)itemForLayoutRole:(long long)arg1;
- (id)itemsToLayoutAttributesMap;
- (id)latestItemPassingTest:(id /* block */)arg1;
- (id)layoutAttributesForItem:(id)arg1;
- (id)layoutAttributesForItemInRole:(long long)arg1;
- (long long)layoutRoleForItem:(id)arg1;
- (id)leafAppLayoutForItem:(id)arg1;
- (id)leafAppLayoutForRole:(long long)arg1;
- (id)leafAppLayouts;
- (id)plistRepresentation;
- (id)preferredDisplayIdentity;
- (long long)preferredDisplayOrdinal;
- (id)protobufRepresentation;
- (void)setCachedDisplayItemLayoutAttributesForNonPreferredDisplay:(id)arg1;
- (void)setCachedLastAutoLayoutSpace:(id)arg1;
- (void)setCachedLastOverlappingModelKey:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (unsigned long long)switcherLayoutElementType;
- (long long)type;
- (id)zOrderedItems;
- (id)zOrderedLeafAppLayouts;

@end
