
@interface SBCoverSheetSlidingViewController : UIViewController <PTSettingsKeyObserver, SBCoverSheetSystemGestureDelegatePositionProviding> {
    bool  _canBePulledDown;
    bool  _canBePulledUp;
    UIViewFloatAnimatableProperty * _catchupProperty;
    id /* block */  _completionBlock;
    NSObject<OS_dispatch_group> * _completionGroup;
    UIViewController<SBCoverSheetSlidingViewControllerContentViewController> * _contentViewController;
    <SBCoverSheetSlidingViewControllerDelegate> * _delegate;
    SBScreenEdgePanGestureRecognizer * _dismissAddendumGestureRecognizer;
    SBScreenEdgePanGestureRecognizer * _dismissGestureRecognizer;
    long long  _dismissGestureState;
    long long  _dismissalSlidingMode;
    long long  _dismissalTransformMode;
    SBFFrameRateAssertion * _frameRateAssertion;
    long long  _groupCount;
    SBHomeGestureSettings * _homeGestureSettings;
    SBIndirectPanGestureRecognizer * _indirectDismissGestureRecognizer;
    bool  _indirectPresentGestureCalledBegin;
    SBIndirectPanGestureRecognizer * _indirectPresentGestureRecognizer;
    double  _initialTouchOffsetFromScreenEdge;
    struct CGPoint { 
        double x; 
        double y; 
    }  _lastGestureVelocity;
    struct CGPoint { 
        double x; 
        double y; 
    }  _lastTouchLocation;
    CSLockScreenSettings * _lockScreenSettings;
    bool  _performingCatchUpForPresentation;
    SBCoverSheetPositionView * _positionView;
    long long  _presentGestureState;
    UIViewFloatAnimatableProperty * _progressProperty;
    SBProximitySensorManager * _proximitySensorManager;
    bool  _roundsCorners;
    SBFluidScrunchGestureRecognizer * _scrunchDismissGestureRecognizer;
    <BSInvalidatable> * _suppressTouchCancellation;
    SBCoverSheetSystemGesturesDelegate * _systemGesturesDelegate;
    CSCoverSheetTransitionSettings * _transitionSettings;
}

@property (nonatomic) bool canBePulledDown;
@property (nonatomic) bool canBePulledUp;
@property (nonatomic, retain) UIViewFloatAnimatableProperty *catchupProperty;
@property (nonatomic, copy) id /* block */ completionBlock;
@property (nonatomic, retain) NSObject<OS_dispatch_group> *completionGroup;
@property (nonatomic, readonly) UIViewController<SBCoverSheetSlidingViewControllerContentViewController> *contentViewController;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBCoverSheetSlidingViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SBScreenEdgePanGestureRecognizer *dismissAddendumGestureRecognizer;
@property (nonatomic, retain) SBScreenEdgePanGestureRecognizer *dismissGestureRecognizer;
@property (nonatomic) long long dismissalSlidingMode;
@property (nonatomic) long long dismissalTransformMode;
@property (nonatomic) long long groupCount;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SBHomeGestureSettings *homeGestureSettings;
@property (nonatomic, retain) SBIndirectPanGestureRecognizer *indirectDismissGestureRecognizer;
@property (nonatomic) bool indirectPresentGestureCalledBegin;
@property (nonatomic, retain) SBIndirectPanGestureRecognizer *indirectPresentGestureRecognizer;
@property (nonatomic) double initialTouchOffsetFromScreenEdge;
@property (nonatomic) struct CGPoint { double x1; double x2; } lastGestureVelocity;
@property (nonatomic) struct CGPoint { double x1; double x2; } lastTouchLocation;
@property (nonatomic, retain) CSLockScreenSettings *lockScreenSettings;
@property (nonatomic) bool performingCatchUpForPresentation;
@property (nonatomic, retain) SBCoverSheetPositionView *positionView;
@property (setter=_logPresentGestureState:, nonatomic) long long presentGestureState;
@property (nonatomic, retain) UIViewFloatAnimatableProperty *progressProperty;
@property (nonatomic, retain) SBProximitySensorManager *proximitySensorManager;
@property (nonatomic) bool roundsCorners;
@property (nonatomic, retain) SBFluidScrunchGestureRecognizer *scrunchDismissGestureRecognizer;
@property (readonly) Class superclass;
@property (nonatomic, retain) SBCoverSheetSystemGesturesDelegate *systemGesturesDelegate;
@property (nonatomic) CSCoverSheetTransitionSettings *transitionSettings;

- (void).cxx_destruct;
- (void)_addSystemGestureRecognizerIfUntracked:(id)arg1 withType:(unsigned long long)arg2;
- (void)_addSystemGestureRecognizers;
- (struct CGPoint { double x1; double x2; })_adjustedTouchLocationForCurrentDismissalMode:(struct CGPoint { double x1; double x2; })arg1;
- (void)_animationTickForPresentationValue:(bool)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_animationTickedWithProgress:(double)arg1 velocity:(double)arg2 forPresentationValue:(bool)arg3;
- (struct CGPoint { double x1; double x2; })_averageVelocityForGesture:(id)arg1;
- (void)_beginTransitionFromAppeared:(bool)arg1;
- (bool)_canShowWhileLocked;
- (void)_cancelTransitionForGesture:(id)arg1;
- (void)_commitTransitionToAppeared:(bool)arg1 animated:(bool)arg2;
- (void)_createProperties;
- (void)_dismissCoverSheetAnimated:(bool)arg1 withCompletion:(id /* block */)arg2;
- (void)_dismissGestureBeganWithGestureRecognizer:(id)arg1;
- (void)_dismissGestureChangedWithGestureRecognizer:(id)arg1;
- (void)_endTransitionToAppeared:(bool)arg1;
- (struct CGPoint { double x1; double x2; })_finalLocationForTransitionToPresented:(bool)arg1;
- (void)_finishTransitionToPresented:(bool)arg1 animated:(bool)arg2 withCompletion:(id /* block */)arg3;
- (id)_grabberRecognizer;
- (void)_handleDismissGesture:(id)arg1;
- (void)_handleIndirectPresentGesture:(id)arg1;
- (void)_handlePresentGesture:(id)arg1;
- (bool)_isPresentingInterstitialForGestureRecognizer:(id)arg1;
- (bool)_isTransitioning;
- (struct CGPoint { double x1; double x2; })_locationForGesture:(id)arg1;
- (void)_logDismissGestureState:(long long)arg1 forAddendumGesture:(bool)arg2;
- (void)_logPresentGestureState:(long long)arg1;
- (bool)_mathForGestureRecognizerPointsDown:(id)arg1 position:(double*)arg2 velocity:(double*)arg3 instantVelocity:(double*)arg4 averageVelocity:(double*)arg5;
- (void)_positionSubviewsForContentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 forPresentationValue:(bool)arg2;
- (void)_presentCoverSheetAnimated:(bool)arg1 forUserGesture:(bool)arg2 withCompletion:(id /* block */)arg3;
- (void)_presentGestureBeganWithGestureRecognizer:(id)arg1;
- (void)_presentOrDismissGestureChangedWithGestureRecognizer:(id)arg1;
- (void)_presentOrDismissGestureEndedWithGestureRecognizer:(id)arg1;
- (void)_removeSystemGestureRecognizers;
- (void)_setCornerRounded:(bool)arg1;
- (bool)_shouldEndPresentedForEndingGestureRecognizer:(id)arg1;
- (bool)_shouldRubberBandForGestureRecognizer:(id)arg1;
- (void)_startCatchupAnimationWithDuration:(double)arg1 completion:(id /* block */)arg2;
- (void)_studyLogForCompletionOfTransitionToPresented:(bool)arg1;
- (void)_studyLogForGestureRecognizerState:(long long)arg1 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 position:(double)arg3 velocity:(double)arg4;
- (void)_transitionToViewControllerAppearState:(int)arg1;
- (void)_transitionToViewControllerAppearState:(int)arg1 forUserGesture:(bool)arg2;
- (void)_transitionToViewControllerAppearState:(int)arg1 ifNeeded:(bool)arg2 forUserGesture:(bool)arg3;
- (void)_updateCoverSheetDismissSettings:(id)arg1;
- (void)_updateForLocation:(struct CGPoint { double x1; double x2; })arg1 interactive:(bool)arg2;
- (void)_updateHomeGestureSettings:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_updatePositionViewForProgress:(double)arg1 velocity:(double)arg2 forPresentationValue:(bool)arg3;
- (struct CGPoint { double x1; double x2; })_velocityForGesture:(id)arg1;
- (double)_viewVelocity;
- (id)activeGestureRecognizer;
- (bool)canBePulledDown;
- (bool)canBePulledUp;
- (bool)canTransitionToPresented:(bool)arg1;
- (id)catchupProperty;
- (id /* block */)completionBlock;
- (id)completionGroup;
- (id)contentViewController;
- (id)coverSheetIdentifier;
- (void)dealloc;
- (id)delegate;
- (id)dismissAddendumGestureRecognizer;
- (id)dismissGestureRecognizer;
- (long long)dismissalSlidingMode;
- (long long)dismissalTransformMode;
- (long long)groupCount;
- (id)homeGestureSettings;
- (id)indirectDismissGestureRecognizer;
- (bool)indirectPresentGestureCalledBegin;
- (id)indirectPresentGestureRecognizer;
- (id)initWithContentViewController:(id)arg1 canBePulledDown:(bool)arg2 canBePulledUp:(bool)arg3 dismissalPreemptingGestureRecognizer:(id)arg4;
- (double)initialTouchOffsetFromScreenEdge;
- (void)invalidate;
- (bool)isAnyGestureActivelyRecognized;
- (bool)isBottomMostSlider;
- (bool)isDismissGestureActive;
- (bool)isPresentGestureActive;
- (bool)isTransitioning;
- (struct CGPoint { double x1; double x2; })lastGestureVelocity;
- (struct CGPoint { double x1; double x2; })lastTouchLocation;
- (void)loadView;
- (id)lockScreenSettings;
- (bool)mathForGestureRecognizerPointsDown:(id)arg1;
- (long long)participantState;
- (bool)performingCatchUpForPresentation;
- (id)positionView;
- (long long)presentGestureState;
- (id)progressProperty;
- (id)proximitySensorManager;
- (bool)roundsCorners;
- (id)scrunchDismissGestureRecognizer;
- (void)setCanBePulledDown:(bool)arg1;
- (void)setCanBePulledUp:(bool)arg1;
- (void)setCatchupProperty:(id)arg1;
- (void)setCompletionBlock:(id /* block */)arg1;
- (void)setCompletionGroup:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDismissAddendumGestureRecognizer:(id)arg1;
- (void)setDismissGestureRecognizer:(id)arg1;
- (void)setDismissGesturesEnabled:(bool)arg1;
- (void)setDismissalSlidingMode:(long long)arg1;
- (void)setDismissalTransformMode:(long long)arg1;
- (void)setGroupCount:(long long)arg1;
- (void)setHomeGestureSettings:(id)arg1;
- (void)setIndirectDismissGestureRecognizer:(id)arg1;
- (void)setIndirectPresentGestureCalledBegin:(bool)arg1;
- (void)setIndirectPresentGestureRecognizer:(id)arg1;
- (void)setInitialTouchOffsetFromScreenEdge:(double)arg1;
- (void)setLastGestureVelocity:(struct CGPoint { double x1; double x2; })arg1;
- (void)setLastTouchLocation:(struct CGPoint { double x1; double x2; })arg1;
- (void)setLockScreenSettings:(id)arg1;
- (void)setPerformingCatchUpForPresentation:(bool)arg1;
- (void)setPositionView:(id)arg1;
- (void)setPresented:(bool)arg1 forUserGesture:(bool)arg2 animated:(bool)arg3 withCompletion:(id /* block */)arg4;
- (void)setProgressProperty:(id)arg1;
- (void)setProximitySensorManager:(id)arg1;
- (void)setRoundsCorners:(bool)arg1;
- (void)setScrunchDismissGestureRecognizer:(id)arg1;
- (void)setSystemGesturesDelegate:(id)arg1;
- (void)setTransitionSettings:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (bool)shouldAutomaticallyForwardRotationMethods;
- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (id)systemGesturesDelegate;
- (id)transitionSettings;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (bool)wantsFullScreenLayout;

@end
