
@interface SBGrabberTongue : NSObject <SBSystemGestureRecognizerDelegate> {
    bool  _beganAmbiguousPullGesture;
    UIView * _containingView;
    <BSInvalidatable> * _deferOrientationUpdatesAssertion;
    <SBGrabberTongueDelegate> * _delegate;
    UIPanGestureRecognizer * _edgePullGestureRecognizer;
    double  _gestureStartTime;
    bool  _inAmbiguousGesture;
    bool  _inDismissTongueGesture;
    bool  _inPullGesture;
    bool  _inShowTongueGesture;
    SBIndirectPanGestureRecognizer * _indirectEdgePullGestureRecognizer;
    bool  _invalidated;
    NSString * _name;
    unsigned long long  _screenEdge;
    unsigned long long  _systemGestureType;
    UITapGestureRecognizer * _tapGestureRecognizer;
    _UIBackdropView * _tongueBackdropView;
    UIImageView * _tongueChevron;
    UIView * _tongueContainer;
    bool  _tongueVisible;
    SBWindowScene * _windowScene;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) <SBGrabberTongueDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, readonly) unsigned long long screenEdge;
@property (readonly) Class superclass;
@property (getter=isVisible, nonatomic, readonly) bool visible;

- (void).cxx_destruct;
- (double)_ambiguousActivationMargin;
- (double)_ambiguousActivationMarginIfHonored;
- (void)_cancelPendingTongueDismissRequests;
- (double)_centerOnScreenEdge;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_chevronFrameForTongueBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)_createEdgePullGestureRecognizerWithAction:(SEL)arg1;
- (id)_createTapGestureRecognizerWithAction:(SEL)arg1;
- (void)_createTongueAndGestureRecognizersIfNecessaryWithColorStyle:(long long)arg1;
- (void)_didDismiss;
- (void)_didPresentInteractively:(id)arg1;
- (void)_dismissTongue:(id)arg1;
- (void)_dismissTongueWithStyle:(long long)arg1 animated:(bool)arg2;
- (double)_distanceFromEdgeForRecognizer:(id)arg1;
- (double)_edgeOrientedVelocityForRecognizer:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_frameForTongueWhenVisible:(bool)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_grabberTongueScreenInsets;
- (void)_handlePullGesture:(id)arg1;
- (void)_handleTapped:(id)arg1;
- (id)_newBackdropViewWithColorStyle:(long long)arg1;
- (id)_newChevronView;
- (void)_presentTongueAnimated:(bool)arg1 autoDismiss:(bool)arg2;
- (void)_pullGestureBegan:(id)arg1;
- (void)_pullGestureCanceled:(id)arg1;
- (void)_pullGestureEnded:(id)arg1;
- (void)_pullGestureUpdated:(id)arg1;
- (bool)_shouldAllowSecondSwipeWithRecognizer:(id)arg1;
- (bool)_shouldReceiveTouch:(id)arg1;
- (bool)_shouldSecondSwipeDismissTongueWithRecognizer:(id)arg1;
- (bool)_shouldShowTongueOnFirstSwipeWithRecognizer:(id)arg1;
- (bool)_tongueOrPullEnabledForGestureRecognizer:(id)arg1;
- (struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })_transformForTongueContainer;
- (void)_updateCancelsTouchesWithRecognizerIfNeeded:(id)arg1;
- (void)_willDismiss;
- (void)_willPresent;
- (void)_willPresentInteractively:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (bool)dismissWithStyle:(long long)arg1 animated:(bool)arg2;
- (double)distanceFromEdge;
- (double)edgeLocationForTouch:(id)arg1;
- (double)edgeOrientedVelocity;
- (id)edgePullGestureRecognizer;
- (bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)indirectEdgePullGestureRecognizer;
- (id)init;
- (id)initWithDelegate:(id)arg1 edge:(unsigned long long)arg2 type:(unsigned long long)arg3 windowScene:(id)arg4;
- (void)installInView:(id)arg1 withColorStyle:(long long)arg2;
- (void)invalidate;
- (bool)isEdgeLocationInGrabberRegion:(double)arg1;
- (bool)isVisible;
- (id)name;
- (void)presentAnimated:(bool)arg1;
- (void)presentAnimated:(bool)arg1 autoDismiss:(bool)arg2;
- (unsigned long long)screenEdge;
- (void)setName:(id)arg1;
- (void)uninstall;
- (id)viewForSystemGestureRecognizer:(id)arg1;

@end
