
@interface SBSingleSceneController : NSObject <BSDescriptionProviding, BSInvalidatable, FBSceneObserver, SBSceneSettingsUpdaterObserver, SBSceneViewControllerBuilding> {
    RBSProcessIdentity * _clientIdentity;
    SBUIKitResizableSceneHostComponent * _hostComponent;
    unsigned long long  _initialSupportedInterfaceOrientations;
    SBTraitsSceneParticipantDelegate * _lastSceneTraitsParticipantDelegate;
    SBTraitsOrientedContentViewController * _orientedSceneViewController;
    <SBScenePresenting> * _presenter;
    SBTraitsOrientedResizableContentViewController * _resizableOrientedSceneViewController;
    FBScene * _scene;
    bool  _sceneContentVisible;
    UISceneRequestOptions * _sceneOptions;
    SBSceneSettingsUpdater * _sceneSettingsUpdater;
    SBFSceneWorkspaceController * _sceneWorkspaceController;
    <BSInvalidatable> * _settingsUpdaterObserverInvalidatable;
    bool  _shouldActivateForDisplayConfiguration;
    bool  _shouldActivateUponClientConnection;
    bool  _shouldBeKeptActiveWhileForeground;
    bool  _shouldForegroundForDisplayConfiguration;
    bool  _shouldPresentAnyContentState;
    FBSDisplayConfiguration * _targetDisplayConfiguration;
    NSString * _traitsRole;
    <UIScenePresenter> * _uiScenePresenter;
    bool  _visible;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SBUIKitResizableSceneHostComponent *hostComponent;
@property (nonatomic) unsigned long long initialSupportedInterfaceOrientations;
@property (nonatomic) <SBScenePresenting> *presenter;
@property (nonatomic, readonly) FBScene *scene;
@property (getter=isSceneActive, nonatomic) bool sceneActive;
@property (getter=isSceneContentVisible, nonatomic) bool sceneContentVisible;
@property (nonatomic, readonly) UISceneRequestOptions *sceneOptions;
@property (nonatomic, readonly) NSString *scenePersistentIdentifier;
@property (nonatomic, readonly) SBFSceneWorkspaceController *sceneWorkspaceController;
@property (nonatomic) bool shouldActivateForDisplayConfiguration;
@property (nonatomic) bool shouldActivateUponClientConnection;
@property (nonatomic) bool shouldBeKeptActiveWhileForeground;
@property (nonatomic) bool shouldForegroundForDisplayConfiguration;
@property (nonatomic) bool shouldPresentAnyContentState;
@property (readonly) Class superclass;
@property (nonatomic, retain) FBSDisplayConfiguration *targetDisplayConfiguration;
@property (nonatomic, readonly) NSString *traitsRole;
@property (nonatomic) bool visible;

- (void).cxx_destruct;
- (void)_dismissScene;
- (void)_evaluateSceneActivationState;
- (void)_evaluateSceneForegroundState;
- (void)_evaluateVisibility;
- (bool)_isClientProcessRunning;
- (id)_newActivationContext;
- (void)_presentScene;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)didUpdateSceneTraitsDelegate:(id)arg1;
- (id)hostComponent;
- (id)initWithSceneWorkspaceController:(id)arg1 sceneRequestOptions:(id)arg2 clientIdentity:(id)arg3 traitsRole:(id)arg4 level:(double)arg5;
- (unsigned long long)initialSupportedInterfaceOrientations;
- (void)invalidate;
- (bool)isSceneActive;
- (bool)isSceneContentVisible;
- (id)presenter;
- (id)scene;
- (void)scene:(id)arg1 didCompleteUpdateWithContext:(id)arg2 error:(id)arg3;
- (void)sceneContentStateDidChange:(id)arg1;
- (void)sceneDidInvalidate:(id)arg1;
- (id)sceneOptions;
- (id)scenePersistentIdentifier;
- (id)sceneWorkspaceController;
- (void)setHostComponent:(id)arg1;
- (void)setInitialSupportedInterfaceOrientations:(unsigned long long)arg1;
- (void)setPresenter:(id)arg1;
- (void)setSceneActive:(bool)arg1;
- (void)setSceneContentVisible:(bool)arg1;
- (void)setShouldActivateForDisplayConfiguration:(bool)arg1;
- (void)setShouldActivateUponClientConnection:(bool)arg1;
- (void)setShouldBeKeptActiveWhileForeground:(bool)arg1;
- (void)setShouldForegroundForDisplayConfiguration:(bool)arg1;
- (void)setShouldPresentAnyContentState:(bool)arg1;
- (void)setTargetDisplayConfiguration:(id)arg1;
- (void)setVisible:(bool)arg1;
- (bool)shouldActivateForDisplayConfiguration;
- (bool)shouldActivateUponClientConnection;
- (bool)shouldBeKeptActiveWhileForeground;
- (bool)shouldForegroundForDisplayConfiguration;
- (bool)shouldPresentAnyContentState;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)targetDisplayConfiguration;
- (id)traitsOrientedResizableViewController;
- (id)traitsOrientedViewController;
- (id)traitsRole;
- (bool)visible;

@end
