
@interface SBSwitcherChamoisSettings : PTSettings {
    bool  _allowTrueMaximizeForAllApps;
    <BSDefaultObserver> * _appSwitcherDefaultsObserver;
    SBFFluidBehaviorSettings * _appToAppLayoutSettings;
    SBFFluidBehaviorSettings * _appToAppOpacitySettings;
    bool  _blurWallpaperInApps;
    bool  _cachedChamoisHideDock;
    bool  _cachedChamoisHideDockExternal;
    bool  _cachedChamoisHideStrips;
    bool  _cachedChamoisHideStripsExternal;
    SBSwitcherChamoisLayoutAttributes * _cachedChamoisLayoutAttributes;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _cachedChamoisLayoutAttributes_containerBounds;
    double  _cachedChamoisLayoutAttributes_floatingDockHeight;
    long long  _cachedChamoisLayoutAttributes_interfaceOrientation;
    bool  _cachedChamoisLayoutAttributes_isEmbeddedDisplay;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _cachedChamoisLayoutAttributes_nativeContainerReferencePixelBounds;
    bool  _cachedChamoisLayoutAttributes_prefersDockHidden;
    bool  _cachedChamoisLayoutAttributes_prefersStripHidden;
    bool  _cachedChamoisLayoutAttributes_requiresFullScreen;
    double  _cachedChamoisLayoutAttributes_statusBarHeight;
    bool  _cachedChamoisLayoutAttributes_stripDisabledWhenHidden;
    bool  _changeFocusOnClickDown;
    struct CGSize { 
        double width; 
        double height; 
    }  _diffuseShadowOffset;
    double  _diffuseShadowOpacity;
    double  _diffuseShadowRadius;
    SBSwitcherChamoisSnapPaddingSettings * _embeddedDisplaySnapPaddingSettings;
    unsigned long long  _externalDisplayHighResVerticalResolution;
    SBSwitcherChamoisSnapPaddingSettings * _externalDisplaySnapPaddingSettings;
    double  _homeGestureMinimumYDistanceForHomeOrAppSwitcher;
    SBFFluidBehaviorSettings * _liveResizeAfterReleaseLayoutAnimationSettings;
    SBFFluidBehaviorSettings * _liveResizeDuringDragLayoutAnimationSettings;
    unsigned long long  _maximumNumberOfAppsOnStage;
    unsigned long long  _numberOfRowsWhileInAppOnEmbeddedDisplay;
    unsigned long long  _numberOfRowsWhileInAppOnExternalDisplay;
    unsigned long long  _numberOfRowsWhileInAppOnExternalDisplayHighRes;
    unsigned long long  _numberOfVisibleItemsPerGroup;
    double  _pinWindowEdgeForResizeMargin;
    bool  _rasterizeScaledApps;
    bool  _rejectDropsWhenStageIsFull;
    double  _rimShadowOpacity;
    double  _rimShadowRadius;
    SBFFluidBehaviorSettings * _stageFocusChangeSettings;
    double  _stageOccludedAppScaleFactor;
    double  _stripDropZoneMultiplier;
    double  _stripsHoverRevealZoneWidthFixed;
    double  _stripsHoverRevealZoneWidthScale;
    unsigned long long  _stripsHoverRevealZoneWidthType;
    double  _switcherCornerRadius;
    double  _switcherHeightForIconAndLabelsUnderEachPile;
    double  _switcherPileCardMinimumPeekAmount;
    double  _switcherPileCompactingFactor;
    bool  _tapWallpaperToGoHome;
    bool  _useLeadingWindowEdgeForDropZoneCalculations;
    bool  _useLowFatigueStripAnimation;
    SBFFluidBehaviorSettings * _windowDragAnimationSettings;
}

@property bool allowTrueMaximizeForAllApps;
@property (retain) SBFFluidBehaviorSettings *appToAppLayoutSettings;
@property (retain) SBFFluidBehaviorSettings *appToAppOpacitySettings;
@property bool blurWallpaperInApps;
@property bool changeFocusOnClickDown;
@property struct CGSize { double x1; double x2; } diffuseShadowOffset;
@property double diffuseShadowOpacity;
@property double diffuseShadowRadius;
@property (retain) SBSwitcherChamoisSnapPaddingSettings *embeddedDisplaySnapPaddingSettings;
@property unsigned long long externalDisplayHighResVerticalResolution;
@property (retain) SBSwitcherChamoisSnapPaddingSettings *externalDisplaySnapPaddingSettings;
@property (nonatomic) double homeGestureMinimumYDistanceForHomeOrAppSwitcher;
@property (retain) SBFFluidBehaviorSettings *liveResizeAfterReleaseLayoutAnimationSettings;
@property (retain) SBFFluidBehaviorSettings *liveResizeDuringDragLayoutAnimationSettings;
@property unsigned long long maximumNumberOfAppsOnStage;
@property unsigned long long numberOfRowsWhileInAppOnEmbeddedDisplay;
@property unsigned long long numberOfRowsWhileInAppOnExternalDisplay;
@property unsigned long long numberOfRowsWhileInAppOnExternalDisplayHighRes;
@property unsigned long long numberOfVisibleItemsPerGroup;
@property double pinWindowEdgeForResizeMargin;
@property bool rasterizeScaledApps;
@property bool rejectDropsWhenStageIsFull;
@property double rimShadowOpacity;
@property double rimShadowRadius;
@property (retain) SBFFluidBehaviorSettings *stageFocusChangeSettings;
@property double stageOccludedAppScaleFactor;
@property double stripDropZoneMultiplier;
@property double stripsHoverRevealZoneWidthFixed;
@property double stripsHoverRevealZoneWidthScale;
@property unsigned long long stripsHoverRevealZoneWidthType;
@property double switcherCornerRadius;
@property double switcherHeightForIconAndLabelsUnderEachPile;
@property double switcherPileCardMinimumPeekAmount;
@property double switcherPileCompactingFactor;
@property bool tapWallpaperToGoHome;
@property bool useLeadingWindowEdgeForDropZoneCalculations;
@property bool useLowFatigueStripAnimation;
@property (retain) SBFFluidBehaviorSettings *windowDragAnimationSettings;

+ (id)settingsControllerModule;

- (void).cxx_destruct;
- (id)_gridHeightsForSafeHeight:(double)arg1 minimumHeight:(double)arg2 stageInterItemSpacing:(double)arg3;
- (id)_gridWidthsForSafeWidth:(double)arg1 minimumWidth:(double)arg2 stageInterItemSpacing:(double)arg3;
- (struct CGSize { double x1; double x2; })_nearestGridSizeForSize:(struct CGSize { double x1; double x2; })arg1 gridWidths:(id)arg2 gridHeights:(id)arg3 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4;
- (void)_observeAppSwitcherDefaults;
- (bool)_shouldPreferDockHiddenForWindowScene:(id)arg1;
- (bool)_shouldPreferStripHiddenForWindowScene:(id)arg1 interfaceOrientation:(long long)arg2;
- (double)_statusBarHeight;
- (double)_stripCardScaleForContainerBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 screenEdgePadding:(double)arg2 stripVerticalEdgeSpacing:(double)arg3 stripInterItemSpacing:(double)arg4 floatingDockHeight:(double)arg5 numberOfRows:(unsigned long long)arg6;
- (double)_stripWidthForContainerBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 screenEdgePadding:(double)arg2 stripStackDistance:(double)arg3 stripCardScale:(double)arg4 stripTiltAngle:(double)arg5 containerPerspective:(double)arg6;
- (void)_updateCachedAppSwitcherDefaults;
- (bool)allowTrueMaximizeForAllApps;
- (id)appToAppLayoutSettings;
- (id)appToAppOpacitySettings;
- (bool)blurWallpaperInApps;
- (bool)changeFocusOnClickDown;
- (void)dealloc;
- (struct CGSize { double x1; double x2; })diffuseShadowOffset;
- (double)diffuseShadowOpacity;
- (double)diffuseShadowRadius;
- (id)embeddedDisplaySnapPaddingSettings;
- (unsigned long long)externalDisplayHighResVerticalResolution;
- (id)externalDisplaySnapPaddingSettings;
- (double)homeGestureMinimumYDistanceForHomeOrAppSwitcher;
- (id)initWithDefaultValues;
- (id)layoutAttributesForContainerBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 nativeContainerReferencePixelBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 interfaceOrientation:(long long)arg3 floatingDockHeight:(double)arg4 statusBarHeight:(double)arg5 requiresFullScreen:(bool)arg6 prefersStripHidden:(bool)arg7 prefersDockHidden:(bool)arg8 isEmbeddedDisplay:(bool)arg9;
- (id)layoutAttributesForWindowScene:(id)arg1 interfaceOrientation:(long long)arg2 requiresFullScreen:(bool)arg3 floatingDockHeight:(double)arg4;
- (id)liveResizeAfterReleaseLayoutAnimationSettings;
- (id)liveResizeDuringDragLayoutAnimationSettings;
- (unsigned long long)maximumNumberOfAppsOnStage;
- (unsigned long long)numberOfRowsWhileInAppOnEmbeddedDisplay;
- (unsigned long long)numberOfRowsWhileInAppOnExternalDisplay;
- (unsigned long long)numberOfRowsWhileInAppOnExternalDisplayHighRes;
- (unsigned long long)numberOfVisibleItemsPerGroup;
- (double)pinWindowEdgeForResizeMargin;
- (bool)rasterizeScaledApps;
- (bool)rejectDropsWhenStageIsFull;
- (double)rimShadowOpacity;
- (double)rimShadowRadius;
- (void)setAllowTrueMaximizeForAllApps:(bool)arg1;
- (void)setAppToAppLayoutSettings:(id)arg1;
- (void)setAppToAppOpacitySettings:(id)arg1;
- (void)setBlurWallpaperInApps:(bool)arg1;
- (void)setChangeFocusOnClickDown:(bool)arg1;
- (void)setDefaultValues;
- (void)setDiffuseShadowOffset:(struct CGSize { double x1; double x2; })arg1;
- (void)setDiffuseShadowOpacity:(double)arg1;
- (void)setDiffuseShadowRadius:(double)arg1;
- (void)setEmbeddedDisplaySnapPaddingSettings:(id)arg1;
- (void)setExternalDisplayHighResVerticalResolution:(unsigned long long)arg1;
- (void)setExternalDisplaySnapPaddingSettings:(id)arg1;
- (void)setHomeGestureMinimumYDistanceForHomeOrAppSwitcher:(double)arg1;
- (void)setLiveResizeAfterReleaseLayoutAnimationSettings:(id)arg1;
- (void)setLiveResizeDuringDragLayoutAnimationSettings:(id)arg1;
- (void)setMaximumNumberOfAppsOnStage:(unsigned long long)arg1;
- (void)setNumberOfRowsWhileInAppOnEmbeddedDisplay:(unsigned long long)arg1;
- (void)setNumberOfRowsWhileInAppOnExternalDisplay:(unsigned long long)arg1;
- (void)setNumberOfRowsWhileInAppOnExternalDisplayHighRes:(unsigned long long)arg1;
- (void)setNumberOfVisibleItemsPerGroup:(unsigned long long)arg1;
- (void)setPinWindowEdgeForResizeMargin:(double)arg1;
- (void)setRasterizeScaledApps:(bool)arg1;
- (void)setRejectDropsWhenStageIsFull:(bool)arg1;
- (void)setRimShadowOpacity:(double)arg1;
- (void)setRimShadowRadius:(double)arg1;
- (void)setStageFocusChangeSettings:(id)arg1;
- (void)setStageOccludedAppScaleFactor:(double)arg1;
- (void)setStripDropZoneMultiplier:(double)arg1;
- (void)setStripsHoverRevealZoneWidthFixed:(double)arg1;
- (void)setStripsHoverRevealZoneWidthScale:(double)arg1;
- (void)setStripsHoverRevealZoneWidthType:(unsigned long long)arg1;
- (void)setSwitcherCornerRadius:(double)arg1;
- (void)setSwitcherHeightForIconAndLabelsUnderEachPile:(double)arg1;
- (void)setSwitcherPileCardMinimumPeekAmount:(double)arg1;
- (void)setSwitcherPileCompactingFactor:(double)arg1;
- (void)setTapWallpaperToGoHome:(bool)arg1;
- (void)setUseLeadingWindowEdgeForDropZoneCalculations:(bool)arg1;
- (void)setUseLowFatigueStripAnimation:(bool)arg1;
- (void)setWindowDragAnimationSettings:(id)arg1;
- (id)stageFocusChangeSettings;
- (double)stageOccludedAppScaleFactor;
- (double)stripDropZoneMultiplier;
- (double)stripsHoverRevealZoneWidthFixed;
- (double)stripsHoverRevealZoneWidthScale;
- (unsigned long long)stripsHoverRevealZoneWidthType;
- (double)switcherCornerRadius;
- (double)switcherHeightForIconAndLabelsUnderEachPile;
- (double)switcherPileCardMinimumPeekAmount;
- (double)switcherPileCompactingFactor;
- (bool)tapWallpaperToGoHome;
- (bool)useLeadingWindowEdgeForDropZoneCalculations;
- (bool)useLowFatigueStripAnimation;
- (id)windowDragAnimationSettings;

@end
