
@interface SBTraitsSceneParticipantDelegate : NSObject <BSInvalidatable, FBSceneObserver, SBSceneHandleObserver, SBTraitsParticipantDelegate, SBTraitsSceneSettingsUpdater> {
    id /* block */  _actuateOrientationAlongsideBlock;
    id /* block */  _actuateOrientationSettingsAlongsideBlock;
    id /* block */  _actuateZOrderAlongsideBlock;
    TRAArbiter * _arbiter;
    bool  _canDetermineActiveOrientation;
    BKSAnimationFenceHandle * _fallbackFence_90210730;
    unsigned long long  _initialSupportedOrientationsOverride;
    bool  _invalidated;
    bool  _orientationActuationAnimatable;
    bool  _orientationActuationEnabled;
    long long  _orientationMode;
    long long  _orientationModeOverride;
    SBTraitsSceneOrientationRequestAssistant * _orientationRequestActionAssistant;
    TRAParticipant * _participant;
    NSNumber * _preferredSceneLevel;
    FBScene * _scene;
    UIApplicationSceneClientSettingsDiffInspector * _sceneClientSettingsDiffInspector;
    SBSceneHandle * _sceneHandle;
}

@property (nonatomic, copy) id /* block */ actuateOrientationAlongsideBlock;
@property (nonatomic, copy) id /* block */ actuateOrientationSettingsAlongsideBlock;
@property (nonatomic, copy) id /* block */ actuateZOrderAlongsideBlock;
@property (nonatomic) TRAArbiter *arbiter;
@property (nonatomic) bool canDetermineActiveOrientation;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long initialSupportedOrientationsOverride;
@property (getter=isOrientationActuationAnimatable, nonatomic) bool orientationActuationAnimatable;
@property (getter=isOrientationActuationAnimatable, nonatomic) bool orientationActuationEnabled;
@property (nonatomic) long long orientationModeOverride;
@property (nonatomic) TRAParticipant *participant;
@property (nonatomic, retain) NSNumber *preferredSceneLevel;
@property (nonatomic) FBScene *scene;
@property (nonatomic, readonly) long long sceneCurrentOrientation;
@property (nonatomic) SBSceneHandle *sceneHandle;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (unsigned long long)_allLegalOrientations;
- (double)_angleFromScreenReferenceSpaceForSettings:(id)arg1 displayIdentity:(id)arg2;
- (id)_application;
- (unsigned long long)_bestGuessSupportedInterfaceOrientations;
- (void)_evaluateOrientationTransitionContext:(id)arg1;
- (unsigned long long)_hostReferenceAngleModeForDisplayIdentity:(id)arg1;
- (bool)_isAllowedToHavePortraitUpsideDown;
- (long long)_orientationMode;
- (long long)_preferredOrientation;
- (void)_resetToInitialState;
- (unsigned long long)_sanitizedMask:(unsigned long long)arg1 forApplication:(id)arg2;
- (unsigned long long)_supportedOrientations;
- (id /* block */)actuateOrientationAlongsideBlock;
- (id /* block */)actuateOrientationSettingsAlongsideBlock;
- (void)actuateOrientationSettingsWithContext:(id)arg1;
- (void)actuateUserInterfaceStyleSettingsWithContext:(id)arg1;
- (id /* block */)actuateZOrderAlongsideBlock;
- (void)actuateZOrderLevelSettings;
- (void)appendDescriptionForParticipant:(id)arg1 withBuilder:(id)arg2 multilinePrefix:(id)arg3;
- (id)arbiter;
- (bool)canDetermineActiveOrientation;
- (void)dealloc;
- (id)description;
- (void)didChangeSettingsForParticipant:(id)arg1 context:(id)arg2;
- (id)initWithScene:(id)arg1;
- (id)initWithSceneHandle:(id)arg1;
- (unsigned long long)initialSupportedOrientationsOverride;
- (void)invalidate;
- (bool)isOrientationActuationAnimatable;
- (bool)isOrientationActuationAnimatable;
- (bool)needsActuationForUpdateReasons:(long long)arg1;
- (long long)orientationModeOverride;
- (id)participant;
- (id)participantAssociatedSceneIdentityTokens:(id)arg1;
- (void)participantWillInvalidate:(id)arg1;
- (id)preferredSceneLevel;
- (id)scene;
- (void)scene:(id)arg1 didUpdateClientSettingsWithDiff:(id)arg2 oldClientSettings:(id)arg3 transitionContext:(id)arg4;
- (void)sceneContentStateDidChange:(id)arg1;
- (long long)sceneCurrentOrientation;
- (id)sceneHandle;
- (void)sceneHandle:(id)arg1 didCreateScene:(id)arg2;
- (void)sceneHandle:(id)arg1 didDestroyScene:(id)arg2;
- (void)setActuateOrientationAlongsideBlock:(id /* block */)arg1;
- (void)setActuateOrientationSettingsAlongsideBlock:(id /* block */)arg1;
- (void)setActuateZOrderAlongsideBlock:(id /* block */)arg1;
- (void)setArbiter:(id)arg1;
- (void)setCanDetermineActiveOrientation:(bool)arg1;
- (void)setInitialSupportedOrientationsOverride:(unsigned long long)arg1;
- (void)setOrientationActuationAnimatable:(bool)arg1;
- (void)setOrientationActuationEnabled:(bool)arg1;
- (void)setOrientationModeOverride:(long long)arg1;
- (void)setParticipant:(id)arg1;
- (void)setPreferredSceneLevel:(id)arg1;
- (void)setScene:(id)arg1;
- (void)setSceneHandle:(id)arg1;
- (void)updateOrientationSceneSettingsForParticipant:(id)arg1;
- (void)updatePreferencesForParticipant:(id)arg1 updater:(id)arg2;
- (void)updatePreferencesWithUpdater:(id)arg1;

@end
