
@interface EDAMNoteAttributes : FATObject {
    NSNumber * _altitude;
    EDAMLazyMap * _applicationData;
    NSString * _author;
    NSDictionary * _classifications;
    NSString * _conflictSourceNoteGuid;
    NSString * _contentClass;
    NSNumber * _creatorId;
    NSString * _lastEditedBy;
    NSNumber * _lastEditorId;
    NSNumber * _latitude;
    NSNumber * _longitude;
    NSNumber * _noteTitleQuality;
    NSString * _placeName;
    NSNumber * _reminderDoneTime;
    NSNumber * _reminderOrder;
    NSNumber * _reminderTime;
    NSNumber * _shareDate;
    NSNumber * _sharedWithBusiness;
    NSString * _source;
    NSString * _sourceApplication;
    NSString * _sourceURL;
    NSNumber * _subjectDate;
}

@property (nonatomic, retain) NSNumber *altitude;
@property (nonatomic, retain) EDAMLazyMap *applicationData;
@property (nonatomic, retain) NSString *author;
@property (nonatomic, retain) NSDictionary *classifications;
@property (nonatomic, retain) NSString *conflictSourceNoteGuid;
@property (nonatomic, retain) NSString *contentClass;
@property (nonatomic, retain) NSNumber *creatorId;
@property (nonatomic, retain) NSString *lastEditedBy;
@property (nonatomic, retain) NSNumber *lastEditorId;
@property (nonatomic, retain) NSNumber *latitude;
@property (nonatomic, retain) NSNumber *longitude;
@property (nonatomic, retain) NSNumber *noteTitleQuality;
@property (nonatomic, retain) NSString *placeName;
@property (nonatomic, retain) NSNumber *reminderDoneTime;
@property (nonatomic, retain) NSNumber *reminderOrder;
@property (nonatomic, retain) NSNumber *reminderTime;
@property (nonatomic, retain) NSNumber *shareDate;
@property (nonatomic, retain) NSNumber *sharedWithBusiness;
@property (nonatomic, retain) NSString *source;
@property (nonatomic, retain) NSString *sourceApplication;
@property (nonatomic, retain) NSString *sourceURL;
@property (nonatomic, retain) NSNumber *subjectDate;

+ (id)structFields;
+ (id)structName;

- (void).cxx_destruct;
- (id)altitude;
- (id)applicationData;
- (id)author;
- (id)classifications;
- (id)conflictSourceNoteGuid;
- (id)contentClass;
- (id)creatorId;
- (id)lastEditedBy;
- (id)lastEditorId;
- (id)latitude;
- (id)longitude;
- (id)noteTitleQuality;
- (id)placeName;
- (id)reminderDoneTime;
- (id)reminderOrder;
- (id)reminderTime;
- (void)setAltitude:(id)arg1;
- (void)setApplicationData:(id)arg1;
- (void)setAuthor:(id)arg1;
- (void)setClassifications:(id)arg1;
- (void)setConflictSourceNoteGuid:(id)arg1;
- (void)setContentClass:(id)arg1;
- (void)setCreatorId:(id)arg1;
- (void)setLastEditedBy:(id)arg1;
- (void)setLastEditorId:(id)arg1;
- (void)setLatitude:(id)arg1;
- (void)setLongitude:(id)arg1;
- (void)setNoteTitleQuality:(id)arg1;
- (void)setPlaceName:(id)arg1;
- (void)setReminderDoneTime:(id)arg1;
- (void)setReminderOrder:(id)arg1;
- (void)setReminderTime:(id)arg1;
- (void)setShareDate:(id)arg1;
- (void)setSharedWithBusiness:(id)arg1;
- (void)setSource:(id)arg1;
- (void)setSourceApplication:(id)arg1;
- (void)setSourceURL:(id)arg1;
- (void)setSubjectDate:(id)arg1;
- (id)shareDate;
- (id)sharedWithBusiness;
- (id)source;
- (id)sourceApplication;
- (id)sourceURL;
- (id)subjectDate;

@end
