
@interface IOPortLDCMManagerV4 : NSObject {
    bool  _behaviorOverrideDisableMitigations;
    bool  _behaviorOverrideDisableUI;
    int  _buildType;
    int  _currentMitigationsStatus;
    unsigned long long  _dryPollingInterval;
    bool  _isReceptacleEmpty;
    unsigned char  _isWet;
    unsigned int  _ldcmFeatureConnect;
    NSObject<OS_dispatch_queue> * _ldcmV4DispatchQueue;
    NSString * _measurementInfoOutputString;
    bool  _mitigationsEnabled;
    unsigned int  _notification;
    LDCMNotificationUIManagerV4 * _notificationUIManager;
    bool  _overrideEnabled;
    unsigned char  _previousLDCMPortStatus;
    NSObject<OS_dispatch_source> * _timer;
    bool  _uiActive;
    bool  _waveformExtractionDisabled;
    unsigned long long  _wetPollingInterval;
}

@property (nonatomic) bool behaviorOverrideDisableMitigations;
@property (nonatomic) bool behaviorOverrideDisableUI;
@property (nonatomic) int buildType;
@property (nonatomic) int currentMitigationsStatus;
@property (nonatomic) unsigned long long dryPollingInterval;
@property (nonatomic) bool isReceptacleEmpty;
@property (nonatomic) unsigned char isWet;
@property (nonatomic) unsigned int ldcmFeatureConnect;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *ldcmV4DispatchQueue;
@property (nonatomic) NSString *measurementInfoOutputString;
@property (nonatomic) bool mitigationsEnabled;
@property (nonatomic) unsigned int notification;
@property (nonatomic, retain) LDCMNotificationUIManagerV4 *notificationUIManager;
@property (nonatomic) bool overrideEnabled;
@property (nonatomic) unsigned char previousLDCMPortStatus;
@property (nonatomic, retain) NSObject<OS_dispatch_source> *timer;
@property (nonatomic) bool uiActive;
@property (nonatomic) bool waveformExtractionDisabled;
@property (nonatomic) unsigned long long wetPollingInterval;

- (void).cxx_destruct;
- (bool)behaviorOverrideDisableMitigations;
- (bool)behaviorOverrideDisableUI;
- (id)buildMeasurementHeaderString;
- (id)buildMeasurementOutputString:(id)arg1 withMeasurementReason:(int)arg2 withMeasurementEvent:(id)arg3;
- (int)buildType;
- (bool)checkIsReceptacleEmpty;
- (int)currentMitigationsStatus;
- (void)dealloc;
- (unsigned long long)dryPollingInterval;
- (id)extractData:(unsigned int*)arg1 :(unsigned long long)arg2;
- (void)generateLDCMCSVData;
- (int)getData:(char *)arg1 :(unsigned long long*)arg2;
- (id)getMeasurementOutputString;
- (int)getWaveform:(char *)arg1 :(unsigned long long*)arg2;
- (void)handleAttachEvent;
- (void)handleDetachEvent;
- (void)handleLDCMInterrupt;
- (void)handleLDCMMitigationsStatusChange:(int)arg1;
- (void)hideUI;
- (id)initWithParams:(unsigned long long)arg1 withDryPollingInterval:(unsigned long long)arg2 withService:(unsigned int)arg3 withNotificationPort:(struct IONotificationPort { }*)arg4 withServerRunloop:(struct __CFRunLoop { }*)arg5;
- (bool)isReceptacleEmpty;
- (unsigned char)isWet;
- (unsigned int)ldcmFeatureConnect;
- (id)ldcmV4DispatchQueue;
- (void)logInfo:(id)arg1;
- (id)measurementInfoOutputString;
- (bool)mitigationsEnabled;
- (unsigned int)notification;
- (id)notificationUIManager;
- (bool)overrideEnabled;
- (void)performLDCMMeasurement:(int)arg1;
- (unsigned char)previousLDCMPortStatus;
- (void)processBehaviorDictionary:(id)arg1;
- (id)publishAnalytics:(id)arg1 withMeasurementReason:(int)arg2 withWaveformRawData:(char *)arg3 withWaveformDataLen:(unsigned long long)arg4;
- (void)setBehaviorOverrideDisableMitigations:(bool)arg1;
- (void)setBehaviorOverrideDisableUI:(bool)arg1;
- (void)setBuildType:(int)arg1;
- (void)setCurrentMitigationsStatus:(int)arg1;
- (void)setDryPollingInterval:(unsigned long long)arg1;
- (void)setIsReceptacleEmpty:(bool)arg1;
- (void)setIsWet:(unsigned char)arg1;
- (int)setLDCMMeasurementStatus:(int)arg1;
- (int)setLDCMState:(int)arg1;
- (void)setLdcmFeatureConnect:(unsigned int)arg1;
- (void)setLdcmV4DispatchQueue:(id)arg1;
- (int)setLiquidDetected:(unsigned char)arg1;
- (void)setMeasurementInfoOutputString:(id)arg1;
- (int)setMitigations:(unsigned char)arg1;
- (void)setMitigationsEnabled:(bool)arg1;
- (void)setNotification:(unsigned int)arg1;
- (void)setNotificationUIManager:(id)arg1;
- (void)setOverride:(unsigned char)arg1;
- (void)setOverrideEnabled:(bool)arg1;
- (void)setPreviousLDCMPortStatus:(unsigned char)arg1;
- (void)setTimer:(id)arg1;
- (void)setUiActive:(bool)arg1;
- (int)setUserOverride:(unsigned char)arg1;
- (void)setWaveformExtractionDisabled:(bool)arg1;
- (int)setWaveformExtractionEnabled:(unsigned char)arg1;
- (void)setWetPollingInterval:(unsigned long long)arg1;
- (void)showUI;
- (void)storeWaveform:(char *)arg1 withWaveformDataLen:(unsigned long long)arg2;
- (id)timer;
- (bool)uiActive;
- (bool)waveformExtractionDisabled;
- (unsigned long long)wetPollingInterval;

@end
