
@protocol CMLXPCInterface

@required

- (void)asyncResponseDataByKeyword:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSData *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSString *, NSError *, void*
- (void)asyncResponseDataByKeywords:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSString *, NSError *, void*
- (void)asyncResponseSimilarityScoresForElements:(void *)arg1 shardIndices:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: NSArray *, NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSString *, NSError *, void*
- (void)constructPIRBatchRequestWithIndices:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)constructPIRBatchRequestWithKeywords:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)constructPIRRequestWithIndex:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: unsigned long long, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)constructPIRRequestWithKeyword:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSData *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)constructPIRRequestWithLatitude:(void *)arg1 longitude:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: double, double, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)decryptBatchOfSimilarityScores:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSData *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)decryptPIRBatchResponse:(void *)arg1 indices:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: NSData *, NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)decryptPIRBatchResponse:(void *)arg1 keywords:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: NSData *, NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)decryptPIRResponse:(void *)arg1 index:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: NSData *, unsigned long long, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)decryptPIRResponse:(void *)arg1 keyword:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: NSData *, NSData *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)decryptPIRResponse:(void *)arg1 latitude:(void *)arg2 longitude:(void *)arg3 useCase:(void *)arg4 reply:(void *)arg5; // needs 5 arg types, found 11: NSData *, double, double, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)encryptBatchOfElements:(void *)arg1 shardIndices:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: NSArray *, NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)queryStatusForUseCases:(void *)arg1 options:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSArray *, unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)requestDataByIndex:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: unsigned long long, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)requestDataByIndices:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)requestDataByKeyword:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSData *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)requestDataByKeywords:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)requestDataByLatitude:(void *)arg1 longitude:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: double, double, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)setPECConfig:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: CMLPECConfig *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (void)setPIRConfig:(void *)arg1 useCase:(void *)arg2 reply:(void *)arg3; // needs 3 arg types, found 9: CMLPIRConfig *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)similarityScoresForElements:(void *)arg1 shardIndices:(void *)arg2 useCase:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 10: NSArray *, NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*

@end
