
@protocol DNDSRemoteServiceProviderDelegate <DNDSRemoteServiceProviderBehaviorResolutionDelegate, DNDSRemoteServiceProviderAssertionDelegate, DNDSRemoteServiceProviderStateDelegate, DNDSRemoteServiceProviderSettingsDelegate, DNDSRemoteServiceProviderModeConfigurationsDelegate, DNDSRemoteServiceProviderGlobalConfigurationDelegate, DNDSRemoteServiceProviderAppInfoDelegate, DNDSRemoteServiceProviderMeDeviceStateDelegate, DNDSRemoteServiceProviderAuxiliaryStateDelegate, DNDSRemoteServiceProviderAppConfigurationDelegate>

@end
