
@protocol FPXVendor <FPXOperationService, FPXVendorObservation>

@required

- (void)URLForItemID:(void *)arg1 creatingPlaceholderIfMissing:(void *)arg2 ignoreAlternateContentsURL:(void *)arg3 completionHandler:(void *)arg4; // needs 4 arg types, found 11: FPItemID *, bool, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPSandboxingURLWrapper *, FPSandboxingURLWrapper *, NSError *, void*
- (void)_test_callFileProviderManagerAPIs:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)beginRequestWithDomain:(void *)arg1 alternateContentsDictionary:(void *)arg2 domainServicer:(void *)arg3 providerDomain:(void *)arg4 domainVersion:(void *)arg5 completionHandler:(void *)arg6; // needs 6 arg types, found 11: NSFileProviderDomain *, NSDictionary *, <FPDDomainServicing> *, FPProviderDomain *, NSFileProviderDomainVersion *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)bulkEvictItemsWithItemIDs:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: NSArray *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (NSProgress *)createItemBasedOnTemplate:(void *)arg1 fields:(void *)arg2 contents:(void *)arg3 options:(void *)arg4 request:(void *)arg5 bounce:(void *)arg6 completionHandler:(void *)arg7; // needs 7 arg types, found 16: FPItem *, unsigned long long, FPSandboxingURLWrapper *, unsigned long long, NSFileProviderRequest *, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPItem *, unsigned long long, bool, FPExtensionResponse *, NSError *, void*
- (NSProgress *)deleteItemWithID:(void *)arg1 baseVersion:(void *)arg2 options:(void *)arg3 request:(void *)arg4 completionHandler:(void *)arg5; // needs 5 arg types, found 11: FPItemID *, NSFileProviderItemVersion *, unsigned long long, NSFileProviderRequest *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPExtensionResponse *, NSError *, void*
- (void)deleteSearchableItemsWithSpotlightDomainIdentifiers:(void *)arg1 domainIdentifier:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 8: NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)didChangeItemID:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: FPItemID *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)didUpdateAlternateContentsDocumentForDocumentWithURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)dropDomainWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)dropIndexForDomain:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)dumpIndexStateForDomain:(void *)arg1 toFileHandler:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 8: NSString *, NSFileHandle *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)dumpInternalStateToTermDumper:(void *)arg1 domainIdentifier:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 8: FPCTLTermDumper *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)evictItemAtURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPItemID *, NSError *, void*
- (void)fetchAlternateContentsURLWrapperForURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPSandboxingURLWrapper *, NSError *, void*
- (NSProgress *)fetchContentsForItemWithID:(void *)arg1 version:(void *)arg2 request:(void *)arg3 estimatedItemSize:(void *)arg4 isSymlink:(void *)arg5 extent:(void *)arg6 alignment:(void *)arg7 options:(void *)arg8 completionHandler:(void *)arg9; // needs 9 arg types, found 19: FPItemID *, NSFileProviderItemVersion *, NSFileProviderRequest *, long long, bool, NSValue *, unsigned long long, unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPSandboxingURLWrapper *, FPItem *, FPExtensionResponse *, NSValue *, unsigned long long, NSError *, void*
- (NSProgress *)fetchContentsForItemWithID:(void *)arg1 version:(void *)arg2 usingExistingContentsAtURL:(void *)arg3 existingVersion:(void *)arg4 request:(void *)arg5 estimatedItemSize:(void *)arg6 isSymlink:(void *)arg7 completionHandler:(void *)arg8; // needs 8 arg types, found 17: FPItemID *, NSFileProviderItemVersion *, FPSandboxingURLWrapper *, NSFileProviderItemVersion *, NSFileProviderRequest *, long long, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPSandboxingURLWrapper *, FPItem *, FPExtensionResponse *, unsigned long long, NSError *, void*
- (void)fetchCustomPushTopicsWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)fetchOperationServiceEndpoint:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSXPCListenerEndpoint *, NSError *, void*
- (void)fetchServicesForItemID:(void *)arg1 allowRestrictedSources:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 10: FPItemID *, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSXPCListenerEndpoint *, NSArray *, NSError *, void*
- (void)fetchVendorEndpoint:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSXPCListenerEndpoint *, NSError *, void*
- (void)forceUpdateBlockedProcessNamesFromDomain:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)identifierForItemAtURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPItemID *, NSError *, void*
- (void)importDidFinishWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)indexOneBatchInDomain:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)itemChangedAtURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)itemForItemID:(void *)arg1 request:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 10: FPItemID *, NSFileProviderRequest *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPItem *, FPExtensionResponse *, NSError *, void*
- (void)itemForURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPItem *, NSError *, void*
- (void)listRemoteVersionsWithSettings:(void *)arg1 observer:(void *)arg2 request:(void *)arg3 completionHandler:(void *)arg4; // needs 4 arg types, found 10: FPExtensionEnumerationSettings *, <FPXEnumeratorObserver> *, NSFileProviderRequest *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, <FPXEnumerator> *, NSError *, void*
- (NSProgress *)modifyItem:(void *)arg1 baseVersion:(void *)arg2 changedFields:(void *)arg3 contents:(void *)arg4 options:(void *)arg5 request:(void *)arg6 completionHandler:(void *)arg7; // needs 7 arg types, found 16: FPItem *, NSFileProviderItemVersion *, unsigned long long, FPSandboxingURLWrapper *, unsigned long long, NSFileProviderRequest *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPItem *, unsigned long long, bool, FPExtensionResponse *, NSError *, void*
- (void)movingItemAtURL:(void *)arg1 requiresProvidingWithDestinationURL:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 9: NSURL *, NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)providePlaceholderAtURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSURL *, NSError *, void*
- (void)removeTrashedItemsOlderThanDate:(void *)arg1 domainIdentifier:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 8: NSDate *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)setAlternateContentsURL:(void *)arg1 forDocumentWithURL:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 9: FPSandboxingURLWrapper *, NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, FPItemID *, NSError *, void*
- (void)signalEnumeratorForMaterializedItemsWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)signalEnumeratorForPendingItemsWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)startProvidingItemAtURL:(void *)arg1 readingOptions:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 8: NSURL *, unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)trashItemAtURL:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSURL *, NSError *, void*
- (void)valuesForAttributes:(void *)arg1 forItemID:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 9: NSArray *, FPItemID *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSDictionary *, NSError *, void*
- (void)waitForStabilizationWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)wakeForPushWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*

@end
