
@protocol PLPhotoAnalysisLegacyServiceProtocol <PLPhotoAnalysisJobServiceProtocol, PLPhotoAnalysisGraphServiceProtocol, PLPhotoAnalysisGraphServiceMusicProtocol, PLPhotoAnalysisGraphServiceClientProtocol, PLPhotoAnalysisVisionServiceFaceProcessingProtocol, PLPhotoAnalysisPresentationServiceProtocol>

@end
