
@interface AVCSession : NSObject <AVCSessionParticipantControlProtocol, AVCSessionParticipantDelegate> {
    int  _activeConfigurationCount;
    NSData * _cachedNegotiationData;
    NSDictionary * _capabilities;
    AVCSessionConfiguration * _configuration;
    VCXPCClientShared * _connection;
    id  _delegate;
    NSObject<OS_dispatch_queue> * _delegateNotificationQueue;
    NSData * _frequencyLevels;
    AVCSessionParticipant * _localParticipant;
    NSMutableDictionary * _participantsToAdd;
    VCSessionPresentationInfo * _presentationInfo;
    NSMutableDictionary * _remoteParticipants;
    long long  _sessionToken;
    NSObject<OS_dispatch_queue> * _stateQueue;
    NSString * _transportToken;
    NSString * _uuid;
}

@property (getter=isAudioEnabled, nonatomic) bool audioEnabled;
@property (getter=isAudioMuted, nonatomic) bool audioMuted;
@property (getter=isAudioPaused, nonatomic) bool audioPaused;
@property (nonatomic, retain) NSDictionary *capabilities;
@property (nonatomic, retain) AVCSessionConfiguration *configuration;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <AVCSessionDelegate> *delegate;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *delegateNotificationQueue;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSData *frequencyLevels;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) AVCSessionParticipant *localParticipant;
@property (nonatomic, readonly) NSData *negotiationData;
@property (getter=isOneToOneEnabled, nonatomic) bool oneToOneEnabled;
@property (nonatomic, readonly) NSMutableDictionary *participantsToAdd;
@property (nonatomic) struct tagAVCSessionPresentationInfo { struct CGRect { struct CGPoint { double x_1_2_1; double x_1_2_2; } x_1_1_1; struct CGSize { double x_2_2_1; double x_2_2_2; } x_1_1_2; } x1; unsigned int x2; unsigned int x3; unsigned char x4; } presentationInfo;
@property (nonatomic, readonly) NSArray *remoteParticipants;
@property (nonatomic, readonly) NSMutableDictionary *remoteParticipantsMap;
@property (getter=isScreenEnabled, nonatomic) bool screenEnabled;
@property (nonatomic, readonly) long long sessionToken;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSString *uuid;
@property (getter=isVideoEnabled, nonatomic) bool videoEnabled;
@property (getter=isVideoPaused, nonatomic) bool videoPaused;
@property (nonatomic) float volume;
@property (nonatomic, readonly) VCXPCClientShared *xpcConnection;

+ (id)configurationWithSessionMode:(long long)arg1;
+ (int)mediaNegotiatorVersionWithNegotiationProtocolVersion:(unsigned int)arg1;

- (void)addParticipant:(id)arg1;
- (void)addParticipants:(id)arg1;
- (void)appendConfigurationToXPCArguments:(id)arg1;
- (void)beginParticipantConfiguration;
- (id)capabilities;
- (id)configuration;
- (void)dealloc;
- (id)delegate;
- (id)delegateNotificationQueue;
- (void)deregisterFromNotifications;
- (id)description;
- (void)didAddParticipantHandlerWithResult:(id)arg1;
- (id)dispatchedConfiguration;
- (void)endParticipantConfiguration;
- (id)frequencyLevels;
- (id)initPrivateWithTransportToken:(id)arg1 configuration:(id)arg2 negotiationData:(id)arg3 delegate:(id)arg4 queue:(id)arg5;
- (id)initWithTransportToken:(id)arg1 configuration:(id)arg2 delegate:(id)arg3 queue:(id)arg4;
- (id)initWithTransportToken:(id)arg1 configuration:(id)arg2 negotiationData:(id)arg3 delegate:(id)arg4 queue:(id)arg5;
- (bool)isAudioEnabled;
- (bool)isAudioMuted;
- (bool)isAudioPaused;
- (bool)isOneToOneEnabled;
- (bool)isScreenEnabled;
- (bool)isVideoEnabled;
- (bool)isVideoPaused;
- (id)localParticipant;
- (unsigned int)mediaStateForMediaType:(unsigned int)arg1;
- (id)negotiationData;
- (id)negotiationDataForLoopbackParticipant;
- (id)negotiationDataForProtocolVersion:(unsigned int)arg1;
- (id)newNSErrorWithErrorDictionary:(id)arg1;
- (void)participant:(id)arg1 audioEnabled:(bool)arg2 didSucceed:(bool)arg3 error:(id)arg4;
- (void)participant:(id)arg1 audioPaused:(bool)arg2 didSucceed:(bool)arg3 error:(id)arg4;
- (void)participant:(id)arg1 didReact:(id)arg2;
- (void)participant:(id)arg1 frequencyLevelsDidChange:(id)arg2;
- (void)participant:(id)arg1 mediaPrioritiesDidChange:(id)arg2;
- (void)participant:(id)arg1 mediaStateDidChange:(unsigned int)arg2 forMediaType:(unsigned int)arg3 didSucceed:(bool)arg4 error:(id)arg5;
- (void)participant:(id)arg1 mixingDidStartForMediaType:(unsigned int)arg2 mixingMediaType:(unsigned int)arg3;
- (void)participant:(id)arg1 mixingDidStopForMediaType:(unsigned int)arg2;
- (void)participant:(id)arg1 screenEnabled:(bool)arg2 didSucceed:(bool)arg3 error:(id)arg4;
- (void)participant:(id)arg1 videoEnabled:(bool)arg2 didSucceed:(bool)arg3 error:(id)arg4;
- (void)participant:(id)arg1 videoPaused:(bool)arg2 didSucceed:(bool)arg3 error:(id)arg4;
- (void)participantDidStopReacting:(id)arg1;
- (id)participantsToAdd;
- (struct tagAVCSessionPresentationInfo { struct CGRect { struct CGPoint { double x_1_2_1; double x_1_2_2; } x_1_1_1; struct CGSize { double x_2_2_1; double x_2_2_2; } x_1_1_2; } x1; unsigned int x2; unsigned int x3; unsigned char x4; })presentationInfo;
- (void)registerBlocksForNotifications;
- (id)remoteParticipants;
- (id)remoteParticipantsMap;
- (void)removeParticipant:(id)arg1;
- (void)removeParticipants:(id)arg1;
- (long long)sessionToken;
- (void)setAudioEnabled:(bool)arg1;
- (void)setAudioMuted:(bool)arg1;
- (void)setAudioPaused:(bool)arg1;
- (void)setCapabilities:(id)arg1;
- (void)setConfiguration:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMediaState:(unsigned int)arg1 forMediaType:(unsigned int)arg2;
- (void)setOneToOneEnabled:(bool)arg1;
- (void)setPresentationInfo:(struct tagAVCSessionPresentationInfo { struct CGRect { struct CGPoint { double x_1_2_1; double x_1_2_2; } x_1_1_1; struct CGSize { double x_2_2_1; double x_2_2_2; } x_1_1_2; } x1; unsigned int x2; unsigned int x3; unsigned char x4; })arg1;
- (void)setScreenEnabled:(bool)arg1;
- (void)setVideoEnabled:(bool)arg1;
- (void)setVideoPaused:(bool)arg1;
- (void)setVolume:(float)arg1;
- (void)setupNotificationQueue:(id)arg1;
- (void)start;
- (void)stop;
- (void)stopWithError:(id)arg1;
- (void)updateConfiguration:(id)arg1;
- (void)updateOneToOneModeEnabled:(bool)arg1;
- (id)uuid;
- (void)validateParticipantConfiguration;
- (bool)validateParticipantToAdd:(id)arg1;
- (bool)validateParticipantToRemove:(id)arg1;
- (float)volume;
- (id)xpcConnection;

@end
