
@interface VCDefaults : NSObject {
    int  _forceBitrate;
    int  _forceCaptureHeight;
    int  _forceCaptureWidth;
    int  _forceEncodeFramerate;
    int  _forceEncodeHeight;
    int  _forceEncodeWidth;
    int  _forceFramerate;
    int  _forceKeyFrameInterval;
    int  _forceRecvVideoPayload;
    int  _forceVideoPayload;
    bool  _forceWiFiAssist;
    bool  _forceWiFiAssistOutOfBudget;
    bool  _isFECVersion2Enabled;
}

@property (readonly) unsigned int aacBlockSize;
@property (readonly) unsigned char audioPriorityDecayFast;
@property (readonly) unsigned char audioPriorityDecaySlow;
@property (readonly) unsigned char audioPriorityRampUpSpeed;
@property (readonly) bool audioRecordingEnabled;
@property (readonly) float audioVoiceDetectionSensitivity;
@property (readonly) bool bandwidthEstimationDumpEnabled;
@property (readonly) int bundleAudio;
@property (readonly) bool cameraVideoStablization;
@property (readonly) bool canDecodeHD;
@property (readonly) unsigned char cannedVideoPacketMode;
@property (readonly) float depthFrameRateMultiplier;
@property (readonly) bool disableRed;
@property (readonly) bool disableVAD;
@property (readonly) bool dumpMediaBlob;
@property (readonly) bool enableBitstreamCapture;
@property (readonly) bool enableGFTStatsReceiveThread;
@property (readonly) bool enableGFTStatsReporting;
@property (readonly) bool enableHEIFAndHEVCForMoments;
@property (readonly) bool enablePacketLogging;
@property (readonly) bool enableRecvBitstreamDump;
@property (readonly) int enableRxDecodeYUVDump;
@property (readonly) bool enableTxBitstreamDump;
@property (readonly) int enableTxSourceYuvDump;
@property (readonly) bool enableTxTimestampAlignmentLogs;
@property (readonly) bool enableVPBLogging;
@property (readonly) int enableiRATSuggestion;
@property (readonly) int encodingScore;
@property (readonly) int extraPayloads;
@property (readonly) bool forceARCapture;
@property (readonly) int forceAudioBitrate;
@property (readonly) int forceAudioChannelCount;
@property (readonly) int forceAudioHardwareSampleRate;
@property (readonly) int forceAudioPacketsPerBundle;
@property (readonly) int forceAudioPayload;
@property (readonly) float forceAudioPowerThreshold;
@property (readonly) int forceAudioPowerTimeInterval;
@property (readonly) bool forceAudioPriorityEnabled;
@property (readonly) unsigned char forceAudioPriorityValue;
@property (readonly) int forceBitrate;
@property (readonly) int forceCaptureHeight;
@property (readonly) int forceCaptureWidth;
@property (readonly) bool forceDisableAudioPowerSpectrumRegister;
@property (readonly) bool forceDisableEffectsHealthCheck;
@property (readonly) bool forceDisableFaceZoom;
@property (readonly) bool forceDisableMediaEncryption;
@property (readonly) bool forceDisableMediaPriority;
@property (readonly) bool forceDisableMediaQueue;
@property (readonly) bool forceDisableMediaStalled;
@property (readonly) bool forceDisableMessageEncryption;
@property (readonly) bool forceDisableProcessSpecificRequirements;
@property (readonly) bool forceDisableReporting;
@property (readonly) bool forceDisableSSRCCollisionDetection;
@property (readonly) bool forceDisableThermal;
@property (readonly) bool forceDisableVideoDegraded;
@property (readonly) bool forceDisableVideoRuleCell720;
@property (readonly) bool forceDisableVideoRuleWiFi1080;
@property (readonly) bool forceDynamicEffectsFramerate;
@property (readonly) bool forceEVSWideBand;
@property (readonly) bool forceEnablePearlCamera;
@property (readonly) int forceEncodeFramerate;
@property (readonly) int forceEncodeHeight;
@property (readonly) int forceEncodeWidth;
@property (readonly) bool forceFECRepairStream;
@property (readonly) int forceFramerate;
@property (readonly) bool forceHWI;
@property (readonly) bool forceIPv6;
@property (readonly) int forceKeyFrameInterval;
@property (readonly) bool forceMirroredCapture;
@property (readonly) bool forceMultiwayHWI;
@property (readonly) bool forceMuteAtStart;
@property (readonly) bool forceOneToOneMode;
@property (readonly) int forceRecvVideoPayload;
@property (readonly) int forceRedMaxDelay;
@property (readonly) int forceRedNumPayloads;
@property (readonly) bool forceScreenHWI;
@property (readonly) bool forceUseFloat;
@property (readonly) int forceVideoPayload;
@property (readonly) bool forceVideoStreamDisableBitrateCap;
@property (readonly) int forceVideoStreamFramerate;
@property (readonly) int forceVideoStreamKeyFrameInterval;
@property (readonly) bool forceVideoStreamLowLatency;
@property (readonly) int forceVideoStreamPayload;
@property (readonly) int forceVideoStreamResolution;
@property (readonly) int forceVideoStreamRxMaxBitrate;
@property (readonly) int forceVideoStreamRxMinBitrate;
@property (readonly) int forceVideoStreamTxMaxBitrate;
@property (readonly) int forceVideoStreamTxMinBitrate;
@property (readonly) unsigned int forceVisibilityIndex;
@property (readonly) bool forceWiFiAssist;
@property (readonly) bool forceWiFiAssistOutOfBudget;
@property (readonly) bool isFECVersion2Enabled;
@property (readonly) bool isReceiverTestVerificationEnabled;
@property (readonly) bool isTransmitterTestVerificationEnabled;
@property (readonly) int localRATTypeOverride;
@property (readonly) int localWRMLinkType;
@property (readonly) int max2GRate;
@property (readonly) unsigned int maxActiveVideoDecoders;
@property (readonly) unsigned int maxActiveVideoEncoders;
@property (readonly) bool mediaQueueDumpEnabled;
@property (readonly) unsigned int minParticipantCountSendVoiceActiveOnly;
@property (readonly) bool momentsUseBestVideoRule;
@property (readonly) bool momentsUserPreferenceEnabled;
@property (readonly) unsigned int multiwayAudioNetworkBitrateCapCellular;
@property (readonly) unsigned int multiwayAudioNetworkBitrateCapWifi;
@property (readonly) unsigned int multiwayVideoNetworkBitrateCapCellular;
@property (readonly) unsigned int multiwayVideoNetworkBitrateCapWifi;
@property (readonly) bool offerAnetecCodecEnabled;
@property (readonly) int packetExpirationTime;
@property (readonly) float pauseHeartbeatInterval;
@property (readonly) unsigned int prominenceActiveAccumulationThreshold;
@property (readonly) unsigned int prominenceActiveProbabilityThreshold;
@property (readonly) unsigned int prominenceInactiveAccumulationThreshold;
@property (readonly) unsigned int prominenceInactiveProbabilityThreshold;
@property (readonly) bool rateControlAllowBurstyLossRampDown;
@property (readonly) bool rateControlAllowVideoStop;
@property (readonly) int rateControlBasebandSlowDownFactor;
@property (readonly) bool rateControlDumpEnabled;
@property (readonly) int rateControlForceRxCap;
@property (readonly) int rateControlForceRxRate;
@property (readonly) int rateControlForceTxCap;
@property (readonly) int rateControlForceTxRate;
@property (readonly) bool rateControlLogEnabled;
@property (readonly) int rateControlStatisticsQueueWaitTime;
@property (readonly) int rateControllerType;
@property (readonly) int redundancyControlForceVideoRedundancyPercentage;
@property (readonly) double remoteMediaStallTimeout;
@property (readonly) bool shouldDisplayVideoInfoLayer;
@property (readonly) unsigned int silenceLevelMovingAveragePeriod;
@property (readonly) bool supportsOneToOneMode;
@property (readonly) bool useCannedVideoPackets;
@property (readonly) bool useSBR;
@property (readonly) bool useVirtualCapture;
@property (readonly) int videoStreamRateControlAlgorithm;
@property (readonly) bool videoStreamRateControlDumpEnabled;
@property (readonly) NSString *virtualHardware;

+ (bool)booleanValueForKey:(struct __CFString { }*)arg1;
+ (bool)booleanValueForKey:(struct __CFString { }*)arg1 defaultValue:(bool)arg2;
+ (id)copyStringValueForKey:(struct __CFString { }*)arg1;
+ (double)getDoubleValueForKey:(struct __CFString { }*)arg1 defaultValue:(double)arg2;
+ (long long)integerValueForKey:(struct __CFString { }*)arg1;
+ (long long)integerValueForKey:(struct __CFString { }*)arg1 defaultValue:(long long)arg2;
+ (id)sharedInstance;

- (unsigned int)aacBlockSize;
- (id)allocWithZone:(struct _NSZone { }*)arg1;
- (unsigned char)audioPriorityDecayFast;
- (unsigned char)audioPriorityDecaySlow;
- (unsigned char)audioPriorityRampUpSpeed;
- (bool)audioRecordingEnabled;
- (float)audioVoiceDetectionSensitivity;
- (id)autorelease;
- (bool)bandwidthEstimationDumpEnabled;
- (int)bundleAudio;
- (bool)cameraVideoStablization;
- (bool)canDecodeHD;
- (unsigned char)cannedVideoPacketMode;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (float)depthFrameRateMultiplier;
- (bool)disableRed;
- (bool)disableVAD;
- (bool)dumpMediaBlob;
- (bool)enableAudioDumpParticipantLocal:(bool)arg1;
- (bool)enableAudioDumpParticipantRemote:(bool)arg1;
- (bool)enableBitstreamCapture;
- (bool)enableGFTStatsReceiveThread;
- (bool)enableGFTStatsReporting;
- (bool)enableHEIFAndHEVCForMoments;
- (bool)enablePacketLogging;
- (bool)enableRecvBitstreamDump;
- (int)enableRxDecodeYUVDump;
- (bool)enableTxBitstreamDump;
- (int)enableTxSourceYuvDump;
- (bool)enableTxTimestampAlignmentLogs;
- (bool)enableVPBLogging;
- (int)enableiRATSuggestion;
- (int)encodingScore;
- (int)extraPayloads;
- (bool)forceARCapture;
- (int)forceAudioBitrate;
- (int)forceAudioChannelCount;
- (int)forceAudioHardwareSampleRate;
- (int)forceAudioPacketsPerBundle;
- (int)forceAudioPayload;
- (float)forceAudioPowerThreshold;
- (int)forceAudioPowerTimeInterval;
- (bool)forceAudioPriorityEnabled;
- (unsigned char)forceAudioPriorityValue;
- (int)forceBitrate;
- (int)forceCaptureHeight;
- (int)forceCaptureWidth;
- (bool)forceDisableAudioPowerSpectrumRegister;
- (bool)forceDisableEffectsHealthCheck;
- (bool)forceDisableFaceZoom;
- (bool)forceDisableMediaEncryption;
- (bool)forceDisableMediaPriority;
- (bool)forceDisableMediaQueue;
- (bool)forceDisableMediaStalled;
- (bool)forceDisableMessageEncryption;
- (bool)forceDisableProcessSpecificRequirements;
- (bool)forceDisableReporting;
- (bool)forceDisableSSRCCollisionDetection;
- (bool)forceDisableThermal;
- (bool)forceDisableVideoDegraded;
- (bool)forceDisableVideoRuleCell720;
- (bool)forceDisableVideoRuleWiFi1080;
- (bool)forceDynamicEffectsFramerate;
- (bool)forceEVSWideBand;
- (bool)forceEnableAudioMockInputPathForAppleTV;
- (bool)forceEnablePearlCamera;
- (int)forceEncodeFramerate;
- (int)forceEncodeHeight;
- (int)forceEncodeWidth;
- (bool)forceFECRepairStream;
- (int)forceFramerate;
- (bool)forceHWI;
- (bool)forceIPv6;
- (int)forceKeyFrameInterval;
- (bool)forceMirroredCapture;
- (bool)forceMultiwayHWI;
- (bool)forceMuteAtStart;
- (bool)forceOneToOneMode;
- (int)forceRecvVideoPayload;
- (int)forceRedMaxDelay;
- (int)forceRedNumPayloads;
- (bool)forceScreenHWI;
- (unsigned int)forceThermalLevelFramerate:(unsigned int)arg1;
- (bool)forceUseFloat;
- (bool)forceUseInternalRTPThreadingWithDefaultValue:(bool)arg1;
- (int)forceVideoPayload;
- (bool)forceVideoStreamDisableBitrateCap;
- (int)forceVideoStreamFramerate;
- (int)forceVideoStreamKeyFrameInterval;
- (bool)forceVideoStreamLowLatency;
- (int)forceVideoStreamPayload;
- (int)forceVideoStreamResolution;
- (int)forceVideoStreamRxMaxBitrate;
- (int)forceVideoStreamRxMinBitrate;
- (int)forceVideoStreamTxMaxBitrate;
- (int)forceVideoStreamTxMinBitrate;
- (unsigned int)forceVisibilityIndex;
- (bool)forceWiFiAssist;
- (bool)forceWiFiAssistOutOfBudget;
- (bool)forceWifiAssist;
- (bool)forceWifiAssistOutOfBudget;
- (id)init;
- (bool)isFECVersion2Enabled;
- (bool)isReceiverTestVerificationEnabled;
- (bool)isTransmitterTestVerificationEnabled;
- (int)localRATTypeOverride;
- (int)localWRMLinkType;
- (int)max2GRate;
- (unsigned int)maxActiveVideoDecoders;
- (unsigned int)maxActiveVideoEncoders;
- (bool)mediaQueueDumpEnabled;
- (unsigned int)minParticipantCountSendVoiceActiveOnly;
- (bool)momentsUseBestVideoRule;
- (bool)momentsUserPreferenceEnabled;
- (unsigned int)multiwayAudioNetworkBitrateCapCellular;
- (unsigned int)multiwayAudioNetworkBitrateCapWifi;
- (unsigned int)multiwayVideoNetworkBitrateCapCellular;
- (unsigned int)multiwayVideoNetworkBitrateCapWifi;
- (bool)offerAnetecCodecEnabled;
- (int)packetExpirationTime;
- (float)pauseHeartbeatInterval;
- (unsigned int)prominenceActiveAccumulationThreshold;
- (unsigned int)prominenceActiveProbabilityThreshold;
- (unsigned int)prominenceInactiveAccumulationThreshold;
- (unsigned int)prominenceInactiveProbabilityThreshold;
- (bool)rateControlAllowBurstyLossRampDown;
- (bool)rateControlAllowVideoStop;
- (int)rateControlBasebandSlowDownFactor;
- (bool)rateControlDumpEnabled;
- (int)rateControlForceRxCap;
- (int)rateControlForceRxRate;
- (int)rateControlForceTxCap;
- (int)rateControlForceTxRate;
- (bool)rateControlLogEnabled;
- (int)rateControlStatisticsQueueWaitTime;
- (int)rateControllerType;
- (int)redundancyControlForceVideoRedundancyPercentage;
- (oneway void)release;
- (double)remoteMediaStallTimeout;
- (id)retain;
- (unsigned long long)retainCount;
- (void)seperateString:(id)arg1;
- (bool)shouldDisplayVideoInfoLayer;
- (bool)shouldOverrideEffectsFramerate:(unsigned int*)arg1;
- (unsigned int)silenceLevelMovingAveragePeriod;
- (bool)supportsOneToOneMode;
- (bool)useCannedVideoPackets;
- (bool)useSBR;
- (bool)useVirtualCapture;
- (int)videoStreamRateControlAlgorithm;
- (bool)videoStreamRateControlDumpEnabled;
- (id)virtualHardware;

@end
