
@interface FBKDeviceDiagnosticsController : NSObject <FBKAttachmentManagerDelegate, FBKFilerArchiving> {
    id  __filesBeingAttachedCount;
    bool  _addedCurrentDeviceNeedsMatcherPredicateEvaluation;
    NSArray * _attachmentCollections;
    NSArray * _attachmentDescriptors;
    NSMutableSet * _attachmentsBeingAttached;
    NSMutableDictionary * _cachedDiffableIdentifiersTable;
    NSSet * _currentMatcherPredicates;
    NSSet * _deferredAttachmentCollections;
    <FBKDeviceDiagnosticsDelegate> * _delegate;
    id  _deviceDiagnosticsCombineObject;
    FBKDeviceManager * _deviceManager;
    <FBKFilerForm> * _filerForm;
    NSNumber * _filerFormID;
    long long  _filesBeingAttachedCount;
    id  _filesBeingCopiedCount;
    NSString * _formPlatform;
    NSSet * _ignoredMatchers;
    NSSet * _previousMatcherPredicates;
    long long  _removeDeviceMaxRetry;
    NSSet * _removedDevices;
    long long  _state;
}

@property (nonatomic, retain) id _filesBeingAttachedCount;
@property (nonatomic) bool addedCurrentDeviceNeedsMatcherPredicateEvaluation;
@property (nonatomic, retain) NSArray *attachmentCollections;
@property (nonatomic, retain) NSArray *attachmentDescriptors;
@property (nonatomic, retain) NSMutableSet *attachmentsBeingAttached;
@property (nonatomic, retain) NSMutableDictionary *cachedDiffableIdentifiersTable;
@property (nonatomic, readonly) _TtC12FeedbackCore37FBKDeviceDiagnosticsControllerCombine *combine;
@property (nonatomic, readonly) FBKAttachmentManager *currentDeviceAttachmentManager;
@property (nonatomic, readonly) DEDBugSession *currentDeviceBugSession;
@property (nonatomic, readonly) NSSet *currentMatcherPredicates;
@property (nonatomic, retain) NSSet *deferredAttachmentCollections;
@property (nonatomic) <FBKDeviceDiagnosticsDelegate> *delegate;
@property (nonatomic, retain) id deviceDiagnosticsCombineObject;
@property (nonatomic, retain) FBKDeviceManager *deviceManager;
@property (nonatomic, readonly) NSArray *devicesInPlay;
@property (nonatomic, retain) <FBKFilerForm> *filerForm;
@property (nonatomic, retain) NSNumber *filerFormID;
@property (nonatomic) long long filesBeingAttachedCount;
@property (nonatomic, retain) id filesBeingCopiedCount;
@property (nonatomic, readonly) NSString *formPlatform;
@property (nonatomic, readonly) bool hasAttachmentsForUpload;
@property (nonatomic, retain) NSSet *ignoredMatchers;
@property (nonatomic, retain) NSSet *previousMatcherPredicates;
@property (nonatomic) long long removeDeviceMaxRetry;
@property (nonatomic, retain) NSSet *removedDevices;
@property (nonatomic) long long state;

+ (id)currentDeviceAttachmentManagerWithDeviceAttachments:(id)arg1;
+ (id)currentDeviceBiased_MatcherPredicatesForDevice:(id)arg1 withGivenMatchers:(id)arg2;
+ (bool)device:(id)arg1 matchesAnyPredicate:(id)arg2 fromCollection:(id)arg3 formPlatform:(id)arg4;
+ (id)filteredMatcherPredicatesForMatchers:(id)arg1 ignoredMatcherPredicates:(id)arg2;
+ (id)matchersForDevice:(id)arg1 withGivenMatchers:(id)arg2 canMatchVisibleDevices:(bool)arg3 fromCollection:(id)arg4 formPlatform:(id)arg5;
+ (id)removeDuplicateMatcherPredicatesWithDevice:(id)arg1 matchers:(id)arg2;

- (void).cxx_destruct;
- (id)_filesBeingAttachedCount;
- (void)abortAllSessions;
- (void)addAttachmentWithItemProvider:(id)arg1;
- (void)addDevice:(id)arg1;
- (bool)addedCurrentDeviceNeedsMatcherPredicateEvaluation;
- (id)additionalDeviceCandidates;
- (id)attachmentCollections;
- (id)attachmentDescriptors;
- (void)attachmentManager:(id)arg1 didAddAttachment:(id)arg2 atIndex:(long long)arg3;
- (void)attachmentManager:(id)arg1 didFinishAttaching:(id)arg2 error:(id)arg3;
- (void)attachmentManager:(id)arg1 didRemoveAttachment:(id)arg2 atIndex:(long long)arg3;
- (void)attachmentManager:(id)arg1 didStartAttaching:(id)arg2;
- (void)attachmentManager:(id)arg1 didStartBugSessionsForDevice:(id)arg2 success:(bool)arg3;
- (void)attachmentManager:(id)arg1 didUpdateAttachment:(id)arg2 atIndex:(long long)arg3;
- (id)attachmentsBeingAttached;
- (id)attachmentsForDevice:(id)arg1;
- (id)cachedDiffableIdentifiersTable;
- (bool)canCancelAttachmentCollection:(id)arg1;
- (bool)canDeleteAttachment:(id)arg1;
- (bool)canRemoveDevice:(id)arg1;
- (id)combine;
- (void)commitAllFilesForForm:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)copyFileFrom:(id)arg1;
- (void)createCombineObjectIfNeeded;
- (id)currentDeviceAttachmentManager;
- (id)currentDeviceBugSession;
- (id)currentMatcherPredicates;
- (id)currentMatcherPredicates;
- (void)dealloc;
- (id)deferredAttachmentCollections;
- (id)delegate;
- (id)deviceDataForSubmission;
- (id)deviceDiagnosticsCombineObject;
- (bool)deviceHasAnyAttachmentsWithDevice:(id)arg1;
- (id)deviceManager;
- (id)devicesInPlay;
- (id)devicesMatching:(id)arg1 withConfiguredDevices:(id)arg2;
- (id)filerForm;
- (id)filerFormID;
- (long long)filesBeingAttachedCount;
- (id)filesBeingCopiedCount;
- (void)finishInitializationWithChosenDevices:(id)arg1 matcherPredicates:(id)arg2 pendingFileUrls:(id)arg3 pendingURLExtensions:(id)arg4;
- (void)finishInitializationWithChosenDevices:(id)arg1 matcherPredicates:(id)arg2 pendingFileUrls:(id)arg3 pendingURLExtensions:(id)arg4 shouldGetSessionStatus:(bool)arg5 shouldCheckForDeferredDiagnostics:(bool)arg6;
- (id)formPlatform;
- (void)gatherAllMissingRequirementsWithAnswers:(id)arg1;
- (void)gatherAttachment:(id)arg1 answers:(id)arg2;
- (id)generateSectionIdentifierGroupsWithDeviceSectionPrefix:(id)arg1 deferredDeviceSectionPrefix:(id)arg2;
- (id)generateSnapshotIdentifiersTrackingLastDevice:(bool)arg1;
- (bool)hasAnyAttachments;
- (bool)hasAttachmentsCollecting;
- (bool)hasAttachmentsForUpload;
- (bool)hasFilePromises;
- (bool)hasUnmetRequirementAttachments;
- (id)ignoredMatchers;
- (id)initWithDeviceManager:(id)arg1 delegate:(id)arg2 filerForm:(id)arg3 pendingFileUrls:(id)arg4 pendingURLExtensions:(id)arg5 draftDeviceIds:(id)arg6;
- (id)initWithDeviceManager:(id)arg1 delegate:(id)arg2 filerForm:(id)arg3 pendingFileUrls:(id)arg4 pendingURLExtensions:(id)arg5 draftDeviceIds:(id)arg6 attachmentDescriptors:(id)arg7;
- (id)maybeAttachmentWithIdentifier:(id)arg1;
- (id)maybeDeviceWithIdentifier:(id)arg1;
- (void)moveFileFrom:(id)arg1;
- (void)postLaunchAttachLocalFiles:(id)arg1;
- (id)previousMatcherPredicates;
- (void)reevaluateMatcherPredicates;
- (void)removeAllAttachments;
- (bool)removeAttachment:(id)arg1;
- (void)removeDevice:(id)arg1;
- (long long)removeDeviceMaxRetry;
- (id)removedDevices;
- (void)requestDeviceChoiceButDontBeAnnoyingWithGivenDeviceChoices:(id)arg1 matcherPredicates:(id)arg2 needsChoices:(id /* block */)arg3;
- (void)setAddedCurrentDeviceNeedsMatcherPredicateEvaluation:(bool)arg1;
- (void)setAttachmentCollections:(id)arg1;
- (void)setAttachmentDescriptors:(id)arg1;
- (void)setAttachmentsBeingAttached:(id)arg1;
- (void)setCachedDiffableIdentifiersTable:(id)arg1;
- (void)setDeferredAttachmentCollections:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDeviceDiagnosticsCombineObject:(id)arg1;
- (void)setDeviceManager:(id)arg1;
- (void)setFilerForm:(id)arg1;
- (void)setFilerFormID:(id)arg1;
- (void)setFilesBeingAttachedCount:(long long)arg1;
- (void)setFilesBeingCopiedCount:(id)arg1;
- (void)setIgnoredMatchers:(id)arg1;
- (void)setPreviousMatcherPredicates:(id)arg1;
- (void)setRemoveDeviceMaxRetry:(long long)arg1;
- (void)setRemovedDevices:(id)arg1;
- (void)setState:(long long)arg1;
- (void)set_filesBeingAttachedCount:(id)arg1;
- (long long)state;
- (id)trailingSwipeActionConfigurationWithAttachment:(id)arg1 fromViewController:(id)arg2;
- (id)trailingSwipeActionConfigurationWithAttachment:(id)arg1 orDevice:(id)arg2 fromViewController:(id)arg3;
- (id)trailingSwipeActionConfigurationWithDevice:(id)arg1 fromViewController:(id)arg2;
- (id)unreachableDevicesInPlay;
- (void)updateAttachmentCollectionObserver:(id)arg1 formResponse:(id)arg2;
- (void)updateFilesBeingCopiedCountCancellable;
- (void)updateStatePublisher;

@end
