
@interface AWDCFNetworkTransactionMetrics : PBCodable <NSCopying> {
    bool  _apsRelayAttempted;
    bool  _apsRelaySucceeded;
    NSString * _connectionUUID;
    struct { 
        unsigned int requestEnd : 1; 
        unsigned int requestStart : 1; 
        unsigned int responseEnd : 1; 
        unsigned int responseStart : 1; 
        unsigned int timestamp : 1; 
        unsigned int totalBytesExpectedToRead : 1; 
        unsigned int totalBytesExpectedToWrite : 1; 
        unsigned int totalBytesRead : 1; 
        unsigned int totalBytesWritten : 1; 
        unsigned int http3Status : 1; 
        unsigned int networkLoadType : 1; 
        unsigned int networkProtocolName : 1; 
        unsigned int apsRelayAttempted : 1; 
        unsigned int apsRelaySucceeded : 1; 
        unsigned int isRedirected : 1; 
        unsigned int reusedConnection : 1; 
    }  _has;
    int  _http3Status;
    bool  _isRedirected;
    int  _networkLoadType;
    int  _networkProtocolName;
    unsigned long long  _requestEnd;
    unsigned long long  _requestStart;
    unsigned long long  _responseEnd;
    unsigned long long  _responseStart;
    bool  _reusedConnection;
    unsigned long long  _timestamp;
    unsigned long long  _totalBytesExpectedToRead;
    unsigned long long  _totalBytesExpectedToWrite;
    unsigned long long  _totalBytesRead;
    unsigned long long  _totalBytesWritten;
}

@property (nonatomic) bool apsRelayAttempted;
@property (nonatomic) bool apsRelaySucceeded;
@property (nonatomic, retain) NSString *connectionUUID;
@property (nonatomic) bool hasApsRelayAttempted;
@property (nonatomic) bool hasApsRelaySucceeded;
@property (nonatomic, readonly) bool hasConnectionUUID;
@property (nonatomic) bool hasHttp3Status;
@property (nonatomic) bool hasIsRedirected;
@property (nonatomic) bool hasNetworkLoadType;
@property (nonatomic) bool hasNetworkProtocolName;
@property (nonatomic) bool hasRequestEnd;
@property (nonatomic) bool hasRequestStart;
@property (nonatomic) bool hasResponseEnd;
@property (nonatomic) bool hasResponseStart;
@property (nonatomic) bool hasReusedConnection;
@property (nonatomic) bool hasTimestamp;
@property (nonatomic) bool hasTotalBytesExpectedToRead;
@property (nonatomic) bool hasTotalBytesExpectedToWrite;
@property (nonatomic) bool hasTotalBytesRead;
@property (nonatomic) bool hasTotalBytesWritten;
@property (nonatomic) int http3Status;
@property (nonatomic) bool isRedirected;
@property (nonatomic) int networkLoadType;
@property (nonatomic) int networkProtocolName;
@property (nonatomic) unsigned long long requestEnd;
@property (nonatomic) unsigned long long requestStart;
@property (nonatomic) unsigned long long responseEnd;
@property (nonatomic) unsigned long long responseStart;
@property (nonatomic) bool reusedConnection;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) unsigned long long totalBytesExpectedToRead;
@property (nonatomic) unsigned long long totalBytesExpectedToWrite;
@property (nonatomic) unsigned long long totalBytesRead;
@property (nonatomic) unsigned long long totalBytesWritten;

- (int)StringAsHttp3Status:(id)arg1;
- (int)StringAsNetworkLoadType:(id)arg1;
- (int)StringAsNetworkProtocolName:(id)arg1;
- (bool)apsRelayAttempted;
- (bool)apsRelaySucceeded;
- (id)connectionUUID;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasApsRelayAttempted;
- (bool)hasApsRelaySucceeded;
- (bool)hasConnectionUUID;
- (bool)hasHttp3Status;
- (bool)hasIsRedirected;
- (bool)hasNetworkLoadType;
- (bool)hasNetworkProtocolName;
- (bool)hasRequestEnd;
- (bool)hasRequestStart;
- (bool)hasResponseEnd;
- (bool)hasResponseStart;
- (bool)hasReusedConnection;
- (bool)hasTimestamp;
- (bool)hasTotalBytesExpectedToRead;
- (bool)hasTotalBytesExpectedToWrite;
- (bool)hasTotalBytesRead;
- (bool)hasTotalBytesWritten;
- (unsigned long long)hash;
- (int)http3Status;
- (id)http3StatusAsString:(int)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isRedirected;
- (void)mergeFrom:(id)arg1;
- (int)networkLoadType;
- (id)networkLoadTypeAsString:(int)arg1;
- (int)networkProtocolName;
- (id)networkProtocolNameAsString:(int)arg1;
- (bool)readFrom:(id)arg1;
- (unsigned long long)requestEnd;
- (unsigned long long)requestStart;
- (unsigned long long)responseEnd;
- (unsigned long long)responseStart;
- (bool)reusedConnection;
- (void)setApsRelayAttempted:(bool)arg1;
- (void)setApsRelaySucceeded:(bool)arg1;
- (void)setConnectionUUID:(id)arg1;
- (void)setHasApsRelayAttempted:(bool)arg1;
- (void)setHasApsRelaySucceeded:(bool)arg1;
- (void)setHasHttp3Status:(bool)arg1;
- (void)setHasIsRedirected:(bool)arg1;
- (void)setHasNetworkLoadType:(bool)arg1;
- (void)setHasNetworkProtocolName:(bool)arg1;
- (void)setHasRequestEnd:(bool)arg1;
- (void)setHasRequestStart:(bool)arg1;
- (void)setHasResponseEnd:(bool)arg1;
- (void)setHasResponseStart:(bool)arg1;
- (void)setHasReusedConnection:(bool)arg1;
- (void)setHasTimestamp:(bool)arg1;
- (void)setHasTotalBytesExpectedToRead:(bool)arg1;
- (void)setHasTotalBytesExpectedToWrite:(bool)arg1;
- (void)setHasTotalBytesRead:(bool)arg1;
- (void)setHasTotalBytesWritten:(bool)arg1;
- (void)setHttp3Status:(int)arg1;
- (void)setIsRedirected:(bool)arg1;
- (void)setNetworkLoadType:(int)arg1;
- (void)setNetworkProtocolName:(int)arg1;
- (void)setRequestEnd:(unsigned long long)arg1;
- (void)setRequestStart:(unsigned long long)arg1;
- (void)setResponseEnd:(unsigned long long)arg1;
- (void)setResponseStart:(unsigned long long)arg1;
- (void)setReusedConnection:(bool)arg1;
- (void)setTimestamp:(unsigned long long)arg1;
- (void)setTotalBytesExpectedToRead:(unsigned long long)arg1;
- (void)setTotalBytesExpectedToWrite:(unsigned long long)arg1;
- (void)setTotalBytesRead:(unsigned long long)arg1;
- (void)setTotalBytesWritten:(unsigned long long)arg1;
- (unsigned long long)timestamp;
- (unsigned long long)totalBytesExpectedToRead;
- (unsigned long long)totalBytesExpectedToWrite;
- (unsigned long long)totalBytesRead;
- (unsigned long long)totalBytesWritten;
- (void)writeTo:(id)arg1;

@end
