
@interface _MKFAccessory : _MKFModel <HMDNSManagedObjectBackingStoreModelObjectRepresentable, MKFAccessory, MKFAccessoryPrivateExtensions>

@property (nonatomic, copy) NSNumber *accessoryCategory;
@property (nonatomic, readonly, retain) NSArray *actionMediaPlaybacks;
@property (nonatomic, retain) NSSet *actionMediaPlaybacks_;
@property (nonatomic, readonly, retain) NSArray *analysisEventBulletinRegistrations;
@property (nonatomic, retain) NSSet *analysisEventBulletinRegistrations_;
@property (nonatomic, retain) _MKFApplicationData *applicationData;
@property (nonatomic, retain) <MKFApplicationData> *applicationData;
@property (nonatomic, retain) NSArray *appliedFirewallWANRules;
@property (nonatomic, readonly, retain) NSArray *cameraAccessModeBulletinRegistrations;
@property (nonatomic, retain) NSSet *cameraAccessModeBulletinRegistrations_;
@property (nonatomic, readonly, retain) NSArray *cameraReachabilityBulletinRegistrations;
@property (nonatomic, retain) NSSet *cameraReachabilityBulletinRegistrations_;
@property (nonatomic, readonly, retain) NSArray *cameraSignificantEventBulletinRegistrations;
@property (nonatomic, retain) NSSet *cameraSignificantEventBulletinRegistrations_;
@property (nonatomic, copy) NSString *configurationAppIdentifier;
@property (nonatomic, copy) NSString *configuredName;
@property (nonatomic, copy) NSNumber *currentNetworkProtectionMode;
@property (nonatomic, readonly, copy) MKFAccessoryDatabaseID *databaseID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSString *firmwareVersion;
@property (nonatomic, copy) NSUUID *groupIdentifier;
@property (nonatomic, copy) NSString *groupName;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSUUID *hmd_modelID;
@property (nonatomic, readonly, copy) NSUUID *hmd_parentModelID;
@property (nonatomic, retain) _MKFHome *home;
@property (nonatomic, readonly, retain) <MKFHome> *home;
@property (nonatomic, retain) _MKFAccessory *hostAccessory;
@property (nonatomic, retain) <MKFAccessory> *hostAccessory;
@property (nonatomic, readonly, retain) NSArray *hostedAccessories;
@property (nonatomic, retain) NSSet *hostedAccessories_;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSNumber *initialCategoryIdentifier;
@property (nonatomic, copy) NSString *initialManufacturer;
@property (nonatomic, copy) NSString *initialModel;
@property (nonatomic, copy) NSNumber *lastNetworkAccessViolationOccurrenceSince1970;
@property (nonatomic, copy) NSNumber *lastNetworkAccessViolationResetSince1970;
@property (nonatomic, copy) NSDate *lastSeenDate;
@property (nonatomic, copy) NSNumber *lowBattery;
@property (nonatomic, copy) NSString *manufacturer;
@property (nonatomic, readonly, retain) NSArray *mediaPropertyNotificationRegistrations;
@property (nonatomic, retain) NSSet *mediaPropertyNotificationRegistrations_;
@property (nonatomic, copy) NSString *model;
@property (nonatomic, copy) NSUUID *modelID;
@property (nonatomic, readonly, copy) NSUUID *modelID;
@property (nonatomic, copy) NSNumber *networkClientIdentifier;
@property (nonatomic, copy) NSNumber *networkClientLAN;
@property (nonatomic, copy) NSString *networkClientProfileFingerprint;
@property (nonatomic, copy) NSString *networkRouterUUID;
@property (nonatomic, copy) NSString *pendingConfigurationIdentifier;
@property (nonatomic, copy) NSString *primaryProfileVersion;
@property (nonatomic, copy) NSString *productData;
@property (nonatomic, copy) NSString *providedName;
@property (nonatomic, retain) _MKFRoom *room;
@property (nonatomic, retain) <MKFRoom> *room;
@property (nonatomic, copy) NSString *serialNumber;
@property (nonatomic, retain) _MKFSoftwareUpdate *softwareUpdate;
@property (nonatomic, retain) <MKFSoftwareUpdate> *softwareUpdate;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSNumber *suspendCapable;
@property (nonatomic, readonly, retain) NSArray *usersWithListeningHistoryEnabled;
@property (nonatomic, retain) NSSet *usersWithListeningHistoryEnabled_;
@property (nonatomic, readonly, retain) NSArray *usersWithMediaContentProfileEnabled;
@property (nonatomic, retain) NSSet *usersWithMediaContentProfileEnabled_;
@property (nonatomic, readonly, retain) NSArray *usersWithPersonalRequestsEnabled;
@property (nonatomic, retain) NSSet *usersWithPersonalRequestsEnabled_;
@property (nonatomic, copy) NSNumber *wiFiCredentialType;
@property (nonatomic, retain) NSData *wiFiUniquePreSharedKey;
@property (nonatomic, copy) NSDate *writerTimestamp;

+ (id)backingModelProtocol;
+ (Class)cd_modelClass;
+ (id)fetchRequest;
+ (id)homeRelation;
+ (id)modelIDForParentRelationshipTo:(id)arg1;

- (id)actionMediaPlaybacks;
- (void)addHostedAccessoriesObject:(id)arg1;
- (void)addUsersWithListeningHistoryEnabledObject:(id)arg1;
- (void)addUsersWithMediaContentProfileEnabledObject:(id)arg1;
- (void)addUsersWithPersonalRequestsEnabledObject:(id)arg1;
- (id)analysisEventBulletinRegistrations;
- (id)cameraAccessModeBulletinRegistrations;
- (id)cameraReachabilityBulletinRegistrations;
- (id)cameraSignificantEventBulletinRegistrations;
- (id)castIfAccessory;
- (id)databaseID;
- (id)hostedAccessories;
- (id)materializeOrCreateApplicationDataRelation:(bool*)arg1;
- (id)materializeOrCreateSoftwareUpdateRelation:(bool*)arg1;
- (id)mediaPropertyNotificationRegistrations;
- (void)removeHostedAccessoriesObject:(id)arg1;
- (void)removeUsersWithListeningHistoryEnabledObject:(id)arg1;
- (void)removeUsersWithMediaContentProfileEnabledObject:(id)arg1;
- (void)removeUsersWithPersonalRequestsEnabledObject:(id)arg1;
- (id)usersWithListeningHistoryEnabled;
- (id)usersWithMediaContentProfileEnabled;
- (id)usersWithPersonalRequestsEnabled;

@end
