
@interface MPMediaLibraryArtwork : NSObject {
    ML3Artwork * _artwork;
    MPMediaLibraryArtworkRequest * _artworkRequest;
    NSArray * _autogeneratedSizes;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _stateLock;
    NSArray * _validSizes;
}

@property (nonatomic, retain) ML3Artwork *artwork;
@property (nonatomic) MPMediaLibraryArtworkRequest *artworkRequest;
@property (nonatomic, readonly) NSArray *autogeneratedSizes;
@property (nonatomic, copy) NSDictionary *effectsMetadata;
@property (nonatomic, readonly, copy) NSURL *originalFileURL;
@property (nonatomic, readonly) struct os_unfair_lock_s { unsigned int x1; } stateLock;
@property (nonatomic, readonly) NSArray *validSizes;

+ (bool)artworkExistsForRequest:(id)arg1;
+ (id)availableArtworkWithRequest:(id)arg1;
+ (void)cancelFetchingArtworkForRequest:(id)arg1;
+ (void)fetchArtworkForRequest:(id)arg1 completionHandler:(id /* block */)arg2;
+ (void)fetchArtworkInfoForRequest:(id)arg1 completionHandler:(id /* block */)arg2;
+ (bool)fetchableArtworkExistsForRequest:(id)arg1;
+ (bool)needsToFetchArtworkForRequest:(id)arg1;

- (void).cxx_destruct;
- (id)artwork;
- (id)artworkRequest;
- (id)autogeneratedSizes;
- (id)effectsMetadata;
- (unsigned long long)hash;
- (id)imageFileURLForEffect:(id)arg1;
- (id)imageFileURLForSize:(struct CGSize { double x1; double x2; })arg1;
- (id)init;
- (bool)isEqual:(id)arg1;
- (id)originalFileURL;
- (void)setArtwork:(id)arg1;
- (void)setArtworkRequest:(id)arg1;
- (void)setEffectsMetadata:(id)arg1;
- (struct os_unfair_lock_s { unsigned int x1; })stateLock;
- (id)validSizes;

@end
