
@interface MPNowPlayingSession : NSObject {
    bool  _active;
    id  _adTimeRangesEndObserverToken;
    id  _adTimeRangesStartObserverToken;
    AVAudioSession * _audioSession;
    bool  _automaticallyPublishesNowPlayingInfo;
    NSDictionary * _baseNowPlayingInfo;
    bool  _canBecomeActive;
    id  _creditsTimeObserverToken;
    NSArray * _currentAdTimeRanges;
    double  _currentAssetNetCreditsStartTime;
    double  _currentAssetNetDuration;
    <MPNowPlayingSessionDelegate> * _delegate;
    bool  _invalidated;
    NSSet * _mxSessionIDs;
    MPNowPlayingInfoCenter * _nowPlayingInfoCenter;
    bool  _pictureInPictureEnabled;
    MRPlayerPath * _playerPath;
    NSMutableSet * _playerSet;
    NSObject<OS_dispatch_queue> * _privateQueue;
    MPRemoteCommandCenter * _remoteCommandCenter;
    NSString * _routingContextID;
}

@property (getter=isActive, nonatomic, readonly) bool active;
@property (nonatomic, retain) id adTimeRangesEndObserverToken;
@property (nonatomic, retain) id adTimeRangesStartObserverToken;
@property (nonatomic, readonly) AVAudioSession *audioSession;
@property (nonatomic, readonly) unsigned int audioSessionID;
@property (nonatomic) bool automaticallyPublishesNowPlayingInfo;
@property (nonatomic, retain) NSDictionary *baseNowPlayingInfo;
@property (nonatomic) bool canBecomeActive;
@property (nonatomic, retain) id creditsTimeObserverToken;
@property (nonatomic, retain) NSArray *currentAdTimeRanges;
@property (nonatomic) double currentAssetNetCreditsStartTime;
@property (nonatomic) double currentAssetNetDuration;
@property (nonatomic) <MPNowPlayingSessionDelegate> *delegate;
@property (nonatomic, readonly) NSSet *mxSessionIDs;
@property (nonatomic, retain) MPNowPlayingInfoCenter *nowPlayingInfoCenter;
@property (getter=isPictureInPictureEnabled, nonatomic) bool pictureInPictureEnabled;
@property (nonatomic, readonly) MRPlayerPath *playerPath;
@property (nonatomic, retain) NSMutableSet *playerSet;
@property (nonatomic, readonly) NSArray *players;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *privateQueue;
@property (nonatomic, readonly) MPRemoteCommandCenter *remoteCommandCenter;
@property (nonatomic, readonly) NSString *routingContextID;

+ (id)nowPlayingSessionForPlayerID:(id)arg1;
+ (id)nowPlayingSessionForPlayerPath:(id)arg1;

- (void).cxx_destruct;
- (void)_playerItemNowPlayingInfoDidChange:(id)arg1;
- (void)activePlayerDidChangeNotification:(id)arg1;
- (id)adTimeRangesEndObserverToken;
- (id)adTimeRangesStartObserverToken;
- (void)addPlayer:(id)arg1;
- (void)addPlayerItemObservers:(id)arg1;
- (void)addPlayerObservers:(id)arg1;
- (id)audioSession;
- (unsigned int)audioSessionID;
- (bool)automaticallyPublishesNowPlayingInfo;
- (id)baseNowPlayingInfo;
- (void)becomeActiveIfPossibleWithCompletion:(id /* block */)arg1;
- (bool)canBecomeActive;
- (id)creditsTimeObserverToken;
- (id)currentAdTimeRanges;
- (double)currentAssetNetCreditsStartTime;
- (double)currentAssetNetDuration;
- (void)dealloc;
- (id)delegate;
- (float)effectivePlaybackRateWithPlayer:(id)arg1;
- (void)endpointWithCompletion:(id /* block */)arg1;
- (void)extractNowPlayingInfoFromPlayersAndUpdateAdRanges;
- (bool)hasInvalidAdTimeRange:(id)arg1 totalDuration:(id)arg2;
- (id)initWithPlayerPath:(id)arg1 routingContextID:(id)arg2;
- (id)initWithPlayers:(id)arg1;
- (void)invalidate;
- (bool)isActive;
- (bool)isPictureInPictureEnabled;
- (id)mediaExperienceIDs;
- (id)mxSessionIDKeyPath;
- (id)mxSessionIDs;
- (struct { long long x1; int x2; unsigned int x3; long long x4; })netTimeForGrossTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1;
- (id)nowPlayingInfoCenter;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)playerItemDidPlayToEnd:(id)arg1;
- (void)playerItemPlaybackStalled:(id)arg1;
- (void)playerItemTimeJumped:(id)arg1;
- (id)playerPath;
- (void)playerPictureInPictureEnabledDidChangeNotification:(id)arg1;
- (void)playerRateDidChange:(id)arg1;
- (id)playerSet;
- (id)players;
- (id)privateQueue;
- (id)remoteCommandCenter;
- (void)removePlayer:(id)arg1;
- (void)removePlayerItemObservers:(id)arg1;
- (void)removePlayerObservers:(id)arg1;
- (id)routingContextID;
- (void)setActive:(bool)arg1;
- (void)setAdTimeRangesEndObserverToken:(id)arg1;
- (void)setAdTimeRangesStartObserverToken:(id)arg1;
- (void)setAutomaticallyPublishesNowPlayingInfo:(bool)arg1;
- (void)setBaseNowPlayingInfo:(id)arg1;
- (void)setCanBecomeActive:(bool)arg1;
- (void)setCreditsTimeObserverToken:(id)arg1;
- (void)setCurrentAdTimeRanges:(id)arg1;
- (void)setCurrentAssetNetCreditsStartTime:(double)arg1;
- (void)setCurrentAssetNetDuration:(double)arg1;
- (void)setDelegate:(id)arg1;
- (void)setNowPlayingInfoCenter:(id)arg1;
- (void)setPictureInPictureEnabled:(bool)arg1;
- (void)setPlayerSet:(id)arg1;
- (void)setPrivateQueue:(id)arg1;
- (void)updateAudioSession:(id)arg1;
- (void)updateMediaExperienceIDs;
- (void)updateNowPlayingInfo;

@end
