
@interface MPPlaybackUserDefaults : NSObject <MFPlaybackDefaults> {
    NSObject<OS_dispatch_queue> * _accountsQueue;
    NSUserDefaults * _airplayUserDefaults;
    NSUserDefaults * _iPodUserDefaults;
    NSUserDefaults * _mediaPlaybackCoreUserDefaults;
    struct { 
        int mobileiPodPrefsChanged; 
        int mobileiPodPlaybackPrefsChangedAllowCellularData; 
        int videoPrefsChanged; 
        int airplayPrefsChanged; 
    }  _notifyTokens;
    long long  _preferredVideoDownloadResolution;
    NSUserDefaults * _videoUserDefaults;
}

@property (nonatomic, readonly) double HomePodPFSQForcedLeaseRenewThreshold;
@property (nonatomic, readonly) double activationDelay;
@property (nonatomic, readonly) bool allowScreenRecording;
@property (nonatomic, readonly) bool allowsHighQualityMusicStreamingOnCellular;
@property (nonatomic, readonly) bool archiveSessionArtwork;
@property (nonatomic, readonly) long long artworkCacheLimit;
@property (nonatomic, readonly) double assetURLExpirationDuration;
@property (nonatomic, readonly) unsigned long long audioAnalysisRefreshRate;
@property (nonatomic, readonly) float audioTapTimeOutRatioForFailureDetection;
@property (nonatomic) double crossFadeDuration;
@property (getter=isCrossFadeEnabled, nonatomic) bool crossFadeEnabled;
@property (nonatomic, readonly) float defaultVocalLevel;
@property (nonatomic, readonly, copy) NSNumber *delayAssetLoadDuration;
@property (nonatomic, readonly, copy) NSNumber *delayQueueLoadDuration;
@property (getter=isDevicePrivateListeningEnabled, nonatomic, readonly, copy) NSNumber *devicePrivateListeningEnabled;
@property (nonatomic, readonly) bool disableAssetCaching;
@property (nonatomic, readonly) bool disableAudioAnalysis;
@property (nonatomic, readonly) bool disableAudioProcessing;
@property (nonatomic, readonly) bool disableHLSAssetCaching;
@property (nonatomic, readonly) bool disableMiniSINF;
@property (nonatomic, readonly) bool disablePeriodicStateRestore;
@property (nonatomic, readonly) bool disableQHO;
@property (getter=isProcessTapEnabled, nonatomic, readonly) bool enableProcessTap;
@property (nonatomic, readonly) long long exportableArtworkCacheLimit;
@property (getter=isFocusModePrivateListeningEnabled, nonatomic, copy) NSNumber *focusModePrivateListeningEnabled;
@property (nonatomic, readonly) bool forceDisableUpNext;
@property (nonatomic, readonly) bool forceLibrarySupplementalContexts;
@property (nonatomic, readonly) bool forceMusicResolution;
@property (nonatomic, readonly) bool forceMusicStreaming;
@property (nonatomic, readonly, copy) NSNumber *forcedIntentDestination;
@property (nonatomic, readonly) long long forcedMusicResolution;
@property (nonatomic, readonly) double forwardBufferDuration;
@property (nonatomic, readonly) bool ignoreDisableUpNext;
@property (nonatomic, readonly) bool includeContentItemDebugFields;
@property (nonatomic, readonly) long long maximumQueueHandOffSize;
@property (nonatomic, readonly) float minVocalLevel;
@property (nonatomic, readonly) MPPlaybackEQSetting *musicEQSetting;
@property (nonatomic) long long musicRepeatType;
@property (nonatomic) long long musicShuffleType;
@property (nonatomic, readonly) double playbackAuthorizationTokenHalfLifeDuration;
@property (nonatomic) float playbackRate;
@property (nonatomic) long long preferredMusicDownloadResolution;
@property (nonatomic) long long preferredMusicHighBandwidthResolution;
@property (nonatomic) long long preferredMusicLowBandwidthResolution;
@property (nonatomic, readonly) long long preferredVideoDownloadResolution;
@property (nonatomic, readonly) long long preferredVideoHighBandwidthResolution;
@property (nonatomic, readonly) long long preferredVideoLowBandwidthResolution;
@property (nonatomic) bool prefersSpatialAudio;
@property (nonatomic) bool prefersSpatialDownloads;
@property (nonatomic, readonly) bool prerollEnabled;
@property (getter=isPrivateListeningEnabled, nonatomic, copy) NSNumber *privateListeningEnabled;
@property (nonatomic, readonly) NSNumber *progressiveDownloadAssetRatio;
@property (nonatomic, readonly) bool shouldBypassVocalAttenuationDenoising;
@property (nonatomic, readonly) bool shouldBypassVocalAttenuationSupportFlag;
@property (nonatomic, readonly) bool shouldPreroll;
@property (nonatomic, readonly) bool shouldPurgeSideLoadedVocalAttenuationModels;
@property (nonatomic, readonly) bool shouldRecordVocalAttenuationStatistics;
@property (nonatomic, readonly) bool shouldSkipNextStateRestoration;
@property (nonatomic, readonly) bool shouldUseRemoteVocalAttenuationModel;
@property (nonatomic, readonly) bool shouldUseSideLoadedVocalAttenuationModel;
@property (nonatomic, readonly) bool showDebugUI;
@property (nonatomic) bool showLosslessAudio;
@property (nonatomic) bool soundCheckEnabled;
@property (nonatomic) long long spatialAudioPreference;
@property (nonatomic, readonly) bool speakerRouteEnabled;
@property (nonatomic, readonly) double unloadingPlaybackAssetsOnIdleDuration;
@property (nonatomic, readonly) double vocalAttenuationGracePeriodAfterPause;
@property (nonatomic, readonly) bool vocalAttenuationLogInputAndOuputRMSValues;
@property (nonatomic, readonly, copy) NSString *vocalAttenuationStatisticsName;

// Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer

+ (id)standardUserDefaults;

- (void).cxx_destruct;
- (double)HomePodPFSQForcedLeaseRenewThreshold;
- (void)_accountStoreChangedNotification:(id)arg1;
- (id)_init;
- (void)_loadAccountProperties;
- (void)_migrateUserDefaults;
- (double)activationDelay;
- (bool)allowScreenRecording;
- (bool)allowsHighQualityMusicStreamingOnCellular;
- (bool)archiveSessionArtwork;
- (long long)artworkCacheLimit;
- (double)assetURLExpirationDuration;
- (unsigned long long)audioAnalysisRefreshRate;
- (float)audioTapTimeOutRatioForFailureDetection;
- (bool)autoPlayEnabledForUserIdentity:(id)arg1;
- (void)clearShouldSkipNextStateRestoration;
- (double)crossFadeDuration;
- (void)dealloc;
- (float)defaultVocalLevel;
- (id)delayAssetLoadDuration;
- (id)delayQueueLoadDuration;
- (bool)disableAssetCaching;
- (bool)disableAudioAnalysis;
- (bool)disableAudioProcessing;
- (bool)disableHLSAssetCaching;
- (bool)disableMiniSINF;
- (bool)disablePeriodicStateRestore;
- (bool)disableQHO;
- (long long)exportableArtworkCacheLimit;
- (bool)forceDisableUpNext;
- (bool)forceLibrarySupplementalContexts;
- (bool)forceMusicResolution;
- (bool)forceMusicStreaming;
- (id)forcedIntentDestination;
- (long long)forcedMusicResolution;
- (double)forwardBufferDuration;
- (bool)ignoreDisableUpNext;
- (bool)includeContentItemDebugFields;
- (bool)isCrossFadeEnabled;
- (id)isDevicePrivateListeningEnabled;
- (id)isFocusModePrivateListeningEnabled;
- (id)isPrivateListeningEnabled;
- (bool)isProcessTapEnabled;
- (long long)maximumQueueHandOffSize;
- (float)minVocalLevel;
- (id)musicEQSetting;
- (long long)musicRepeatType;
- (long long)musicShuffleType;
- (double)playbackAuthorizationTokenHalfLifeDuration;
- (float)playbackRate;
- (long long)preferredMusicDownloadResolution;
- (long long)preferredMusicHighBandwidthResolution;
- (long long)preferredMusicLowBandwidthResolution;
- (long long)preferredVideoDownloadResolution;
- (long long)preferredVideoHighBandwidthResolution;
- (long long)preferredVideoLowBandwidthResolution;
- (bool)prefersSpatialAudio;
- (bool)prefersSpatialDownloads;
- (bool)prerollEnabled;
- (id)progressiveDownloadAssetRatio;
- (void)resetAllInternalSettings;
- (void)setAutoPlayEnabled:(bool)arg1 forUserIdentity:(id)arg2;
- (void)setCrossFadeDuration:(double)arg1;
- (void)setCrossFadeEnabled:(bool)arg1;
- (void)setFocusModePrivateListeningEnabled:(id)arg1;
- (void)setMusicRepeatType:(long long)arg1;
- (void)setMusicShuffleType:(long long)arg1;
- (void)setPlaybackAuthorizationTokenHalfLifeDuration:(double)arg1;
- (void)setPlaybackRate:(float)arg1;
- (void)setPreferredMusicDownloadResolution:(long long)arg1;
- (void)setPreferredMusicHighBandwidthResolution:(long long)arg1;
- (void)setPreferredMusicLowBandwidthResolution:(long long)arg1;
- (void)setPrefersSpatialAudio:(bool)arg1;
- (void)setPrefersSpatialDownloads:(bool)arg1;
- (void)setPrivateListeningEnabled:(id)arg1;
- (void)setShowLosslessAudio:(bool)arg1;
- (void)setSoundCheckEnabled:(bool)arg1;
- (void)setSpatialAudioPreference:(long long)arg1;
- (bool)shouldBypassVocalAttenuationDenoising;
- (bool)shouldBypassVocalAttenuationSupportFlag;
- (bool)shouldPurgeSideLoadedVocalAttenuationModels;
- (bool)shouldRecordVocalAttenuationStatistics;
- (bool)shouldSkipNextStateRestoration;
- (bool)shouldUseRemoteVocalAttenuationModel;
- (bool)shouldUseSideLoadedVocalAttenuationModel;
- (bool)showDebugUI;
- (bool)showLosslessAudio;
- (bool)soundCheckEnabled;
- (long long)spatialAudioPreference;
- (bool)speakerRouteEnabled;
- (double)unloadingPlaybackAssetsOnIdleDuration;
- (double)vocalAttenuationGracePeriodAfterPause;
- (bool)vocalAttenuationLogInputAndOuputRMSValues;
- (id)vocalAttenuationStatisticsName;

// Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore

- (bool)shouldPreroll;

@end
