
@interface PPTopicQuery : NSObject <NSCopying, NSSecureCoding> {
    double  _decayRate;
    unsigned long long  _deviceFilter;
    bool  _excludeWithoutSentiment;
    NSSet * _excludingAlgorithms;
    NSSet * _excludingSourceBundleIds;
    bool  _filterByRelevanceDate;
    NSDate * _fromDate;
    unsigned long long  _limit;
    NSSet * _matchingAlgorithms;
    NSString * _matchingContactHandle;
    NSSet * _matchingDocumentIds;
    NSSet * _matchingGroupIds;
    NSSet * _matchingMappedTopicIds;
    NSSet * _matchingSourceBundleIds;
    NSSet * _matchingTopicIds;
    NSString * _matchingTopicTrie;
    unsigned long long  _minimumComponentCount;
    bool  _orderByIdentifier;
    bool  _removeNearDuplicates;
    bool  _scoreWithBiases;
    bool  _scoreWithCalibration;
    bool  _scoreWithStrictFiltering;
    NSDate * _scoringDate;
    NSDate * _toDate;
}

@property (nonatomic) double decayRate;
@property (nonatomic) unsigned long long deviceFilter;
@property (nonatomic) bool excludeWithoutSentiment;
@property (nonatomic, retain) NSSet *excludingAlgorithms;
@property (nonatomic, retain) NSSet *excludingSourceBundleIds;
@property (nonatomic) bool filterByRelevanceDate;
@property (nonatomic, retain) NSDate *fromDate;
@property (nonatomic) unsigned long long limit;
@property (nonatomic, retain) NSSet *matchingAlgorithms;
@property (nonatomic, retain) NSString *matchingContactHandle;
@property (nonatomic, retain) NSSet *matchingDocumentIds;
@property (nonatomic, retain) NSSet *matchingGroupIds;
@property (nonatomic, retain) NSSet *matchingMappedTopicIds;
@property (nonatomic, retain) NSSet *matchingSourceBundleIds;
@property (nonatomic, retain) NSSet *matchingTopicIds;
@property (nonatomic, retain) NSString *matchingTopicTrie;
@property (nonatomic) unsigned long long minimumComponentCount;
@property (nonatomic) bool orderByIdentifier;
@property (nonatomic) bool overrideDecayRate;
@property (nonatomic) bool removeNearDuplicates;
@property (nonatomic) bool scoreWithBiases;
@property (nonatomic) bool scoreWithCalibration;
@property (nonatomic) bool scoreWithStrictFiltering;
@property (nonatomic, retain) NSDate *scoringDate;
@property (nonatomic, retain) NSDate *toDate;

+ (id)_algorithmsDescription:(id)arg1;
+ (id)queryForCSSearchableItem:(id)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)customizedDescription;
- (double)decayRate;
- (id)description;
- (unsigned long long)deviceFilter;
- (void)encodeWithCoder:(id)arg1;
- (bool)excludeWithoutSentiment;
- (id)excludingAlgorithms;
- (id)excludingSourceBundleIds;
- (bool)filterByRelevanceDate;
- (id)fromDate;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToTopicQuery:(id)arg1;
- (unsigned long long)limit;
- (id)matchingAlgorithms;
- (id)matchingContactHandle;
- (id)matchingDocumentIds;
- (id)matchingGroupIds;
- (id)matchingMappedTopicIds;
- (id)matchingSourceBundleIds;
- (id)matchingTopicIds;
- (id)matchingTopicTrie;
- (unsigned long long)minimumComponentCount;
- (bool)orderByIdentifier;
- (bool)overrideDecayRate;
- (bool)removeNearDuplicates;
- (bool)scoreWithBiases;
- (bool)scoreWithCalibration;
- (bool)scoreWithStrictFiltering;
- (id)scoringDate;
- (void)setDecayRate:(double)arg1;
- (void)setDeviceFilter:(unsigned long long)arg1;
- (void)setExcludeWithoutSentiment:(bool)arg1;
- (void)setExcludingAlgorithms:(id)arg1;
- (void)setExcludingSourceBundleIds:(id)arg1;
- (void)setFilterByRelevanceDate:(bool)arg1;
- (void)setFromDate:(id)arg1;
- (void)setLimit:(unsigned long long)arg1;
- (void)setMatchingAlgorithms:(id)arg1;
- (void)setMatchingContactHandle:(id)arg1;
- (void)setMatchingDocumentIds:(id)arg1;
- (void)setMatchingGroupIds:(id)arg1;
- (void)setMatchingMappedTopicIds:(id)arg1;
- (void)setMatchingSourceBundleIds:(id)arg1;
- (void)setMatchingTopicIds:(id)arg1;
- (void)setMatchingTopicTrie:(id)arg1;
- (void)setMinimumComponentCount:(unsigned long long)arg1;
- (void)setOrderByIdentifier:(bool)arg1;
- (void)setOverrideDecayRate:(bool)arg1;
- (void)setRemoveNearDuplicates:(bool)arg1;
- (void)setScoreWithBiases:(bool)arg1;
- (void)setScoreWithCalibration:(bool)arg1;
- (void)setScoreWithStrictFiltering:(bool)arg1;
- (void)setScoringDate:(id)arg1;
- (void)setToDate:(id)arg1;
- (id)toDate;

@end
