
@interface SMSafetyMonitorManager : NSObject <SMEligibilityProtocol, SMFrameworkProtocol, SMInitiatorCacheProtocol, SMInitiatorDestinationBoundSessionProtocol, SMInitiatorProtocol, SMInitiatorSafetyCacheMonitoringProtocol, SMInitiatorSessionConfigurationProtocol, SMInitiatorSessionMonitorProtocol, SMMadridMessengerProtocol, SMReceiverMonitorProtocol, SMReceiverProtocol, SMSessionStoreProtocol, SMSuggestionsProtocol, SMSuggestionsStoreProtocol, SMUserNotificationProtocol> {
    SMHeartbeatTimer * _heartbeatTimer;
    id /* block */  _initiatorSafetyCacheHandler;
    NSObject<OS_dispatch_queue> * _queue;
    id /* block */  _receiverSafetyCacheHandler;
    id /* block */  _receiverSessionStatusHandler;
    NSString * _restorationIdentifier;
    id /* block */  _sessionStateHandler;
    NSXPCConnection * _xpcConnection;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SMHeartbeatTimer *heartbeatTimer;
@property (nonatomic, copy) id /* block */ initiatorSafetyCacheHandler;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;
@property (nonatomic, copy) id /* block */ receiverSafetyCacheHandler;
@property (nonatomic, copy) id /* block */ receiverSessionStatusHandler;
@property (nonatomic, retain) NSString *restorationIdentifier;
@property (nonatomic, copy) id /* block */ sessionStateHandler;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSXPCConnection *xpcConnection;

+ (id)defaultManager;

- (void).cxx_destruct;
- (void)_createConnection;
- (id)_getConnection;
- (id)_proxyForServicingSelector:(SEL)arg1 asynchronous:(bool)arg2 withErrorHandler:(id /* block */)arg3;
- (id)_proxyForServicingSelector:(SEL)arg1 withErrorHandler:(id /* block */)arg2;
- (void)_setUpMonitoring;
- (void)_startHeartbeatForSessionID:(id)arg1;
- (void)_stopHeartbeat;
- (void)calculateDistanceToDestination:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)cancelInitializationForSessionID:(id)arg1 handler:(id /* block */)arg2;
- (void)cancelInitializationWithHandler:(id /* block */)arg1;
- (void)cancelMadridMessageSendForMessageGUID:(id)arg1 toHandle:(id)arg2 completion:(id /* block */)arg3;
- (void)checkEligibilityOfDestination:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)checkInitiatorEligibilityWithHandler:(id /* block */)arg1;
- (void)clearSessionMonitorStatesWithHandler:(id /* block */)arg1;
- (void)clearSessionsWithHandler:(id /* block */)arg1;
- (void)clearSuggestionsWithHandler:(id /* block */)arg1;
- (void)clearTriggerDestinationStatesWithHandler:(id /* block */)arg1;
- (void)createConnection;
- (id)createSMProxyErrorWithSelector:(SEL)arg1 error:(id)arg2;
- (void)dealloc;
- (void)endSessionForSessionID:(id)arg1 reason:(unsigned long long)arg2 handler:(id /* block */)arg3;
- (void)estimateEtaToDestination:(id)arg1 transportType:(unsigned long long)arg2 completionHandler:(id /* block */)arg3;
- (void)fetchAllReceiverSessionStatusWithCompletion:(id /* block */)arg1;
- (void)fetchCurrentSessionStateWithHandler:(id /* block */)arg1;
- (void)fetchInitiatorSafetyCacheForSessionID:(id)arg1 completion:(id /* block */)arg2;
- (void)fetchMostLikelyReceiverHandlesWithHandler:(id /* block */)arg1;
- (void)fetchMostLikelySessionDestinationsWithHandler:(id /* block */)arg1;
- (void)fetchMostRecentSessionMonitorStateWithSessionID:(id)arg1 handler:(id /* block */)arg2;
- (void)fetchReceiverSafetyCacheForSessionID:(id)arg1 completion:(id /* block */)arg2;
- (void)fetchReceiverSessionStatusForSessionID:(id)arg1 completion:(id /* block */)arg2;
- (void)fetchSessionConfigurationsWithOptions:(id)arg1 handler:(id /* block */)arg2;
- (void)fetchSessionManagerStatesWithOptions:(id)arg1 handler:(id /* block */)arg2;
- (void)fetchSessionReceiptForSessionID:(id)arg1 completion:(id /* block */)arg2;
- (void)fetchShouldShowProactiveSuggestionsWithHandler:(id /* block */)arg1;
- (void)fetchSuggestedSessionConfigurationWithHandler:(id /* block */)arg1;
- (void)fetchSuggestionsCountWithOptions:(id)arg1 handler:(id /* block */)arg2;
- (void)fetchSuggestionsWithOptions:(id)arg1 handler:(id /* block */)arg2;
- (void)fetchTriggerDestinationStateWithSessionID:(id)arg1 handler:(id /* block */)arg2;
- (void)handleDaemonStart;
- (id)heartbeatTimer;
- (void)iMessageConversationDeletedFor:(id)arg1;
- (void)iMessageDeletedFor:(id)arg1;
- (void)iMessageReceived:(id)arg1 fromHandle:(id)arg2 fromMe:(bool)arg3;
- (void)iMessageScheduledSendCancelFor:(id)arg1 successful:(bool)arg2 withError:(id)arg3;
- (void)iMessageScheduledSendScheduledFor:(id)arg1 guid:(id)arg2 successful:(bool)arg3 withError:(id)arg4;
- (void)iMessageScheduledSendTriggeredFor:(id)arg1;
- (void)iMessageSendFor:(id)arg1 guid:(id)arg2 successful:(bool)arg3 withError:(id)arg4;
- (id)init;
- (id)initWithRestorationIdentifier:(id)arg1;
- (void)initializeSessionWithHandle:(id)arg1 handler:(id /* block */)arg2;
- (id /* block */)initiatorSafetyCacheHandler;
- (void)launchSessionInitiationUIWithConfiguration:(id)arg1 handler:(id /* block */)arg2;
- (void)launchTaskWithSelector:(SEL)arg1 remainingAttempts:(unsigned long long)arg2 proxyErrorHandler:(id /* block */)arg3 taskBlock:(id /* block */)arg4;
- (void)modifySessionWithConfiguration:(id)arg1 handler:(id /* block */)arg2;
- (void)onInitiatorSafetyCacheChangeForSessionID:(id)arg1 phoneCache:(id)arg2 watchCache:(id)arg3 cacheExpiryDate:(id)arg4 cacheReleaseDate:(id)arg5;
- (void)onReceiverSafetyCacheChangeForSessionID:(id)arg1 phoneCache:(id)arg2 watchCache:(id)arg3;
- (void)onReceiverSessionStatusChangeForSessionID:(id)arg1 sessionStatus:(id)arg2;
- (void)onSessionStateChanged:(id)arg1 forActiveDevice:(bool)arg2 withError:(id)arg3;
- (long long)prepareUserInfoForNotificationContent:(id)arg1 initiatorHandle:(id)arg2 messageUrl:(id)arg3;
- (void)processStateForHeartbeat:(id)arg1 forActiveDevice:(bool)arg2 withError:(id)arg3;
- (void)promptDestinationAnomalyVerificationWithContext:(id)arg1 handler:(id /* block */)arg2;
- (void)promptRoundTripAnomalyVerificationWithContext:(id)arg1 handler:(id /* block */)arg2;
- (void)promptSafeArrivalWithContext:(id)arg1 handler:(id /* block */)arg2;
- (void)promptTimerEndedVerificationWithContext:(id)arg1 handler:(id /* block */)arg2;
- (id)queue;
- (id /* block */)receiverSafetyCacheHandler;
- (id /* block */)receiverSessionStatusHandler;
- (double)requestTimeFromTimed;
- (void)respondToNotificationWithIdentifier:(id)arg1 sessionIdentifier:(id)arg2 actionIdentifier:(id)arg3 handler:(id /* block */)arg4;
- (void)respondToTriggerPromptForSessionID:(id)arg1 response:(long long)arg2 handler:(id /* block */)arg3;
- (id)restorationIdentifier;
- (void)runProactiveSuggestionsEngineWithContext:(id)arg1 shouldStoreSuggestions:(bool)arg2 handler:(id /* block */)arg3;
- (void)scheduleMadridMessageSendForMessage:(id)arg1 messageGUID:(id)arg2 associatedGUID:(id)arg3 sendDate:(id)arg4 toHandle:(id)arg5 summaryText:(id)arg6 completion:(id /* block */)arg7;
- (void)sendHeartbeatForSessionID:(id)arg1 handler:(id /* block */)arg2;
- (void)sendIDSMessage:(id)arg1 toHandle:(id)arg2 completion:(id /* block */)arg3;
- (void)sendIDSMessageToMyDevices:(id)arg1 completion:(id /* block */)arg2;
- (void)sendIDSMessageToMyNearbyDevices:(id)arg1 completion:(id /* block */)arg2;
- (void)sendIDSMessageToPairedDevice:(id)arg1 completion:(id /* block */)arg2;
- (void)sendMadridMessage:(id)arg1 associatedGUID:(id)arg2 toHandle:(id)arg3 summaryText:(id)arg4 completion:(id /* block */)arg5;
- (void)sendSafetyCacheForSessionID:(id)arg1 handler:(id /* block */)arg2;
- (id /* block */)sessionStateHandler;
- (void)setHeartbeatTimer:(id)arg1;
- (void)setInitiatorSafetyCacheHandler:(id /* block */)arg1;
- (void)setQueue:(id)arg1;
- (void)setReceiverSafetyCacheHandler:(id /* block */)arg1;
- (void)setReceiverSessionStatusHandler:(id /* block */)arg1;
- (void)setRestorationIdentifier:(id)arg1;
- (void)setSessionStateHandler:(id /* block */)arg1;
- (void)setXpcConnection:(id)arg1;
- (bool)shouldDropMessage:(id)arg1 from:(id)arg2 fromMe:(bool)arg3;
- (void)shouldShowKeyboardSuggestionsForInitiator:(id)arg1 receiver:(id)arg2 handler:(id /* block */)arg3;
- (void)shouldShowTipKitSuggestionsForInitiator:(id)arg1 receiver:(id)arg2 handler:(id /* block */)arg3;
- (void)showSuggestionsDetectionUIWithSuggestion:(id)arg1 handler:(id /* block */)arg2;
- (void)startMonitoringInitiatorSafetyCacheWithHandler:(id /* block */)arg1;
- (void)startMonitoringReceiverSafetyCacheWithHandler:(id /* block */)arg1;
- (void)startMonitoringReceiverSessionStatusWithHandler:(id /* block */)arg1;
- (void)startMonitoringSessionStateWithHandler:(id /* block */)arg1;
- (void)startSessionWithConfiguration:(id)arg1 handler:(id /* block */)arg2;
- (void)stopMonitoringInitiatorSafetyCacheWithCompletion:(id /* block */)arg1;
- (void)stopMonitoringReceiverSafetyCacheWithCompletion:(id /* block */)arg1;
- (void)stopMonitoringReceiverSessionStatusWithCompletion:(id /* block */)arg1;
- (void)stopMonitoringSessionStateWithHandler:(id /* block */)arg1;
- (void)storeSessionConfigurations:(id)arg1 handler:(id /* block */)arg2;
- (void)storeSessionManagerStates:(id)arg1 handler:(id /* block */)arg2;
- (void)storeSessionMonitorStates:(id)arg1 handler:(id /* block */)arg2;
- (void)storeSuggestions:(id)arg1 handler:(id /* block */)arg2;
- (void)storeTriggerDestinationStates:(id)arg1 handler:(id /* block */)arg2;
- (void)submitInitializationAnalyticsEventWithError:(id)arg1 duration:(double)arg2;
- (void)userRequestedCacheDownloadForSessionID:(id)arg1 completion:(id /* block */)arg2;
- (id)xpcConnection;

@end
