
@interface WFModuleSummaryCoordinator : NSObject <WFModuleSummaryEditorDelegate, WFParameterEventObserver, WFSlotTemplateViewDelegate, WFVariableDelegate, WFVariableUIDelegate> {
    bool  _allowsPickingVariables;
    <WFEditorAuxiliaryViewPresenter> * _auxiliaryViewPresenter;
    NSArray * _contents;
    WFModuleSummaryEditor * _currentEditor;
    bool  _currentEditorIsEditing;
    WFSlotIdentifier * _currentlyEditingSlotIdentifier;
    WFSlotIdentifier * _currentlyTypingSlotIdentifier;
    <WFModuleSummaryCoordinatorDelegate> * _delegate;
    NSSet * _editableParameters;
    NSMutableDictionary * _mutableStagedParameterStates;
    NSDictionary * _parameterStates;
    NSSet * _parameters;
    bool  _processing;
    NSString * _summaryFormatString;
    WFModuleSummaryTemplateBuilder * _templateBuilder;
    WFSlotTemplateView * _templateView;
    id /* block */  _updateBlock;
    WFVariable * _variableBeingEdited;
    <WFVariableProvider> * _variableProvider;
    <WFVariableUIDelegate> * _variableUIDelegate;
    NSHashTable * _variablesBeingObserved;
}

@property (nonatomic) bool allowsPickingVariables;
@property (nonatomic) <WFEditorAuxiliaryViewPresenter> *auxiliaryViewPresenter;
@property (nonatomic, copy) NSArray *contents;
@property (nonatomic, retain) WFModuleSummaryEditor *currentEditor;
@property (nonatomic) bool currentEditorIsEditing;
@property (nonatomic, retain) WFSlotIdentifier *currentlyEditingSlotIdentifier;
@property (nonatomic, retain) WFSlotIdentifier *currentlyTypingSlotIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WFModuleSummaryCoordinatorDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSSet *editableParameters;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableDictionary *mutableStagedParameterStates;
@property (nonatomic, readonly, copy) NSDictionary *parameterStates;
@property (nonatomic, copy) NSSet *parameters;
@property (nonatomic) bool processing;
@property (nonatomic, readonly, copy) NSDictionary *stagedParameterStates;
@property (nonatomic, readonly, copy) NSString *summaryFormatString;
@property (readonly) Class superclass;
@property (nonatomic, retain) WFModuleSummaryTemplateBuilder *templateBuilder;
@property (nonatomic, retain) WFSlotTemplateView *templateView;
@property (nonatomic, copy) id /* block */ updateBlock;
@property (nonatomic, retain) WFVariable *variableBeingEdited;
@property (nonatomic) <WFVariableProvider> *variableProvider;
@property (nonatomic) <WFVariableUIDelegate> *variableUIDelegate;
@property (nonatomic, retain) NSHashTable *variablesBeingObserved;

+ (void)enumerateVariableAttachmentsInContents:(id)arg1 withBlock:(id /* block */)arg2;
+ (double)heightForWidth:(double)arg1 withSummaryFormatString:(id)arg2 parameters:(id)arg3 editableParameters:(id)arg4 parameterStates:(id)arg5 stagedParameterStates:(id)arg6 horizontalPadding:(double)arg7 font:(id)arg8 unpopulatedFont:(id)arg9 textAlignment:(long long)arg10;
+ (id)parameterStatesByApplyingStaging:(id)arg1 toOriginal:(id)arg2;

- (void).cxx_destruct;
- (id)addElementToArrayForParameterKey:(id)arg1;
- (bool)allowsPickingVariables;
- (id)auxiliaryViewPresenter;
- (void)beginEditingSlotWithIdentifier:(id)arg1 fromTextAttachment:(id)arg2;
- (void)cancelEditingWithCompletionHandler:(id /* block */)arg1;
- (id)contents;
- (id)createSummaryEditorForSlotWithIdentifier:(id)arg1;
- (id)currentEditor;
- (bool)currentEditorIsEditing;
- (id)currentParameterStateForParameterKey:(id)arg1;
- (id)currentlyEditingSlotIdentifier;
- (id)currentlyTypingSlotIdentifier;
- (id)delegate;
- (void)destroyCurrentEditor;
- (id)editableParameters;
- (Class)editorClassForParameter:(id)arg1;
- (id)firstSlotIdentifierWithParameterKey:(id)arg1;
- (id)init;
- (id)initialStateForSummaryEditor:(id)arg1;
- (void)menuDidDismissInSlotTemplateView:(id)arg1;
- (id)mutableStagedParameterStates;
- (void)parameterAttributesDidChange:(id)arg1;
- (id)parameterForKey:(id)arg1;
- (id)parameterStates;
- (id)parameters;
- (id)presentationAnchorForSlotWithIdentifier:(id)arg1;
- (bool)processing;
- (void)removeElementFromArrayAtIndex:(unsigned long long)arg1 forParameterKey:(id)arg2;
- (void)revealAction:(id)arg1 preScrollHandler:(id /* block */)arg2 goBackHandler:(id /* block */)arg3 scrolledAwayHandler:(id /* block */)arg4;
- (void)setAllowsPickingVariables:(bool)arg1;
- (void)setAuxiliaryViewPresenter:(id)arg1;
- (void)setContents:(id)arg1;
- (void)setCurrentEditor:(id)arg1;
- (void)setCurrentEditorIsEditing:(bool)arg1;
- (void)setCurrentlyEditingSlotIdentifier:(id)arg1;
- (void)setCurrentlyTypingSlotIdentifier:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMutableStagedParameterStates:(id)arg1;
- (void)setParameters:(id)arg1;
- (void)setProcessing:(bool)arg1;
- (void)setSummaryFormatString:(id)arg1 withParameters:(id)arg2 editableParameters:(id)arg3 parameterStates:(id)arg4;
- (void)setTemplateBuilder:(id)arg1;
- (void)setTemplateView:(id)arg1;
- (void)setUpdateBlock:(id /* block */)arg1;
- (void)setVariableBeingEdited:(id)arg1;
- (void)setVariableProvider:(id)arg1;
- (void)setVariableUIDelegate:(id)arg1;
- (void)setVariablesBeingObserved:(id)arg1;
- (void)showActionOutputPickerAllowingShortcutInput:(bool)arg1 variableProvider:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)showParameterEditingHint:(id)arg1;
- (void)showVariableEditorWithOptions:(id)arg1 fromSourceRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)slotTemplateView:(id)arg1 deletePressedOnSlotWithIdentifier:(id)arg2 allowResettingValue:(bool)arg3;
- (void)slotTemplateView:(id)arg1 didChangeText:(id)arg2 forSlotWithIdentifier:(id)arg3;
- (void)slotTemplateView:(id)arg1 didDeselectSlotWithIdentifier:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)slotTemplateView:(id)arg1 didEndTypingInSlotWithIdentifier:(id)arg2;
- (void)slotTemplateView:(id)arg1 didSelectSlotWithIdentifier:(id)arg2;
- (void)slotTemplateView:(id)arg1 didTapTextAttachment:(id)arg2 inSlotWithIdentifier:(id)arg3;
- (void)slotTemplateView:(id)arg1 disclosureArrowDidChange:(bool)arg2;
- (id)slotTemplateView:(id)arg1 menuForSlotIdentifier:(id)arg2 style:(unsigned long long)arg3;
- (void)slotTemplateView:(id)arg1 outputButtonDidChange:(bool)arg2;
- (bool)slotTemplateView:(id)arg1 shouldChangeText:(id)arg2 forSlotWithIdentifier:(id)arg3;
- (bool)slotTemplateView:(id)arg1 shouldTapTextAttachment:(id)arg2 inSlotWithIdentifier:(id)arg3;
- (void)slotTemplateView:(id)arg1 typingDidCopyWithOriginalBlock:(id /* block */)arg2;
- (void)slotTemplateView:(id)arg1 typingDidCutWithOriginalBlock:(id /* block */)arg2;
- (void)slotTemplateView:(id)arg1 typingDidPasteWithOriginalBlock:(id /* block */)arg2;
- (void)slotTemplateView:(id)arg1 willBeginTypingInSlotWithIdentifier:(id)arg2 usingTextEntry:(id)arg3 allowMultipleLines:(bool*)arg4;
- (void)slotTemplateViewDidInvalidateSize:(id)arg1;
- (void)slotTemplateViewTintColorDidChange:(id)arg1;
- (id)stagedParameterStates;
- (void)summaryEditor:(id)arg1 didCommitParameterState:(id)arg2;
- (void)summaryEditor:(id)arg1 didRequestEditingSlotWithIdentifier:(id)arg2;
- (void)summaryEditor:(id)arg1 didStageParameterState:(id)arg2;
- (void)summaryEditor:(id)arg1 willUpdateVariable:(id)arg2;
- (void)summaryEditorDidFinish:(id)arg1 returnToKeyboard:(bool)arg2 withTextAttachmentToEdit:(id)arg3;
- (void)summaryEditorDidRequestTextEntry:(id)arg1;
- (id)summaryFormatString;
- (id)templateBuilder;
- (id)templateView;
- (id)transformParameterStateForSerialization:(id)arg1 inEditor:(id)arg2;
- (id /* block */)updateBlock;
- (void)updateTemplateContentsAnimated:(bool)arg1;
- (void)updateVariableObservationsWithContents:(id)arg1;
- (id)variableBeingEdited;
- (void)variableDidChange:(id)arg1;
- (id)variableProvider;
- (id)variableUIDelegate;
- (id)variablesBeingObserved;

@end
