
@interface PTRaytracingV14RenderState : NSObject {
    float  _anamorphicFactor;
    <MTLBuffer> * _aperturePointsXY;
    void _colorSize;
    NSString * _description;
    <MTLTexture> * _disparityDiff;
    PTMTLDropHints * _disparityDiffDropHints;
    <MTLBuffer> * _disparityDiffGlobalMax;
    <MTLBuffer> * _disparityDiffGlobalMinMax;
    <MTLTexture> * _disparityEdges;
    <MTLTexture> * _disparityEdgesTemp;
    PTDisparityUpscale * _disparityUpscale;
    bool  _doVisualization;
    PTMTLDropHints * _dropHintsRGBRadiusUpscaled;
    PTMTLDropHints * _dropHintsRaytracing;
    float  _edgeTolerance;
    <MTLTexture> * _focusEdgeMask;
    PTGlobalReduction * _globalReduction;
    float  _kPyramidSamplingFraction;
    int  _quality;
    PTQualitySettings * _qualitySettings;
    <MTLTexture> * _randomGaussNoise;
    <MTLBuffer> * _randomUChars;
    <MTLTexture> * _randomizedGauss;
    int  _rayCount;
    <MTLTexture> * _raytracedRGBRadius;
    <MTLTexture> * _raytracedRGBRadiusUpscaled;
    float  _raytracingRadiusLocal;
    <MTLComputePipelineState> * _raytracingSDOF;
}

@property float anamorphicFactor;
@property (nonatomic, retain) <MTLBuffer> *aperturePointsXY;
@property void colorSize;
@property (nonatomic, retain) <MTLTexture> *disparityDiff;
@property (nonatomic, retain) PTMTLDropHints *disparityDiffDropHints;
@property (nonatomic, retain) <MTLBuffer> *disparityDiffGlobalMinMax;
@property (nonatomic, retain) <MTLTexture> *disparityEdges;
@property (nonatomic, retain) <MTLTexture> *disparityEdgesTemp;
@property (nonatomic, retain) PTDisparityUpscale *disparityUpscale;
@property bool doVisualization;
@property (nonatomic, retain) PTMTLDropHints *dropHintsRGBRadiusUpscaled;
@property (nonatomic, retain) PTMTLDropHints *dropHintsRaytracing;
@property float edgeTolerance;
@property (nonatomic, retain) <MTLTexture> *focusEdgeMask;
@property (nonatomic, retain) PTGlobalReduction *globalReduction;
@property float pyramidSamplingFraction;
@property (nonatomic, retain) PTQualitySettings *qualitySettings;
@property (nonatomic, retain) <MTLTexture> *randomGaussNoise;
@property (nonatomic, retain) <MTLBuffer> *randomUChars;
@property int rayCount;
@property (nonatomic, retain) <MTLTexture> *raytracedRGBRadius;
@property (nonatomic, retain) <MTLTexture> *raytracedRGBRadiusUpscaled;
@property float raytracingRadiusLocal;
@property (nonatomic, retain) <MTLComputePipelineState> *raytracingSDOF;

- (void).cxx_destruct;
- (float)anamorphicFactor;
- (id)aperturePointsXY;
- (void)colorSize;
- (unsigned long long)dependentFrames;
- (id)description;
- (id)disparityDiff;
- (id)disparityDiffDropHints;
- (id)disparityDiffGlobalMinMax;
- (id)disparityEdges;
- (id)disparityEdgesTemp;
- (id)disparityUpscale;
- (bool)doVisualization;
- (id)dropHintsRGBRadiusUpscaled;
- (id)dropHintsRaytracing;
- (float)edgeTolerance;
- (id)focusEdgeMask;
- (id)globalReduction;
- (id)initWithMetalContext:(id)arg1 util:(id)arg2 quality:(int)arg3 colorSize:(struct CGSize { double x1; double x2; })arg4 disparitySize:(struct CGSize { double x1; double x2; })arg5 debugRendering:(long long)arg6 pyramidPixelFormat:(unsigned long long)arg7 config:(id)arg8 debugTextures:(id)arg9;
- (float)pyramidSamplingFraction;
- (id)qualitySettings;
- (id)randomGaussNoise;
- (id)randomUChars;
- (int)rayCount;
- (id)raytracedRGBRadius;
- (id)raytracedRGBRadiusUpscaled;
- (float)raytracingRadiusLocal;
- (id)raytracingSDOF;
- (void)reset;
- (void)setAnamorphicFactor:(float)arg1;
- (void)setAperturePointsXY:(id)arg1;
- (void)setColorSize;
- (void)setDisparityDiff:(id)arg1;
- (void)setDisparityDiffDropHints:(id)arg1;
- (void)setDisparityDiffGlobalMinMax:(id)arg1;
- (void)setDisparityEdges:(id)arg1;
- (void)setDisparityEdgesTemp:(id)arg1;
- (void)setDisparityUpscale:(id)arg1;
- (void)setDoVisualization:(bool)arg1;
- (void)setDropHintsRGBRadiusUpscaled:(id)arg1;
- (void)setDropHintsRaytracing:(id)arg1;
- (void)setEdgeTolerance:(float)arg1;
- (void)setFocusEdgeMask:(id)arg1;
- (void)setGlobalReduction:(id)arg1;
- (void)setPyramidSamplingFraction:(float)arg1;
- (void)setQualitySettings:(id)arg1;
- (void)setRandomGaussNoise:(id)arg1;
- (void)setRandomUChars:(id)arg1;
- (void)setRayCount:(int)arg1;
- (void)setRaytracedRGBRadius:(id)arg1;
- (void)setRaytracedRGBRadiusUpscaled:(id)arg1;
- (void)setRaytracingRadiusLocal:(float)arg1;
- (void)setRaytracingSDOF:(id)arg1;

@end
