
@interface CKSyncEngineFetchChangesOperation : NSOperation <CKPropertiesDescription> {
    CKDatabase * _database;
    id /* block */  _databaseChangeTokenUpdatedBlock;
    id /* block */  _databaseChangesConfigurationBlock;
    NSError * _error;
    int  _executionState;
    id /* block */  _fetchChangesCompletionBlock;
    id /* block */  _fetchDatabaseChangesCompletionBlock;
    id /* block */  _networkAttributionBundleIDOverrideBlock;
    id /* block */  _nextRecordZoneChangesConfigurationsBlock;
    NSOperationQueue * _operationQueue;
    CKSyncEngineFetchChangesOptions * _options;
    id /* block */  _recordWasChangedBlock;
    id /* block */  _recordWithIDWasDeletedBlock;
    id /* block */  _recordZoneChangeTokensUpdatedBlock;
    id /* block */  _recordZoneFetchCompletionBlock;
    id /* block */  _recordZoneWithIDChangedBlock;
    id /* block */  _recordZoneWithIDWasDeletedBlock;
    id /* block */  _recordZoneWithIDWasDeletedDueToUserEncryptedDataResetBlock;
    id /* block */  _recordZoneWithIDWasPurgedBlock;
    id /* block */  _willBeginFetchingChangesForZoneIDsBlock;
    id /* block */  _willEnqueueOperationBlock;
}

@property (nonatomic, readonly) CKDatabase *database;
@property (nonatomic, copy) id /* block */ databaseChangeTokenUpdatedBlock;
@property (nonatomic, copy) id /* block */ databaseChangesConfigurationBlock;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSError *error;
@property (nonatomic, copy) id /* block */ fetchChangesCompletionBlock;
@property (nonatomic, copy) id /* block */ fetchDatabaseChangesCompletionBlock;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id /* block */ networkAttributionBundleIDOverrideBlock;
@property (nonatomic, copy) id /* block */ nextRecordZoneChangesConfigurationsBlock;
@property (nonatomic, retain) NSOperationQueue *operationQueue;
@property (nonatomic, readonly) CKSyncEngineFetchChangesOptions *options;
@property (nonatomic, copy) id /* block */ recordWasChangedBlock;
@property (nonatomic, copy) id /* block */ recordWithIDWasDeletedBlock;
@property (nonatomic, copy) id /* block */ recordZoneChangeTokensUpdatedBlock;
@property (nonatomic, copy) id /* block */ recordZoneFetchCompletionBlock;
@property (nonatomic, copy) id /* block */ recordZoneWithIDChangedBlock;
@property (nonatomic, copy) id /* block */ recordZoneWithIDWasDeletedBlock;
@property (nonatomic, copy) id /* block */ recordZoneWithIDWasDeletedDueToUserEncryptedDataResetBlock;
@property (nonatomic, copy) id /* block */ recordZoneWithIDWasPurgedBlock;
@property (readonly) Class superclass;
@property (nonatomic, copy) id /* block */ willBeginFetchingChangesForZoneIDsBlock;
@property (nonatomic, copy) id /* block */ willEnqueueOperationBlock;

+ (bool)_removesDependenciesAfterFinish;
+ (unsigned long long)maxZonesPerOperation;
+ (void)setMaxZonesPerOperation:(unsigned long long)arg1;

- (void).cxx_destruct;
- (void)CKDescribePropertiesUsing:(id)arg1;
- (id)CKDescriptionClassName;
- (void)cancel;
- (id)cancelledError;
- (id)database;
- (id /* block */)databaseChangeTokenUpdatedBlock;
- (id /* block */)databaseChangesConfigurationBlock;
- (id)description;
- (id)error;
- (id /* block */)fetchChangesCompletionBlock;
- (id /* block */)fetchDatabaseChangesCompletionBlock;
- (void)fetchDatabaseChangesThenRecordZoneChangesWithDatabaseChangeToken:(id)arg1;
- (void)fetchRecordZoneChangesIfNecessaryOrFinish;
- (void)fetchRecordZoneChangesWithZoneIDs:(id)arg1 configurations:(id)arg2 fetchAllChanges:(bool)arg3 shouldFetchAssetContents:(bool)arg4;
- (void)finishWithError:(id)arg1;
- (id)init;
- (id)initWithDatabase:(id)arg1 options:(id)arg2;
- (bool)isAsynchronous;
- (bool)isExecuting;
- (bool)isFinished;
- (id /* block */)networkAttributionBundleIDOverrideBlock;
- (id /* block */)nextRecordZoneChangesConfigurationsBlock;
- (id)operationQueue;
- (id)options;
- (id /* block */)recordWasChangedBlock;
- (id /* block */)recordWithIDWasDeletedBlock;
- (id /* block */)recordZoneChangeTokensUpdatedBlock;
- (id /* block */)recordZoneFetchCompletionBlock;
- (id /* block */)recordZoneWithIDChangedBlock;
- (id /* block */)recordZoneWithIDWasDeletedBlock;
- (id /* block */)recordZoneWithIDWasDeletedDueToUserEncryptedDataResetBlock;
- (id /* block */)recordZoneWithIDWasPurgedBlock;
- (id)redactedDescription;
- (void)setDatabaseChangeTokenUpdatedBlock:(id /* block */)arg1;
- (void)setDatabaseChangesConfigurationBlock:(id /* block */)arg1;
- (void)setError:(id)arg1;
- (void)setFetchChangesCompletionBlock:(id /* block */)arg1;
- (void)setFetchDatabaseChangesCompletionBlock:(id /* block */)arg1;
- (void)setNetworkAttributionBundleIDOverrideBlock:(id /* block */)arg1;
- (void)setNextRecordZoneChangesConfigurationsBlock:(id /* block */)arg1;
- (void)setOperationQueue:(id)arg1;
- (void)setRecordWasChangedBlock:(id /* block */)arg1;
- (void)setRecordWithIDWasDeletedBlock:(id /* block */)arg1;
- (void)setRecordZoneChangeTokensUpdatedBlock:(id /* block */)arg1;
- (void)setRecordZoneFetchCompletionBlock:(id /* block */)arg1;
- (void)setRecordZoneWithIDChangedBlock:(id /* block */)arg1;
- (void)setRecordZoneWithIDWasDeletedBlock:(id /* block */)arg1;
- (void)setRecordZoneWithIDWasDeletedDueToUserEncryptedDataResetBlock:(id /* block */)arg1;
- (void)setRecordZoneWithIDWasPurgedBlock:(id /* block */)arg1;
- (void)setWillBeginFetchingChangesForZoneIDsBlock:(id /* block */)arg1;
- (void)setWillEnqueueOperationBlock:(id /* block */)arg1;
- (void)start;
- (void)transitionToExecuting;
- (void)transitionToFinished;
- (id /* block */)willBeginFetchingChangesForZoneIDsBlock;
- (id /* block */)willEnqueueOperationBlock;

@end
