
@interface FCIssue : NSObject <FCContentArchivable, FCFeedPersonalizingItem, FCIssueAccessCheckable, NSCopying> {
    NSArray * _allArticleIDs;
    NSArray * _allowedStorefrontIDs;
    NSArray * _blockedStorefrontIDs;
    NSString * _coverArticleID;
    NSString * _coverDate;
    FCColor * _coverImageAccentColor;
    double  _coverImageAspectRatio;
    FCAssetHandle * _coverImageAssetHandle;
    FCColor * _coverImageBackgroundColor;
    FCColor * _coverImagePrimaryColor;
    FCColor * _coverImageTextColor;
    NSString * _identifier;
    FCInterestToken * _interestToken;
    bool  _isCurrent;
    bool  _isDraft;
    NSString * _issueDescription;
    NTPBIssueRecord * _issueRecord;
    double  _layeredCoverAspectRatio;
    NSString * _layeredCoverJSON;
    FCColor * _layeredCoverPrimaryColor;
    FCAssetHandle * _metadataJSONAssetHandle;
    long long  _minimumNewsVersion;
    NSString * _notificationDescription;
    bool  _paid;
    NSDate * _publicationDate;
    FCFeedPersonalizedItemScoreProfile * _scoreProfile;
    NSDate * _sortDate;
    <FCChannelProviding> * _sourceChannel;
    NSString * _title;
    NSArray * _topicTagIDs;
    long long  _type;
}

@property (nonatomic, readonly, copy) NSArray *allArticleIDs;
@property (nonatomic, readonly, copy) NSArray *allowedStorefrontIDs;
@property (getter=isANF, nonatomic, readonly) bool anf;
@property (nonatomic, readonly, copy) NSArray *blockedStorefrontIDs;
@property (nonatomic, readonly) long long bodyTextLength;
@property (getter=isBundlePaid, nonatomic, readonly) bool bundlePaid;
@property (nonatomic, readonly, copy) NSString *clusterID;
@property (nonatomic, readonly) FCContentArchive *contentArchive;
@property (nonatomic, readonly, copy) NSString *coverArticleID;
@property (nonatomic, readonly, copy) NSString *coverDate;
@property (nonatomic, readonly, copy) FCColor *coverImageAccentColor;
@property (nonatomic, readonly) double coverImageAspectRatio;
@property (nonatomic, readonly) FCAssetHandle *coverImageAssetHandle;
@property (nonatomic, readonly, copy) FCColor *coverImageBackgroundColor;
@property (nonatomic, readonly, copy) FCColor *coverImagePrimaryColor;
@property (nonatomic, readonly, copy) FCColor *coverImageTextColor;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLArticleContentExpiration *expirationData;
@property (nonatomic, readonly) NSData *float16FullBodyEncoding;
@property (nonatomic, readonly) NSData *float16TitleEncoding;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList *globalCohorts;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats *globalConversionStats;
@property (nonatomic, readonly) double globalUserFeedback;
@property (nonatomic, readonly) unsigned long long halfLife;
@property (nonatomic, readonly) unsigned long long halfLifeOverride;
@property (nonatomic, readonly) bool hasAudioTrack;
@property (nonatomic, readonly) bool hasGlobalUserFeedback;
@property (nonatomic, readonly) bool hasThumbnail;
@property (nonatomic, readonly) bool hasVideo;
@property (readonly) unsigned long long hash;
@property (getter=isHiddenFromAutoFavorites, nonatomic, readonly) bool hiddenFromAutoFavorites;
@property (nonatomic, readonly, copy) NSArray *iAdCategories;
@property (nonatomic, readonly, copy) NSString *identifier;
@property (nonatomic, retain) FCInterestToken *interestToken;
@property (nonatomic, readonly) bool isBlockedExplicitContent;
@property (nonatomic, readonly) bool isCurrent;
@property (nonatomic, readonly) bool isDraft;
@property (nonatomic, readonly) bool isEvergreen;
@property (nonatomic, readonly) bool isFeatureCandidate;
@property (nonatomic, readonly) bool isFeatured;
@property (nonatomic, readonly) bool isLocalDraft;
@property (nonatomic, readonly, copy) NSString *issueDescription;
@property (nonatomic, readonly) NTPBIssueRecord *issueRecord;
@property (nonatomic, readonly, copy) NSString *itemID;
@property (nonatomic, readonly, copy) NSString *language;
@property (nonatomic, readonly) double layeredCoverAspectRatio;
@property (nonatomic, readonly, copy) NSString *layeredCoverJSON;
@property (nonatomic, readonly, copy) FCColor *layeredCoverPrimaryColor;
@property (nonatomic, readonly) FCAssetHandle *metadataJSONAssetHandle;
@property (nonatomic, readonly) long long minimumNewsVersion;
@property (nonatomic, readonly, copy) NSString *notificationDescription;
@property (getter=isPaid, nonatomic, readonly) bool paid;
@property (nonatomic, readonly, copy) NSDate *publicationDate;
@property (nonatomic, readonly, copy) NSDate *publishDate;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList *publisherCohorts;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats *publisherConversionStats;
@property (nonatomic, readonly, copy) NSString *publisherID;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLTagMetadata *publisherTagMetadata;
@property (nonatomic, readonly) bool reduceVisibility;
@property (retain) FCFeedPersonalizedItemScoreProfile *scoreProfile;
@property (nonatomic, readonly, copy) NSDate *sortDate;
@property (nonatomic, readonly, copy) <FCChannelProviding> *sourceChannel;
@property (nonatomic, readonly, copy) NSString *sourceChannelID;
@property (nonatomic, readonly, copy) NSString *sourceFeedID;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSData *thumbnailPerceptualHash;
@property (nonatomic, readonly, copy) NSString *title;
@property (nonatomic, readonly, copy) NSArray *topicIDs;
@property (nonatomic, readonly, copy) NSArray *topicTagIDs;
@property (nonatomic, readonly, copy) NSArray *topics;
@property (nonatomic, readonly) long long type;
@property (nonatomic, readonly) bool webConverted;

+ (bool)_fakeIssuesTimestamp;

- (void).cxx_destruct;
- (id)allArticleIDs;
- (id)allowedStorefrontIDs;
- (id)blockedStorefrontIDs;
- (id)contentArchive;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)coverArticleID;
- (id)coverDate;
- (id)coverImageAccentColor;
- (double)coverImageAspectRatio;
- (id)coverImageAssetHandle;
- (id)coverImageBackgroundColor;
- (id)coverImagePrimaryColor;
- (id)coverImageTextColor;
- (id)description;
- (void)enumerateTopicCohortsWithBlock:(id /* block */)arg1;
- (void)enumerateTopicConversionStatsWithBlock:(id /* block */)arg1;
- (id)globalCohorts;
- (id)globalConversionStats;
- (double)globalUserFeedback;
- (unsigned long long)halfLife;
- (bool)hasGlobalUserFeedback;
- (bool)hasThumbnail;
- (bool)hasVideo;
- (unsigned long long)hash;
- (id)identifier;
- (id)init;
- (id)initWithData:(id)arg1 sourceChannel:(id)arg2 assetManager:(id)arg3;
- (id)initWithIdentifier:(id)arg1 type:(long long)arg2 title:(id)arg3 publicationDate:(id)arg4 coverDate:(id)arg5 metadataJSONAssetHandle:(id)arg6 coverImageAssetHandle:(id)arg7 coverImageAspectRatio:(double)arg8 coverImagePrimaryColor:(id)arg9 coverImageBackgroundColor:(id)arg10 coverImageTextColor:(id)arg11 coverImageAccentColor:(id)arg12 layeredCoverJSON:(id)arg13 layeredCoverAspectRatio:(double)arg14 layeredCoverPrimaryColor:(id)arg15 isCurrent:(bool)arg16 isDraft:(bool)arg17 isPaid:(bool)arg18 minimumNewsVersion:(long long)arg19 allArticleIDs:(id)arg20 coverArticleID:(id)arg21 allowedStorefrontIDs:(id)arg22 blockedStorefrontIDs:(id)arg23 topicTagIDs:(id)arg24 sourceChannel:(id)arg25 notificationDescription:(id)arg26 issueDescription:(id)arg27 sortDate:(id)arg28;
- (id)initWithIssue:(id)arg1 overrides:(id)arg2;
- (id)initWithIssueRecord:(id)arg1 assetManager:(id)arg2 interestToken:(id)arg3 sourceChannel:(id)arg4;
- (id)interestToken;
- (bool)isANF;
- (bool)isBlockedExplicitContent;
- (bool)isBundlePaid;
- (bool)isCurrent;
- (bool)isDraft;
- (bool)isEqual:(id)arg1;
- (bool)isHiddenFromAutoFavorites;
- (bool)isLocalDraft;
- (bool)isPaid;
- (id)issueDescription;
- (id)issueRecord;
- (id)itemID;
- (double)layeredCoverAspectRatio;
- (id)layeredCoverJSON;
- (id)layeredCoverPrimaryColor;
- (id)metadataJSONAssetHandle;
- (long long)minimumNewsVersion;
- (id)notificationDescription;
- (id)publicationDate;
- (id)publishDate;
- (id)publisherCohorts;
- (id)publisherConversionStats;
- (id)publisherID;
- (id)publisherTagMetadata;
- (id)scoreProfile;
- (void)setInterestToken:(id)arg1;
- (void)setScoreProfile:(id)arg1;
- (id)sortDate;
- (id)sourceChannel;
- (id)sourceChannelID;
- (id)sourceFeedID;
- (id)title;
- (id)topicIDs;
- (id)topicTagIDs;
- (id)topics;
- (long long)type;

@end
