
@interface ACHMonthlyChallengeAwardingSource : NSObject <ACHAchievementProgressProviding, ACHEarnedInstanceAwarding, HDCurrentActivitySummaryHelperObserver, HDDataObserver, HDHealthDaemonReadyObserver> {
    unsigned char  _creatorDevice;
    ACHEarnedInstanceStore * _earnedInstanceStore;
    ACHEarnedInstanceAwardingEngine * _engine;
    HKHealthStore * _healthStore;
    NSObject<OS_dispatch_queue> * _internalQueue;
    ACHMonthlyChallengeDataSource * _monthlyDataSource;
    NSNumber * _overrideIsAppleWatch;
    HDProfile * _profile;
    ACHAchievementProgressEngine * _progressEngine;
    ACHCurrentActivitySummaryQuery * _summaryQuery;
    ACHTemplateStore * _templateStore;
    HKAnchoredObjectQuery * _workoutQuery;
}

@property (nonatomic) unsigned char creatorDevice;
@property (nonatomic, retain) NSDictionary *dataStoreProperties;
@property (nonatomic, readonly) NSArray *dataStorePropertyKeys;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) ACHEarnedInstanceStore *earnedInstanceStore;
@property (nonatomic) ACHEarnedInstanceAwardingEngine *engine;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) HKHealthStore *healthStore;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *internalQueue;
@property (nonatomic, readonly) bool isAppleWatch;
@property (nonatomic) ACHMonthlyChallengeDataSource *monthlyDataSource;
@property (nonatomic, retain) NSNumber *overrideIsAppleWatch;
@property (nonatomic) HDProfile *profile;
@property (nonatomic) ACHAchievementProgressEngine *progressEngine;
@property (nonatomic, retain) ACHCurrentActivitySummaryQuery *summaryQuery;
@property (readonly) Class superclass;
@property (nonatomic) ACHTemplateStore *templateStore;
@property (nonatomic, readonly) NSString *uniqueName;
@property (nonatomic, retain) HKAnchoredObjectQuery *workoutQuery;

- (void).cxx_destruct;
- (id)_earnedDateComponentsForTemplate:(id)arg1;
- (id)_earnedInstancesForInterval:(id)arg1;
- (id)_evaluationEnvironmentForTemplate:(id)arg1;
- (id)_evaluationEnvironmentForTemplate:(id)arg1 andDateComponentInterval:(id)arg2;
- (id)_monthlyChallengeTemplatesForHistoricalInterval:(id)arg1;
- (id)_queue_goalQuantityForTemplate:(id)arg1;
- (id)_queue_progressQuantityForTemplate:(id)arg1;
- (void)_requestIncrementalEvaluation;
- (void)_startQueries;
- (unsigned char)creatorDevice;
- (void)currentActivitySummaryHelper:(id)arg1 didUpdateTodayActivitySummary:(id)arg2 changedFields:(unsigned long long)arg3;
- (void)currentActivitySummaryHelper:(id)arg1 didUpdateYesterdayActivitySummary:(id)arg2 changedFields:(unsigned long long)arg3;
- (void)daemonReady:(id)arg1;
- (void)dataStoreDidClearAllProperties:(id)arg1 completion:(id /* block */)arg2;
- (id)dataStoreProperties;
- (id)dataStorePropertyKeys;
- (id)earnedInstanceStore;
- (id)earnedInstancesForHistoricalInterval:(id)arg1 databaseContext:(id)arg2;
- (id)earnedInstancesForHistoricalInterval:(id)arg1 error:(id*)arg2;
- (id)engine;
- (id)healthStore;
- (id)initWithHealthStore:(id)arg1 awardingEngine:(id)arg2 templateStore:(id)arg3 earnedInstanceStore:(id)arg4 monthlyDataSource:(id)arg5 creatorDevice:(unsigned char)arg6 progressEngine:(id)arg7;
- (id)initWithProfile:(id)arg1 awardingEngine:(id)arg2 templateStore:(id)arg3 earnedInstanceStore:(id)arg4 monthlyDataSource:(id)arg5 creatorDevice:(unsigned char)arg6 progressEngine:(id)arg7;
- (id)internalQueue;
- (bool)isAppleWatch;
- (id)monthlyDataSource;
- (id)overrideIsAppleWatch;
- (id)profile;
- (id)progressEngine;
- (id)providerIdentifier;
- (bool)providesProgressForTemplate:(id)arg1;
- (void)requestAchievementProgressUpdatesForTemplates:(id)arg1;
- (void)samplesAdded:(id)arg1 anchor:(id)arg2;
- (void)setCreatorDevice:(unsigned char)arg1;
- (void)setDataStoreProperties:(id)arg1;
- (void)setEarnedInstanceStore:(id)arg1;
- (void)setEngine:(id)arg1;
- (void)setHealthStore:(id)arg1;
- (void)setInternalQueue:(id)arg1;
- (void)setMonthlyDataSource:(id)arg1;
- (void)setOverrideIsAppleWatch:(id)arg1;
- (void)setProfile:(id)arg1;
- (void)setProgressEngine:(id)arg1;
- (void)setSummaryQuery:(id)arg1;
- (void)setTemplateStore:(id)arg1;
- (void)setWorkoutQuery:(id)arg1;
- (id)summaryQuery;
- (id)templateStore;
- (id)uniqueName;
- (id)workoutQuery;

@end
