
@interface GKPlayer : GKBasePlayer <NSCoding, NSSecureCoding> {
    NSArray * _friends;
    GKPlayerInternal * _internal;
    NSAttributedString * _whenString;
}

@property (nonatomic, readonly) NSNumber *acceptedGameInviteFromThisFriend;
@property (nonatomic, copy) NSString *alias;
@property (nonatomic, readonly) NSNumber *automatchedTogether;
@property (nonatomic, readonly) long long avatarType;
@property (nonatomic, readonly) NSString *cacheKey;
@property (nonatomic, retain) CNContact *contact;
@property (nonatomic, readonly) NSString *displayName;
@property (nonatomic, readonly) NSString *firstName;
@property (nonatomic, readonly) NSNumber *friendBiDirectional;
@property (nonatomic, readonly) NSNumber *friendLevel;
@property (nonatomic, readonly) NSNumber *friendPlayedNearby;
@property (nonatomic, readonly) NSNumber *friendPlayedWith;
@property (nonatomic, retain) NSArray *friends;
@property (nonatomic, readonly, retain) NSString *gamePlayerID;
@property (nonatomic, readonly) NSString *guestIdentifier;
@property (nonatomic, readonly) bool hasPhoto;
@property (nonatomic, readonly) NSNumber *initiatedGameInviteToThisFriend;
@property (retain) GKPlayerInternal *internal;
@property (nonatomic, readonly) bool isAnonymousPlayer;
@property (nonatomic, readonly) bool isAutomatchPlayer;
@property (nonatomic, readonly) bool isFamiliarFriend;
@property (nonatomic) bool isFriend;
@property (nonatomic, readonly) bool isGuestPlayer;
@property (nonatomic, readonly) bool isInContacts;
@property (nonatomic, readonly) bool isInvitable;
@property (nonatomic, readonly) bool isLocalPlayer;
@property (nonatomic, readonly) bool isUnknownPlayer;
@property (nonatomic, readonly) NSString *lastName;
@property (nonatomic, readonly) NSDate *lastPlayedDate;
@property (nonatomic, readonly) GKGame *lastPlayedGame;
@property (getter=isLoaded, nonatomic, readonly) bool loaded;
@property (nonatomic, readonly) NSString *messagesID;
@property (nonatomic) unsigned long long numberOfFriends;
@property (nonatomic, retain) NSString *playerID;
@property (nonatomic, retain) NSString *reason;
@property (nonatomic, retain) NSString *reason2;
@property (readonly) NSString *referenceKey;
@property (nonatomic) unsigned int rid;
@property (nonatomic) int source;
@property (nonatomic, readonly) struct { long long x1; long long x2; long long x3; long long x4; long long x5; long long x6; long long x7; long long x8; long long x9; } stats;
@property (nonatomic, copy) NSString *status;
@property (nonatomic, readonly, retain) NSString *teamPlayerID;
@property (nonatomic, retain) NSAttributedString *whenString;

// Image: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation

+ (void)_loadPlayersForIdentifiers:(id)arg1 withCompletionHandler:(id /* block */)arg2;
+ (id)anonymousGuestPlayerWithIdentifier:(id)arg1;
+ (id)anonymousPlayer;
+ (id)automatchPlayer;
+ (id)cacheKeyForPlayerID:(id)arg1;
+ (id)canonicalizedPlayerForInternal:(id)arg1;
+ (id)instanceMethodSignatureForSelector:(SEL)arg1;
+ (bool)instancesRespondToSelector:(SEL)arg1;
+ (bool)isGuestPlayerID:(id)arg1;
+ (void)loadCompletePlayersForPlayers:(id)arg1 completionHandler:(id /* block */)arg2;
+ (void)loadPlayersForIdentifiers:(id)arg1 withCompletionHandler:(id /* block */)arg2;
+ (void)loadPlayersForIdentifiersPrivate:(id)arg1 withCompletionHandler:(id /* block */)arg2;
+ (void)loadPlayersForLegacyIdentifiers:(id)arg1 withCompletionHandler:(id /* block */)arg2;
+ (id)playerFromPlayerID:(id)arg1;
+ (bool)supportsSecureCoding;
+ (id)unknownPlayer;

- (void).cxx_destruct;
- (void)_postChangeNotification;
- (id)acceptedGameInviteFromThisFriend;
- (id)alias;
- (id)automatchedTogether;
- (long long)avatarType;
- (id)cacheKey;
- (void)dealloc;
- (id)description;
- (id)displayName;
- (id)displayNameWithOptions:(unsigned char)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)friendBiDirectional;
- (id)friendLevel;
- (id)friendPlayedNearby;
- (id)friendPlayedWith;
- (id)friends;
- (id)gamePlayerID;
- (bool)hasPhoto;
- (unsigned long long)hash;
- (id)identifierForIDS;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithInternalRepresentation:(id)arg1;
- (id)initiatedGameInviteToThisFriend;
- (id)internal;
- (bool)isEqual:(id)arg1;
- (bool)isFamiliarFriend;
- (bool)isFriendablePlayer;
- (bool)isInContacts;
- (bool)isInvitable;
- (id)lastPlayedGame;
- (void)loadCommonFriends:(bool)arg1 asPlayersWithCompletionHandler:(id /* block */)arg2;
- (void)loadFriendsAsPlayersWithCompletionHandler:(id /* block */)arg1;
- (void)loadFriendsWithFilter:(id)arg1 withComplationHandler:(id /* block */)arg2;
- (void)loadGamesPlayed:(id /* block */)arg1;
- (void)loadGamesPlayedDetailsWithCompletionHandler:(id /* block */)arg1;
- (void)loadGamesPlayedIncludingInstalledGames:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)loadProfileDiscardingStaleData:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)loadProfileWithCompletionHandler:(id /* block */)arg1;
- (void)loadRecentMatchesForGame:(id)arg1 block:(id /* block */)arg2;
- (id)messagesID;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)minimalPlayer;
- (id)playerID;
- (void)postChangeNotification;
- (void)recordScopedIdState:(bool)arg1;
- (id)referenceKey;
- (bool)respondsToSelector:(SEL)arg1;
- (bool)scopedIDsArePersistent;
- (id)searchName;
- (void)setAcceptedGameInviteFromThisFriend:(id)arg1;
- (void)setAutomatchedTogether:(id)arg1;
- (void)setFriendBiDirectional:(id)arg1;
- (void)setFriendLevel:(id)arg1;
- (void)setFriendPlayedNearby:(id)arg1;
- (void)setFriendPlayedWith:(id)arg1;
- (void)setFriends:(id)arg1;
- (void)setInitiatedGameInviteToThisFriend:(id)arg1;
- (void)setInternal:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setWhenString:(id)arg1;
- (id)sortName;
- (struct { long long x1; long long x2; long long x3; long long x4; long long x5; long long x6; long long x7; long long x8; long long x9; })stats;
- (id)teamPlayerID;
- (id)valueForUndefinedKey:(id)arg1;
- (id)whenString;

// Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI

+ (id)monogramQueue;
+ (void)preloadImagesForPlayers:(id)arg1 size:(long long)arg2;
+ (long long)sizeForPhotoSize:(long long)arg1;

- (void)_loadPhotoForSize:(long long)arg1 withCompletionHandler:(id /* block */)arg2;
- (void)_playerAvatarWithSize:(long long)arg1 completionHandler:(id /* block */)arg2;
- (id)avatarImageRenderer;
- (void)clearInMemoryCachedAvatars;
- (id)contact;
- (id)initWithContact:(id)arg1;
- (id)initWithParticipant:(id)arg1 forBundleID:(id)arg2;
- (void)loadPhotoForSize:(long long)arg1 withCompletionHandler:(id /* block */)arg2;
- (void)loadPlayerContactForAvatarControllerWithImageSize:(long long)arg1 handler:(id /* block */)arg2;
- (id)monogramColorIndex;
- (void)monogramImageWithPhotoSize:(long long)arg1 handler:(id /* block */)arg2;
- (id)photoURLForSize:(long long)arg1;
- (id)placeholderImageWithPhotoSize:(long long)arg1;
- (void)playerAvatarDataWithSize:(long long)arg1 completionHandler:(id /* block */)arg2;
- (void)playerAvatarImageWithSize:(long long)arg1 completionHandler:(id /* block */)arg2;
- (void)renderMonogramImageWithPhotoSize:(long long)arg1 monogramString:(id)arg2 handler:(id /* block */)arg3;
- (id)renderingScopeForPhotoSize:(long long)arg1;
- (id)renderingScopeForPhotoSize:(long long)arg1 colorIndex:(long long)arg2;
- (void)setContact:(id)arg1;
- (void)setTuParticipant:(id)arg1;
- (void)setTuParticipant:(id)arg1 forBundleID:(id)arg2;
- (void)showAlertWithTitle:(id)arg1 andMessage:(id)arg2;
- (void)showConfirmationAlertWithTitle:(id)arg1 message:(id)arg2 buttonTitle:(id)arg3 block:(id /* block */)arg4 cancelAction:(id /* block */)arg5;
- (id)stringForMonogram;
- (id)tuParticipant;

@end
