
@interface CLSAestheticsModel : NSObject <CLSSignalModel> {
    double  _aestheticScoreThresholdToBeAestheticallyPrettyGood;
    double  _aestheticScoreThresholdToBeAwesome;
    CLSSignalNode * _failureScoreNode;
    CLSSignalNode * _harmoniousColorScoreNode;
    CLSSignalNode * _immersivenessScoreNode;
    CLSSignalNode * _interestingSubjectScoreNode;
    CLSSignalNode * _intrusiveObjectPresenceScoreNode;
    CLSSignalNode * _livelyColorScoreNode;
    CLSSignalNode * _lowLightNode;
    CLSSignalNode * _noiseScoreNode;
    CLSSignalNode * _overallAestheticScoreNode;
    CLSSignalNode * _pleasantCameraTiltScoreNode;
    CLSSignalNode * _pleasantCompositionScoreNode;
    CLSSignalNode * _pleasantLightingScoreNode;
    CLSSignalNode * _pleasantPatternScoreNode;
    CLSSignalNode * _pleasantPerspectiveScoreNode;
    CLSSignalNode * _pleasantPostProcessingScoreNode;
    CLSSignalNode * _pleasantReflectionsScoreNode;
    CLSSignalNode * _pleasantSymmetryScoreNode;
    CLSSignalNode * _sharplyFocusedSubjectScoreNode;
    CLSSignalNode * _tastefullyBlurredScoreNode;
    unsigned long long  _version;
    CLSSignalNode * _wellChosenSubjectScoreNode;
    CLSSignalNode * _wellFramedSubjectScoreNode;
    CLSSignalNode * _wellTimedShotScoreNode;
}

@property (readonly) double aestheticScoreThresholdToBeAestheticallyPrettyGood;
@property (readonly) double aestheticScoreThresholdToBeAwesome;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) CLSSignalNode *failureScoreNode;
@property (readonly) CLSSignalNode *harmoniousColorScoreNode;
@property (readonly) unsigned long long hash;
@property (readonly) CLSSignalNode *immersivenessScoreNode;
@property (readonly) CLSSignalNode *interestingSubjectScoreNode;
@property (readonly) CLSSignalNode *intrusiveObjectPresenceScoreNode;
@property (readonly) CLSSignalNode *livelyColorScoreNode;
@property (readonly) CLSSignalNode *lowLightNode;
@property (readonly) CLSSignalNode *noiseScoreNode;
@property (readonly) CLSSignalNode *overallAestheticScoreNode;
@property (readonly) CLSSignalNode *pleasantCameraTiltScoreNode;
@property (readonly) CLSSignalNode *pleasantCompositionScoreNode;
@property (readonly) CLSSignalNode *pleasantLightingScoreNode;
@property (readonly) CLSSignalNode *pleasantPatternScoreNode;
@property (readonly) CLSSignalNode *pleasantPerspectiveScoreNode;
@property (readonly) CLSSignalNode *pleasantPostProcessingScoreNode;
@property (readonly) CLSSignalNode *pleasantReflectionsScoreNode;
@property (readonly) CLSSignalNode *pleasantSymmetryScoreNode;
@property (readonly) CLSSignalNode *sharplyFocusedSubjectScoreNode;
@property (readonly) Class superclass;
@property (readonly) CLSSignalNode *tastefullyBlurredScoreNode;
@property (readonly) unsigned long long version;
@property (readonly) CLSSignalNode *wellChosenSubjectScoreNode;
@property (readonly) CLSSignalNode *wellFramedSubjectScoreNode;
@property (readonly) CLSSignalNode *wellTimedShotScoreNode;

+ (unsigned long long)baseSceneAnalysisVersionWithSceneAnalysisVersion:(unsigned long long)arg1;
+ (unsigned long long)latestVersion;
+ (double)legacyAestheticScoreThresholdToBeAestheticallyPrettyGood;
+ (double)legacyAestheticScoreThresholdToBeAwesome;
+ (double)legacyAestheticScoreThresholdToNotBeJunk;
+ (id)name;

- (void).cxx_destruct;
- (double)aestheticScoreThresholdToBeAestheticallyPrettyGood;
- (double)aestheticScoreThresholdToBeAwesome;
- (id)failureScoreNode;
- (id)harmoniousColorScoreNode;
- (id)immersivenessScoreNode;
- (id)initForTesting;
- (id)initWithSceneAnalysisVersion:(unsigned long long)arg1;
- (id)interestingSubjectScoreNode;
- (id)intrusiveObjectPresenceScoreNode;
- (id)livelyColorScoreNode;
- (id)lowLightNode;
- (id)noiseScoreNode;
- (id)overallAestheticScoreNode;
- (id)pleasantCameraTiltScoreNode;
- (id)pleasantCompositionScoreNode;
- (id)pleasantLightingScoreNode;
- (id)pleasantPatternScoreNode;
- (id)pleasantPerspectiveScoreNode;
- (id)pleasantPostProcessingScoreNode;
- (id)pleasantReflectionsScoreNode;
- (id)pleasantSymmetryScoreNode;
- (void)setupVersion31;
- (void)setupVersion32;
- (void)setupVersion86;
- (id)sharplyFocusedSubjectScoreNode;
- (id)tastefullyBlurredScoreNode;
- (unsigned long long)version;
- (id)wellChosenSubjectScoreNode;
- (id)wellFramedSubjectScoreNode;
- (id)wellTimedShotScoreNode;

@end
