
@interface AFModesConfiguration : NSObject <NSCopying, NSSecureCoding> {
    long long  _buttonPressDetected;
    long long  _deviceMotion;
    long long  _deviceOrientation;
    long long  _deviceRaised;
    long long  _faceDetected;
    long long  _flatDevicePosture;
    long long  _isBacklightOn;
    bool  _isConnectedToCarPlay;
    bool  _isDeviceScreenON;
    bool  _isEyesFree;
    bool  _isFlexibleFollowup;
    bool  _isForCarDND;
    bool  _isInAmbient;
    bool  _isInPocket;
    long long  _isInSleepLock;
    long long  _isInTheaterMode;
    long long  _isInWaterLock;
    long long  _isInWorkout;
    bool  _isMapsNavigationActive;
    bool  _isMediaPlaying;
    long long  _isOnWrist;
    bool  _isRequestMadeWithPhysicalDeviceInteraction;
    bool  _isSiriAutoPrompt;
    bool  _isUIFree;
    bool  _isVoiceTriggerRequest;
    bool  _liftToWakeDetected;
    NSString * _modeOverrideValue;
    long long  _touchScreenDetected;
    bool  _userInitiatedWakeDetected;
    bool  _userTypedInSiri;
}

@property (nonatomic, readonly) long long buttonPressDetected;
@property (nonatomic, readonly) long long deviceMotion;
@property (nonatomic, readonly) long long deviceOrientation;
@property (nonatomic, readonly) long long deviceRaised;
@property (nonatomic, readonly) long long faceDetected;
@property (nonatomic, readonly) long long flatDevicePosture;
@property (nonatomic, readonly) long long isBacklightOn;
@property (nonatomic, readonly) bool isConnectedToCarPlay;
@property (nonatomic, readonly) bool isDeviceScreenON;
@property (nonatomic, readonly) bool isEyesFree;
@property (nonatomic, readonly) bool isFlexibleFollowup;
@property (nonatomic, readonly) bool isForCarDND;
@property (nonatomic, readonly) bool isInAmbient;
@property (nonatomic, readonly) bool isInPocket;
@property (nonatomic, readonly) long long isInSleepLock;
@property (nonatomic, readonly) long long isInTheaterMode;
@property (nonatomic, readonly) long long isInWaterLock;
@property (nonatomic, readonly) long long isInWorkout;
@property (nonatomic, readonly) bool isMapsNavigationActive;
@property (nonatomic, readonly) bool isMediaPlaying;
@property (nonatomic, readonly) long long isOnWrist;
@property (nonatomic, readonly) bool isRequestMadeWithPhysicalDeviceInteraction;
@property (nonatomic, readonly) bool isSiriAutoPrompt;
@property (nonatomic, readonly) bool isUIFree;
@property (nonatomic, readonly) bool isVoiceTriggerRequest;
@property (nonatomic, readonly) bool liftToWakeDetected;
@property (nonatomic, readonly, copy) NSString *modeOverrideValue;
@property (nonatomic, readonly) long long touchScreenDetected;
@property (nonatomic, readonly) bool userInitiatedWakeDetected;
@property (nonatomic, readonly) bool userTypedInSiri;

+ (id)newWithBuilder:(id /* block */)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_descriptionWithIndent:(unsigned long long)arg1;
- (long long)buttonPressDetected;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (long long)deviceMotion;
- (long long)deviceOrientation;
- (long long)deviceRaised;
- (void)encodeWithCoder:(id)arg1;
- (long long)faceDetected;
- (long long)flatDevicePosture;
- (unsigned long long)hash;
- (id)init;
- (id)initWithBuilder:(id /* block */)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithIsEyesFree:(bool)arg1 isUIFree:(bool)arg2 isForCarDND:(bool)arg3 isInAmbient:(bool)arg4 isMapsNavigationActive:(bool)arg5 isVoiceTriggerRequest:(bool)arg6 isConnectedToCarPlay:(bool)arg7 isRequestMadeWithPhysicalDeviceInteraction:(bool)arg8 isSiriAutoPrompt:(bool)arg9 isFlexibleFollowup:(bool)arg10 isMediaPlaying:(bool)arg11 userTypedInSiri:(bool)arg12 modeOverrideValue:(id)arg13 isDeviceScreenON:(bool)arg14 isInPocket:(bool)arg15 liftToWakeDetected:(bool)arg16 userInitiatedWakeDetected:(bool)arg17 deviceMotion:(long long)arg18 deviceRaised:(long long)arg19 faceDetected:(long long)arg20 touchScreenDetected:(long long)arg21 buttonPressDetected:(long long)arg22 flatDevicePosture:(long long)arg23 deviceOrientation:(long long)arg24 isInWorkout:(long long)arg25 isBacklightOn:(long long)arg26 isInWaterLock:(long long)arg27 isInSleepLock:(long long)arg28 isInTheaterMode:(long long)arg29 isOnWrist:(long long)arg30;
- (long long)isBacklightOn;
- (bool)isConnectedToCarPlay;
- (bool)isDeviceScreenON;
- (bool)isEqual:(id)arg1;
- (bool)isEyesFree;
- (bool)isFlexibleFollowup;
- (bool)isForCarDND;
- (bool)isInAmbient;
- (bool)isInPocket;
- (long long)isInSleepLock;
- (long long)isInTheaterMode;
- (long long)isInWaterLock;
- (long long)isInWorkout;
- (bool)isMapsNavigationActive;
- (bool)isMediaPlaying;
- (long long)isOnWrist;
- (bool)isRequestMadeWithPhysicalDeviceInteraction;
- (bool)isSiriAutoPrompt;
- (bool)isUIFree;
- (bool)isVoiceTriggerRequest;
- (bool)liftToWakeDetected;
- (id)modeOverrideValue;
- (id)mutatedCopyWithMutator:(id /* block */)arg1;
- (long long)touchScreenDetected;
- (bool)userInitiatedWakeDetected;
- (bool)userTypedInSiri;

@end
