
@interface SBSServer : NSObject <NSXPCListenerDelegate, SBSImplementer, SBSImplementerInternal> {
    NSMutableArray * _clients;
    <SBSHomePodControlsImplementer> * _controlsDelegate;
    <SBSDebugInfoImplementer> * _debugInfoDelegate;
    NSMutableSet * _delegates;
    <SBSPowerMonitorImplementer> * _powerMonitorDelegate;
    <SBSProfilesImplementer> * _profilesDelegate;
    <SBSProximityHandoffUIImplementer> * _proximityHandoffUIDelegate;
    SBSRemoteDeviceReceiver * _receiver;
    NSXPCListener * _serverListener;
    <SBSStereoLeaderRoleImplementer> * _stereoLeaderDelegate;
    <SBSSysdiagnoseImplementer> * _sysdiagnoseDelegate;
    <SBSSystemImplementer> * _systemDelegate;
    <SBSVolumeEventMonitorImplementer> * _volumeEventMonitorDelegate;
}

@property (nonatomic) <SBSHomePodControlsImplementer> *controlsDelegate;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBSDebugInfoImplementer> *debugInfoDelegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) <SBSPowerMonitorImplementer> *powerMonitorDelegate;
@property (nonatomic) <SBSProfilesImplementer> *profilesDelegate;
@property (nonatomic) <SBSProximityHandoffUIImplementer> *proximityHandoffUIDelegate;
@property (nonatomic) <SBSStereoLeaderRoleImplementer> *stereoLeaderDelegate;
@property (readonly) Class superclass;
@property (nonatomic) <SBSSysdiagnoseImplementer> *sysdiagnoseDelegate;
@property (nonatomic) <SBSSystemImplementer> *systemDelegate;
@property (nonatomic) <SBSVolumeEventMonitorImplementer> *volumeEventMonitorDelegate;

+ (bool)_isInternalBuild;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_findConnectionAndSetClientType:(unsigned long long)arg1;
- (id)_gatherXPCClientInfo:(id)arg1;
- (bool)_hasEntitlement:(id)arg1;
- (id)_processNameForPID:(int)arg1;
- (void)clearHomeSWUpdate;
- (void)clearHomeSWUpdateInternal;
- (id)controlsDelegate;
- (id)debugInfoDelegate;
- (void)disassociateCurrentNetwork;
- (void)disassociateCurrentNetworkInternal;
- (void)disassociateNetworkWithName:(id)arg1;
- (void)disassociateNetworkWithNameInternal:(id)arg1;
- (void)fetchLatestEvents:(long long)arg1 completionHandler:(id /* block */)arg2;
- (void)getAllDebugInfo:(id /* block */)arg1;
- (void)getAllDebugInfoInternal:(id /* block */)arg1;
- (void)getAllSyncedAlarmsAndTimers:(id /* block */)arg1;
- (void)getAllSyncedAlarmsAndTimersInternal:(id /* block */)arg1;
- (void)getFeatureFlags:(id /* block */)arg1;
- (void)getFeatureFlagsInternal:(id /* block */)arg1;
- (void)getInstalledProfiles:(id /* block */)arg1;
- (void)getInstalledProfilesInternal:(id /* block */)arg1;
- (void)getLEDInfo:(id /* block */)arg1;
- (void)getLEDInfoInternal:(id /* block */)arg1;
- (void)getPowerEstimateForInterval:(float)arg1 reply:(id /* block */)arg2;
- (void)getPowerEstimateForIntervalInternal:(float)arg1 reply:(id /* block */)arg2;
- (void)getSelectDebugInfo:(id)arg1 reply:(id /* block */)arg2;
- (void)getSelectDebugInfoInternal:(id)arg1 reply:(id /* block */)arg2;
- (void)getTuningInfo:(id /* block */)arg1;
- (void)getTuningInfoInternal:(id /* block */)arg1;
- (void)getUserDefaults:(id /* block */)arg1;
- (void)getUserDefaultsInternal:(id /* block */)arg1;
- (void)getVolume:(id /* block */)arg1;
- (void)getVolumeInternal:(id /* block */)arg1;
- (void)handleClientDisconnection:(id)arg1;
- (void)handoffCancelInternalWithHandoffType:(unsigned long long)arg1;
- (void)handoffCancelWithHandoffType:(unsigned long long)arg1;
- (void)handoffCompleteInternalWithHandoffType:(unsigned long long)arg1;
- (void)handoffCompleteWithHandoffType:(unsigned long long)arg1;
- (void)handoffSetDeviceAsStereoLeader:(bool)arg1 withOptions:(id)arg2;
- (void)handoffStartInternalWithHandoffType:(unsigned long long)arg1;
- (void)handoffStartWithArtworkColors:(id)arg1 handoffType:(unsigned long long)arg2;
- (void)handoffStartWithArtworkColorsInternal:(id)arg1 handoffType:(unsigned long long)arg2;
- (void)handoffStartWithHandoffType:(unsigned long long)arg1;
- (void)handoffUpdateIntensity:(float)arg1 handoffType:(unsigned long long)arg2;
- (void)handoffUpdateIntensityInternal:(float)arg1 handoffType:(unsigned long long)arg2;
- (void)identifyWithOptions:(id)arg1;
- (void)identifyWithOptionsInternal:(id)arg1;
- (id)init;
- (void)injectSWUpdateToHome:(id)arg1;
- (void)injectSWUpdateToHomeInternal:(id)arg1;
- (void)installProfileData:(id)arg1 completion:(id /* block */)arg2;
- (void)installProfileDataInternal:(id)arg1 completion:(id /* block */)arg2;
- (void)intercomWithOptions:(id)arg1;
- (void)intercomWithOptionsInternal:(id)arg1;
- (void)isDeviceStereoFollower:(id /* block */)arg1;
- (void)isDeviceStereoFollowerInternal:(id /* block */)arg1;
- (bool)isMediaAlarm:(id)arg1;
- (bool)isMediaAlarmInternal:(id)arg1;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)obliterate:(id)arg1;
- (void)obliterateInternal:(id)arg1;
- (void)playTone:(unsigned int)arg1;
- (void)playToneInternal:(unsigned int)arg1;
- (id)powerMonitorDelegate;
- (id)profilesDelegate;
- (void)proximityHandoffCancelled;
- (void)proximityHandoffCompleted;
- (void)proximityHandoffInactive;
- (void)proximityHandoffStarted;
- (id)proximityHandoffUIDelegate;
- (void)proximityHandoffUpdating;
- (void)reboot:(id)arg1;
- (void)rebootInternal:(id)arg1;
- (void)removeProfileByIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)removeProfileByIdentifierInternal:(id)arg1 completion:(id /* block */)arg2;
- (void)render:(id)arg1;
- (void)renderInternal:(id)arg1;
- (void)requestDeferredReboot;
- (void)requestDeferredRebootInternal;
- (void)resetAllUserDefaults;
- (void)resetAllUserDefaultsInternal;
- (void)resetUserDefault:(id)arg1;
- (void)resetUserDefaultInternal:(id)arg1;
- (void)sendButtonCommand:(id)arg1;
- (void)sendButtonCommandInternal:(id)arg1;
- (void)sendLEDCommand:(id)arg1;
- (void)sendLEDCommandInternal:(id)arg1;
- (void)setBootSpinner:(bool)arg1;
- (void)setBootSpinnerInternal:(bool)arg1;
- (void)setControlsDelegate:(id)arg1;
- (void)setDebugInfoDelegate:(id)arg1;
- (void)setDeviceAsStereoLeader:(bool)arg1 withOptions:(id)arg2;
- (void)setDeviceAsStereoLeaderInternal:(bool)arg1 withOptions:(id)arg2;
- (void)setFeatureFlags:(id)arg1;
- (void)setFeatureFlagsInternal:(id)arg1;
- (void)setHomeUpdateState:(long long)arg1;
- (void)setHomeUpdateStateInternal:(long long)arg1;
- (void)setLEDContents:(id)arg1;
- (void)setLEDContentsInternal:(id)arg1;
- (void)setPowerMonitorDelegate:(id)arg1;
- (void)setProfilesDelegate:(id)arg1;
- (void)setProximityHandoffUIDelegate:(id)arg1;
- (void)setStereoLeaderDelegate:(id)arg1;
- (void)setSysdiagnoseDelegate:(id)arg1;
- (void)setSystemDelegate:(id)arg1;
- (void)setTuningInfoOnBox:(id)arg1 at:(id)arg2 withValue:(float)arg3;
- (void)setTuningInfoOnBoxInternal:(id)arg1 at:(id)arg2 withValue:(float)arg3;
- (void)setTurnOffBrightnessFactor:(bool)arg1;
- (void)setUserDefaults:(id)arg1 withValue:(id)arg2;
- (void)setUserDefaultsInternal:(id)arg1 withValue:(id)arg2;
- (void)setVolume:(float)arg1;
- (void)setVolumeEventMonitorDelegate:(id)arg1;
- (void)setVolumeInternal:(float)arg1;
- (void)setWifiEnabled:(bool)arg1;
- (void)setWifiEnabledInternal:(bool)arg1;
- (void)siriSay:(id)arg1;
- (void)siriSayInternal:(id)arg1;
- (id)stereoLeaderDelegate;
- (void)stopTone:(unsigned int)arg1;
- (void)stopToneInternal:(unsigned int)arg1;
- (void)suScanForSoftwareUpdate;
- (void)suScanForSoftwareUpdateInternal;
- (id)sysdiagnoseDelegate;
- (void)sysdiagnoseHasStarted:(bool)arg1;
- (void)sysdiagnoseHasStartedInternal:(bool)arg1;
- (id)systemDelegate;
- (void)triggerWiFiCoreCapture:(id)arg1;
- (void)triggerWiFiCoreCaptureInternal:(id)arg1;
- (id)volumeEventMonitorDelegate;

@end
