
@interface PKAccountBillPaymentViewController : UIViewController <PKAccountAutomaticPaymentsControllerDelegate, PKAccountBillPaymentAmountDescriptionViewDelegate, PKAccountBillPaymentConfirmationViewControllerDelegate, PKAccountBillPaymentControllerDelegate, PKAccountServiceAccountResolutionControllerDelegate, PKAddBankAccountInformationViewControllerDelegate, PKBillPaymentRingViewDataSource, PKBillPaymentRingViewDelegate, UIScrollViewDelegate, _PKVisibilityBackdropViewDelegate> {
    CLInUseAssertion * _CLInUse;
    PKAccount * _account;
    PKAccountServiceAccountResolutionController * _accountResolutionController;
    PKAccountUserCollection * _accountUserCollection;
    PKAddBankAccountInformationViewController * _addBankAccountViewController;
    PKAccountBillPaymentAmountDescriptionView * _amountDescriptionView;
    NSNumberFormatter * _amountFormatter;
    NSDecimalNumber * _apr;
    PKAccountBillPaymentController * _billPaymentCoordinator;
    _PKVisibilityBackdropView * _blurringView;
    bool  _buttonsArePayButtons;
    NSMutableDictionary * _cachedInterestResults;
    PKAccountServiceAccountResolutionCofiguration * _configuration;
    unsigned long long  _featuredViewState;
    bool  _hasAnimatedRing;
    bool  _inLayoutSubviews;
    NSArray * _installmentPlans;
    PKCompoundInterestCalculator * _interestCalculator;
    NSDateFormatter * _interestDateFormatter;
    unsigned long long  _interstitialState;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _keyboardFrame;
    bool  _keyboardVisible;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _lastKeyboardFrame;
    <PKAccountBillPaymentObserver> * _observer;
    bool  _payButtonsEnabled;
    bool  _performingAction;
    PKCreditAccountSummary * _previousAccountSummary;
    PKContinuousButton * _primaryButton;
    UIImageView * _productHeroView;
    PKBillPaymentRingView * _ringView;
    UITapGestureRecognizer * _ringViewTapRecognizer;
    UIScrollView * _scrollView;
    PKContinuousButton * _secondaryButton;
    bool  _shouldEnablePayLaterButton;
    bool  _showKeyboard;
    NSMutableDictionary * _smallRingInterestAttributes;
    NSDictionary * _smallRingInterestDateAttributes;
    UILabel * _smallRingInterestLabel;
    UILabel * _subtitleLabel;
    PKBillPaymentSuggestedAmountController * _suggestedAmountController;
    PKBillPaymentSuggestedAmountList * _suggestionList;
    UIButton * _tertiaryButton;
    UILabel * _titleLabel;
    PKTransactionSource * _transactionSource;
    bool  _usesAccessibilityLayout;
    bool  _usesLargestAccessibilityLayout;
    bool  _viewIsEnabled;
    unsigned char  _visibility;
}

@property (nonatomic, readonly) PKAccount *account;
@property (nonatomic, readonly) PKAccountUserCollection *accountUserCollection;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) <PKAccountBillPaymentObserver> *observer;
@property (readonly) Class superclass;
@property (nonatomic, readonly) PKTransactionSource *transactionSource;

+ (void)_billPaymentViewControllerForAccount:(id)arg1 accountUserCollection:(id)arg2 transactionSource:(id)arg3 configuration:(id)arg4 withCompletion:(id /* block */)arg5;
+ (id)alertControllerForDisplayableError:(id)arg1;
+ (id)alertControllerForDisplayableError:(id)arg1 handler:(id /* block */)arg2;
+ (id)backgroundColor;
+ (void)billPaymentViewControllerForAccount:(id)arg1 accountUserCollection:(id)arg2 transactionSource:(id)arg3 configuration:(id)arg4 withCompletion:(id /* block */)arg5;
+ (bool)canPayBillForAccount:(id)arg1 displayableError:(id*)arg2;
+ (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })contentMargins;
+ (id)displayableErrorForAccount:(id)arg1 reason:(unsigned long long)arg2;
+ (double)ringTopMargin;
+ (struct CGSize { double x1; double x2; })smallRingSizeWithAccessibilityLayout:(bool)arg1;
+ (double)smallRingTopMargin;

- (void).cxx_destruct;
- (void)_accountDidChange:(id)arg1;
- (id)_addBankAccountInformationViewController;
- (void)_cancelButtonTapped:(id)arg1;
- (void)_configureProductHeroView;
- (void)_contactSupportButtonTapped:(id)arg1;
- (void)_dismissViewControllerWithSuccess:(bool)arg1;
- (id)_interestForAmount:(id)arg1;
- (bool)_interestLabelIsOutsideSmallRing;
- (id)_interestPostDate;
- (id)_interestStringForAmount:(id)arg1;
- (void)_interstitialButtonTapped:(id)arg1;
- (void)_layoutFooterWithState:(struct { double x1; double x2; struct CGSize { double x_3_1_1; double x_3_1_2; } x3; double x4; double x5; bool x6; })arg1;
- (struct CGSize { double x1; double x2; })_layoutScrollViewWithContentWidth:(double)arg1;
- (void)_payLaterButtonTapped:(id)arg1;
- (void)_payNowButtonTapped:(id)arg1;
- (id)_paymentAmount;
- (void)_performBillPaymentWithAmount:(id)arg1 billPaymentSuggestedAmountDataEvent:(id)arg2;
- (void)_presentAddBankAccount;
- (void)_presentAlertControllerForError:(id)arg1;
- (void)_reportEventForPassIfNecessary:(id)arg1;
- (id)_roundedInterestForAmount:(id)arg1;
- (void)_setAccount:(id)arg1;
- (void)_setEnabled:(bool)arg1;
- (void)_setPayButtonsEnabled:(bool)arg1;
- (void)_setShowKeyboard:(bool)arg1;
- (void)_setupAmountDescriptionViewForInterstitial;
- (void)_showKeyboardButtonTapped:(id)arg1;
- (void)_showOrHideKeypad;
- (void)_tappedSmallRingView:(id)arg1;
- (id)_title;
- (void)_updateForShowKeyboardAnimated:(bool)arg1;
- (void)_updateInterestString;
- (void)_updateLayoutForKeyboardAction:(id /* block */)arg1;
- (void)_updateNavigationTitle;
- (void)_updatePayNowButtonTitleWithAmount:(id)arg1;
- (void)_updateSubtitle;
- (id)account;
- (void)accountAutomaticPaymentsController:(id)arg1 didSchedulePayment:(id)arg2;
- (void)accountAutomaticPaymentsControllerDidSelectSetupCompletionDone:(id)arg1 viewController:(id)arg2;
- (void)accountBillPaymentController:(id)arg1 hasChangedState:(unsigned long long)arg2 error:(id)arg3 updatedAccount:(id)arg4;
- (void)accountServiceAccountResolutionController:(id)arg1 requestsPresentViewController:(id)arg2 animated:(bool)arg3;
- (id)accountUserCollection;
- (void)addBankAccountInformationViewController:(id)arg1 didAddFundingSource:(id)arg2;
- (void)addBankAccountInformationViewControllerDidFinish:(id)arg1;
- (void)bankAccountInformationViewControllerChangedBankAccountInformation:(id)arg1;
- (void)billPaymentAmountDescriptionView:(id)arg1 hasChangedAmount:(id)arg2 isValidAmount:(bool)arg3;
- (void)billPaymentAmountDescriptionViewHasTappedLearnMore:(id)arg1;
- (id)billPaymentConfirmationInterestForPaymentAmount:(id)arg1;
- (id)billPaymentConfirmationInterestStringForPaymentAmount:(id)arg1;
- (void)billPaymentRingView:(id)arg1 amountChanged:(id)arg2;
- (id)billPaymentRingView:(id)arg1 bottomCurvedTextForSuggestedAmount:(id)arg2;
- (id)billPaymentRingView:(id)arg1 interestTextForAmount:(id)arg2;
- (void)billPaymentRingView:(id)arg1 selectedSuggestedAmount:(id)arg2 selectedSuggestedAmountIsTarget:(bool)arg3 userInitiatedChange:(bool)arg4;
- (id)billPaymentRingView:(id)arg1 topCurvedTextForSuggestedAmount:(id)arg2;
- (id)billPaymentRingViewZeroInterestText:(id)arg1;
- (void)dealloc;
- (id)disabledBottomCurvedTextForBillPaymentRingView:(id)arg1;
- (id)disabledTopCurvedTextForBillPaymentRingView:(id)arg1;
- (id)initWithAccount:(id)arg1 accountUserCollection:(id)arg2 transactionSource:(id)arg3 suggestedAmountController:(id)arg4 configuration:(id)arg5 interstitalState:(unsigned long long)arg6;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithSuggestedAmountController:(id)arg1 account:(id)arg2 accountUserCollection:(id)arg3 transactionSource:(id)arg4 configuration:(id)arg5 interstitialState:(unsigned long long)arg6;
- (id)initWithSuggestedAmountController:(id)arg1 transactionSource:(id)arg2;
- (void)keyboardWillChange:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)loadView;
- (id)observer;
- (id)presentationSceneIdentifierForAccountAutomaticPaymentsController:(id)arg1;
- (id)presentationSceneIdentifierForAccountBillPaymentController:(id)arg1;
- (void)recomputeCategoryVisualizationMangitudesForPassUniqueID:(id)arg1 style:(long long)arg2 paymentService:(id)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setObserver:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)transactionSource;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (void)viewWillLayoutSubviews;
- (long long)visibilityBackdropView:(id)arg1 preferredStyleForTraitCollection:(id)arg2;

@end
