
@interface _INPBTask : PBCodable <NSCopying, NSSecureCoding, _INPBTask> {
    _INPBContactEventTrigger * _contactEventTrigger;
    _INPBDateTime * _createdDateTime;
    struct { 
        unsigned int priority : 1; 
        unsigned int status : 1; 
        unsigned int taskReference : 1; 
        unsigned int taskType : 1; 
    }  _has;
    NSString * _identifier;
    _INPBDateTime * _modifiedDateTime;
    NSString * _parentIdentifier;
    int  _priority;
    _INPBSpatialEventTrigger * _spatialEventTrigger;
    int  _status;
    int  _taskReference;
    int  _taskType;
    _INPBTemporalEventTrigger * _temporalEventTrigger;
    _INPBDataString * _title;
}

@property (nonatomic, retain) _INPBContactEventTrigger *contactEventTrigger;
@property (nonatomic, retain) _INPBDateTime *createdDateTime;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasContactEventTrigger;
@property (nonatomic, readonly) bool hasCreatedDateTime;
@property (nonatomic, readonly) bool hasIdentifier;
@property (nonatomic, readonly) bool hasModifiedDateTime;
@property (nonatomic, readonly) bool hasParentIdentifier;
@property (nonatomic) bool hasPriority;
@property (nonatomic, readonly) bool hasSpatialEventTrigger;
@property (nonatomic) bool hasStatus;
@property (nonatomic) bool hasTaskReference;
@property (nonatomic) bool hasTaskType;
@property (nonatomic, readonly) bool hasTemporalEventTrigger;
@property (nonatomic, readonly) bool hasTitle;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, retain) _INPBDateTime *modifiedDateTime;
@property (nonatomic, copy) NSString *parentIdentifier;
@property (nonatomic) int priority;
@property (nonatomic, retain) _INPBSpatialEventTrigger *spatialEventTrigger;
@property (nonatomic) int status;
@property (readonly) Class superclass;
@property (nonatomic) int taskReference;
@property (nonatomic) int taskType;
@property (nonatomic, retain) _INPBTemporalEventTrigger *temporalEventTrigger;
@property (nonatomic, retain) _INPBDataString *title;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (int)StringAsPriority:(id)arg1;
- (int)StringAsStatus:(id)arg1;
- (int)StringAsTaskReference:(id)arg1;
- (int)StringAsTaskType:(id)arg1;
- (id)contactEventTrigger;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)createdDateTime;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasContactEventTrigger;
- (bool)hasCreatedDateTime;
- (bool)hasIdentifier;
- (bool)hasModifiedDateTime;
- (bool)hasParentIdentifier;
- (bool)hasPriority;
- (bool)hasSpatialEventTrigger;
- (bool)hasStatus;
- (bool)hasTaskReference;
- (bool)hasTaskType;
- (bool)hasTemporalEventTrigger;
- (bool)hasTitle;
- (unsigned long long)hash;
- (id)identifier;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)modifiedDateTime;
- (id)parentIdentifier;
- (int)priority;
- (id)priorityAsString:(int)arg1;
- (bool)readFrom:(id)arg1;
- (void)setContactEventTrigger:(id)arg1;
- (void)setCreatedDateTime:(id)arg1;
- (void)setHasPriority:(bool)arg1;
- (void)setHasStatus:(bool)arg1;
- (void)setHasTaskReference:(bool)arg1;
- (void)setHasTaskType:(bool)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setModifiedDateTime:(id)arg1;
- (void)setParentIdentifier:(id)arg1;
- (void)setPriority:(int)arg1;
- (void)setSpatialEventTrigger:(id)arg1;
- (void)setStatus:(int)arg1;
- (void)setTaskReference:(int)arg1;
- (void)setTaskType:(int)arg1;
- (void)setTemporalEventTrigger:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)spatialEventTrigger;
- (int)status;
- (id)statusAsString:(int)arg1;
- (int)taskReference;
- (id)taskReferenceAsString:(int)arg1;
- (int)taskType;
- (id)taskTypeAsString:(int)arg1;
- (id)temporalEventTrigger;
- (id)title;
- (void)writeTo:(id)arg1;

@end
