
@interface PGGraphMomentNode : PGGraphOptimizedNode <PGAssetCollectionFeature, PGEventEnrichment, PGGraphFullEvent, PGGraphPhotoEvent, PGGraphRelatableEvent> {
    double  _behavioralScore;
    unsigned int  _containsBetterScoringAsset;
    unsigned int  _containsNonJunkAssets;
    double  _contentScore;
    NSString * _encodedCLIPFeatureVector;
    double  _facesProcessedRatio;
    bool  _happensAtSensitiveLocation;
    unsigned int  _hasAssetsWithInterestingScenes;
    unsigned int  _hasHigherThanImprovedAssets;
    double  _inhabitationScore;
    unsigned int  _isInteresting;
    unsigned int  _isInterestingWithAlternateJunking;
    unsigned int  _isSmartInteresting;
    double  _localEndTimestamp;
    NSString * _localIdentifier;
    double  _localStartTimestamp;
    NSString * _name;
    unsigned int  _numberOfAssets;
    unsigned long long  _numberOfAssetsInExtendedCuration;
    unsigned int  _numberOfAssetsWithPersons;
    unsigned int  _numberOfPersonNodes;
    unsigned int  _numberOfRegularGemAssets;
    unsigned int  _numberOfShinyGemAssets;
    double  _scenesProcessedRatio;
    unsigned short  _sharingComposition;
    unsigned int  _totalNumberOfPersons;
    double  _universalEndTimestamp;
    double  _universalStartTimestamp;
}

@property (readonly) NSString *UUID;
@property (readonly) double behavioralScore;
@property (readonly) MAFloatVector *clipFeatureVector;
@property (nonatomic, readonly) PGGraphMomentNodeCollection *collection;
@property (readonly) bool containsBetterScoringAsset;
@property (readonly) bool containsNonJunkAssets;
@property (readonly) double contentScore;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) <PGGraphEventCollection> *eventCollection;
@property (readonly) double facesProcessedRatio;
@property (nonatomic, readonly) NSString *featureIdentifier;
@property (nonatomic, readonly) unsigned long long featureType;
@property (readonly) NSSet *frequentLocationNodes;
@property (readonly) bool happensAtFrequentLocation;
@property (readonly) bool happensAtSensitiveLocation;
@property (readonly) bool hasAddressNodes;
@property (readonly) bool hasAssetsWithInterestingScenes;
@property (readonly) bool hasEnoughFacesProcessed;
@property (readonly) bool hasEnoughScenesProcessed;
@property (readonly) bool hasHigherThanImprovedAssets;
@property (readonly) bool hasLocation;
@property (readonly) bool hasMeanings;
@property (readonly) unsigned long long hash;
@property (readonly) PGGraphHighlightGroupNode *highlightGroupNode;
@property (readonly) PGGraphHighlightNode *highlightNode;
@property (readonly) double inhabitationScore;
@property (readonly) bool isAggregation;
@property (readonly) bool isInteresting;
@property (readonly) bool isInterestingForMemories;
@property (readonly) bool isInterestingWithAlternateJunking;
@property (readonly) bool isLongTrip;
@property (readonly) bool isMeaningful;
@property (readonly) bool isPartOfTrip;
@property (readonly) bool isShortTrip;
@property (readonly) bool isSmartInteresting;
@property (readonly) bool isTrip;
@property (readonly) NSDictionary *jsonDescription;
@property (readonly) NSDate *localEndDate;
@property (readonly) NSString *localIdentifier;
@property (readonly) NSDate *localStartDate;
@property (readonly) unsigned long long locationMobilityType;
@property (readonly) NSString *name;
@property (readonly) PGGraphMomentNode *nextMomentNode;
@property (readonly) unsigned long long numberOfAssets;
@property (readonly) unsigned long long numberOfAssetsInExtendedCuration;
@property (readonly) unsigned long long numberOfAssetsWithPersons;
@property (readonly) unsigned long long numberOfRegularGemAssets;
@property (readonly) unsigned long long numberOfShinyGemAssets;
@property (readonly) bool petIsPresent;
@property (readonly) PGGraphMomentNode *previousMomentNode;
@property (readonly) <PGGraphEventCollection> *scenedEventCollection;
@property (readonly) double scenesProcessedRatio;
@property (readonly) unsigned short sharingComposition;
@property (readonly) Class superclass;
@property (readonly) double timestampUTCEnd;
@property (readonly) double timestampUTCStart;
@property (readonly) unsigned long long totalNumberOfPersons;
@property (readonly) NSDate *universalEndDate;
@property (readonly) NSDate *universalStartDate;
@property (nonatomic, readonly) NSString *uuid;

+ (id)addressOfMoment;
+ (id)alternativeMeaningOfMoment;
+ (id)anniversaryPersonInMoment;
+ (id)authorOfMoment;
+ (id)birthdayPersonInMoment;
+ (long long)breakoutOfRoutineTypeWithNeighborScore:(double)arg1;
+ (id)businessOfMoment;
+ (id)celebratedHolidayOfMoment;
+ (id)cityOfMoment;
+ (id)consolidatedPersonInMoment;
+ (id)consolidatedPersonPresentInAssets;
+ (id)contentBasedPropertiesWithMoment:(id)arg1;
+ (id)contentScoreSortDescriptors;
+ (id)dateOfMoment;
+ (id)featureOfMoment;
+ (id)filter;
+ (id)filterEncodedCLIPFeatureVectorNotEmpty;
+ (id)filterEnoughFacesProcessed;
+ (id)filterEnoughScenesProcessed;
+ (id)filterHappeningAtSensitiveLocation;
+ (id)filterWithLocalDateInterval:(id)arg1;
+ (id)filterWithTotalNumberOfPersonsGreaterThanOrEqualTo:(unsigned long long)arg1;
+ (id)filterWithUUID:(id)arg1;
+ (id)filterWithUUIDs:(id)arg1;
+ (id)filterWithUniversalDateInterval:(id)arg1;
+ (id)firstAndLastMomentNodesInMomentNodes:(id)arg1;
+ (id)frequentLocationOfMoment;
+ (id)highlightOfMoment;
+ (id)improvedPOIOfMoment;
+ (id)inclusivePathFromTargetNodeDomain:(unsigned short)arg1 withName:(id)arg2;
+ (id)inclusivePathToTargetNodeDomain:(unsigned short)arg1 withName:(id)arg2;
+ (id)interestingFilter;
+ (id)interestingWithAlternateJunkingFilter;
+ (id)meaningHierarchyOfMoment;
+ (id)meaningOfMoment;
+ (id)memoryOfMoment;
+ (id)mobilityOfMoment;
+ (id)momentWithOnlyPrivateAssetsOfMoment;
+ (id)momentWithOnlySharedAssetsOfMoment;
+ (id)momentWithPrivateAndSharedAssetsOfMoment;
+ (id)momentWithPrivateAssetsOfMoment;
+ (id)momentWithSharedAssetsOfMoment;
+ (id)nextMomentOfMoment;
+ (id)partOfDayOfMoment;
+ (id)pathFromMoment;
+ (id)pathFromTargetNodeDomain:(unsigned short)arg1;
+ (id)pathToMoment;
+ (id)pathToTargetNodeDomain:(unsigned short)arg1;
+ (id)personActivityMeaningOfMoment;
+ (id)personExcludingMeInMoment;
+ (id)personInMoment;
+ (id)personInProximityInMoment;
+ (id)personPhysicallyPresentInMoment;
+ (id)petPresentInMoment;
+ (id)poiOfMoment;
+ (id)poiWithNonzeroConfidenceOfMoment;
+ (id)poiWithNonzeroConfidenceOfMomentWithHasLegacyWeights:(bool)arg1;
+ (id)preciseAddressOfMoment;
+ (id)previousMomentOfMoment;
+ (id)propertiesWithMoment:(id)arg1;
+ (id)publicEventOfMoment;
+ (id)reliableMeaningOfMoment;
+ (id)reliableSceneOfMoment;
+ (id)remoteAddressOfMoment;
+ (id)roiOfMoment;
+ (id)roiWithNonzeroConfidenceOfMoment;
+ (id)roiWithNonzeroConfidenceOfMomentWithHasLegacyWeights:(bool)arg1;
+ (id)sceneOfMoment;
+ (id)scoreSortDescriptors;
+ (void)setLocalEndDate:(id)arg1 onMomentNodeForIdentifier:(unsigned long long)arg2 inGraph:(id)arg3;
+ (void)setLocalStartDate:(id)arg1 onMomentNodeForIdentifier:(unsigned long long)arg2 inGraph:(id)arg3;
+ (void)setNumberOfAssets:(unsigned long long)arg1 onMomentNodeForIdentifier:(unsigned long long)arg2 inGraph:(id)arg3;
+ (void)setUniversalEndDate:(id)arg1 onMomentNodeForIdentifier:(unsigned long long)arg2 inGraph:(id)arg3;
+ (void)setUniversalStartDate:(id)arg1 onMomentNodeForIdentifier:(unsigned long long)arg2 inGraph:(id)arg3;
+ (id)significantPartOfDayOfMoment;
+ (id)significantPartOfDayOfMomentWithHasLegacyWeights:(bool)arg1;
+ (id)smartInterestingFilter;
+ (id)socialGroupInMoment;
+ (id)specialPOIOfMoment;
+ (id)weekdayOfMoment;
+ (id)weekendOfMoment;

- (void).cxx_destruct;
- (id)UUID;
- (long long)_compareToMomentNode:(id)arg1 withSortDescriptors:(id)arg2;
- (void)_enumeratePartsOfDayWithThreshold:(double)arg1 usingBlock:(id /* block */)arg2;
- (unsigned long long)_partsOfDayWithThreshold:(double)arg1;
- (id)addressEdges;
- (id)addressNodes;
- (id)alternativeMeaningLabels;
- (id)alternativeMeaningLabelsIncludingParents;
- (id)alternativeMeaningNodes;
- (id)anniversaryPersonNodes;
- (id)associatedNodesForRemoval;
- (double)behavioralScore;
- (id)bestAddressNode;
- (struct CLLocationCoordinate2D { double x1; double x2; })bestLocationCoordinate;
- (id)birthdayPersonNodes;
- (id)businessNodes;
- (id)businessedEvent;
- (id)celebratedHolidayNodes;
- (id)changingPropertiesWithProperties:(id)arg1;
- (id)cityNodes;
- (id)clipFeatureVector;
- (id)collection;
- (id)connectedEventsWithTargetDomain:(unsigned short)arg1;
- (id)consolidatedPersonNodes;
- (id)consolidatedPersonNodesPresentInAssets;
- (bool)containsBetterScoringAsset;
- (bool)containsNonJunkAssets;
- (double)contentScore;
- (id)countryNodes;
- (id)dateNodes;
- (id)debugDictionary;
- (id)description;
- (unsigned short)domain;
- (id)earlierMomentNode:(id)arg1;
- (bool)endsBeforeLocalDate:(id)arg1;
- (id)enrichableEvent;
- (void)enumerateAddressEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateAlternativeMeaningEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateBusinessEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateBusinessNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateBusinessesUsingBlock:(id /* block */)arg1;
- (void)enumerateCelebratedHolidayNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateConsolidatedAddressesUsingBlock:(id /* block */)arg1;
- (void)enumerateDateEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateDateNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateFrequentLocationNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateHighlightNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateMeaningEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateMeaningEdgesAndNodesWithDomain:(unsigned short)arg1 block:(id /* block */)arg2;
- (void)enumerateMeaningNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateMeaningfulEventsUsingBlock:(id /* block */)arg1;
- (void)enumeratePOIEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePOINodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePartOfDayEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePartsOfDayUsingBlock:(id /* block */)arg1;
- (void)enumeratePersonEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePersonNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePetNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePreciseAddressEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePreciseAddressNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePublicEventEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumeratePublicEventNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateROIEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateROINodesUsingBlock:(id /* block */)arg1;
- (void)enumerateReliableMeaningNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateRemoteAddressNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateSceneEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateSceneNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateSignificantPartsOfDayUsingBlock:(id /* block */)arg1;
- (void)enumerateSocialGroupEdgesAndNodesUsingBlock:(id /* block */)arg1;
- (void)enumerateSocialGroupNodesUsingBlock:(id /* block */)arg1;
- (id)eventCollection;
- (id)eventEnrichmentMomentNodes;
- (id)eventEnrichmentSortedMomentNodes;
- (id)eventSortedMomentNodes;
- (double)facesProcessedRatio;
- (id)featureIdentifier;
- (unsigned long long)featureType;
- (id)fetchAssetCollectionInPhotoLibrary:(id)arg1;
- (id)frequentLocationNodes;
- (double)graphScore;
- (bool)happensAtFrequentLocation;
- (bool)happensAtSensitiveLocation;
- (bool)happensPartiallyAtHomeOfPersonNodes:(id)arg1;
- (bool)happensPartiallyAtHomeOrWorkOfPersonNodes:(id)arg1;
- (bool)happensPartiallyAtWorkOfPersonNodes:(id)arg1;
- (bool)hasAddressNodes;
- (bool)hasAssetsWithInterestingScenes;
- (bool)hasEnoughFacesProcessed;
- (bool)hasEnoughScenesProcessed;
- (bool)hasHigherThanImprovedAssets;
- (bool)hasLocation;
- (bool)hasMeanings;
- (bool)hasPeopleCountingMe:(bool)arg1;
- (bool)hasPersonNodes;
- (bool)hasProperties:(id)arg1;
- (id)highlightGroupNode;
- (id)highlightNode;
- (id)holidayNodes;
- (double)inhabitationScore;
- (id)initFromMoment:(id)arg1;
- (id)initWithLabel:(id)arg1 domain:(unsigned short)arg2 properties:(id)arg3;
- (bool)isAggregation;
- (bool)isInteresting;
- (bool)isInterestingForMemories;
- (bool)isInterestingWithAlternateJunking;
- (bool)isLongTrip;
- (bool)isMeaningful;
- (bool)isPartOfTrip;
- (bool)isShortTrip;
- (bool)isSmartInteresting;
- (bool)isTrip;
- (bool)isWeekend;
- (id)jsonDescription;
- (id)keywordsForRelatedType:(unsigned long long)arg1 focusOnNodes:(id)arg2;
- (id)label;
- (id)lastWeekendMoments;
- (id)laterMomentNode:(id)arg1;
- (id)localEndDate;
- (id)localIdentifier;
- (id)localStartDate;
- (id)locatedEvent;
- (unsigned long long)locationMobilityType;
- (id)meaningLabels;
- (id)meaningLabelsIncludingParents;
- (id)meaningNodes;
- (double)meaningScore;
- (id)meaningfulEvent;
- (id)name;
- (id)naturalLanguageFeatures;
- (id)nextMomentNode;
- (unsigned long long)numberOfAssets;
- (unsigned long long)numberOfAssetsInExtendedCuration;
- (unsigned long long)numberOfAssetsWithPersons;
- (unsigned long long)numberOfRegularGemAssets;
- (unsigned long long)numberOfShinyGemAssets;
- (unsigned long long)partsOfDay;
- (id)peopledEvent;
- (id)personNodes;
- (id)personNodesInProximity;
- (bool)petIsPresent;
- (id)petNodes;
- (id)photoEvent;
- (id)poiNodes;
- (id)preciseAddressEdges;
- (id)previousMomentNode;
- (id)propertyDictionary;
- (id)propertyForKey:(id)arg1;
- (id)publicEventNodes;
- (id)relatableEvent;
- (id)relatableNode;
- (id)reliableMeaningLabels;
- (id)remoteAddressEdges;
- (id)roiNodes;
- (id)sameMonthMoments;
- (id)sameWeekendMoments;
- (id)scenedEvent;
- (id)scenedEventCollection;
- (double)scenesProcessedRatio;
- (id)seasonNodes;
- (void)setLocalProperties:(id)arg1;
- (unsigned short)sharingComposition;
- (unsigned long long)significantPartsOfDay;
- (id)socialGroupNodes;
- (bool)startsAfterLocalDate:(id)arg1;
- (id)timedEvent;
- (double)timestampUTCEnd;
- (double)timestampUTCStart;
- (unsigned long long)totalNumberOfPersons;
- (id)universalEndDate;
- (id)universalStartDate;
- (id)uuid;
- (id)weekendNode;
- (double)weightForMoment:(id)arg1;

@end
