
@interface GKDashboardChallengePlayerPickerViewController : GKDashboardCollectionViewController <GKComposeControllerDelegate, UISearchBarDelegate, UITextFieldDelegate> {
    GKChallenge * _challenge;
    id /* block */  _completionHandler;
    UIViewController * _composeController;
    NSLayoutConstraint * _customizeMessageBottomConstraint;
    UIBarButtonItem * _customizeMessageButton;
    UILabel * _descriptionLabel;
    double  _initialCustomizeMessageBottomConstraintConstant;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _initialInsets;
    NSArray * _initiallySelectedPlayers;
    NSString * _message;
    UITextField * _messageField;
    UIView * _scrollingHeader;
    NSLayoutConstraint * _scrollingHeaderTopConstraint;
    double  _scrollingHeaderTopConstraintConstant;
    UIButton * _sendButton;
    bool  _shouldApplyInitialOffset;
    bool  _shouldIgnoreClearSelection;
}

@property (nonatomic, retain) GKChallenge *challenge;
@property (nonatomic, copy) id /* block */ completionHandler;
@property (nonatomic, retain) UIViewController *composeController;
@property (nonatomic) NSLayoutConstraint *customizeMessageBottomConstraint;
@property (nonatomic) UIBarButtonItem *customizeMessageButton;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) UILabel *descriptionLabel;
@property (readonly) unsigned long long hash;
@property (nonatomic) double initialCustomizeMessageBottomConstraintConstant;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } initialInsets;
@property (nonatomic, retain) NSArray *initiallySelectedPlayers;
@property (nonatomic, copy) NSString *message;
@property (nonatomic) UITextField *messageField;
@property (nonatomic) UIView *scrollingHeader;
@property (nonatomic) NSLayoutConstraint *scrollingHeaderTopConstraint;
@property (nonatomic) double scrollingHeaderTopConstraintConstant;
@property (nonatomic) UIButton *sendButton;
@property (nonatomic) bool shouldApplyInitialOffset;
@property (nonatomic) bool shouldIgnoreClearSelection;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_updateButtonEnableState;
- (void)addMessage:(id)arg1;
- (void)adjustCustomizeMessageConstraint;
- (void)applyInitialContentOffset;
- (void)cancel:(id)arg1;
- (id)challenge;
- (void)clearSelection;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id /* block */)completionHandler;
- (id)composeController;
- (id)customizeMessageBottomConstraint;
- (id)customizeMessageButton;
- (void)dataUpdated:(bool)arg1 withError:(id)arg2;
- (id)descriptionLabel;
- (id)initWithChallenge:(id)arg1 initiallySelectedPlayers:(id)arg2;
- (double)initialCustomizeMessageBottomConstraintConstant;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })initialInsets;
- (id)initiallySelectedPlayers;
- (void)loadData;
- (id)message;
- (id)messageField;
- (id)preferredFocusEnvironments;
- (void)scrollViewDidScroll:(id)arg1;
- (id)scrollingHeader;
- (id)scrollingHeaderTopConstraint;
- (double)scrollingHeaderTopConstraintConstant;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)selectPlayersAtIndexPaths:(id)arg1;
- (void)send:(id)arg1;
- (id)sendButton;
- (void)setChallenge:(id)arg1;
- (void)setCompletionHandler:(id /* block */)arg1;
- (void)setComposeController:(id)arg1;
- (void)setCustomizeMessageBottomConstraint:(id)arg1;
- (void)setCustomizeMessageButton:(id)arg1;
- (void)setDescriptionLabel:(id)arg1;
- (void)setInitialCustomizeMessageBottomConstraintConstant:(double)arg1;
- (void)setInitialInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setInitiallySelectedPlayers:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setMessageField:(id)arg1;
- (void)setScrollingHeader:(id)arg1;
- (void)setScrollingHeaderTopConstraint:(id)arg1;
- (void)setScrollingHeaderTopConstraintConstant:(double)arg1;
- (void)setSearchText:(id)arg1;
- (void)setSendButton:(id)arg1;
- (void)setShouldApplyInitialOffset:(bool)arg1;
- (void)setShouldIgnoreClearSelection:(bool)arg1;
- (void)setupNoContentView:(id)arg1 withError:(id)arg2;
- (bool)shouldApplyInitialOffset;
- (bool)shouldIgnoreClearSelection;
- (bool)textFieldShouldReturn:(id)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;

@end
