
@interface VGFaceCaptureOptions : NSObject <NSSecureCoding> {
    float  _bottomMarginHeadRatio;
    NSString * _cameraImageColorSpaceName;
    NSString * _debugDataPath;
    bool  _ensureAlmostNeutralExpressionOnAllPoses;
    bool  _ensureEyesForwardOnFrontPose;
    bool  _ensureEyesOpenOnAllPoses;
    bool  _ensureEyesOpenOnFrontPose;
    float  _eyesForwardPitchSensitivity;
    float  _eyesForwardYawSensitivity;
    float  _eyesOpenSensitivity;
    float  _leftMarginHeadRatio;
    float  _neutralExpressionLowerBound;
    float  _neutralExpressionUpperBound;
    float  _pitchLimit;
    float  _pitchSensitivity;
    NSArray * _requiredExpressions;
    unsigned long long  _requiredPitchPoses;
    unsigned long long  _requiredYawPoses;
    float  _rightMarginHeadRatio;
    float  _topMarginHeadRatio;
    bool  _useFaceTrackingDictionary;
    bool  _writeDebugData;
    float  _yawLimit;
    float  _yawSensitivity;
}

@property (nonatomic) float bottomMarginHeadRatio;
@property (nonatomic, retain) NSString *cameraImageColorSpaceName;
@property (nonatomic, retain) NSString *debugDataPath;
@property (nonatomic) bool ensureAlmostNeutralExpressionOnAllPoses;
@property (nonatomic) bool ensureEyesForwardOnFrontPose;
@property (nonatomic) bool ensureEyesOpenOnAllPoses;
@property (nonatomic) bool ensureEyesOpenOnFrontPose;
@property (nonatomic) float eyesForwardPitchSensitivity;
@property (nonatomic) float eyesForwardYawSensitivity;
@property (nonatomic) float eyesOpenSensitivity;
@property (nonatomic) float leftMarginHeadRatio;
@property (nonatomic) float neutralExpressionLowerBound;
@property (nonatomic) float neutralExpressionUpperBound;
@property (nonatomic) float pitchLimit;
@property (nonatomic) float pitchSensitivity;
@property (nonatomic, retain) NSArray *requiredExpressions;
@property (nonatomic) unsigned long long requiredPitchPoses;
@property (nonatomic) unsigned long long requiredYawPoses;
@property (nonatomic) float rightMarginHeadRatio;
@property (nonatomic) float topMarginHeadRatio;
@property (nonatomic) bool useFaceTrackingDictionary;
@property (nonatomic) bool writeDebugData;
@property (nonatomic) float yawLimit;
@property (nonatomic) float yawSensitivity;

+ (float)defaultAngleSensitivity;
+ (float)defaultEyesOpenSensitivity;
+ (float)defaultNeutralExpressionLowerBound;
+ (float)defaultNeutralExpressionUpperBound;
+ (float)defaultPitchLimit;
+ (unsigned long long)defaultRequiredPitchPoses;
+ (unsigned long long)defaultRequiredYawPoses;
+ (float)defaultYawLimit;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (float)bottomMarginHeadRatio;
- (id)cameraImageColorSpaceName;
- (id)debugDataPath;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (bool)ensureAlmostNeutralExpressionOnAllPoses;
- (bool)ensureEyesForwardOnFrontPose;
- (bool)ensureEyesOpenOnAllPoses;
- (bool)ensureEyesOpenOnFrontPose;
- (float)eyesForwardPitchSensitivity;
- (float)eyesForwardYawSensitivity;
- (float)eyesOpenSensitivity;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithSuiteName:(id)arg1;
- (bool)isEqual:(id)arg1;
- (float)leftMarginHeadRatio;
- (float)neutralExpressionLowerBound;
- (float)neutralExpressionUpperBound;
- (float)pitchLimit;
- (float)pitchSensitivity;
- (id)requiredExpressions;
- (unsigned long long)requiredPitchPoses;
- (unsigned long long)requiredYawPoses;
- (float)rightMarginHeadRatio;
- (void)setBottomMarginHeadRatio:(float)arg1;
- (void)setCameraImageColorSpaceName:(id)arg1;
- (void)setDebugDataPath:(id)arg1;
- (void)setDefaultsWithSuiteName:(id)arg1;
- (void)setEnsureAlmostNeutralExpressionOnAllPoses:(bool)arg1;
- (void)setEnsureEyesForwardOnFrontPose:(bool)arg1;
- (void)setEnsureEyesOpenOnAllPoses:(bool)arg1;
- (void)setEnsureEyesOpenOnFrontPose:(bool)arg1;
- (void)setEyesForwardPitchSensitivity:(float)arg1;
- (void)setEyesForwardYawSensitivity:(float)arg1;
- (void)setEyesOpenSensitivity:(float)arg1;
- (void)setLeftMarginHeadRatio:(float)arg1;
- (void)setNeutralExpressionLowerBound:(float)arg1;
- (void)setNeutralExpressionUpperBound:(float)arg1;
- (void)setPitchLimit:(float)arg1;
- (void)setPitchSensitivity:(float)arg1;
- (void)setRequiredExpressions:(id)arg1;
- (void)setRequiredPitchPoses:(unsigned long long)arg1;
- (void)setRequiredYawPoses:(unsigned long long)arg1;
- (void)setRightMarginHeadRatio:(float)arg1;
- (void)setTopMarginHeadRatio:(float)arg1;
- (void)setUseFaceTrackingDictionary:(bool)arg1;
- (void)setWriteDebugData:(bool)arg1;
- (void)setYawLimit:(float)arg1;
- (void)setYawSensitivity:(float)arg1;
- (float)topMarginHeadRatio;
- (bool)useFaceTrackingDictionary;
- (bool)writeDebugData;
- (float)yawLimit;
- (float)yawSensitivity;

@end
