
@interface BMMomentsEventData : BMEventBase <BMStoreData> {
    bool  _IHAState;
    int  _age;
    int  _ageRange;
    NSString * _appEntryEngType;
    int  _biologicalSex;
    BMMomentsEventDataEventBundle * _bundle;
    NSString * _bundleEvergreenType;
    NSString * _bundleInterface;
    NSString * _categoryOfEvent;
    BMMomentsEventDataEvent * _event;
    bool  _hasAge;
    bool  _hasIHAState;
    bool  _hasIsBundle;
    bool  _hasRaw_endDate;
    bool  _hasRaw_startDate;
    bool  _hasViewTotalSuggestionsCount;
    bool  _hasViewVisibleSuggestionsCount;
    bool  _isBundle;
    NSString * _megaSignalTypeUsed;
    double  _raw_endDate;
    double  _raw_startDate;
    NSString * _sugSeetEngType;
    int  _viewTotalSuggestionsCount;
    int  _viewVisibleSuggestionsCount;
}

@property (nonatomic, readonly) bool IHAState;
@property (nonatomic, readonly) int age;
@property (nonatomic, readonly) int ageRange;
@property (nonatomic, readonly) NSString *appEntryEngType;
@property (nonatomic, readonly) int biologicalSex;
@property (nonatomic, readonly) BMMomentsEventDataEventBundle *bundle;
@property (nonatomic, readonly) NSString *bundleEvergreenType;
@property (nonatomic, readonly) NSString *bundleInterface;
@property (nonatomic, readonly) NSString *categoryOfEvent;
@property (nonatomic, readonly) unsigned int dataVersion;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDate *endDate;
@property (nonatomic, readonly) BMMomentsEventDataEvent *event;
@property (nonatomic) bool hasAge;
@property (nonatomic) bool hasIHAState;
@property (nonatomic) bool hasIsBundle;
@property (nonatomic) bool hasViewTotalSuggestionsCount;
@property (nonatomic) bool hasViewVisibleSuggestionsCount;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isBundle;
@property (nonatomic, readonly) NSString *megaSignalTypeUsed;
@property (nonatomic, readonly) NSDate *startDate;
@property (nonatomic, readonly) NSString *sugSeetEngType;
@property (readonly) Class superclass;
@property (nonatomic, readonly) int viewTotalSuggestionsCount;
@property (nonatomic, readonly) int viewVisibleSuggestionsCount;

+ (id)columns;
+ (id)eventWithData:(id)arg1 dataVersion:(unsigned int)arg2;
+ (id)validKeyPaths;

- (void).cxx_destruct;
- (bool)IHAState;
- (int)age;
- (int)ageRange;
- (id)appEntryEngType;
- (int)biologicalSex;
- (id)bundle;
- (id)bundleEvergreenType;
- (id)bundleInterface;
- (id)categoryOfEvent;
- (unsigned int)dataVersion;
- (id)description;
- (id)endDate;
- (id)event;
- (bool)hasAge;
- (bool)hasIHAState;
- (bool)hasIsBundle;
- (bool)hasViewTotalSuggestionsCount;
- (bool)hasViewVisibleSuggestionsCount;
- (id)initByReadFrom:(id)arg1;
- (id)initWithEvent:(id)arg1 bundle:(id)arg2 isBundle:(id)arg3 IHAState:(id)arg4 age:(id)arg5 ageRange:(int)arg6 biologicalSex:(int)arg7;
- (id)initWithEvent:(id)arg1 bundle:(id)arg2 isBundle:(id)arg3 IHAState:(id)arg4 age:(id)arg5 ageRange:(int)arg6 biologicalSex:(int)arg7 startDate:(id)arg8 endDate:(id)arg9 categoryOfEvent:(id)arg10 bundleInterface:(id)arg11 bundleEvergreenType:(id)arg12 sugSeetEngType:(id)arg13 appEntryEngType:(id)arg14 megaSignalTypeUsed:(id)arg15 viewVisibleSuggestionsCount:(id)arg16 viewTotalSuggestionsCount:(id)arg17;
- (id)initWithJSONDictionary:(id)arg1 error:(id*)arg2;
- (bool)isBundle;
- (bool)isEqual:(id)arg1;
- (id)jsonDictionary;
- (id)megaSignalTypeUsed;
- (id)serialize;
- (void)setHasAge:(bool)arg1;
- (void)setHasIHAState:(bool)arg1;
- (void)setHasIsBundle:(bool)arg1;
- (void)setHasViewTotalSuggestionsCount:(bool)arg1;
- (void)setHasViewVisibleSuggestionsCount:(bool)arg1;
- (id)startDate;
- (id)sugSeetEngType;
- (int)viewTotalSuggestionsCount;
- (int)viewVisibleSuggestionsCount;
- (void)writeTo:(id)arg1;

@end
