
@interface _TtCFC8PaperKit29MarkupContainerViewController18dataRepresentationFT9withErrorGSqGVs33AutoreleasingUnsafeMutablePointerGSqCSo7NSError____GSqV10Foundation4Data_L_12ImageWrapper : _TtCs12_SwiftObject {
    void image;
}

@end
