
@interface BRCContainerScheduler : NSObject <APSConnectionDelegate, BRCAppLibraryDelegate, BRCClientZoneDelegate> {
    BRCContainerMetadataSyncPersistedState * _containerMetadataPersistedState;
    BRCSyncOperationThrottle * _containerMetadataSyncDownThrottle;
    _BRCOperation<BRCOperationSubclass> * _containerMetadataSyncOperation;
    BRCDeadlineSource * _containerMetadataSyncSource;
    unsigned int  _containerMetadataSyncState;
    BRCSyncOperationThrottle * _containerMetadataSyncUpThrottle;
    NSString * _environmentName;
    NSObject<OS_dispatch_group> * _initialSyncDownGroup;
    bool  _isInSyncBubble;
    NSError * _lastContainerMetadataSyncDownError;
    NSError * _lastContainerMetadataSyncUpError;
    NSDate * _lastPeriodicSyncDate;
    NSError * _lastSharedDatabaseSyncDownError;
    NSError * _lastSideCarSyncDownError;
    NSError * _lastSideCarSyncUpError;
    NSError * _lastZoneHealthSyncDownError;
    NSError * _lastZoneHealthSyncUpError;
    BRCMigrateZonePCSOperation * _migrateZonePCSOperation;
    BRCDeadlineSource * _migrateZonePCSSource;
    NSMutableArray * _nextZoneHealthSyncDownBarriers;
    _BRCOperation<BRCOperationSubclass> * _periodicSyncOperation;
    APSConnection * _pushConnection;
    BRCFairSource * _pushSource;
    NSData * _pushToken;
    NSObject<OS_dispatch_workloop> * _pushWorkloop;
    BRCAccountSession * _session;
    unsigned int  _sharedDBSyncState;
    BRCSyncOperationThrottle * _sharedDatabaseSyncDownThrottle;
    _BRCOperation<BRCOperationSubclass> * _sharedDatabaseSyncOperation;
    BRCDeadlineSource * _sharedDatabaseSyncSource;
    BRCSyncOperationThrottle * _sideCarSyncDownThrottle;
    _BRCOperation<BRCOperationSubclass> * _sideCarSyncOperation;
    BRCSideCarSyncPersistedState * _sideCarSyncPersistedState;
    BRCDeadlineSource * _sideCarSyncSource;
    unsigned int  _sideCarSyncState;
    BRCSyncOperationThrottle * _sideCarSyncUpThrottle;
    NSObject<OS_dispatch_group> * _syncGroup;
    BRCDeadlineScheduler * _syncScheduler;
    BRCSyncBudgetThrottle * _syncUpBudget;
    BRCZoneHealthSyncPersistedState * _zoneHealthPersistedState;
    BRCSyncOperationThrottle * _zoneHealthSyncDownThrottle;
    _BRCOperation<BRCOperationSubclass> * _zoneHealthSyncOperation;
    BRCDeadlineSource * _zoneHealthSyncSource;
    unsigned int  _zoneHealthSyncState;
    BRCSyncOperationThrottle * _zoneHealthSyncUpThrottle;
}

@property (nonatomic, readonly) BRCContainerMetadataSyncPersistedState *containerMetadataPersistedState;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSObject<OS_dispatch_group> *initialSyncDownGroup;
@property (nonatomic, readonly) BRCAccountSession *session;
@property (nonatomic, readonly) BRCSideCarSyncPersistedState *sideCarSyncPersistedState;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSObject<OS_dispatch_group> *syncGroup;
@property (nonatomic, readonly) BRCDeadlineScheduler *syncScheduler;
@property (nonatomic, readonly) BRCSyncBudgetThrottle *syncUpBudget;
@property (nonatomic, readonly) BRCZoneHealthSyncPersistedState *zoneHealthSyncPersistedState;

- (void).cxx_destruct;
- (void)_connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;
- (id)_newSyncDeadlineSourceWithName:(id)arg1;
- (void)_printSyncErrorIfNecessaryWithThrottle:(id)arg1 context:(id)arg2 error:(id)arg3 now:(long long)arg4;
- (void)_scheduleCrossZoneMovePCSPrep;
- (void)_scheduleUpdatePushTopicsRegistration;
- (void)_syncScheduleForContainersMetadata;
- (void)_syncScheduleForSharedDatabase;
- (void)_syncScheduleForSideCar;
- (void)_syncScheduleForZoneHealth;
- (void)_unscheduleClientZone:(id)arg1;
- (void)_updatePushTopicsRegistration;
- (void)close;
- (void)closeContainers;
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4;
- (id)containerMetadataPersistedState;
- (void)didChangeSyncStatusForContainerMetadataForContainer:(id)arg1;
- (void)didChangeSyncStatusForZoneHealthForContainer:(id)arg1;
- (void)didInitialSyncDownForClientZone:(id)arg1;
- (void)dumpToContext:(id)arg1 includeAllItems:(bool)arg2 db:(id)arg3;
- (void)enablePushNotifications;
- (void)finishedZoneHealthSyncDownWithRequestID:(unsigned long long)arg1 error:(id)arg2;
- (id)initWithAccountSession:(id)arg1 pushWorkloop:(id)arg2;
- (id)initialSyncDownGroup;
- (id)internalZoneSyncDownAnalyticsErrors;
- (id)internalZoneSyncUpAnalyticsErrors;
- (void)notifyAfterNextZoneHealthSyncDown:(id /* block */)arg1;
- (void)receivedUpdatedSideCarServerChangeToken:(id)arg1 requestID:(unsigned long long)arg2;
- (void)receivedUpdatedZoneHealthServerChangeToken:(id)arg1 requestID:(unsigned long long)arg2;
- (void)redoZonePCSPreperation;
- (void)refreshPushRegistrationAfterAppsListChanged;
- (void)resume;
- (void)schedulePeriodicSyncIfNecessaryInGroup:(id)arg1;
- (void)scheduleSyncDownForContainerMetadataWithGroup:(id)arg1;
- (void)scheduleSyncDownForSharedDatabaseImmediately:(bool)arg1;
- (void)scheduleSyncDownForSideCarWithGroup:(id)arg1;
- (void)scheduleSyncDownForZoneHealthWithGroup:(id)arg1;
- (void)scheduleSyncUpForSideCar;
- (id)session;
- (void)setup;
- (id)sideCarSyncPersistedState;
- (void)syncContextDidBecomeBackground:(id)arg1;
- (void)syncContextDidBecomeForeground:(id)arg1;
- (id)syncGroup;
- (id)syncScheduler;
- (id)syncUpBudget;
- (void)willInitialSyncDownForClientZone:(id)arg1;
- (id)zoneHealthSyncPersistedState;

@end
