
@interface CNMeCardSharingSettingsViewController : UIViewController <CNMeCardSharingEnabledDelegate, CNMeCardSharingSettingsHeaderViewControllerDelegate, CNMeCardSharingSettingsPreferenceMenuCellDelegate, CNPhotoPickerViewControllerDelegate, CNPresenterDelegate, CNSNaPSetupFlowManagerDelegate, UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate> {
    <CNMeCardSharingAvatarProvider> * _avatarProvider;
    OBButtonTray * _buttonTray;
    _TtC10ContactsUI37CNAvatarPosterPairCollectionPreWarmer * _carouselPreWarmer;
    CNContact * _contact;
    CNContactStore * _contactStore;
    OBBoldTrayButton * _continueButton;
    <CNMeCardSharingSettingsViewControllerDelegate> * _delegate;
    CNSNaPSetupFlowManager * _editAvatarPosterFlowManager;
    CNMutableContact * _editingContact;
    CNMeCardSharingContactAvatarProvider * _editingContactAvatarProvider;
    CNContactImage * _editingContactImage;
    NSString * _editingFamilyName;
    NSString * _editingGivenName;
    CNMeCardSharingEnabledDataSource * _enabledDataSource;
    UITextField * _familyNameField;
    UITextField * _givenNameField;
    long long  _headerMode;
    CNMeCardSharingSettingsHeaderViewController * _headerViewController;
    bool  _isPresentedInOnboarding;
    double  _keyboardHeight;
    CNMeCardSharingPickerLayoutAttributes * _layoutAttributes;
    CNSharingProfileLogger * _logger;
    CNSharingProfileMeCardUpdater * _meCardUpdater;
    CNMeCardSharingSettingsNameDataSource * _nameDataSource;
    long long  _nameOrder;
    <CNMeCardSharingNameProvider> * _nameProvider;
    CNPhotoPickerViewController * _photoPicker;
    NSArray * _sectionDataSources;
    UISwitch * _shareSwitch;
    CNMeCardSharingAudienceDataSource * _sharingAudienceDataSource;
    bool  _shouldSetAsMeContact;
    bool  _showsWallpaperSuggestionsGalleryPicker;
    CNSharedProfileOnboardingController * _snapOnboardingController;
    UITableView * _tableView;
    double  _tableViewBottomInsets;
}

@property (nonatomic, readonly) <CNMeCardSharingAvatarProvider> *avatarProvider;
@property (nonatomic, retain) OBButtonTray *buttonTray;
@property (nonatomic, retain) _TtC10ContactsUI37CNAvatarPosterPairCollectionPreWarmer *carouselPreWarmer;
@property (nonatomic, retain) CNContact *contact;
@property (nonatomic, readonly) CNContactStore *contactStore;
@property (nonatomic, retain) OBBoldTrayButton *continueButton;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <CNMeCardSharingSettingsViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) CNSNaPSetupFlowManager *editAvatarPosterFlowManager;
@property (nonatomic, retain) CNMutableContact *editingContact;
@property (nonatomic, retain) CNMeCardSharingContactAvatarProvider *editingContactAvatarProvider;
@property (nonatomic, retain) CNContactImage *editingContactImage;
@property (nonatomic, retain) NSString *editingFamilyName;
@property (nonatomic, retain) NSString *editingGivenName;
@property (nonatomic, readonly) CNMeCardSharingEnabledDataSource *enabledDataSource;
@property (nonatomic, retain) UITextField *familyNameField;
@property (nonatomic, retain) UITextField *givenNameField;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long headerMode;
@property (nonatomic, retain) CNMeCardSharingSettingsHeaderViewController *headerViewController;
@property (nonatomic) bool isPresentedInOnboarding;
@property (readonly) bool isPresentingModalViewController;
@property (nonatomic) double keyboardHeight;
@property (nonatomic, readonly) CNMeCardSharingPickerLayoutAttributes *layoutAttributes;
@property (nonatomic, readonly) CNSharingProfileLogger *logger;
@property (nonatomic, retain) CNSharingProfileMeCardUpdater *meCardUpdater;
@property (nonatomic, readonly) CNMeCardSharingSettingsNameDataSource *nameDataSource;
@property (nonatomic) long long nameOrder;
@property (nonatomic, readonly) <CNMeCardSharingNameProvider> *nameProvider;
@property (nonatomic, retain) CNPhotoPickerViewController *photoPicker;
@property (nonatomic, retain) NSArray *sectionDataSources;
@property (nonatomic, readonly) unsigned long long selectedSharingAudience;
@property (nonatomic, retain) UISwitch *shareSwitch;
@property (nonatomic, readonly) CNMeCardSharingAudienceDataSource *sharingAudienceDataSource;
@property (nonatomic, readonly) bool sharingEnabled;
@property (nonatomic) bool shouldSetAsMeContact;
@property (nonatomic) bool showsWallpaperSuggestionsGalleryPicker;
@property (nonatomic, retain) CNSharedProfileOnboardingController *snapOnboardingController;
@property (readonly) Class superclass;
@property (nonatomic, retain) UITableView *tableView;
@property (nonatomic) double tableViewBottomInsets;

+ (id)descriptorForRequiredKeys;

- (void).cxx_destruct;
- (void)adjustInsetsForKeyboardOverlap:(double)arg1;
- (double)availableHeaderHeight;
- (void)avatarPosterEditorFromFlowManager:(id)arg1 didUpdateContact:(id)arg2 withVisualIdentity:(id)arg3;
- (id)avatarProvider;
- (id)buttonTray;
- (id)carouselPreWarmer;
- (id)contact;
- (id)contactStore;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (id)continueButton;
- (void)dealloc;
- (id)delegate;
- (void)didTapContinueButton:(id)arg1;
- (id)editAvatarPosterFlowManager;
- (id)editingContact;
- (id)editingContactAvatarProvider;
- (id)editingContactImage;
- (id)editingFamilyName;
- (id)editingGivenName;
- (id)enabledDataSource;
- (void)familyNameDidChange:(id)arg1;
- (id)familyNameField;
- (void)generateEditingContactWithCompletionHandler:(id /* block */)arg1;
- (void)givenNameDidChange:(id)arg1;
- (id)givenNameField;
- (long long)headerMode;
- (id)headerViewController;
- (id)initForOnboardingWithContactStore:(id)arg1 contact:(id)arg2 avatarProvider:(id)arg3 nameProvider:(id)arg4 sharingEnabled:(bool)arg5 selectedSharingAudience:(unsigned long long)arg6 showsWallpaperSuggestionsGalleryPicker:(bool)arg7 headerMode:(long long)arg8;
- (id)initWithContactStore:(id)arg1 contact:(id)arg2 avatarProvider:(id)arg3 nameProvider:(id)arg4 sharingEnabled:(bool)arg5 selectedSharingAudience:(unsigned long long)arg6;
- (id)initWithContactStore:(id)arg1 contact:(id)arg2 avatarProvider:(id)arg3 nameProvider:(id)arg4 sharingEnabled:(bool)arg5 selectedSharingAudience:(unsigned long long)arg6 showsWallpaperSuggestionsGalleryPicker:(bool)arg7 headerMode:(long long)arg8;
- (id)initWithContactStore:(id)arg1 contact:(id)arg2 avatarProvider:(id)arg3 nameProvider:(id)arg4 sharingEnabled:(bool)arg5 selectedSharingAudience:(unsigned long long)arg6 showsWallpaperSuggestionsGalleryPicker:(bool)arg7 headerMode:(long long)arg8 presentedInOnboarding:(bool)arg9;
- (bool)isPresentedInOnboarding;
- (bool)isPresentingModalViewController;
- (double)keyboardHeight;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (id)layoutAttributes;
- (id)logger;
- (id)meCardUpdater;
- (id)nameDataSource;
- (long long)nameOrder;
- (id)nameProvider;
- (void)notifyDelegateOfChangesWithDidSaveMeCard:(bool)arg1 contactImage:(id)arg2 sharingResult:(id)arg3;
- (void)notifyDelegateOfChangesWithDidSaveToMeCard:(bool)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)performSaveToMeCardAction;
- (id)photoPicker;
- (void)photoPicker:(id)arg1 didUpdatePhotoForContact:(id)arg2 withContactImage:(id)arg3;
- (void)photoPickerDidCancel:(id)arg1;
- (void)preWarmContactPosterForContact:(id)arg1;
- (void)presentErrorAlertForEmptyPhotoIfNeededWithCompletion:(id /* block */)arg1;
- (void)presentNameEditor;
- (void)presentPhotoPickerControllerForContact:(id)arg1;
- (void)promptForSavingToMeCardIfNeeded;
- (void)saveDraftContact;
- (id)sectionDataSources;
- (unsigned long long)selectedSharingAudience;
- (void)sender:(id)arg1 dismissViewController:(id)arg2;
- (void)sender:(id)arg1 dismissViewController:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)sender:(id)arg1 presentViewController:(id)arg2;
- (void)setButtonTray:(id)arg1;
- (void)setCarouselPreWarmer:(id)arg1;
- (void)setContact:(id)arg1;
- (void)setContinueButton:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setEditAvatarPosterFlowManager:(id)arg1;
- (void)setEditingContact:(id)arg1;
- (void)setEditingContactAvatarProvider:(id)arg1;
- (void)setEditingContactImage:(id)arg1;
- (void)setEditingFamilyName:(id)arg1;
- (void)setEditingGivenName:(id)arg1;
- (void)setFamilyNameField:(id)arg1;
- (void)setGivenNameField:(id)arg1;
- (void)setHeaderMode:(long long)arg1;
- (void)setHeaderViewController:(id)arg1;
- (void)setIsPresentedInOnboarding:(bool)arg1;
- (void)setKeyboardHeight:(double)arg1;
- (void)setMeCardUpdater:(id)arg1;
- (void)setNameOrder:(long long)arg1;
- (void)setPhotoPicker:(id)arg1;
- (void)setSectionDataSources:(id)arg1;
- (void)setShareSwitch:(id)arg1;
- (void)setShouldSetAsMeContact:(bool)arg1;
- (void)setShowsWallpaperSuggestionsGalleryPicker:(bool)arg1;
- (void)setSnapOnboardingController:(id)arg1;
- (void)setTableView:(id)arg1;
- (void)setTableViewBottomInsets:(double)arg1;
- (id)shareSwitch;
- (id)sharingAudienceDataSource;
- (bool)sharingEnabled;
- (void)sharingEnabledDataSource:(id)arg1 didChangeEnabledState:(bool)arg2;
- (id)sharingResultWithContactImage:(id)arg1 wallpaper:(id)arg2 watchWallpaperImageData:(id)arg3 didSaveToMeCard:(bool)arg4;
- (void)sharingSettingsHeaderWasTapped:(id)arg1;
- (void)sharingSettingsPreferenceMenuCell:(id)arg1 didSelectSharingAudience:(unsigned long long)arg2;
- (bool)shouldSetAsMeContact;
- (bool)showsWallpaperSuggestionsGalleryPicker;
- (id)snapOnboardingController;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (double)tableViewBottomInsets;
- (void)textFieldDidEndEditing:(id)arg1;
- (id)textFieldForIndex:(long long)arg1;
- (bool)textFieldShouldReturn:(id)arg1;
- (id)textFields;
- (void)updateContact:(id)arg1 withEditedContact:(id)arg2;
- (void)updateContact:(id)arg1 withImagePropertiesFromContact:(id)arg2;
- (void)updateContact:(id)arg1 withNamePropertiesFromContact:(id)arg2;
- (void)updateHeaderViewFrame;
- (void)updateHeaderViewFrameAndTableView;
- (void)updateTableViewBottomPaddingIfNeeded;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (double)viewHeight;
- (void)viewIsAppearing:(bool)arg1;

@end
