
@interface CNSharedProfileBannerView : UIView <CNUILikenessCachingRendererDelegate> {
    UIButton * _actionButton;
    CNSharedProfileAnimationGenerator * _animationGenerator;
    CNAvatarView * _avatarView;
    NSArray * _constraints;
    <CNSharedProfileBannerViewDelegate> * _delegate;
    UIButton * _dismissButton;
    bool  _isIgnored;
    UIStackView * _labelStackView;
    CNSharedProfileStateOracle * _sharedProfileStateOracle;
    bool  _shouldPerformActionUponCacheInvalidation;
    CNSharedProfileBannerStyle * _style;
    UILabel * _subtitleLabel;
    unsigned long long  _tappedAction;
    UILabel * _titleLabel;
}

@property (nonatomic, retain) UIButton *actionButton;
@property (nonatomic, retain) CNSharedProfileAnimationGenerator *animationGenerator;
@property (nonatomic, retain) CNAvatarView *avatarView;
@property (nonatomic, retain) NSArray *constraints;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <CNSharedProfileBannerViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UIButton *dismissButton;
@property (nonatomic, readonly) double estimatedHeight;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isIgnored;
@property (nonatomic, retain) UIStackView *labelStackView;
@property (nonatomic, retain) CNSharedProfileStateOracle *sharedProfileStateOracle;
@property (nonatomic) bool shouldPerformActionUponCacheInvalidation;
@property (nonatomic, retain) CNSharedProfileBannerStyle *style;
@property (nonatomic, retain) UILabel *subtitleLabel;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long tappedAction;
@property (nonatomic, retain) UILabel *titleLabel;

+ (id)log;

- (void).cxx_destruct;
- (id)actionButton;
- (id)actionButtonTitleForAction:(unsigned long long)arg1;
- (id)animationGenerator;
- (void)avatarCacheDidUpdateForIdentifiers:(id)arg1;
- (struct CGSize { double x1; double x2; })avatarSize;
- (id)avatarView;
- (id)constraints;
- (id)contactDisplayName;
- (id)delegate;
- (void)didTapActionButton;
- (void)didTapDismiss;
- (id)dismissButton;
- (double)estimatedHeight;
- (double)estimatedHorizontalHeight;
- (double)estimatedVerticalHeight;
- (bool)hasTappedAction;
- (id)horizontalConstraints;
- (id)init;
- (void)invalidateAvatarCacheEntriesForContact:(id)arg1;
- (bool)isIgnored;
- (bool)isRTL;
- (bool)isRevertAction:(unsigned long long)arg1;
- (id)labelStackView;
- (void)layoutSubviews;
- (void)performAnimationIfNeeded;
- (void)setActionButton:(id)arg1;
- (void)setAnimationGenerator:(id)arg1;
- (void)setAvatarView:(id)arg1;
- (void)setConstraints:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDismissButton:(id)arg1;
- (void)setIsIgnored:(bool)arg1;
- (void)setLabelStackView:(id)arg1;
- (void)setSharedProfileStateOracle:(id)arg1;
- (void)setShouldPerformActionUponCacheInvalidation:(bool)arg1;
- (void)setStyle:(id)arg1;
- (void)setSubtitleLabel:(id)arg1;
- (void)setTappedAction:(unsigned long long)arg1;
- (void)setTitleLabel:(id)arg1;
- (void)setUpActionButton;
- (void)setUpAvatarView;
- (void)setUpDismissButton;
- (void)setUpLabels;
- (void)setUpViews;
- (void)setUpWithSharedProfileStateOracle:(id)arg1 tappedAction:(unsigned long long)arg2 hasPerformedAnimation:(bool)arg3;
- (id)sharedProfileStateOracle;
- (bool)shouldPerformActionUponCacheInvalidation;
- (void)startObservingAvatarCacheInvalidation;
- (id)style;
- (id)subtitleForAction:(unsigned long long)arg1 contactName:(id)arg2;
- (id)subtitleForTappedAction:(unsigned long long)arg1;
- (id)subtitleLabel;
- (id)subtitleTextColorForTappedAction:(unsigned long long)arg1;
- (unsigned long long)tappedAction;
- (id)titleForAction:(unsigned long long)arg1;
- (id)titleLabel;
- (void)updateConstraints;
- (void)updateContactForTappedAction;
- (void)updateUIForCurrentState;
- (id)verticalConstraintsWithAvatarView;
- (id)verticalConstraintsWithHiddenAvatarView;
- (id)xmarkImageWithColorConfiguration:(id)arg1;

@end
