
@interface PXAssetVariationRenderProvider : PXObservable {
    NSOperation * __analysisOperation;
    NSDate * __beginRenderingDate;
    NSNumber * __editSourceDuration;
    NSNumber * __recipeGenerationDuration;
    NSMutableDictionary * __renderingDurationByVariationType;
    NSMutableDictionary * __renderingOperationsByVariationType;
    NSDictionary * _analysisResult;
    NSIndexSet * _desiredVariationTypes;
    <PXEditSourceLoader> * _editSourceLoader;
    NSError * _error;
    bool  _hasBegunRendering;
    NSProgress * _initialLoadingProgress;
    NSProgress * _observedEditSourceLoaderProgress;
    NSMutableDictionary * _progressesByVariationType;
    NSProgress * _recipeGenerationProgress;
    bool  _renderAllResources;
    NSMutableDictionary * _resultsByVariationType;
    unsigned char  _signpostID;
    long long  _status;
    NSString * _statusDescription;
    struct CGSize { 
        double width; 
        double height; 
    }  _targetSize;
    NSNumber * _totalRenderingDuration;
    PXUpdater * _updater;
    NSObject<OS_dispatch_queue> * _workQueue;
}

@property (setter=_setAnalysisOperation:, nonatomic, retain) NSOperation *_analysisOperation;
@property (setter=_setBeginRenderingDate:, nonatomic, retain) NSDate *_beginRenderingDate;
@property (setter=_setEditSourceDuration:, nonatomic, retain) NSNumber *_editSourceDuration;
@property (nonatomic, readonly) bool _hasAllResults;
@property (setter=_setRecipeGenerationDuration:, nonatomic, retain) NSNumber *_recipeGenerationDuration;
@property (nonatomic, readonly) NSMutableDictionary *_renderingDurationByVariationType;
@property (nonatomic, readonly) NSMutableDictionary *_renderingOperationsByVariationType;
@property (nonatomic, copy) NSDictionary *analysisResult;
@property (nonatomic, readonly, copy) NSIndexSet *desiredVariationTypes;
@property (nonatomic, readonly) <PXEditSourceLoader> *editSourceLoader;
@property (setter=_setError:, nonatomic, retain) NSError *error;
@property (nonatomic, readonly) NSProgress *initialLoadingProgress;
@property (nonatomic) bool renderAllResources;
@property (setter=_setStatus:, nonatomic) long long status;
@property (setter=_setStatusDescription:, nonatomic, copy) NSString *statusDescription;
@property (nonatomic) struct CGSize { double x1; double x2; } targetSize;
@property (nonatomic, retain) NSNumber *totalRenderingDuration;

+ (void)_performSimulatedWorkWithProgress:(id)arg1;
+ (id)_renderingLog;
+ (id)sharedOperationQueue;
+ (id)supportedVariationTypes;

- (void).cxx_destruct;
- (id)_analysisOperation;
- (id)_beginRenderingDate;
- (id)_editSourceDuration;
- (void)_handleAnalysisOperationCompleted:(id)arg1;
- (void)_handleCachedAnalysisResult:(id)arg1;
- (void)_handleRenderingOperationCompleted:(id)arg1;
- (void)_handleRenderingOperationStarted:(id)arg1;
- (bool)_hasAllResults;
- (void)_invalidateAnalysisResult;
- (void)_invalidateCachedAnalysisResult;
- (void)_invalidateRenders;
- (void)_invalidateStatus;
- (id)_recipeGenerationDuration;
- (void)_removeAllResults;
- (id)_renderingDurationByVariationType;
- (id)_renderingOperationsByVariationType;
- (void)_setAnalysisOperation:(id)arg1;
- (void)_setBeginRenderingDate:(id)arg1;
- (void)_setEditSourceDuration:(id)arg1;
- (void)_setError:(id)arg1;
- (void)_setProgress:(id)arg1 forVariationType:(long long)arg2;
- (void)_setRecipeGenerationDuration:(id)arg1;
- (void)_setResult:(id)arg1 forVariationType:(long long)arg2;
- (void)_setStatus:(long long)arg1;
- (void)_setStatusDescription:(id)arg1;
- (void)_updateAnalysisResult;
- (void)_updateCachedAnalysisResult;
- (void)_updateRenders;
- (void)_updateStatus;
- (long long)_variationSourceType;
- (id)analysisResult;
- (void)beginRendering;
- (void)cancelRendering;
- (void)dealloc;
- (id)debugDescription;
- (id)desiredVariationTypes;
- (void)didPerformChanges;
- (id)editSourceLoader;
- (id)error;
- (id)init;
- (id)initWithEditSourceLoader:(id)arg1 targetSize:(struct CGSize { double x1; double x2; })arg2 desiredVariationTypes:(id)arg3;
- (id)initialLoadingProgress;
- (id)mutableChangeObject;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)progressForVariationType:(long long)arg1;
- (bool)renderAllResources;
- (id)renderResultForVariationType:(long long)arg1;
- (void)setAnalysisResult:(id)arg1;
- (void)setRenderAllResources:(bool)arg1;
- (void)setTargetSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setTotalRenderingDuration:(id)arg1;
- (long long)status;
- (id)statusDescription;
- (struct CGSize { double x1; double x2; })targetSize;
- (id)totalRenderingDuration;
- (void)unloadResults;

@end
