
@interface PXGViewControllerTransition : PXObservable <PXGMutableViewControllerTransition, UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate> {
    NSMutableArray * _alongsideAnimationBlocks;
    id /* block */  _animationUpdateBlock;
    id /* block */  _completionHandler;
    <PXGViewControllerTransitionEndPoint> * _detailEndPoint;
    PXGItemPlacement * _detailItemOriginalPlacement;
    PXGItemPlacement * _detailItemPlacementOverride;
    UIViewController * _detailViewController;
    PXDisplayLink * _displayLink;
    NSArray * _endPointInfos;
    UIView * _fromContentView;
    UIPercentDrivenInteractiveTransition * _interactiveTransition;
    bool  _isEnding;
    bool  _isInteractive;
    bool  _isVerticalOnly;
    PXGViewControllerItemPlacementInterpolator * _itemPlacementInterpolator;
    UIViewController * _presentedViewController;
    UIViewController * _presentingViewController;
    <PXGViewControllerTransitionEndPoint> * _summaryEndPoint;
    PXGItemPlacement * _summaryItemOriginalPlacement;
    PXGItemPlacement * _summaryItemPlacementOverride;
    UIViewController * _summaryViewController;
    UIView * _toContentView;
    <UIViewControllerContextTransitioning> * _transitionContext;
    double  _transitionDuration;
    long long  _transitionKind;
    double  fractionCompleted;
}

@property (nonatomic, readonly) NSMutableArray *alongsideAnimationBlocks;
@property (nonatomic, copy) id /* block */ animationUpdateBlock;
@property (nonatomic, copy) id /* block */ completionHandler;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) <PXGViewControllerTransitionEndPoint> *detailEndPoint;
@property (nonatomic, readonly) _PXGTransitionEndPointInfo *detailEndPointInfo;
@property (nonatomic, readonly) PXGItemPlacement *detailItemOriginalPlacement;
@property (nonatomic, copy) PXGItemPlacement *detailItemPlacementOverride;
@property (nonatomic, readonly) UIViewController *detailViewController;
@property (nonatomic, retain) PXDisplayLink *displayLink;
@property (nonatomic, copy) NSArray *endPointInfos;
@property (nonatomic) double fractionCompleted;
@property (nonatomic, retain) UIView *fromContentView;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIPercentDrivenInteractiveTransition *interactiveTransition;
@property (nonatomic) bool isEnding;
@property (nonatomic) bool isInteractive;
@property (nonatomic, readonly) bool isVerticalOnly;
@property (nonatomic, retain) PXGViewControllerItemPlacementInterpolator *itemPlacementInterpolator;
@property (nonatomic, readonly) UIViewController *presentedViewController;
@property (nonatomic) UIViewController *presentingViewController;
@property (nonatomic, readonly) <PXGViewControllerTransitionEndPoint> *summaryEndPoint;
@property (nonatomic, readonly) _PXGTransitionEndPointInfo *summaryEndPointInfo;
@property (nonatomic, readonly) PXGItemPlacement *summaryItemOriginalPlacement;
@property (nonatomic, copy) PXGItemPlacement *summaryItemPlacementOverride;
@property (nonatomic, readonly) UIViewController *summaryViewController;
@property (readonly) Class superclass;
@property (nonatomic, retain) UIView *toContentView;
@property (nonatomic, retain) <UIViewControllerContextTransitioning> *transitionContext;
@property (nonatomic) double transitionDuration;
@property (nonatomic) long long transitionKind;

+ (id)_createTransitionWithSummaryViewController:(id)arg1 presentedViewController:(id)arg2 detailViewController:(id)arg3;
+ (id)_transitionWithDetailViewController:(id)arg1 createIfNeeded:(bool)arg2 verticalOnly:(bool)arg3;
+ (id)interactiveDismissalOfDetailViewController:(id)arg1;
+ (void)prepareDismissalOfDetailViewController:(id)arg1;
+ (void)prepareTransitionFromSummaryViewController:(id)arg1 toPresentedViewController:(id)arg2 detailViewController:(id)arg3;
+ (id)transitionWithDetailViewController:(id)arg1;

- (void).cxx_destruct;
- (void)_endTransitionAnimation:(bool)arg1;
- (void)_handleDisplayLink:(id)arg1;
- (id)_initWithSummaryViewController:(id)arg1 presentedViewController:(id)arg2 detailViewController:(id)arg3;
- (bool)_isContentViewControllerHidden:(id)arg1;
- (bool)_isTransitionAllowedWithKind:(long long)arg1;
- (void)_notifyAlongsideAnimationBlocks:(double)arg1;
- (void)_prepareTransitionAnimationWithReadinessHandler:(id /* block */)arg1 completionHandler:(id /* block */)arg2;
- (double)_progressForFractionCompleted:(double)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_rectInContainerView:(id)arg1 fromRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 inCoordinateSpace:(id)arg3 inContentViewController:(id)arg4;
- (void)_transitionDidEnd:(bool)arg1;
- (void)_transitionDidUpdateWithTransitionTime:(double)arg1;
- (id)_transitionViewControllerForContentViewController:(id)arg1;
- (void)_transitionWillBegin;
- (void)_willDismissWithoutTransition;
- (id)alongsideAnimationBlocks;
- (void)animateAlongside:(id /* block */)arg1;
- (void)animateTransition:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id /* block */)animationUpdateBlock;
- (void)cancel;
- (id /* block */)completionHandler;
- (id)detailEndPoint;
- (id)detailEndPointInfo;
- (id)detailItemOriginalPlacement;
- (id)detailItemPlacementOverride;
- (id)detailViewController;
- (id)displayLink;
- (id)endPointInfos;
- (void)finish;
- (double)fractionCompleted;
- (id)fromContentView;
- (id)init;
- (void)installCompletionHandler:(id /* block */)arg1;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)interactiveTransition;
- (bool)isEnding;
- (bool)isInteractive;
- (bool)isVerticalOnly;
- (id)itemPlacementInterpolator;
- (void)performChanges:(id /* block */)arg1;
- (id)presentedViewController;
- (id)presentingViewController;
- (void)setAnimationUpdateBlock:(id /* block */)arg1;
- (void)setCompletionHandler:(id /* block */)arg1;
- (void)setDetailItemOriginalPlacement:(id)arg1;
- (void)setDetailItemPlacementOverride:(id)arg1;
- (void)setDisplayLink:(id)arg1;
- (void)setEndPointInfos:(id)arg1;
- (void)setFractionCompleted:(double)arg1;
- (void)setFromContentView:(id)arg1;
- (void)setInteractiveTransition:(id)arg1;
- (void)setIsEnding:(bool)arg1;
- (void)setIsInteractive:(bool)arg1;
- (void)setIsVerticalOnly:(bool)arg1;
- (void)setItemPlacementInterpolator:(id)arg1;
- (void)setPresentingViewController:(id)arg1;
- (void)setSummaryItemOriginalPlacement:(id)arg1;
- (void)setSummaryItemPlacementOverride:(id)arg1;
- (void)setToContentView:(id)arg1;
- (void)setTransitionContext:(id)arg1;
- (void)setTransitionDuration:(double)arg1;
- (void)setTransitionKind:(long long)arg1;
- (id)summaryEndPoint;
- (id)summaryEndPointInfo;
- (id)summaryItemOriginalPlacement;
- (id)summaryItemPlacementOverride;
- (id)summaryViewController;
- (id)toContentView;
- (id)transitionContext;
- (double)transitionDuration;
- (double)transitionDuration:(id)arg1;
- (long long)transitionKind;

@end
