
@interface PXMockDisplayAssetCollection : NSObject <PXDisplayAssetCollection> {
    long long  _assetCollectionType;
    NSDate * _endDate;
    bool  _isPrivacySensitiveAlbum;
    NSString * _localizedSubtitle;
    NSString * _localizedTitle;
    NSDate * _startDate;
    long long  _subtype;
    long long  _type;
    unsigned long long  estimatedAssetCount;
    bool  isAggregation;
    bool  isEnriched;
    bool  isEnrichmentComplete;
    bool  isRecent;
    NSString * localizedDateDescription;
    NSArray * localizedLocationNames;
    NSString * localizedSmartDescription;
    double  promotionScore;
    unsigned short  px_highlightEnrichmentState;
    long long  px_highlightKind;
    bool  px_isSuggestion;
}

@property (nonatomic, readonly) long long assetCollectionType;
@property (nonatomic, readonly) bool canContainAssets;
@property (nonatomic, readonly) bool canContainCollections;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDate *endDate;
@property (nonatomic, readonly) unsigned long long estimatedAssetCount;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isAggregation;
@property (nonatomic, readonly) bool isEnriched;
@property (nonatomic, readonly) bool isEnrichmentComplete;
@property (nonatomic, readonly) bool isPrivacySensitiveAlbum;
@property (nonatomic, readonly) bool isRecent;
@property (nonatomic, readonly) NSString *localizedDateDescription;
@property (nonatomic, readonly) NSString *localizedDebugDescription;
@property (nonatomic, readonly) NSArray *localizedLocationNames;
@property (nonatomic, readonly) NSString *localizedSmartDescription;
@property (nonatomic, readonly) NSString *localizedSubtitle;
@property (nonatomic, readonly) NSString *localizedTitle;
@property (nonatomic, readonly) double promotionScore;
@property (nonatomic, readonly) bool px_allowsImplicitSelectionForProjectOrSharingAction;
@property (nonatomic, readonly) bool px_allowsMoveToPersonalLibrary;
@property (nonatomic, readonly) bool px_allowsMoveToSharedLibrary;
@property (nonatomic, readonly) bool px_canAddContent;
@property (nonatomic, readonly) bool px_canCreateContent;
@property (nonatomic, readonly) bool px_canDeleteContent;
@property (nonatomic, readonly) bool px_canRearrangeContent;
@property (nonatomic, readonly) bool px_canRemoveContent;
@property (nonatomic, readonly) id px_cheapLogIdentifier;
@property (nonatomic, readonly) bool px_containsPrivateContent;
@property (nonatomic, readonly) unsigned short px_highlightEnrichmentState;
@property (nonatomic, readonly) long long px_highlightKind;
@property (nonatomic, readonly) bool px_isAllLibraryDuplicatesSmartAlbum;
@property (nonatomic, readonly) bool px_isAllPhotosSmartAlbum;
@property (nonatomic, readonly) bool px_isAnimatedSmartAlbum;
@property (nonatomic, readonly) bool px_isBurstsSmartAlbum;
@property (nonatomic, readonly) bool px_isCinematicSmartAlbum;
@property (nonatomic, readonly) bool px_isCloudMultipleContributorsEnabled;
@property (nonatomic, readonly) bool px_isContentSyndicationAlbum;
@property (nonatomic, readonly) bool px_isContentSyndicationAllPhotosAlbum;
@property (nonatomic, readonly) bool px_isContentSyndicationFolder;
@property (nonatomic, readonly) bool px_isContentSyndicationVirtualCollection;
@property (nonatomic, readonly) bool px_isDayGroupHighlight;
@property (nonatomic, readonly) bool px_isDeletable;
@property (nonatomic, readonly) bool px_isDepthEffectSmartAlbum;
@property (nonatomic, readonly) bool px_isFavoritesSmartAlbum;
@property (nonatomic, readonly) bool px_isFolder;
@property (nonatomic, readonly) bool px_isForYouVirtualCollection;
@property (nonatomic, readonly) bool px_isHiddenSmartAlbum;
@property (nonatomic, readonly) bool px_isHighlight;
@property (nonatomic, readonly) bool px_isImportHistoryCollection;
@property (nonatomic, readonly) bool px_isImportSessionCollection;
@property (nonatomic, readonly) bool px_isImportedAlbum;
@property (nonatomic, readonly) bool px_isInReadWriteCloudLibrary;
@property (nonatomic, readonly) bool px_isLivePhotosSmartAlbum;
@property (nonatomic, readonly) bool px_isLongExposuresSmartAlbum;
@property (nonatomic, readonly) bool px_isMacSyncedAlbum;
@property (nonatomic, readonly) bool px_isMacSyncedEventsFolder;
@property (nonatomic, readonly) bool px_isMacSyncedFacesAlbum;
@property (nonatomic, readonly) bool px_isMacSyncedFacesFolder;
@property (nonatomic, readonly) bool px_isMacSyncedRegularAlbum;
@property (nonatomic, readonly) bool px_isMediaTypeSmartAlbum;
@property (nonatomic, readonly) bool px_isMediaTypesFolder;
@property (nonatomic, readonly) bool px_isMemoriesVirtualCollection;
@property (nonatomic, readonly) bool px_isMemory;
@property (nonatomic, readonly) bool px_isMoment;
@property (nonatomic, readonly) bool px_isMomentShare;
@property (nonatomic, readonly) bool px_isMomentShareVirtualCollection;
@property (nonatomic, readonly) bool px_isMomentsVirtualCollection;
@property (nonatomic, readonly) bool px_isMyAlbumsVirtualCollection;
@property (nonatomic, readonly) bool px_isMyPhotoStreamAlbum;
@property (nonatomic, readonly) bool px_isOwnedSharedAlbum;
@property (nonatomic, readonly) bool px_isPanoramasSmartAlbum;
@property (nonatomic, readonly) bool px_isPeopleVirtualCollection;
@property (nonatomic, readonly) bool px_isPhotosVirtualCollection;
@property (nonatomic, readonly) bool px_isPlacesSmartAlbum;
@property (nonatomic, readonly) bool px_isPrivacySensitiveAlbum;
@property (nonatomic, readonly) bool px_isProResSmartAlbum;
@property (nonatomic, readonly) bool px_isProject;
@property (nonatomic, readonly) bool px_isProjectsFolder;
@property (nonatomic, readonly) bool px_isRAWSmartAlbum;
@property (nonatomic, readonly) bool px_isRecentMomentsVirtualCollection;
@property (nonatomic, readonly) bool px_isRecentlyAddedSmartAlbum;
@property (nonatomic, readonly) bool px_isRecentlyDeletedSmartAlbum;
@property (nonatomic, readonly) bool px_isRecentlyEditedSmartAlbum;
@property (nonatomic, readonly) bool px_isRecentsSmartAlbum;
@property (nonatomic, readonly) bool px_isRegularAlbum;
@property (nonatomic, readonly) bool px_isRegularFolder;
@property (nonatomic, readonly) bool px_isRenamable;
@property (nonatomic, readonly) bool px_isRootSmartAlbum;
@property (nonatomic, readonly) bool px_isScreenRecordingsSmartAlbum;
@property (nonatomic, readonly) bool px_isScreenshotsSmartAlbum;
@property (nonatomic, readonly) bool px_isSelfPortraitsSmartAlbum;
@property (nonatomic, readonly) bool px_isSharedActivityVirtualCollection;
@property (nonatomic, readonly) bool px_isSharedAlbum;
@property (nonatomic, readonly) bool px_isSharedAlbumsAndActivityFolder;
@property (nonatomic, readonly) bool px_isSharedAlbumsFolder;
@property (nonatomic, readonly) bool px_isSharedAlbumsVirtualCollection;
@property (nonatomic, readonly) bool px_isSharedLibrarySharingSuggestion;
@property (nonatomic, readonly) bool px_isSharedLibrarySharingSuggestionsSmartAlbum;
@property (nonatomic, readonly) bool px_isSlomoVideosSmartAlbum;
@property (nonatomic, readonly) bool px_isSmartAlbum;
@property (nonatomic, readonly) bool px_isSmartFolder;
@property (nonatomic, readonly) bool px_isSpatialSmartAlbum;
@property (nonatomic, readonly) bool px_isSuggestion;
@property (nonatomic, readonly) bool px_isTimelapsesSmartAlbum;
@property (nonatomic, readonly) bool px_isTopLevelFolder;
@property (nonatomic, readonly) bool px_isTransientPlacesCollection;
@property (nonatomic, readonly) bool px_isUnableToUploadSmartAlbum;
@property (nonatomic, readonly) bool px_isUserCreated;
@property (nonatomic, readonly) bool px_isUserSmartAlbum;
@property (nonatomic, readonly) bool px_isVideosSmartAlbum;
@property (nonatomic, readonly) bool px_shouldUseFacesRectForSmartCropping;
@property (nonatomic, readonly) bool px_supportsFastCuration;
@property (nonatomic, readonly) NSDate *startDate;
@property (nonatomic, readonly) long long subtype;
@property (readonly) Class superclass;
@property (nonatomic, readonly) long long type;
@property (nonatomic, readonly) NSString *uuid;

- (void).cxx_destruct;
- (long long)assetCollectionType;
- (bool)canContainAssets;
- (bool)canContainCollections;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)endDate;
- (unsigned long long)estimatedAssetCount;
- (id)init;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 type:(long long)arg3 subtype:(long long)arg4;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 type:(long long)arg3 subtype:(long long)arg4 startDate:(id)arg5 endDate:(id)arg6;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 type:(long long)arg3 subtype:(long long)arg4 startDate:(id)arg5 endDate:(id)arg6 isPrivacySensitiveAlbum:(bool)arg7;
- (bool)isAggregation;
- (bool)isEnriched;
- (bool)isEnrichmentComplete;
- (bool)isPrivacySensitiveAlbum;
- (bool)isRecent;
- (id)localizedDateDescription;
- (id)localizedDateDescriptionWithOptions:(unsigned long long)arg1;
- (id)localizedDebugDescription;
- (id)localizedLocationNames;
- (id)localizedSmartDescription;
- (id)localizedSubtitle;
- (id)localizedTitle;
- (double)promotionScore;
- (bool)px_allowsImplicitSelectionForProjectOrSharingAction;
- (bool)px_allowsMoveToPersonalLibrary;
- (bool)px_allowsMoveToSharedLibrary;
- (bool)px_canAddContent;
- (bool)px_canCreateContent;
- (bool)px_canDeleteContent;
- (bool)px_canRearrangeContent;
- (bool)px_canRemoveContent;
- (id)px_cheapLogIdentifier;
- (bool)px_containsPrivateContent;
- (unsigned short)px_highlightEnrichmentState;
- (long long)px_highlightKind;
- (bool)px_isAllLibraryDuplicatesSmartAlbum;
- (bool)px_isAllPhotosSmartAlbum;
- (bool)px_isAnimatedSmartAlbum;
- (bool)px_isBurstsSmartAlbum;
- (bool)px_isCinematicSmartAlbum;
- (bool)px_isCloudMultipleContributorsEnabled;
- (bool)px_isContentSyndicationAlbum;
- (bool)px_isContentSyndicationAllPhotosAlbum;
- (bool)px_isContentSyndicationFolder;
- (bool)px_isContentSyndicationVirtualCollection;
- (bool)px_isDayGroupHighlight;
- (bool)px_isDeletable;
- (bool)px_isDepthEffectSmartAlbum;
- (bool)px_isFavoritesSmartAlbum;
- (bool)px_isFolder;
- (bool)px_isForYouVirtualCollection;
- (bool)px_isHiddenSmartAlbum;
- (bool)px_isHighlight;
- (bool)px_isImportHistoryCollection;
- (bool)px_isImportSessionCollection;
- (bool)px_isImportedAlbum;
- (bool)px_isInReadWriteCloudLibrary;
- (bool)px_isLivePhotosSmartAlbum;
- (bool)px_isLongExposuresSmartAlbum;
- (bool)px_isMacSyncedAlbum;
- (bool)px_isMacSyncedEventsFolder;
- (bool)px_isMacSyncedFacesAlbum;
- (bool)px_isMacSyncedFacesFolder;
- (bool)px_isMacSyncedRegularAlbum;
- (bool)px_isMediaTypeSmartAlbum;
- (bool)px_isMediaTypesFolder;
- (bool)px_isMemoriesVirtualCollection;
- (bool)px_isMemory;
- (bool)px_isMoment;
- (bool)px_isMomentShare;
- (bool)px_isMomentShareVirtualCollection;
- (bool)px_isMomentsVirtualCollection;
- (bool)px_isMyAlbumsVirtualCollection;
- (bool)px_isMyPhotoStreamAlbum;
- (bool)px_isOwnedSharedAlbum;
- (bool)px_isPanoramasSmartAlbum;
- (bool)px_isPeopleVirtualCollection;
- (bool)px_isPhotosVirtualCollection;
- (bool)px_isPlacesSmartAlbum;
- (bool)px_isPrivacySensitiveAlbum;
- (bool)px_isProResSmartAlbum;
- (bool)px_isProject;
- (bool)px_isProjectsFolder;
- (bool)px_isRAWSmartAlbum;
- (bool)px_isRecentMomentsVirtualCollection;
- (bool)px_isRecentlyAddedSmartAlbum;
- (bool)px_isRecentlyDeletedSmartAlbum;
- (bool)px_isRecentlyEditedSmartAlbum;
- (bool)px_isRecentsSmartAlbum;
- (bool)px_isRegularAlbum;
- (bool)px_isRegularFolder;
- (bool)px_isRenamable;
- (bool)px_isRootSmartAlbum;
- (bool)px_isScreenRecordingsSmartAlbum;
- (bool)px_isScreenshotsSmartAlbum;
- (bool)px_isSelfPortraitsSmartAlbum;
- (bool)px_isSharedActivityVirtualCollection;
- (bool)px_isSharedAlbum;
- (bool)px_isSharedAlbumsAndActivityFolder;
- (bool)px_isSharedAlbumsFolder;
- (bool)px_isSharedAlbumsVirtualCollection;
- (bool)px_isSharedLibrarySharingSuggestion;
- (bool)px_isSharedLibrarySharingSuggestionsSmartAlbum;
- (bool)px_isSlomoVideosSmartAlbum;
- (bool)px_isSmartAlbum;
- (bool)px_isSmartFolder;
- (bool)px_isSpatialSmartAlbum;
- (bool)px_isSuggestion;
- (bool)px_isTimelapsesSmartAlbum;
- (bool)px_isTopLevelFolder;
- (bool)px_isTransientPlacesCollection;
- (bool)px_isUnableToUploadSmartAlbum;
- (bool)px_isUserCreated;
- (bool)px_isUserSmartAlbum;
- (bool)px_isVideosSmartAlbum;
- (bool)px_shouldUseFacesRectForSmartCropping;
- (bool)px_supportsFastCuration;
- (id)startDate;
- (long long)subtype;
- (long long)type;
- (id)uuid;

@end
