
@interface PXPhotosDetailsCaptionHashtagsWidget : NSObject <PXCaptionHashtagsEntryViewDelegate, PXPhotoLibraryUIChangeObserver, PXWidget> {
    PHAsset * _asset;
    _PXUIContainerView * _containerView;
    struct CGSize { 
        double width; 
        double height; 
    }  _contentSize;
    PXPhotosDetailsContext * _context;
    id /* block */  _deferredAppearingAnimation;
    long long  _exitEditChangesSavingMode;
    bool  _isInEditMode;
    struct CGSize { 
        double width; 
        double height; 
    }  _maxVisibleSizeInEditMode;
    UIView * _separatorView;
    PXWidgetSpec * _spec;
    PXCaptionHashtagsEntryView * _textEntryView;
    UIView * _textViewContainer;
    <PXWidgetDelegate> * _widgetDelegate;
    <PXWidgetEditingDelegate> * _widgetEditingDelegate;
}

@property (nonatomic, readonly) bool allowUserInteractionWithSubtitle;
@property (retain) PHAsset *asset;
@property (nonatomic, readonly) PXAssetActionManager *assetActionManager;
@property (nonatomic, readonly) _PXUIContainerView *containerView;
@property (nonatomic, readonly) long long contentLayoutStyle;
@property (nonatomic) struct CGSize { double x1; double x2; } contentSize;
@property (nonatomic, readonly) PXTilingController *contentTilingController;
@property (nonatomic, readonly) NSObject<PXAnonymousView> *contentView;
@property (nonatomic, readonly) long long contentViewAnchoringType;
@property (nonatomic, retain) PXPhotosDetailsContext *context;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, copy) id /* block */ deferredAppearingAnimation;
@property (readonly, copy) NSString *description;
@property (nonatomic) long long exitEditChangesSavingMode;
@property (nonatomic, readonly) double extraSpaceNeededAtContentBottom;
@property (getter=isFaceModeEnabled, nonatomic) bool faceModeEnabled;
@property (nonatomic, readonly) bool hasContentForCurrentInput;
@property (nonatomic, readonly) bool hasLoadedContentData;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isInEditMode;
@property (nonatomic, readonly) NSString *localizedCaption;
@property (nonatomic, readonly) NSString *localizedDisclosureTitle;
@property (nonatomic, readonly) NSString *localizedSubtitle;
@property (nonatomic, readonly) NSString *localizedTitle;
@property (nonatomic) struct CGSize { double x1; double x2; } maxVisibleSizeInEditMode;
@property (getter=isSelecting, nonatomic) bool selecting;
@property (nonatomic, readonly) PXSectionedSelectionManager *selectionManager;
@property (nonatomic, retain) UIView *separatorView;
@property (nonatomic, readonly) NSString *snappableWidgetIdentifier;
@property (nonatomic, retain) PXWidgetSpec *spec;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool supportsFaceMode;
@property (nonatomic, readonly) bool supportsSelection;
@property (nonatomic, readonly) PXCaptionHashtagsEntryView *textEntryView;
@property (nonatomic, readonly) UIView *textViewContainer;
@property (getter=isUserInteractionEnabled, nonatomic) bool userInteractionEnabled;
@property (nonatomic, readonly) bool wantsFocus;
@property (nonatomic, readonly) bool wantsNoSpaceAfterContentBottom;
@property (nonatomic) <PXWidgetDelegate> *widgetDelegate;
@property (nonatomic) <PXWidgetEditingDelegate> *widgetEditingDelegate;
@property (nonatomic) <PXWidgetInteractionDelegate> *widgetInteractionDelegate;
@property (nonatomic) <PXWidgetUnlockDelegate> *widgetUnlockDelegate;

- (void).cxx_destruct;
- (void)_addSeparatorView;
- (void)_applySpec;
- (void)_configureFadeInAnimation;
- (void)_configureTextViewVisibility:(bool)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_contentInsets;
- (bool)_fadeInEnabled;
- (void)_logCPAnalyticsEventsForCommittedCaption:(id)arg1 numOfHashtags:(unsigned long long)arg2;
- (bool)_prefersFloatingiPadInfoPanelLayout;
- (void)_removeSeparatorView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_textEntryViewFrameForSize:(struct CGSize { double x1; double x2; })arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_textViewContainerInsets;
- (id)asset;
- (bool)canSnapToEdges;
- (void)captionHashtagsEntryViewDidBeginEditing:(id)arg1;
- (void)captionHashtagsEntryViewDidEndEditing:(id)arg1;
- (void)captionHashtagsEntryViewPreferredHeightDidChange:(id)arg1;
- (void)captionHashtagsEntryViewRequestFocus:(id)arg1;
- (bool)captionHashtagsEntryViewShouldBeginEditing:(id)arg1;
- (bool)captionHashtagsEntryViewShouldEndEditing:(id)arg1;
- (void)captionHashtagsEntryViewWillBeginEditing:(id)arg1;
- (id)containerView;
- (struct CGSize { double x1; double x2; })contentSize;
- (id)contentView;
- (void)contentViewDidDisappear;
- (void)contentViewWillAppear;
- (void)contentViewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (id)context;
- (double)currentContentHeight;
- (id /* block */)deferredAppearingAnimation;
- (long long)exitEditChangesSavingMode;
- (bool)hasContentForCurrentInput;
- (id)init;
- (bool)isInEditMode;
- (void)loadContentData;
- (struct CGSize { double x1; double x2; })maxVisibleSizeInEditMode;
- (void)photoLibraryDidChangeOnMainQueue:(id)arg1 withPreparedInfo:(id)arg2;
- (double)preferredContentHeightForWidth:(double)arg1;
- (id)prepareForPhotoLibraryChange:(id)arg1;
- (void)requestExitEditWithChangesSavingMode:(long long)arg1;
- (id)separatorView;
- (void)setAsset:(id)arg1;
- (void)setContentSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setContext:(id)arg1;
- (void)setDeferredAppearingAnimation:(id /* block */)arg1;
- (void)setExitEditChangesSavingMode:(long long)arg1;
- (void)setMaxVisibleSizeInEditMode:(struct CGSize { double x1; double x2; })arg1;
- (void)setSeparatorView:(id)arg1;
- (void)setSpec:(id)arg1;
- (void)setWidgetDelegate:(id)arg1;
- (void)setWidgetEditingDelegate:(id)arg1;
- (id)snappableWidgetIdentifier;
- (id)spec;
- (id)textEntryView;
- (id)textViewContainer;
- (void)unloadContentData;
- (bool)wantsFocus;
- (id)widgetDelegate;
- (id)widgetEditingDelegate;

@end
