
@interface TPPBPeerStableInfo : PBCodable <NSCopying> {
    unsigned long long  _clock;
    NSMutableArray * _custodianRecoveryKeys;
    NSString * _deviceName;
    NSString * _flexiblePolicyHash;
    unsigned long long  _flexiblePolicyVersion;
    NSString * _frozenPolicyHash;
    unsigned long long  _frozenPolicyVersion;
    struct { 
        unsigned int clock : 1; 
        unsigned int flexiblePolicyVersion : 1; 
        unsigned int frozenPolicyVersion : 1; 
        unsigned int userControllableViewStatus : 1; 
        unsigned int isInheritedAccount : 1; 
    }  _has;
    bool  _isInheritedAccount;
    NSString * _osVersion;
    NSMutableArray * _policySecrets;
    NSData * _recoveryEncryptionPublicKey;
    NSData * _recoverySigningPublicKey;
    TPPBSecureElementIdentity * _secureElementIdentity;
    NSString * _serialNumber;
    int  _userControllableViewStatus;
    TPPBPeerStableInfoSetting * _walrus;
    TPPBPeerStableInfoSetting * _webAccess;
}

@property (nonatomic) unsigned long long clock;
@property (nonatomic, retain) NSMutableArray *custodianRecoveryKeys;
@property (nonatomic, retain) NSString *deviceName;
@property (nonatomic, retain) NSString *flexiblePolicyHash;
@property (nonatomic) unsigned long long flexiblePolicyVersion;
@property (nonatomic, retain) NSString *frozenPolicyHash;
@property (nonatomic) unsigned long long frozenPolicyVersion;
@property (nonatomic) bool hasClock;
@property (nonatomic, readonly) bool hasDeviceName;
@property (nonatomic, readonly) bool hasFlexiblePolicyHash;
@property (nonatomic) bool hasFlexiblePolicyVersion;
@property (nonatomic, readonly) bool hasFrozenPolicyHash;
@property (nonatomic) bool hasFrozenPolicyVersion;
@property (nonatomic) bool hasIsInheritedAccount;
@property (nonatomic, readonly) bool hasOsVersion;
@property (nonatomic, readonly) bool hasRecoveryEncryptionPublicKey;
@property (nonatomic, readonly) bool hasRecoverySigningPublicKey;
@property (nonatomic, readonly) bool hasSecureElementIdentity;
@property (nonatomic, readonly) bool hasSerialNumber;
@property (nonatomic) bool hasUserControllableViewStatus;
@property (nonatomic, readonly) bool hasWalrus;
@property (nonatomic, readonly) bool hasWebAccess;
@property (nonatomic) bool isInheritedAccount;
@property (nonatomic, retain) NSString *osVersion;
@property (nonatomic, retain) NSMutableArray *policySecrets;
@property (nonatomic, retain) NSData *recoveryEncryptionPublicKey;
@property (nonatomic, retain) NSData *recoverySigningPublicKey;
@property (nonatomic, retain) TPPBSecureElementIdentity *secureElementIdentity;
@property (nonatomic, retain) NSString *serialNumber;
@property (nonatomic) int userControllableViewStatus;
@property (nonatomic, retain) TPPBPeerStableInfoSetting *walrus;
@property (nonatomic, retain) TPPBPeerStableInfoSetting *webAccess;

+ (Class)custodianRecoveryKeysType;
+ (Class)policySecretsType;

- (void).cxx_destruct;
- (int)StringAsUserControllableViewStatus:(id)arg1;
- (void)addCustodianRecoveryKeys:(id)arg1;
- (void)addPolicySecrets:(id)arg1;
- (void)clearCustodianRecoveryKeys;
- (void)clearPolicySecrets;
- (unsigned long long)clock;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)custodianRecoveryKeys;
- (id)custodianRecoveryKeysAtIndex:(unsigned long long)arg1;
- (unsigned long long)custodianRecoveryKeysCount;
- (id)description;
- (id)deviceName;
- (id)dictionaryRepresentation;
- (id)flexiblePolicyHash;
- (unsigned long long)flexiblePolicyVersion;
- (id)frozenPolicyHash;
- (unsigned long long)frozenPolicyVersion;
- (bool)hasClock;
- (bool)hasDeviceName;
- (bool)hasFlexiblePolicyHash;
- (bool)hasFlexiblePolicyVersion;
- (bool)hasFrozenPolicyHash;
- (bool)hasFrozenPolicyVersion;
- (bool)hasIsInheritedAccount;
- (bool)hasOsVersion;
- (bool)hasRecoveryEncryptionPublicKey;
- (bool)hasRecoverySigningPublicKey;
- (bool)hasSecureElementIdentity;
- (bool)hasSerialNumber;
- (bool)hasUserControllableViewStatus;
- (bool)hasWalrus;
- (bool)hasWebAccess;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (bool)isInheritedAccount;
- (void)mergeFrom:(id)arg1;
- (id)osVersion;
- (id)policySecrets;
- (id)policySecretsAtIndex:(unsigned long long)arg1;
- (unsigned long long)policySecretsCount;
- (bool)readFrom:(id)arg1;
- (id)recoveryEncryptionPublicKey;
- (id)recoverySigningPublicKey;
- (id)secureElementIdentity;
- (id)serialNumber;
- (void)setClock:(unsigned long long)arg1;
- (void)setCustodianRecoveryKeys:(id)arg1;
- (void)setDeviceName:(id)arg1;
- (void)setFlexiblePolicyHash:(id)arg1;
- (void)setFlexiblePolicyVersion:(unsigned long long)arg1;
- (void)setFrozenPolicyHash:(id)arg1;
- (void)setFrozenPolicyVersion:(unsigned long long)arg1;
- (void)setHasClock:(bool)arg1;
- (void)setHasFlexiblePolicyVersion:(bool)arg1;
- (void)setHasFrozenPolicyVersion:(bool)arg1;
- (void)setHasIsInheritedAccount:(bool)arg1;
- (void)setHasUserControllableViewStatus:(bool)arg1;
- (void)setIsInheritedAccount:(bool)arg1;
- (void)setOsVersion:(id)arg1;
- (void)setPolicySecrets:(id)arg1;
- (void)setRecoveryEncryptionPublicKey:(id)arg1;
- (void)setRecoverySigningPublicKey:(id)arg1;
- (void)setSecureElementIdentity:(id)arg1;
- (void)setSerialNumber:(id)arg1;
- (void)setUserControllableViewStatus:(int)arg1;
- (void)setWalrus:(id)arg1;
- (void)setWebAccess:(id)arg1;
- (int)userControllableViewStatus;
- (id)userControllableViewStatusAsString:(int)arg1;
- (id)walrus;
- (id)webAccess;
- (void)writeTo:(id)arg1;

@end
