
@interface _UICollectionViewListLayoutSectionConfiguration : NSObject <NSCopying> {
    bool  __apiVersion;
    UIColor * __backgroundColor;
    NSString * __footerElementKind;
    NSString * __headerElementKind;
    long long  _appearanceStyle;
    UICollectionView * _collectionView;
    double  _cornerRadius;
    id /* block */  _didEndSwipingHandler;
    double  _estimatedRowHeight;
    double  _estimatedSectionFooterHeight;
    double  _estimatedSectionHeaderHeight;
    double  _headerTopPadding;
    NSArray * _itemHeights;
    id /* block */  _itemSeparatorHandler;
    <NSCollectionLayoutEnvironment_Private> * _layoutEnvironment;
    id /* block */  _leadingSwipeActionsConfigurationProvider;
    double  _rowHeight;
    double  _sectionFooterHeight;
    double  _sectionHeaderHeight;
    _UIListSeparatorConfiguration * _separatorConfiguration;
    id /* block */  _separatorInsetProvider;
    long long  _separatorStyle;
    bool  _stylesFirstItemAsHeader;
    id /* block */  _trailingSwipeActionsConfigurationProvider;
    id /* block */  _willBeginSwipingHandler;
}

@property (getter=_isAPIVersion, nonatomic) bool _apiVersion;
@property (nonatomic, retain) UIColor *_backgroundColor;
@property (nonatomic, copy) NSString *_footerElementKind;
@property (nonatomic, copy) NSString *_headerElementKind;
@property (getter=_itemSeparatorHandler, setter=_setItemSeparatorHandler:, nonatomic, copy) id /* block */ _itemSeparatorHandler;
@property (getter=_separatorConfiguration, setter=_setSeparatorConfiguration:, nonatomic, copy) _UIListSeparatorConfiguration *_separatorConfiguration;
@property (getter=_separatorConfigurationNoCopy, nonatomic, readonly) _UIListSeparatorConfiguration *_separatorConfigurationNoCopy;
@property (nonatomic) long long appearanceStyle;
@property (getter=_collectionView, nonatomic, readonly) UICollectionView *collectionView;
@property (getter=_constants, nonatomic, readonly) <UITableConstants> *constants;
@property (nonatomic) double cornerRadius;
@property (nonatomic, copy) id /* block */ didEndSwipingHandler;
@property (nonatomic) double estimatedRowHeight;
@property (nonatomic) double estimatedSectionFooterHeight;
@property (nonatomic) double estimatedSectionHeaderHeight;
@property (nonatomic) double headerTopPadding;
@property (getter=_itemHeights, setter=_setItemHeights:, nonatomic, copy) NSArray *itemHeights;
@property (getter=_layoutEnvironment, nonatomic, readonly) <NSCollectionLayoutEnvironment_Private> *layoutEnvironment;
@property (nonatomic, copy) id /* block */ leadingSwipeActionsConfigurationProvider;
@property (nonatomic) double rowHeight;
@property (nonatomic) double sectionFooterHeight;
@property (nonatomic) double sectionHeaderHeight;
@property (nonatomic) struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; } separatorInset;
@property (nonatomic, copy) id /* block */ separatorInsetProvider;
@property (nonatomic) long long separatorStyle;
@property (nonatomic) bool stylesFirstItemAsHeader;
@property (nonatomic, copy) id /* block */ trailingSwipeActionsConfigurationProvider;
@property (getter=_wantsSwipeActions, nonatomic, readonly) bool wantsSwipeActions;
@property (nonatomic, copy) id /* block */ willBeginSwipingHandler;

+ (id)new;

- (void).cxx_destruct;
- (void)_addSupplementaryItemsToLayout:(id)arg1;
- (id)_backgroundColor;
- (id)_collectionView;
- (id)_constants;
- (id)_createSeparatorForBottom:(bool)arg1;
- (id)_createSwipeActionsContainer;
- (long long)_defaultContentInsetsReference;
- (double)_defaultRowHeight;
- (double)_defaultSectionFooterHeight;
- (double)_defaultSectionHeaderHeight;
- (long long)_defaultSeparatorStyleForAppearanceStyle:(long long)arg1;
- (double)_effectiveEstimatedRowHeight;
- (double)_effectiveEstimatedSectionFooterHeight;
- (double)_effectiveEstimatedSectionHeaderHeight;
- (id)_footerElementKind;
- (id)_generateLayoutGroup:(id)arg1;
- (bool)_hasFooter;
- (bool)_hasHeaderOrFirstItemStyledAsHeader;
- (bool)_hasSupplementaryAsHeader;
- (id)_headerElementKind;
- (bool)_isAPIVersion;
- (id)_itemHeights;
- (id /* block */)_itemSeparatorHandler;
- (id)_layoutEnvironment;
- (struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })_sectionContentInsetsForAppearanceStyleWithDefaultInsets:(struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })_sectionContentInsetsForVerticallySeparatedSectionsWithDefaultInsets:(struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (id)_separatorConfiguration;
- (id)_separatorConfigurationNoCopy;
- (double)_separatorHeight;
- (void)_setItemHeights:(id)arg1;
- (void)_setItemSeparatorHandler:(id /* block */)arg1;
- (void)_setSeparatorConfiguration:(id)arg1;
- (bool)_shouldDrawThickSeparators;
- (bool)_shouldPinSupplementaries;
- (bool)_shouldSupplementariesFollowSectionInsets;
- (double)_topContentInsetForGroupedAppearance;
- (double)_topContentInsetForPaddingAboveHeader;
- (id)_traitCollection;
- (bool)_usesSectionBackgroundDecoration;
- (bool)_wantsSwipeActions;
- (long long)appearanceStyle;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)cornerRadius;
- (id /* block */)didEndSwipingHandler;
- (double)estimatedRowHeight;
- (double)estimatedSectionFooterHeight;
- (double)estimatedSectionHeaderHeight;
- (double)headerTopPadding;
- (id)init;
- (id)initWithAppearanceStyle:(long long)arg1 layoutEnvironment:(id)arg2;
- (id)initWithCollectionView:(id)arg1;
- (id /* block */)leadingSwipeActionsConfigurationProvider;
- (double)rowHeight;
- (double)sectionFooterHeight;
- (double)sectionHeaderHeight;
- (struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })separatorInset;
- (id /* block */)separatorInsetProvider;
- (long long)separatorStyle;
- (void)setAppearanceStyle:(long long)arg1;
- (void)setCornerRadius:(double)arg1;
- (void)setDidEndSwipingHandler:(id /* block */)arg1;
- (void)setEstimatedRowHeight:(double)arg1;
- (void)setEstimatedSectionFooterHeight:(double)arg1;
- (void)setEstimatedSectionHeaderHeight:(double)arg1;
- (void)setHeaderTopPadding:(double)arg1;
- (void)setLeadingSwipeActionsConfigurationProvider:(id /* block */)arg1;
- (void)setRowHeight:(double)arg1;
- (void)setSectionFooterHeight:(double)arg1;
- (void)setSectionHeaderHeight:(double)arg1;
- (void)setSeparatorInset:(struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setSeparatorInsetProvider:(id /* block */)arg1;
- (void)setSeparatorStyle:(long long)arg1;
- (void)setStylesFirstItemAsHeader:(bool)arg1;
- (void)setTrailingSwipeActionsConfigurationProvider:(id /* block */)arg1;
- (void)setWillBeginSwipingHandler:(id /* block */)arg1;
- (void)set_apiVersion:(bool)arg1;
- (void)set_backgroundColor:(id)arg1;
- (void)set_footerElementKind:(id)arg1;
- (void)set_headerElementKind:(id)arg1;
- (bool)stylesFirstItemAsHeader;
- (id /* block */)trailingSwipeActionsConfigurationProvider;
- (id /* block */)willBeginSwipingHandler;

@end
