
@interface _UINavigationBarTitleControl : UIControl <_UITAMICAdaptorViewDelegate> {
    UIView * _backgroundView;
    NSArray * _backgroundViewConstraints;
    UIImageView * _chevron;
    NSArray * _chevronConstraints;
    UILayoutGuide * _chevronGuide;
    double  _contentAlpha;
    UIDocumentProperties * _documentProperties;
    UIView * _effectiveTitleView;
    NSArray * _inlineTitleConstraints;
    UILabel * _inlineTitleView;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _menuAlignmentInsets;
    NSDictionary * _resolvedAttributes;
    NSLayoutConstraint * _sosConstraint;
    NSString * _title;
    NSDictionary * _titleAttributes;
    NSArray * _titleConstraints;
    UILayoutGuide * _titleLayoutGuide;
    id /* block */  _titleMenuProvider;
    UIView * _titleView;
    float  _titleViewCompressionResistancePriority;
    <_UINavigationBarTitleControlVisualProvider> * _visualProvider;
    _UITAMICAdaptorView * _wrapperView;
}

@property (nonatomic) double contentAlpha;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UIDocumentProperties *documentProperties;
@property (nonatomic, readonly) UIView *effectiveTitleView;
@property (nonatomic, readonly) bool hasBaseline;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isInteractive;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } menuAlignmentInsets;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, copy) NSDictionary *titleAttributes;
@property (nonatomic, readonly) UILabel *titleLabel;
@property (nonatomic, retain) UILayoutGuide *titleLayoutGuide;
@property (nonatomic, copy) id /* block */ titleMenuProvider;
@property (nonatomic, retain) UIView *titleView;
@property (nonatomic) float titleViewCompressionResistancePriority;
@property (nonatomic, readonly) double trailingPadding;
@property (nonatomic, retain) <_UINavigationBarTitleControlVisualProvider> *visualProvider;

+ (id)titleMenuSuggestedActionsWithDocumentFileURL:(id)arg1;

- (void).cxx_destruct;
- (id)_backgroundViewConstraintsForIdiom:(long long)arg1;
- (id)_baselineView;
- (void)_cleanupWrapperView;
- (id)_contextMenuInteraction:(id)arg1 overrideSuggestedActionsForConfiguration:(id)arg2;
- (id)_contextMenuInteraction:(id)arg1 styleForMenuWithConfiguration:(id)arg2;
- (unsigned long long)_controlEventsForActionTriggered;
- (id)_debugInfo;
- (void)_ensureNecessaryViews;
- (bool)_inactiveForPointer;
- (void)_invalidateSceneDraggingBehavior;
- (id)_preferredPresentationSourceItem;
- (id)_preferredSender;
- (id)_preview;
- (void)_resetTitleViewConstraints;
- (void)_updateContentAlpha;
- (void)_updateInlineTitleView;
- (void)_updateInteractions;
- (struct CGSize { double x1; double x2; })availableSizeForAdaptor:(id)arg1 proposedSize:(struct CGSize { double x1; double x2; })arg2;
- (double)contentAlpha;
- (id)contextMenuInteraction:(id)arg1 configurationForMenuAtLocation:(struct CGPoint { double x1; double x2; })arg2;
- (id)contextMenuInteraction:(id)arg1 previewForDismissingMenuWithConfiguration:(id)arg2;
- (id)contextMenuInteraction:(id)arg1 previewForHighlightingMenuWithConfiguration:(id)arg2;
- (void)didMoveToWindow;
- (id)documentProperties;
- (id)effectiveTitleView;
- (bool)hasBaseline;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isInteractive;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })menuAlignmentInsets;
- (struct CGPoint { double x1; double x2; })menuAttachmentPointForConfiguration:(id)arg1;
- (id)pointerInteraction:(id)arg1 regionForRequest:(id)arg2 defaultRegion:(id)arg3;
- (id)pointerInteraction:(id)arg1 styleForRegion:(id)arg2;
- (void)pointerInteraction:(id)arg1 willEnterRegion:(id)arg2 animator:(id)arg3;
- (void)pointerInteraction:(id)arg1 willExitRegion:(id)arg2 animator:(id)arg3;
- (id)pointerShapeInContainer:(id)arg1;
- (void)setContentAlpha:(double)arg1;
- (void)setDocumentProperties:(id)arg1;
- (void)setHighlighted:(bool)arg1;
- (void)setMenuAlignmentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setTitle:(id)arg1;
- (void)setTitleAttributes:(id)arg1;
- (void)setTitleLayoutGuide:(id)arg1;
- (void)setTitleMenuProvider:(id /* block */)arg1;
- (void)setTitleView:(id)arg1;
- (void)setTitleViewCompressionResistancePriority:(float)arg1;
- (void)setVisualProvider:(id)arg1;
- (id)title;
- (id)titleAttributes;
- (id)titleLabel;
- (id)titleLayoutGuide;
- (id /* block */)titleMenuProvider;
- (id)titleView;
- (float)titleViewCompressionResistancePriority;
- (double)trailingPadding;
- (void)updateConstraints;
- (id)viewForFirstBaselineLayout;
- (id)viewForLastBaselineLayout;
- (id)visualProvider;

@end
