
@interface UICollectionView : UIScrollView <UIDataSourceTranslating, _UICollectionTableIndexOverlayHost, _UICollectionViewSubviewManagerDelegate, _UIDataSourceBackedView, _UIHorizontalIndexTitleBarDelegate, _UIKeyboardAutoRespondingScrollView, _UISelectionInteractionDelegate, _UIUpdateCycleIdleObserver> {
    _UICollectionViewPrefetchingContext * _activeOrthogonalPrefetchingContext;
    NSTimer * _autoscrollTimer;
    UIView * _backgroundView;
    NSIndexPath * _cancellingToIndexPath;
    UICollectionViewCell * _cellBeingReconfigured;
    NSMutableDictionary * _cellClassDict;
    NSMutableDictionary * _cellNibDict;
    NSMutableDictionary * _cellNibExternalObjectsTables;
    NSMutableDictionary * _cellReuseQueues;
    NSMutableDictionary * _clonedCellsDict;
    NSMutableDictionary * _clonedDecorationViewsDict;
    NSMutableDictionary * _clonedSupplementaryViewsDict;
    UICollectionViewData * _collectionViewData;
    struct { 
        unsigned int delegateShouldHighlightItemAtIndexPath : 1; 
        unsigned int delegateDidHighlightItemAtIndexPath : 1; 
        unsigned int delegateDidUnhighlightItemAtIndexPath : 1; 
        unsigned int delegateShouldSelectItemAtIndexPath : 1; 
        unsigned int delegateShouldDeselectItemAtIndexPath : 1; 
        unsigned int delegateDidSelectItemAtIndexPath : 1; 
        unsigned int delegateDidDeselectItemAtIndexPath : 1; 
        unsigned int delegateSupportsMenus : 1; 
        unsigned int delegateWillDisplayCell : 1; 
        unsigned int delegateWillDisplaySupplementaryView : 1; 
        unsigned int delegateDidEndDisplayingCell : 1; 
        unsigned int delegateDidEndDisplayingSupplementaryView : 1; 
        unsigned int delegateIndexForReferenceItemDuringLayoutTransition : 1; 
        unsigned int delegateOverrideForTransitionOffsetSize : 1; 
        unsigned int delegateTargetContentOffsetForProposedContentOffsetSPI : 1; 
        unsigned int delegateTargetContentOffsetForProposedContentOffset : 1; 
        unsigned int delegateTargetIndexPathForMoveSPI : 1; 
        unsigned int delegateTargetIndexPathForMove_deprecated : 1; 
        unsigned int delegateTargetIndexPathForMoveOfItem : 1; 
        unsigned int delegateCanFocusItemAtIndexPath_deprecated : 1; 
        unsigned int delegateDidFocusItemAtIndexPath_deprecated : 1; 
        unsigned int delegateCanFocusItemAtIndexPath : 1; 
        unsigned int delegateDidFocusItemAtIndexPath : 1; 
        unsigned int delegateDidUnfocusItemAtIndexPath : 1; 
        unsigned int delegateIndexPathForPreferredFocusedItem : 1; 
        unsigned int delegateShouldUpdateFocusFromRowAtIndexPathToView : 1; 
        unsigned int delegateIndexPathForPreferredFocusedView : 1; 
        unsigned int delegateShouldUpdateFocusInContext : 1; 
        unsigned int delegateDidUpdateFocusInContext : 1; 
        unsigned int delegateHorizontalIndexTitleBarSelectedEntry : 1; 
        unsigned int delegateCanEditItemAtIndexPath : 1; 
        unsigned int delegateWasNonNil : 1; 
        unsigned int delegateContextMenuConfigurationForItemAtIndexPaths : 1; 
        unsigned int delegateContextMenuHighlightPreviewForItemAtIndexPath : 1; 
        unsigned int delegateContextMenuDismissalPreviewForItemAtIndexPath : 1; 
        unsigned int delegateContextMenuConfigurationForItemAtIndexPath_DEPR : 1; 
        unsigned int delegateContextMenuPreviewForHighlighting_DEPR : 1; 
        unsigned int delegateContextMenuPreviewForDismissing_DEPR : 1; 
        unsigned int delegateContextMenuwillPerformPreviewAction : 1; 
        unsigned int delegateWillDisplayContextMenu : 1; 
        unsigned int delegateWillEndContextMenuInteraction : 1; 
        unsigned int delegateStyleForContextMenu : 1; 
        unsigned int delegateAccessoriesForContextMenu : 1; 
        unsigned int delegate_dci_contextMenuConfigurationForItemsAtIndexPaths : 1; 
        unsigned int delegate_dci_contextMenuConfigurationForSelectedItemsAtIndexPaths : 1; 
        unsigned int delegate_dci_contextMenuPreviewForHighlightingItemAtIndexPath : 1; 
        unsigned int delegate_dci_contextMenuPreviewForDismissingToItemAtIndexPath : 1; 
        unsigned int delegateSceneActivationConfigurationAtIndexPath : 1; 
        unsigned int delegateSceneActivationConfigurationAtIndexPathSPI : 1; 
        unsigned int delegateOrthogonalScrollViewDidScrollSPI : 1; 
        unsigned int delegateSelectionFollowsFocusForItemAtIndexPath : 1; 
        unsigned int delegateCanPerformPrimaryActionForItemAtIndexPath : 1; 
        unsigned int delegatePerformPrimaryActionForItemAtIndexPath : 1; 
        unsigned int delegateIndexPathForContentOffsetPreservationSPI : 1; 
        unsigned int dataSourceNumberOfSections : 1; 
        unsigned int dataSourceViewForSupplementaryElement : 1; 
        unsigned int dataSourceCanMoveItemAtIndexPathSPI : 1; 
        unsigned int dataSourceMoveItemAtIndexPathSPI : 1; 
        unsigned int dataSourceSectionIndexTitlesSPI : 1; 
        unsigned int dataSourceSectionIndexTitlesTrimmedToCountSPI : 1; 
        unsigned int dataSourceIndexPathForSectionIndexSPI : 1; 
        unsigned int dataSourceCanMoveItemAtIndexPath : 1; 
        unsigned int dataSourceMoveItemAtIndexPath : 1; 
        unsigned int dataSourceIndexTitles : 1; 
        unsigned int dataSourceIndexPathForIndex : 1; 
        unsigned int dataSourceWasNonNil : 1; 
        unsigned int dataSourceIsDiffableDataSource : 1; 
        unsigned int dataSourceCanEditItemAtIndexPath : 1; 
        unsigned int prefetchDataSourcePrefetchItemsAtIndexPaths : 1; 
        unsigned int prefetchDataSourceCancelPrefetchingForItemsAtIndexPaths : 1; 
        unsigned int prefetchDataSourceWasNonNil : 1; 
        unsigned int reloadSkippedDuringSuspension : 1; 
        unsigned int scheduledUpdateVisibleCells : 1; 
        unsigned int scheduledUpdateVisibleCellLayoutAttributes : 1; 
        unsigned int allowsSelection : 1; 
        unsigned int allowsMultipleSelection : 1; 
        unsigned int allowsSelectionDuringEditing : 1; 
        unsigned int allowsUserInitiatedMultipleSelection : 1; 
        unsigned int allowsMultipleSelectionDuringEditing : 1; 
        unsigned int selectionFollowsFocus : 2; 
        unsigned int shouldBecomeFocusedOnSelection : 2; 
        unsigned int allowsFocus : 2; 
        unsigned int allowsFocusDuringEditing : 2; 
        unsigned int containsFocus : 1; 
        unsigned int displaysHorizontalIndexTitleBar : 1; 
        unsigned int fadeCellsForBoundsChange : 1; 
        unsigned int updatingLayout : 1; 
        unsigned int needsReload : 1; 
        unsigned int reloading : 1; 
        unsigned int skipLayoutDuringSnapshotting : 1; 
        unsigned int layoutInvalidatedSinceLastCellUpdate : 1; 
        unsigned int doneFirstLayout : 1; 
        unsigned int loadingOffscreenViews : 1; 
        unsigned int updating : 1; 
        unsigned int updatingVisibleCells : 1; 
        unsigned int backgroundColorSet : 1; 
        unsigned int preRotationBoundsSet : 1; 
        unsigned int updateFocusAfterItemAnimations : 1; 
        unsigned int remembersLastFocusedIndexPath : 1; 
        unsigned int updateFocusAfterLoadingCells : 1; 
        unsigned int creatingViewFromPreferredFocusedView : 1; 
        unsigned int performingLayout : 1; 
        unsigned int keepsFirstResponderVisibleOnBoundsChange : 1; 
        unsigned int editing : 1; 
        unsigned int shouldDeriveVisibleBoundsFromContainingScrollView : 1; 
        unsigned int alwaysBounceWasCustomized : 1; 
        unsigned int usingCustomLayoutMargins : 1; 
        unsigned int settingDefaultLayoutMargins : 1; 
        unsigned int defaultLayoutMarginsSetFromViewController : 1; 
        unsigned int shouldPrefetchCellsWhenPerformingReloadData : 1; 
        unsigned int scheduledReloadPrefetchDuringNextLayoutPass : 1; 
        unsigned int indexTitlesLoaded : 1; 
        unsigned int shouldApplyShadowUpdates : 1; 
        unsigned int preventNotificationOfRebaseObserversWhenApplyingUpdates : 1; 
        unsigned int allowsVisibleCellUpdatesDuringUpdateAnimations : 1; 
        unsigned int allowsVisibleViewUpdatesDuringLayoutTransitions : 1; 
        unsigned int isCompletingInteractiveMovement : 1; 
        unsigned int isRegisteredForGeometryChanges : 1; 
        unsigned int isIdleObserverRegistered : 1; 
        unsigned int prefetchingEnabled : 1; 
        unsigned int generatingDescriptionWithDataSource : 1; 
        unsigned int isRequestingCellOrSupplementary : 1; 
        unsigned int skipAttributesApplication : 1; 
        unsigned int isPerformingInternalBatchUpdates : 1; 
        unsigned int selfSizingInvalidation : 2; 
        unsigned int shouldAnimateNextRecomputePreferredAttributesForInvalidatedElements : 1; 
        unsigned int scheduledRecomputePreferredAttributesForInvalidatedElements : 1; 
        unsigned int delaysUserInitiatedItemSelection : 1; 
        unsigned int isAnimatingInteractiveMovementCompletion : 1; 
        unsigned int shouldResetInitialLayoutOnDataSourceChange : 1; 
        unsigned int shouldPersistSelectionOnReloadDataWhenPossible : 1; 
        unsigned int forceRebaseContentOffsetAnchorDuringBatchUpdates : 1; 
        unsigned int skipForcedLayoutBeforeBatchUpdates : 1; 
        unsigned int clearTargetIndexPathforScrollingAfterLayout : 1; 
        unsigned int isResigningFirstResponderDuringReloadData : 1; 
        unsigned int suppressPromiseRegionGeneration : 1; 
        unsigned int preserveAnchorAndScrollTargetOnBoundsChange : 1; 
        unsigned int isSelectingItemAtIndexPath : 1; 
        unsigned int adjustContentOffsetAfterLayout : 1; 
        unsigned int disableSavingContentOffsetAnchor : 1; 
    }  _collectionViewFlags;
    long long  _containerScrollViewVisitationCount;
    UIFocusContainerGuide * _contentFocusContainerGuide;
    NSIndexPath * _contentOffsetRestorationAnchor;
    struct CGPoint { 
        double x; 
        double y; 
    }  _contentOffsetWhenScrollNotificationsSuspended;
    UIContextMenuInteraction * _contextMenuInteraction;
    long long  _currentIndexTitleIndex;
    double  _currentInteractiveTransitionProgress;
    double  _currentInteractiveTransitionTimeStamp;
    UICollectionViewCell * _currentPromiseFulfillmentCell;
    UITouch * _currentTouch;
    UICollectionViewUpdate * _currentUpdate;
    <UICollectionViewDataSource_Private> * _dataSource;
    _UICollectionViewFeedbackLoopDebugger * _debugger;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _defaultLayoutMargins;
    NSMutableArray * _deleteItems;
    long long  _didScrollNotificationSuspensionCount;
    _UICollectionViewDragAndDropController * _dragAndDropController;
    <UICollectionViewDragDelegate_Private> * _dragDelegate;
    _UICollectionViewDragDestinationController * _dragDestinationController;
    <UICollectionViewDragDestination> * _dragDestinationDelegate;
    long long  _dragDestinationVisualStyle;
    long long  _dragInteractionEnabledState;
    long long  _dragPlaceholderInsertionCadence;
    long long  _dragReorderingCadence;
    _UICollectionViewDragSourceController * _dragSourceController;
    <UICollectionViewDragSource> * _dragSourceDelegate;
    <UICollectionViewDropDelegate_Private> * _dropDelegate;
    _UIDynamicAnimationGroup * _endInteractiveTransitionAnimationGroup;
    UIFocusContainerGuide * _endOfContentFocusContainerGuide;
    UICollectionViewUpdateItem * _expectedDiffableUpdateItem;
    NSIndexPath * _firstResponderIndexPath;
    UICollectionReusableView * _firstResponderView;
    NSString * _firstResponderViewKind;
    long long  _firstResponderViewType;
    _UICollectionViewFocusedItemState * _focusedItemState;
    NSIndexPath * _highlightedSpringLoadedItem;
    _UIHorizontalIndexTitleBar * _horizontalIndexTitleBar;
    struct CGPoint { 
        double x; 
        double y; 
    }  _horizontalIndexTitleBarOffset;
    _UIIndexPathIdentityTracker * _identityTracker;
    UIIndexBarAccessoryView * _indexBar;
    NSArray * _indexBarSectionIndexTitles;
    _UICollectionTableIndexOverlayManager * _indexOverlayManager;
    NSIndexPath * _indexPathBeingReconfigured;
    NSIndexPath * _indexPathOfFocusedCellBeforeFocusingOnHorizontalIndexTitleBar;
    NSMutableOrderedSet * _indexPathsRequiringPreferredAttributes;
    NSMutableArray * _insertItems;
    id /* block */  _interactiveCompletionHandler;
    NSMutableDictionary * _interactiveTransitionInfos;
    NSMutableDictionary * _interactiveTransitionValueTrackingDict;
    UICollectionViewLayoutInvalidationContext * _intrinsicContentSizeInvalidationContext;
    NSMutableDictionary * _invalidatedDecorationIndexPaths;
    NSMutableSet * _invalidatedItemIndexPaths;
    NSMutableDictionary * _invalidatedSupplementaryIndexPaths;
    id /* block */  _invalidationBlock;
    bool  _isInInteractiveTransition;
    bool  _isMovingFocusFromHorizontalIndexTitleBarToContent;
    struct CGPoint { 
        double x; 
        double y; 
    }  _lastLayoutOffset;
    UICollectionViewLayout * _layout;
    _UICollectionViewPrefetchingContext * _mainPrefetchingContext;
    NSMutableArray * _moveItems;
    _UICollectionViewMultiSelectController * _multiSelectController;
    id /* block */  _navigationCompletion;
    UICollectionReusableView * _newContentView;
    UICollectionViewLayout * _nextLayoutForInteractiveTranstion;
    NSHashTable * _notifiedDisplayedCells;
    struct CGPoint { 
        double x; 
        double y; 
    }  _offsetToContentOffsetRestorationAnchor;
    struct CGPoint { 
        double x; 
        double y; 
    }  _offsetToTargetIndexPathForScrolling;
    NSArray * _originalDeleteItems;
    NSArray * _originalInsertItems;
    _UICollectionViewOrthogonalScrollerSectionController * _orthogonalScrollerController;
    NSMutableDictionary * _orthogonalSectionPrefetchingContexts;
    NSMutableSet * _pendingDeselectionIndexPaths;
    NSIndexPath * _pendingSelectionIndexPath;
    long long  _performUsingPresentationValuesRefCount;
    id /* block */  _postUpdateBlock;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _preRotationBounds;
    long long  _preferredDragDestinationVisualStyle;
    NSMutableDictionary * _prefetchCacheItems;
    <UICollectionViewDataSourcePrefetching> * _prefetchDataSource;
    _UIVelocityIntegrator * _prefetchVelocityIntegrator;
    double  _previousInteractiveTransitionProgress;
    double  _previousInteractiveTransitionTimeStamp;
    UIViewPropertyAnimator * _reconfigureAnimator;
    NSMutableArray * _reloadItems;
    long long  _reloadingSuspendedCount;
    _UICollectionViewFocusedItemState * _rememberedFocusedItemState;
    _UIDragDestinationIndicatorView * _reorderDestinationView;
    _UIDragSnappingFeedbackGenerator * _reorderFeedbackGenerator;
    long long  _reorderingCadence;
    struct CGPoint { 
        double x; 
        double y; 
    }  _reorderingTargetPosition;
    unsigned long long  _requestedPositionOfTargetIndexPathForScrolling;
    long long  _rotationAnimationCount;
    struct CGPoint { 
        double x; 
        double y; 
    }  _rotationBoundsOffset;
    UIWindowSceneActivationInteraction * _sceneActivationInteraction;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _scrollingTargetItemFrame;
    bool  _searchFullPageOnFocusUpdate;
    NSMutableArray * _sectionContainersQueuedForRemoval;
    _UICollectionViewSectionFocusGuideController * _sectionFocusGuideController;
    NSMutableDictionary * _sectionToContainerViewMap;
    _UIFocusFastScrollingIndexBarEntry * _selectedIndexTitleEntry;
    _UICollectionViewSelectionController * _selectionController;
    _UISelectionInteraction * _selectionInteraction;
    bool  _shouldAccumulateTrackedLayoutValues;
    _UICollectionViewSubviewManager * _subviewManager;
    _UICollectionViewSubviewRouter * _subviewRouter;
    NSMutableDictionary * _supplementaryViewClassDict;
    NSMutableDictionary * _supplementaryViewNibDict;
    NSMutableDictionary * _supplementaryViewNibExternalObjectsTables;
    NSMutableSet * _supplementaryViewRegisteredKinds;
    NSMutableDictionary * _supplementaryViewReuseQueues;
    _UICollectionViewFocusedItemState * _targetFocusedItemState;
    NSIndexPath * _targetIndexPathForScrolling;
    NSMutableArray * _trackedValuesKeys;
    UICollectionViewLayoutAttributes * _transitionLayoutAttributes;
    long long  _updateAnimationCount;
    id /* block */  _updateCompletionHandler;
    long long  _updateCount;
    long long  _updateVisibleCellsRecursionCount;
    NSMutableSet * _viewsOptedOutOfBeingParentedIntoContainers;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _visibleBounds;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _visibleRectInsets;
}

@property (nonatomic, readonly) bool __hasTransitionLayoutAttributes;
@property (nonatomic, readonly) bool _delegateSupportsPrimaryAction;
@property (getter=_isEditing, nonatomic, readonly) bool _editing;
@property (nonatomic, readonly) bool _isRequestingCellOrSupplementary;
@property (nonatomic, readonly) bool _needsReload;
@property (getter=_selectionController, nonatomic, readonly) _UICollectionViewSelectionController *_selectionController;
@property (getter=_allowsEffectiveMultipleSelection, nonatomic, readonly) bool allowsEffectiveMultipleSelection;
@property (getter=_allowsEffectiveSelection, nonatomic, readonly) bool allowsEffectiveSelection;
@property (nonatomic) bool allowsFocus;
@property (nonatomic) bool allowsFocusDuringEditing;
@property (nonatomic) bool allowsMultipleSelection;
@property (nonatomic) bool allowsMultipleSelectionDuringEditing;
@property (nonatomic) bool allowsSelection;
@property (nonatomic) bool allowsSelectionDuringEditing;
@property (nonatomic, retain) UIView *backgroundView;
@property (nonatomic) bool cellRegistered;
@property (getter=_collectionViewData, nonatomic, readonly) UICollectionViewData *collectionViewData;
@property (nonatomic, retain) UICollectionViewLayout *collectionViewLayout;
@property (nonatomic, readonly) UIContextMenuInteraction *contextMenuInteraction;
@property (getter=_currentPromiseFulfillmentCell, setter=_setCurrentPromiseFulfillmentCell:, nonatomic, retain) UICollectionViewCell *currentPromiseFulfillmentCell;
@property (getter=_currentTouch, setter=_setCurrentTouch:, nonatomic, retain) UITouch *currentTouch;
@property (getter=_currentUpdate, nonatomic, readonly) UICollectionViewUpdate *currentUpdate;
@property (nonatomic) <UICollectionViewDataSource> *dataSource;
@property (getter=_dataSourceSupportsReordering, nonatomic, readonly) bool dataSourceSupportsReordering;
@property (readonly, copy) NSString *debugDescription;
@property (getter=_defaultLayoutMargins, setter=_setDefaultLayoutMargins:, nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } defaultLayoutMargins;
@property (nonatomic) <UICollectionViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) <UICollectionViewDragDelegate> *dragDelegate;
@property (nonatomic) bool dragInteractionEnabled;
@property (nonatomic) <UICollectionViewDropDelegate> *dropDelegate;
@property (getter=isEditing, nonatomic) bool editing;
@property (getter=_endOfContentFocusContainerGuide, nonatomic, readonly) UIFocusContainerGuide *endOfContentFocusContainerGuide;
@property (getter=_expectedDiffableUpdateItem, nonatomic, retain) UICollectionViewUpdateItem *expectedDiffableUpdateItem;
@property (getter=_focusedItemState, setter=_setFocusedItemState:, nonatomic, copy) _UICollectionViewFocusedItemState *focusedItemState;
@property (nonatomic, readonly) bool hasActiveDrag;
@property (nonatomic, readonly) bool hasActiveDrop;
@property (getter=_hasCustomBackground, nonatomic, readonly) bool hasCustomBackground;
@property (nonatomic, readonly) bool hasUncommittedUpdates;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool headersRegistered;
@property (getter=_horizontalIndexTitleBar, setter=_setHorizontalIndexTitleBar:, nonatomic, retain) _UIHorizontalIndexTitleBar *horizontalIndexTitleBar;
@property (nonatomic, readonly) NSIndexPath *ic_firstItemIndexPath;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } ic_firstSelectedItemFrame;
@property (nonatomic, readonly) NSIndexPath *ic_middleVisibleIndexPath;
@property (readonly) bool ic_selectionContainsFocusedItem;
@property (getter=_indexOverlayManager, setter=_setIndexOverlayManager:, nonatomic, retain) _UICollectionTableIndexOverlayManager *indexOverlayManager;
@property (nonatomic, retain) NSIndexPath *indexPathOfFocusedCellBeforeFocusingOnHorizontalIndexTitleBar;
@property (nonatomic, readonly) NSArray *indexPathsForFocusedItems;
@property (nonatomic, readonly) NSArray *indexPathsForSelectedItems;
@property (nonatomic, readonly) NSArray *indexPathsForVisibleItems;
@property (nonatomic) bool isMovingFocusFromHorizontalIndexTitleBarToContent;
@property (getter=_keepsFirstResponderVisibleOnBoundsChange, setter=_setKeepsFirstResponderVisibleOnBoundsChange:, nonatomic) bool keepsFirstResponderVisibleOnBoundsChange;
@property (getter=mt_isEditing, setter=mt_setEditing:, nonatomic) bool mt_editing;
@property (nonatomic, readonly) NSArray *mui_indexPathsForPreparedItems;
@property (nonatomic, readonly) NSArray *mui_sortedIndexPathsForVisibleItems;
@property (getter=_navigationCompletion, setter=_setNavigationCompletion:, nonatomic, copy) id /* block */ navigationCompletion;
@property (nonatomic, readonly) long long numberOfSections;
@property (getter=_isPerformingReloadData, nonatomic, readonly) bool performingReloadData;
@property (nonatomic) <UICollectionViewDataSourcePrefetching> *prefetchDataSource;
@property (getter=isPrefetchingEnabled, nonatomic) bool prefetchingEnabled;
@property (getter=_rememberedFocusedItemState, setter=_setRememberedFocusedItemState:, nonatomic, copy) _UICollectionViewFocusedItemState *rememberedFocusedItemState;
@property (nonatomic) bool remembersLastFocusedIndexPath;
@property (getter=_reorderDestinationView, setter=_setReorderDestinationView:, nonatomic, retain) _UIDragDestinationIndicatorView *reorderDestinationView;
@property (getter=_reorderedItems, nonatomic, readonly) NSArray *reorderedItems;
@property (nonatomic) long long reorderingCadence;
@property (getter=_reorderingTargetPosition, nonatomic, readonly) struct CGPoint { double x1; double x2; } reorderingTargetPosition;
@property (getter=_searchFullPageOnFocusUpdate, setter=_setSearchFullPageOnFocusUpdate:, nonatomic) bool searchFullPageOnFocusUpdate;
@property (nonatomic, retain) _UIFocusFastScrollingIndexBarEntry *selectedIndexTitleEntry;
@property (nonatomic) bool selectionFollowsFocus;
@property (nonatomic) long long selfSizingInvalidation;
@property (readonly) Class superclass;
@property (getter=_supportsAutomaticCatalystDragAndDropReordering, nonatomic, readonly) bool supportsAutomaticCatalystDragAndDropReordering;
@property (nonatomic) bool tu_deriveVisibleBoundsFromContainingScrollView;
@property (nonatomic, readonly) NSArray *visibleCells;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } vuiBounds;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } vuiContentInsets;
@property (nonatomic) struct CGPoint { double x1; double x2; } vuiContentOffset;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } vuiContentSize;
@property (nonatomic, readonly) NSArray *vuiIndexPathsForVisibleItems;
@property (nonatomic, readonly) NSArray *vuiPreciseIndexPathsForFullyVisibleItems;
@property (nonatomic, readonly) NSArray *vuiPreciseIndexPathsForVisibleItems;
@property (nonatomic, readonly) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } vuiSafeAreaInsets;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } vuiSize;
@property (nonatomic, readonly) NSArray *vuiVisibleCells;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (id)_reuseKeyForSupplementaryViewOfKind:(id)arg1 withReuseIdentifier:(id)arg2;
+ (bool)_supportsInvalidatingFocusCache;

- (void).cxx_destruct;
- (void)_Bug_Detected_In_Client_Of_UICollectionView_Invalid_Batch_Updates:(id)arg1;
- (void)_Bug_Detected_In_Client_Of_UICollectionView_Invalid_Number_Of_Items_In_Section:(id)arg1;
- (void)_Bug_Detected_In_Client_Of_UICollectionView_Invalid_Number_Of_Sections:(id)arg1;
- (bool)__hasTransitionLayoutAttributes;
- (bool)__isKindOfUICollectionView;
- (void)_accessibilitySetInterfaceStyleIntent:(unsigned long long)arg1;
- (void)_addContainerScrollViewForNotifications:(id)arg1;
- (void)_addControlledSubview:(id)arg1;
- (void)_addControlledSubview:(id)arg1 atZIndex:(long long)arg2 forced:(bool)arg3;
- (void)_addControlledSubview:(id)arg1 atZIndex:(long long)arg2 forced:(bool)arg3 initialAttributes:(id)arg4;
- (void)_addEntriesFromDictionary:(id)arg1 inDictionary:(id)arg2;
- (void)_addEntriesFromDictionary:(id)arg1 inDictionary:(id)arg2 andSet:(id)arg3;
- (void)_addItemAtIndexPathToActiveDragSession:(id)arg1;
- (void)_addSubview:(id)arg1 positioned:(long long)arg2 relativeTo:(id)arg3;
- (void)_addUpdateToShadowControllerIfNeeded:(id)arg1;
- (struct CGPoint { double x1; double x2; })_adjustFocusContentOffset:(struct CGPoint { double x1; double x2; })arg1 toShowFocusItemWithInfo:(id)arg2;
- (void)_adjustForAutomaticKeyboardInfo:(id)arg1 animated:(bool)arg2 lastAdjustment:(double*)arg3;
- (double)_alignedContentMarginGivenMargin:(double)arg1;
- (bool)_allowsEffectiveFocus;
- (bool)_allowsEffectiveMultipleSelection;
- (bool)_allowsEffectiveSelection;
- (bool)_allowsEffectiveSelectionOrCustomActionAtIndexPath:(id)arg1;
- (bool)_allowsMultipleSelectionDuringEditing;
- (bool)_allowsSelectionDuringEditing;
- (bool)_allowsVisibleCellUpdatesDuringUpdateAnimations;
- (bool)_allowsVisibleViewUpdatesDuringLayoutTransitions;
- (void)_animateVisibleView:(id)arg1 withLayoutAttributes:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)_applyAutomaticAdjustedContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)_applyBlockToAllReusableViews:(id /* block */)arg1;
- (void)_applyLayoutAttributes:(id)arg1 toView:(id)arg2;
- (id)_arrayForUpdateAction:(int)arg1;
- (id)_attributesForItemsVisibleDuringCurrentUpdateWithOldVisibleViews:(id)arg1 attributesForNewModel:(id)arg2;
- (id)_autoScrollAssistantForIndexPath:(id)arg1;
- (void)_autoScrollAssistantUpdateContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)_autoscrollForReordering:(id)arg1;
- (bool)_beginInteractiveMovementForItemAtIndexPath:(id)arg1;
- (bool)_beginReorderingItemAtIndexPath:(id)arg1;
- (void)_beginReusableViewCreationAndSelfSizingOutsideVisibleCellsUpdate;
- (void)_beginUpdates;
- (void)_cacheOrReuseCell:(id)arg1 forIndexPath:(id)arg2 invalidatePreferredAttributes:(bool)arg3 notifyDidEndDisplaying:(bool)arg4;
- (bool)_canBeginReorderingItem;
- (bool)_canEditItemAtIndexPath:(id)arg1;
- (bool)_canPerformAction:(SEL)arg1 forCell:(id)arg2 sender:(id)arg3;
- (bool)_canPerformPrimaryActionForItemAtIndexPath:(id)arg1;
- (bool)_canReorderItemAtIndexPath:(id)arg1;
- (bool)_canReusePreviouslyFocusedManagedSubview:(id)arg1;
- (void)_cancelInteractiveMovementWithCompletion:(id /* block */)arg1;
- (void)_cancelInteractiveTransitionWithFinalAnimation:(bool)arg1;
- (void)_cancelReordering;
- (void)_cancelTouches;
- (bool)_cellAtIndexPath:(id)arg1 containsInteractiveControlAtPoint:(struct CGPoint { double x1; double x2; })arg2;
- (void)_cellBackgroundChangedForSelectionOrHighlight:(id)arg1;
- (void)_cellBecameFocused:(id)arg1;
- (bool)_cellCanBecomeFocused:(id)arg1;
- (void)_cellDidBecomeFocused:(id)arg1;
- (void)_cellDidBecomeUnfocused:(id)arg1;
- (long long)_cellFocusItemDeferral:(id)arg1;
- (id)_cellForItemAtIndexPath:(id)arg1;
- (id)_cellForItemAtIndexPath:(id)arg1 includePrefetchedCells:(bool)arg2;
- (void)_cellMenuDismissed;
- (void)_cellPreferredSeparatorInsetsChanged:(id)arg1;
- (long long)_cellPrefetchMode;
- (bool)_checkForPreferredAttributesInView:(id)arg1 originalAttributes:(id)arg2;
- (id)_childFocusRegionsInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inCoordinateSpace:(id)arg2;
- (void)_cleanUpAfterInteractiveTransitionDidFinish:(bool)arg1;
- (void)_clearContentOffsetRestorationAnchor;
- (void)_clearNeedsRecomputePreferredAttributesForInvalidatedElements;
- (void)_clearTargetIndexPathForScrolling;
- (id)_collectionViewData;
- (void)_completeInteractiveMovementWithDisposition:(long long)arg1 completion:(id /* block */)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_computeFutureVisibleBoundsForPrefetchVelocity:(struct CGVector { double x1; double x2; })arg1 visibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)_computeMainPrefetchCandidatesForVelocity:(struct CGVector { double x1; double x2; })arg1;
- (id)_computeMainPrefetchCandidatesForVisibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 futureVisibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 prefetchVector:(struct CGVector { double x1; double x2; })arg3;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_computePrefetchCacheValidationBoundsForPrefetchVelocity:(struct CGVector { double x1; double x2; })arg1 visibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)_computeVisibleContentOffsetForUpdate:(id)arg1 usingData:(id)arg2;
- (void)_configureCachedCellForDisplay:(id)arg1 withIndexPath:(id)arg2 layoutAttributesToUpdate:(id)arg3;
- (void)_configureCellForDisplay:(id)arg1 indexPath:(id)arg2 cached:(bool)arg3;
- (void)_configureContextMenuInteractionIfNeeded;
- (void)_configureSceneActivationInteractionIfNeeded;
- (void)_configureSupplementaryViewForDisplay:(id)arg1 withElementKind:(id)arg2 indexPath:(id)arg3;
- (bool)_containsFocusedItem;
- (id)_contentFocusContainerGuide;
- (struct CGPoint { double x1; double x2; })_contentOffsetForLowFidelityScrollInDirection:(struct CGPoint { double x1; double x2; })arg1 duration:(double*)arg2;
- (struct CGPoint { double x1; double x2; })_contentOffsetForNewFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 oldFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 newContentSize:(struct CGSize { double x1; double x2; })arg3 andOldContentSize:(struct CGSize { double x1; double x2; })arg4;
- (struct CGPoint { double x1; double x2; })_contentOffsetForScrollingToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2;
- (struct CGPoint { double x1; double x2; })_contentOffsetForScrollingToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2 itemFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3 containingScrollView:(id)arg4 clampToScrollableArea:(bool)arg5;
- (struct CGPoint { double x1; double x2; })_contentOffsetFromProposedOffset:(struct CGPoint { double x1; double x2; })arg1 forScrollingToItemWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 atScrollPosition:(unsigned long long)arg3 containingScrollViewBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4 supplementaryViewInsets:(struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })arg5;
- (id)_contextMenuInteraction:(id)arg1 accessoriesForMenuWithConfiguration:(id)arg2;
- (id)_contextMenuInteraction:(id)arg1 styleForMenuWithConfiguration:(id)arg2;
- (void)_createAndAppendViewAnimationsForDeletesInCurrentUpdate:(id)arg1 disappearingAnimations:(id)arg2;
- (void)_createAndAppendViewAnimationsForExistingAndDeletedAuxiliariesInCurrentUpdate:(id)arg1 disappearingAnimations:(id)arg2 animationsForOnScreenViews:(id)arg3 newSubviewManager:(id)arg4 oldVisibleViews:(id)arg5;
- (void)_createAndAppendViewAnimationsForExistingAndNewlyVisibleItemsInCurrentUpdate:(id)arg1 animationsForOnScreenViews:(id)arg2 newSubviewManager:(id)arg3 oldVisibleViews:(id)arg4 attributesForNewModel:(id)arg5;
- (void)_createAndAppendViewAnimationsForInsertedAuxiliariesInCurrentUpdate:(id)arg1 appearingAnimations:(id)arg2 newSubviewManager:(id)arg3;
- (void)_createAndAppendViewAnimationsForInsertsInCurrentUpdate:(id)arg1 appearingAnimations:(id)arg2 newSubviewManager:(id)arg3;
- (void)_createAndAppendViewAnimationsForNewlyVisibleAuxiliariesInCurrentUpdate:(id)arg1 appearingAnimations:(id)arg2 animationsForOnScreenViews:(id)arg3 newSubviewManager:(id)arg4 attributesForNewModel:(id)arg5;
- (id)_createPreparedCellForItemAtIndexPath:(id)arg1 withLayoutAttributes:(id)arg2 applyAttributes:(bool)arg3;
- (id)_createPreparedCellForItemAtIndexPath:(id)arg1 withLayoutAttributes:(id)arg2 applyAttributes:(bool)arg3 isFocused:(bool)arg4 notify:(bool)arg5;
- (id)_createPreparedSupplementaryViewForElementOfKind:(id)arg1 atIndexPath:(id)arg2 layout:(id)arg3 withLayoutAttributes:(id)arg4 applyAttributes:(bool)arg5;
- (id)_createStaticScrollBar;
- (unsigned long long)_createVisibleViewsForAttributes:(id)arg1 fadeForBoundsChange:(bool)arg2 notifyLayoutForVisibleCellsPass:(bool)arg3;
- (struct _UICollectionViewVisibleCellsUpdateResult { unsigned long long x1; unsigned long long x2; unsigned long long x3; bool x4; })_createVisibleViewsForSingleCategoryAttributes:(id)arg1 limitCreation:(bool)arg2 fadeForBoundsChange:(bool)arg3;
- (id)_currentPromiseFulfillmentCell;
- (long long)_currentSectionIndexTitleIndex;
- (id)_currentTouch;
- (id)_currentUpdate;
- (id)_customScrollAnimation;
- (id)_dataSourceActual;
- (bool)_dataSourceImplementsNumberOfSections;
- (bool)_dataSourceImplementsReorderingHandlers;
- (id)_dataSourceIndexPathForPresentationIndexPath:(id)arg1;
- (bool)_dataSourceMatchesCurrentCounts;
- (long long)_dataSourceNumberOfItemsInSection:(long long)arg1;
- (long long)_dataSourceNumberOfSections;
- (id)_dataSourceProxy;
- (long long)_dataSourceSectionIndexForPresentationSectionIndex:(long long)arg1;
- (id)_dataSourceSectionIndexTitles;
- (bool)_dataSourceSupportsReordering;
- (void)_decrementRotationAnimationCount;
- (void)_decrementUpdateAnimationCountWithContext:(id)arg1;
- (bool)_defaultAllowsFocus;
- (bool)_defaultAllowsFocusDuringEditing;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_defaultLayoutMargins;
- (id)_defaultTargetedPreviewForIdentifier:(id)arg1;
- (bool)_delaysUserInitiatedItemSelection;
- (id)_delegateActual;
- (bool)_delegateAllowsHighlightingItemAtIndexPath:(id)arg1;
- (bool)_delegateAllowsSelectingItemAtIndexPath:(id)arg1;
- (id)_delegatePreferredIndexPath;
- (id)_delegateProxy;
- (bool)_delegateSupportsMenuInteraction;
- (bool)_delegateSupportsPrimaryAction;
- (struct CGPoint { double x1; double x2; })_delegateTargetOffsetForProposedContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (id)_dequeueReusableCellWithRegistration:(id)arg1 forIndexPath:(id)arg2;
- (id)_dequeueReusableSupplementaryWithRegistration:(id)arg1 forIndexPath:(id)arg2;
- (id)_dequeueReusableViewOfKind:(id)arg1 withIdentifier:(id)arg2 forIndexPath:(id)arg3 viewCategory:(unsigned long long)arg4;
- (bool)_derivesBoundsAndScrollingDisabledInContainerScrollView;
- (void)_deselectAllAnimated:(bool)arg1 notifyDelegate:(bool)arg2;
- (void)_deselectItemAtIndexPath:(id)arg1 animated:(bool)arg2 notifyDelegate:(bool)arg3;
- (void)_didMoveFromWindow:(id)arg1 toWindow:(id)arg2;
- (void)_didScroll;
- (void)_didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (id)_diffableDataSourceImpl;
- (id)_diffableIdentifierForIndexPath:(id)arg1;
- (bool)_displaysHorizontalIndexTitleBar;
- (id)_dragAndDropController;
- (bool)_dragAndDropNeededForReordering;
- (id)_dragDelegateActual;
- (id)_dragDelegateProxy;
- (id)_dragDestinationController;
- (id)_dragDestinationDelegateActual;
- (id)_dragDestinationDelegateProxy;
- (long long)_dragDestinationVisualStyle;
- (long long)_dragPlaceholderInsertionCadence;
- (long long)_dragReorderingCadence;
- (id)_dragSourceController;
- (id)_dragSourceDelegateActual;
- (id)_dragSourceDelegateProxy;
- (id)_dropDelegateActual;
- (id)_dropDelegateProxy;
- (id)_dynamicAnimationsForTrackValues;
- (unsigned long long)_edgesPropagatingSafeAreaInsetsToSubviews;
- (bool)_effectiveDefaultAllowsFocus;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_effectiveVisibleBoundsForBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_endInteractiveMovementWithCompletion:(id /* block */)arg1;
- (void)_endItemAnimationsWithInvalidationContext:(id)arg1;
- (void)_endItemAnimationsWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2;
- (void)_endItemAnimationsWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2 animator:(id)arg3;
- (void)_endItemAnimationsWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2 animator:(id)arg3 collectionViewAnimator:(id)arg4;
- (id)_endOfContentFocusContainerGuide;
- (void)_endReordering;
- (void)_endReusableViewCreationAndSelfSizingOutsideVisibleCellsUpdate;
- (void)_endUpdatesWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2 animator:(id)arg3;
- (void)_endUpdatesWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2 animator:(id)arg3 collectionViewAnimator:(id)arg4;
- (void)_ensureFocusedViewIsNotHidden;
- (void)_ensureViewsAreLoadedInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_enumerateVisibleViews:(id /* block */)arg1;
- (id)_existingIndexPathForIdentityTrackerIdentifier:(id)arg1;
- (id)_existingVisibleCells;
- (id)_expectedDiffableUpdateItem;
- (id)_extantFocusItemsInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_finishInteractiveTransitionShouldFinish:(bool)arg1 finalAnimation:(bool)arg2;
- (void)_finishInteractiveTransitionWithFinalAnimation:(bool)arg1;
- (id)_focusFastScrollingIndexBarEntries;
- (void)_focusMovementDidFailNotification:(id)arg1;
- (unsigned long long)_focusPrimaryScrollableAxis;
- (id)_focusPromiseRegionsInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inCoordinateSpace:(id)arg2 inSection:(long long)arg3;
- (id)_focusScrollBoundaryMetricsForItem:(id)arg1;
- (bool)_focusTriggersSelectionDelegate;
- (id)_focusedItemState;
- (bool)_forcePreserveSemanticContentOffsetDuringUpdates;
- (id)_fulfillPromisedFocusRegionForCell:(id)arg1;
- (void)_geometryChanged:(const struct { int x1; struct CGPoint { double x_2_1_1; double x_2_1_2; } x2; struct CGPoint { double x_3_1_1; double x_3_1_2; } x3; struct CGSize { double x_4_1_1; double x_4_1_2; } x4; struct CGPoint { double x_5_1_1; double x_5_1_2; } x5; struct CATransform3D { double x_6_1_1; double x_6_1_2; double x_6_1_3; double x_6_1_4; double x_6_1_5; double x_6_1_6; double x_6_1_7; double x_6_1_8; double x_6_1_9; double x_6_1_10; double x_6_1_11; double x_6_1_12; double x_6_1_13; double x_6_1_14; double x_6_1_15; double x_6_1_16; } x6; id x7; id x8; id x9; id x10; }*)arg1 forAncestor:(id)arg2;
- (void)_getOriginalReorderingIndexPaths:(id*)arg1 targetIndexPaths:(id*)arg2;
- (long long)_globalIndexPathForItemAtIndexPath:(id)arg1;
- (void)_handlePresses:(id)arg1 keyHandler:(id /* block */)arg2 defaultHandler:(id /* block */)arg3;
- (bool)_hasActiveDrag;
- (bool)_hasActiveDrop;
- (bool)_hasContainerScrollViewsAndScrollingDisabled;
- (bool)_hasContentForBarInteractions;
- (bool)_hasCustomBackground;
- (bool)_hasFocusedCellForIndexPath:(id)arg1 shouldUsePreUpdateData:(bool)arg2;
- (bool)_hasPrefetchItems;
- (bool)_hasRegisteredClassOrNibForSupplementaryViewOfKind:(id)arg1;
- (bool)_hasUncommittedUpdates;
- (void)_hideIndexOverlay;
- (void)_highlightFirstVisibleItemIfAppropriate;
- (bool)_highlightItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(unsigned long long)arg3;
- (bool)_highlightItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(unsigned long long)arg3 notifyDelegate:(bool)arg4;
- (void)_highlightSpringLoadedItemAtIndexPath:(id)arg1;
- (id)_horizontalIndexTitleBar;
- (struct CGPoint { double x1; double x2; })_horizontalIndexTitleBarOffset;
- (id)_identityTracker:(bool)arg1;
- (void)_incrementRotationAnimationCount;
- (void)_incrementUpdateAnimationCountWithContext:(id)arg1;
- (id)_indexBarEntries;
- (id)_indexOverlayManager;
- (id)_indexPathAfterShadowUpdatesForIndexPath:(id)arg1;
- (id)_indexPathBeforeShadowUpdatesForIndexPath:(id)arg1;
- (id)_indexPathForCell:(id)arg1;
- (id)_indexPathForEntryWithTitle:(id)arg1 atIndex:(long long)arg2 validateTitles:(bool)arg3;
- (id)_indexPathForGlobalIndex:(long long)arg1;
- (id)_indexPathForInsertionAtPoint:(struct CGPoint { double x1; double x2; })arg1 dropIntent:(long long)arg2 sourceIndexPath:(id)arg3 indicatorLayoutAttributes:(id*)arg4;
- (id)_indexPathForItemAtPoint:(struct CGPoint { double x1; double x2; })arg1;
- (id)_indexPathForView:(id)arg1 ofType:(unsigned long long)arg2;
- (bool)_indexPathIsSectionAppendingIndexPath:(id)arg1;
- (bool)_indexPathIsValid:(id)arg1;
- (bool)_indexPathIsValid:(id)arg1 allowSectionItemSentinel:(bool)arg2;
- (id)_indexPathOfItemNearestToPoint:(struct CGPoint { double x1; double x2; })arg1 intersectingRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (id)_indexPathsAfterShadowUpdatesForIndexPaths:(id)arg1;
- (id)_indexPathsAfterShadowUpdatesForIndexPaths:(id)arg1 allowingAppendingInserts:(bool)arg2;
- (id)_indexPathsBeforeShadowUpdatesForIndexPaths:(id)arg1;
- (id)_indexPathsForPreparedItems;
- (id)_indexPathsForSelectedItems;
- (id)_indexPathsForVisibleDecorationViewsOfKind:(id)arg1;
- (id)_indexPathsForVisibleItems;
- (id)_indexPathsForVisibleSupplementaryViewsOfKind:(id)arg1;
- (id)_indexPathsForVisibleSupplementaryViewsOfKind:(id)arg1 isDecorationView:(bool)arg2;
- (bool)_inferFocusabilityForCell:(id)arg1 atIndexPath:(id)arg2;
- (void)_invalidateLayoutForPreferredContentSizeCategoryTraitDidChange;
- (void)_invalidateLayoutForReload;
- (void)_invalidateLayoutForUpdatedLayoutMarginsIfNeeded;
- (void)_invalidateLayoutForVisibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 oldVisibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)_invalidateLayoutWithContext:(id)arg1;
- (void)_invalidateWithBlock:(id /* block */)arg1;
- (bool)_isConnectedToDiffableDataSource;
- (bool)_isCurrentlyPerformingLegacyReordering;
- (bool)_isDragDestinationInteractivelyReordering;
- (bool)_isEditing;
- (bool)_isFirstResponderInDeletedSectionOrItem;
- (bool)_isFocusedViewInDeletedSectionOrItem;
- (bool)_isIndexPathSelectedItem:(id)arg1;
- (bool)_isMovingFocusFromHorizontalIndexBarToCellContent:(id)arg1;
- (bool)_isOperatingWithPresentationValues;
- (bool)_isPerformingReloadData;
- (bool)_isReordering;
- (bool)_isReorderingItemAtIndexPath:(id)arg1;
- (bool)_isReorderingItemAtIndexPath:(id)arg1 includingDragAndDrop:(bool)arg2;
- (bool)_isRequestingCellOrSupplementary;
- (bool)_isSectionValidInIndexPath:(id)arg1;
- (bool)_isViewInReuseQueue:(id)arg1;
- (bool)_keepsFirstResponderVisibleOnBoundsChange;
- (id)_keysForObject:(id)arg1 inDictionary:(id)arg2;
- (void)_layoutAdjustmentsDidChange;
- (id)_layoutAttributes:(id)arg1 filteredForCategory:(unsigned long long)arg2;
- (id)_layoutAttributesForFailedMovementWithHeading:(unsigned long long)arg1;
- (void)_layoutDirectionTraitDidChange;
- (void)_layoutMarginsDidChangeFromOldMargins:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)_layoutMarginsWillChange;
- (void)_layoutSectionContainerViews;
- (void)_managedSubviewAdded:(id)arg1;
- (id)_managedSubviewForView:(id)arg1;
- (id)_managedViews;
- (void)_moveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)_moveSection:(long long)arg1 toSection:(long long)arg2;
- (void)_moveSectionIndexTitleIndexToIndex:(long long)arg1 highlight:(bool)arg2;
- (void)_moveWithEvent:(id)arg1;
- (id)_multiSelectController;
- (id /* block */)_navigationCompletion;
- (bool)_needsReload;
- (void)_notifyDataSourceForMoveOfItemFromIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)_notifyDidEndDisplayingCellIfNeeded:(id)arg1 forIndexPath:(id)arg2;
- (void)_notifyDidEndDisplayingSupplementaryView:(id)arg1;
- (void)_notifyDidScroll;
- (void)_notifyWillDisplayCellIfNeeded:(id)arg1 forIndexPath:(id)arg2;
- (void)_notifyWillDisplaySupplementaryView:(id)arg1 forElementKind:(id)arg2 atIndexPath:(id)arg3;
- (id)_objectInDictionary:(id)arg1 forKind:(id)arg2 indexPath:(id)arg3;
- (void)_offsetPinnedReorderedItemsWithCurrentContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)_orthogonalScrollView:(id)arg1 didScrollToOffset:(struct CGPoint { double x1; double x2; })arg2 inSection:(long long)arg3;
- (id)_orthogonalScrollerController;
- (void)_performAction:(SEL)arg1 forCell:(id)arg2 sender:(id)arg3;
- (void)_performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2 invalidationContext:(id)arg3;
- (void)_performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2 invalidationContext:(id)arg3 tentativelyForReordering:(bool)arg4;
- (void)_performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2 invalidationContext:(id)arg3 tentativelyForReordering:(bool)arg4 animator:(id)arg5;
- (void)_performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2 invalidationContext:(id)arg3 tentativelyForReordering:(bool)arg4 animator:(id)arg5 animationHandler:(id /* block */)arg6;
- (void)_performBatchUpdates:(id /* block */)arg1 customAnimationsProvider:(id /* block */)arg2;
- (void)_performBatchUpdates:(id /* block */)arg1 viewPropertyAnimator:(id)arg2 customAnimationsProvider:(id /* block */)arg3;
- (void)_performDiffableUpdate:(id /* block */)arg1;
- (void)_performInternalBatchUpdates:(id /* block */)arg1;
- (void)_performReloadPrefetchIfNeeded;
- (id)_performShadowUpdates:(id /* block */)arg1;
- (void)_performUpdate:(id)arg1;
- (void)_performUsingPresentationValues:(id /* block */)arg1;
- (void)_performWhileSuppressingPromiseRegionGeneration:(id /* block */)arg1;
- (void)_performWithoutNotifyingRebaseObserversWhenApplyingUpdates:(id /* block */)arg1;
- (void)_pinReorderedItemsWithPinningTest:(id /* block */)arg1;
- (id)_pivotForTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (void)_populateSubviewManagerWithExistingVisibleViewsForCurrentUpdate:(id)arg1 addingDeletedViewsToSet:(id)arg2 updateLayoutAttributesIndexPaths:(bool)arg3;
- (long long)_preferredDragDestinationVisualStyle;
- (id)_prefetchDataSourceActual;
- (id)_prefetchDataSourceProxy;
- (unsigned long long)_prefetchItemsForPrefetchingContext:(id)arg1;
- (bool)_prefetchingAllowed;
- (id)_prefetchingContextForOrthogonalScrollingSection:(long long)arg1;
- (id)_prefetchingContextForVisibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 prefetchVector:(struct CGVector { double x1; double x2; })arg2 prefetchRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3 attributes:(id)arg4;
- (bool)_prefetchingEnabledDefault;
- (void)_prepareClonedViewsForTransitionLayout;
- (void)_prepareLayoutForUpdates:(bool)arg1;
- (void)_prepareViewForUse:(id)arg1 withElementCategory:(unsigned long long)arg2 elementKind:(id)arg3 reuseIdentifier:(id)arg4 indexPath:(id)arg5;
- (void)_prepareViewForUse:(id)arg1 withElementCategory:(unsigned long long)arg2 elementKind:(id)arg3 reuseIdentifier:(id)arg4 indexPath:(id)arg5 applyDefaultAttributes:(bool)arg6;
- (id)_preparedCellForItemAtIndexPath:(id)arg1 withLayoutAttributes:(id)arg2 applyAttributes:(bool)arg3 isFocused:(bool)arg4 notify:(bool)arg5;
- (id)_presentationIndexPathForDataSourceIndexPath:(id)arg1;
- (long long)_presentationSectionIndexForDataSourceSectionIndex:(long long)arg1;
- (id)_primaryFocusItemForFocusGroup:(id)arg1;
- (void)_processQueuedSectionContainerRemovals;
- (void)_processViewSpecificInvalidationsForVisibleViews;
- (void)_pruneCachedPrefetchViewsForVelocity:(struct CGVector { double x1; double x2; })arg1;
- (void)_prunePrefetchedViewsAtIndexPaths:(id)arg1;
- (void)_purgeReuseQueues;
- (void)_rebaseContentOffsetAnchorOrScrollTargetForUpdate:(id)arg1;
- (void)_rebasePrefetchedCellIndexPathsWithMapping:(id /* block */)arg1;
- (void)_recomputePreferredAttributesForInvalidatedElementsIfNeeded;
- (bool)_recomputePreferredAttributesForInvalidatedView:(id)arg1 originalAttributes:(id)arg2;
- (void)_recomputeSectionIndexTitleIndex;
- (void)_reconfigureCell:(id)arg1 forItemAtIndexPath:(id)arg2;
- (void)_reconfigureItemAtIndexPath:(id)arg1;
- (void)_reconfigureSectionContainersForUpdate:(id)arg1;
- (void)_registerForGeometryChangesIfInSupeview;
- (void)_registeredSupplementaryViewKind:(id)arg1;
- (void)_reloadDataIfNeeded;
- (void)_reloadSectionIndexTitles;
- (id)_rememberedFocusedItemState;
- (bool)_remembersPreviouslyFocusedItem;
- (void)_removeAnyAncestorScrollViewNotifications;
- (bool)_removeCellFromVisibleCells:(id)arg1;
- (void)_removeContainerScrollViewForNotifications:(id)arg1;
- (void)_removeReorderDestinationView;
- (void)_removeStandaloneIndexBarIfNecessary;
- (void)_removeUntrackedAuxillaryViewsForBeforeVisibleViews:(id)arg1 afterVisibleViews:(id)arg2 withTrackingViewAnimations:(id)arg3;
- (void)_removeVisibleViews:(id)arg1 fadeForBoundsChange:(bool)arg2;
- (id)_reorderDestinationView;
- (id)_reorderFeedbackGenerator;
- (void)_reorderPrefetchCandidates:(id)arg1 forPrefetchVelocity:(struct CGVector { double x1; double x2; })arg2 visibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3;
- (unsigned long long)_reorderedItemCount;
- (id)_reorderedItemForView:(id)arg1;
- (id)_reorderedItems;
- (long long)_reorderingCadence;
- (struct CGPoint { double x1; double x2; })_reorderingTargetPosition;
- (void)_reparentViewIntoCorrectContainer:(id)arg1;
- (void)_reparentViewIntoSelf:(id)arg1;
- (void)_requestFocusOnItemAtIndexPath:(id)arg1;
- (void)_resetAllPrefetchContexts;
- (void)_resetContainerScrollViewVisitationCount;
- (void)_resetDropTargetAppearance;
- (void)_resetOrRebaseFocusedItemForCurrentUpdateWithIndexPathMapping:(id /* block */)arg1;
- (void)_resetPrefetchState;
- (void)_resetPrefetchedCachedCells;
- (void)_resetPrefetchingContext:(id)arg1;
- (void)_resetUpdateItemArrays;
- (void)_resignOrRebaseFirstResponderViewWithIndexPathMapping:(id /* block */)arg1;
- (void)_resumeReloads;
- (void)_reusableViewDidInvalidateIntrinsicContentSize:(id)arg1;
- (id)_reusableViewWithoutAttributesForElementCategory:(unsigned long long)arg1 kind:(id)arg2 indexPath:(id)arg3;
- (bool)_reuseCell:(id)arg1;
- (bool)_reuseCell:(id)arg1 notifyDidEndDisplaying:(bool)arg2;
- (id)_reuseDictionaryForCell:(bool)arg1;
- (void)_reusePrefetchedCell:(id)arg1;
- (void)_reusePreviouslyFocusedManagedSubviewIfNeeded:(id)arg1;
- (id)_reuseQueueForViewWithElementCategory:(unsigned long long)arg1 elementKind:(id)arg2 reuseIdentifier:(id)arg3;
- (void)_reuseReusableViewIfNeeded:(id)arg1;
- (bool)_reuseSupplementaryView:(id)arg1;
- (bool)_reviseNewContentOffsetForUpdate:(id)arg1;
- (void)_safeAreaInsetsDidChangeFromOldInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)_safeAreaInsetsWillChange;
- (id)_sceneActivationConfigurationForLocation:(struct CGPoint { double x1; double x2; })arg1;
- (void)_scrollFirstResponderCellToVisible:(bool)arg1;
- (void)_scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2 animated:(bool)arg3;
- (void)_scrollViewAnimationEnded:(id)arg1 finished:(bool)arg2;
- (void)_scrollViewDidEndDraggingWithDeceleration:(bool)arg1;
- (void)_scrollViewWillEndDraggingWithVelocity:(struct CGPoint { double x1; double x2; })arg1 targetContentOffset:(inout struct CGPoint { double x1; double x2; }*)arg2;
- (bool)_searchFullPageOnFocusUpdate;
- (id)_sectionContainerViewForSectionIndex:(long long)arg1 createIfNecessary:(bool)arg2;
- (long long)_sectionIndexChangedToIndex:(long long)arg1 title:(id)arg2;
- (id)_sectionIndexesAfterShadowUpdatesForSectionIndexes:(id)arg1;
- (id)_sectionIndexesAfterShadowUpdatesForSectionIndexes:(id)arg1 allowingAppendingInserts:(bool)arg2;
- (void)_selectAllSelectedItems;
- (void)_selectItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(unsigned long long)arg3 notifyDelegate:(bool)arg4;
- (void)_selectItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(unsigned long long)arg3 notifyDelegate:(bool)arg4 deselectPrevious:(bool)arg5 performCustomSelectionAction:(bool)arg6;
- (id)_selectableIndexPathForItemContainingHitView:(id)arg1;
- (id)_selectionController;
- (void)_selectionInteractionDidBeginHinting:(id)arg1;
- (void)_selectionInteractionDidCancelHinting:(id)arg1;
- (void)_selectionInteractionDidSelect:(id)arg1;
- (bool)_selectionInteractionShouldBegin:(id)arg1;
- (long long)_selfSizingInvalidationMode;
- (void)_semanticContextTraitDidChange;
- (void)_setAllowsMultipleSelectionDuringEditing:(bool)arg1;
- (void)_setAllowsSelectionDuringEditing:(bool)arg1;
- (void)_setAllowsVisibleCellUpdatesDuringUpdateAnimations:(bool)arg1;
- (void)_setAllowsVisibleViewUpdatesDuringLayoutTransitions:(bool)arg1;
- (void)_setCellPrefetchMode:(long long)arg1;
- (void)_setCollectionViewLayout:(id)arg1 animated:(bool)arg2 isInteractive:(bool)arg3 completion:(id /* block */)arg4;
- (void)_setCollectionViewLayout:(id)arg1 animated:(bool)arg2 isInteractive:(bool)arg3 completion:(id /* block */)arg4 animator:(id)arg5;
- (void)_setContentSize:(struct CGSize { double x1; double x2; })arg1 skipContentOffsetAdjustment:(bool)arg2;
- (void)_setContentSizeFromLayout:(struct CGSize { double x1; double x2; })arg1 isRecursivelyUpdatingVisibleCells:(bool)arg2;
- (void)_setCurrentPromiseFulfillmentCell:(id)arg1;
- (void)_setCurrentTouch:(id)arg1;
- (void)_setDefaultAlwaysBounceVertical:(bool)arg1 horizontal:(bool)arg2;
- (void)_setDefaultLayoutMargins:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)_setDefaultLayoutMargins:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1 fromViewController:(bool)arg2;
- (void)_setDelaysUserInitiatedItemSelection:(bool)arg1;
- (void)_setDisplaysHorizontalIndexTitleBar:(bool)arg1;
- (void)_setDragPlaceholderInsertionCadence:(long long)arg1;
- (void)_setDragReorderingCadence:(long long)arg1;
- (void)_setEffectiveDataSource:(id)arg1;
- (void)_setExternalObjectTable:(id)arg1 forNibLoadingOfCellWithReuseIdentifier:(id)arg2;
- (void)_setExternalObjectTable:(id)arg1 forNibLoadingOfSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)_setFocusedItemState:(id)arg1;
- (void)_setForcePreserveSemanticContentOffsetDuringUpdates:(bool)arg1;
- (void)_setHorizontalIndexTitleBar:(id)arg1;
- (void)_setHorizontalIndexTitleBarOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)_setIndexOverlayManager:(id)arg1;
- (void)_setIsAncestorOfFirstResponder:(bool)arg1;
- (void)_setKeepsFirstResponderVisibleOnBoundsChange:(bool)arg1;
- (void)_setNavigationCompletion:(id /* block */)arg1;
- (void)_setNeedsRecomputePreferredAttributesForInvalidatedElements;
- (void)_setNeedsVisibleCellsUpdate:(bool)arg1 withLayoutAttributes:(bool)arg2;
- (void)_setObject:(id)arg1 inDictionary:(id)arg2 forKind:(id)arg3 indexPath:(id)arg4;
- (void)_setPreferredDragDestinationVisualStyle:(long long)arg1;
- (void)_setPrefetchingContext:(id)arg1 forOrthogonalScrollingSection:(long long)arg2;
- (void)_setRememberedFocusedItemState:(id)arg1;
- (void)_setRemembersPreviouslyFocusedItem:(bool)arg1;
- (void)_setReorderDestinationView:(id)arg1;
- (void)_setReorderFeedbackGenerator:(id)arg1;
- (void)_setReorderingCadence:(long long)arg1;
- (void)_setSearchFullPageOnFocusUpdate:(bool)arg1;
- (void)_setSelfSizingInvalidationMode:(long long)arg1;
- (void)_setShouldBecomeFocusedOnSelection:(bool)arg1;
- (void)_setShouldDeriveVisibleBoundsFromContainingScrollView:(bool)arg1;
- (void)_setShouldPersistSelectionOnReloadDataWhenPossible:(bool)arg1;
- (void)_setShouldPrefetchCellsWhenPerformingReloadData:(bool)arg1;
- (void)_setShouldPreventFocusScrollPastContentSize:(bool)arg1;
- (void)_setShouldResetInitialLayoutOnDataSourceChange:(bool)arg1;
- (void)_setShouldSkipForcedLayoutBeforeBatchUpdates:(bool)arg1;
- (void)_setUpCompletionHandlerForAnimationInterruptionIfNecessary;
- (void)_setUsesStaticScrollBar:(bool)arg1;
- (void)_setVisibleRectEdgeInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)_setVisibleView:(id)arg1 forLayoutAttributes:(id)arg2;
- (id)_setupAnimationsForResizedViewsWithOldModel:(id)arg1;
- (void)_setupCellAnimations;
- (void)_setupDragDestinationControllerIfNeeded;
- (void)_setupDragSourceControllerIfNeeded;
- (void)_setupIndexOverlayManagerIfNecessary;
- (void)_shiftSectionIndexTitleIndexByAmount:(long long)arg1;
- (bool)_shouldApplyShadowUpdates;
- (bool)_shouldBecomeFocusedOnSelection;
- (bool)_shouldDeriveVisibleBoundsFromContainingScrollView;
- (bool)_shouldDeselectItemsOnTouchesBegan;
- (bool)_shouldFadeCellsForBoundChangeWhileRotating;
- (bool)_shouldPersistSelectionOnReloadDataWhenPossible;
- (bool)_shouldPrefetchCellsWhenPerformingReloadData;
- (bool)_shouldResetInitialLayoutOnDataSourceChange;
- (bool)_shouldScrollToContentBeginningInRightToLeft;
- (bool)_shouldSelectionFollowFocusForIndexPath:(id)arg1 initiatedBySelection:(bool)arg2;
- (bool)_shouldShowMenuForCell:(id)arg1;
- (bool)_shouldSkipForcedLayoutBeforeBatchUpdates;
- (bool)_shouldSpringLoadItemAtIndexPath:(id)arg1 withContext:(id)arg2;
- (bool)_shouldUpdateFocusInContext:(id)arg1;
- (void)_sortAttributesByDistanceToVisibleBoundsOrigin:(id)arg1;
- (id)_sortedDeduplicatedReloadItems;
- (void)_startViewAnimationsWithContext:(id)arg1 oldVisibleViews:(id)arg2 reorderedViewAttributesTable:(id)arg3 viewAnimator:(id)arg4 viewAnimationsCompletedDispatchGroup:(id)arg5;
- (void)_stopAutoscrollTimer;
- (void)_stopScrollingNotify:(bool)arg1 pin:(bool)arg2;
- (id)_subviewRouterForOrthogonalScrollViewAtSection:(long long)arg1;
- (id)_subviewRouterForView:(id)arg1 attributes:(id)arg2 createIfNecessary:(bool)arg3;
- (bool)_supportsAutomaticCatalystDragAndDropReordering;
- (void)_suspendReloads;
- (id)_systemDefaultFocusGroupIdentifier;
- (id)_targetIndexPathForMoveOfItemFromOriginalIndexPath:(id)arg1 atCurrentIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (id)_targetedPreviewForBackgroundMenuAtPoint:(struct CGPoint { double x1; double x2; })arg1;
- (void)_teardownDragDestinationController;
- (void)_teardownDragSourceController;
- (long long)_totalItemCount;
- (void)_trackLayoutValue:(double)arg1 forKey:(id)arg2;
- (double)_trackedLayoutValueForKey:(id)arg1;
- (void)_transitionIndexOverlaySelectionViewToVisible:(bool)arg1;
- (id)_translateDataSourceIndexPathToPresentationIndexPathAsNeeded:(id)arg1;
- (id)_translateDataSourceIndexPathsToPresentationIndexPathsAsNeeded:(id)arg1;
- (id)_translatePresentationIndexPathToDataSourceIndexPathAsNeeded:(id)arg1;
- (id)_translatePresentationIndexPathsToDataSourceIndexPathsAsNeeded:(id)arg1;
- (void)_unhighlightAllItems;
- (void)_unhighlightAllItemsAndHighlightGlobalItem:(long long)arg1;
- (void)_unhighlightItemAtIndexPath:(id)arg1 animated:(bool)arg2;
- (void)_unhighlightItemAtIndexPath:(id)arg1 animated:(bool)arg2 notifyDelegate:(bool)arg3;
- (void)_unhighlightSpringLoadedItem;
- (struct CGVector { double x1; double x2; })_unitVectorForVector:(struct CGVector { double x1; double x2; })arg1;
- (void)_unpinReorderedItemsIfNeeded;
- (void)_unregisterForGeometryChangesIfNeeded;
- (void)_updateAnimationDidStop:(id)arg1 finished:(bool)arg2;
- (void)_updateBackgroundColorIfNeeded;
- (void)_updateBackgroundView;
- (void)_updateContainerScrollViewsForNotifications;
- (void)_updateContentFocusContainerGuides;
- (void)_updateContextMenuStateForVisibleCells:(id)arg1;
- (void)_updateCycleIdleUntil:(unsigned long long)arg1;
- (void)_updateDefaultLayoutMargins;
- (void)_updateDragDestinationVisualStyle;
- (void)_updateDragInteractionForCurrentInteractionEnabledState;
- (void)_updateDropTargetAppearanceWithTargetIndexPath:(id)arg1 intent:(long long)arg2 indicatorLayoutAttributes:(id)arg3;
- (void)_updateEditing:(bool)arg1 forView:(id)arg2 atIndexPath:(id)arg3;
- (void)_updateFocusAfterLoadingVisibleCellsIfNeeded:(id)arg1;
- (void)_updateFocusScrollBoundaryMetrics:(id)arg1 forItem:(id)arg2 inSection:(long long)arg3;
- (void)_updateFocusedCellIndexPathIfNecessaryWithLastFocusedRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_updateHorizontalIndexTitleBarSelectionForFocusedIndexPath:(id)arg1;
- (void)_updateIndex;
- (id)_updateIndexOverlayToShowTitleAtIndex:(long long)arg1;
- (void)_updateLayoutAttributesForExistingVisibleViewsFadingForBoundsChange:(bool)arg1;
- (void)_updateOrderingOfViewsInDisappearingViewAnimations:(id)arg1 onScreenViewAnimations:(id)arg2;
- (void)_updatePreferredAttributesForCurrentUpdate;
- (void)_updatePreferredAttributesForCurrentUpdate:(unsigned long long)arg1;
- (bool)_updatePreferredAttributesForItemsInCurrentUpdate:(id)arg1 rect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (bool)_updatePreferredAttributesForItemsInCurrentUpdateWithRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 newlyVisible:(id)arg2 includeInserts:(bool)arg3;
- (bool)_updatePreferredAttributesForReusableViewInCurrentUpdate:(id)arg1 withOriginalAttributes:(id)arg2 isExistingView:(bool)arg3;
- (bool)_updatePreferredAttributesForSupplementariesInCurrentUpdate:(id)arg1;
- (bool)_updatePreferredAttributesForSupplementariesInCurrentUpdateWithRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 newlyVisible:(id)arg2 includeInserts:(bool)arg3;
- (bool)_updatePrefetchItemIfNeeded:(id)arg1 forIndexPath:(id)arg2 withLayoutAttributes:(id)arg3 willDisplay:(bool)arg4;
- (void)_updatePrefetchVelocityIntegratorForVisibleBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)_updatePrefetchedCells:(bool)arg1;
- (void)_updatePrefetchedCellsForOrthogonalScrollingSection:(long long)arg1 withOriginalPrefetchingVector:(struct CGVector { double x1; double x2; })arg2 canCompute:(bool)arg3 canPrefetch:(bool)arg4;
- (void)_updateReorderDestinationViewWithLayoutAttributes:(id)arg1;
- (void)_updateReorderingTargetPosition:(struct CGPoint { double x1; double x2; })arg1;
- (void)_updateReorderingTargetPosition:(struct CGPoint { double x1; double x2; })arg1 forced:(bool)arg2;
- (void)_updateRowsAtIndexPaths:(id)arg1 updateAction:(int)arg2;
- (void)_updateRowsAtIndexPaths:(id)arg1 updateAction:(int)arg2 updates:(id)arg3;
- (void)_updateSectionIndex;
- (void)_updateSections:(id)arg1 updateAction:(int)arg2;
- (void)_updateSelectionIsKey;
- (void)_updateTrackedLayoutValuesWith:(id)arg1;
- (void)_updateTransitionWithProgress:(double)arg1;
- (id)_updateTranslator;
- (unsigned long long)_updateVisibleCellsNow:(bool)arg1;
- (bool)_updateWithItems:(id)arg1 tentativelyForReordering:(bool)arg2 propertyAnimator:(id)arg3 collectionViewAnimator:(id)arg4;
- (void)_updateWithUpdates:(id)arg1 updateAction:(long long)arg2;
- (id)_updatedNewlyAppearingLayoutAttributesForCurrentVisibleBounds:(bool)arg1;
- (bool)_useIdleObserverForCellPrefetching;
- (void)_userSelectItemAtIndexPath:(id)arg1;
- (bool)_validateScrollingTargetIndexPath:(id)arg1;
- (bool)_validateSelectionOrHighlightIndexPath:(id)arg1 isSelection:(bool)arg2 allowMassIndexPath:(bool)arg3 assertIfInvalid:(bool)arg4;
- (id)_viewAnimationsForCurrentUpdate;
- (id)_viewAnimationsForCurrentUpdateWithCollectionViewAnimator:(id)arg1 updatingContentOffsetForRestorationAnchor:(bool)arg2;
- (id)_viewAnimationsForView:(id)arg1 startingLayoutAttributes:(id)arg2 endingLayoutAttributes:(id)arg3 startingLayout:(id)arg4 endingLayout:(id)arg5 animationSetup:(id /* block */)arg6 animationCompletion:(id /* block */)arg7 enableCustomAnimations:(bool)arg8 customAnimationsType:(unsigned long long)arg9;
- (id)_viewControllerToNotifyOnLayoutSubviews;
- (bool)_viewIsReorderedCell:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_visibleBounds;
- (id)_visibleCellForIndexPath:(id)arg1;
- (id)_visibleDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)_visibleDecorationViewsOfKind:(id)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_visibleRectEdgeInsets;
- (id)_visibleSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)_visibleSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2 isDecorationView:(bool)arg3;
- (id)_visibleSupplementaryViewsOfKind:(id)arg1;
- (id)_visibleSupplementaryViewsOfKind:(id)arg1 isDecorationView:(bool)arg2;
- (id)_visibleViewForLayoutAttributes:(id)arg1;
- (bool)_wantsIndexOverlays;
- (void)_wheelChangedWithEvent:(id)arg1;
- (void)_willRemoveSubview:(id)arg1;
- (void)_willUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (bool)allowsFocus;
- (bool)allowsFocusDuringEditing;
- (bool)allowsMultipleSelection;
- (bool)allowsMultipleSelectionDuringEditing;
- (bool)allowsSelection;
- (bool)allowsSelectionDuringEditing;
- (bool)allowsUserInitiatedMultipleSelection;
- (id)backgroundView;
- (bool)beginInteractiveMovementForItemAtIndexPath:(id)arg1;
- (void)bringSubviewToFront:(id)arg1;
- (bool)canBeEdited;
- (bool)canBecomeFirstResponder;
- (bool)canBecomeFocused;
- (void)cancelInteractiveMovement;
- (void)cancelInteractiveTransition;
- (id)cellForItemAtIndexPath:(id)arg1;
- (id)collectionViewLayout;
- (id)contextMenuInteraction;
- (id)contextMenuInteraction:(id)arg1 configuration:(id)arg2 dismissalPreviewForItemWithIdentifier:(id)arg3;
- (id)contextMenuInteraction:(id)arg1 configuration:(id)arg2 highlightPreviewForItemWithIdentifier:(id)arg3;
- (id)contextMenuInteraction:(id)arg1 configurationForMenuAtLocation:(struct CGPoint { double x1; double x2; })arg2;
- (void)contextMenuInteraction:(id)arg1 willDisplayMenuForConfiguration:(id)arg2 animator:(id)arg3;
- (void)contextMenuInteraction:(id)arg1 willEndForConfiguration:(id)arg2 animator:(id)arg3;
- (void)contextMenuInteraction:(id)arg1 willPerformPreviewActionForMenuWithConfiguration:(id)arg2 animator:(id)arg3;
- (id)dataSource;
- (id)dataSourceIndexPathForPresentationIndexPath:(id)arg1;
- (long long)dataSourceSectionIndexForPresentationSectionIndex:(long long)arg1;
- (void)dealloc;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)deleteItemsAtIndexPaths:(id)arg1;
- (void)deleteSections:(id)arg1;
- (id)dequeueConfiguredReusableCellWithRegistration:(id)arg1 forIndexPath:(id)arg2 item:(id)arg3;
- (id)dequeueConfiguredReusableSupplementaryViewWithRegistration:(id)arg1 forIndexPath:(id)arg2;
- (id)dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (id)dequeueReusableSupplementaryViewOfKind:(id)arg1 withReuseIdentifier:(id)arg2 forIndexPath:(id)arg3;
- (id)description;
- (void)deselectItemAtIndexPath:(id)arg1 animated:(bool)arg2;
- (void)didMoveToWindow;
- (id)dragDelegate;
- (id)dragDestinationDelegate;
- (bool)dragInteractionEnabled;
- (id)dragSourceDelegate;
- (id)dropDelegate;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)endInteractiveMovement;
- (void)exchangeSubviewAtIndex:(long long)arg1 withSubviewAtIndex:(long long)arg2;
- (void)finishInteractiveTransition;
- (id)focusItemsInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)hasActiveDrag;
- (bool)hasActiveDrop;
- (bool)hasUncommittedUpdates;
- (long long)highlightedGlobalItem;
- (void)horizontalIndexBar:(id)arg1 selectedEntry:(id)arg2;
- (struct CGPoint { double x1; double x2; })indexBarAccessoryView:(id)arg1 contentOffsetForEntry:(id)arg2 atIndex:(long long)arg3;
- (id)indexPathForCell:(id)arg1;
- (id)indexPathForItemAtPoint:(struct CGPoint { double x1; double x2; })arg1;
- (id)indexPathForSupplementaryView:(id)arg1;
- (id)indexPathOfFocusedCellBeforeFocusingOnHorizontalIndexTitleBar;
- (id)indexPathsForSelectedItems;
- (id)indexPathsForVisibleItems;
- (id)indexPathsForVisibleSupplementaryElementsOfKind:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 collectionViewLayout:(id)arg2;
- (void)insertItemsAtIndexPaths:(id)arg1;
- (void)insertSections:(id)arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (bool)isDragSessionActive;
- (bool)isEditing;
- (bool)isMovingFocusFromHorizontalIndexTitleBarToContent;
- (bool)isPrefetchingEnabled;
- (bool)isSpringLoaded;
- (id)keyCommands;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (void)layoutHorizontalIndexTitleBar;
- (void)layoutSubviews;
- (long long)maximumGlobalItemIndex;
- (void)moveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)moveSection:(long long)arg1 toSection:(long long)arg2;
- (long long)numberOfItemsInSection:(long long)arg1;
- (long long)numberOfSections;
- (void)performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2;
- (void)performBatchUpdates:(id /* block */)arg1 withAnimator:(id)arg2;
- (void)performUsingPresentationValues:(id /* block */)arg1;
- (id)preferredFocusedView;
- (void)prefetchCompleteForItemAtIndexPath:(id)arg1;
- (id)prefetchDataSource;
- (id)preparedCells;
- (id)presentationIndexPathForDataSourceIndexPath:(id)arg1;
- (long long)presentationSectionIndexForDataSourceSectionIndex:(long long)arg1;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
- (void)reconfigureItemsAtIndexPaths:(id)arg1;
- (void)registerClass:(Class)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)registerClass:(Class)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)registerNib:(id)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)registerNib:(id)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)reloadData;
- (void)reloadItemsAtIndexPaths:(id)arg1;
- (void)reloadSections:(id)arg1;
- (bool)remembersLastFocusedIndexPath;
- (long long)reorderingCadence;
- (void)scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2 animated:(bool)arg3;
- (void)selectItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(unsigned long long)arg3;
- (id)selectedIndexTitleEntry;
- (bool)selectionFollowsFocus;
- (long long)selfSizingInvalidation;
- (void)sendSubviewToBack:(id)arg1;
- (void)setAllowsFocus:(bool)arg1;
- (void)setAllowsFocusDuringEditing:(bool)arg1;
- (void)setAllowsMultipleSelection:(bool)arg1;
- (void)setAllowsMultipleSelectionDuringEditing:(bool)arg1;
- (void)setAllowsSelection:(bool)arg1;
- (void)setAllowsSelectionDuringEditing:(bool)arg1;
- (void)setAllowsUserInitiatedMultipleSelection:(bool)arg1;
- (void)setAlwaysBounceHorizontal:(bool)arg1;
- (void)setAlwaysBounceVertical:(bool)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setBackgroundView:(id)arg1;
- (void)setBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setCollectionViewLayout:(id)arg1;
- (void)setCollectionViewLayout:(id)arg1 animated:(bool)arg2;
- (void)setCollectionViewLayout:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)setCollectionViewLayout:(id)arg1 withAnimator:(id)arg2;
- (void)setContentInset:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)setContentOffset:(struct CGPoint { double x1; double x2; })arg1 animated:(bool)arg2;
- (void)setContentSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setDataSource:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDirectionalLayoutMargins:(struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setDragDelegate:(id)arg1;
- (void)setDragDestinationDelegate:(id)arg1;
- (void)setDragInteractionEnabled:(bool)arg1;
- (void)setDragSourceDelegate:(id)arg1;
- (void)setDropDelegate:(id)arg1;
- (void)setEditing:(bool)arg1;
- (void)setExpectedDiffableUpdateItem:(id)arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setIndexPathOfFocusedCellBeforeFocusingOnHorizontalIndexTitleBar:(id)arg1;
- (void)setIsMovingFocusFromHorizontalIndexTitleBarToContent:(bool)arg1;
- (void)setLayoutMargins:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setPrefetchDataSource:(id)arg1;
- (void)setPrefetchingEnabled:(bool)arg1;
- (void)setRemembersLastFocusedIndexPath:(bool)arg1;
- (void)setReorderingCadence:(long long)arg1;
- (void)setScrollEnabled:(bool)arg1;
- (void)setSelectedIndexTitleEntry:(id)arg1;
- (void)setSelectionFollowsFocus:(bool)arg1;
- (void)setSelfSizingInvalidation:(long long)arg1;
- (void)setSemanticContentAttribute:(long long)arg1;
- (void)setSpringLoaded:(bool)arg1;
- (void)setupHorizontalIndexTitleBar;
- (id)startInteractiveTransitionToCollectionViewLayout:(id)arg1 completion:(id /* block */)arg2;
- (void)subviewManagerDidUpdateCells:(id)arg1;
- (id)supplementaryViewForElementKind:(id)arg1 atIndexPath:(id)arg2;
- (id)targetForAction:(SEL)arg1 withSender:(id)arg2;
- (void)teardownHorizontalIndexTitleBar;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)updateInteractiveMovementTargetPosition:(struct CGPoint { double x1; double x2; })arg1;
- (void)userInteractionStoppedWithIndexBarView:(id)arg1;
- (id)visibleCells;
- (id)visibleSupplementaryViewsOfKind:(id)arg1;

// Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI

+ (void)_performSwiftUITestingOverrides;

- (id)_SwiftUITesting__viewAnimationsForCurrentUpdateWithCollectionViewAnimator:(id)arg1;

// Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit

- (struct CGSize { double x1; double x2; })__ck_contentSize;
- (id)__ck_indexPathForLastItem;
- (id)__ck_indexPathForReplyItem;
- (bool)__ck_isScrolledToBottomHidingIndexPath:(id)arg1;
- (void)__ck_reloadDataKeepingSelection;
- (struct CGPoint { double x1; double x2; })__ck_scrollToBottomContentOffsetHidingIndexPath:(id)arg1;
- (void)__ck_scrollToTopOfCellAtIndexPath:(id)arg1 hidingCellAtIndexPath:(id)arg2 animated:(bool)arg3;

// Image: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI

- (id)_gkDequeueCellForClass:(Class)arg1 forIndexPath:(id)arg2;
- (id)_gkDequeueSupplementaryViewForClass:(Class)arg1 ofKind:(id)arg2 forIndexPath:(id)arg3;
- (id)_gkFocusingLayout;
- (id)_gkHorizontalLayout;
- (void)_gkPerformWithoutViewReuse:(id /* block */)arg1;
- (void)_gkRegisterCellClass:(Class)arg1;
- (void)_gkRegisterClass:(Class)arg1 forSupplementaryViewOfKind:(id)arg2;
- (void)_gkRegisterNib:(id)arg1 forCellClass:(Class)arg2;
- (id)_gkReuseIdentifierForClass:(Class)arg1;
- (id)_gkVisibleCellForIndexPath:(id)arg1;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (void)hk_scrollToItemRespectingFlowLayoutSectionInsetAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(unsigned long long)arg3;

// Image: /System/Library/PrivateFrameworks/MailUI.framework/MailUI

- (id)mui_indexPathsForPreparedItems;
- (id)mui_sortedIndexPathsForVisibleItems;

// Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI

- (id)ic_cellAtLocation:(struct CGPoint { double x1; double x2; })arg1;
- (void)ic_deselectAllItems;
- (void)ic_deselectAllItemsAnimated:(bool)arg1;
- (id)ic_firstItemIndexPath;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })ic_firstSelectedItemFrame;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })ic_frameForItemAtIndexPath:(id)arg1;
- (id)ic_middleVisibleIndexPath;
- (void)ic_reloadDataWithCompletion:(id /* block */)arg1;
- (void)ic_selectCellAtIndexPath:(id)arg1 animated:(bool)arg2;
- (bool)ic_selectFirstItemIfNoneSelected;
- (bool)ic_selectionContainsFocusedItem;
- (id)indexPathsForFocusedItems;

// Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore

- (struct CGSize { double x1; double x2; })_px_currentContentSize;

// Image: /System/Library/PrivateFrameworks/PhotosUIPrivate.framework/PhotosUIPrivate

- (id)next:(long long)arg1 indexPathFromIndexPath:(id)arg2;
- (void)pu_animateUpdateOfCollectionViewSubview:(id)arg1 animations:(id /* block */)arg2 completion:(id /* block */)arg3;
- (void)pu_scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2 animated:(bool)arg3;
- (void)pu_scrollToRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 atScrollPosition:(unsigned long long)arg2 animated:(bool)arg3;

// Image: /System/Library/PrivateFrameworks/PodcastsUI.framework/PodcastsUI

- (bool)mt_isEditing;
- (void)mt_setEditing:(bool)arg1;

// Image: /System/Library/PrivateFrameworks/RelevanceEngineUI.framework/RelevanceEngineUI

- (bool)cellRegistered;
- (bool)headersRegistered;
- (void)setCellRegistered:(bool)arg1;
- (void)setHeadersRegistered:(bool)arg1;

// Image: /System/Library/PrivateFrameworks/SearchToShareCore.framework/SearchToShareCore

- (void)sts_enumerateAllIndexPathsUsingBlock:(id /* block */)arg1;

// Image: /System/Library/PrivateFrameworks/StickersUI.framework/StickersUI

- (id)animationForCell:(id)arg1 sourceCell:(id)arg2 triggerDelay:(double)arg3;
- (void)stk_performRippleAnimationAtIndexPath:(id)arg1 delay:(double)arg2;

// Image: /System/Library/PrivateFrameworks/TVMLKit.framework/TVMLKit

- (bool)tv_isFocusOnNonOwnedCell;
- (struct CGSize { double x1; double x2; })tv_sizeThatFits:(struct CGSize { double x1; double x2; })arg1 withContentInset:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg2;

// Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI

- (void)setTu_deriveVisibleBoundsFromContainingScrollView:(bool)arg1;
- (bool)tu_deriveVisibleBoundsFromContainingScrollView;
- (void)tu_reloadSectionIndexTitles;

// Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI

+ (id)_vui_indexPathsWithIndexSet:(id)arg1 andSection:(unsigned long long)arg2;
+ (id)collectionViewWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 parentView:(id)arg2 collectionViewLayout:(id)arg3;

- (id)_preciseIndexPathsForVisibleItems:(bool)arg1;
- (void)_vui_applyChangeSet:(id)arg1 inSection:(unsigned long long)arg2 updateDataSourceBlock:(id /* block */)arg3 applyChangeBlock:(id /* block */)arg4 shouldWrapInUpdate:(bool)arg5 completionHandler:(id /* block */)arg6;
- (void)_vui_applyDeleteChange:(id)arg1 inSection:(unsigned long long)arg2 applyChangeBlock:(id /* block */)arg3;
- (void)_vui_applyInsertChange:(id)arg1 inSection:(unsigned long long)arg2 applyChangeBlock:(id /* block */)arg3;
- (void)_vui_applyItemUpdateChanges:(id)arg1 inSection:(unsigned long long)arg2 applyChangeBlock:(id /* block */)arg3;
- (void)_vui_applyMoveChanges:(id)arg1 inSection:(unsigned long long)arg2 applyChangeBlock:(id /* block */)arg3;
- (void)_vui_applySectionUpdateChanges:(id)arg1 applyChangeBlock:(id /* block */)arg2 updateDataSourceBlock:(id /* block */)arg3;
- (void)_vui_applyUpdateChanges:(id)arg1 inSection:(unsigned long long)arg2 applyChangeBlock:(id /* block */)arg3 updateDataSourceBlock:(id /* block */)arg4;
- (void)setVuiContentInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setVuiContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)setVuiContentOffset:(struct CGPoint { double x1; double x2; })arg1 animated:(bool)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })vuiBounds;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })vuiContentInsets;
- (struct CGPoint { double x1; double x2; })vuiContentOffset;
- (struct CGSize { double x1; double x2; })vuiContentSize;
- (id)vuiIndexPathsForVisibleItems;
- (id)vuiPreciseIndexPathsForFullyVisibleItems;
- (id)vuiPreciseIndexPathsForVisibleItems;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })vuiSafeAreaInsets;
- (struct CGSize { double x1; double x2; })vuiSize;
- (id)vuiVisibleCells;
- (void)vui_applyChangeSet:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)vui_applyChangeSet:(id)arg1 inSection:(unsigned long long)arg2 completionHandler:(id /* block */)arg3;
- (void)vui_applyChangeSet:(id)arg1 inSection:(unsigned long long)arg2 updateDataSourceBlock:(id /* block */)arg3 applyChangeBlock:(id /* block */)arg4 completionHandler:(id /* block */)arg5;
- (void)vui_applyChangeSet:(id)arg1 inSection:(unsigned long long)arg2 updateDataSourceBlock:(id /* block */)arg3 completionHandler:(id /* block */)arg4;
- (id)vui_cellForItemAtIndexPath:(id)arg1;
- (id)vui_dequeueReusableCellWithIdentifier:(id)arg1 indexPath:(id)arg2;
- (id)vui_dequeueReusableSupplementaryViewOfKind:(id)arg1 withReuseIdentifier:(id)arg2 forIndexPath:(id)arg3;
- (id)vui_indexPathForCell:(id)arg1;
- (bool)vui_isIndexPathValid:(id)arg1;
- (void)vui_registerClass:(Class)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)vui_registerClass:(Class)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)vui_scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2 animated:(bool)arg3;
- (void)vui_setLayout:(id)arg1;

@end
