
@interface UIKeyShortcutHUDMetrics : NSObject {
    double  _availableVerticalSpace;
    _UIKeyShortcutHUDMenu * _baseMenu;
    _UIKeyShortcutHUDClientTraits * _clientTraits;
    bool  _combinedShortcutAndAlternateColumnWidths;
    double  _computedHUDWidthForBaseMenu;
    _UIKeyShortcutHUDMenu * _displayedMenu;
    NSMutableArray * _displayedMenuCategoryOffsets;
    NSMutableArray * _displayedMenuColumnMetrics;
    double  _displayedMenuContentWidth;
    _UIKeyShortcutHUDShortcutColumnMetrics * _displayedSearchColumnMetrics;
    unsigned long long  _numCellsPerColumn;
    double  _searchButtonWidth;
    double  _searchModePreferredMenuPanelHeight;
    bool  _searching;
    UIView * _selfSizingPlayground;
    _UIKeyShortcutHUDToolbarSearchCell * _selfSizingSearchCell;
    _UIKeyShortcutHUDShortcutCell * _selfSizingShortcutCell;
    _UIKeyShortcutHUDToolbarCategoryCell * _selfSizingToolbarCategoryCell;
    NSMapTable * _shortcutCellIndexPathsMap;
    NSMapTable * _shortcutCellMetricsMap;
    bool  _shouldDisplayEscShortcutAlternative;
    bool  _shouldDisplayGlobeModiferAsGlobeSymbol;
    bool  _shouldMirrorShortcutInputs;
    UITraitCollection * _traitCollection;
    double  _widestToolbarCategoryCellWidth;
}

@property (nonatomic) double availableVerticalSpace;
@property (nonatomic) _UIKeyShortcutHUDMenu *baseMenu;
@property (nonatomic, readonly) unsigned long long baseNumberOfVisibleColumns;
@property (nonatomic, readonly) UIFont *cancelButtonFont;
@property (nonatomic, readonly) UIFont *categoryHeaderFont;
@property (nonatomic, readonly) double categoryHeaderVerticalTextAdjustment;
@property (nonatomic, readonly) double cellFlashDuration;
@property (nonatomic) _UIKeyShortcutHUDClientTraits *clientTraits;
@property (getter=areShortcutAndAlternateColumnWidthsCombined, nonatomic, readonly) bool combinedShortcutAndAlternateColumnWidths;
@property (nonatomic) double computedHUDWidthForBaseMenu;
@property (nonatomic, readonly) unsigned long long contentSizeAdjustedMaxNumberOfCellsPerColumn;
@property (nonatomic, readonly) _UIKeyShortcutHUDMenu *displayedMenu;
@property (nonatomic, retain) NSMutableArray *displayedMenuCategoryOffsets;
@property (nonatomic, retain) NSMutableArray *displayedMenuColumnMetrics;
@property (nonatomic, readonly) double displayedMenuContentWidth;
@property (nonatomic, retain) _UIKeyShortcutHUDShortcutColumnMetrics *displayedSearchColumnMetrics;
@property (nonatomic, readonly) double emptyColumnWidth;
@property (nonatomic, readonly) double hiddenMenuPanelHeight;
@property (nonatomic, readonly) double hiddenMenuPanelWidth;
@property (nonatomic, readonly) long long hudBlurStyle;
@property (getter=isHUDShrunkToFitHorizontally, nonatomic, readonly) bool hudShrunkToFitHorizontally;
@property (nonatomic, readonly) UIFont *keyShortcutInputCharacterFont;
@property (nonatomic, readonly) UIFont *keyShortcutInputSymbolFont;
@property (nonatomic, readonly) UIFont *keyShortcutInputWordFont;
@property (nonatomic, readonly) UIFont *keyShortcutModifiersFont;
@property (nonatomic, readonly) unsigned long long maxNumberOfCellsInSearchResults;
@property (nonatomic, readonly) unsigned long long maxNumberOfCellsPerColumn;
@property (nonatomic, readonly) double maxShortcutCellWidth;
@property (nonatomic, readonly) double menuBaseVerticalContentInset;
@property (nonatomic, readonly) double menuBottomContentInset;
@property (nonatomic, readonly) double menuCellCornerRadius;
@property (nonatomic, readonly) double menuCellHeight;
@property (nonatomic, readonly) double menuCellHorizontalContentMargin;
@property (nonatomic, readonly) double menuColumnSpacing;
@property (nonatomic, readonly) double menuHorizontalContentInset;
@property (nonatomic, readonly) unsigned long long menuPanelCornerMask;
@property (nonatomic, readonly) double menuPanelStrokeWidth;
@property (nonatomic, readonly) double menuPlatterCornerRadius;
@property (nonatomic, readonly) UIColor *menuSeparatorColor;
@property (nonatomic, readonly) double menuSeparatorHorizontalMargin;
@property (nonatomic, readonly) UIVisualEffect *menuSeparatorVisualEffect;
@property (nonatomic, readonly) double menuTopContentInset;
@property (nonatomic, readonly) double minShortcutCellWidth;
@property (nonatomic, readonly) double minShortcutNameKeyCombinationSpacing;
@property (nonatomic, readonly) double minimumBottomScreenEdgeDistance;
@property (nonatomic, readonly) double minimumScreenEdgeDistance;
@property (nonatomic, readonly) unsigned long long numCellsPerColumn;
@property (nonatomic, readonly) NSDictionary *platterSeparatedOptions;
@property (nonatomic, readonly) double platterShadowOpacity;
@property (nonatomic, readonly) double platterShadowRadius;
@property (nonatomic, readonly) UIColor *platterStrokeColor;
@property (nonatomic, readonly) UIVisualEffect *platterVisualEffect;
@property (nonatomic, readonly) double platterZPosition;
@property (nonatomic, readonly) double searchButtonWidth;
@property (nonatomic, readonly) UIColor *searchHUDTextColor;
@property (nonatomic, readonly) double searchModeMaximumMenuPanelHeight;
@property (nonatomic, readonly) double searchModeMenuBaseVerticalContentInset;
@property (nonatomic, readonly) double searchModeMenuBottomContentInset;
@property (nonatomic, readonly) double searchModeMenuTopContentInset;
@property (nonatomic, readonly) double searchModePreferredMenuPanelHeight;
@property (nonatomic, readonly) double searchModePreferredMenuPanelWidth;
@property (nonatomic, readonly) double searchModeStandardHUDWidth;
@property (getter=isSearching, nonatomic, readonly) bool searching;
@property (nonatomic) UIView *selfSizingPlayground;
@property (nonatomic, readonly) _UIKeyShortcutHUDToolbarSearchCell *selfSizingSearchCell;
@property (nonatomic, readonly) _UIKeyShortcutHUDShortcutCell *selfSizingShortcutCell;
@property (nonatomic, readonly) _UIKeyShortcutHUDToolbarCategoryCell *selfSizingToolbarCategoryCell;
@property (nonatomic, readonly) double separatorWidth;
@property (nonatomic, retain) NSMapTable *shortcutCellIndexPathsMap;
@property (nonatomic, retain) NSMapTable *shortcutCellMetricsMap;
@property (nonatomic, readonly) UIFont *shortcutSubtitleFont;
@property (nonatomic, readonly) UIColor *shortcutSubtitleTextColor;
@property (nonatomic, readonly) double shortcutTitleToSubtitleVerticalPadding;
@property (nonatomic, readonly) bool shouldAlignShortcutModifiersAndInputInColumn;
@property (nonatomic, readonly) bool shouldDisplayEscShortcutAlternative;
@property (nonatomic, readonly) bool shouldDisplayGlobeModiferAsGlobeSymbol;
@property (nonatomic, readonly) bool shouldExtendToolbarThroughSafeArea;
@property (nonatomic, readonly) bool shouldMirrorShortcutInputs;
@property (nonatomic, readonly) UIFont *standardHUDFont;
@property (nonatomic, readonly) UIColor *standardHUDTextColor;
@property (nonatomic, readonly) double standardHUDWidth;
@property (nonatomic, readonly) double standardMenuPadding;
@property (nonatomic, readonly) double standardMenuPanelHeight;
@property (nonatomic, readonly) double standardMenuToolbarSpacing;
@property (nonatomic, readonly) double standardPlatterStrokeWidth;
@property (nonatomic, readonly) double standardShortcutInputReservedWidth;
@property (nonatomic, readonly) double standardShortcutModifierInputMinimumSpacing;
@property (nonatomic, readonly) double standardToolbarContentHeight;
@property (nonatomic, readonly) UIFont *toolbarCategoryRegularFont;
@property (nonatomic, readonly) UIFont *toolbarCategoryVisibleFont;
@property (nonatomic, readonly) double toolbarCellCornerRadius;
@property (nonatomic, readonly) double toolbarContentInset;
@property (nonatomic, readonly) unsigned long long toolbarPanelCornerMask;
@property (nonatomic, readonly) double toolbarPanelStrokeWidth;
@property (nonatomic, readonly) double toolbarPlatterCornerRadius;
@property (nonatomic, readonly) UIColor *toolbarSeparatorColor;
@property (nonatomic, readonly) double toolbarSeparatorVerticalMargin;
@property (nonatomic, readonly) UIVisualEffect *toolbarSeparatorVisualEffect;
@property (nonatomic, readonly) bool toolbarStylesCategoriesAsPageControl;
@property (nonatomic, retain) UITraitCollection *traitCollection;
@property (nonatomic, readonly) double widestToolbarCategoryCellWidth;

+ (id)currentMetrics;
+ (void)setCurrentMetrics:(id)arg1;

- (void).cxx_destruct;
- (void)_computeAndStoreCellMetricsForShortcut:(id)arg1 indexPath:(id)arg2;
- (double)_computedWidthForCategoryAtIndex:(unsigned long long)arg1;
- (void)_setDisplayedMenu:(id)arg1 searching:(bool)arg2 combinedShortcutAndAlternateColumnWidths:(bool)arg3;
- (double)_shortcutWidthAdjustmentForMetrics:(id)arg1 shortcutWidth:(double)arg2;
- (double)_toolbarContentToWindowBottomEdgeSpacing;
- (double)_toolbarDistanceFromBottomOfWindow;
- (double)_toolbarHeight;
- (void)_updateBaseMenuMetrics;
- (void)_updateDisplayedMenuMetrics;
- (void)_updateDisplayedSearchMenuMetrics;
- (void)_updateDisplayedStandardMenuMetrics;
- (bool)areShortcutAndAlternateColumnWidthsCombined;
- (double)availableVerticalSpace;
- (id)baseMenu;
- (unsigned long long)baseNumberOfVisibleColumns;
- (id)cancelButtonFont;
- (id)categoryHeaderFont;
- (double)categoryHeaderVerticalTextAdjustment;
- (unsigned long long)categoryIndexAtHorizontalOffset:(double)arg1;
- (double)cellFlashDuration;
- (double)cellWidthForShortcut:(id)arg1;
- (id)clientTraits;
- (void)computeOneTimeMetrics;
- (double)computedHUDWidthForBaseMenu;
- (unsigned long long)contentSizeAdjustedMaxNumberOfCellsPerColumn;
- (double)contentSizeScaledMetric:(double)arg1;
- (id)displayedMenu;
- (id)displayedMenuCategoryOffsets;
- (id)displayedMenuColumnMetrics;
- (double)displayedMenuContentWidth;
- (id)displayedSearchColumnMetrics;
- (double)emptyColumnWidth;
- (double)headerWidthForCategory:(id)arg1;
- (double)hiddenMenuPanelHeight;
- (double)hiddenMenuPanelWidth;
- (double)horizontalOffsetForCategoryAtIndex:(unsigned long long)arg1;
- (long long)hudBlurStyle;
- (double)inputWidthForShortcut:(id)arg1;
- (bool)isHUDShrunkToFitHorizontally;
- (bool)isSearching;
- (id)keyShortcutInputCharacterFont;
- (id)keyShortcutInputSymbolFont;
- (id)keyShortcutInputWordFont;
- (id)keyShortcutModifiersFont;
- (unsigned long long)maxNumberOfCellsInSearchResults;
- (unsigned long long)maxNumberOfCellsPerColumn;
- (double)maxShortcutCellWidth;
- (double)menuBaseVerticalContentInset;
- (double)menuBottomContentInset;
- (double)menuCellCornerRadius;
- (double)menuCellHeight;
- (double)menuCellHorizontalContentMargin;
- (double)menuColumnSpacing;
- (double)menuHorizontalContentInset;
- (unsigned long long)menuPanelCornerMask;
- (double)menuPanelStrokeWidth;
- (double)menuPlatterCornerRadius;
- (id)menuSeparatorColor;
- (double)menuSeparatorHorizontalMargin;
- (id)menuSeparatorVisualEffect;
- (double)menuTopContentInset;
- (double)minShortcutCellWidth;
- (double)minShortcutNameKeyCombinationSpacing;
- (double)minimumBottomScreenEdgeDistance;
- (double)minimumScreenEdgeDistance;
- (double)modifiersWidthForShortcut:(id)arg1;
- (unsigned long long)numCellsPerColumn;
- (id)platterSeparatedOptions;
- (double)platterShadowOpacity;
- (double)platterShadowRadius;
- (id)platterStrokeColor;
- (id)platterVisualEffect;
- (double)platterZPosition;
- (double)searchButtonWidth;
- (id)searchHUDTextColor;
- (double)searchModeMaximumMenuPanelHeight;
- (double)searchModeMenuBaseVerticalContentInset;
- (double)searchModeMenuBottomContentInset;
- (double)searchModeMenuTopContentInset;
- (double)searchModePreferredMenuPanelHeight;
- (double)searchModePreferredMenuPanelWidth;
- (double)searchModeStandardHUDWidth;
- (id)selfSizingPlayground;
- (id)selfSizingSearchCell;
- (id)selfSizingShortcutCell;
- (id)selfSizingToolbarCategoryCell;
- (double)separatorWidth;
- (void)setAvailableVerticalSpace:(double)arg1;
- (void)setBaseMenu:(id)arg1;
- (void)setClientTraits:(id)arg1;
- (void)setComputedHUDWidthForBaseMenu:(double)arg1;
- (void)setDisplayedMenu:(id)arg1 searching:(bool)arg2;
- (void)setDisplayedMenuCategoryOffsets:(id)arg1;
- (void)setDisplayedMenuColumnMetrics:(id)arg1;
- (void)setDisplayedSearchColumnMetrics:(id)arg1;
- (void)setSelfSizingPlayground:(id)arg1;
- (void)setShortcutCellIndexPathsMap:(id)arg1;
- (void)setShortcutCellMetricsMap:(id)arg1;
- (void)setTraitCollection:(id)arg1;
- (id)shortcutCellIndexPathsMap;
- (id)shortcutCellMetricsMap;
- (id)shortcutSubtitleFont;
- (id)shortcutSubtitleTextColor;
- (double)shortcutTitleToSubtitleVerticalPadding;
- (bool)shouldAlignShortcutModifiersAndInputInColumn;
- (bool)shouldDisplayEscShortcutAlternative;
- (bool)shouldDisplayGlobeModiferAsGlobeSymbol;
- (bool)shouldExtendToolbarThroughSafeArea;
- (bool)shouldMirrorShortcutInputs;
- (id)standardHUDFont;
- (id)standardHUDTextColor;
- (double)standardHUDWidth;
- (double)standardMenuPadding;
- (double)standardMenuPanelHeight;
- (double)standardMenuToolbarSpacing;
- (double)standardPlatterStrokeWidth;
- (double)standardShortcutInputReservedWidth;
- (double)standardShortcutModifierInputMinimumSpacing;
- (double)standardToolbarContentHeight;
- (id)toolbarCategoryRegularFont;
- (id)toolbarCategoryVisibleFont;
- (double)toolbarCellCornerRadius;
- (double)toolbarContentInset;
- (unsigned long long)toolbarPanelCornerMask;
- (double)toolbarPanelStrokeWidth;
- (double)toolbarPlatterCornerRadius;
- (id)toolbarSeparatorColor;
- (double)toolbarSeparatorVerticalMargin;
- (id)toolbarSeparatorVisualEffect;
- (bool)toolbarStylesCategoriesAsPageControl;
- (id)traitCollection;
- (double)widestToolbarCategoryCellWidth;

@end
