
@interface CSAudioInjectionProvider : CSAudioRecorder <CSAudioInjectionEngineDelegate> {
    unsigned long long  _activateEndTime;
    unsigned long long  _activateStartTime;
    bool  _allowZeroInjection;
    NSString * _atvRemoteDeviceID;
    NSMutableDictionary * _audioInjectionEngines;
    CSAudioRecordContext * _audioRecordContext;
    CSAudioInjectionEngine * _builtInAudioInjectionEngine;
    CSAudioInjectionDevice * _builtInDevice;
    CSAudioInjectionDevice * _bundleTvRemote;
    NSMutableArray * _connectedDevices;
    unsigned long long  _deactivateEndTime;
    unsigned long long  _deactivateStartTime;
    float  _didStartDelayInSeconds;
    unsigned long long  _latestPluginStreamId;
    NSHashTable * _observers;
    NSObject<OS_dispatch_queue> * _queue;
    NSUUID * _uuid;
}

@property (nonatomic) unsigned long long activateEndTime;
@property (nonatomic) unsigned long long activateStartTime;
@property (nonatomic) bool allowZeroInjection;
@property (nonatomic, retain) NSString *atvRemoteDeviceID;
@property (nonatomic, retain) NSMutableDictionary *audioInjectionEngines;
@property (nonatomic, retain) CSAudioRecordContext *audioRecordContext;
@property (nonatomic, retain) CSAudioInjectionEngine *builtInAudioInjectionEngine;
@property (nonatomic, retain) CSAudioInjectionDevice *builtInDevice;
@property (nonatomic, retain) CSAudioInjectionDevice *bundleTvRemote;
@property (nonatomic, retain) NSMutableArray *connectedDevices;
@property (nonatomic) unsigned long long deactivateEndTime;
@property (nonatomic) unsigned long long deactivateStartTime;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) float didStartDelayInSeconds;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned long long latestPluginStreamId;
@property (nonatomic, retain) NSHashTable *observers;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSUUID *uuid;

+ (void)createSharedAudioSession;
+ (id)defaultInjectionProvider;

- (void).cxx_destruct;
- (void)_connectPluginDevice:(id)arg1;
- (void)_createSpeechDetectionVADIfNeeded;
- (void)_tearDownSpeechDetectionVADIfNeeded;
- (bool)activateAudioSessionWithReason:(unsigned long long)arg1 streamHandleId:(unsigned long long)arg2 error:(id*)arg3;
- (unsigned long long)activateEndTime;
- (unsigned long long)activateStartTime;
- (unsigned long long)alertStartTime;
- (bool)allowZeroInjection;
- (id)atvRemoteDeviceID;
- (id)audioDeviceInfoWithStreamHandleId:(unsigned long long)arg1 recordDeviceIndicator:(id)arg2;
- (void)audioEngineAudioChunkForTvAvailable:(id)arg1 audioChunk:(id)arg2;
- (void)audioEngineBufferAvailable:(id)arg1 audioStreamHandleId:(unsigned long long)arg2 buffer:(id)arg3 remoteVAD:(id)arg4 atTime:(unsigned long long)arg5 isFileLoadedBuffer:(bool)arg6;
- (void)audioEngineDidStartRecord:(id)arg1 audioStreamHandleId:(unsigned long long)arg2 successfully:(bool)arg3 error:(id)arg4;
- (void)audioEngineDidStopRecord:(id)arg1 audioStreamHandleId:(unsigned long long)arg2 reason:(unsigned long long)arg3;
- (id)audioInjectionEngines;
- (id)audioRecordContext;
- (float)averagePowerForChannel:(unsigned long long)arg1;
- (id)builtInAudioInjectionEngine;
- (id)builtInDevice;
- (id)bundleTvRemote;
- (void)configureAlertBehavior:(id)arg1 audioStreamHandleId:(unsigned long long)arg2;
- (void)connectDevice:(id)arg1;
- (id)connectedDevices;
- (bool)deactivateAudioSession:(unsigned long long)arg1 error:(id*)arg2;
- (bool)deactivateAudioSession:(unsigned long long)arg1 streamHandleId:(unsigned long long)arg2 error:(id*)arg3;
- (unsigned long long)deactivateEndTime;
- (unsigned long long)deactivateStartTime;
- (void)dealloc;
- (float)didStartDelayInSeconds;
- (void)disconnectDevice:(id)arg1;
- (bool)duckOthersOption;
- (void)enableMiniDucking:(bool)arg1;
- (id)fetchGibraltarVoiceTriggerInfoWithRecordDeviceIndicator:(id)arg1;
- (id)getPlaybackRouteForStreamID:(unsigned long long)arg1;
- (id)init;
- (bool)isNarrowBandWithStreamHandleId:(unsigned long long)arg1;
- (bool)isRecordingWithRecordDeviceIndicator:(id)arg1;
- (bool)isSessionCurrentlyActivated;
- (unsigned long long)latestPluginStreamId;
- (id)metrics;
- (id)observers;
- (float)peakPowerForChannel:(unsigned long long)arg1;
- (bool)playAlertSoundForType:(long long)arg1 recordDevideIndicator:(id)arg2;
- (bool)playRecordStartingAlertAndResetEndpointerFromStream:(unsigned long long)arg1 withAlertOverride:(long long)arg2;
- (bool)prepareAudioStreamRecord:(id)arg1 recordDeviceIndicator:(id)arg2 error:(id*)arg3;
- (bool)prewarmAudioSessionWithStreamHandleId:(unsigned long long)arg1 error:(id*)arg2;
- (id)primaryInputDevice;
- (id)queue;
- (id)recordDeviceInfoWithStreamHandleId:(unsigned long long)arg1 recordDeviceIndicator:(id)arg2;
- (id)recordRouteWithRecordDeviceIndicator:(id)arg1;
- (id)recordSettingsWithStreamHandleId:(unsigned long long)arg1;
- (float)recordingSampleRateWithStreamHandleId:(unsigned long long)arg1;
- (void)registerObserver:(id)arg1;
- (void)setActivateEndTime:(unsigned long long)arg1;
- (void)setActivateStartTime:(unsigned long long)arg1;
- (bool)setAlertSoundFromURL:(id)arg1 forType:(long long)arg2 force:(bool)arg3;
- (void)setAllowZeroInjection:(bool)arg1;
- (void)setAtvRemoteDeviceID:(id)arg1;
- (void)setAudioInjectionEngines:(id)arg1;
- (void)setAudioRecordContext:(id)arg1;
- (void)setAudioSessionEventDelegate:(id)arg1;
- (void)setBuiltInAudioInjectionEngine:(id)arg1;
- (void)setBuiltInDevice:(id)arg1;
- (void)setBundleTvRemote:(id)arg1;
- (void)setConnectedDevices:(id)arg1;
- (void)setContext:(id)arg1 completion:(id /* block */)arg2;
- (bool)setCurrentContext:(id)arg1 streamHandleId:(unsigned long long)arg2 error:(id*)arg3;
- (void)setDeactivateEndTime:(unsigned long long)arg1;
- (void)setDeactivateStartTime:(unsigned long long)arg1;
- (void)setDidStartDelayInSeconds:(float)arg1;
- (void)setDuckOthersOption:(bool)arg1;
- (void)setLatestPluginStreamId:(unsigned long long)arg1;
- (void)setMeteringEnabled:(bool)arg1;
- (void)setObservers:(id)arg1;
- (void)setQueue:(id)arg1;
- (bool)setRecordMode:(long long)arg1 streamHandleId:(unsigned long long)arg2 error:(id*)arg3;
- (void)setUuid:(id)arg1;
- (void)start;
- (bool)startAudioStreamWithOption:(id)arg1 recordDeviceIndicator:(id)arg2 error:(id*)arg3;
- (void)stop;
- (bool)stopAudioStreamWithRecordDeviceIndicator:(id)arg1 error:(id*)arg2;
- (void)unregisterObserver:(id)arg1;
- (void)updateMeters;
- (id)uuid;
- (void)willDestroy;

@end
