
@interface USKData : NSObject {
    unsigned long long  _arraySize;
    USKNode * _nodeOwner;
    USKProperty * _propertyOwner;
    USKScene * _sceneOwner;
    NSString * _type;
    struct VtValue { 
        struct type { 
            unsigned char __lx[8]; 
        } _storage; 
        struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::VtValue::_TypeInfo> { 
            struct _TypeInfo {} *_ptrAndBits; 
        } _info; 
    }  _value;
}

@property (nonatomic, readonly) unsigned long long arraySize;
@property (nonatomic, readonly, retain) NSData *dataNoCopy;
@property (nonatomic, readonly) NSString *type;

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)arraySize;
- (bool)boolValue;
- (id)dataNoCopy;
- (unsigned long long)double2Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 maxCount:(unsigned long long)arg2;
- (void)double2Value;
- (unsigned long long)double3Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 maxCount:(unsigned long long)arg2;
- (void)double3Value;
- (unsigned long long)double4Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 maxCount:(unsigned long long)arg2;
- (void)double4Value;
- (unsigned long long)double4x4Array:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; }*)arg1 maxCount:(unsigned long long)arg2;
- (struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; })double4x4Value;
- (unsigned long long)doubleArray:(double*)arg1 maxCount:(unsigned long long)arg2;
- (double)doubleValue;
- (unsigned long long)float2Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 maxCount:(unsigned long long)arg2;
- (void)float2Value;
- (unsigned long long)float3Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 maxCount:(unsigned long long)arg2;
- (void)float3Value;
- (unsigned long long)float4Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 maxCount:(unsigned long long)arg2;
- (void)float4Value;
- (unsigned long long)float4x4Array:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; }*)arg1 maxCount:(unsigned long long)arg2;
- (struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; })float4x4Value;
- (unsigned long long)floatArray:(float*)arg1 maxCount:(unsigned long long)arg2;
- (float)floatValue;
- (unsigned long long)hash;
- (id)initWithBool:(bool)arg1;
- (id)initWithDouble2;
- (id)initWithDouble2Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (id)initWithDouble3;
- (id)initWithDouble3Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (id)initWithDouble4;
- (id)initWithDouble4Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (id)initWithDouble4x4:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; })arg1;
- (id)initWithDouble4x4Array:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; }*)arg1 count:(unsigned long long)arg2;
- (id)initWithDouble:(double)arg1;
- (id)initWithDoubleArray:(double*)arg1 count:(unsigned long long)arg2;
- (id)initWithFloat2;
- (id)initWithFloat2Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (id)initWithFloat3;
- (id)initWithFloat3Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (id)initWithFloat4;
- (id)initWithFloat4Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (id)initWithFloat:(float)arg1;
- (id)initWithFloatArray:(float*)arg1 count:(unsigned long long)arg2;
- (id)initWithInt:(int)arg1;
- (id)initWithIntArray:(int*)arg1 count:(unsigned long long)arg2;
- (id)initWithObjectPath:(id)arg1;
- (id)initWithQuatf:(struct { })arg1;
- (id)initWithQuatfArray:(struct { }*)arg1 count:(unsigned long long)arg2;
- (id)initWithResourcePath:(id)arg1;
- (id)initWithResourcePathArray:(id)arg1;
- (id)initWithString:(id)arg1;
- (id)initWithStringArray:(id)arg1;
- (id)initWithTimeCode:(id)arg1;
- (id)initWithToken:(id)arg1;
- (id)initWithTokenArray:(id)arg1;
- (id)initWithUInt:(unsigned int)arg1;
- (id)initWithUIntArray:(unsigned int*)arg1 count:(unsigned long long)arg2;
- (id)initWithURL:(id)arg1;
- (id)initWithVtValue:(struct VtValue { struct type { unsigned char x_1_1_1[8]; } x1; struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::VtValue::_TypeInfo> { struct _TypeInfo {} *x_2_1_1; } x2; })arg1 typeName:(struct TfToken { struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::TfToken::_Rep> { struct _Rep {} *x_1_1_1; } x1; })arg2;
- (id)initWithVtValue:(struct VtValue { struct type { unsigned char x_1_1_1[8]; } x1; struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::VtValue::_TypeInfo> { struct _TypeInfo {} *x_2_1_1; } x2; })arg1 typeName:(struct TfToken { struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::TfToken::_Rep> { struct _Rep {} *x_1_1_1; } x1; })arg2 withNodeOwner:(id)arg3;
- (id)initWithVtValue:(struct VtValue { struct type { unsigned char x_1_1_1[8]; } x1; struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::VtValue::_TypeInfo> { struct _TypeInfo {} *x_2_1_1; } x2; })arg1 typeName:(struct TfToken { struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::TfToken::_Rep> { struct _Rep {} *x_1_1_1; } x1; })arg2 withPropertyOwner:(id)arg3;
- (id)initWithVtValue:(struct VtValue { struct type { unsigned char x_1_1_1[8]; } x1; struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::VtValue::_TypeInfo> { struct _TypeInfo {} *x_2_1_1; } x2; })arg1 typeName:(struct TfToken { struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::TfToken::_Rep> { struct _Rep {} *x_1_1_1; } x1; })arg2 withSceneOwner:(id)arg3;
- (unsigned long long)intArray:(int*)arg1 maxCount:(unsigned long long)arg2;
- (int)intValue;
- (bool)isEqual:(id)arg1;
- (id)objectPathValue;
- (id)pathArray;
- (unsigned long long)quatfArray:(struct { }*)arg1 maxCount:(unsigned long long)arg2;
- (struct { })quatfValue;
- (id)resourcePath;
- (id)resourcePathArray;
- (void)setBoolValue:(bool)arg1;
- (void)setDouble2Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (void)setDouble2Value;
- (void)setDouble3Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (void)setDouble3Value;
- (void)setDouble4Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (void)setDouble4Value;
- (void)setDouble4x4Array:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; }*)arg1 count:(unsigned long long)arg2;
- (void)setDouble4x4Value:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; })arg1;
- (void)setDoubleArray:(double*)arg1 count:(unsigned long long)arg2;
- (void)setDoubleValue:(double)arg1;
- (void)setFloat2Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (void)setFloat2Value;
- (void)setFloat3Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (void)setFloat3Value;
- (void)setFloat4Array:(/* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
- (void)setFloat4Value;
- (void)setFloatArray:(float*)arg1 count:(unsigned long long)arg2;
- (void)setFloatValue:(float)arg1;
- (void)setIntArray:(int*)arg1 count:(unsigned long long)arg2;
- (void)setIntValue:(int)arg1;
- (void)setObjectPathValue:(id)arg1;
- (void)setQuatfArray:(struct { }*)arg1 count:(unsigned long long)arg2;
- (void)setQuatfValue:(struct { })arg1;
- (void)setResourcePath:(id)arg1;
- (void)setResourcePathArray:(id)arg1;
- (void)setStringArray:(id)arg1;
- (void)setStringValue:(id)arg1;
- (void)setTimeCodeValue:(id)arg1;
- (void)setTokenArray:(id)arg1;
- (void)setTokenValue:(id)arg1;
- (void)setUIntArray:(unsigned int*)arg1 count:(unsigned long long)arg2;
- (void)setUIntValue:(unsigned int)arg1;
- (void)setURLValue:(id)arg1;
- (void)setValue:(struct VtValue { struct type { unsigned char x_1_1_1[8]; } x1; struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::VtValue::_TypeInfo> { struct _TypeInfo {} *x_2_1_1; } x2; })arg1;
- (id)stringArray;
- (id)stringValue;
- (id)timeCodeValue;
- (id)tokenArray;
- (id)tokenValue;
- (id)type;
- (unsigned long long)uintArray:(unsigned int*)arg1 maxCount:(unsigned long long)arg2;
- (unsigned int)uintValue;
- (id)urlValue;
- (struct VtValue { struct type { unsigned char x_1_1_1[8]; } x1; struct TfPointerAndBits<const pxrInternal_v0_22__aapl__pxrReserved__::VtValue::_TypeInfo> { struct _TypeInfo {} *x_2_1_1; } x2; })value;

@end
