
@interface CWFNetworkProfile : NSObject <CWFJSONEncodable, NSCopying, NSSecureCoding, WFNetworkListRecord> {
    NSString * _cachedIdentifier;
    NSString * _cachedNetworkName;
    unsigned long long  _cachedShortSSID;
    NSMutableDictionary * _internal;
    bool  _useCachedIdentifier;
    bool  _useCachedNetworkName;
    bool  _useCachedShortSSID;
}

@property (nonatomic, copy) NSSet *BSSList;
@property (nonatomic, copy) NSDictionary *DNSHeuristicsFailureStateInfo;
@property (getter=isDNSHeuristicsFilteredNetwork, nonatomic) bool DNSHeuristicsFilteredNetwork;
@property (nonatomic, copy) NSDictionary *EAPProfile;
@property (nonatomic, copy) NSArray *NAIRealmNameList;
@property (nonatomic, copy) NSString *NANServiceID;
@property (nonatomic, copy) NSDictionary *OSSpecificAttributes;
@property (nonatomic, copy) NSData *SSID;
@property (nonatomic, readonly, copy) NSArray *TLSTrustedServerNames;
@property (nonatomic) long long WAPISubtype;
@property (nonatomic) long long WEPSubtype;
@property (nonatomic, readonly, copy) NSArray *acceptedEAPTypes;
@property (nonatomic) long long addReason;
@property (nonatomic, copy) NSDate *addedAt;
@property (getter=isAutoJoinDisabled, nonatomic) bool autoJoinDisabled;
@property (getter=isBlueAtlasNetwork, nonatomic) bool blueAtlasNetwork;
@property (nonatomic, copy) NSString *bundleID;
@property (nonatomic, readonly) bool bypassCaptive;
@property (nonatomic, retain) NSString *cachedIdentifier;
@property (nonatomic, retain) NSString *cachedNetworkName;
@property (nonatomic) unsigned long long cachedShortSSID;
@property (nonatomic, copy) NSDictionary *captiveProfile;
@property (getter=isCarPlayNetwork, nonatomic) bool carplayNetwork;
@property (nonatomic, copy) NSString *carplayUUID;
@property (nonatomic, copy) NSArray *cellularNetworkInfo;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDictionary *dictionary;
@property (nonatomic) long long disable6EMode;
@property (nonatomic, copy) NSDate *disable6EModeTimestamp;
@property (nonatomic, copy) NSString *displayedOperatorName;
@property (nonatomic, copy) NSString *domainName;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long hiddenState;
@property (nonatomic, readonly, copy) NSArray *innerAcceptedEAPTypes;
@property (nonatomic, retain) NSMutableDictionary *internal;
@property (nonatomic, readonly) bool isAllowedInLockdownMode;
@property (nonatomic, readonly) bool isAmbiguousNetworkName;
@property (nonatomic, readonly) bool isAppBased;
@property (nonatomic, readonly) bool isCaptive;
@property (nonatomic, readonly) bool isCaptiveStateDetermined;
@property (nonatomic, readonly) bool isCarPlay;
@property (nonatomic, readonly) bool isEAP;
@property (nonatomic, readonly) bool isOWE;
@property (nonatomic, readonly) bool isOpen;
@property (nonatomic, readonly) bool isPSK;
@property (nonatomic, readonly) bool isPasspoint;
@property (nonatomic, readonly) bool isPasswordSharingSupported;
@property (nonatomic, readonly) bool isProfileBased;
@property (nonatomic, readonly) bool isTLSCertificateRequired;
@property (nonatomic, readonly) bool isWAPI;
@property (nonatomic, readonly) bool isWEP;
@property (nonatomic, readonly) bool isWPA;
@property (nonatomic, readonly) bool isWPA2;
@property (nonatomic, readonly) bool isWPA3;
@property (nonatomic, copy) NSDate *lastDiscoveredAt;
@property (nonatomic, readonly, copy) NSDate *lastJoinedAt;
@property (nonatomic, copy) NSDate *lastJoinedBySystemAt;
@property (nonatomic) unsigned long long lastJoinedBySystemAtWeek;
@property (nonatomic, copy) NSDate *lastJoinedByUserAt;
@property (nonatomic, readonly, copy) NSDate *lastJoinedOnAnyDeviceAt;
@property (nonatomic) long long lowDataMode;
@property (nonatomic) long long movingAttribute;
@property (nonatomic) long long nearbyShareableStatus;
@property (nonatomic, copy) NSString *networkGroupID;
@property (nonatomic) unsigned long long networkGroupPriority;
@property (nonatomic, readonly, copy) NSString *networkName;
@property (getter=isPasswordSharingDisabled, nonatomic) bool passwordSharingDisabled;
@property (nonatomic, copy) NSString *payloadUUID;
@property (getter=isPersonalHotspot, nonatomic) bool personalHotspot;
@property (nonatomic, copy) NSString *privacyProxyBlockedReason;
@property (getter=isPrivacyProxyEnabled, nonatomic) bool privacyProxyEnabled;
@property (nonatomic, readonly, copy) NSSet *properties;
@property (getter=isPublicAirPlayNetwork, nonatomic) bool publicAirPlayNetwork;
@property (nonatomic) long long publicAttribute;
@property (nonatomic, copy) NSArray *roamingConsortiumList;
@property (nonatomic, copy) NSArray *seamlessSSIDList;
@property (getter=isServiceProviderRoamingEnabled, nonatomic) bool serviceProviderRoamingEnabled;
@property (getter=isSessionBased, nonatomic) bool sessionBased;
@property (nonatomic, readonly) unsigned long long shortSSID;
@property (getter=isStandalone6G, nonatomic) bool standalone6G;
@property (nonatomic, readonly) unsigned long long strongestSupportedSecurityType;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long supportedSecurityTypes;
@property (getter=isSystemMode, nonatomic) bool systemMode;
@property (nonatomic) int transitionDisabledFlags;
@property (nonatomic, copy) NSDate *updatedAt;
@property (nonatomic) bool useCachedIdentifier;
@property (nonatomic) bool useCachedNetworkName;
@property (nonatomic) bool useCachedShortSSID;
@property (nonatomic, copy) NSDictionary *userPreferredNetworkNames;
@property (nonatomic, copy) NSDictionary *userPreferredPasspointDomains;
@property (nonatomic, copy) NSDate *was6GHzOnlyAt;
@property (nonatomic) unsigned long long was6GHzOnlyAtWeek;
@property (nonatomic, readonly, copy) NSDate *was6GHzOnlyOnAnyDeviceAt;
@property (nonatomic, readonly) bool wasCaptive;
@property (nonatomic) bool wasMoreRecentlyJoinedByUser;
@property (nonatomic, readonly) bool wasRecently6GHzOnlyOnAnyDevice;
@property (nonatomic, readonly) unsigned long long weakestSupportedSecurityType;

// Image: /System/Library/PrivateFrameworks/CoreWiFi.framework/CoreWiFi

+ (id)supportedOSSpecificKeys;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)BSSList;
- (id)DNSHeuristicsFailureStateInfo;
- (id)EAPProfile;
- (id)JSONCompatibleKeyValueMap;
- (id)NAIRealmNameList;
- (id)NANServiceID;
- (id)OSSpecificAttributes;
- (id)OSSpecificValueForKey:(id)arg1;
- (id)OTASystemInfoBeaconProbeList;
- (id)SIMIdentifiers;
- (id)SSID;
- (id)TLSTrustedServerNames;
- (long long)WAPISubtype;
- (long long)WEPSubtype;
- (id)__basicDescription;
- (id)__coreWiFiSpecificProperties;
- (id)__defaultProperties;
- (id)__descriptionFor6EMode;
- (id)__descriptionForBSSListWithLimit:(unsigned long long)arg1;
- (id)__descriptionForCaptiveFlags;
- (id)__descriptionForHiddenState;
- (id)__descriptionForLowDataMode;
- (id)__descriptionForMovingAttribute;
- (id)__descriptionForNearbyShareableStatus;
- (id)__descriptionForPublicAttribute;
- (id)__filteredNetworkProfileWithProperties:(id)arg1 includeRequiredProperties:(bool)arg2 OSSpecificKeys:(id)arg3;
- (id)__keyForProperty:(long long)arg1;
- (long long)__propertyForKey:(id)arg1;
- (id)__requiredProperties;
- (id)acceptedEAPTypes;
- (long long)addReason;
- (id)addedAt;
- (id)bundleID;
- (bool)bypassCaptive;
- (id)cachedIdentifier;
- (id)cachedNetworkName;
- (unsigned long long)cachedShortSSID;
- (id)captiveProfile;
- (id)carplayUUID;
- (id)cellularNetworkInfo;
- (long long)compareSupportedSecurityTypes:(id)arg1;
- (long long)compareUserPriority:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)coreWiFiSpecificAttributes;
- (id)debugDescription;
- (id)description;
- (long long)disable6EMode;
- (id)disable6EModeTimestamp;
- (id)displayedOperatorName;
- (id)domainName;
- (unsigned long long)effectiveSupportedSecurityTypes;
- (void)encodeWithCoder:(id)arg1;
- (id)expirationDate;
- (id)externalForm;
- (id)filteredNetworkProfileWithProperties:(id)arg1;
- (id)filteredNetworkProfileWithProperties:(id)arg1 OSSpecificKeys:(id)arg2;
- (unsigned long long)hash;
- (long long)hiddenState;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithExternalForm:(id)arg1;
- (id)innerAcceptedEAPTypes;
- (id)internal;
- (bool)isAllowedInLockdownMode;
- (bool)isAmbiguousNetworkName;
- (bool)isAppBased;
- (bool)isAutoJoinDisabled;
- (bool)isAutojoinDisabledUntilFirstUserJoin;
- (bool)isBlueAtlasNetwork;
- (bool)isCaptive;
- (bool)isCaptiveStateDetermined;
- (bool)isCarPlay;
- (bool)isCarplayNetwork;
- (bool)isDNSHeuristicsFilteredNetwork;
- (bool)isEAP;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToNetworkProfile:(id)arg1;
- (bool)isHighPopularity;
- (bool)isHighQuality;
- (bool)isLowPopularity;
- (bool)isLowQuality;
- (bool)isOWE;
- (bool)isOpen;
- (bool)isPSK;
- (bool)isPasspoint;
- (bool)isPasspointHomeOperatorNetwork;
- (bool)isPasspointProvisionedNetwork;
- (bool)isPasswordSharingDisabled;
- (bool)isPasswordSharingSupported;
- (bool)isPersonalHotspot;
- (bool)isPotentiallyCaptive;
- (bool)isPotentiallyMoving;
- (bool)isPrivacyProxyEnabled;
- (bool)isProfileBased;
- (bool)isProminentDisplay;
- (bool)isPublicAirPlayNetwork;
- (bool)isServiceProviderRoamingEnabled;
- (bool)isSessionBased;
- (bool)isStandalone6G;
- (bool)isSuspicious;
- (bool)isSystemMode;
- (bool)isTCPGood;
- (bool)isTLSCertificateRequired;
- (bool)isWAPI;
- (bool)isWEP;
- (bool)isWPA;
- (bool)isWPA2;
- (bool)isWPA3;
- (long long)lastDisconnectReason;
- (id)lastDisconnectTimestamp;
- (id)lastDiscoveredAt;
- (id)lastHomeForceFixDate;
- (id)lastJoinedAt;
- (id)lastJoinedBySystemAt;
- (unsigned long long)lastJoinedBySystemAtWeek;
- (id)lastJoinedByUserAt;
- (id)lastJoinedOnAnyDeviceAt;
- (long long)locationOfInterest;
- (long long)lowDataMode;
- (id)matchingKnownBSS:(id)arg1;
- (void)mergeWithNetworkProfile:(id)arg1;
- (long long)movingAttribute;
- (long long)nearbyShareableStatus;
- (id)networkDisabledUntilDate;
- (id)networkGroupID;
- (unsigned long long)networkGroupPriority;
- (id)networkName;
- (long long)networkOfInterestHomeState;
- (long long)networkOfInterestWorkState;
- (id)networkQualityDate;
- (double)networkQualityResponsiveness;
- (id)passpointAccountName;
- (id)payloadUUID;
- (unsigned long long)popularityScore;
- (id)privacyProxyBlockedReason;
- (id)properties;
- (long long)publicAttribute;
- (unsigned long long)qualityScore;
- (id)roamingConsortiumList;
- (id)seamlessSSIDList;
- (void)setAddReason:(long long)arg1;
- (void)setAddedAt:(id)arg1;
- (void)setAutoJoinDisabled:(bool)arg1;
- (void)setBSSList:(id)arg1;
- (void)setBlueAtlasNetwork:(bool)arg1;
- (void)setBundleID:(id)arg1;
- (void)setCachedIdentifier:(id)arg1;
- (void)setCachedNetworkName:(id)arg1;
- (void)setCachedShortSSID:(unsigned long long)arg1;
- (void)setCaptiveProfile:(id)arg1;
- (void)setCarplayNetwork:(bool)arg1;
- (void)setCarplayUUID:(id)arg1;
- (void)setCellularNetworkInfo:(id)arg1;
- (void)setCoreWiFiSpecificAttributes:(id)arg1;
- (void)setDNSHeuristicsFailureStateInfo:(id)arg1;
- (void)setDNSHeuristicsFilteredNetwork:(bool)arg1;
- (void)setDisable6EMode:(long long)arg1;
- (void)setDisable6EModeTimestamp:(id)arg1;
- (void)setDisableAutojoinUntilFirstUserJoin:(bool)arg1;
- (void)setDisplayedOperatorName:(id)arg1;
- (void)setDomainName:(id)arg1;
- (void)setEAPProfile:(id)arg1;
- (void)setExpirationDate:(id)arg1;
- (void)setHiddenState:(long long)arg1;
- (void)setHighPopularity:(bool)arg1;
- (void)setHighQuality:(bool)arg1;
- (void)setInternal:(id)arg1;
- (void)setIsSuspicious:(bool)arg1;
- (void)setIsTCPGood:(bool)arg1;
- (void)setLastDisconnectReason:(long long)arg1;
- (void)setLastDisconnectTimestamp:(id)arg1;
- (void)setLastDiscoveredAt:(id)arg1;
- (void)setLastHomeForceFixDate:(id)arg1;
- (void)setLastJoinedBySystemAt:(id)arg1;
- (void)setLastJoinedBySystemAtWeek:(unsigned long long)arg1;
- (void)setLastJoinedByUserAt:(id)arg1;
- (void)setLocationOfInterest:(long long)arg1;
- (void)setLowDataMode:(long long)arg1;
- (void)setLowPopularity:(bool)arg1;
- (void)setLowQuality:(bool)arg1;
- (void)setMovingAttribute:(long long)arg1;
- (void)setNAIRealmNameList:(id)arg1;
- (void)setNANServiceID:(id)arg1;
- (void)setNearbyShareableStatus:(long long)arg1;
- (void)setNetworkDisabledUntilDate:(id)arg1;
- (void)setNetworkGroupID:(id)arg1;
- (void)setNetworkGroupPriority:(unsigned long long)arg1;
- (void)setNetworkOfInterestHomeState:(long long)arg1;
- (void)setNetworkOfInterestWorkState:(long long)arg1;
- (void)setNetworkQualityDate:(id)arg1;
- (void)setNetworkQualityResponsiveness:(double)arg1;
- (void)setOSSpecificAttributes:(id)arg1;
- (void)setOSSpecificValue:(id)arg1 forKey:(id)arg2;
- (void)setOTASystemInfoBeaconProbeList:(id)arg1;
- (void)setPasspointAccountName:(id)arg1;
- (void)setPasspointHomeOperatorNetwork:(bool)arg1;
- (void)setPasspointProvisionedNetwork:(bool)arg1;
- (void)setPasswordSharingDisabled:(bool)arg1;
- (void)setPayloadUUID:(id)arg1;
- (void)setPersonalHotspot:(bool)arg1;
- (void)setPopularityScore:(unsigned long long)arg1;
- (void)setPotentiallyCaptive:(bool)arg1;
- (void)setPotentiallyMoving:(bool)arg1;
- (void)setPrivacyProxyBlockedReason:(id)arg1;
- (void)setPrivacyProxyEnabled:(bool)arg1;
- (void)setProminentDisplay:(bool)arg1;
- (void)setPublicAirPlayNetwork:(bool)arg1;
- (void)setPublicAttribute:(long long)arg1;
- (void)setQualityScore:(unsigned long long)arg1;
- (void)setRoamingConsortiumList:(id)arg1;
- (void)setSIMIdentifiers:(id)arg1;
- (void)setSSID:(id)arg1;
- (void)setSSIDHarvestStatus:(long long)arg1;
- (void)setSeamlessSSIDList:(id)arg1;
- (void)setServiceProviderRoamingEnabled:(bool)arg1;
- (void)setSessionBased:(bool)arg1;
- (void)setStandalone6G:(bool)arg1;
- (void)setSupportedSecurityTypes:(unsigned long long)arg1;
- (void)setSystemMode:(bool)arg1;
- (void)setTotalNetworkUsage:(unsigned long long)arg1;
- (void)setTransitionDisabledFlags:(int)arg1;
- (void)setUpdatedAt:(id)arg1;
- (void)setUseCachedIdentifier:(bool)arg1;
- (void)setUseCachedNetworkName:(bool)arg1;
- (void)setUseCachedShortSSID:(bool)arg1;
- (void)setUserPreferredNetworkNames:(id)arg1;
- (void)setUserPreferredPasspointDomains:(id)arg1;
- (void)setWAPISubtype:(long long)arg1;
- (void)setWEPSubtype:(long long)arg1;
- (void)setWalletIdentifier:(id)arg1;
- (void)setWas6GHzOnlyAt:(id)arg1;
- (void)setWas6GHzOnlyAtWeek:(unsigned long long)arg1;
- (unsigned long long)shortSSID;
- (long long)ssidHarvestStatus;
- (unsigned long long)strongestSupportedSecurityType;
- (unsigned long long)supportedSecurityTypes;
- (unsigned long long)totalNetworkUsage;
- (int)transitionDisabledFlags;
- (id)updatedAt;
- (bool)useCachedIdentifier;
- (bool)useCachedNetworkName;
- (bool)useCachedShortSSID;
- (id)userPreferredNetworkNames;
- (id)userPreferredPasspointDomains;
- (id)walletIdentifier;
- (id)was6GHzOnlyAt;
- (unsigned long long)was6GHzOnlyAtWeek;
- (id)was6GHzOnlyOnAnyDeviceAt;
- (bool)wasCaptive;
- (bool)wasMoreRecentlyJoinedByUser;
- (bool)wasRecently6GHzOnlyOnAnyDevice;
- (unsigned long long)weakestSupportedSecurityType;

// Image: /System/Library/PrivateFrameworks/NPTKit.framework/NPTKit

- (id)__descriptionForHiddenState;
- (id)__descriptionForLowDataMode;
- (id)dictionary;

// Image: /System/Library/PrivateFrameworks/WiFiKit.framework/WiFiKit

- (bool)autoJoinConfigurable;
- (bool)autoLoginConfigurable;
- (bool)canBeDisplayedAsCurrent;
- (long long)carPlayNetworkType;
- (bool)forgetable;
- (bool)hasJoined6GHz;
- (id)hotspotBatteryLife;
- (id)hotspotCellularProtocol;
- (id)hotspotSignalStrength;
- (bool)iOSHotspot;
- (bool)isAdhoc;
- (bool)isEnterprise;
- (bool)isEquivalentRecord:(id)arg1;
- (bool)isInstantHotspot;
- (bool)isKnown;
- (bool)isManaged;
- (bool)isPopular;
- (bool)isSecure;
- (bool)isUnconfiguredAccessory;
- (id)lastJoinedDate;
- (id)networkQualityDate;
- (double)networkQualityResponsiveness;
- (bool)networkQualityVisible;
- (bool)prominentDisplay;
- (id)randomMACAddress;
- (bool)randomMACAddressConfigurable;
- (long long)rssi;
- (bool)saveDataModeConfigurable;
- (float)scaledRSSI;
- (bool)shouldShowInKnownNetworkList;
- (bool)shouldShowInMyNetworkList;
- (unsigned long long)signalBars;
- (id)ssid;
- (id)subtitle;
- (id)title;
- (unsigned long long)uniqueIdentifier;
- (bool)wifiModeConfigurable;

@end
