
@interface SiriNLUSELFLogUtils : NSObject

+ (id)convertAccepted:(id)arg1;
+ (id)convertAcknowledged:(id)arg1;
+ (int)convertCDMCorrectionType:(int)arg1;
+ (int)convertCDMMatcherName:(int)arg1;
+ (int)convertCDMParserAlgorithmType:(int)arg1;
+ (int)convertCDMReformType:(int)arg1;
+ (int)convertCDMRepetitionType:(int)arg1;
+ (int)convertCDMRewriteType:(int)arg1;
+ (id)convertCancelled:(id)arg1;
+ (int)convertComponentInvocationSource:(int)arg1;
+ (id)convertCorrectionOutcome:(id)arg1;
+ (id)convertDelegated:(id)arg1;
+ (id)convertGaveOptions:(id)arg1;
+ (id)convertInformed:(id)arg1;
+ (id)convertInternalSpanData:(id)arg1;
+ (int)convertLegacyContextSource:(int)arg1;
+ (id)convertLegacyNLContext:(id)arg1;
+ (id)convertLvcResult:(id)arg1;
+ (id)convertMatchInfo:(id)arg1;
+ (int)convertMatchInfoAliasType:(int)arg1;
+ (id)convertMatchingSpan:(id)arg1;
+ (id)convertMatchingSpanTier1:(id)arg1;
+ (id)convertMentionDetectorSpanData:(id)arg1;
+ (id)convertMentionResolverSpanData:(id)arg1;
+ (id)convertNLContext:(id)arg1;
+ (id)convertNonTier1UsoGraph:(id)arg1;
+ (id)convertNonTier1UsoGraph:(id)arg1 identifiers:(id)arg2 entitySpans:(id)arg3;
+ (id)convertOffered:(id)arg1;
+ (id)convertPLUMSpanData:(id)arg1;
+ (id)convertParser:(id)arg1;
+ (id)convertPrompted:(id)arg1;
+ (id)convertReformedTurnInputBundle:(id)arg1;
+ (id)convertRejected:(id)arg1;
+ (id)convertRepetitionResult:(id)arg1;
+ (id)convertReportedFailure:(id)arg1;
+ (id)convertReportedSuccess:(id)arg1;
+ (id)convertSiriVocabularySpanData:(id)arg1;
+ (id)convertSystemDialogAct:(id)arg1;
+ (id)convertTask:(id)arg1;
+ (id)convertToken:(id)arg1;
+ (id)convertTokenChain:(id)arg1;
+ (id)convertTurnContext:(id)arg1;
+ (id)convertTurnInput:(id)arg1;
+ (int)convertUSOEntityIdentifierNluComponent:(int)arg1;
+ (int)convertUSOEntitySpanNluComponent:(int)arg1;
+ (id)convertUUID:(id)arg1;
+ (id)convertUserDialogAct:(id)arg1;
+ (id)convertUserParse:(id)arg1;
+ (id)convertUserStatedTask:(id)arg1;
+ (int)convertUsoBackingAppBundleType:(id)arg1;
+ (id)convertUsoEdge:(id)arg1;
+ (id)convertUsoEntityIdentifier:(id)arg1;
+ (id)convertUsoEntityIdentifier:(id)arg1 index:(long long)arg2;
+ (id)convertUsoEntityIdentifierTier1:(id)arg1 index:(long long)arg2;
+ (id)convertUsoEntitySpan:(id)arg1;
+ (id)convertUsoEntitySpan:(id)arg1 index:(long long)arg2;
+ (id)convertUsoEntitySpanTier1:(id)arg1 index:(long long)arg2;
+ (id)convertUsoGraph:(id)arg1;
+ (id)convertUsoNode:(id)arg1;
+ (id)convertUsoNodeDataTier1:(id)arg1 index:(long long)arg2;
+ (id)convertUtteranceAlignment:(id)arg1;
+ (id)convertUtteranceSpan:(id)arg1;
+ (id)convertVersion:(id)arg1;
+ (id)convertWantedToPause:(id)arg1;
+ (id)convertWantedToProceed:(id)arg1;
+ (id)convertWantedToRepeat:(id)arg1;
+ (id)createAllZeroUUID;
+ (id)createCDMAllServicesSetupEndedLog:(id)arg1;
+ (id)createCDMAllServicesSetupFailedLog:(id)arg1;
+ (id)createCDMAllServicesSetupStartedLog:(id)arg1;
+ (id)createCDMAssetSetupEndedLog:(id)arg1 metadata:(id)arg2;
+ (id)createCDMAssetSetupFailedLog:(id)arg1 errorDomain:(int)arg2 errorCode:(unsigned int)arg3 metadata:(id)arg4;
+ (id)createCDMAssetSetupStartedLog:(id)arg1 serviceTypes:(id)arg2 metadata:(id)arg3;
+ (id)createCDMAssetsReportedLog:(id)arg1 metadata:(id)arg2;
+ (id)createCDMClientSetupEndedLog:(id)arg1;
+ (id)createCDMClientSetupFailedLog:(id)arg1 errorDomain:(int)arg2 errorCode:(unsigned int)arg3;
+ (id)createCDMClientSetupStartedLog:(id)arg1 cdmServiceGraphName:(int)arg2;
+ (id)createCDMRequestEndedLog:(id)arg1 metadata:(id)arg2;
+ (id)createCDMRequestFailedLog:(int)arg1 errorDomainString:(id)arg2 errorCode:(int)arg3 metadata:(id)arg4;
+ (id)createCDMRequestFailedLog:(int)arg1 metadata:(id)arg2;
+ (id)createCDMRequestStartedLog:(id)arg1 metadata:(id)arg2 cdmServiceGraphName:(int)arg3;
+ (id)createCDMSetupMissingAssetsDetectedLog:(id)arg1 services:(id)arg2 metadata:(id)arg3;
+ (id)createCdmXpcEventProcessingEndedLog:(id)arg1 metadata:(id)arg2;
+ (id)createCdmXpcEventProcessingFailedLog:(id)arg1 reason:(int)arg2 errorCode:(unsigned int)arg3 metadata:(id)arg4;
+ (id)createCdmXpcEventProcessingStartedLog:(id)arg1 xpcType:(int)arg2 xpcSystemEventType:(int)arg3 serviceName:(int)arg4 metadata:(id)arg5;
+ (id)createContextUpdateEndedLog:(id)arg1 contextUpdateResponse:(id)arg2 metadata:(id)arg3;
+ (id)createDelegatedUserDialogActTier1Event:(id)arg1 withLinkId:(id)arg2;
+ (id)createMatchingSpanEndedLog:(id)arg1 spanMatchResponse:(id)arg2 metadata:(id)arg3;
+ (id)createMultiHypoTokenizationEndedLog:(id)arg1 tokenizationResponses:(id)arg2 tokenizationInputType:(int)arg3 metadata:(id)arg4;
+ (id)createNLXClientEventMetadataWithNlId:(id)arg1 andWithTrpId:(id)arg2 andWithResultCandidateId:(id)arg3 andWithRequester:(int*)arg4;
+ (id)createNLXCurareContext:(id)arg1 metadata:(id)arg2;
+ (id)createNLXLegacyNLContextTier1Event:(id)arg1 withLinkId:(id)arg2;
+ (id)createNLXRequestLinkWithTarget:(int)arg1 andTargetId:(id)arg2 metadata:(id)arg3;
+ (id)createSystemDialogActTier1Event:(id)arg1 withLinkId:(id)arg2;
+ (id)createTokenizationEndedLog:(id)arg1 tokenizationResponse:(id)arg2 metadata:(id)arg3;
+ (id)createTokenizationEndedLog:(id)arg1 tokenizationResponse:(id)arg2 tokenizationInputType:(int)arg3 metadata:(id)arg4;
+ (id)extractRequestLinkData:(id)arg1;
+ (int)getErrorDomain:(id)arg1;
+ (id)getErrorDomainMapping;
+ (id)getObjCUsoGraphFromOntologyUsoGraph:(struct unique_ptr<siri::ontology::UsoGraph, std::default_delete<siri::ontology::UsoGraph>> { struct __compressed_pair<siri::ontology::UsoGraph *, std::default_delete<siri::ontology::UsoGraph>> { struct UsoGraph {} *x_1_1_1; } x1; })arg1;
+ (id)getReferenceFromAccepted:(id)arg1;
+ (id)getReferenceFromAcknowledged:(id)arg1;
+ (id)getReferenceFromCancelled:(id)arg1;
+ (id)getReferenceFromRejected:(id)arg1;
+ (id)getReferenceFromWantedToPause:(id)arg1;
+ (id)getReferenceFromWantedToProceed:(id)arg1;
+ (id)getReferenceFromWantedToRepeat:(id)arg1;
+ (id)getTaskFromUserStatedTask:(id)arg1;
+ (bool)isLegacyNlContextPresent:(id)arg1;
+ (bool)isNlContextPresent:(id)arg1;
+ (void)populateEventsWithMetadata:(id)arg1 metadata:(id)arg2;

@end
