
@interface AKAuthorizationPaneViewController : UIViewController <UITableViewDataSource, UITableViewDelegate> {
    UIVisualEffectView * _blurryTray;
    <AKAuthorizationEditableDataSources> * _editableDataSources;
    AKAuthorizationPaneContext * _footerPaneContext;
    NSLayoutConstraint * _footerWidthConstraint;
    AKAuthorizationPaneContext * _headerPaneContext;
    NSLayoutConstraint * _headerWidthConstraint;
    bool  _isWristDetectionEnabled;
    NSMutableArray * _mutableConstraints;
    <AKAuthorizationPaneDelegate> * _paneDelegate;
    UIStackView * _paneFooterStackView;
    UIStackView * _paneHeaderStackView;
    UITableView * _tableView;
}

@property (nonatomic, retain) UIVisualEffectView *blurryTray;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) <AKAuthorizationEditableDataSources> *editableDataSources;
@property (nonatomic, retain) AKAuthorizationPaneContext *footerPaneContext;
@property (nonatomic, readonly) NSLayoutConstraint *footerWidthConstraint;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) AKAuthorizationPaneContext *headerPaneContext;
@property (nonatomic, readonly) NSLayoutConstraint *headerWidthConstraint;
@property (nonatomic, readonly) bool isWristDetectionEnabled;
@property (nonatomic, retain) NSMutableArray *mutableConstraints;
@property (nonatomic) <AKAuthorizationPaneDelegate> *paneDelegate;
@property (nonatomic, readonly) UIStackView *paneFooterStackView;
@property (nonatomic, readonly) UIStackView *paneHeaderStackView;
@property (readonly) Class superclass;
@property (nonatomic, retain) UITableView *tableView;

- (void).cxx_destruct;
- (void)_adjustForPositionOfScrollView:(id)arg1;
- (void)_configureContentTrayIfNeeded;
- (double)_contentTrayOffsetAdjustedForScrollInset:(bool)arg1;
- (double)_deviceSafeAreaBottomInset;
- (id)_indexPathForLastRow;
- (bool)_isContentUnderNavigationBar;
- (bool)_isContentUnderTray;
- (double)_navigationBarHeaderHeight;
- (id)_newContainerView;
- (id)_newStackView;
- (long long)_safeIndexWithCount:(long long)arg1;
- (void)_setCompressedHeightForView:(id)arg1;
- (void)_setupContexts;
- (bool)_shouldEmbedContentTray;
- (void)_updateBlurForTray;
- (id)blurryTray;
- (double)contentScrollOffset;
- (id)editableDataSources;
- (id)footerPaneContext;
- (id)footerWidthConstraint;
- (id)headerPaneContext;
- (id)headerWidthConstraint;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (double)intrinsicContentHeight;
- (bool)isWristDetectionEnabled;
- (double)maximumContentHeight;
- (double)maximumContentWidth;
- (id)mutableConstraints;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)paneDelegate;
- (id)paneFooterStackView;
- (id)paneHeaderStackView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setBlurryTray:(id)arg1;
- (void)setEditableDataSources:(id)arg1;
- (void)setFooterPaneContext:(id)arg1;
- (void)setHeaderPaneContext:(id)arg1;
- (void)setMutableConstraints:(id)arg1;
- (void)setPaneDelegate:(id)arg1;
- (void)setTableView:(id)arg1;
- (bool)shouldEmbedContentTrayIfNeeded;
- (void)sizeToFitPaneContent;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillLayoutSubviews;

@end
