
@interface AssistantController : PSListController <AssistantHistoryDelegate, AssistantVoiceActivationDelegate, AssistantVoiceSettingsConnectionProvider, CNContactPickerDelegate, DevicePINControllerDelegate, UAFAssetUtilitiesDelegate, VTUIEnrollTrainingViewControllerDelegate, VTUISiriDataSharingOptInPresentationDelegate, VTUIVoiceSelectionViewControllerDelegate> {
    AFSettingsConnection * _AFSettingsConnection;
    NSArray * _allAppsSpecifiers;
    PSSpecifier * _announceMessagesSpecifier;
    unsigned long long  _assetState;
    UAFAssetUtilities * _assetUtils;
    NSArray * _assistantSettings;
    CNContactStore * _contactStore;
    PSSpecifier * _currentSiriActivationSpecifier;
    NSMutableSet * _disabledSpotlightBundles;
    NSMutableSet * _disabledSpotlightDomains;
    AFEnablementConfiguration * _enablementConfiguration;
    AFEnablementFlowConfigurationProvider * _enablementConfigurationProvider;
    PSRootController * _enablementFlowNavigationController;
    VTUIEnrollTrainingViewController * _enrollmentController;
    PSSpecifier * _hardwareButtonActivationSpecifier;
    NSSet * _installedBundleIDs;
    NSArray * _languagesInHome;
    double  _lastDownloadTimestamp;
    PSSpecifier * _lockScreenSpecifier;
    bool  _needsReloadSpecifiersOnViewWillAppear;
    NSString * _pendingLanguage;
    CNContactPickerViewController * _peoplePicker;
    SUICAssistantVoiceSettingsConnection * _settingsConnection;
    UIViewController * _siriDataSharingOptInViewController;
    VTUISiriDataSharingOptInPresenter * _siriDataSharingPresenter;
    PSSpecifier * _siriInCallSpecifier;
    ASTLockScreenSuggestionsGlobalController * _suggestionsFromAppleAllowNotificationsController;
    bool  _thisIsMeDevice;
    NSObject<OS_dispatch_queue> * _utilityQueue;
    PSSpecifier * _voiceActivationSettingsSpecifier;
    PSSpecifier * _voiceActivationSpecifier;
    id /* block */  _voiceSelectionCompletion;
    id /* block */  _voiceSelectionFlowDismissalHandler;
    PSSpecifier * _voiceSpecifier;
    id /* block */  _voiceTriggerEnablementCompletion;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) SUICAssistantVoiceSettingsConnection *settingsConnection;
@property (readonly) Class superclass;

+ (bool)_heySiriSupportedForLanguage:(id)arg1;
+ (id)bundle;
+ (void)presentAssistantEnableAlertForState:(bool)arg1 presentingViewController:(id)arg2 actionHandler:(id /* block */)arg3;
+ (id)shortTitlesForLanguageIdentifiers:(id)arg1;

- (void).cxx_destruct;
- (void)_addHyperlinkStyleToText:(id)arg1 inString:(id)arg2 action:(SEL)arg3 forGroup:(id)arg4;
- (void)_askSiriUseDefaultFooterTextWithGroupSpecifier:(id)arg1;
- (void)_askSiriUseDownloadFinishedFooterTextWithGroupSpecifier:(id)arg1;
- (void)_askSiriUseDownloadReadyFooterTextWithGroupSpecifier:(id)arg1;
- (void)_askSiriUseDownloadingFooterTextWithGroupSpecifier:(id)arg1 withProgress:(unsigned long long)arg2;
- (void)_askSiriUseOutOfSpaceFooterTextWithGroupSpecifier:(id)arg1 withSpaceRequiredText:(id)arg2;
- (id)_confirmationPromptDisableHeySiri:(bool)arg1 disableMultiUser:(bool)arg2 disableSpokenFeedback:(bool)arg3;
- (id)_createEnablementFlowControllerForConfiguration:(id)arg1 recognitionLanguageCode:(id)arg2;
- (id /* block */)_createVoiceSelectionCompletionForSpecifier:(id)arg1 recognitionLanguageCode:(id)arg2;
- (id /* block */)_createVoiceSelectionDismissalHandlerWithSpecifier:(id)arg1 actionHandler:(id /* block */)arg2;
- (bool)_downloadSiriAssets;
- (void)_handleEnablementConfirmationForSpecifier:(id)arg1 actionHandler:(id /* block */)arg2;
- (void)_handleThemisEnablementConfirmationForSpecifier:(id)arg1 presentingViewController:(id)arg2 actionHandler:(id /* block */)arg3;
- (void)_insertSiriInCallSpecifier;
- (bool)_isAssistantLockScreenAccessRestricted;
- (bool)_isCurrentSpecifierVoiceActivation;
- (bool)_isHeySiriAlwaysOn;
- (bool)_isIncompatibleWithWatchLanguage:(id)arg1;
- (bool)_isVoiceTriggerEnabled;
- (bool)_languageWillDisableHeySiri:(id)arg1;
- (id)_localizeTriggerString:(id)arg1;
- (id)_localizedStringWithFormattedIDTemplate:(id)arg1;
- (void)_makeMeDeviceDetermination;
- (bool)_pairedWithSiriSpeaksEnabledNanoHardware;
- (void)_presentSiriDataSharingOptInViewController;
- (void)_refreshAvailableLanguagesInTheHome;
- (void)_reloadSiriInCallSpecifier;
- (void)_removeSiriInCallSpecifier;
- (void)_runEnablementFlowDismissalHandlersIfApplicable;
- (void)_runVoiceTriggerEnablementCompletionIfApplicable;
- (void)_setAccessibleFromLockScreen:(bool)arg1;
- (void)_setAssistantEnabled:(id)arg1 forSpecifier:(id)arg2 presentingViewController:(id)arg3 actionHandler:(id /* block */)arg4;
- (void)_setAssistantLanguageCancelled:(id)arg1;
- (void)_setAssistantLanguageConfirmed:(id)arg1;
- (void)_setAssistantLanguageHeySiriDisableConfirmed:(id)arg1;
- (void)_setAssistantLanguageWatchMismatchConfirmed:(id)arg1;
- (void)_showIncompatibleWatchLanguageAlert;
- (void)_showWillDisableAlertWillDisableHeySiri:(bool)arg1 disableMultiUser:(bool)arg2 disableSpokenFeedbackOnWatch:(bool)arg3;
- (void)_updateSiriFooterGroup:(id)arg1 forceReload:(bool)arg2;
- (void)_updateSpecifiersForLanguage:(id)arg1;
- (void)_voiceSelectionCancelled;
- (id)accessibleFromLockScreen:(id)arg1;
- (void)assistantAboutDonePressed:(id)arg1;
- (void)assistantDisabledCancelled:(id)arg1;
- (void)assistantDisabledConfirmed:(id)arg1;
- (id)assistantEnabled:(id)arg1;
- (void)assistantEnabledCancelled:(id)arg1;
- (void)assistantEnabledConfirmed:(id)arg1;
- (void)assistantEnabledDidChange:(bool)arg1;
- (id)assistantLanguage:(id)arg1;
- (void)assistantLanguageDidChange:(id)arg1;
- (id)assistantVoice:(id)arg1;
- (id)assistantVoiceLanguage:(id)arg1;
- (id)bundle;
- (void)cancelSetup:(id)arg1;
- (void)configureApplicationListSpecifiersFor:(id)arg1;
- (void)configureAskSiriSpecifiersFor:(id)arg1;
- (void)configureContentFromAppleSpecifiersFor:(id)arg1;
- (void)configureSearchSuggestionsFromAppleSpecifiersFor:(id)arg1;
- (void)configureSuggestionsFromAppleSpecifiersFor:(id)arg1;
- (void)confirmDisableForMultiUserVoiceIdentificationWithSpecifier:(id)arg1 pairedWatch:(bool)arg2 presentingViewController:(id)arg3 actionHandler:(id /* block */)arg4;
- (void)confirmDisableWithSpecifier:(id)arg1 pairedWatch:(bool)arg2 presentingViewController:(id)arg3 actionHandler:(id /* block */)arg4;
- (void)confirmResetHiddenSuggestions:(id)arg1;
- (id)confirmationSpecifierWillDisableHeySiri:(bool)arg1 disableMultiUser:(bool)arg2 disableSpokenFeedbackOnWatch:(bool)arg3;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (void)contactsDidChange;
- (void)continueSetup;
- (void)dealloc;
- (void)deleteHistorySuccessfulFromViewController:(id)arg1;
- (void)didAcceptEnteredPIN;
- (void)didBecomeActive;
- (void)didCancelEnteringPIN;
- (void)downloadSiriAssets;
- (void)handleAssetStatusUpdated;
- (void)handleURL:(id)arg1 withCompletion:(id /* block */)arg2;
- (id)hardwareButtonTrigger:(id)arg1;
- (id)init;
- (bool)isFlexibleFollowupsSupported;
- (id)isShowInAppLibraryEnabled:(id)arg1;
- (id)isShowInLookUpEnabled;
- (id)isShowInSpotlightEnabled;
- (id)isShowWhenListeningEnabled:(id)arg1;
- (id)isShowWhenSharingEnabled:(id)arg1;
- (id)isShowZKWRecentsEnabled:(id)arg1;
- (id)isShowZKWSuggestionsEnabled:(id)arg1;
- (void)languageCodeDidChange;
- (void)loadAppStorePageForBundleId:(id)arg1;
- (void)lowPowerModeChangedNotification:(id)arg1;
- (id)meCard:(id)arg1;
- (void)networkPathChangeSatisfied:(bool)arg1 isExpensive:(bool)arg2;
- (void)openStorageManagement:(id)arg1;
- (void)outputVoiceDidChange;
- (void)preferencesDidChange;
- (void)prepareForSnapshot;
- (void)presentationControllerDidDismiss:(id)arg1;
- (void)reloadSpecifiers;
- (void)resetZKWHiddenSuggestions:(id)arg1;
- (void)retryDownloadSiriAssetsWithDelay:(double)arg1;
- (void)saveSpotlightSettings;
- (void)setAccessibleFromLockScreen:(id)arg1 forSpecifier:(id)arg2;
- (void)setAssistantEnabled:(bool)arg1;
- (void)setAssistantLanguage:(id)arg1;
- (void)setAssistantLanguage:(id)arg1 forSpecifier:(id)arg2;
- (void)setDisabledFromLockScreen:(bool)arg1;
- (void)setHardwareButtonTrigger:(id)arg1 forSpecifier:(id)arg2;
- (void)setShowInAppLibraryEnabled:(id)arg1 forSpecifier:(id)arg2;
- (void)setShowInLookUpEnabled:(id)arg1;
- (void)setShowInSpotlightEnabled:(id)arg1;
- (void)setShowWhenListeningEnabled:(id)arg1 forSpecifier:(id)arg2;
- (void)setShowWhenSharingEnabled:(id)arg1 forSpecifier:(id)arg2;
- (void)setShowZKWRecentsEnabled:(id)arg1 forSpecifier:(id)arg2;
- (void)setShowZKWSuggestionsEnabled:(id)arg1 forSpecifier:(id)arg2;
- (void)setVoiceActivation:(id)arg1 forSpecifier:(id)arg2 withTrainingCompletionIfNecessary:(id /* block */)arg3;
- (void)setVoiceTrigger:(id)arg1 forSpecifier:(id)arg2;
- (void)setVoiceTrigger:(id)arg1 forSpecifier:(id)arg2 transitionWithNavControllerIfNecessary:(id)arg3;
- (id)settingsConnection;
- (void)showAboutAssistantSheet:(id)arg1;
- (void)showAboutImproveDictationSheet:(id)arg1;
- (void)showAboutSearchSuggestionsSheet:(id)arg1;
- (void)showAssistantConfirmationViewForSpecifier:(id)arg1 presentingViewController:(id)arg2 actionHandler:(id /* block */)arg3;
- (void)showAssistantHistoryViewController:(id)arg1;
- (void)showAssistantVoiceActivationController:(id)arg1;
- (void)showLearnMore;
- (void)showMeCardPicker:(id)arg1;
- (void)siriDataSharingOptInRequestsDismissalFromPresenter:(id)arg1;
- (id)siriInCallEnabled:(id)arg1;
- (void)siriUODAvailabilityDidChange:(bool)arg1;
- (void)skipSetup;
- (id)specifiers;
- (void)startVoiceTriggerTraining:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (id)voiceActivationSelection:(id)arg1;
- (void)voiceSelectionController:(id)arg1 didSelectVoice:(id)arg2;
- (id)voiceTrigger:(id)arg1;
- (bool)watchSupportsSiriLanguageCode:(id)arg1;

@end
