
@interface PKTextInputDebugViewController : UIViewController <PKTextInputDebugStateIntrospectorDelegate, PKTextInputDebugViewTableCellDelegate, UITableViewDataSource, UITableViewDelegate> {
    NSTimer * __autoreloadTimer;
    bool  __needsReloadData;
    bool  __needsReloadTargetsVisualization;
    UIView * __statusContainerView;
    UITableView * __statusTableView;
    NSArray * __statusViewPositionConstraints;
    UIToolbar * __statusViewToolbar;
    PKTextInputDebugTargetsView * __targetsContainerView;
    bool  __visualizeTargets;
    PKTextInputDebugLogController * _debugLogController;
    <PKTextInputDebugViewControllerDelegate> * _delegate;
    PKTextInputElementsController * _elementsController;
    PKTextInputDebugStateIntrospector * _introspectorDataSource;
    unsigned long long  _statusViewAnchorCorner;
}

@property (nonatomic, retain) NSTimer *_autoreloadTimer;
@property (nonatomic) bool _needsReloadData;
@property (nonatomic) bool _needsReloadTargetsVisualization;
@property (nonatomic, retain) UIView *_statusContainerView;
@property (nonatomic, retain) UITableView *_statusTableView;
@property (nonatomic, retain) NSArray *_statusViewPositionConstraints;
@property (nonatomic, retain) UIToolbar *_statusViewToolbar;
@property (nonatomic, retain) PKTextInputDebugTargetsView *_targetsContainerView;
@property (setter=_setVisualizeTargets:, nonatomic) bool _visualizeTargets;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, retain) PKTextInputDebugLogController *debugLogController;
@property (nonatomic) <PKTextInputDebugViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) PKTextInputElementsController *elementsController;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) PKTextInputDebugStateIntrospector *introspectorDataSource;
@property (nonatomic) unsigned long long statusViewAnchorCorner;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_autoreloadTimer;
- (bool)_canShowWhileLocked;
- (void)_configureCell:(id)arg1 forItemAtIndex:(long long)arg2;
- (void)_handleAutoreloadTimerFired;
- (void)_handleCloseButton:(id)arg1;
- (void)_handleLogButton:(id)arg1;
- (void)_handleRadarButton:(id)arg1;
- (void)_handleTargetsButton:(id)arg1;
- (bool)_needsReloadData;
- (bool)_needsReloadTargetsVisualization;
- (void)_reloadDebugStateData;
- (void)_reloadTargetsVisualization;
- (void)_setVisualizeTargets:(bool)arg1;
- (void)_setupStatusView;
- (id)_statusContainerView;
- (id)_statusTableView;
- (id)_statusViewPositionConstraints;
- (id)_statusViewToolbar;
- (id)_targetsContainerView;
- (void)_updateStatusView;
- (void)_updateTargetsVisualizationView;
- (bool)_visualizeTargets;
- (id)debugLogController;
- (void)debugStateIntrospectorContentDidChange:(id)arg1;
- (void)debugViewTableCellDidTapDetailsButton:(id)arg1;
- (id)delegate;
- (id)elementsController;
- (id)introspectorDataSource;
- (void)loadView;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setDebugLogController:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setElementsController:(id)arg1;
- (void)setIntrospectorDataSource:(id)arg1;
- (void)setNeedsReloadDebugStateData;
- (void)setNeedsReloadTargetsVisualization;
- (void)setStatusViewAnchorCorner:(unsigned long long)arg1;
- (void)set_autoreloadTimer:(id)arg1;
- (void)set_needsReloadData:(bool)arg1;
- (void)set_needsReloadTargetsVisualization:(bool)arg1;
- (void)set_statusContainerView:(id)arg1;
- (void)set_statusTableView:(id)arg1;
- (void)set_statusViewPositionConstraints:(id)arg1;
- (void)set_statusViewToolbar:(id)arg1;
- (void)set_targetsContainerView:(id)arg1;
- (unsigned long long)statusViewAnchorCorner;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;

@end
