
@interface PKToolConfiguration : NSObject <NSCopying> {
    UIImage * _bandContourImage;
    UIImage * _bandMaskImage;
    double  _bandVerticalOffset;
    UIImage * _baseImage;
    PKFloatRange * _cachedStrokeWeightRange;
    UIColor * _defaultColor;
    long long  _inkVersion;
    bool  _isEraserTool;
    NSString * _localizedName;
    double  _maximumBandThickness;
    double  _minimumBandThickness;
    double  _opacityLabelVerticalOffset;
    UIBezierPath * _shadowPath;
    UIBezierPath * _shadowPathIncludingTip;
    NSDictionary * _strokeWeightsToButtonImages;
    bool  _supportsColor;
    bool  _supportsOpacity;
    UIImage * _tipContourImage;
    UIImage * _tipMaskImage;
    id /* block */  _viewControllerProvider;
    UIColor * _weightButtonTintColorOverride;
}

@property (nonatomic, copy) UIImage *bandContourImage;
@property (nonatomic, copy) UIImage *bandMaskImage;
@property (nonatomic) double bandVerticalOffset;
@property (nonatomic, copy) UIImage *baseImage;
@property (nonatomic, readonly) UIColor *defaultColor;
@property (nonatomic, copy) UIImage *image;
@property (nonatomic, readonly) long long inkVersion;
@property (nonatomic, readonly) bool isEraserTool;
@property (nonatomic, copy) NSString *localizedName;
@property (nonatomic, readonly) double maximumBandThickness;
@property (nonatomic, readonly) double minimumBandThickness;
@property (nonatomic) double opacityLabelVerticalOffset;
@property (nonatomic, copy) UIBezierPath *shadowPath;
@property (nonatomic, readonly) UIBezierPath *shadowPathIncludingTip;
@property (nonatomic, readonly) bool shouldShowOpacityInColorPicker;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } strokeWeightButtonSize;
@property (nonatomic, copy) NSDictionary *strokeWeightsToButtonImages;
@property (nonatomic, readonly) bool supportsColor;
@property (nonatomic, readonly) bool supportsOpacity;
@property (nonatomic, readonly) bool supportsStrokeWeight;
@property (nonatomic, copy) UIImage *tipContourImage;
@property (nonatomic, readonly) UIImage *tipMaskImage;
@property (nonatomic, copy) id /* block */ viewControllerProvider;
@property (nonatomic, readonly) UIColor *weightButtonTintColorOverride;

+ (id)_configurationForFountainPen;
+ (id)_configurationForMonoline;
+ (id)_configurationForWatercolor;
+ (id)_deepCopyStrokeWeightDictionary:(id)arg1;
+ (id)defaultColorForInkingToolWithIdentifier:(id)arg1;
+ (id)defaultConfigurationForToolWithIdentifier:(id)arg1;
+ (id)defaultConfigurationForToolWithIdentifier:(id)arg1 inkVersion:(long long)arg2;
+ (id)p_assetImageForToolIdentifier:(id)arg1 assetNumber:(unsigned long long)arg2 bundle:(id)arg3;
+ (id)p_bitmapEraserImageWithWeight:(double)arg1 imageSize:(struct CGSize { double x1; double x2; })arg2;
+ (id)p_objectEraserImageWithWeight:(double)arg1 imageSize:(struct CGSize { double x1; double x2; })arg2;

- (void).cxx_destruct;
- (id)bandContourImage;
- (id)bandMaskImage;
- (double)bandThicknessForStrokeWeight:(double)arg1;
- (double)bandVerticalOffset;
- (id)baseImage;
- (void)clearTipMaskImageAndShadowPathIncludingTip;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)defaultColor;
- (unsigned long long)hash;
- (id)image;
- (id)init;
- (id)initWithLocalizedName:(id)arg1 baseImage:(id)arg2 shadowPath:(id)arg3;
- (long long)inkVersion;
- (bool)isEqual:(id)arg1;
- (bool)isEraserTool;
- (id)localizedName;
- (double)maximumBandThickness;
- (double)minimumBandThickness;
- (double)opacityLabelVerticalOffset;
- (id)p_strokeWeightRange;
- (void)setBandContourImage:(id)arg1;
- (void)setBandMaskImage:(id)arg1;
- (void)setBandVerticalOffset:(double)arg1;
- (void)setBaseImage:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setLocalizedName:(id)arg1;
- (void)setMinimumBandThickness:(double)arg1 andMaximumBandThickness:(double)arg2;
- (void)setOpacityLabelVerticalOffset:(double)arg1;
- (void)setShadowPath:(id)arg1;
- (void)setStrokeWeightsToButtonImages:(id)arg1;
- (void)setSupportsColor:(bool)arg1 andOpacity:(bool)arg2;
- (void)setSupportsColor:(bool)arg1 andOpacity:(bool)arg2 defaultColor:(id)arg3;
- (void)setTipContourImage:(id)arg1;
- (void)setTipMaskImage:(id)arg1 withShadowPathIncludingTip:(id)arg2;
- (void)setViewControllerProvider:(id /* block */)arg1;
- (id)shadowPath;
- (id)shadowPathIncludingTip;
- (bool)shouldShowOpacityInColorPicker;
- (struct CGSize { double x1; double x2; })strokeWeightButtonSize;
- (id)strokeWeightsToButtonImages;
- (bool)supportsColor;
- (bool)supportsOpacity;
- (bool)supportsStrokeWeight;
- (id)tipContourImage;
- (id)tipMaskImage;
- (id /* block */)viewControllerProvider;
- (id)weightButtonTintColorOverride;

@end
