
@interface NTPBFeedItem : PBCodable <FCClassifiable, FCFeedTransformationItem, NSCopying> {
    NSString * _articleID;
    long long  _bodyTextLength;
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats * _channelConversionStats;
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLTagMetadata * _channelTagMetadata;
    NSString * _clusterID;
    unsigned long long  _contentType;
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLArticleContentExpiration * _expirationData;
    unsigned long long  _feedHalfLifeMilliseconds;
    NSString * _feedID;
    NSData * _float16FullBodyEncoding;
    NSData * _float16TitleEncoding;
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList * _globalCohorts;
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats * _globalConversionStats;
    double  _globalUserFeedback;
    struct { 
        unsigned int bodyTextLength : 1; 
        unsigned int contentType : 1; 
        unsigned int feedHalfLifeMilliseconds : 1; 
        unsigned int globalUserFeedback : 1; 
        unsigned int minimumNewsVersion : 1; 
        unsigned int order : 1; 
        unsigned int publishDateMilliseconds : 1; 
        unsigned int publisherArticleVersion : 1; 
        unsigned int hasAudioTrack : 1; 
        unsigned int hasThumbnail : 1; 
        unsigned int hasVideo : 1; 
        unsigned int hasVideoStillImage : 1; 
        unsigned int isBundlePaid : 1; 
        unsigned int isEvergreen : 1; 
        unsigned int isExplicitContent : 1; 
        unsigned int isFeatureCandidate : 1; 
        unsigned int isFeatured : 1; 
        unsigned int isFromBlockedStorefront : 1; 
        unsigned int isHiddenFromAutoFavorites : 1; 
        unsigned int isIssueOnly : 1; 
        unsigned int isPaid : 1; 
        unsigned int isSponsored : 1; 
        unsigned int reduceVisibility : 1; 
        unsigned int webConverted : 1; 
    }  _has;
    bool  _hasAudioTrack;
    bool  _hasThumbnail;
    bool  _hasVideo;
    bool  _hasVideoStillImage;
    bool  _isBundlePaid;
    bool  _isEvergreen;
    bool  _isExplicitContent;
    bool  _isFeatureCandidate;
    bool  _isFeatured;
    bool  _isFromBlockedStorefront;
    bool  _isHiddenFromAutoFavorites;
    bool  _isIssueOnly;
    bool  _isPaid;
    bool  _isSponsored;
    NSString * _language;
    long long  _minimumNewsVersion;
    unsigned long long  _order;
    NSString * _parentIssueID;
    unsigned long long  _publishDateMilliseconds;
    long long  _publisherArticleVersion;
    bool  _reduceVisibility;
    NTPBScoreProfiles * _scoreProfiles;
    NSString * _sourceArticleListID;
    COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList * _sourceChannelCohorts;
    NSString * _sourceChannelID;
    NSData * _thumbnailPerceptualHash;
    NSMutableArray * _topicIDs;
    NSMutableArray * _topics;
    bool  _webConverted;
}

@property (getter=isANF, nonatomic, readonly) bool anf;
@property (nonatomic, readonly, copy) NSString *articleID;
@property (nonatomic, retain) NSString *articleID;
@property (nonatomic, readonly) long long bodyTextLength;
@property (nonatomic) long long bodyTextLength;
@property (getter=isBundlePaid, nonatomic, readonly) bool bundlePaid;
@property (nonatomic, readonly) bool canBePurchased;
@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats *channelConversionStats;
@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLTagMetadata *channelTagMetadata;
@property (nonatomic, readonly, copy) NSString *clusterID;
@property (nonatomic, retain) NSString *clusterID;
@property (nonatomic, readonly) unsigned long long contentType;
@property (nonatomic) unsigned long long contentType;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLArticleContentExpiration *expirationData;
@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLArticleContentExpiration *expirationData;
@property (getter=isExplicitContent, nonatomic, readonly) bool explicitContent;
@property (nonatomic, readonly) unsigned long long feedHalfLifeMilliseconds;
@property (nonatomic) unsigned long long feedHalfLifeMilliseconds;
@property (nonatomic, readonly, copy) NSString *feedID;
@property (nonatomic, retain) NSString *feedID;
@property (nonatomic, readonly) NSData *float16FullBodyEncoding;
@property (nonatomic, retain) NSData *float16FullBodyEncoding;
@property (nonatomic, readonly) NSData *float16TitleEncoding;
@property (nonatomic, retain) NSData *float16TitleEncoding;
@property (getter=isFromBlockedStorefront, nonatomic, readonly) bool fromBlockedStorefront;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList *globalCohorts;
@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList *globalCohorts;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats *globalConversionStats;
@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats *globalConversionStats;
@property (nonatomic, readonly) double globalUserFeedback;
@property (nonatomic) double globalUserFeedback;
@property (nonatomic, readonly) unsigned long long halfLife;
@property (nonatomic, readonly) unsigned long long halfLifeOverride;
@property (nonatomic, readonly) bool hasArticleID;
@property (nonatomic, readonly) bool hasAudioTrack;
@property (nonatomic) bool hasAudioTrack;
@property (nonatomic) bool hasBodyTextLength;
@property (nonatomic, readonly) bool hasChannelConversionStats;
@property (nonatomic, readonly) bool hasChannelTagMetadata;
@property (nonatomic, readonly) bool hasClusterID;
@property (nonatomic) bool hasContentType;
@property (nonatomic, readonly) bool hasExpirationData;
@property (nonatomic) bool hasFeedHalfLifeMilliseconds;
@property (nonatomic, readonly) bool hasFeedID;
@property (nonatomic, readonly) bool hasFloat16FullBodyEncoding;
@property (nonatomic, readonly) bool hasFloat16TitleEncoding;
@property (nonatomic, readonly) bool hasGlobalCohorts;
@property (nonatomic, readonly) bool hasGlobalConversionStats;
@property (nonatomic, readonly) bool hasGlobalUserFeedback;
@property (nonatomic) bool hasGlobalUserFeedback;
@property (nonatomic) bool hasHasAudioTrack;
@property (nonatomic) bool hasHasThumbnail;
@property (nonatomic) bool hasHasVideo;
@property (nonatomic) bool hasHasVideoStillImage;
@property (nonatomic) bool hasIsBundlePaid;
@property (nonatomic) bool hasIsEvergreen;
@property (nonatomic) bool hasIsExplicitContent;
@property (nonatomic) bool hasIsFeatureCandidate;
@property (nonatomic) bool hasIsFeatured;
@property (nonatomic) bool hasIsFromBlockedStorefront;
@property (nonatomic) bool hasIsHiddenFromAutoFavorites;
@property (nonatomic) bool hasIsIssueOnly;
@property (nonatomic) bool hasIsPaid;
@property (nonatomic) bool hasIsSponsored;
@property (nonatomic, readonly) bool hasLanguage;
@property (nonatomic) bool hasMinimumNewsVersion;
@property (nonatomic) bool hasOrder;
@property (nonatomic, readonly) bool hasParentIssueID;
@property (nonatomic) bool hasPublishDateMilliseconds;
@property (nonatomic) bool hasPublisherArticleVersion;
@property (nonatomic) bool hasReduceVisibility;
@property (nonatomic, readonly) bool hasScoreProfiles;
@property (nonatomic, readonly) bool hasSourceArticleListID;
@property (nonatomic, readonly) bool hasSourceChannelCohorts;
@property (nonatomic, readonly) bool hasSourceChannelID;
@property (nonatomic, readonly) bool hasThumbnail;
@property (nonatomic) bool hasThumbnail;
@property (nonatomic, readonly) bool hasThumbnailPerceptualHash;
@property (nonatomic, readonly) bool hasVideo;
@property (nonatomic) bool hasVideo;
@property (nonatomic, readonly) bool hasVideoStillImage;
@property (nonatomic) bool hasVideoStillImage;
@property (nonatomic) bool hasWebConverted;
@property (readonly) unsigned long long hash;
@property (getter=isHiddenFromAutoFavorites, nonatomic, readonly) bool hiddenFromAutoFavorites;
@property (nonatomic, readonly, copy) NSArray *iAdCategories;
@property (nonatomic, readonly) NSString *identifier;
@property (nonatomic) bool isBundlePaid;
@property (nonatomic, readonly) bool isEvergreen;
@property (nonatomic) bool isEvergreen;
@property (nonatomic) bool isExplicitContent;
@property (nonatomic, readonly) bool isFeatureCandidate;
@property (nonatomic) bool isFeatureCandidate;
@property (nonatomic, readonly) bool isFeatured;
@property (nonatomic) bool isFeatured;
@property (nonatomic) bool isFromBlockedStorefront;
@property (nonatomic) bool isHiddenFromAutoFavorites;
@property (nonatomic) bool isIssueOnly;
@property (nonatomic) bool isPaid;
@property (nonatomic) bool isSponsored;
@property (nonatomic, readonly, copy) NSString *itemID;
@property (nonatomic, readonly, copy) NSString *language;
@property (nonatomic, retain) NSString *language;
@property (nonatomic, readonly) long long minimumNewsVersion;
@property (nonatomic) long long minimumNewsVersion;
@property (nonatomic, readonly) unsigned long long order;
@property (nonatomic) unsigned long long order;
@property (getter=isPaid, nonatomic, readonly) bool paid;
@property (nonatomic, retain) NSString *parentIssueID;
@property (nonatomic, readonly, copy) NSDate *publishDate;
@property (nonatomic, readonly) unsigned long long publishDateMilliseconds;
@property (nonatomic) unsigned long long publishDateMilliseconds;
@property (nonatomic, readonly) long long publisherArticleVersion;
@property (nonatomic) long long publisherArticleVersion;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList *publisherCohorts;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLConversionStats *publisherConversionStats;
@property (nonatomic, readonly, copy) NSString *publisherID;
@property (nonatomic, readonly) COMAPPLEFELDSPARPROTOCOLLIVERPOOLTagMetadata *publisherTagMetadata;
@property (nonatomic, readonly) bool reduceVisibility;
@property (nonatomic) bool reduceVisibility;
@property (nonatomic, readonly) unsigned long long role;
@property (retain) FCFeedPersonalizedItemScoreProfile *scoreProfile;
@property (nonatomic, retain) NTPBScoreProfiles *scoreProfiles;
@property (nonatomic, retain) NSString *sourceArticleListID;
@property (nonatomic, readonly, copy) <FCChannelProviding> *sourceChannel;
@property (nonatomic, retain) COMAPPLEFELDSPARPROTOCOLLIVERPOOLCohortList *sourceChannelCohorts;
@property (nonatomic, readonly, copy) NSString *sourceChannelID;
@property (nonatomic, retain) NSString *sourceChannelID;
@property (nonatomic, readonly, copy) NSString *sourceFeedID;
@property (getter=isSponsored, nonatomic, readonly) bool sponsored;
@property (nonatomic, readonly) unsigned long long storyType;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSData *thumbnailPerceptualHash;
@property (nonatomic, retain) NSData *thumbnailPerceptualHash;
@property (nonatomic, readonly, copy) NSArray *topicIDs;
@property (nonatomic, retain) NSMutableArray *topicIDs;
@property (nonatomic, readonly, copy) NSArray *topics;
@property (nonatomic, retain) NSMutableArray *topics;
@property (nonatomic, readonly) bool webConverted;
@property (nonatomic) bool webConverted;

// Image: /System/Library/PrivateFrameworks/NewsTransport.framework/NewsTransport

+ (Class)topicIDsType;
+ (Class)topicsType;

- (void)addTopicIDs:(id)arg1;
- (void)addTopics:(id)arg1;
- (id)articleID;
- (long long)bodyTextLength;
- (id)channelConversionStats;
- (id)channelTagMetadata;
- (void)clearTopicIDs;
- (void)clearTopics;
- (id)clusterID;
- (unsigned long long)contentType;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)expirationData;
- (unsigned long long)feedHalfLifeMilliseconds;
- (id)feedID;
- (id)float16FullBodyEncoding;
- (id)float16TitleEncoding;
- (id)globalCohorts;
- (id)globalConversionStats;
- (double)globalUserFeedback;
- (bool)hasArticleID;
- (bool)hasAudioTrack;
- (bool)hasBodyTextLength;
- (bool)hasChannelConversionStats;
- (bool)hasChannelTagMetadata;
- (bool)hasClusterID;
- (bool)hasContentType;
- (bool)hasExpirationData;
- (bool)hasFeedHalfLifeMilliseconds;
- (bool)hasFeedID;
- (bool)hasFloat16FullBodyEncoding;
- (bool)hasFloat16TitleEncoding;
- (bool)hasGlobalCohorts;
- (bool)hasGlobalConversionStats;
- (bool)hasGlobalUserFeedback;
- (bool)hasHasAudioTrack;
- (bool)hasHasThumbnail;
- (bool)hasHasVideo;
- (bool)hasHasVideoStillImage;
- (bool)hasIsBundlePaid;
- (bool)hasIsEvergreen;
- (bool)hasIsExplicitContent;
- (bool)hasIsFeatureCandidate;
- (bool)hasIsFeatured;
- (bool)hasIsFromBlockedStorefront;
- (bool)hasIsHiddenFromAutoFavorites;
- (bool)hasIsIssueOnly;
- (bool)hasIsPaid;
- (bool)hasIsSponsored;
- (bool)hasLanguage;
- (bool)hasMinimumNewsVersion;
- (bool)hasOrder;
- (bool)hasParentIssueID;
- (bool)hasPublishDateMilliseconds;
- (bool)hasPublisherArticleVersion;
- (bool)hasReduceVisibility;
- (bool)hasScoreProfiles;
- (bool)hasSourceArticleListID;
- (bool)hasSourceChannelCohorts;
- (bool)hasSourceChannelID;
- (bool)hasThumbnail;
- (bool)hasThumbnailPerceptualHash;
- (bool)hasVideo;
- (bool)hasVideoStillImage;
- (bool)hasWebConverted;
- (unsigned long long)hash;
- (bool)isBundlePaid;
- (bool)isEqual:(id)arg1;
- (bool)isEvergreen;
- (bool)isExplicitContent;
- (bool)isFeatureCandidate;
- (bool)isFeatured;
- (bool)isFromBlockedStorefront;
- (bool)isHiddenFromAutoFavorites;
- (bool)isIssueOnly;
- (bool)isPaid;
- (bool)isSponsored;
- (id)language;
- (void)mergeFrom:(id)arg1;
- (long long)minimumNewsVersion;
- (unsigned long long)order;
- (id)parentIssueID;
- (unsigned long long)publishDateMilliseconds;
- (long long)publisherArticleVersion;
- (bool)readFrom:(id)arg1;
- (bool)reduceVisibility;
- (id)scoreProfiles;
- (void)setArticleID:(id)arg1;
- (void)setBodyTextLength:(long long)arg1;
- (void)setChannelConversionStats:(id)arg1;
- (void)setChannelTagMetadata:(id)arg1;
- (void)setClusterID:(id)arg1;
- (void)setContentType:(unsigned long long)arg1;
- (void)setExpirationData:(id)arg1;
- (void)setFeedHalfLifeMilliseconds:(unsigned long long)arg1;
- (void)setFeedID:(id)arg1;
- (void)setFloat16FullBodyEncoding:(id)arg1;
- (void)setFloat16TitleEncoding:(id)arg1;
- (void)setGlobalCohorts:(id)arg1;
- (void)setGlobalConversionStats:(id)arg1;
- (void)setGlobalUserFeedback:(double)arg1;
- (void)setHasAudioTrack:(bool)arg1;
- (void)setHasBodyTextLength:(bool)arg1;
- (void)setHasContentType:(bool)arg1;
- (void)setHasFeedHalfLifeMilliseconds:(bool)arg1;
- (void)setHasGlobalUserFeedback:(bool)arg1;
- (void)setHasHasAudioTrack:(bool)arg1;
- (void)setHasHasThumbnail:(bool)arg1;
- (void)setHasHasVideo:(bool)arg1;
- (void)setHasHasVideoStillImage:(bool)arg1;
- (void)setHasIsBundlePaid:(bool)arg1;
- (void)setHasIsEvergreen:(bool)arg1;
- (void)setHasIsExplicitContent:(bool)arg1;
- (void)setHasIsFeatureCandidate:(bool)arg1;
- (void)setHasIsFeatured:(bool)arg1;
- (void)setHasIsFromBlockedStorefront:(bool)arg1;
- (void)setHasIsHiddenFromAutoFavorites:(bool)arg1;
- (void)setHasIsIssueOnly:(bool)arg1;
- (void)setHasIsPaid:(bool)arg1;
- (void)setHasIsSponsored:(bool)arg1;
- (void)setHasMinimumNewsVersion:(bool)arg1;
- (void)setHasOrder:(bool)arg1;
- (void)setHasPublishDateMilliseconds:(bool)arg1;
- (void)setHasPublisherArticleVersion:(bool)arg1;
- (void)setHasReduceVisibility:(bool)arg1;
- (void)setHasThumbnail:(bool)arg1;
- (void)setHasVideo:(bool)arg1;
- (void)setHasVideoStillImage:(bool)arg1;
- (void)setHasWebConverted:(bool)arg1;
- (void)setIsBundlePaid:(bool)arg1;
- (void)setIsEvergreen:(bool)arg1;
- (void)setIsExplicitContent:(bool)arg1;
- (void)setIsFeatureCandidate:(bool)arg1;
- (void)setIsFeatured:(bool)arg1;
- (void)setIsFromBlockedStorefront:(bool)arg1;
- (void)setIsHiddenFromAutoFavorites:(bool)arg1;
- (void)setIsIssueOnly:(bool)arg1;
- (void)setIsPaid:(bool)arg1;
- (void)setIsSponsored:(bool)arg1;
- (void)setLanguage:(id)arg1;
- (void)setMinimumNewsVersion:(long long)arg1;
- (void)setOrder:(unsigned long long)arg1;
- (void)setParentIssueID:(id)arg1;
- (void)setPublishDateMilliseconds:(unsigned long long)arg1;
- (void)setPublisherArticleVersion:(long long)arg1;
- (void)setReduceVisibility:(bool)arg1;
- (void)setScoreProfiles:(id)arg1;
- (void)setSourceArticleListID:(id)arg1;
- (void)setSourceChannelCohorts:(id)arg1;
- (void)setSourceChannelID:(id)arg1;
- (void)setThumbnailPerceptualHash:(id)arg1;
- (void)setTopicIDs:(id)arg1;
- (void)setTopics:(id)arg1;
- (void)setWebConverted:(bool)arg1;
- (id)sourceArticleListID;
- (id)sourceChannelCohorts;
- (id)sourceChannelID;
- (id)thumbnailPerceptualHash;
- (id)topicIDs;
- (id)topicIDsAtIndex:(unsigned long long)arg1;
- (unsigned long long)topicIDsCount;
- (id)topics;
- (id)topicsAtIndex:(unsigned long long)arg1;
- (unsigned long long)topicsCount;
- (bool)webConverted;
- (void)writeTo:(id)arg1;

// Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore

+ (id)baseKeysForArticleRecord;
+ (id)baseKeysForFeedItemRecord;
+ (id)feedItemFromCKRecord:(id)arg1 storefrontID:(id)arg2 recordSource:(id)arg3;
+ (id)keysForArticleRecordWithRecordSource:(id)arg1;
+ (id)keysForFeedItemAndArticleRecordWithRecordSource:(id)arg1;

- (unsigned long long)articleContentType;
- (bool)canBePurchased;
- (long long)compareGlobalUserFeedback:(id)arg1;
- (long long)compareGlobalUserFeedbackDescending:(id)arg1;
- (long long)compareOrder:(id)arg1;
- (long long)compareOrderDescending:(id)arg1;
- (id)description;
- (void)enumerateFeaturesWithBlock:(id /* block */)arg1;
- (void)enumerateTopicCohortsWithBlock:(id /* block */)arg1;
- (void)enumerateTopicConversionStatsWithBlock:(id /* block */)arg1;
- (unsigned long long)halfLife;
- (bool)hasFeature:(id)arg1;
- (unsigned long long)hash;
- (id)identifier;
- (bool)isANF;
- (bool)isEqual:(id)arg1;
- (id)itemID;
- (void)markAsEvergreen;
- (bool)mustShow;
- (id)publishDate;
- (long long)publisherArticleVersion;
- (id)publisherCohorts;
- (id)publisherConversionStats;
- (id)publisherID;
- (id)publisherTagMetadata;
- (id)scoreProfile;
- (void)setScoreProfile:(id)arg1;
- (id)sourceFeedID;

@end
