
@interface SXEmbedComponentView : SXComponentView <SXViewportChangeListener, UIGestureRecognizerDelegate, UIScrollViewDelegate, WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate, _WKFullscreenDelegate> {
    NSString * _HTML;
    <SXComponentActionHandler> * _actionHandler;
    UIActivityIndicatorView * _activityIndicator;
    <SXAnalyticsReporting> * _analyticsReporting;
    struct CGSize { 
        double width; 
        double height; 
    }  _currentLayoutSize;
    struct CGSize { 
        double width; 
        double height; 
    }  _currentViewportSize;
    struct CGSize { 
        double width; 
        double height; 
    }  _currentlyLayoutingForSize;
    WKWebsiteDataStore * _dataStore;
    <SXEmbedType> * _embedConfiguration;
    <SXEmbedDataProvider> * _embedDataProvider;
    SXEmbedResource * _embedResource;
    UILabel * _errorLabel;
    NSMutableSet * _expectedMessages;
    bool  _failedLoading;
    bool  _hasRegisteredScriptMessageHandlers;
    WKNavigation * _initialNavigation;
    <SXLayoutInvalidator> * _layoutInvalidator;
    SXWebContentLoadEvent * _loadEvent;
    <SXProxyAuthenticationHandler> * _proxyAuthenticationHandler;
    <SWReachabilityProvider> * _reachabilityProvider;
    SXRelatedWebViewCache * _relatedWebViewCache;
    <SXSceneStateMonitor> * _sceneStateMonitor;
    TFMultiDelegate * _scriptMessageHandler;
    NSString * _userScript;
    bool  _usingElementFullscreen;
    SWCrashRetryThrottler * _webCrashRetryThrottler;
    WKWebView * _webView;
    WKWebView * _webViewPresentingInFullscreen;
}

@property (nonatomic, retain) NSString *HTML;
@property (nonatomic, readonly) <SXComponentActionHandler> *actionHandler;
@property (nonatomic, retain) UIActivityIndicatorView *activityIndicator;
@property (nonatomic, readonly) <SXAnalyticsReporting> *analyticsReporting;
@property (nonatomic) struct CGSize { double x1; double x2; } currentLayoutSize;
@property (nonatomic) struct CGSize { double x1; double x2; } currentViewportSize;
@property (nonatomic) struct CGSize { double x1; double x2; } currentlyLayoutingForSize;
@property (nonatomic, readonly) WKWebsiteDataStore *dataStore;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) <SXEmbedType> *embedConfiguration;
@property (nonatomic, readonly) <SXEmbedDataProvider> *embedDataProvider;
@property (nonatomic, retain) SXEmbedResource *embedResource;
@property (nonatomic, retain) UILabel *errorLabel;
@property (nonatomic, retain) NSMutableSet *expectedMessages;
@property (nonatomic) bool failedLoading;
@property (nonatomic) bool hasRegisteredScriptMessageHandlers;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) WKNavigation *initialNavigation;
@property (nonatomic, readonly) <SXLayoutInvalidator> *layoutInvalidator;
@property (nonatomic, retain) SXWebContentLoadEvent *loadEvent;
@property (nonatomic, readonly) <SXProxyAuthenticationHandler> *proxyAuthenticationHandler;
@property (nonatomic, readonly) <SWReachabilityProvider> *reachabilityProvider;
@property (nonatomic, readonly) SXRelatedWebViewCache *relatedWebViewCache;
@property (nonatomic, readonly) <SXSceneStateMonitor> *sceneStateMonitor;
@property (nonatomic, readonly) TFMultiDelegate *scriptMessageHandler;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSString *userScript;
@property (nonatomic) bool usingElementFullscreen;
@property (nonatomic, retain) SWCrashRetryThrottler *webCrashRetryThrottler;
@property (nonatomic, retain) WKWebView *webView;
@property (nonatomic, retain) WKWebView *webViewPresentingInFullscreen;

- (void).cxx_destruct;
- (id)HTML;
- (id)HTMLByEnclosingHTML:(id)arg1 withHTML:(id)arg2;
- (void)_webViewDidEnterElementFullscreen:(id)arg1;
- (void)_webViewDidEnterFullscreen:(id)arg1;
- (void)_webViewDidExitElementFullscreen:(id)arg1;
- (void)_webViewDidExitFullscreen:(id)arg1;
- (void)_webViewWebProcessDidCrash:(id)arg1;
- (id)actionHandler;
- (id)activityIndicator;
- (void)addScriptMessageHandlers;
- (bool)allowHierarchyRemoval;
- (id)analyticsReporting;
- (struct CGSize { double x1; double x2; })currentLayoutSize;
- (struct CGSize { double x1; double x2; })currentViewportSize;
- (struct CGSize { double x1; double x2; })currentlyLayoutingForSize;
- (id)dataStore;
- (void)dealloc;
- (void)discardContents;
- (void)displayEmbedIfNeeded;
- (id)embedConfiguration;
- (id)embedDataProvider;
- (id)embedResource;
- (id)enclosingHTML;
- (id)errorLabel;
- (id)expectedMessages;
- (bool)failedLoading;
- (void)finalizeLayoutForSize:(struct CGSize { double x1; double x2; })arg1;
- (bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleError:(id)arg1;
- (bool)hasLoadedEmbedData;
- (bool)hasRegisteredScriptMessageHandlers;
- (id)initWithDOMObjectProvider:(id)arg1 viewport:(id)arg2 presentationDelegate:(id)arg3 componentStyleRendererFactory:(id)arg4 reachabilityProvider:(id)arg5 embedDataProvider:(id)arg6 actionHandler:(id)arg7 layoutInvalidator:(id)arg8 websiteDataStore:(id)arg9 relatedWebViewCache:(id)arg10 proxyAuthenticationHandler:(id)arg11 sceneStateMonitor:(id)arg12 analyticsReporting:(id)arg13;
- (id)initialNavigation;
- (double)initialScale;
- (id)layoutInvalidator;
- (void)layoutWebViewForSize:(struct CGSize { double x1; double x2; })arg1;
- (void)loadComponent:(id)arg1;
- (void)loadEmbedData;
- (void)loadEmbedIfNeeded;
- (id)loadEvent;
- (void)loadWebView;
- (void)loadWebViewIfNeeded;
- (void)presentComponentWithChanges:(struct { bool x1; bool x2; bool x3; })arg1;
- (void)prewarmWebView;
- (id)proxyAuthenticationHandler;
- (id)reachabilityProvider;
- (id)relatedWebViewCache;
- (void)reloadEmbed;
- (void)removeScriptMessageHandlers;
- (void)renderContents;
- (void)reportLoadEventWithError:(id)arg1;
- (id)sceneStateMonitor;
- (id)scriptMessageHandler;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)setActivityIndicator:(id)arg1;
- (void)setCurrentLayoutSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setCurrentViewportSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setCurrentlyLayoutingForSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setEmbedConfiguration:(id)arg1;
- (void)setEmbedResource:(id)arg1;
- (void)setErrorLabel:(id)arg1;
- (void)setExpectedMessages:(id)arg1;
- (void)setFailedLoading:(bool)arg1;
- (void)setHTML:(id)arg1;
- (void)setHasRegisteredScriptMessageHandlers:(bool)arg1;
- (void)setInitialNavigation:(id)arg1;
- (void)setLoadEvent:(id)arg1;
- (void)setUserScript:(id)arg1;
- (void)setUsingElementFullscreen:(bool)arg1;
- (void)setWebCrashRetryThrottler:(id)arg1;
- (void)setWebView:(id)arg1;
- (void)setWebViewPresentingInFullscreen:(id)arg1;
- (bool)shouldAllowRequestToURL:(id)arg1;
- (bool)shouldLayoutWebView;
- (bool)shouldShowWebView;
- (void)showActivityIndicator:(bool)arg1;
- (id)unableToLoadMessage;
- (unsigned long long)userActionMediaTypes;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (id)userScript;
- (bool)usingElementFullscreen;
- (void)viewport:(id)arg1 appearStateChangedFromState:(unsigned long long)arg2;
- (id)webCrashRetryThrottler;
- (id)webView;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(id /* block */)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)webViewEnteredFullscreen:(id)arg1;
- (void)webViewExitedFullscreen:(id)arg1;
- (id)webViewPresentingInFullscreen;
- (void)willPresentComponentWithChanges:(struct { bool x1; bool x2; bool x3; })arg1;

@end
