
@interface HAPAccessory : HMFObject <HMFMerging> {
    HMFMACAddress * _bluetoothClassicMacAddress;
    long long  _communicationProtocol;
    int  _consecutiveFailedPingCount;
    <HAPAccessoryDelegate> * _delegate;
    NSString * _firmwareVersion;
    NSString * _identifier;
    NSNumber * _instanceID;
    long long  _linkType;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSString * _manufacturer;
    NSString * _model;
    NSString * _name;
    bool  _primary;
    NSString * _productData;
    bool  _reachable;
    NSString * _serialNumber;
    HAPAccessoryServer * _server;
    NSString * _serverIdentifier;
    NSArray * _services;
    bool  _shouldDisconnectOnIdle;
    NSNumber * _sleepInterval;
    unsigned long long  _suspendedState;
    NSDate * _timeBecameReachable;
    NSString * _uniqueIdentifier;
    NSObject<OS_dispatch_queue> * _workQueue;
}

@property (copy) HMFMACAddress *bluetoothClassicMacAddress;
@property (nonatomic, readonly, copy) NSNumber *category;
@property (readonly) long long communicationProtocol;
@property (nonatomic) int consecutiveFailedPingCount;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <HAPAccessoryDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSString *firmwareVersion;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSNumber *instanceID;
@property (nonatomic, readonly) long long linkType;
@property (nonatomic, copy) NSString *manufacturer;
@property (nonatomic, copy) NSString *model;
@property (nonatomic, copy) NSString *name;
@property (getter=isPaired, nonatomic, readonly) bool paired;
@property (getter=isPrimary, nonatomic) bool primary;
@property (nonatomic, copy) NSString *productData;
@property (getter=isReachable, nonatomic) bool reachable;
@property (nonatomic, copy) NSString *serialNumber;
@property (nonatomic) HAPAccessoryServer *server;
@property (nonatomic, copy) NSString *serverIdentifier;
@property (nonatomic, copy) NSArray *services;
@property (nonatomic) bool shouldDisconnectOnIdle;
@property (nonatomic, copy) NSNumber *sleepInterval;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long suspendedState;
@property (nonatomic, copy) NSDate *timeBecameReachable;
@property (nonatomic, copy) NSString *uniqueIdentifier;
@property (retain) NSObject<OS_dispatch_queue> *workQueue;

+ (id)instanceIDForUniqueIdentifier:(id)arg1;
+ (bool)isAccessoryPairedWithIdentifier:(id)arg1;
+ (bool)isAccessoryPrimaryWithUniqueIdentifier:(id)arg1;
+ (id)logCategory;
+ (id)productDataStringFromData:(id)arg1;
+ (id)serverIdentifierWithUniqueIdentifier:(id)arg1;

- (void).cxx_destruct;
- (bool)_updateAndValidateServices;
- (bool)_updateService:(id)arg1;
- (bool)_validateCharacteristicValues;
- (id)bluetoothClassicMacAddress;
- (id)category;
- (id)characteristicOfType:(id)arg1 serviceType:(id)arg2;
- (id)characteristicWithInstanceID:(id)arg1;
- (id)characteristicsOfType:(id)arg1;
- (long long)communicationProtocol;
- (int)consecutiveFailedPingCount;
- (id)delegate;
- (id)description;
- (id)firmwareVersion;
- (unsigned long long)hash;
- (id)identifier;
- (id)init;
- (id)initWithServer:(id)arg1 instanceID:(id)arg2;
- (id)initWithServer:(id)arg1 instanceID:(id)arg2 parsedServices:(id)arg3;
- (id)instanceID;
- (void)invalidateWithError:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isPaired;
- (bool)isPrimary;
- (bool)isReachable;
- (long long)linkType;
- (id)logIdentifier;
- (id)manufacturer;
- (bool)mergeObject:(id)arg1;
- (id)model;
- (id)name;
- (id)productData;
- (void)readCharacteristicValues:(id)arg1 timeout:(double)arg2 completionQueue:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)readValueForCharacteristic:(id)arg1 timeout:(double)arg2 completionQueue:(id)arg3 completionHandler:(id /* block */)arg4;
- (id)serialNumber;
- (id)server;
- (id)serverIdentifier;
- (id)serviceWithInstanceID:(id)arg1;
- (id)services;
- (id)servicesOfType:(id)arg1;
- (void)setBluetoothClassicMacAddress:(id)arg1;
- (void)setConsecutiveFailedPingCount:(int)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFirmwareVersion:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setInstanceID:(id)arg1;
- (void)setManufacturer:(id)arg1;
- (void)setModel:(id)arg1;
- (void)setName:(id)arg1;
- (void)setPrimary:(bool)arg1;
- (void)setProductData:(id)arg1;
- (void)setReachable:(bool)arg1;
- (void)setSerialNumber:(id)arg1;
- (void)setServer:(id)arg1;
- (void)setServerIdentifier:(id)arg1;
- (void)setServices:(id)arg1;
- (void)setShouldDisconnectOnIdle:(bool)arg1;
- (void)setSleepInterval:(id)arg1;
- (void)setSuspendedState:(unsigned long long)arg1;
- (void)setTimeBecameReachable:(id)arg1;
- (void)setUniqueIdentifier:(id)arg1;
- (void)setWorkQueue:(id)arg1;
- (id)shortDescription;
- (bool)shouldDisconnectOnIdle;
- (bool)shouldMergeObject:(id)arg1;
- (id)sleepInterval;
- (unsigned long long)suspendedState;
- (id)timeBecameReachable;
- (id)uniqueIdentifier;
- (bool)updateForAccessoryInformationService;
- (id)workQueue;
- (void)writeCharacteristicValue:(id)arg1 timeout:(double)arg2 completionQueue:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)writeCharacteristicValues:(id)arg1 timeout:(double)arg2 completionQueue:(id)arg3 completionHandler:(id /* block */)arg4;

@end
