
@interface HDCodableFitnessFriendWorkout : PBCodable <HDDecoding, NSCopying> {
    long long  _amm;
    NSString * _bundleID;
    NSString * _deviceManufacturer;
    NSString * _deviceModel;
    double  _duration;
    NSData * _friendUUID;
    double  _goal;
    long long  _goalType;
    struct { 
        unsigned int amm : 1; 
        unsigned int duration : 1; 
        unsigned int goal : 1; 
        unsigned int goalType : 1; 
        unsigned int isIndoorWorkout : 1; 
        unsigned int isWatchWorkout : 1; 
        unsigned int totalBasalEnergyBurnedInCanonicalUnit : 1; 
        unsigned int totalDistanceInCanonicalUnit : 1; 
        unsigned int totalEnergyBurnedInCanonicalUnit : 1; 
        unsigned int type : 1; 
    }  _has;
    long long  _isIndoorWorkout;
    long long  _isWatchWorkout;
    HDCodableSample * _sample;
    NSString * _seymourCatalogWorkoutIdentifier;
    NSString * _seymourMediaType;
    double  _totalBasalEnergyBurnedInCanonicalUnit;
    double  _totalDistanceInCanonicalUnit;
    double  _totalEnergyBurnedInCanonicalUnit;
    long long  _type;
}

@property (nonatomic) long long amm;
@property (nonatomic, retain) NSString *bundleID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *deviceManufacturer;
@property (nonatomic, retain) NSString *deviceModel;
@property (nonatomic) double duration;
@property (nonatomic, retain) NSData *friendUUID;
@property (nonatomic) double goal;
@property (nonatomic) long long goalType;
@property (nonatomic) bool hasAmm;
@property (nonatomic, readonly) bool hasBundleID;
@property (nonatomic, readonly) bool hasDeviceManufacturer;
@property (nonatomic, readonly) bool hasDeviceModel;
@property (nonatomic) bool hasDuration;
@property (nonatomic, readonly) bool hasFriendUUID;
@property (nonatomic) bool hasGoal;
@property (nonatomic) bool hasGoalType;
@property (nonatomic) bool hasIsIndoorWorkout;
@property (nonatomic) bool hasIsWatchWorkout;
@property (nonatomic, readonly) bool hasSample;
@property (nonatomic, readonly) bool hasSeymourCatalogWorkoutIdentifier;
@property (nonatomic, readonly) bool hasSeymourMediaType;
@property (nonatomic) bool hasTotalBasalEnergyBurnedInCanonicalUnit;
@property (nonatomic) bool hasTotalDistanceInCanonicalUnit;
@property (nonatomic) bool hasTotalEnergyBurnedInCanonicalUnit;
@property (nonatomic) bool hasType;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long isIndoorWorkout;
@property (nonatomic) long long isWatchWorkout;
@property (nonatomic, retain) HDCodableSample *sample;
@property (nonatomic, retain) NSString *seymourCatalogWorkoutIdentifier;
@property (nonatomic, retain) NSString *seymourMediaType;
@property (readonly) Class superclass;
@property (nonatomic) double totalBasalEnergyBurnedInCanonicalUnit;
@property (nonatomic) double totalDistanceInCanonicalUnit;
@property (nonatomic) double totalEnergyBurnedInCanonicalUnit;
@property (nonatomic) long long type;

- (void).cxx_destruct;
- (long long)amm;
- (bool)applyToObject:(id)arg1;
- (id)bundleID;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)deviceManufacturer;
- (id)deviceModel;
- (id)dictionaryRepresentation;
- (double)duration;
- (id)friendUUID;
- (double)goal;
- (long long)goalType;
- (bool)hasAmm;
- (bool)hasBundleID;
- (bool)hasDeviceManufacturer;
- (bool)hasDeviceModel;
- (bool)hasDuration;
- (bool)hasFriendUUID;
- (bool)hasGoal;
- (bool)hasGoalType;
- (bool)hasIsIndoorWorkout;
- (bool)hasIsWatchWorkout;
- (bool)hasSample;
- (bool)hasSeymourCatalogWorkoutIdentifier;
- (bool)hasSeymourMediaType;
- (bool)hasTotalBasalEnergyBurnedInCanonicalUnit;
- (bool)hasTotalDistanceInCanonicalUnit;
- (bool)hasTotalEnergyBurnedInCanonicalUnit;
- (bool)hasType;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (long long)isIndoorWorkout;
- (long long)isWatchWorkout;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (id)sample;
- (void)setAmm:(long long)arg1;
- (void)setBundleID:(id)arg1;
- (void)setDeviceManufacturer:(id)arg1;
- (void)setDeviceModel:(id)arg1;
- (void)setDuration:(double)arg1;
- (void)setFriendUUID:(id)arg1;
- (void)setGoal:(double)arg1;
- (void)setGoalType:(long long)arg1;
- (void)setHasAmm:(bool)arg1;
- (void)setHasDuration:(bool)arg1;
- (void)setHasGoal:(bool)arg1;
- (void)setHasGoalType:(bool)arg1;
- (void)setHasIsIndoorWorkout:(bool)arg1;
- (void)setHasIsWatchWorkout:(bool)arg1;
- (void)setHasTotalBasalEnergyBurnedInCanonicalUnit:(bool)arg1;
- (void)setHasTotalDistanceInCanonicalUnit:(bool)arg1;
- (void)setHasTotalEnergyBurnedInCanonicalUnit:(bool)arg1;
- (void)setHasType:(bool)arg1;
- (void)setIsIndoorWorkout:(long long)arg1;
- (void)setIsWatchWorkout:(long long)arg1;
- (void)setSample:(id)arg1;
- (void)setSeymourCatalogWorkoutIdentifier:(id)arg1;
- (void)setSeymourMediaType:(id)arg1;
- (void)setTotalBasalEnergyBurnedInCanonicalUnit:(double)arg1;
- (void)setTotalDistanceInCanonicalUnit:(double)arg1;
- (void)setTotalEnergyBurnedInCanonicalUnit:(double)arg1;
- (void)setType:(long long)arg1;
- (id)seymourCatalogWorkoutIdentifier;
- (id)seymourMediaType;
- (double)totalBasalEnergyBurnedInCanonicalUnit;
- (double)totalDistanceInCanonicalUnit;
- (double)totalEnergyBurnedInCanonicalUnit;
- (long long)type;
- (void)writeTo:(id)arg1;

@end
