
@interface VMUFieldInfo : NSObject {
    VMUClassInfo * _destinationLayout;
    unsigned int  _flags;
    NSString * _ivarName;
    unsigned int  _offset;
    NSArray * _possibleEnumPayloadFieldArray;
    unsigned int  _scanType;
    unsigned int  _scannable;
    unsigned int  _size;
    unsigned int  _stride;
    NSMutableArray * _subFieldArray;
    void * _swiftTyperef;
    NSString * _typeName;
}

@property (readonly) unsigned int bitfieldWidth;
@property (nonatomic, retain) VMUClassInfo *destinationLayout;
@property (nonatomic, readonly) unsigned int flags;
@property (nonatomic, readonly) bool isArrayEntries;
@property (nonatomic, readonly) bool isArraySize;
@property (nonatomic, readonly) bool isByref;
@property (nonatomic, readonly) bool isCapture;
@property (nonatomic, readonly) bool isKeyField;
@property (nonatomic, readonly) bool isKeysPointer;
@property (nonatomic, readonly) bool isStorageBitmapPointer;
@property (nonatomic, readonly) bool isStorageImplPointer;
@property (nonatomic, readonly) bool isValueField;
@property (nonatomic, readonly) bool isValuesPointer;
@property (nonatomic, readonly) NSString *ivarName;
@property (readonly) unsigned int kind;
@property (readonly) unsigned int offset;
@property (nonatomic, readonly) NSArray *possibleEnumPayloadFieldArray;
@property (readonly) unsigned int scanType;
@property (readonly) unsigned int scannableSize;
@property (readonly) unsigned int size;
@property (readonly) unsigned int stride;
@property (nonatomic, readonly) NSArray *subFieldArray;
@property (readonly) void*swiftTyperef;
@property (nonatomic, readonly) NSString *typeName;
@property (nonatomic, readonly) bool typeNameMayDescribeReferencedAllocation;
@property (readonly) NSString *typedDescription;

- (void).cxx_destruct;
- (id)_fullIvarNameAtOffset:(unsigned int)arg1 leafOffset:(unsigned int*)arg2 depth:(unsigned int)arg3;
- (void)_setFlags:(unsigned int)arg1;
- (void)_setIvarName:(id)arg1;
- (void)_setKind:(unsigned int)arg1;
- (void)_setOffset:(unsigned int)arg1;
- (void)_setScanType:(unsigned int)arg1;
- (void)_setScannableSize:(unsigned int)arg1;
- (void)_setSize:(unsigned int)arg1;
- (void)_setStride:(unsigned int)arg1;
- (unsigned int)bitfieldWidth;
- (void)dealloc;
- (id)description;
- (id)descriptionOfFieldValueInObjectMemory:(void*)arg1 scanner:(id)arg2;
- (id)destinationLayout;
- (unsigned int)flags;
- (id)fullIvarNameAtOffset:(unsigned int)arg1;
- (id)getLeafFieldAtOffset:(unsigned int)arg1 leafOffset:(unsigned int*)arg2;
- (unsigned long long)hash;
- (id)initStorageEntryFieldWithName:(id)arg1 type:(id)arg2 kind:(unsigned int)arg3 scan:(unsigned int)arg4 offset:(unsigned int)arg5 size:(unsigned int)arg6 stride:(unsigned int)arg7 subFieldArray:(id)arg8;
- (id)initStorageInfoFieldWithName:(id)arg1 type:(id)arg2 kind:(unsigned int)arg3 scan:(unsigned int)arg4 offset:(unsigned int)arg5 size:(unsigned int)arg6 stride:(unsigned int)arg7 subFieldArray:(id)arg8;
- (id)initSwiftEnumPayloadFieldWithName:(id)arg1 type:(id)arg2 kind:(unsigned int)arg3 scan:(unsigned int)arg4 offset:(unsigned int)arg5 size:(unsigned int)arg6 stride:(unsigned int)arg7 possibleEnumSubFieldArray:(id)arg8 swiftTyperef:(void*)arg9;
- (id)initWithName:(id)arg1 type:(id)arg2 kind:(unsigned int)arg3 scan:(unsigned int)arg4 offset:(unsigned int)arg5 size:(unsigned int)arg6 stride:(unsigned int)arg7 subFieldArray:(id)arg8 swiftTyperef:(void*)arg9;
- (id)initWithName:(id)arg1 type:(id)arg2 scan:(unsigned int)arg3 offset:(unsigned int)arg4 size:(unsigned int)arg5;
- (id)initWithObjcIvar:(struct objc_ivar { }*)arg1 size:(unsigned int)arg2 offset:(unsigned int)arg3 ivarName:(const char *)arg4 isARC:(bool)arg5 is64Bit:(bool)arg6;
- (id)initWithSerializer:(id)arg1 classMap:(id)arg2 version:(unsigned int)arg3 error:(id*)arg4;
- (id)initWithSerializer:(id)arg1 classMap:(id)arg2 version:(unsigned int)arg3 returnedDestinationLayoutClassInfoIndex:(unsigned int*)arg4 error:(id*)arg5;
- (void)initializeSubFieldArray;
- (bool)isArrayEntries;
- (bool)isArraySize;
- (bool)isByref;
- (bool)isCapture;
- (bool)isEqual:(id)arg1;
- (bool)isKeyField;
- (bool)isKeysPointer;
- (bool)isStorageBitmapPointer;
- (bool)isStorageImplPointer;
- (bool)isValueField;
- (bool)isValuesPointer;
- (id)ivarName;
- (unsigned int)kind;
- (id)mutableCopy;
- (unsigned int)offset;
- (id)possibleEnumPayloadFieldArray;
- (unsigned int)scanType;
- (unsigned int)scannableSize;
- (void)serializeWithClassMap:(id)arg1 simpleSerializer:(id)arg2 version:(unsigned int)arg3;
- (void)setDestinationLayout:(id)arg1;
- (void)setTypeName:(id)arg1;
- (unsigned int)size;
- (unsigned int)stride;
- (id)subFieldArray;
- (void*)swiftTyperef;
- (id)typeName;
- (bool)typeNameMayDescribeReferencedAllocation;
- (id)typedDescription;

@end
