
@interface _UIKeyboardArbiterClientHandle : NSObject <_UIKeyboardArbitration> {
    bool  _acquiringFocus;
    BSAbsoluteMachTimer * _acquiringFocusTimer;
    bool  _active;
    NSString * _bundleIdentifier;
    NSArray * _cachedContext;
    bool  _checkingShowability;
    int  _childrenSuppressionCount;
    NSXPCConnection * _connection;
    bool  _deactivating;
    BSServiceConnectionEndpointInjector * _endpointGrantInjector;
    bool  _hasDebugInformationEntitlement;
    NSMutableSet * _hostedPids;
    double  _iavHeight;
    bool  _inputUIHost;
    bool  _invalidated;
    bool  _keyboardOnScreen;
    double  _level;
    bool  _multipleScenes;
    _UIKeyboardArbiter * _owner;
    id /* block */  _pendingNotifyKeyboardChanged;
    int  _prevActiveIdentifier;
    RBSProcessHandle * _processHandle;
    UIKBArbiterClientFocusContext * _remoteFocusContext;
    RBSAssertion * _remoteKeepAliveAssertion;
    unsigned long long  _remoteKeepAliveAssertionCount;
    unsigned long long  _remoteKeepAliveTimerCount;
    bool  _requestedCorrectionOfClientSceneIdentityWhileAcquiringFocus;
    bool  _requiresInputUIForAutofillUIOnly;
    bool  _running;
    FBSCAContextSceneLayer * _sceneLayer;
    int  _suppressionCount;
    unsigned long long  _wantedState;
    bool  _wantsFence;
}

@property (getter=isAcquiringFocus, nonatomic, readonly) bool acquiringFocus;
@property (readonly) bool active;
@property (readonly, retain) NSString *bundleIdentifier;
@property (readonly) NSXPCConnection *connection;
@property (readonly) bool deactivating;
@property (nonatomic) bool hasDebugInformationEntitlement;
@property (readonly) bool hasHostedPids;
@property (readonly) double iavHeight;
@property (nonatomic) bool inputUIHost;
@property (readonly) bool isKeyboardOnScreen;
@property (readonly) double level;
@property (readonly) bool multipleScenes;
@property (nonatomic, copy) id /* block */ pendingNotifyKeyboardChanged;
@property int prevActiveIdentifier;
@property (readonly, retain) RBSProcessHandle *processHandle;
@property (readonly) int processIdentifier;
@property (readonly, retain) UIKBArbiterClientFocusContext *remoteFocusContext;
@property (nonatomic) bool requestedCorrectionOfClientSceneIdentityWhileAcquiringFocus;
@property (nonatomic) bool requiresInputUIForAutofillUIOnly;
@property bool running;
@property (readonly, retain) FBSCAContextSceneLayer *sceneLayer;
@property int suppressionCount;
@property (readonly) unsigned long long wantedState;
@property (readonly) bool wantsFence;

+ (id)handlerWithArbiter:(id)arg1 forConnection:(id)arg2;

- (void).cxx_destruct;
- (void)_deactivateScene;
- (bool)_isKeyboardOnScreen:(id)arg1;
- (void)_reevaluateRemoteFocusContext:(id)arg1;
- (bool)_shouldRejectSceneIdentityUpdateCorrectingClientIfNeeded:(id)arg1 fromSelector:(SEL)arg2;
- (bool)active;
- (void)addHostedPids:(id)arg1;
- (void)applicationShouldFocusWithBundle:(id)arg1 onCompletion:(id /* block */)arg2;
- (void)beginAcquiringFocusOnQueue:(id)arg1;
- (id)bundleIdentifier;
- (void)cacheWindowContext;
- (void)checkActivation:(unsigned long long)arg1;
- (void)clearAcquiringFocus;
- (id)connection;
- (bool)deactivating;
- (void)dealloc;
- (id)description;
- (void)didAttachLayer;
- (void)didDetachLayer;
- (void)focusApplicationWithProcessIdentifier:(int)arg1 context:(id)arg2 onCompletion:(id /* block */)arg3;
- (void)focusApplicationWithProcessIdentifier:(int)arg1 context:(id)arg2 stealingKeyboard:(bool)arg3 onCompletion:(id /* block */)arg4;
- (bool)hasDebugInformationEntitlement;
- (bool)hasHostedPids;
- (double)iavHeight;
- (bool)inputUIHost;
- (void)invalidate;
- (bool)isAcquiringFocus;
- (bool)isHandlerShowableWithHandler:(id)arg1;
- (bool)isHostingPID:(int)arg1;
- (bool)isKeyboardOnScreen;
- (double)level;
- (bool)multipleScenes;
- (void)notifyHostedPIDsOfSuppression:(bool)arg1;
- (void)notifyHostedPIDsOfSuppression:(bool)arg1 active:(bool)arg2;
- (void)notifyIAVHeight:(double)arg1;
- (id /* block */)pendingNotifyKeyboardChanged;
- (int)prevActiveIdentifier;
- (id)processHandle;
- (int)processIdentifier;
- (void)releaseProcessAssertion;
- (id)remoteFocusContext;
- (bool)requestedCorrectionOfClientSceneIdentityWhileAcquiringFocus;
- (bool)requiresInputUIForAutofillUIOnly;
- (void)retrieveDebugInformation:(id /* block */)arg1;
- (void)retrieveMoreDebugInformationWithCompletion:(id /* block */)arg1;
- (bool)running;
- (id)sceneLayer;
- (void)setClientFocusContext:(id)arg1;
- (void)setDeactivating:(bool)arg1;
- (void)setHasDebugInformationEntitlement:(bool)arg1;
- (void)setInputUIHost:(bool)arg1;
- (void)setKeyboardTotalDisable:(bool)arg1 withFence:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)setPendingNotifyKeyboardChanged:(id /* block */)arg1;
- (void)setPrevActiveIdentifier:(int)arg1;
- (void)setRequestedCorrectionOfClientSceneIdentityWhileAcquiringFocus:(bool)arg1;
- (void)setRequiresInputUIForAutofillUIOnly:(bool)arg1;
- (void)setRunning:(bool)arg1;
- (void)setSuppressionCount:(int)arg1;
- (void)setWantsFencing:(bool)arg1;
- (void)setWindowContextID:(unsigned int)arg1 focusContext:(id)arg2 windowState:(unsigned long long)arg3 withLevel:(double)arg4;
- (void)setWindowHostingPID:(int)arg1 active:(bool)arg2;
- (void)signalAutofillUIBringupWithCompletion:(id /* block */)arg1;
- (void)signalEventSourceChanged:(long long)arg1 completionHandler:(id /* block */)arg2;
- (void)signalKeyboardChangeComplete;
- (void)signalKeyboardChanged:(id)arg1 onCompletion:(id /* block */)arg2;
- (void)signalKeyboardClientChanged:(id)arg1 onCompletion:(id /* block */)arg2;
- (void)signalKeyboardUIDidChange:(id)arg1 onCompletion:(id /* block */)arg2;
- (void)startArbitrationWithExpectedState:(id)arg1 focusContext:(id)arg2 hostingPIDs:(id)arg3 usingFence:(bool)arg4 withSuppression:(int)arg5 onConnected:(id /* block */)arg6;
- (void)startArbitrationWithExpectedState:(id)arg1 hostingPIDs:(id)arg2 usingFence:(bool)arg3 withSuppression:(int)arg4 onConnected:(id /* block */)arg5;
- (int)suppressionCount;
- (bool)takeProcessAssertionOnRemoteWithQueue:(id)arg1;
- (void)transition:(id)arg1 eventStage:(unsigned long long)arg2 withInfo:(id)arg3;
- (void)uncacheWindowContext;
- (void)updateSuspensionCountForPids:(id)arg1 active:(bool)arg2;
- (unsigned long long)wantedState;
- (bool)wantsFence;

@end
