
@interface PBFPosterModelStoreCoordinator : NSObject <PBFPosterSnapshotCoordinatorProviding> {
    NSObject<OS_dispatch_queue> * _accessQueue;
    NSMapTable * _accessQueue_identityToPosterSnapshotCoordinator;
    NSMutableDictionary * _accessQueue_posterIdentityBySupplementByVersion;
    NSMutableDictionary * _accessQueue_stagedPosterIdentityBySupplementByVersion;
    NSURL * _containerVersionsURL;
    NSString * _descriptorIdentifier;
    NSString * _extensionIdentifier;
    NSFileManager * _fileManager;
    NSURL * _identifierURL;
    NSUUID * _posterUUID;
    NSURL * _providerInfoURL;
    NSURL * _providerURL;
    bool  _readonly;
    NSString * _role;
    NSURL * _transientInternalInfoURL;
}

@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *accessQueue;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *descriptorIdentifier;
@property (nonatomic, readonly) NSString *extensionIdentifier;
@property (nonatomic, readonly) NSFileManager *fileManager;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSURL *identifierURL;
@property (nonatomic, readonly, copy) NSUUID *posterUUID;
@property (nonatomic, copy) NSDictionary *providerInfo;
@property (nonatomic, readonly, copy) NSString *role;
@property (nonatomic, readonly) NSSet *snapshotURLs;
@property (readonly) Class superclass;

+ (id)createNewStoreCoordinatorWithPath:(id)arg1 error:(id*)arg2;
+ (id)expectedFileProtection;
+ (id)expectedSnapshotURLResourceValues;
+ (id)expectedURLResourceValuesForDirectories;
+ (id)expectedURLResourceValuesForFiles;
+ (bool)requiresDescriptorIdentifier;
+ (bool)shouldBeExcludedFromBackup;
+ (long long)type;

- (void).cxx_destruct;
- (id)_accessQueue_allPosterPaths;
- (void)_accessQueue_applyResourceValuesForURLs:(id)arg1 expectedResourceValues:(id)arg2 synchronous:(bool)arg3;
- (id)_accessQueue_buildIdentityForVersion:(unsigned long long)arg1 supplement:(unsigned long long)arg2;
- (id)_accessQueue_checkEnvironmentConsistency;
- (bool)_accessQueue_configureFileSystemForNewContents:(id)arg1 atPath:(id)arg2 error:(out id*)arg3;
- (id)_accessQueue_contentsOfURLWithinStore:(id)arg1 resourceKeys:(id)arg2 standardizeURLs:(bool)arg3;
- (void)_accessQueue_enumerateSnapshotCoordinators:(id /* block */)arg1;
- (id)_accessQueue_fetchIdentityForVersion:(unsigned long long)arg1 supplement:(unsigned long long)arg2 error:(id*)arg3;
- (void)_accessQueue_fixupResourceValuesWithinURL:(id)arg1 synchronous:(bool)arg2;
- (id)_accessQueue_identityOfLatestVersion;
- (void)_accessQueue_invalidate;
- (id)_accessQueue_posterPathForIdentity:(id)arg1;
- (id)_accessQueue_posterSnapshotCoordinatorForIdentity:(id)arg1;
- (id)_accessQueue_providerInfoWithError:(out id*)arg1;
- (void)_accessQueue_purgeSnapshotCache;
- (void)_accessQueue_removeSupplement:(unsigned long long)arg1 forVersion:(unsigned long long)arg2 error:(out id*)arg3;
- (id)_accessQueue_setupNewSupplementWithOptions:(unsigned long long)arg1 error:(out id*)arg2;
- (id)_accessQueue_setupNewVersionWithOptions:(unsigned long long)arg1 contents:(id)arg2 error:(out id*)arg3;
- (id)_accessQueue_snapshotURLs;
- (void)_accessQueue_writeProviderInfo:(id)arg1 error:(out id*)arg2;
- (void)_correctPermissionsForInternalDirectories:(out id*)arg1;
- (id)_posterPathForIdentity:(id)arg1;
- (void)abortStaged;
- (id)accessQueue;
- (id)addNewSupplementWithError:(out id*)arg1;
- (id)addNewVersionWithContents:(id)arg1 error:(out id*)arg2;
- (id)allPosterPaths;
- (id)checkEnvironmentConsistency;
- (bool)commitStagedWithError:(out id*)arg1;
- (id)descriptorIdentifier;
- (id)ensureFileSystemIntegrity;
- (id)extensionIdentifier;
- (id)fileManager;
- (bool)hasKnownVersions;
- (id)identifierURL;
- (id)identityForVersion:(unsigned long long)arg1 supplement:(unsigned long long)arg2;
- (id)identityOfLatestVersion;
- (id)initWithProvider:(id)arg1 identifierURL:(id)arg2 posterUUID:(id)arg3;
- (id)initWithProvider:(id)arg1 identifierURL:(id)arg2 posterUUID:(id)arg3 readonly:(bool)arg4;
- (void)invalidate;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)pathForIdentity:(id)arg1;
- (id)pathForVersion:(unsigned long long)arg1 supplement:(unsigned long long)arg2;
- (id)pathOfLatestVersion;
- (void)pbf_enumerateSnapshotCoordinators:(id /* block */)arg1;
- (id)pbf_posterSnapshotCoordinatorForIdentity:(id)arg1;
- (id)posterUUID;
- (id)providerInfo;
- (void)purgeSnapshotCache;
- (void)reapEverythingExceptLatestVersion;
- (void)reapSnapshots;
- (id)reapSnapshotsMatchingURLs:(id)arg1;
- (void)removeSupplement:(unsigned long long)arg1 forVersion:(unsigned long long)arg2 error:(out id*)arg3;
- (id)role;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setProviderInfo:(id)arg1;
- (bool)setProviderInfo:(id)arg1 error:(out id*)arg2;
- (id)snapshotURLs;
- (id)stageNewSupplementWithError:(out id*)arg1;
- (id)stageNewVersionWithContents:(id)arg1 error:(out id*)arg2;

@end
