
@interface PORegistrationContext : NSObject {
    int  _authMethod;
    bool  _authorizationProvided;
    NSString * _containerAppBundleIdentifier;
    LAContext * _credentialContext;
    bool  _deviceKeysShouldChange;
    NSString * _extensionIdentifier;
    int  _failureCount;
    NSString * _loginUserName;
    bool  _migratingDeviceKeys;
    bool  _newUser;
    long long  _options;
    POProfile * _profile;
    long long  _protocolVersion;
    NSString * _registrationToken;
    bool  _repair;
    bool  _resetKeys;
    bool  _retry;
    NSString * _smartCardTokenId;
    POExtension * _ssoExtension;
    long long  _state;
    bool  _useSharedDeviceKeys;
    NSString * _userName;
    bool  _userNotified;
}

@property int authMethod;
@property bool authorizationProvided;
@property (retain) NSString *containerAppBundleIdentifier;
@property (retain) LAContext *credentialContext;
@property bool deviceKeysShouldChange;
@property (retain) NSString *extensionIdentifier;
@property int failureCount;
@property (retain) NSString *loginUserName;
@property bool migratingDeviceKeys;
@property (getter=isNewUser) bool newUser;
@property long long options;
@property (retain) POProfile *profile;
@property long long protocolVersion;
@property (retain) NSString *registrationToken;
@property (getter=isRepair) bool repair;
@property bool resetKeys;
@property (getter=isRetry) bool retry;
@property (retain) NSString *smartCardTokenId;
@property (retain) POExtension *ssoExtension;
@property long long state;
@property bool useSharedDeviceKeys;
@property (retain) NSString *userName;
@property bool userNotified;

- (void).cxx_destruct;
- (int)authMethod;
- (bool)authorizationProvided;
- (id)containerAppBundleIdentifier;
- (id)credentialContext;
- (bool)deviceKeysShouldChange;
- (id)extensionIdentifier;
- (int)failureCount;
- (id)init;
- (bool)isNewUser;
- (bool)isRepair;
- (bool)isRetry;
- (bool)isUserNotification;
- (id)loginUserName;
- (bool)migratingDeviceKeys;
- (long long)options;
- (id)profile;
- (long long)protocolVersion;
- (id)registrationToken;
- (bool)resetKeys;
- (void)setAuthMethod:(int)arg1;
- (void)setAuthorizationProvided:(bool)arg1;
- (void)setContainerAppBundleIdentifier:(id)arg1;
- (void)setCredentialContext:(id)arg1;
- (void)setDeviceKeysShouldChange:(bool)arg1;
- (void)setExtensionIdentifier:(id)arg1;
- (void)setFailureCount:(int)arg1;
- (void)setLoginUserName:(id)arg1;
- (void)setMigratingDeviceKeys:(bool)arg1;
- (void)setNewUser:(bool)arg1;
- (void)setOptions:(long long)arg1;
- (void)setProfile:(id)arg1;
- (void)setProtocolVersion:(long long)arg1;
- (void)setRegistrationToken:(id)arg1;
- (void)setRepair:(bool)arg1;
- (void)setResetKeys:(bool)arg1;
- (void)setRetry:(bool)arg1;
- (void)setSmartCardTokenId:(id)arg1;
- (void)setSsoExtension:(id)arg1;
- (void)setState:(long long)arg1;
- (void)setUseSharedDeviceKeys:(bool)arg1;
- (void)setUserName:(id)arg1;
- (void)setUserNotified:(bool)arg1;
- (id)smartCardTokenId;
- (id)ssoExtension;
- (long long)state;
- (bool)useSharedDeviceKeys;
- (id)userName;
- (bool)userNotified;

@end
