
@interface BWGraph : NSObject {
    NSString * _applicationID;
    bool  _beingConfigured;
    bool  _classicRetainedBufferCount;
    int  _clientPID;
    NSObject<OS_dispatch_group> * _commitGroup;
    unsigned int  _configurationQueuePriority;
    NSMutableArray * _connections;
    bool  _deferredNodePrepareCancelled;
    NSMutableArray * _deferredPreparePrioritySinks;
    NSMutableArray * _deferredStartSourceNodes;
    int  _errorStatus;
    BWMemoryPoolFlushAssertion * _flushAssertion;
    int  _graphStateTransitionTimeoutSeconds;
    bool  _haveStartedOrCancelledDeferredSourceNodes;
    long long  _inflightConfigurationID;
    BWMemoryAnalyticsPayload * _memoryAnalyticsPayload;
    bool  _memoryAnalyticsReportingEnabled;
    BWMemoryPool * _memoryPool;
    NSString * _modeDescription;
    NSMutableArray * _nodes;
    NSArray * _nodesToPrepareAfterGraphStart;
    NSMutableArray * _nodesToPrepareConcurrently;
    NSObject<OS_dispatch_group> * _nonDeferredSourceNodesStartGroup;
    NSMutableArray * _outputsWithSharedPools;
    NSMutableDictionary * _outputsWithSharedPoolsForAttachedMedia;
    bool  _resumesConnectionsAsNodesArePrepared;
    bool  _running;
    bool  _runningForContinuityCapture;
    NSMutableArray * _sinkNodes;
    NSString * _sourceDescription;
    NSMutableArray * _sourceNodes;
    NSObject<OS_dispatch_group> * _sourceNodesStartGroup;
    NSObject<OS_dispatch_queue> * _sourceStartQueue;
    NSObject<OS_dispatch_group> * _startGroup;
    <BWGraphStatusDelegate> * _statusDelegate;
    bool  _supportsLiveReconfiguration;
}

@property (nonatomic, readonly) bool deferredNodePrepareEnabled;
@property int errorStatus;
@property (nonatomic, readonly) BWMemoryAnalyticsPayload *memoryAnalyticsPayload;
@property (nonatomic) bool memoryAnalyticsReportingEnabled;
@property (nonatomic, retain) BWMemoryPool *memoryPool;
@property (nonatomic) bool resumesConnectionsAsNodesArePrepared;
@property (getter=isRunningForContinuityCapture, nonatomic, readonly) bool runningForContinuityCapture;
@property (nonatomic) <BWGraphStatusDelegate> *statusDelegate;
@property (nonatomic, readonly) bool supportsLiveReconfiguration;

+ (void)initialize;

- (id)_breadthFirstEnumerator;
- (id)_depthFirstEnumeratorWithVertexOrdering:(int)arg1;
- (bool)_resolveFormats:(id*)arg1;
- (id)_reverseBreadthFirstEnumerator;
- (id)_reverseDepthFirstEnumeratorWithVertexOrdering:(int)arg1;
- (id)_sinkNodes;
- (id)_sourceNodes;
- (bool)addNode:(id)arg1 error:(id*)arg2;
- (id)applicationID;
- (void)beginConfiguration;
- (void)cancelDeferredNodePrepare;
- (void)cancelDeferredSourceNodeStart;
- (int)clientPID;
- (bool)commitConfigurationWithID:(long long)arg1 error:(id*)arg2;
- (bool)connectOutput:(id)arg1 toInput:(id)arg2 pipelineStage:(id)arg3;
- (void)dealloc;
- (bool)deferredNodePrepareEnabled;
- (id)dotString;
- (void)enableConcurrentPrepareForNode:(id)arg1;
- (void)enableDeferredPrepareForNodesNotInPathOfSinkNode:(id)arg1;
- (void)enableDeferredStartForSourceNode:(id)arg1;
- (int)errorStatus;
- (id)init;
- (id)initWithConfigurationQueuePriority:(unsigned int)arg1;
- (bool)isRunningForContinuityCapture;
- (id)memoryAnalyticsPayload;
- (bool)memoryAnalyticsReportingEnabled;
- (id)memoryPool;
- (id)modeDescription;
- (void)notifyWhenNonDeferredSourceNodesHaveStarted:(id /* block */)arg1;
- (bool)resumesConnectionsAsNodesArePrepared;
- (void)setApplicationID:(id)arg1;
- (void)setClientPID:(int)arg1;
- (void)setErrorStatus:(int)arg1;
- (void)setMemoryAnalyticsReportingEnabled:(bool)arg1;
- (void)setMemoryPool:(id)arg1;
- (void)setModeDescription:(id)arg1;
- (void)setResumesConnectionsAsNodesArePrepared:(bool)arg1;
- (void)setSourceDescription:(id)arg1;
- (void)setStatusDelegate:(id)arg1;
- (id)sourceDescription;
- (bool)start:(id*)arg1;
- (void)startDeferredNodePrepareIfNeededWithCompletionHandler:(id /* block */)arg1;
- (void)startDeferredSourceNodesIfNeeded;
- (id)statusDelegate;
- (bool)stop:(id*)arg1;
- (bool)supportsLiveReconfiguration;
- (void)waitForNonDeferredSourceNodesToStart;
- (void)waitForStartOrCommitToComplete;

@end
