
@interface SSDateFormatManager : NSObject {
    NSDateIntervalFormatter * _allDayDateFormatter;
    CNDateComponentsFormatter * _birthdayDateComponentsFormatter;
    NSCalendar * _calendar;
    NSDateComponentsFormatter * _dateComponentsFormatter;
    NSDateFormatter * _dateFormatter;
    NSDateIntervalFormatter * _dateIntervalFormatter;
    NSDateFormatter * _dayOfWeekFormatter;
    NSDateIntervalFormatter * _mediumDayOfWeekDateIntervalFormatter;
    NSDateIntervalFormatter * _mediumDayOfWeekDateTimeIntervalFormatter;
    NSDateFormatter * _mediumRelativeDateFormatter;
    NSDateComponents * _oneDayComponents;
    NSLocale * _overrideLocale;
    NSDateIntervalFormatter * _shortDateIntervalFormatter;
    NSDateFormatter * _shortDateTimeFormatter;
    NSDateIntervalFormatter * _shortDateTimeIntervalFormatter;
    NSDateFormatter * _shortDayOfWeekFormatter;
    NSDateFormatter * _shortRelativeDateFormatter;
    NSDateFormatter * _shortTimeFormatter;
}

@property (retain) NSDateIntervalFormatter *allDayDateFormatter;
@property (retain) CNDateComponentsFormatter *birthdayDateComponentsFormatter;
@property (retain) NSCalendar *calendar;
@property (retain) NSDateComponentsFormatter *dateComponentsFormatter;
@property (retain) NSDateFormatter *dateFormatter;
@property (retain) NSDateIntervalFormatter *dateIntervalFormatter;
@property (retain) NSDateFormatter *dayOfWeekFormatter;
@property (retain) NSDateIntervalFormatter *mediumDayOfWeekDateIntervalFormatter;
@property (retain) NSDateIntervalFormatter *mediumDayOfWeekDateTimeIntervalFormatter;
@property (retain) NSDateFormatter *mediumRelativeDateFormatter;
@property (retain) NSDateComponents *oneDayComponents;
@property (retain) NSLocale *overrideLocale;
@property (retain) NSDateIntervalFormatter *shortDateIntervalFormatter;
@property (retain) NSDateFormatter *shortDateTimeFormatter;
@property (retain) NSDateIntervalFormatter *shortDateTimeIntervalFormatter;
@property (retain) NSDateFormatter *shortDayOfWeekFormatter;
@property (retain) NSDateFormatter *shortRelativeDateFormatter;
@property (retain) NSDateFormatter *shortTimeFormatter;

+ (id)allDayDateFormatter;
+ (id)calendar;
+ (bool)date:(id)arg1 isBetweenDate:(id)arg2 andDate:(id)arg3;
+ (id)dateCompletedStringFormat;
+ (id)dateCreatedStringFormat;
+ (id)dateDueStringFormat;
+ (id)dateFormatter;
+ (id)dateIntervalFormatter;
+ (id)dateLastCalledStringFormat;
+ (id)dateLastOpenedStringFormat;
+ (id)dateLastPlayedStringFormat;
+ (id)dateModifiedStringFormat;
+ (id)dyanmicStringFromDate:(id)arg1;
+ (id)dynamicCompactStringFromDate:(id)arg1;
+ (id)dynamicDateTimeStringsFromDate:(id)arg1;
+ (id)dynamicMediumStringFromDate:(id)arg1;
+ (id)dynamicStringFromDate:(id)arg1 isCompact:(bool)arg2;
+ (bool)hasRelativeFormatForDate:(id)arg1;
+ (id)icalConformingStringFromDate:(id)arg1;
+ (void)initialize;
+ (bool)isDate:(id)arg1 withinTimeInterval:(double)arg2 includePast:(bool)arg3;
+ (bool)isDateWithinMonthsTime:(id)arg1;
+ (bool)isDateWithinWeeksTime:(id)arg1;
+ (id)mediumDayOfWeekDateTimeIntervalFormatter;
+ (id)nextUpcomingDateForDateComponents:(id)arg1 fromDate:(id)arg2;
+ (void)overrideLocale:(id)arg1;
+ (id)shortDateTimeFormatter;
+ (id)shortDateTimeStringFromDate:(id)arg1 isAllDay:(bool)arg2;
+ (id)shortDateTimeStringFromDate:(id)arg1 isAllDay:(bool)arg2 showAllDayString:(bool)arg3;
+ (id)stringFromBirthdayComponents:(id)arg1;
+ (id)stringFromTimeInterval:(double)arg1;
+ (id)stringsFromDate:(id)arg1 toDate:(id)arg2 isAllDay:(bool)arg3;
+ (id)tomorrow;

- (void).cxx_destruct;
- (id)allDayDateFormatter;
- (id)birthdayDateComponentsFormatter;
- (id)calendar;
- (id)dateComponentsFormatter;
- (id)dateFormatter;
- (id)dateIntervalFormatter;
- (id)dayOfWeekFormatter;
- (id)init;
- (id)mediumDayOfWeekDateIntervalFormatter;
- (id)mediumDayOfWeekDateTimeIntervalFormatter;
- (id)mediumRelativeDateFormatter;
- (id)oneDayComponents;
- (id)overrideLocale;
- (void)setAllDayDateFormatter:(id)arg1;
- (void)setBirthdayDateComponentsFormatter:(id)arg1;
- (void)setCalendar:(id)arg1;
- (void)setDateComponentsFormatter:(id)arg1;
- (void)setDateFormatter:(id)arg1;
- (void)setDateIntervalFormatter:(id)arg1;
- (void)setDayOfWeekFormatter:(id)arg1;
- (void)setMediumDayOfWeekDateIntervalFormatter:(id)arg1;
- (void)setMediumDayOfWeekDateTimeIntervalFormatter:(id)arg1;
- (void)setMediumRelativeDateFormatter:(id)arg1;
- (void)setOneDayComponents:(id)arg1;
- (void)setOverrideLocale:(id)arg1;
- (void)setShortDateIntervalFormatter:(id)arg1;
- (void)setShortDateTimeFormatter:(id)arg1;
- (void)setShortDateTimeIntervalFormatter:(id)arg1;
- (void)setShortDayOfWeekFormatter:(id)arg1;
- (void)setShortRelativeDateFormatter:(id)arg1;
- (void)setShortTimeFormatter:(id)arg1;
- (void)setupFormatters;
- (void)setupFormattersWithTemplate;
- (id)shortDateIntervalFormatter;
- (id)shortDateTimeFormatter;
- (id)shortDateTimeIntervalFormatter;
- (id)shortDayOfWeekFormatter;
- (id)shortRelativeDateFormatter;
- (id)shortTimeFormatter;

@end
