
@interface PPRankableSocialHighlight : PBCodable <BMStoreData, MLFeatureProvider, NSCopying> {
    NSMutableArray * _applicationIdentifiers;
    NSString * _attributionIdentifier;
    NSString * _batchIdentifier;
    NSMutableArray * _calculatedFeatures;
    NSString * _clientIdentifier;
    NSString * _collaborationIdentifier;
    double  _contentCreationSecondsSinceReferenceDate;
    NSString * _contentDisplayName;
    NSString * _contentType;
    NSString * _displayName;
    NSString * _domainIdentifier;
    NSString * _fileProviderId;
    double  _firstPassScore;
    bool  _fromMeEntitlementOverrideIsPresent;
    NSString * _groupPhotoPathDigest;
    NSData * _handleToIdentityMap;
    struct { 
        unsigned int contentCreationSecondsSinceReferenceDate : 1; 
        unsigned int firstPassScore : 1; 
        unsigned int rankingSecondsSinceReferenceDate : 1; 
        unsigned int score : 1; 
        unsigned int syndicationSecondsSinceReferenceDate : 1; 
        unsigned int topKScore : 1; 
        unsigned int highlightType : 1; 
        unsigned int rank : 1; 
        unsigned int fromMeEntitlementOverrideIsPresent : 1; 
        unsigned int isCollaboration : 1; 
        unsigned int isConversationAutoDonating : 1; 
        unsigned int isPrimary : 1; 
        unsigned int isTopKResult : 1; 
    }  _has;
    NSString * _highlightIdentifier;
    int  _highlightType;
    bool  _isCollaboration;
    bool  _isConversationAutoDonating;
    bool  _isPrimary;
    bool  _isTopKResult;
    NSData * _localIdentity;
    NSData * _localIdentityProof;
    NSString * _originatingDeviceId;
    unsigned int  _rank;
    double  _rankingSecondsSinceReferenceDate;
    NSString * _resolvedUrl;
    NSString * _resourceUrl;
    double  _score;
    PPSocialHighlightContact * _sender;
    NSString * _sourceBundleId;
    double  _syndicationSecondsSinceReferenceDate;
    double  _topKScore;
    NSString * _variant;
}

@property (nonatomic, retain) NSMutableArray *applicationIdentifiers;
@property (nonatomic, retain) NSString *attributionIdentifier;
@property (nonatomic, retain) NSString *batchIdentifier;
@property (nonatomic, retain) NSMutableArray *calculatedFeatures;
@property (nonatomic, retain) NSString *clientIdentifier;
@property (nonatomic, retain) NSString *collaborationIdentifier;
@property (nonatomic) double contentCreationSecondsSinceReferenceDate;
@property (nonatomic, retain) NSString *contentDisplayName;
@property (nonatomic, retain) NSString *contentType;
@property (nonatomic, readonly) unsigned int dataVersion;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *displayName;
@property (nonatomic, retain) NSString *domainIdentifier;
@property (nonatomic, readonly) NSSet *featureNames;
@property (nonatomic, retain) NSString *fileProviderId;
@property (nonatomic) double firstPassScore;
@property (nonatomic) bool fromMeEntitlementOverrideIsPresent;
@property (nonatomic, retain) NSString *groupPhotoPathDigest;
@property (nonatomic, retain) NSData *handleToIdentityMap;
@property (nonatomic, readonly) bool hasAttributionIdentifier;
@property (nonatomic, readonly) bool hasBatchIdentifier;
@property (nonatomic, readonly) bool hasClientIdentifier;
@property (nonatomic, readonly) bool hasCollaborationIdentifier;
@property (nonatomic) bool hasContentCreationSecondsSinceReferenceDate;
@property (nonatomic, readonly) bool hasContentDisplayName;
@property (nonatomic, readonly) bool hasContentType;
@property (nonatomic, readonly) bool hasDisplayName;
@property (nonatomic, readonly) bool hasDomainIdentifier;
@property (nonatomic, readonly) bool hasFileProviderId;
@property (nonatomic) bool hasFirstPassScore;
@property (nonatomic) bool hasFromMeEntitlementOverrideIsPresent;
@property (nonatomic, readonly) bool hasGroupPhotoPathDigest;
@property (nonatomic, readonly) bool hasHandleToIdentityMap;
@property (nonatomic, readonly) bool hasHighlightIdentifier;
@property (nonatomic) bool hasHighlightType;
@property (nonatomic) bool hasIsCollaboration;
@property (nonatomic) bool hasIsConversationAutoDonating;
@property (nonatomic) bool hasIsPrimary;
@property (nonatomic) bool hasIsTopKResult;
@property (nonatomic, readonly) bool hasLocalIdentity;
@property (nonatomic, readonly) bool hasLocalIdentityProof;
@property (nonatomic, readonly) bool hasOriginatingDeviceId;
@property (nonatomic) bool hasRank;
@property (nonatomic) bool hasRankingSecondsSinceReferenceDate;
@property (nonatomic, readonly) bool hasResolvedUrl;
@property (nonatomic, readonly) bool hasResourceUrl;
@property (nonatomic) bool hasScore;
@property (nonatomic, readonly) bool hasSender;
@property (nonatomic, readonly) bool hasSourceBundleId;
@property (nonatomic) bool hasSyndicationSecondsSinceReferenceDate;
@property (nonatomic) bool hasTopKScore;
@property (nonatomic, readonly) bool hasVariant;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *highlightIdentifier;
@property (nonatomic) int highlightType;
@property (nonatomic) bool isCollaboration;
@property (nonatomic) bool isConversationAutoDonating;
@property (nonatomic) bool isPrimary;
@property (nonatomic) bool isTopKResult;
@property (nonatomic, retain) NSData *localIdentity;
@property (nonatomic, retain) NSData *localIdentityProof;
@property (nonatomic, retain) NSString *originatingDeviceId;
@property (nonatomic) unsigned int rank;
@property (nonatomic) double rankingSecondsSinceReferenceDate;
@property (nonatomic, retain) NSString *resolvedUrl;
@property (nonatomic, retain) NSString *resourceUrl;
@property (nonatomic) double score;
@property (nonatomic, retain) PPSocialHighlightContact *sender;
@property (nonatomic, retain) NSString *sourceBundleId;
@property (readonly) Class superclass;
@property (nonatomic) double syndicationSecondsSinceReferenceDate;
@property (nonatomic) double topKScore;
@property (nonatomic, retain) NSString *variant;

+ (Class)applicationIdentifiersType;
+ (Class)calculatedFeaturesType;
+ (id)eventWithData:(id)arg1 dataVersion:(unsigned int)arg2;

- (void).cxx_destruct;
- (int)StringAsHighlightType:(id)arg1;
- (void)addApplicationIdentifiers:(id)arg1;
- (void)addCalculatedFeatures:(id)arg1;
- (id)applicationIdentifiers;
- (id)applicationIdentifiersAtIndex:(unsigned long long)arg1;
- (unsigned long long)applicationIdentifiersCount;
- (id)attributionIdentifier;
- (id)batchIdentifier;
- (id)calculatedFeatureValueForKey:(id)arg1;
- (id)calculatedFeatures;
- (id)calculatedFeaturesAtIndex:(unsigned long long)arg1;
- (unsigned long long)calculatedFeaturesCount;
- (void)clearApplicationIdentifiers;
- (void)clearCalculatedFeatures;
- (id)clientIdentifier;
- (id)collaborationIdentifier;
- (double)contentCreationSecondsSinceReferenceDate;
- (id)contentDisplayName;
- (id)contentType;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned int)dataVersion;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayName;
- (id)domainIdentifier;
- (id)featureNames;
- (id)featureValueForName:(id)arg1;
- (id)features;
- (id)fileProviderId;
- (double)firstPassScore;
- (bool)fromMeEntitlementOverrideIsPresent;
- (id)groupPhotoPathDigest;
- (id)handleToIdentityMap;
- (bool)hasAttributionIdentifier;
- (bool)hasBatchIdentifier;
- (bool)hasClientIdentifier;
- (bool)hasCollaborationIdentifier;
- (bool)hasContentCreationSecondsSinceReferenceDate;
- (bool)hasContentDisplayName;
- (bool)hasContentType;
- (bool)hasDisplayName;
- (bool)hasDomainIdentifier;
- (bool)hasFileProviderId;
- (bool)hasFirstPassScore;
- (bool)hasFromMeEntitlementOverrideIsPresent;
- (bool)hasGroupPhotoPathDigest;
- (bool)hasHandleToIdentityMap;
- (bool)hasHighlightIdentifier;
- (bool)hasHighlightType;
- (bool)hasIsCollaboration;
- (bool)hasIsConversationAutoDonating;
- (bool)hasIsPrimary;
- (bool)hasIsTopKResult;
- (bool)hasLocalIdentity;
- (bool)hasLocalIdentityProof;
- (bool)hasOriginatingDeviceId;
- (bool)hasRank;
- (bool)hasRankingSecondsSinceReferenceDate;
- (bool)hasResolvedUrl;
- (bool)hasResourceUrl;
- (bool)hasScore;
- (bool)hasSender;
- (bool)hasSourceBundleId;
- (bool)hasSyndicationSecondsSinceReferenceDate;
- (bool)hasTopKScore;
- (bool)hasVariant;
- (unsigned long long)hash;
- (id)highlightIdentifier;
- (int)highlightType;
- (id)highlightTypeAsString:(int)arg1;
- (bool)isCollaboration;
- (bool)isConversationAutoDonating;
- (bool)isEqual:(id)arg1;
- (bool)isPrimary;
- (bool)isTopKResult;
- (id)json;
- (id)localIdentity;
- (id)localIdentityProof;
- (void)mergeFrom:(id)arg1;
- (id)originatingDeviceId;
- (unsigned int)rank;
- (double)rankingSecondsSinceReferenceDate;
- (bool)readFrom:(id)arg1;
- (id)resolvedUrl;
- (id)resourceUrl;
- (double)score;
- (id)sender;
- (id)serialize;
- (void)setApplicationIdentifiers:(id)arg1;
- (void)setAttributionIdentifier:(id)arg1;
- (void)setBatchIdentifier:(id)arg1;
- (void)setCalculatedFeatures:(id)arg1;
- (void)setCalculatedFeaturesFromDictionary:(id)arg1;
- (void)setClientIdentifier:(id)arg1;
- (void)setCollaborationIdentifier:(id)arg1;
- (void)setContentCreationSecondsSinceReferenceDate:(double)arg1;
- (void)setContentDisplayName:(id)arg1;
- (void)setContentType:(id)arg1;
- (void)setDisplayName:(id)arg1;
- (void)setDomainIdentifier:(id)arg1;
- (void)setFileProviderId:(id)arg1;
- (void)setFirstPassScore:(double)arg1;
- (void)setFromMeEntitlementOverrideIsPresent:(bool)arg1;
- (void)setGroupPhotoPathDigest:(id)arg1;
- (void)setHandleToIdentityMap:(id)arg1;
- (void)setHasContentCreationSecondsSinceReferenceDate:(bool)arg1;
- (void)setHasFirstPassScore:(bool)arg1;
- (void)setHasFromMeEntitlementOverrideIsPresent:(bool)arg1;
- (void)setHasHighlightType:(bool)arg1;
- (void)setHasIsCollaboration:(bool)arg1;
- (void)setHasIsConversationAutoDonating:(bool)arg1;
- (void)setHasIsPrimary:(bool)arg1;
- (void)setHasIsTopKResult:(bool)arg1;
- (void)setHasRank:(bool)arg1;
- (void)setHasRankingSecondsSinceReferenceDate:(bool)arg1;
- (void)setHasScore:(bool)arg1;
- (void)setHasSyndicationSecondsSinceReferenceDate:(bool)arg1;
- (void)setHasTopKScore:(bool)arg1;
- (void)setHighlightIdentifier:(id)arg1;
- (void)setHighlightType:(int)arg1;
- (void)setIsCollaboration:(bool)arg1;
- (void)setIsConversationAutoDonating:(bool)arg1;
- (void)setIsPrimary:(bool)arg1;
- (void)setIsTopKResult:(bool)arg1;
- (void)setLocalIdentity:(id)arg1;
- (void)setLocalIdentityProof:(id)arg1;
- (void)setOriginatingDeviceId:(id)arg1;
- (void)setRank:(unsigned int)arg1;
- (void)setRankingSecondsSinceReferenceDate:(double)arg1;
- (void)setResolvedUrl:(id)arg1;
- (void)setResourceUrl:(id)arg1;
- (void)setScore:(double)arg1;
- (void)setSender:(id)arg1;
- (void)setSourceBundleId:(id)arg1;
- (void)setSyndicationSecondsSinceReferenceDate:(double)arg1;
- (void)setTopKScore:(double)arg1;
- (void)setVariant:(id)arg1;
- (id)sourceBundleId;
- (double)syndicationSecondsSinceReferenceDate;
- (double)topKScore;
- (id)variant;
- (void)writeTo:(id)arg1;

@end
