
@interface _MRAudioFormatProtobuf : PBCodable <NSCopying> {
    NSString * _audioChannelLayoutDescription;
    long long  _bitDepth;
    long long  _bitrate;
    unsigned int  _channelLayout;
    unsigned int  _codec;
    NSString * _groupID;
    struct { 
        unsigned int bitDepth : 1; 
        unsigned int bitrate : 1; 
        unsigned int sampleRate : 1; 
        unsigned int channelLayout : 1; 
        unsigned int codec : 1; 
        unsigned int tier : 1; 
        unsigned int multiChannel : 1; 
        unsigned int spatialized : 1; 
    }  _has;
    bool  _multiChannel;
    long long  _sampleRate;
    bool  _spatialized;
    NSString * _stableVariantID;
    int  _tier;
}

@property (nonatomic, retain) NSString *audioChannelLayoutDescription;
@property (nonatomic) long long bitDepth;
@property (nonatomic) long long bitrate;
@property (nonatomic) unsigned int channelLayout;
@property (nonatomic) unsigned int codec;
@property (nonatomic, retain) NSString *groupID;
@property (nonatomic, readonly) bool hasAudioChannelLayoutDescription;
@property (nonatomic) bool hasBitDepth;
@property (nonatomic) bool hasBitrate;
@property (nonatomic) bool hasChannelLayout;
@property (nonatomic) bool hasCodec;
@property (nonatomic, readonly) bool hasGroupID;
@property (nonatomic) bool hasMultiChannel;
@property (nonatomic) bool hasSampleRate;
@property (nonatomic) bool hasSpatialized;
@property (nonatomic, readonly) bool hasStableVariantID;
@property (nonatomic) bool hasTier;
@property (nonatomic) bool multiChannel;
@property (nonatomic) long long sampleRate;
@property (nonatomic) bool spatialized;
@property (nonatomic, retain) NSString *stableVariantID;
@property (nonatomic) int tier;

- (void).cxx_destruct;
- (int)StringAsTier:(id)arg1;
- (id)audioChannelLayoutDescription;
- (long long)bitDepth;
- (long long)bitrate;
- (unsigned int)channelLayout;
- (unsigned int)codec;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)groupID;
- (bool)hasAudioChannelLayoutDescription;
- (bool)hasBitDepth;
- (bool)hasBitrate;
- (bool)hasChannelLayout;
- (bool)hasCodec;
- (bool)hasGroupID;
- (bool)hasMultiChannel;
- (bool)hasSampleRate;
- (bool)hasSpatialized;
- (bool)hasStableVariantID;
- (bool)hasTier;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)multiChannel;
- (bool)readFrom:(id)arg1;
- (long long)sampleRate;
- (void)setAudioChannelLayoutDescription:(id)arg1;
- (void)setBitDepth:(long long)arg1;
- (void)setBitrate:(long long)arg1;
- (void)setChannelLayout:(unsigned int)arg1;
- (void)setCodec:(unsigned int)arg1;
- (void)setGroupID:(id)arg1;
- (void)setHasBitDepth:(bool)arg1;
- (void)setHasBitrate:(bool)arg1;
- (void)setHasChannelLayout:(bool)arg1;
- (void)setHasCodec:(bool)arg1;
- (void)setHasMultiChannel:(bool)arg1;
- (void)setHasSampleRate:(bool)arg1;
- (void)setHasSpatialized:(bool)arg1;
- (void)setHasTier:(bool)arg1;
- (void)setMultiChannel:(bool)arg1;
- (void)setSampleRate:(long long)arg1;
- (void)setSpatialized:(bool)arg1;
- (void)setStableVariantID:(id)arg1;
- (void)setTier:(int)arg1;
- (bool)spatialized;
- (id)stableVariantID;
- (int)tier;
- (id)tierAsString:(int)arg1;
- (void)writeTo:(id)arg1;

@end
