
@interface MTMaterialSettingsInterpolator : NSObject {
    id /* block */  _blurRadiusTransformer;
    <MTRecipeMaterialSettingsProviding> * _finalSettings;
    <MTRecipeMaterialSettingsProviding> * _initialSettings;
    bool  _overlay;
    double  _previousWeighting;
    double  _weighting;
}

@property (getter=isBackdropRequiredEver, nonatomic, readonly) bool backdropRequiredEver;
@property (getter=isBackdropRequiredFinally, nonatomic, readonly) bool backdropRequiredFinally;
@property (getter=isBackdropRequiredInitially, nonatomic, readonly) bool backdropRequiredInitially;
@property (nonatomic, readonly) double backdropScale;
@property (getter=isBlurAtEnd, nonatomic, readonly) bool blurAtEnd;
@property (getter=isBlurEnabled, nonatomic, readonly) bool blurEnabled;
@property (nonatomic, readonly, copy) NSString *blurInputQuality;
@property (nonatomic, readonly) double blurRadius;
@property (nonatomic, copy) id /* block */ blurRadiusTransformer;
@property (nonatomic, readonly) double brightness;
@property (getter=isBrightnessEnabled, nonatomic, readonly) bool brightnessEnabled;
@property (nonatomic, readonly) struct CAColorMatrix { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; float x17; float x18; float x19; float x20; } colorMatrix;
@property (getter=isColorMatrixEnabled, nonatomic, readonly) bool colorMatrixEnabled;
@property (getter=isCurvesEnabled, nonatomic, readonly) bool curvesEnabled;
@property (nonatomic, readonly, copy) NSDictionary *curvesValues;
@property (nonatomic, retain) <MTRecipeMaterialSettingsProviding> *finalSettings;
@property (nonatomic, retain) <MTRecipeMaterialSettingsProviding> *initialSettings;
@property (nonatomic, readonly) double luminanceAmount;
@property (getter=isLuminanceEnabled, nonatomic, readonly) bool luminanceEnabled;
@property (nonatomic, readonly, copy) NSArray *luminanceValues;
@property (getter=isOverlay, nonatomic, readonly) bool overlay;
@property (nonatomic, readonly) double saturation;
@property (getter=isSaturationEnabled, nonatomic, readonly) bool saturationEnabled;
@property (nonatomic, readonly) double tintAlpha;
@property (nonatomic, readonly, copy) MTColor *tintColor;
@property (getter=isTintEnabled, nonatomic, readonly) bool tintEnabled;
@property (nonatomic) double weighting;
@property (getter=isWeightingChanging, nonatomic, readonly) bool weightingChanging;
@property (nonatomic, readonly) double zoom;
@property (getter=isZoomEnabled, nonatomic, readonly) bool zoomEnabled;

+ (id)_filteringProtocolGetterNames;

- (void).cxx_destruct;
- (id)_backdropScaleWithSettings:(id)arg1;
- (id)_blurRadiusWithSettings:(id)arg1;
- (id)_brightnessWithSettings:(id)arg1;
- (id)_colorMatrixColorWithSettings:(id)arg1 alpha:(double)arg2;
- (id)_colorMatrixWithSettings:(id)arg1;
- (id)_colorWithGetterBlock:(id /* block */)arg1;
- (id)_filteringProperty:(id)arg1 withSettings:(id)arg2;
- (double)_floatPropertyValueForProperty:(id)arg1;
- (double)_floatPropertyValueForProperty:(id)arg1 withTransformer:(id /* block */)arg2;
- (bool)_isBackdropRequiredWithSettings:(id)arg1;
- (bool)_isBackdropRequiredWithSubSettings:(id)arg1;
- (bool)_isPropertyEnabled:(id)arg1 consideringWeighting:(bool)arg2;
- (bool)_isTintEnabledWithSettings:(id)arg1;
- (id)_luminanceAmountWithSettings:(id)arg1;
- (id)_luminanceInputValues;
- (id)_propertyValueForProperty:(id)arg1 withTransformer:(id /* block */)arg2;
- (id)_saturationWithSettings:(id)arg1;
- (id)_tintAlphaWithSettings:(id)arg1;
- (id)_zoomWithSettings:(id)arg1;
- (double)backdropScale;
- (id)blurInputQuality;
- (double)blurRadius;
- (id /* block */)blurRadiusTransformer;
- (double)brightness;
- (struct CAColorMatrix { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; float x17; float x18; float x19; float x20; })colorMatrix;
- (id)curvesValues;
- (id)description;
- (id)finalSettings;
- (void)finalizeWeighting;
- (id)initWithSettings:(id)arg1;
- (id)initialSettings;
- (id)initialSettingsInterpolator;
- (bool)isBackdropRequiredEver;
- (bool)isBackdropRequiredFinally;
- (bool)isBackdropRequiredInitially;
- (bool)isBlurAtEnd;
- (bool)isBlurEnabled;
- (bool)isBrightnessEnabled;
- (bool)isColorMatrixEnabled;
- (bool)isCurvesEnabled;
- (bool)isLuminanceEnabled;
- (bool)isOverlay;
- (bool)isSaturationEnabled;
- (bool)isTintEnabled;
- (bool)isWeightingChanging;
- (bool)isZoomEnabled;
- (double)luminanceAmount;
- (id)luminanceValues;
- (double)saturation;
- (void)setBlurRadiusTransformer:(id /* block */)arg1;
- (void)setFinalSettings:(id)arg1;
- (void)setInitialSettings:(id)arg1;
- (void)setWeighting:(double)arg1;
- (double)tintAlpha;
- (id)tintColor;
- (struct CGImage { }*)variableBlurInputMask;
- (double)weighting;
- (double)zoom;

@end
