
@interface CAMCaptureConfiguration : NSObject {
    long long  _HDRMode;
    long long  _audioConfiguration;
    long long  _device;
    NSDictionary * _exposureBiasesByMode;
    long long  _flashMode;
    long long  _irisMode;
    long long  _macroMode;
    bool  _mirrorFrontCameraCaptures;
    long long  _mode;
    bool  _photoBooth;
    long long  _photoModeAspectRatioCrop;
    long long  _photoModeEffectFilterType;
    double  _portraitModeApertureValue;
    long long  _portraitModeEffectFilterType;
    double  _portraitModeIntensityValue;
    long long  _portraitModeLightingEffectType;
    long long  _proResVideoMode;
    long long  _rawMode;
    unsigned long long  _selectedSemanticStyleIndex;
    NSArray * _semanticStyles;
    long long  _sharedLibraryMode;
    long long  _squareModeEffectFilterType;
    long long  _timerDuration;
    long long  _torchMode;
    long long  _videoConfiguration;
    long long  _videoStabilizationMode;
    bool  _zoomPIPEnabled;
}

@property (nonatomic, readonly) long long HDRMode;
@property (nonatomic, readonly) long long audioConfiguration;
@property (nonatomic, readonly) long long device;
@property (nonatomic, readonly) NSDictionary *exposureBiasesByMode;
@property (nonatomic, readonly) long long flashMode;
@property (nonatomic, readonly) long long irisMode;
@property (nonatomic, readonly) long long macroMode;
@property (nonatomic) bool mirrorFrontCameraCaptures;
@property (nonatomic, readonly) long long mode;
@property (getter=isPhotoBooth, nonatomic, readonly) bool photoBooth;
@property (nonatomic, readonly) long long photoModeAspectRatioCrop;
@property (nonatomic, readonly) long long photoModeEffectFilterType;
@property (nonatomic, readonly) double portraitModeApertureValue;
@property (nonatomic, readonly) long long portraitModeEffectFilterType;
@property (nonatomic, readonly) double portraitModeIntensityValue;
@property (nonatomic, readonly) long long portraitModeLightingEffectType;
@property (nonatomic, readonly) long long proResVideoMode;
@property (nonatomic, readonly) long long rawMode;
@property (nonatomic) unsigned long long selectedSemanticStyleIndex;
@property (nonatomic, retain) NSArray *semanticStyles;
@property (nonatomic) long long sharedLibraryMode;
@property (nonatomic, readonly) long long squareModeEffectFilterType;
@property (nonatomic, readonly) long long timerDuration;
@property (nonatomic, readonly) long long torchMode;
@property (nonatomic, readonly) long long videoConfiguration;
@property (nonatomic, readonly) long long videoStabilizationMode;
@property (nonatomic, readonly) bool zoomPIPEnabled;

+ (long long)_fallbackVideoConfigurationForUnsupportedConfiguration:(long long)arg1;
+ (long long)audioConfigurationForMode:(long long)arg1 device:(long long)arg2 emulationMode:(long long)arg3 duringCall:(bool)arg4 forceMonoAudioRecording:(bool)arg5;
+ (id)captureGraphConfigurationUsingConfiguration:(id)arg1 outputToExternalStorage:(bool)arg2;
+ (id)configuration:(id)arg1 withDevice:(long long)arg2;
+ (long long)sanitizeVideoConfigurationForDesiredConfiguration:(long long)arg1 mode:(long long)arg2 device:(long long)arg3;
+ (id)tinyConfigurationForConfiguration:(id)arg1 preserveFilters:(bool)arg2;

- (void).cxx_destruct;
- (long long)HDRMode;
- (id)_previewFilters;
- (long long)audioConfiguration;
- (long long)device;
- (id)exposureBiasesByMode;
- (long long)flashMode;
- (id)initForPhotoBoothWithCaptureDevice:(long long)arg1;
- (id)initWithCaptureMode:(long long)arg1 captureDevice:(long long)arg2 videoConfiguration:(long long)arg3 audioConfiguration:(long long)arg4 flashMode:(long long)arg5 torchMode:(long long)arg6 HDRMode:(long long)arg7 irisMode:(long long)arg8 timerDuration:(long long)arg9 photoModeAspectRatioCrop:(long long)arg10 photoModeEffectFilterType:(long long)arg11 squareModeEffectFilterType:(long long)arg12 portraitModeEffectFilterType:(long long)arg13 portraitModeLightingEffectType:(long long)arg14 portraitModeApertureValue:(double)arg15 portraitModeIntensityValue:(double)arg16 mirrorFrontCameraCaptures:(bool)arg17 exposureBiasesByMode:(id)arg18 macroMode:(long long)arg19 rawMode:(long long)arg20 proResVideoMode:(long long)arg21 semanticStyles:(id)arg22 selectedSemanticStyleIndex:(unsigned long long)arg23 videoStabilizationMode:(long long)arg24 zoomPIPEnabled:(bool)arg25 sharedLibraryMode:(long long)arg26;
- (id)initWithConfiguration:(id)arg1;
- (long long)irisMode;
- (bool)isPhotoBooth;
- (long long)macroMode;
- (bool)mirrorFrontCameraCaptures;
- (long long)mode;
- (long long)photoModeAspectRatioCrop;
- (long long)photoModeEffectFilterType;
- (double)portraitModeApertureValue;
- (long long)portraitModeEffectFilterType;
- (double)portraitModeIntensityValue;
- (long long)portraitModeLightingEffectType;
- (long long)proResVideoMode;
- (long long)rawMode;
- (unsigned long long)selectedSemanticStyleIndex;
- (id)semanticStyles;
- (void)setMirrorFrontCameraCaptures:(bool)arg1;
- (void)setSelectedSemanticStyleIndex:(unsigned long long)arg1;
- (void)setSemanticStyles:(id)arg1;
- (void)setSharedLibraryMode:(long long)arg1;
- (long long)sharedLibraryMode;
- (long long)squareModeEffectFilterType;
- (long long)timerDuration;
- (long long)torchMode;
- (long long)videoConfiguration;
- (long long)videoStabilizationMode;
- (bool)zoomPIPEnabled;

@end
