
@interface CAMUserPreferences : NSObject {
    bool  _HDR10BitVideoEnabled;
    bool  _PALVideoEnabled;
    bool  _QRBannersEnabledInSettings;
    long long  _VFRMode;
    long long  __backPreferredHEICPhotoResolution;
    long long  __frontPreferredHEICPhotoResolution;
    bool  __hasReadLastWrittenValues;
    NSDate * __lastViewedSettingsInterfaceDate;
    NSDate * __lastWrittenSettingsDate;
    bool  __preferHEVCWhenAvailable;
    long long  __previewAspectModeForPhotoModes;
    long long  __previewAspectModeForVideoModes;
    double  __resetTimeoutOverride;
    bool  __shouldDisableCameraSwitchingDuringVideoRecording;
    NSUserDefaults * __underlyingUserDefaults;
    bool  _actionModeLowLightEnabled;
    bool  _burstFollowsEncoderSettings;
    bool  _bypassWelcomeScreens;
    CAMCaptureConfiguration * _captureConfiguration;
    long long  _cinematicConfiguration;
    CAMConflictingControlConfiguration * _conflictingControlConfiguration;
    NSArray * _customLensGroup;
    long long  _defaultCustomLens;
    bool  _defaultToSharedLibraryEnabled;
    bool  _didAcknowledgeCTMDescription;
    bool  _didAcknowledgeCinematicModeDescription;
    bool  _didAcknowledgeDepthInPhotoModeDescription;
    bool  _didAcknowledgePortraitModeDescription;
    bool  _didAcknowledgeSemanticStylesDescription;
    bool  _didResetTorchMode;
    bool  _enhancedVideoStabilization;
    long long  _explicitProResColorSpace;
    bool  _forceEnableQRBanners;
    bool  _imageAnalysisEnabled;
    bool  _lockAsShutterEnabled;
    bool  _lowLightVideoEnabled;
    long long  _maximumRAWPhotoResolution;
    bool  _overCapturePreviewEnabled;
    long long  _overriddenBackCaptureInterval;
    long long  _overriddenFrontCaptureInterval;
    bool  _photoFormatControlEnabled;
    struct { 
        long long encoding; 
        long long resolution; 
    }  _photoFormatControlSecondaryFormat;
    long long  _photoModeLastCapturedEffectFilterType;
    long long  _portraitModeLastCapturedEffectFilterType;
    long long  _portraitModeRearDevice;
    double  _portraitModeRearZoomValue;
    long long  _preferredMinimumFreeBytes;
    bool  _preserveAperture;
    bool  _preserveCaptureMode;
    bool  _preserveEffectFilter;
    bool  _preserveExposure;
    bool  _preserveLivePhoto;
    bool  _preserveNightMode;
    bool  _preservePhotoResolution;
    bool  _preservePortraitZoom;
    bool  _preserveProRes;
    bool  _preserveRAW;
    bool  _preserveSuperWideAutoMacro;
    bool  _preserveVideoStabilization;
    bool  _proResControlEnabled;
    bool  _rawControlEnabled;
    NSDate * _resetTimeoutDate;
    bool  _responsiveShutterEnabled;
    bool  _semanticDevelopmentEnabled;
    bool  _shareWhenAtHomeEnabled;
    bool  _sharedLibraryAutoBehaviorEnabled;
    bool  _sharedLibraryEnabled;
    NSDate * _sharedLibraryLastDiscoveryDate;
    CLLocation * _sharedLibraryLastDiscoveryLocation;
    CLLocation * _sharedLibraryLastLocation;
    bool  _sharedLibraryLastLocationAcquiredDuringTrip;
    NSDate * _sharedLibraryLastUserActionDate;
    CLLocation * _sharedLibraryLastUserActionLocation;
    bool  _sharedLibrarySwitchEnabled;
    bool  _shouldCaptureHDREV0;
    bool  _shouldDelayRemotePersistence;
    bool  _shouldForceMonoAudioRecording;
    bool  _shouldLockWhiteBalanceDuringVideoRecording;
    bool  _shouldMirrorFrontCameraCaptures;
    bool  _shouldShowGridView;
    bool  _shouldShowHorizonLevelView;
    bool  _shouldShowLevelView;
    bool  _shouldUseContentAwareDistortionCorrection;
    bool  _shouldUseDepthSuggestionInPhotoMode;
    bool  _shouldUseModernHDRBehavior;
    bool  _shouldUseVolumeUpBurst;
    long long  _slomoConfiguration;
    long long  _squareModeLastCapturedEffectFilterType;
    bool  _superWideAutoMacroControlAllowed;
    long long  _videoConfiguration;
    bool  _videoConfigurationControlEnabled;
    bool  _zoomPIPEnabled;
}

@property (nonatomic, readonly) bool HDR10BitVideoEnabled;
@property (getter=isPALVideoEnabled, nonatomic, readonly) bool PALVideoEnabled;
@property (nonatomic, readonly) bool QRBannersEnabledInSettings;
@property (nonatomic, readonly) long long VFRMode;
@property (nonatomic, readonly) long long _backPreferredHEICPhotoResolution;
@property (nonatomic, readonly) long long _frontPreferredHEICPhotoResolution;
@property (setter=_setHasReadLastWrittenValues:, nonatomic) bool _hasReadLastWrittenValues;
@property (nonatomic, readonly) NSDate *_lastViewedSettingsInterfaceDate;
@property (setter=_setLastWrittenSettingsDate:, nonatomic) NSDate *_lastWrittenSettingsDate;
@property (nonatomic, readonly) bool _preferHEVCWhenAvailable;
@property (setter=_setPreviewAspectModeForPhotoModes:, nonatomic) long long _previewAspectModeForPhotoModes;
@property (setter=_setPreviewAspectModeForVideoModes:, nonatomic) long long _previewAspectModeForVideoModes;
@property (nonatomic, readonly) double _resetTimeoutOverride;
@property (nonatomic, readonly) bool _shouldDisableCameraSwitchingDuringVideoRecording;
@property (getter=_underlyingUserDefaults, setter=_setUnderlyingUserDefaults:, nonatomic, retain) NSUserDefaults *_underlyingUserDefaults;
@property (nonatomic, readonly) bool actionModeLowLightEnabled;
@property (nonatomic, readonly) bool allowExplicitProResColorSpace;
@property (nonatomic, readonly) bool burstFollowsEncoderSettings;
@property (nonatomic, readonly) bool bypassWelcomeScreens;
@property (nonatomic, retain) CAMCaptureConfiguration *captureConfiguration;
@property (nonatomic, readonly) long long cinematicConfiguration;
@property (nonatomic, retain) CAMConflictingControlConfiguration *conflictingControlConfiguration;
@property (nonatomic, readonly) NSArray *customLensGroup;
@property (nonatomic, readonly) long long defaultCustomLens;
@property (nonatomic) bool defaultToSharedLibraryEnabled;
@property (nonatomic) bool didAcknowledgeCTMDescription;
@property (nonatomic) bool didAcknowledgeCinematicModeDescription;
@property (nonatomic) bool didAcknowledgeDepthInPhotoModeDescription;
@property (nonatomic) bool didAcknowledgePortraitModeDescription;
@property (nonatomic) bool didAcknowledgeSemanticStylesDescription;
@property (nonatomic, readonly) bool didConfirmSlomo1080p240MostCompatible;
@property (nonatomic, readonly) bool didConfirmVideo4k60MostCompatible;
@property (setter=_setDidResetTorchMode:, nonatomic) bool didResetTorchMode;
@property (nonatomic, readonly) bool enhancedVideoStabilization;
@property (nonatomic, readonly) long long explicitProResColorSpace;
@property (nonatomic) bool forceEnableQRBanners;
@property (getter=isImageAnalysisEnabled, nonatomic, readonly) bool imageAnalysisEnabled;
@property (getter=isLockAsShutterEnabled, nonatomic, readonly) bool lockAsShutterEnabled;
@property (getter=isLowLightVideoEnabled, nonatomic, readonly) bool lowLightVideoEnabled;
@property (nonatomic, readonly) long long maximumRAWPhotoResolution;
@property (getter=isOverCapturePreviewEnabled, nonatomic, readonly) bool overCapturePreviewEnabled;
@property (nonatomic, readonly) long long overriddenBackCaptureInterval;
@property (nonatomic, readonly) long long overriddenFrontCaptureInterval;
@property (nonatomic, readonly) long long photoEncodingBehavior;
@property (nonatomic, readonly) bool photoFormatControlEnabled;
@property (nonatomic, readonly) struct { long long x1; long long x2; } photoFormatControlSecondaryFormat;
@property (nonatomic) long long photoModeLastCapturedEffectFilterType;
@property (nonatomic) long long portraitModeLastCapturedEffectFilterType;
@property (nonatomic) long long portraitModeRearDevice;
@property (nonatomic) double portraitModeRearZoomValue;
@property (nonatomic, readonly) long long preferredMinimumFreeBytes;
@property (nonatomic, readonly) bool preserveAperture;
@property (nonatomic, readonly) bool preserveCaptureMode;
@property (nonatomic, readonly) bool preserveEffectFilter;
@property (nonatomic, readonly) bool preserveExposure;
@property (nonatomic, readonly) bool preserveLivePhoto;
@property (nonatomic, readonly) bool preserveNightMode;
@property (nonatomic, readonly) bool preservePhotoResolution;
@property (nonatomic, readonly) bool preservePortraitZoom;
@property (nonatomic, readonly) bool preserveProRes;
@property (nonatomic, readonly) bool preserveRAW;
@property (nonatomic, readonly) bool preserveSuperWideAutoMacro;
@property (nonatomic, readonly) bool preserveVideoStabilization;
@property (getter=isProResControlEnabled, nonatomic, readonly) bool proResControlEnabled;
@property (nonatomic, readonly) bool rawControlEnabled;
@property (setter=_setResetTimeoutDate:, nonatomic, retain) NSDate *resetTimeoutDate;
@property (nonatomic, readonly) bool responsiveShutterEnabled;
@property (nonatomic, readonly) bool semanticDevelopmentEnabled;
@property (nonatomic) bool shareWhenAtHomeEnabled;
@property (nonatomic) bool sharedLibraryAutoBehaviorEnabled;
@property (nonatomic) bool sharedLibraryEnabled;
@property (nonatomic, retain) NSDate *sharedLibraryLastDiscoveryDate;
@property (nonatomic, retain) CLLocation *sharedLibraryLastDiscoveryLocation;
@property (nonatomic, retain) CLLocation *sharedLibraryLastLocation;
@property (nonatomic) bool sharedLibraryLastLocationAcquiredDuringTrip;
@property (nonatomic, retain) NSDate *sharedLibraryLastUserActionDate;
@property (nonatomic, retain) CLLocation *sharedLibraryLastUserActionLocation;
@property (nonatomic) bool sharedLibrarySwitchEnabled;
@property (nonatomic, readonly) bool shouldCaptureHDREV0;
@property (nonatomic, readonly) bool shouldDelayRemotePersistence;
@property (nonatomic, readonly) bool shouldForceMonoAudioRecording;
@property (nonatomic, readonly) bool shouldLockWhiteBalanceDuringVideoRecording;
@property (nonatomic) bool shouldMirrorFrontCameraCaptures;
@property (nonatomic) bool shouldShowGridView;
@property (nonatomic, readonly) bool shouldShowHorizonLevelView;
@property (nonatomic, readonly) bool shouldShowLevelView;
@property (nonatomic, readonly) bool shouldShowQRBanners;
@property (nonatomic, readonly) bool shouldUseContentAwareDistortionCorrection;
@property (nonatomic) bool shouldUseDepthSuggestionInPhotoMode;
@property (nonatomic, readonly) bool shouldUseModernHDRBehavior;
@property (nonatomic, readonly) bool shouldUseVolumeUpBurst;
@property (nonatomic, readonly) long long slomoConfiguration;
@property (nonatomic) long long squareModeLastCapturedEffectFilterType;
@property (getter=isSuperWideAutoMacroControlAllowed, nonatomic, readonly) bool superWideAutoMacroControlAllowed;
@property (nonatomic, readonly) bool usingMostCompatibleEncoding;
@property (nonatomic, readonly) long long videoConfiguration;
@property (getter=isVideoConfigurationControlEnabled, nonatomic, readonly) bool videoConfigurationControlEnabled;
@property (getter=isZoomPIPEnabled, nonatomic, readonly) bool zoomPIPEnabled;

+ (id)_defaultExposureBiasesByMode;
+ (bool)_fallBackToCameraDefaultsForBundleIdentifier:(id)arg1;
+ (id)defaultCaptureConfiguration;
+ (long long)defaultDevice;
+ (long long)defaultDevicePosition;
+ (long long)defaultFilterTypeForMode:(long long)arg1;
+ (long long)defaultLightingTypeForMode:(long long)arg1;
+ (long long)defaultMode;
+ (bool)hasSharedLibraryAlgorithmsPreferences;
+ (bool)isSharedLibrarySupportedAndEnabledForCapabilities:(id)arg1;
+ (void)performApertureMigrationWithCapabilities:(id)arg1;
+ (void)performHorizonLevelUpgradeWithCapabilities:(id)arg1;
+ (void)performLowLightVideoMigrationWithCapabilities:(id)arg1;
+ (void)performResponsiveShutterMigrationWithCapabilities:(id)arg1;
+ (void)performSuperWideAutoMacroMigrationWithCapabilities:(id)arg1;
+ (id)preferences;
+ (void)removeSharedLibraryAlgorithmsPreferences;
+ (bool)shouldEnableHDR10BitVideoForHEVCEnabled:(bool)arg1 capabilities:(id)arg2;
+ (void)updateLastViewedSettingsDate;

- (void).cxx_destruct;
- (bool)HDR10BitVideoEnabled;
- (bool)QRBannersEnabledInSettings;
- (long long)VFRMode;
- (long long)_backPreferredHEICPhotoResolution;
- (long long)_frontPreferredHEICPhotoResolution;
- (bool)_hasReadLastWrittenValues;
- (id)_lastViewedSettingsInterfaceDate;
- (id)_lastWrittenSettingsDate;
- (bool)_preferHEVCWhenAvailable;
- (long long)_previewAspectModeForPhotoModes;
- (long long)_previewAspectModeForVideoModes;
- (void)_publishAnalyticsIfNeeded;
- (void)_resetSharedLibraryAlgorithmsPreferences;
- (double)_resetTimeoutOverride;
- (double)_resetTimeoutSeconds;
- (long long)_sanitizeEffectFilterType:(long long)arg1 forMode:(long long)arg2;
- (long long)_sanitizeLightingType:(long long)arg1 forMode:(long long)arg2;
- (void)_setDidResetTorchMode:(bool)arg1;
- (void)_setHasReadLastWrittenValues:(bool)arg1;
- (void)_setLastWrittenSettingsDate:(id)arg1;
- (void)_setPreviewAspectModeForPhotoModes:(long long)arg1;
- (void)_setPreviewAspectModeForVideoModes:(long long)arg1;
- (void)_setResetTimeoutDate:(id)arg1;
- (void)_setUnderlyingUserDefaults:(id)arg1;
- (bool)_shouldDisableCameraSwitchingDuringVideoRecording;
- (bool)_shouldReconfigureCurrentConfigurationForSettingsChange;
- (bool)_shouldResetPreferencesForTimeout;
- (id)_underlyingUserDefaults;
- (void)_updateLastWrittenSettingsDate;
- (bool)actionModeLowLightEnabled;
- (bool)allowExplicitProResColorSpace;
- (bool)burstFollowsEncoderSettings;
- (bool)bypassWelcomeScreens;
- (id)captureConfiguration;
- (long long)cinematicConfiguration;
- (long long)colorSpaceForMode:(long long)arg1 videoConfiguration:(long long)arg2 videoEncodingBehavior:(long long)arg3;
- (id)conflictingControlConfiguration;
- (id)customLensGroup;
- (long long)defaultCustomLens;
- (long long)defaultDeviceForModeChange:(long long)arg1 devicePosition:(long long)arg2;
- (bool)defaultToSharedLibraryEnabled;
- (double)defaultZoomFactorForGraphConfiguration:(id)arg1 captureOrientation:(long long)arg2 outputToExternalStorage:(bool)arg3;
- (bool)didAcknowledgeCTMDescription;
- (bool)didAcknowledgeCinematicModeDescription;
- (bool)didAcknowledgeDepthInPhotoModeDescription;
- (bool)didAcknowledgePortraitModeDescription;
- (bool)didAcknowledgeSemanticStylesDescription;
- (bool)didConfirmSlomo1080p240MostCompatible;
- (bool)didConfirmVideo4k60MostCompatible;
- (bool)didResetTorchMode;
- (bool)enhancedVideoStabilization;
- (long long)explicitProResColorSpace;
- (id)filterTypesForMode:(long long)arg1;
- (bool)forceEnableQRBanners;
- (bool)isAutoFPSVideoEnabledForMode:(long long)arg1 device:(long long)arg2 videoConfiguration:(long long)arg3 encodingBehavior:(long long)arg4 outputToExternalStorage:(bool)arg5;
- (bool)isImageAnalysisEnabled;
- (bool)isLockAsShutterEnabled;
- (bool)isLowLightVideoEnabled;
- (bool)isOverCapturePreviewEnabled;
- (bool)isPALVideoEnabled;
- (bool)isProResControlEnabled;
- (bool)isSuperWideAutoMacroControlAllowed;
- (bool)isVideoConfigurationControlEnabled;
- (bool)isZoomPIPEnabled;
- (long long)maximumPhotoResolutionForMode:(long long)arg1 device:(long long)arg2;
- (long long)maximumRAWPhotoResolution;
- (bool)mirrorCameraCapturesForDevicePosition:(long long)arg1 mode:(long long)arg2;
- (long long)overriddenBackCaptureInterval;
- (long long)overriddenFrontCaptureInterval;
- (long long)photoEncodingBehavior;
- (bool)photoFormatControlEnabled;
- (struct { long long x1; long long x2; })photoFormatControlSecondaryFormat;
- (long long)photoModeLastCapturedEffectFilterType;
- (long long)portraitModeLastCapturedEffectFilterType;
- (long long)portraitModeRearDevice;
- (double)portraitModeRearZoomValue;
- (long long)ppt_readPortraitLightingType;
- (long long)preferredHEICPhotoResolutionForDevicePosition:(long long)arg1;
- (long long)preferredMinimumFreeBytes;
- (bool)preserveAperture;
- (bool)preserveCaptureMode;
- (bool)preserveEffectFilter;
- (bool)preserveExposure;
- (bool)preserveLivePhoto;
- (bool)preserveNightMode;
- (bool)preservePhotoResolution;
- (bool)preservePortraitZoom;
- (bool)preserveProRes;
- (bool)preserveRAW;
- (bool)preserveSuperWideAutoMacro;
- (bool)preserveVideoStabilization;
- (long long)previewViewAspectModeForMode:(long long)arg1;
- (bool)rawControlEnabled;
- (bool)readPreferencesWithOverrides:(id)arg1 emulationMode:(long long)arg2 callActive:(bool)arg3 shouldResetCaptureConfiguration:(bool*)arg4;
- (id)resetTimeoutDate;
- (bool)responsiveShutterEnabled;
- (bool)semanticDevelopmentEnabled;
- (void)setCaptureConfiguration:(id)arg1;
- (void)setConflictingControlConfiguration:(id)arg1;
- (void)setDefaultToSharedLibraryEnabled:(bool)arg1;
- (void)setDidAcknowledgeCTMDescription:(bool)arg1;
- (void)setDidAcknowledgeCinematicModeDescription:(bool)arg1;
- (void)setDidAcknowledgeDepthInPhotoModeDescription:(bool)arg1;
- (void)setDidAcknowledgePortraitModeDescription:(bool)arg1;
- (void)setDidAcknowledgeSemanticStylesDescription:(bool)arg1;
- (void)setForceEnableQRBanners:(bool)arg1;
- (void)setPhotoModeLastCapturedEffectFilterType:(long long)arg1;
- (void)setPortraitModeLastCapturedEffectFilterType:(long long)arg1;
- (void)setPortraitModeRearDevice:(long long)arg1;
- (void)setPortraitModeRearZoomValue:(double)arg1;
- (void)setPreviewViewAspectMode:(long long)arg1 forMode:(long long)arg2;
- (void)setShareWhenAtHomeEnabled:(bool)arg1;
- (void)setSharedLibraryAutoBehaviorEnabled:(bool)arg1;
- (void)setSharedLibraryEnabled:(bool)arg1;
- (void)setSharedLibraryLastDiscoveryDate:(id)arg1;
- (void)setSharedLibraryLastDiscoveryLocation:(id)arg1;
- (void)setSharedLibraryLastLocation:(id)arg1;
- (void)setSharedLibraryLastLocationAcquiredDuringTrip:(bool)arg1;
- (void)setSharedLibraryLastUserActionDate:(id)arg1;
- (void)setSharedLibraryLastUserActionLocation:(id)arg1;
- (void)setSharedLibrarySwitchEnabled:(bool)arg1;
- (void)setShouldMirrorFrontCameraCaptures:(bool)arg1;
- (void)setShouldShowGridView:(bool)arg1;
- (void)setShouldUseDepthSuggestionInPhotoMode:(bool)arg1;
- (void)setSquareModeLastCapturedEffectFilterType:(long long)arg1;
- (bool)shareWhenAtHomeEnabled;
- (bool)sharedLibraryAutoBehaviorEnabled;
- (bool)sharedLibraryEnabled;
- (id)sharedLibraryLastDiscoveryDate;
- (id)sharedLibraryLastDiscoveryLocation;
- (id)sharedLibraryLastLocation;
- (bool)sharedLibraryLastLocationAcquiredDuringTrip;
- (id)sharedLibraryLastUserActionDate;
- (id)sharedLibraryLastUserActionLocation;
- (bool)sharedLibrarySwitchEnabled;
- (bool)shouldCaptureHDREV0;
- (bool)shouldDelayRemotePersistence;
- (bool)shouldDisableCameraSwitchingDuringVideoRecordingForMode:(long long)arg1;
- (bool)shouldForceMonoAudioRecording;
- (bool)shouldLockWhiteBalanceDuringVideoRecording;
- (bool)shouldMirrorFrontCameraCaptures;
- (bool)shouldShowGridView;
- (bool)shouldShowHorizonLevelView;
- (bool)shouldShowLevelView;
- (bool)shouldShowQRBanners;
- (bool)shouldUseContentAwareDistortionCorrection;
- (bool)shouldUseDepthSuggestionInPhotoMode;
- (bool)shouldUseModernHDRBehavior;
- (bool)shouldUsePhotoFormatControlForMode:(long long)arg1 device:(long long)arg2;
- (bool)shouldUseVolumeUpBurst;
- (long long)slomoConfiguration;
- (long long)squareModeLastCapturedEffectFilterType;
- (bool)usingMostCompatibleEncoding;
- (long long)videoConfiguration;
- (long long)videoEncodingBehaviorForConfiguration:(long long)arg1 mode:(long long)arg2 desiredProResVideoMode:(long long)arg3 outputToExternalStorage:(bool)arg4;
- (long long)videoStabilizationStrengthForVideoStabilizationMode:(long long)arg1 captureMode:(long long)arg2;
- (void)writePreferences;

@end
