
@interface UIPrintPanelViewController : UIViewController <UINavigationControllerDelegate, UIPopoverPresentationControllerDelegate, UIPrintPanelAppearanceDelegate> {
    UIActivityViewController * _activityViewController;
    bool  _animated;
    UIViewController<UIPrintAppExtensionProtocol> * _appPrintExtensionController;
    bool  _dismissed;
    NSArray * _horizScrollPrintPanelConstraints;
    NSArray * _lastUsedPrinterArray;
    long long  _lastUsedPrinterIndex;
    NSObject<OS_dispatch_queue> * _lookupPrinterQueue;
    UIPrinter * _observedPrinter;
    UIViewController * _parentController;
    UIAlertController * _pdfCreationProgressController;
    UIPopoverController * _poverController;
    NSLayoutConstraint * _previewHeightConstraint;
    UIView * _previewPanelView;
    UIView * _previewSeparatorView;
    UIPrintPreviewViewController * _previewViewController;
    UIPrintInfo * _printInfo;
    UIPrintInteractionController * _printInteractionController;
    UIPrintPanelNavigationController * _printOptionsNavController;
    UITableView * _printOptionsTableView;
    UIPrintOptionsTableViewController * _printOptionsTableViewController;
    NSLayoutConstraint * _printOptionsWidthConstraint;
    UIPrintPanelNavigationController * _printPanelNavigationController;
    UIPrintPanelWindow * _printPanelWindow;
    double  _progressPresentationTime;
    bool  _quickLookPDFGenerationCancelled;
    bool  _quickLookPDFGenerationInProgress;
    NSURL * _quickLookPDFURL;
    UIBarButtonItem * _shareButton;
    NSString * _shareablePDFDirectoryPath;
    NSArray * _vertScrollPrintPanelConstraints;
}

@property (nonatomic, retain) UIActivityViewController *activityViewController;
@property (nonatomic) bool animated;
@property (nonatomic, retain) UIViewController<UIPrintAppExtensionProtocol> *appPrintExtensionController;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool dismissed;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSArray *horizScrollPrintPanelConstraints;
@property (retain) NSArray *lastUsedPrinterArray;
@property (nonatomic) long long lastUsedPrinterIndex;
@property (nonatomic, retain) UIPrinter *observedPrinter;
@property (nonatomic) UIViewController *parentController;
@property (retain) UIAlertController *pdfCreationProgressController;
@property (nonatomic, retain) UIPopoverController *poverController;
@property (nonatomic, retain) NSLayoutConstraint *previewHeightConstraint;
@property (nonatomic, retain) UIView *previewPanelView;
@property (nonatomic, retain) UIView *previewSeparatorView;
@property (nonatomic, retain) UIPrintPreviewViewController *previewViewController;
@property (nonatomic, retain) UIPrintInfo *printInfo;
@property (nonatomic, retain) UIPrintInteractionController *printInteractionController;
@property (nonatomic, retain) UIPrintPanelNavigationController *printOptionsNavController;
@property (nonatomic, retain) UITableView *printOptionsTableView;
@property (nonatomic, retain) UIPrintOptionsTableViewController *printOptionsTableViewController;
@property (nonatomic, retain) NSLayoutConstraint *printOptionsWidthConstraint;
@property (nonatomic, retain) UIPrintPanelNavigationController *printPanelNavigationController;
@property (nonatomic, retain) UIPrintPanelWindow *printPanelWindow;
@property double progressPresentationTime;
@property bool quickLookPDFGenerationCancelled;
@property bool quickLookPDFGenerationInProgress;
@property (retain) NSURL *quickLookPDFURL;
@property (nonatomic, retain) UIBarButtonItem *shareButton;
@property (retain) NSString *shareablePDFDirectoryPath;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSArray *vertScrollPrintPanelConstraints;

+ (bool)_preventsAppearanceProxyCustomization;

- (void).cxx_destruct;
- (void)_presentInParentAnimated:(bool)arg1;
- (id)activityViewController;
- (void)addCanelButtonToNavItem:(id)arg1;
- (void)addPrintShareButtonsToNavItem:(id)arg1;
- (bool)animated;
- (id)appPrintExtensionController;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)cancelButtonPressed:(id)arg1;
- (void)cancelPrinting;
- (void)cancelQuickLookPDFGeneration;
- (id)createShareablePDFFileURL:(id)arg1;
- (void)dealloc;
- (void)dismissAnimated:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)dismissKeyboard;
- (void)dismissPrintPanelWithAction:(long long)arg1 animated:(bool)arg2 completionHandler:(id /* block */)arg3;
- (bool)dismissed;
- (void)generateQuickLookPDFWithCompletionHandler:(id /* block */)arg1;
- (void)hideGeneratingPDFProgress:(id)arg1;
- (id)horizScrollPrintPanelConstraints;
- (id)initWithPrintInterationController:(id)arg1 inParentController:(id)arg2;
- (id)keyCommands;
- (id)lastUsedPrinterArray;
- (long long)lastUsedPrinterIndex;
- (void)loadView;
- (void)lookupLastUsedPrinter;
- (unsigned long long)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)observedPrinter;
- (id)parentController;
- (id)pdfCreationProgressController;
- (id)poverController;
- (void)presentPrintPanelAnimated:(bool)arg1 hostingScene:(id)arg2;
- (void)presentPrintPanelFromBarButtonItem:(id)arg1 animated:(bool)arg2;
- (void)presentPrintPanelFromRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 inView:(id)arg2 animated:(bool)arg3;
- (id)previewHeightConstraint;
- (id)previewPanelView;
- (id)previewSeparatorView;
- (id)previewViewController;
- (void)printButtonPressed:(id)arg1;
- (id)printInfo;
- (id)printInteractionController;
- (void)printNavigationConrollerDidDismiss;
- (id)printOptionsNavController;
- (id)printOptionsTableView;
- (id)printOptionsTableViewController;
- (id)printOptionsWidthConstraint;
- (void)printPanelDidDisappear;
- (id)printPanelNavigationController;
- (id)printPanelWindow;
- (id)printerDisplayName:(id)arg1;
- (double)progressPresentationTime;
- (bool)quickLookPDFGenerationCancelled;
- (bool)quickLookPDFGenerationInProgress;
- (id)quickLookPDFURL;
- (void)removeShareablePDFFiles;
- (void)setActivityViewController:(id)arg1;
- (void)setAnimated:(bool)arg1;
- (void)setAppPrintExtensionController:(id)arg1;
- (void)setDismissed:(bool)arg1;
- (void)setHorizScrollPrintPanelConstraints:(id)arg1;
- (void)setLastUsedPrinterArray:(id)arg1;
- (void)setLastUsedPrinterIndex:(long long)arg1;
- (void)setObservedPrinter:(id)arg1;
- (void)setParentController:(id)arg1;
- (void)setPdfCreationProgressController:(id)arg1;
- (void)setPoverController:(id)arg1;
- (void)setPreviewHeightConstraint:(id)arg1;
- (void)setPreviewPanelView:(id)arg1;
- (void)setPreviewSeparatorView:(id)arg1;
- (void)setPreviewViewController:(id)arg1;
- (void)setPrintInfo:(id)arg1;
- (void)setPrintInteractionController:(id)arg1;
- (void)setPrintOptionsNavController:(id)arg1;
- (void)setPrintOptionsTableView:(id)arg1;
- (void)setPrintOptionsTableViewController:(id)arg1;
- (void)setPrintOptionsWidthConstraint:(id)arg1;
- (void)setPrintPanelNavigationController:(id)arg1;
- (void)setPrintPanelWindow:(id)arg1;
- (void)setPrinter:(id)arg1;
- (void)setProgressPresentationTime:(double)arg1;
- (void)setQuickLookPDFGenerationCancelled:(bool)arg1;
- (void)setQuickLookPDFGenerationInProgress:(bool)arg1;
- (void)setQuickLookPDFURL:(id)arg1;
- (void)setShareButton:(id)arg1;
- (void)setShareablePDFDirectoryPath:(id)arg1;
- (void)setVertScrollPrintPanelConstraints:(id)arg1;
- (id)shareButton;
- (void)shareButtonPress:(id)arg1;
- (id)shareablePDFDirectoryPath;
- (id)shareableURLForPreviewing;
- (bool)shouldShowDuplex;
- (bool)shouldShowLayout;
- (bool)shouldShowOrientation;
- (bool)shouldShowPageRange;
- (bool)shouldShowScaling;
- (void)showGeneratingPDFProgressPanel;
- (void)showSharePanelForPDFURL:(id)arg1;
- (bool)showingVerticalPreview;
- (void)startPrinting;
- (void)updatePageRange;
- (void)updatePreviewLayoutConstraints;
- (void)updateViewConstraints;
- (id)vertScrollPrintPanelConstraints;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillLayoutSubviews;

@end
