
@interface ICQPreferencesRemoteUIDelegate : NSObject <ICQUICloudStorageOffersManagerDelegate, ICQUpgradeFlowManagerDelegate, PreferencesRemoteUIDelegateProtocol, RUILoaderDelegate, RUIObjectModelDelegate> {
    ACAccount * _account;
    ICQPreferencesRemoteUIDelegateTableCellButton * _button;
    bool  _cancelled;
    NSArray * _dataclassSubstitutions;
    <DelayedPushDelegate> * _delegate;
    int  _deleteAllDocumentsAttemptCount;
    NSMutableArray * _deleteLoaders;
    NSOperationQueue * _deleteQueue;
    unsigned long long  _forceActionSignal;
    ICQPreferencesFreshmintManager * _freshmintManager;
    long long  _icqAction;
    NSString * _initialAction;
    bool  _isManageStorage;
    bool  _isNativeManageStorage;
    RUILoader * _lastDocumentDeleteLoader;
    ICQUILegacyPurchaseFlowManager * _legacyPurchaseFlowManager;
    ICQUIPreferencesLiftUIDelegate * _liftUIDelegate;
    id /* block */  _linkCompletionBlock;
    RUILoader * _loader;
    UINavigationController * _modalNavigationController;
    UINavigationController * _navigationController;
    NSString * _nextSignpostId;
    NSMutableArray * _objectModels;
    _TtC13iCloudQuotaUI29RecommendationAnalyticsHelper * _recommendationAnalyticsHelper;
    NSString * _requestContentType;
    struct icq_signpost_s { 
        unsigned long long identifier; 
        unsigned long long timestamp; 
    }  _signpost;
    id /* block */  _storageOffersFlowCompletion;
    ICQUICloudStorageOffersManager * _storageOffersManager;
}

@property (nonatomic, retain) NSArray *dataclassSubstitutions;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <DelayedPushDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) ICQPreferencesFreshmintManager *freshmintManager;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSString *initialAction;
@property (nonatomic) bool isManageStorage;
@property (nonatomic) bool isNativeManageStorage;
@property (retain) RUILoader *lastDocumentDeleteLoader;
@property (nonatomic, retain) ICQUIPreferencesLiftUIDelegate *liftUIDelegate;
@property (nonatomic, retain) NSString *nextSignpostId;
@property (readonly) Class superclass;

+ (void)_loadCKStoragePluginSettingsBundleIfNeeded;
+ (id)afuiSettingsSpecifier;
+ (id)healthSettingsSpecifier;
+ (id)messagesSettingsSpecifier;

- (void).cxx_destruct;
- (void)_activateBackupsElementForObjectModel:(id)arg1 completion:(id /* block */)arg2;
- (void)_activatePhotosElementForObjectModel:(id)arg1 completion:(id /* block */)arg2;
- (void)_freshmintStorageUpgradeWithCompletion:(id /* block */)arg1 withURL:(id)arg2;
- (void)_freshmintStorageUpgradeWithICQLink:(id)arg1 completion:(id /* block */)arg2;
- (bool)_loadNativeURL:(id)arg1;
- (void)_popObjectModelAnimated:(bool)arg1;
- (void)_postQuotaDidChangeNotification;
- (void)_presentCloudStorageOffersFlowWithAction:(id)arg1 completion:(id /* block */)arg2;
- (void)_processObjectModel:(id)arg1;
- (void)_processTableRow:(id)arg1;
- (void)_reloadQuotaInfo;
- (void)beginLegacyFlow;
- (void)buyFlowCompletionDidSucceed:(bool)arg1 error:(id)arg2;
- (void)cancelRemoteUI;
- (void)cleanupLoader;
- (void)confirmDeleteAll;
- (void)confirmDeleteWithTitle:(id)arg1 prompt:(id)arg2 explanation:(id)arg3 confirmationAction:(id /* block */)arg4;
- (id)dataclassSubstitutions;
- (void)dealloc;
- (id)delegate;
- (void)deleteAllDocuments;
- (id)freshmintManager;
- (id)initWithNavigationController:(id)arg1;
- (id)initWithNavigationController:(id)arg1 buyStorageFlow:(bool)arg2;
- (id)initWithNavigationController:(id)arg1 initialAction:(id)arg2;
- (id)initWithNavigationController:(id)arg1 initialAction:(id)arg2 account:(id)arg3;
- (id)initialAction;
- (bool)isManageStorage;
- (bool)isNativeManageStorage;
- (id)lastDocumentDeleteLoader;
- (id)liftUIDelegate;
- (void)loadURL:(id)arg1 postBody:(id)arg2;
- (void)loadURL:(id)arg1 postBody:(id)arg2 additionalHeaders:(id)arg3;
- (void)loader:(id)arg1 didFinishLoadWithError:(id)arg2 forRequest:(id)arg3;
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 topActionSignal:(id)arg3;
- (void)manager:(id)arg1 didCompleteWithError:(id)arg2;
- (void)managerDidCancel:(id)arg1;
- (id)nextSignpostId;
- (void)objectModel:(id)arg1 configureTableRow:(id)arg2 page:(id)arg3;
- (bool)objectModel:(id)arg1 page:(id)arg2 deletedTableRow:(id)arg3 atIndexPath:(id)arg4 withURL:(id)arg5 httpMethod:(id)arg6;
- (void)objectModel:(id)arg1 page:(id)arg2 toggledEditing:(bool)arg3;
- (void)objectModel:(id)arg1 pressedButton:(id)arg2 attributes:(id)arg3;
- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3 completion:(id /* block */)arg4;
- (void)objectModelDidChange:(id)arg1;
- (void)objectModelPressedBack:(id)arg1;
- (id)parentViewControllerForObjectModel:(id)arg1;
- (void)popAndReloadFromRemoteUI:(bool)arg1 additionalHeaders:(id)arg2;
- (void)reloadTopControllerWithAdditionalHeaders:(id)arg1;
- (void)setDataclassSubstitutions:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFreshmintManager:(id)arg1;
- (void)setInitialAction:(id)arg1;
- (void)setIsManageStorage:(bool)arg1;
- (void)setIsNativeManageStorage:(bool)arg1;
- (void)setLastDocumentDeleteLoader:(id)arg1;
- (void)setLiftUIDelegate:(id)arg1;
- (void)setNextSignpostId:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)upgradeFlowManagerDidCancel:(id)arg1;
- (void)upgradeFlowManagerDidComplete:(id)arg1;
- (void)willShowController:(id)arg1;

@end
