
@interface EKICSImporter : NSObject {
    NSObject<OS_dispatch_queue> * _async_queue;
    bool  _asynchronous;
    EKCalendar * _calendar;
    NSMapTable * _calendarToICalFiles;
    NSMapTable * _calendarToITIPFiles;
    NSMapTable * _calendarToVCalFiles;
    id /* block */  _completionCallback;
    unsigned long long  _droppedReminderCount;
    EKEventStore * _eventStore;
    NSMutableSet * _existingEventIDs;
    NSMutableArray * _filesWithReminders;
    NSMutableDictionary * _iCalFilesToImport;
    NSMutableDictionary * _iTIPFiles;
    id /* block */  _importDroppedReminders;
    NSError * _importError;
    NSArray * _importFilePaths;
    id /* block */  _importFoundBackupFile;
    id /* block */  _importSetProgressAsIndeterminate;
    id /* block */  _importSetProgressValue;
    NSMutableArray * _importedItems;
    id /* block */  _makeDecision;
    NSMutableDictionary * _nonITIPFiles;
    unsigned long long  _numInvalidEvents;
    unsigned long long  _options;
    id /* block */  _selectCalendar;
    NSMutableArray * _vCalFilesToImport;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *async_queue;
@property (nonatomic) bool asynchronous;
@property (nonatomic, retain) EKCalendar *calendar;
@property (nonatomic, retain) NSMapTable *calendarToICalFiles;
@property (nonatomic, retain) NSMapTable *calendarToITIPFiles;
@property (nonatomic, retain) NSMapTable *calendarToVCalFiles;
@property (nonatomic, copy) id /* block */ completionCallback;
@property (nonatomic) unsigned long long droppedReminderCount;
@property (nonatomic, retain) EKEventStore *eventStore;
@property (nonatomic, retain) NSMutableSet *existingEventIDs;
@property (nonatomic, retain) NSMutableArray *filesWithReminders;
@property (nonatomic, retain) NSMutableDictionary *iCalFilesToImport;
@property (nonatomic, retain) NSMutableDictionary *iTIPFiles;
@property (nonatomic, copy) id /* block */ importDroppedReminders;
@property (nonatomic, retain) NSError *importError;
@property (nonatomic, readonly) NSArray *importFilePaths;
@property (nonatomic, copy) id /* block */ importFoundBackupFile;
@property (nonatomic, copy) id /* block */ importSetProgressAsIndeterminate;
@property (nonatomic, copy) id /* block */ importSetProgressValue;
@property (nonatomic, retain) NSMutableArray *importedItems;
@property (nonatomic, copy) id /* block */ makeDecision;
@property (nonatomic, retain) NSMutableDictionary *nonITIPFiles;
@property (nonatomic) unsigned long long numInvalidEvents;
@property (nonatomic) unsigned long long options;
@property (nonatomic, copy) id /* block */ selectCalendar;
@property (nonatomic, retain) NSMutableArray *vCalFilesToImport;

+ (id)allowedImportFileTypes;

- (void).cxx_destruct;
- (void)_createImportHandle;
- (bool)_doITIPFileImport;
- (bool)_doImportFiles;
- (id)_existingEventFromICSEvent:(id)arg1 calendar:(id)arg2;
- (id)_findBestEventFromEvents:(id)arg1;
- (id)_findCalendarForExistingEvent:(id)arg1;
- (id)_getImportedCalendarItems;
- (void)_importWithCompletion:(id /* block */)arg1;
- (id)_initWithFilePaths:(id)arg1 eventStore:(id)arg2 calendar:(id)arg3 options:(unsigned long long)arg4;
- (bool)_isAnyAttendeeAddressFrom:(id)arg1 organizer:(id)arg2 equivalentTo:(id)arg3;
- (id)_matchingAttendeeAddressesFrom:(id)arg1 organizer:(id)arg2 inSource:(id)arg3;
- (bool)_message:(id)arg1 hasNewSelfOrganizedEventForCalendar:(id)arg2;
- (unsigned long long)_separateFilesForImport:(id)arg1;
- (bool)_separateICalFilesForITIP;
- (bool)_sortFilesByImportCalendar;
- (void)asyncImportWithCompletion:(id /* block */)arg1;
- (id)async_queue;
- (bool)asynchronous;
- (id)calendar;
- (id)calendarToICalFiles;
- (id)calendarToITIPFiles;
- (id)calendarToVCalFiles;
- (void)callCompletionWithSuccess:(bool)arg1;
- (void)callImportDroppedRemindersCallbackIfThereWereReminders;
- (id)callbackQueue;
- (id /* block */)completionCallback;
- (int)countReminders:(id)arg1;
- (unsigned long long)droppedReminderCount;
- (id)eventFromDocument:(id)arg1;
- (id)eventStore;
- (id)existingEventIDs;
- (id)filesWithReminders;
- (id)iCalFilesToImport;
- (id)iTIPFiles;
- (id /* block */)importDroppedReminders;
- (id)importError;
- (id)importFilePaths;
- (id /* block */)importFoundBackupFile;
- (void)importFoundBackupFile:(id)arg1;
- (bool)importICalFiles;
- (id /* block */)importSetProgressAsIndeterminate;
- (id /* block */)importSetProgressValue;
- (id)importedItems;
- (id)infoForNewCalendarForFiles:(id)arg1 forITIPFiles:(id)arg2 nonITIPFiles:(id)arg3;
- (id)initWithFilePaths:(id)arg1 calendar:(id)arg2 options:(unsigned long long)arg3;
- (id)initWithFilePaths:(id)arg1 eventStore:(id)arg2 options:(unsigned long long)arg3;
- (id /* block */)makeDecision;
- (id)nonITIPFiles;
- (unsigned long long)numInvalidEvents;
- (unsigned long long)options;
- (id /* block */)selectCalendar;
- (id)selectCalendarWithTitle:(id)arg1 color:(id)arg2 description:(id)arg3 error:(id*)arg4;
- (void)setAsync_queue:(id)arg1;
- (void)setAsynchronous:(bool)arg1;
- (void)setCalendar:(id)arg1;
- (void)setCalendarToICalFiles:(id)arg1;
- (void)setCalendarToITIPFiles:(id)arg1;
- (void)setCalendarToVCalFiles:(id)arg1;
- (void)setCompletionCallback:(id /* block */)arg1;
- (void)setDroppedReminderCount:(unsigned long long)arg1;
- (void)setEventStore:(id)arg1;
- (void)setExistingEventIDs:(id)arg1;
- (void)setFilesWithReminders:(id)arg1;
- (void)setICalFilesToImport:(id)arg1;
- (void)setITIPFiles:(id)arg1;
- (void)setImportDroppedReminders:(id /* block */)arg1;
- (void)setImportError:(id)arg1;
- (void)setImportFoundBackupFile:(id /* block */)arg1;
- (void)setImportProgressAsIndeterminate;
- (void)setImportSetProgressAsIndeterminate:(id /* block */)arg1;
- (void)setImportSetProgressValue:(id /* block */)arg1;
- (void)setImportedItems:(id)arg1;
- (void)setMakeDecision:(id /* block */)arg1;
- (void)setNonITIPFiles:(id)arg1;
- (void)setNumInvalidEvents:(unsigned long long)arg1;
- (void)setOptions:(unsigned long long)arg1;
- (void)setSelectCalendar:(id /* block */)arg1;
- (void)setVCalFilesToImport:(id)arg1;
- (bool)shouldImportContinueGivenDecision:(int)arg1 eventsAffected:(unsigned long long)arg2;
- (void)syncImportWithCompletion:(id /* block */)arg1;
- (id)vCalFilesToImport;

@end
