
@interface ProfileCharacteristicsViewController : UITableViewController <UINavigationControllerDelegate, UIPickerViewDataSource, UIPickerViewDelegate> {
    long long  _accessType;
    int  _activeCardioFitnessMedications;
    UIImage * _avatarImage;
    UIImageView * _avatarImageView;
    bool  _beginInEditMode;
    UITableViewCell * _betaBlockerUseCell;
    WDProfileTableViewCell * _biologicalSexCell;
    long long  _biologicalSexDisplayValue;
    HKBiologicalSexObject * _biologicalSexObject;
    UIPickerView * _biologicalSexPicker;
    NSDateComponents * _birthdate;
    WDProfileTableViewCell * _birthdateCell;
    HKBirthdateChangeManager * _birthdateChangeManager;
    NSDateComponents * _birthdateDisplayValue;
    UIDatePicker * _birthdatePicker;
    WDProfileTableViewCell * _bloodTypeCell;
    long long  _bloodTypeDisplayValue;
    HKBloodTypeObject * _bloodTypeObject;
    UIPickerView * _bloodTypePicker;
    UITableViewCell * _calciumChannelBlockerUseCell;
    UIBarButtonItem * _cancelButtonItem;
    UITableViewCell * _cardioFitnessMedicationsCell;
    bool  _cardioFitnessMedicationsSectionHidden;
    unsigned long long  _currentCardioFitnessMedicationsUse;
    NSDiffableDataSourceSnapshot * _currentSnapshot;
    UIBarButtonItem * _customLeftBarButtonItem;
    ProfileCharacteristicDiffableDataSource * _dataSource;
    HKDisplayTypeController * _displayTypeController;
    NSString * _firstName;
    WDProfileEditableTableViewCell * _firstNameCell;
    WDProfileTableViewCell * _fitzpatrickSkinTypeCell;
    long long  _fitzpatrickSkinTypeDisplayValue;
    UIPickerView * _fitzpatrickSkinTypePicker;
    WDDisplayTypeDescriptionTableFooterView * _footerView;
    NSCalendar * _gregorianCalendar;
    WDProfileHeaderView * _headerView;
    HKHealthStore * _healthStore;
    bool  _isCancelling;
    NSString * _lastName;
    WDProfileEditableTableViewCell * _lastNameCell;
    bool  _nameRowsHidden;
    NSDictionary * _orderedRowIdentifiersBySectionIdentifier;
    NSArray * _orderedSectionIdentifiers;
    WDProfileTableViewCell * _selectedCell;
    WDUserDefaults * _userDefaults;
    WDProfileTableViewCell * _wheelchairUseCell;
    long long  _wheelchairUseDisplayValue;
    UIPickerView * _wheelchairUsePicker;
}

@property (nonatomic) long long accessType;
@property (nonatomic, retain) UIImage *avatarImage;
@property (nonatomic, retain) UIImageView *avatarImageView;
@property (nonatomic, retain) HKBirthdateChangeManager *birthdateChangeManager;
@property (nonatomic, retain) NSDiffableDataSourceSnapshot *currentSnapshot;
@property (nonatomic, retain) ProfileCharacteristicDiffableDataSource *dataSource;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (double)avatarImageSize;
+ (bool)cardioFitnessMedicationsSectionHiddenForProfileIdentifier:(id)arg1;
+ (bool)nameRowsHiddenForProfileIdentifier:(id)arg1;
+ (id)orderedRowIdentifiersBySectionIdentifierWithNameRowsHidden:(bool)arg1 andCardioFitnessMedicationsSectionHidden:(bool)arg2;
+ (id)orderedSectionIdentifiersWithCardioFitnessMedicationsSectionHidden:(bool)arg1;

- (void).cxx_destruct;
- (void)_adjustHeaderFrame;
- (id)_birthdayCalendar;
- (id)_checkmarkedCircleImageView;
- (id)_circleImageView;
- (void)_createBarButtonItems;
- (id)_createBetaBlockerCheckMarkCell;
- (id)_createCalciumChannelBlockerCheckMarkCell;
- (void)_createCells;
- (void)_createHeader;
- (void)_createPickers;
- (id)_dateAsAge:(id)arg1;
- (id)_displayStringForBiologicalSex:(long long)arg1;
- (id)_displayStringForBirthDate:(id)arg1;
- (id)_displayStringForBloodType:(long long)arg1;
- (id)_displayStringForFitzpatrickSkinType:(long long)arg1;
- (id)_displayStringForWheelchairUse:(long long)arg1;
- (void)_enableEditing;
- (void)_fetchDataFromHealthStore;
- (id)_generalInfoFooterView;
- (id)_initialBirthdayValue;
- (void)_localeDidChange:(id)arg1;
- (id)_meContact;
- (long long)_profileRowIdentifierForSection:(long long)arg1 forRow:(long long)arg2;
- (void)_resetFirstAndLastNameValues;
- (void)_resetSelectedCell;
- (void)_timeZoneDidChange:(id)arg1;
- (id)_titleForFooterInTableViewSection:(long long)arg1 sectionIdentifier:(id)arg2;
- (void)_updateCellsWithDisplayValues;
- (void)_updateFirstAndLastNameCellsWithDisplayValues;
- (void)_updateFirstName:(id)arg1 lastName:(id)arg2 completion:(id /* block */)arg3;
- (void)_updateFooters;
- (void)_updatePickersWithDisplayValues;
- (id)_wheelchairFooterTitle;
- (long long)accessType;
- (id)avatarImage;
- (id)avatarImageView;
- (id)birthdateChangeManager;
- (void)birthdateChanged:(id)arg1;
- (void)cancelButtonTapped:(id)arg1;
- (id)currentSnapshot;
- (id)dataSource;
- (void)dealloc;
- (void)didClearBirthdate;
- (void)didUpdateName;
- (void)dismissButtonTapped:(id)arg1;
- (id)displayNumberOfActiveCardioFitnessMedications:(int)arg1;
- (id)getCellForIndexPath:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithHealthStore:(id)arg1;
- (id)initWithHealthStore:(id)arg1 inEditMode:(bool)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(bool)arg3;
- (unsigned long long)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (void)setAccessType:(long long)arg1;
- (void)setAvatarImage:(id)arg1;
- (void)setAvatarImageView:(id)arg1;
- (void)setBirthdateChangeManager:(id)arg1;
- (void)setCardioFitnessMedicationCheckmarks;
- (void)setCurrentSnapshot:(id)arg1;
- (void)setDataSource:(id)arg1;
- (void)setEditing:(bool)arg1 animated:(bool)arg2;
- (void)setUpNavigationBar;
- (bool)shouldShowNameInHeaderView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateCheckMarksForCell:(id)arg1 option:(unsigned long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
