
@interface W5WiFiStatus : NSObject <NSCopying, NSSecureCoding> {
    NSString * _bssid;
    NSData * _btcConfig;
    int  _btcMode;
    NSData * _btcProfiles2GHz;
    NSData * _btcProfiles5GHz;
    NSArray * _cachedScanResults;
    NSData * _chainAck;
    W5WiFiChannel * _channel;
    NSString * _countryCode;
    NSData * _desense;
    NSData * _desenseLevel;
    NSArray * _dnsAddresses;
    unsigned int  _eapolControlMode;
    unsigned int  _eapolSupplicantState;
    unsigned long long  _guardInterval;
    NSString * _hardwareMACAddress;
    NSString * _interfaceName;
    NSArray * _ipv4Addresses;
    long long  _ipv4ConfigMethod;
    NSString * _ipv4RouterAddress;
    NSArray * _ipv6Addresses;
    long long  _ipv6ConfigMethod;
    NSString * _ipv6RouterAddress;
    W5WiFiPreferredNetwork * _lastJoinedPreferredNetwork;
    W5WiFiScanResult * _lastJoinedScanResult;
    NSArray * _linkQualityUpdates;
    NSString * _macAddress;
    unsigned long long  _mcsIndex;
    NSString * _networkServiceID;
    long long  _noise;
    unsigned long long  _numberOfSpacialStreams;
    int  _opMode;
    int  _phyMode;
    NSData * _power;
    bool  _powerOn;
    long long  _rssi;
    long long  _security;
    bool  _smartCCADesenseSupported;
    bool  _smartCCADesenseUSBPresence;
    NSData * _ssid;
    NSString * _ssidString;
    NSArray * _supportedChannels;
    NSData * _txChainPower;
    double  _txRate;
}

@property (nonatomic, copy) NSString *bssid;
@property (nonatomic, copy) NSData *btcConfig;
@property (nonatomic) int btcMode;
@property (nonatomic, copy) NSData *btcProfiles2GHz;
@property (nonatomic, copy) NSData *btcProfiles5GHz;
@property (nonatomic, copy) NSArray *cachedScanResults;
@property (nonatomic, copy) NSData *chainAck;
@property (nonatomic, readonly) NSString *chainAckString;
@property (nonatomic, copy) W5WiFiChannel *channel;
@property (nonatomic, copy) NSString *countryCode;
@property (nonatomic, copy) NSData *desense;
@property (nonatomic, copy) NSData *desenseLevel;
@property (nonatomic, readonly) NSString *desenseString;
@property (nonatomic, readonly) NSDictionary *dictionary;
@property (nonatomic, copy) NSArray *dnsAddresses;
@property (nonatomic) unsigned int eapolControlMode;
@property (nonatomic) unsigned int eapolSupplicantState;
@property (nonatomic) unsigned long long guardInterval;
@property (nonatomic, copy) NSString *hardwareMACAddress;
@property (nonatomic, copy) NSString *interfaceName;
@property (nonatomic, copy) NSArray *ipv4Addresses;
@property (nonatomic) long long ipv4ConfigMethod;
@property (nonatomic, copy) NSString *ipv4RouterAddress;
@property (nonatomic, copy) NSArray *ipv6Addresses;
@property (nonatomic) long long ipv6ConfigMethod;
@property (nonatomic, copy) NSString *ipv6RouterAddress;
@property (nonatomic, copy) W5WiFiPreferredNetwork *lastJoinedPreferredNetwork;
@property (nonatomic, copy) W5WiFiScanResult *lastJoinedScanResult;
@property (nonatomic, copy) NSArray *linkQualityUpdates;
@property (nonatomic, copy) NSString *macAddress;
@property (nonatomic) unsigned long long mcsIndex;
@property (nonatomic, copy) NSString *networkServiceID;
@property (nonatomic) long long noise;
@property (nonatomic) unsigned long long numberOfSpacialStreams;
@property (nonatomic) int opMode;
@property (nonatomic) int phyMode;
@property (nonatomic, copy) NSData *power;
@property (nonatomic) bool powerOn;
@property (nonatomic, readonly) NSString *powerString;
@property (nonatomic) long long rssi;
@property (nonatomic) long long security;
@property (nonatomic) bool smartCCADesenseSupported;
@property (nonatomic) bool smartCCADesenseUSBPresence;
@property (nonatomic, copy) NSData *ssid;
@property (nonatomic, copy) NSString *ssidString;
@property (nonatomic, copy) NSArray *supportedChannels;
@property (nonatomic, copy) NSData *txChainPower;
@property (nonatomic) double txRate;

// Image: /System/Library/PrivateFrameworks/WiFiVelocity.framework/WiFiVelocity

+ (bool)supportsSecureCoding;

- (id)bssid;
- (id)btcConfig;
- (int)btcMode;
- (id)btcProfiles2GHz;
- (id)btcProfiles5GHz;
- (id)cachedScanResults;
- (id)chainAck;
- (id)channel;
- (bool)conformsToProtocol:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)countryCode;
- (void)dealloc;
- (id)description;
- (id)desense;
- (id)desenseLevel;
- (id)dnsAddresses;
- (unsigned int)eapolControlMode;
- (unsigned int)eapolSupplicantState;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)guardInterval;
- (id)hardwareMACAddress;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)interfaceName;
- (id)ipv4Addresses;
- (long long)ipv4ConfigMethod;
- (id)ipv4RouterAddress;
- (id)ipv6Addresses;
- (long long)ipv6ConfigMethod;
- (id)ipv6RouterAddress;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToWiFiStatus:(id)arg1;
- (id)lastJoinedPreferredNetwork;
- (id)lastJoinedScanResult;
- (id)linkQualityUpdates;
- (id)macAddress;
- (unsigned long long)mcsIndex;
- (id)networkServiceID;
- (long long)noise;
- (unsigned long long)numberOfSpacialStreams;
- (int)opMode;
- (int)phyMode;
- (id)power;
- (bool)powerOn;
- (long long)rssi;
- (long long)security;
- (void)setBssid:(id)arg1;
- (void)setBtcConfig:(id)arg1;
- (void)setBtcMode:(int)arg1;
- (void)setBtcProfiles2GHz:(id)arg1;
- (void)setBtcProfiles5GHz:(id)arg1;
- (void)setCachedScanResults:(id)arg1;
- (void)setChainAck:(id)arg1;
- (void)setChannel:(id)arg1;
- (void)setCountryCode:(id)arg1;
- (void)setDesense:(id)arg1;
- (void)setDesenseLevel:(id)arg1;
- (void)setDnsAddresses:(id)arg1;
- (void)setEapolControlMode:(unsigned int)arg1;
- (void)setEapolSupplicantState:(unsigned int)arg1;
- (void)setGuardInterval:(unsigned long long)arg1;
- (void)setHardwareMACAddress:(id)arg1;
- (void)setInterfaceName:(id)arg1;
- (void)setIpv4Addresses:(id)arg1;
- (void)setIpv4ConfigMethod:(long long)arg1;
- (void)setIpv4RouterAddress:(id)arg1;
- (void)setIpv6Addresses:(id)arg1;
- (void)setIpv6ConfigMethod:(long long)arg1;
- (void)setIpv6RouterAddress:(id)arg1;
- (void)setLastJoinedPreferredNetwork:(id)arg1;
- (void)setLastJoinedScanResult:(id)arg1;
- (void)setLinkQualityUpdates:(id)arg1;
- (void)setMacAddress:(id)arg1;
- (void)setMcsIndex:(unsigned long long)arg1;
- (void)setNetworkServiceID:(id)arg1;
- (void)setNoise:(long long)arg1;
- (void)setNumberOfSpacialStreams:(unsigned long long)arg1;
- (void)setOpMode:(int)arg1;
- (void)setPhyMode:(int)arg1;
- (void)setPower:(id)arg1;
- (void)setPowerOn:(bool)arg1;
- (void)setRssi:(long long)arg1;
- (void)setSecurity:(long long)arg1;
- (void)setSmartCCADesenseSupported:(bool)arg1;
- (void)setSmartCCADesenseUSBPresence:(bool)arg1;
- (void)setSsid:(id)arg1;
- (void)setSsidString:(id)arg1;
- (void)setSupportedChannels:(id)arg1;
- (void)setTxChainPower:(id)arg1;
- (void)setTxRate:(double)arg1;
- (bool)smartCCADesenseSupported;
- (bool)smartCCADesenseUSBPresence;
- (id)ssid;
- (id)ssidString;
- (id)supportedChannels;
- (id)txChainPower;
- (double)txRate;

// Image: /System/Library/PrivateFrameworks/NPTKit.framework/NPTKit

- (id)chainAckString;
- (id)desenseString;
- (id)dictionary;
- (id)powerString;

@end
