
@interface CSBatteryChargingRingView : CSBatteryChargingView {
    CALayer * _auxiliaryBatteryContainerLayer;
    SBUILegibilityLabel * _auxiliaryBatteryLabel;
    CSRingLayer * _auxiliaryBatteryLevelRing;
    UIView * _auxiliaryBatteryPillClippingView;
    UIView * _auxiliaryBatteryPillLevelView;
    UIView * _auxiliaryBatteryPillTrackView;
    CSRingLayer * _auxiliaryBatteryTrackFillRingLayer;
    CABackdropLayer * _auxiliaryCaptureBackdrop;
    CALayer * _auxiliaryChargingBoltGlyph;
    CALayer * _auxiliaryChargingBoltGlyphMask;
    UIImageView * _auxiliaryGlyphImageView;
    CALayer * _auxiliaryGlyphLayer;
    CABackdropLayer * _averageColorBackdropLayer;
    CABackdropLayer * _backgroundBackdropLayer;
    CABackdropLayer * _backgroundRadiusBackdropLayer;
    CSRingLayer * _batteryLevelRing;
    UIImageView * _boltMaskImageView;
    SBUILegibilityLabel * _chargePercentLabel;
    CALayer * _chargingBoltGlyph;
    UIView * _chargingContainerView;
    CSMagSafeAccessoryConfiguration * _configuration;
    CSMagSafePowerStatus * _externalStatus;
    BCBatteryDevice * _internalBattery;
    CSMagSafePowerStatus * _internalStatus;
    BSAbsoluteMachTimer * _longTailShortcutTimer;
    id /* block */  _longTailShortcutTimerHandler;
    CABackdropLayer * _ringBlurBackdropLayer;
    CSRingLayer * _ringBlurLayer;
    CALayer * _ringTempOverlayLayer;
    CSMagSafeSilhouetteConfiguration * _silhouette;
    CALayer * _silhouetteLayer;
    CALayer * _splashRing;
    CALayer * _splashRing1;
    CALayer * _splashRing3;
    CSRingLayer * _trackFillRingLayer;
}

@property (nonatomic, retain) CALayer *auxiliaryBatteryContainerLayer;
@property (nonatomic, retain) SBUILegibilityLabel *auxiliaryBatteryLabel;
@property (nonatomic, retain) CSRingLayer *auxiliaryBatteryLevelRing;
@property (nonatomic, retain) UIView *auxiliaryBatteryPillClippingView;
@property (nonatomic, retain) UIView *auxiliaryBatteryPillLevelView;
@property (nonatomic, retain) UIView *auxiliaryBatteryPillTrackView;
@property (nonatomic, retain) CSRingLayer *auxiliaryBatteryTrackFillRingLayer;
@property (nonatomic, retain) CABackdropLayer *auxiliaryCaptureBackdrop;
@property (nonatomic, retain) CALayer *auxiliaryChargingBoltGlyph;
@property (nonatomic, retain) CALayer *auxiliaryChargingBoltGlyphMask;
@property (nonatomic, retain) UIImageView *auxiliaryGlyphImageView;
@property (nonatomic, retain) CALayer *auxiliaryGlyphLayer;
@property (nonatomic, retain) CABackdropLayer *averageColorBackdropLayer;
@property (nonatomic, retain) CABackdropLayer *backgroundBackdropLayer;
@property (nonatomic, retain) CABackdropLayer *backgroundRadiusBackdropLayer;
@property (nonatomic, retain) CSRingLayer *batteryLevelRing;
@property (nonatomic, retain) UIImageView *boltMaskImageView;
@property (nonatomic, retain) SBUILegibilityLabel *chargePercentLabel;
@property (nonatomic, retain) CALayer *chargingBoltGlyph;
@property (nonatomic, retain) UIView *chargingContainerView;
@property (nonatomic, retain) CSMagSafeAccessoryConfiguration *configuration;
@property (nonatomic, retain) CSMagSafePowerStatus *externalStatus;
@property (nonatomic, retain) BCBatteryDevice *internalBattery;
@property (nonatomic, retain) CSMagSafePowerStatus *internalStatus;
@property (nonatomic, retain) BSAbsoluteMachTimer *longTailShortcutTimer;
@property (nonatomic, copy) id /* block */ longTailShortcutTimerHandler;
@property (nonatomic, retain) CABackdropLayer *ringBlurBackdropLayer;
@property (nonatomic, retain) CSRingLayer *ringBlurLayer;
@property (nonatomic, retain) CALayer *ringTempOverlayLayer;
@property (nonatomic, retain) CSMagSafeSilhouetteConfiguration *silhouette;
@property (nonatomic, retain) CALayer *silhouetteLayer;
@property (nonatomic, retain) CALayer *splashRing;
@property (nonatomic, retain) CALayer *splashRing1;
@property (nonatomic, retain) CALayer *splashRing3;
@property (nonatomic, retain) CSRingLayer *trackFillRingLayer;

- (void).cxx_destruct;
- (void)_animateSilhouetteToVisible:(bool)arg1;
- (id)_auxiliaryChargePercentFont;
- (id)_chargePercentFont;
- (void)_createAuxiliaryPillViewsIfNeeded;
- (void)_createBoltViewsIfNeeded;
- (double)_estimatedDurationForAnimation:(unsigned long long)arg1;
- (void)_handleExternalStatusUpdate;
- (bool)_isDarkerSystemColorsEnabled;
- (bool)_isReduceMotionEnabled;
- (bool)_isReduceTransparencyEnabled;
- (bool)_isShowingAuxiliary;
- (void)_layoutAuxiliaryChargePercentLabel;
- (void)_layoutChargePercentLabel;
- (struct CGPath { }*)_pathForRingConfiguration:(id)arg1;
- (void)_performChargingBoltDismissAnimation;
- (void)_performChargingBoltPresentAnimation;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_pillFrameForBatteryCharge:(double)arg1;
- (struct CGPoint { double x1; double x2; })_positionForPill:(id)arg1 forBatteryCharge:(double)arg2;
- (id)_powerStatusForBattery:(id)arg1;
- (id)_ringLayerForRingConfiguration:(id)arg1;
- (void)_runAnimationWithType:(unsigned long long)arg1;
- (void)_runAuxiliaryBatteryLevelAnimation;
- (void)_runAuxiliaryBatteryLevelDismissAnimation;
- (void)_runAuxiliaryChargingBoltAnimationVisible:(bool)arg1;
- (void)_runAuxiliaryChargingLabelPresentAnimation;
- (void)_runAuxiliarySplashRingAnimation;
- (void)_runBatteryLevelDismissAnimation;
- (void)_runBatteryLevelRingAnimation;
- (void)_runChargingBoltAnimationVisible:(bool)arg1;
- (void)_runChargingLabelPresentAnimation;
- (void)_runDimAnimation;
- (void)_runRingBlurAnimation;
- (void)_runSplashRingAnimation;
- (bool)_shouldUseShortcutForAnimation:(unsigned long long)arg1;
- (id)_springAnimationWithKeyPath:(id)arg1 delay:(double)arg2 forPresent:(bool)arg3 from:(id)arg4 to:(id)arg5;
- (id)_springAnimationWithKeyPath:(id)arg1 forPresent:(bool)arg2 from:(id)arg3 to:(id)arg4;
- (id)_springAnimationWithKeyPath:(id)arg1 stiffness:(double)arg2 damping:(double)arg3 duration:(double)arg4 delay:(double)arg5;
- (id)_trackAnimationForConfiguration:(id)arg1 withCurrentTime:(double)arg2;
- (id)_trackRingForRingConfiguration:(id)arg1 withBlendMode:(id)arg2;
- (id)_updateChargeString:(id)arg1 oldLabel:(id)arg2 font:(id)arg3;
- (id)auxiliaryBatteryContainerLayer;
- (id)auxiliaryBatteryLabel;
- (id)auxiliaryBatteryLevelRing;
- (id)auxiliaryBatteryPillClippingView;
- (id)auxiliaryBatteryPillLevelView;
- (id)auxiliaryBatteryPillTrackView;
- (id)auxiliaryBatteryTrackFillRingLayer;
- (id)auxiliaryCaptureBackdrop;
- (id)auxiliaryChargingBoltGlyph;
- (id)auxiliaryChargingBoltGlyphMask;
- (id)auxiliaryGlyphImageView;
- (id)auxiliaryGlyphLayer;
- (id)averageColorBackdropLayer;
- (id)backgroundBackdropLayer;
- (id)backgroundRadiusBackdropLayer;
- (double)batteryChargingLevel;
- (long long)batteryCount;
- (id)batteryLevelRing;
- (bool)batteryVisible;
- (id)boltMaskImageView;
- (id)chargePercentLabel;
- (id)chargingBoltGlyph;
- (id)chargingContainerView;
- (id)configuration;
- (void)dealloc;
- (double)desiredVisibilityDuration;
- (id)externalStatus;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 configuration:(id)arg2;
- (id)internalBattery;
- (id)internalStatus;
- (void)layoutSubviews;
- (id)longTailShortcutTimer;
- (id /* block */)longTailShortcutTimerHandler;
- (void)performAnimation:(unsigned long long)arg1 completionHandler:(id /* block */)arg2;
- (id)ringBlurBackdropLayer;
- (id)ringBlurLayer;
- (id)ringTempOverlayLayer;
- (void)setAuxiliaryBatteryContainerLayer:(id)arg1;
- (void)setAuxiliaryBatteryLabel:(id)arg1;
- (void)setAuxiliaryBatteryLevelRing:(id)arg1;
- (void)setAuxiliaryBatteryPillClippingView:(id)arg1;
- (void)setAuxiliaryBatteryPillLevelView:(id)arg1;
- (void)setAuxiliaryBatteryPillTrackView:(id)arg1;
- (void)setAuxiliaryBatteryTrackFillRingLayer:(id)arg1;
- (void)setAuxiliaryCaptureBackdrop:(id)arg1;
- (void)setAuxiliaryChargingBoltGlyph:(id)arg1;
- (void)setAuxiliaryChargingBoltGlyphMask:(id)arg1;
- (void)setAuxiliaryGlyphImageView:(id)arg1;
- (void)setAuxiliaryGlyphLayer:(id)arg1;
- (void)setAverageColorBackdropLayer:(id)arg1;
- (void)setBackgroundBackdropLayer:(id)arg1;
- (void)setBackgroundRadiusBackdropLayer:(id)arg1;
- (void)setBatteryLevelRing:(id)arg1;
- (void)setBatteryVisible:(bool)arg1;
- (void)setBoltMaskImageView:(id)arg1;
- (void)setChargePercentLabel:(id)arg1;
- (void)setChargingBoltGlyph:(id)arg1;
- (void)setChargingContainerView:(id)arg1;
- (void)setConfiguration:(id)arg1;
- (void)setExternalStatus:(id)arg1;
- (void)setInternalBattery:(id)arg1;
- (void)setInternalStatus:(id)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)setLongTailShortcutTimer:(id)arg1;
- (void)setLongTailShortcutTimerHandler:(id /* block */)arg1;
- (void)setPrimaryBatteryText:(id)arg1 forBattery:(id)arg2;
- (void)setRingBlurBackdropLayer:(id)arg1;
- (void)setRingBlurLayer:(id)arg1;
- (void)setRingTempOverlayLayer:(id)arg1;
- (void)setSecondaryBatteryText:(id)arg1 forBattery:(id)arg2;
- (void)setSilhouette:(id)arg1;
- (void)setSilhouetteLayer:(id)arg1;
- (void)setSplashRing1:(id)arg1;
- (void)setSplashRing3:(id)arg1;
- (void)setSplashRing:(id)arg1;
- (void)setTrackFillRingLayer:(id)arg1;
- (id)silhouette;
- (id)silhouetteLayer;
- (id)splashRing;
- (id)splashRing1;
- (id)splashRing3;
- (id)trackFillRingLayer;
- (void)updateForInternalBatteryDevice:(id)arg1;
- (void)updateForInternalPowerStatus:(id)arg1;

@end
