
@interface ASCAdLockupView : UIView <ASCAdLockupPresenterView, ASCLockupMediaPresenterObserver, ASCLockupPresenterObserver, ASCOfferPresenterObserver, UIGestureRecognizerDelegate> {
    ASCAdLockupPresenter * _adLockupPresenter;
    bool  _adMarkerHidden;
    ASCAdTransparencyContainerView * _adTransparencyContainer;
    bool  _automaticallyPresentsProductDetails;
    ASCLockupContentView * _contentView;
    <ASCAdLockupViewDelegate> * _delegate;
    struct { 
        unsigned int adLockupViewDidBeginRequest : 1; 
        unsigned int adLockupViewDidFinishRequest : 1; 
        unsigned int adLockupViewDidFailRequestWithError : 1; 
        unsigned int adLockupViewAppStateDidChange : 1; 
        unsigned int metricsActivityForPresentingProductDetailsOfAdLockupViewInState : 1; 
        unsigned int metricsActivityForAdLockupViewToPerformActionOfOfferInState : 1; 
        unsigned int adLockupViewDidInvalidateIntrinsicContentSize : 1; 
        unsigned int adLockupViewDidPresentProductDetails : 1; 
        unsigned int adLockupViewDidSelectOfferWithState : 1; 
        unsigned int adLockupViewDidSelectAdMarker : 1; 
        unsigned int adLockupViewDidBeginScreenshotsFetchRequest : 1; 
        unsigned int adLockupViewDidCancelScreenshotsFetchRequest : 1; 
        unsigned int adLockupViewDidFinishScreenshotsFetchRequest : 1; 
        unsigned int adLockupViewPreprocessOfferInStateCompletionBlock : 1; 
        unsigned int adLockupViewVideoStateDidChange : 1; 
    }  _delegateRespondsTo;
    ASCGradientBackgroundView * _gradientBackgroundView;
    ASCLockupMediaPresenter * _lockupMediaPresenter;
    ASCLockupPresenter * _lockupPresenter;
    ASCMaterialBackgroundView * _materialBackgroundView;
    ASCLockupMediaView * _mediaView;
    ASCAppearMetricsPresenter * _metricsPresenter;
    ASCOfferPresenter * _offerPresenter;
    NSString * _storeSheetHostBundleID;
    NSString * _storeSheetUsageContext;
    UITapGestureRecognizer * _tapGestureRecognizer;
}

@property (nonatomic, readonly) NSString *accessibilityAdvertisement;
@property (nonatomic, readonly) NSString *accessibilityUserRating;
@property (nonatomic, readonly) ASCAdLockupPresenter *adLockupPresenter;
@property (getter=isAdMarkerHidden, nonatomic) bool adMarkerHidden;
@property (nonatomic, readonly) ASCAdTransparencyContainerView *adTransparencyContainer;
@property (nonatomic) bool automaticallyPresentsProductDetails;
@property (nonatomic, readonly) ASCLockupContentView *contentView;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <ASCAdLockupViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) ASCGradientBackgroundView *gradientBackgroundView;
@property (nonatomic, retain) ASCLockupViewGroup *group;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) ASCLockup *lockup;
@property (nonatomic, readonly) ASCLockupMediaPresenter *lockupMediaPresenter;
@property (nonatomic, readonly) ASCLockupPresenter *lockupPresenter;
@property (nonatomic, readonly) ASCMaterialBackgroundView *materialBackgroundView;
@property (nonatomic, readonly) ASCLockupMediaView *mediaView;
@property (nonatomic, readonly) ASCAppearMetricsPresenter *metricsPresenter;
@property (nonatomic, readonly) ASCOfferPresenter *offerPresenter;
@property (nonatomic, readonly) UIViewController *presentingViewController;
@property (nonatomic, copy) ASCLockupRequest *request;
@property (nonatomic, retain) NSString *storeSheetHostBundleID;
@property (nonatomic, retain) NSString *storeSheetUsageContext;
@property (readonly) Class superclass;
@property (nonatomic, readonly) UITapGestureRecognizer *tapGestureRecognizer;
@property (getter=isVideoLoopingEnabled, nonatomic) bool videoLoopingEnabled;
@property (getter=isVideoMuted, nonatomic) bool videoMuted;

+ (double)topContentViewSpacing;

- (void).cxx_destruct;
- (id)_accessibilitySupplementaryFooterViews;
- (id)_accessibilitySupplementaryHeaderViews;
- (bool)accessibilityActivate;
- (id)accessibilityAdvertisement;
- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityUserRating;
- (id)adLockupPresenter;
- (id)adTransparencyContainer;
- (id)appearMetricsActivity;
- (bool)automaticallyGeneratesAppearMetrics;
- (bool)automaticallyPresentsProductDetails;
- (id)contentView;
- (id)context;
- (id)delegate;
- (id)description;
- (void)didMoveToWindow;
- (void)encodeWithCoder:(id)arg1;
- (id)gradientBackgroundView;
- (id)group;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (bool)isAccessibilityElement;
- (bool)isAdMarkerHidden;
- (bool)isHighlighted;
- (bool)isLargeSizeClass;
- (bool)isVideoLoopingEnabled;
- (bool)isVideoMuted;
- (void)layoutAdContentView;
- (void)layoutMarginsDidChange;
- (void)layoutSubviews;
- (id)lockup;
- (id)lockupMediaPresenter;
- (void)lockupMediaPresenterDidBeginScreenshotsFetchRequest;
- (void)lockupMediaPresenterDidCancelScreenshotsFetchRequest;
- (void)lockupMediaPresenterDidFinishScreenshotsFetchRequest;
- (void)lockupMediaPresenterVideoStateDidChange:(long long)arg1;
- (id)lockupPresenter;
- (void)lockupPresenterDidBeginRequest;
- (void)lockupPresenterDidFailRequestWithError:(id)arg1;
- (void)lockupPresenterDidFinishRequest;
- (id)materialBackgroundView;
- (id)mediaView;
- (id)metricsActivityForPresentingProductDetails;
- (id)metricsParametersForPresentingProductDetails;
- (id)metricsParametersFromMetricsActivity:(id)arg1;
- (id)metricsPresenter;
- (id)offerPresenter;
- (void)offerPresenterDidObserveChangeToState:(id)arg1;
- (void)offerPresenterPreprocessOffer:(id)arg1 inState:(id)arg2 completionBlock:(id /* block */)arg3;
- (void)offerPresenterWillPerformActionOfOffer:(id)arg1 inState:(id)arg2 withActivity:(inout id*)arg3 inContext:(inout id*)arg4;
- (id)offerTheme;
- (void)performAdTransparencyAction;
- (void)performLockupAction;
- (void)performOfferAction;
- (void)presentProductDetailsViewController;
- (id)presentingViewController;
- (id)request;
- (void)setAdMarkerHidden:(bool)arg1;
- (void)setAdTransparencyButtonHidden:(bool)arg1;
- (void)setAppearMetricsActivity:(id)arg1;
- (void)setAutomaticallyGeneratesAppearMetrics:(bool)arg1;
- (void)setAutomaticallyPresentsProductDetails:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDeveloperName:(id)arg1;
- (void)setGroup:(id)arg1;
- (void)setHidden:(bool)arg1;
- (void)setHighlighted:(bool)arg1;
- (void)setLayoutMargins:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setLockup:(id)arg1;
- (void)setOfferTheme:(id)arg1;
- (void)setRequest:(id)arg1;
- (void)setStoreSheetHostBundleID:(id)arg1;
- (void)setStoreSheetUsageContext:(id)arg1;
- (void)setVideoLoopingEnabled:(bool)arg1;
- (void)setVideoMuted:(bool)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)storeSheetHostBundleID;
- (id)storeSheetUsageContext;
- (id)tapGestureRecognizer;
- (void)updateLayoutMarginsForContext:(id)arg1;
- (void)updateVisibility:(long long)arg1;

@end
