
@interface CLPInstSchemaCLPNLv4TaskEvaluationStarted : SISchemaInstrumentationMessage {
    int  _evaluationEnvironment;
    int  _evaluationType;
    int  _experimentType;
    struct { 
        unsigned int evaluationType : 1; 
        unsigned int evaluationEnvironment : 1; 
        unsigned int experimentType : 1; 
        unsigned int recipeType : 1; 
        unsigned int sampleCount : 1; 
        unsigned int isDebugTask : 1; 
    }  _has;
    bool  _hasNlv4AssetVersion;
    bool  _hasNlv4AssetVersionOverride;
    bool  _hasSyntheticDatasetVersion;
    bool  _isDebugTask;
    SISchemaAsset * _nlv4AssetVersion;
    SISchemaAsset * _nlv4AssetVersionOverride;
    int  _recipeType;
    unsigned int  _sampleCount;
    SISchemaAsset * _syntheticDatasetVersion;
}

@property (nonatomic) int evaluationEnvironment;
@property (nonatomic) int evaluationType;
@property (nonatomic) int experimentType;
@property (nonatomic) bool hasEvaluationEnvironment;
@property (nonatomic) bool hasEvaluationType;
@property (nonatomic) bool hasExperimentType;
@property (nonatomic) bool hasIsDebugTask;
@property (nonatomic) bool hasNlv4AssetVersion;
@property (nonatomic) bool hasNlv4AssetVersionOverride;
@property (nonatomic) bool hasRecipeType;
@property (nonatomic) bool hasSampleCount;
@property (nonatomic) bool hasSyntheticDatasetVersion;
@property (nonatomic) bool isDebugTask;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) SISchemaAsset *nlv4AssetVersion;
@property (nonatomic, retain) SISchemaAsset *nlv4AssetVersionOverride;
@property (nonatomic) int recipeType;
@property (nonatomic) unsigned int sampleCount;
@property (nonatomic, retain) SISchemaAsset *syntheticDatasetVersion;

- (void).cxx_destruct;
- (id)applySensitiveConditionsPolicy:(id)arg1;
- (void)deleteEvaluationEnvironment;
- (void)deleteEvaluationType;
- (void)deleteExperimentType;
- (void)deleteIsDebugTask;
- (void)deleteNlv4AssetVersion;
- (void)deleteNlv4AssetVersionOverride;
- (void)deleteRecipeType;
- (void)deleteSampleCount;
- (void)deleteSyntheticDatasetVersion;
- (id)dictionaryRepresentation;
- (int)evaluationEnvironment;
- (int)evaluationType;
- (int)experimentType;
- (bool)hasEvaluationEnvironment;
- (bool)hasEvaluationType;
- (bool)hasExperimentType;
- (bool)hasIsDebugTask;
- (bool)hasNlv4AssetVersion;
- (bool)hasNlv4AssetVersionOverride;
- (bool)hasRecipeType;
- (bool)hasSampleCount;
- (bool)hasSyntheticDatasetVersion;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isDebugTask;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)nlv4AssetVersion;
- (id)nlv4AssetVersionOverride;
- (bool)readFrom:(id)arg1;
- (int)recipeType;
- (unsigned int)sampleCount;
- (void)setEvaluationEnvironment:(int)arg1;
- (void)setEvaluationType:(int)arg1;
- (void)setExperimentType:(int)arg1;
- (void)setHasEvaluationEnvironment:(bool)arg1;
- (void)setHasEvaluationType:(bool)arg1;
- (void)setHasExperimentType:(bool)arg1;
- (void)setHasIsDebugTask:(bool)arg1;
- (void)setHasNlv4AssetVersion:(bool)arg1;
- (void)setHasNlv4AssetVersionOverride:(bool)arg1;
- (void)setHasRecipeType:(bool)arg1;
- (void)setHasSampleCount:(bool)arg1;
- (void)setHasSyntheticDatasetVersion:(bool)arg1;
- (void)setIsDebugTask:(bool)arg1;
- (void)setNlv4AssetVersion:(id)arg1;
- (void)setNlv4AssetVersionOverride:(id)arg1;
- (void)setRecipeType:(int)arg1;
- (void)setSampleCount:(unsigned int)arg1;
- (void)setSyntheticDatasetVersion:(id)arg1;
- (id)suppressMessageUnderConditions;
- (id)syntheticDatasetVersion;
- (void)writeTo:(id)arg1;

@end
