
@interface DODMLASRSchemaDODMLASRLanguageModelMetrics : SISchemaInstrumentationMessage {
    struct { 
        unsigned int linearInterpolationWeight : 1; 
        unsigned int totalDurationInMs : 1; 
        unsigned int numUtterances : 1; 
        unsigned int numWords : 1; 
        unsigned int numOutOfVocabularyWords : 1; 
        unsigned int numInvalidTokens : 1; 
        unsigned int numInvalidUtterances : 1; 
        unsigned int perplexity : 1; 
        unsigned int perplexityOne : 1; 
    }  _has;
    float  _linearInterpolationWeight;
    NSArray * _ngramHits;
    unsigned int  _numInvalidTokens;
    unsigned int  _numInvalidUtterances;
    unsigned int  _numOutOfVocabularyWords;
    unsigned int  _numUtterances;
    unsigned int  _numWords;
    float  _perplexity;
    float  _perplexityOne;
    unsigned long long  _totalDurationInMs;
}

@property (nonatomic) bool hasLinearInterpolationWeight;
@property (nonatomic) bool hasNumInvalidTokens;
@property (nonatomic) bool hasNumInvalidUtterances;
@property (nonatomic) bool hasNumOutOfVocabularyWords;
@property (nonatomic) bool hasNumUtterances;
@property (nonatomic) bool hasNumWords;
@property (nonatomic) bool hasPerplexity;
@property (nonatomic) bool hasPerplexityOne;
@property (nonatomic) bool hasTotalDurationInMs;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) float linearInterpolationWeight;
@property (nonatomic, copy) NSArray *ngramHits;
@property (nonatomic) unsigned int numInvalidTokens;
@property (nonatomic) unsigned int numInvalidUtterances;
@property (nonatomic) unsigned int numOutOfVocabularyWords;
@property (nonatomic) unsigned int numUtterances;
@property (nonatomic) unsigned int numWords;
@property (nonatomic) float perplexity;
@property (nonatomic) float perplexityOne;
@property (nonatomic) unsigned long long totalDurationInMs;

- (void).cxx_destruct;
- (void)addNgramHits:(id)arg1;
- (id)applySensitiveConditionsPolicy:(id)arg1;
- (void)clearNgramHits;
- (void)deleteLinearInterpolationWeight;
- (void)deleteNgramHits;
- (void)deleteNumInvalidTokens;
- (void)deleteNumInvalidUtterances;
- (void)deleteNumOutOfVocabularyWords;
- (void)deleteNumUtterances;
- (void)deleteNumWords;
- (void)deletePerplexity;
- (void)deletePerplexityOne;
- (void)deleteTotalDurationInMs;
- (id)dictionaryRepresentation;
- (bool)hasLinearInterpolationWeight;
- (bool)hasNumInvalidTokens;
- (bool)hasNumInvalidUtterances;
- (bool)hasNumOutOfVocabularyWords;
- (bool)hasNumUtterances;
- (bool)hasNumWords;
- (bool)hasPerplexity;
- (bool)hasPerplexityOne;
- (bool)hasTotalDurationInMs;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (float)linearInterpolationWeight;
- (id)ngramHits;
- (id)ngramHitsAtIndex:(unsigned long long)arg1;
- (unsigned long long)ngramHitsCount;
- (unsigned int)numInvalidTokens;
- (unsigned int)numInvalidUtterances;
- (unsigned int)numOutOfVocabularyWords;
- (unsigned int)numUtterances;
- (unsigned int)numWords;
- (float)perplexity;
- (float)perplexityOne;
- (bool)readFrom:(id)arg1;
- (void)setHasLinearInterpolationWeight:(bool)arg1;
- (void)setHasNumInvalidTokens:(bool)arg1;
- (void)setHasNumInvalidUtterances:(bool)arg1;
- (void)setHasNumOutOfVocabularyWords:(bool)arg1;
- (void)setHasNumUtterances:(bool)arg1;
- (void)setHasNumWords:(bool)arg1;
- (void)setHasPerplexity:(bool)arg1;
- (void)setHasPerplexityOne:(bool)arg1;
- (void)setHasTotalDurationInMs:(bool)arg1;
- (void)setLinearInterpolationWeight:(float)arg1;
- (void)setNgramHits:(id)arg1;
- (void)setNumInvalidTokens:(unsigned int)arg1;
- (void)setNumInvalidUtterances:(unsigned int)arg1;
- (void)setNumOutOfVocabularyWords:(unsigned int)arg1;
- (void)setNumUtterances:(unsigned int)arg1;
- (void)setNumWords:(unsigned int)arg1;
- (void)setPerplexity:(float)arg1;
- (void)setPerplexityOne:(float)arg1;
- (void)setTotalDurationInMs:(unsigned long long)arg1;
- (id)suppressMessageUnderConditions;
- (unsigned long long)totalDurationInMs;
- (void)writeTo:(id)arg1;

@end
