
@interface SISchemaUUFRShown : SISchemaInstrumentationMessage {
    NSString * _aceViewClass;
    NSString * _aceViewID;
    NSString * _dialogIdentifier;
    SISchemaGridCardSection * _gridCardSection;
    struct { 
        unsigned int siriUILocation : 1; 
        unsigned int viewRegionDesignation : 1; 
    }  _has;
    bool  _hasAceViewClass;
    bool  _hasAceViewID;
    bool  _hasDialogIdentifier;
    bool  _hasGridCardSection;
    bool  _hasLinkId;
    bool  _hasSiriResponseContext;
    bool  _hasSnippetClass;
    bool  _hasViewID;
    SISchemaUUID * _linkId;
    SISchemaSiriResponseContext * _siriResponseContext;
    int  _siriUILocation;
    NSString * _snippetClass;
    NSString * _viewID;
    int  _viewRegionDesignation;
    unsigned long long  _whichSubsection;
}

@property (nonatomic, copy) NSString *aceViewClass;
@property (nonatomic, copy) NSString *aceViewID;
@property (nonatomic, copy) NSString *dialogIdentifier;
@property (nonatomic, retain) SISchemaGridCardSection *gridCardSection;
@property (nonatomic) bool hasAceViewClass;
@property (nonatomic) bool hasAceViewID;
@property (nonatomic) bool hasDialogIdentifier;
@property (nonatomic) bool hasGridCardSection;
@property (nonatomic) bool hasLinkId;
@property (nonatomic) bool hasSiriResponseContext;
@property (nonatomic) bool hasSiriUILocation;
@property (nonatomic) bool hasSnippetClass;
@property (nonatomic) bool hasViewID;
@property (nonatomic) bool hasViewRegionDesignation;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) SISchemaUUID *linkId;
@property (nonatomic, retain) SISchemaSiriResponseContext *siriResponseContext;
@property (nonatomic) int siriUILocation;
@property (nonatomic, copy) NSString *snippetClass;
@property (nonatomic, copy) NSString *viewID;
@property (nonatomic) int viewRegionDesignation;
@property (nonatomic, readonly) unsigned long long whichSubsection;

- (void).cxx_destruct;
- (id)aceViewClass;
- (id)aceViewID;
- (id)applySensitiveConditionsPolicy:(id)arg1;
- (void)deleteAceViewClass;
- (void)deleteAceViewID;
- (void)deleteDialogIdentifier;
- (void)deleteGridCardSection;
- (void)deleteLinkId;
- (void)deleteSiriResponseContext;
- (void)deleteSiriUILocation;
- (void)deleteSnippetClass;
- (void)deleteViewID;
- (void)deleteViewRegionDesignation;
- (id)dialogIdentifier;
- (id)dictionaryRepresentation;
- (id)gridCardSection;
- (bool)hasAceViewClass;
- (bool)hasAceViewID;
- (bool)hasDialogIdentifier;
- (bool)hasGridCardSection;
- (bool)hasLinkId;
- (bool)hasSiriResponseContext;
- (bool)hasSiriUILocation;
- (bool)hasSnippetClass;
- (bool)hasViewID;
- (bool)hasViewRegionDesignation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (id)linkId;
- (bool)readFrom:(id)arg1;
- (void)setAceViewClass:(id)arg1;
- (void)setAceViewID:(id)arg1;
- (void)setDialogIdentifier:(id)arg1;
- (void)setGridCardSection:(id)arg1;
- (void)setHasAceViewClass:(bool)arg1;
- (void)setHasAceViewID:(bool)arg1;
- (void)setHasDialogIdentifier:(bool)arg1;
- (void)setHasGridCardSection:(bool)arg1;
- (void)setHasLinkId:(bool)arg1;
- (void)setHasSiriResponseContext:(bool)arg1;
- (void)setHasSiriUILocation:(bool)arg1;
- (void)setHasSnippetClass:(bool)arg1;
- (void)setHasViewID:(bool)arg1;
- (void)setHasViewRegionDesignation:(bool)arg1;
- (void)setLinkId:(id)arg1;
- (void)setSiriResponseContext:(id)arg1;
- (void)setSiriUILocation:(int)arg1;
- (void)setSnippetClass:(id)arg1;
- (void)setViewID:(id)arg1;
- (void)setViewRegionDesignation:(int)arg1;
- (id)siriResponseContext;
- (int)siriUILocation;
- (id)snippetClass;
- (id)suppressMessageUnderConditions;
- (id)viewID;
- (int)viewRegionDesignation;
- (unsigned long long)whichSubsection;
- (void)writeTo:(id)arg1;

@end
