
@interface CAPContactFillerContactEvent : PBCodable <NSCopying> {
    double  _averageBehavioralRuleConfidence;
    double  _averageBehavioralRuleConviction;
    double  _averageBehavioralRuleLift;
    double  _averageBehavioralRuleMLScore;
    double  _averageBehavioralRulePowerFactor;
    double  _averageBehavioralRuleSupport;
    struct { 
        unsigned int averageBehavioralRuleConfidence : 1; 
        unsigned int averageBehavioralRuleConviction : 1; 
        unsigned int averageBehavioralRuleLift : 1; 
        unsigned int averageBehavioralRuleMLScore : 1; 
        unsigned int averageBehavioralRulePowerFactor : 1; 
        unsigned int averageBehavioralRuleSupport : 1; 
        unsigned int interactionModelScore : 1; 
        unsigned int maximumBehavioralRuleConfidence : 1; 
        unsigned int maximumBehavioralRuleConviction : 1; 
        unsigned int maximumBehavioralRuleLift : 1; 
        unsigned int maximumBehavioralRuleMLScore : 1; 
        unsigned int maximumBehavioralRulePowerFactor : 1; 
        unsigned int maximumBehavioralRuleSupport : 1; 
        unsigned int minimumBehavioralRuleConfidence : 1; 
        unsigned int minimumBehavioralRuleConviction : 1; 
        unsigned int minimumBehavioralRuleLift : 1; 
        unsigned int minimumBehavioralRuleMLScore : 1; 
        unsigned int minimumBehavioralRulePowerFactor : 1; 
        unsigned int minimumBehavioralRuleSupport : 1; 
        unsigned int stdevBehavioralRuleConfidence : 1; 
        unsigned int stdevBehavioralRuleConviction : 1; 
        unsigned int stdevBehavioralRuleLift : 1; 
        unsigned int stdevBehavioralRuleMLScore : 1; 
        unsigned int stdevBehavioralRulePowerFactor : 1; 
        unsigned int stdevBehavioralRuleSupport : 1; 
        unsigned int normalizedIncomingCallFrequency : 1; 
        unsigned int normalizedOutgoingCallFrequency : 1; 
        unsigned int numberOfBehavioralRulesAdvocating : 1; 
        unsigned int timeSinceLastContactViaIncomingCall : 1; 
        unsigned int timeSinceLastContactViaOutgoingCall : 1; 
    }  _has;
    double  _interactionModelScore;
    double  _maximumBehavioralRuleConfidence;
    double  _maximumBehavioralRuleConviction;
    double  _maximumBehavioralRuleLift;
    double  _maximumBehavioralRuleMLScore;
    double  _maximumBehavioralRulePowerFactor;
    double  _maximumBehavioralRuleSupport;
    double  _minimumBehavioralRuleConfidence;
    double  _minimumBehavioralRuleConviction;
    double  _minimumBehavioralRuleLift;
    double  _minimumBehavioralRuleMLScore;
    double  _minimumBehavioralRulePowerFactor;
    double  _minimumBehavioralRuleSupport;
    unsigned int  _normalizedIncomingCallFrequency;
    unsigned int  _normalizedIncomingTextFrequency;
    unsigned int  _normalizedOutgoingCallFrequency;
    unsigned int  _normalizedOutgoingTextFrequency;
    unsigned int  _normalizedShareFrequency;
    unsigned int  _numberOfBehavioralRulesAdvocating;
    double  _stdevBehavioralRuleConfidence;
    double  _stdevBehavioralRuleConviction;
    double  _stdevBehavioralRuleLift;
    double  _stdevBehavioralRuleMLScore;
    double  _stdevBehavioralRulePowerFactor;
    double  _stdevBehavioralRuleSupport;
    int  _timeSinceLastContactViaIncomingCall;
    int  _timeSinceLastContactViaIncomingText;
    int  _timeSinceLastContactViaOutgoingCall;
    int  _timeSinceLastContactViaOutgoingText;
    int  _timeSinceLastContactViaShare;
    bool  _wasShareRecipient;
}

@property (nonatomic) double averageBehavioralRuleConfidence;
@property (nonatomic) double averageBehavioralRuleConviction;
@property (nonatomic) double averageBehavioralRuleLift;
@property (nonatomic) double averageBehavioralRuleMLScore;
@property (nonatomic) double averageBehavioralRulePowerFactor;
@property (nonatomic) double averageBehavioralRuleSupport;
@property (nonatomic) bool hasAverageBehavioralRuleConfidence;
@property (nonatomic) bool hasAverageBehavioralRuleConviction;
@property (nonatomic) bool hasAverageBehavioralRuleLift;
@property (nonatomic) bool hasAverageBehavioralRuleMLScore;
@property (nonatomic) bool hasAverageBehavioralRulePowerFactor;
@property (nonatomic) bool hasAverageBehavioralRuleSupport;
@property (nonatomic) bool hasInteractionModelScore;
@property (nonatomic) bool hasMaximumBehavioralRuleConfidence;
@property (nonatomic) bool hasMaximumBehavioralRuleConviction;
@property (nonatomic) bool hasMaximumBehavioralRuleLift;
@property (nonatomic) bool hasMaximumBehavioralRuleMLScore;
@property (nonatomic) bool hasMaximumBehavioralRulePowerFactor;
@property (nonatomic) bool hasMaximumBehavioralRuleSupport;
@property (nonatomic) bool hasMinimumBehavioralRuleConfidence;
@property (nonatomic) bool hasMinimumBehavioralRuleConviction;
@property (nonatomic) bool hasMinimumBehavioralRuleLift;
@property (nonatomic) bool hasMinimumBehavioralRuleMLScore;
@property (nonatomic) bool hasMinimumBehavioralRulePowerFactor;
@property (nonatomic) bool hasMinimumBehavioralRuleSupport;
@property (nonatomic) bool hasNormalizedIncomingCallFrequency;
@property (nonatomic) bool hasNormalizedOutgoingCallFrequency;
@property (nonatomic) bool hasNumberOfBehavioralRulesAdvocating;
@property (nonatomic) bool hasStdevBehavioralRuleConfidence;
@property (nonatomic) bool hasStdevBehavioralRuleConviction;
@property (nonatomic) bool hasStdevBehavioralRuleLift;
@property (nonatomic) bool hasStdevBehavioralRuleMLScore;
@property (nonatomic) bool hasStdevBehavioralRulePowerFactor;
@property (nonatomic) bool hasStdevBehavioralRuleSupport;
@property (nonatomic) bool hasTimeSinceLastContactViaIncomingCall;
@property (nonatomic) bool hasTimeSinceLastContactViaOutgoingCall;
@property (nonatomic) double interactionModelScore;
@property (nonatomic) double maximumBehavioralRuleConfidence;
@property (nonatomic) double maximumBehavioralRuleConviction;
@property (nonatomic) double maximumBehavioralRuleLift;
@property (nonatomic) double maximumBehavioralRuleMLScore;
@property (nonatomic) double maximumBehavioralRulePowerFactor;
@property (nonatomic) double maximumBehavioralRuleSupport;
@property (nonatomic) double minimumBehavioralRuleConfidence;
@property (nonatomic) double minimumBehavioralRuleConviction;
@property (nonatomic) double minimumBehavioralRuleLift;
@property (nonatomic) double minimumBehavioralRuleMLScore;
@property (nonatomic) double minimumBehavioralRulePowerFactor;
@property (nonatomic) double minimumBehavioralRuleSupport;
@property (nonatomic) unsigned int normalizedIncomingCallFrequency;
@property (nonatomic) unsigned int normalizedIncomingTextFrequency;
@property (nonatomic) unsigned int normalizedOutgoingCallFrequency;
@property (nonatomic) unsigned int normalizedOutgoingTextFrequency;
@property (nonatomic) unsigned int normalizedShareFrequency;
@property (nonatomic) unsigned int numberOfBehavioralRulesAdvocating;
@property (nonatomic) double stdevBehavioralRuleConfidence;
@property (nonatomic) double stdevBehavioralRuleConviction;
@property (nonatomic) double stdevBehavioralRuleLift;
@property (nonatomic) double stdevBehavioralRuleMLScore;
@property (nonatomic) double stdevBehavioralRulePowerFactor;
@property (nonatomic) double stdevBehavioralRuleSupport;
@property (nonatomic) int timeSinceLastContactViaIncomingCall;
@property (nonatomic) int timeSinceLastContactViaIncomingText;
@property (nonatomic) int timeSinceLastContactViaOutgoingCall;
@property (nonatomic) int timeSinceLastContactViaOutgoingText;
@property (nonatomic) int timeSinceLastContactViaShare;
@property (nonatomic) bool wasShareRecipient;

- (int)StringAsTimeSinceLastContactViaIncomingCall:(id)arg1;
- (int)StringAsTimeSinceLastContactViaIncomingText:(id)arg1;
- (int)StringAsTimeSinceLastContactViaOutgoingCall:(id)arg1;
- (int)StringAsTimeSinceLastContactViaOutgoingText:(id)arg1;
- (int)StringAsTimeSinceLastContactViaShare:(id)arg1;
- (double)averageBehavioralRuleConfidence;
- (double)averageBehavioralRuleConviction;
- (double)averageBehavioralRuleLift;
- (double)averageBehavioralRuleMLScore;
- (double)averageBehavioralRulePowerFactor;
- (double)averageBehavioralRuleSupport;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasAverageBehavioralRuleConfidence;
- (bool)hasAverageBehavioralRuleConviction;
- (bool)hasAverageBehavioralRuleLift;
- (bool)hasAverageBehavioralRuleMLScore;
- (bool)hasAverageBehavioralRulePowerFactor;
- (bool)hasAverageBehavioralRuleSupport;
- (bool)hasInteractionModelScore;
- (bool)hasMaximumBehavioralRuleConfidence;
- (bool)hasMaximumBehavioralRuleConviction;
- (bool)hasMaximumBehavioralRuleLift;
- (bool)hasMaximumBehavioralRuleMLScore;
- (bool)hasMaximumBehavioralRulePowerFactor;
- (bool)hasMaximumBehavioralRuleSupport;
- (bool)hasMinimumBehavioralRuleConfidence;
- (bool)hasMinimumBehavioralRuleConviction;
- (bool)hasMinimumBehavioralRuleLift;
- (bool)hasMinimumBehavioralRuleMLScore;
- (bool)hasMinimumBehavioralRulePowerFactor;
- (bool)hasMinimumBehavioralRuleSupport;
- (bool)hasNormalizedIncomingCallFrequency;
- (bool)hasNormalizedOutgoingCallFrequency;
- (bool)hasNumberOfBehavioralRulesAdvocating;
- (bool)hasStdevBehavioralRuleConfidence;
- (bool)hasStdevBehavioralRuleConviction;
- (bool)hasStdevBehavioralRuleLift;
- (bool)hasStdevBehavioralRuleMLScore;
- (bool)hasStdevBehavioralRulePowerFactor;
- (bool)hasStdevBehavioralRuleSupport;
- (bool)hasTimeSinceLastContactViaIncomingCall;
- (bool)hasTimeSinceLastContactViaOutgoingCall;
- (unsigned long long)hash;
- (double)interactionModelScore;
- (bool)isEqual:(id)arg1;
- (double)maximumBehavioralRuleConfidence;
- (double)maximumBehavioralRuleConviction;
- (double)maximumBehavioralRuleLift;
- (double)maximumBehavioralRuleMLScore;
- (double)maximumBehavioralRulePowerFactor;
- (double)maximumBehavioralRuleSupport;
- (void)mergeFrom:(id)arg1;
- (double)minimumBehavioralRuleConfidence;
- (double)minimumBehavioralRuleConviction;
- (double)minimumBehavioralRuleLift;
- (double)minimumBehavioralRuleMLScore;
- (double)minimumBehavioralRulePowerFactor;
- (double)minimumBehavioralRuleSupport;
- (unsigned int)normalizedIncomingCallFrequency;
- (unsigned int)normalizedIncomingTextFrequency;
- (unsigned int)normalizedOutgoingCallFrequency;
- (unsigned int)normalizedOutgoingTextFrequency;
- (unsigned int)normalizedShareFrequency;
- (unsigned int)numberOfBehavioralRulesAdvocating;
- (bool)readFrom:(id)arg1;
- (void)setAverageBehavioralRuleConfidence:(double)arg1;
- (void)setAverageBehavioralRuleConviction:(double)arg1;
- (void)setAverageBehavioralRuleLift:(double)arg1;
- (void)setAverageBehavioralRuleMLScore:(double)arg1;
- (void)setAverageBehavioralRulePowerFactor:(double)arg1;
- (void)setAverageBehavioralRuleSupport:(double)arg1;
- (void)setHasAverageBehavioralRuleConfidence:(bool)arg1;
- (void)setHasAverageBehavioralRuleConviction:(bool)arg1;
- (void)setHasAverageBehavioralRuleLift:(bool)arg1;
- (void)setHasAverageBehavioralRuleMLScore:(bool)arg1;
- (void)setHasAverageBehavioralRulePowerFactor:(bool)arg1;
- (void)setHasAverageBehavioralRuleSupport:(bool)arg1;
- (void)setHasInteractionModelScore:(bool)arg1;
- (void)setHasMaximumBehavioralRuleConfidence:(bool)arg1;
- (void)setHasMaximumBehavioralRuleConviction:(bool)arg1;
- (void)setHasMaximumBehavioralRuleLift:(bool)arg1;
- (void)setHasMaximumBehavioralRuleMLScore:(bool)arg1;
- (void)setHasMaximumBehavioralRulePowerFactor:(bool)arg1;
- (void)setHasMaximumBehavioralRuleSupport:(bool)arg1;
- (void)setHasMinimumBehavioralRuleConfidence:(bool)arg1;
- (void)setHasMinimumBehavioralRuleConviction:(bool)arg1;
- (void)setHasMinimumBehavioralRuleLift:(bool)arg1;
- (void)setHasMinimumBehavioralRuleMLScore:(bool)arg1;
- (void)setHasMinimumBehavioralRulePowerFactor:(bool)arg1;
- (void)setHasMinimumBehavioralRuleSupport:(bool)arg1;
- (void)setHasNormalizedIncomingCallFrequency:(bool)arg1;
- (void)setHasNormalizedOutgoingCallFrequency:(bool)arg1;
- (void)setHasNumberOfBehavioralRulesAdvocating:(bool)arg1;
- (void)setHasStdevBehavioralRuleConfidence:(bool)arg1;
- (void)setHasStdevBehavioralRuleConviction:(bool)arg1;
- (void)setHasStdevBehavioralRuleLift:(bool)arg1;
- (void)setHasStdevBehavioralRuleMLScore:(bool)arg1;
- (void)setHasStdevBehavioralRulePowerFactor:(bool)arg1;
- (void)setHasStdevBehavioralRuleSupport:(bool)arg1;
- (void)setHasTimeSinceLastContactViaIncomingCall:(bool)arg1;
- (void)setHasTimeSinceLastContactViaOutgoingCall:(bool)arg1;
- (void)setInteractionModelScore:(double)arg1;
- (void)setMaximumBehavioralRuleConfidence:(double)arg1;
- (void)setMaximumBehavioralRuleConviction:(double)arg1;
- (void)setMaximumBehavioralRuleLift:(double)arg1;
- (void)setMaximumBehavioralRuleMLScore:(double)arg1;
- (void)setMaximumBehavioralRulePowerFactor:(double)arg1;
- (void)setMaximumBehavioralRuleSupport:(double)arg1;
- (void)setMinimumBehavioralRuleConfidence:(double)arg1;
- (void)setMinimumBehavioralRuleConviction:(double)arg1;
- (void)setMinimumBehavioralRuleLift:(double)arg1;
- (void)setMinimumBehavioralRuleMLScore:(double)arg1;
- (void)setMinimumBehavioralRulePowerFactor:(double)arg1;
- (void)setMinimumBehavioralRuleSupport:(double)arg1;
- (void)setNormalizedIncomingCallFrequency:(unsigned int)arg1;
- (void)setNormalizedIncomingTextFrequency:(unsigned int)arg1;
- (void)setNormalizedOutgoingCallFrequency:(unsigned int)arg1;
- (void)setNormalizedOutgoingTextFrequency:(unsigned int)arg1;
- (void)setNormalizedShareFrequency:(unsigned int)arg1;
- (void)setNumberOfBehavioralRulesAdvocating:(unsigned int)arg1;
- (void)setStdevBehavioralRuleConfidence:(double)arg1;
- (void)setStdevBehavioralRuleConviction:(double)arg1;
- (void)setStdevBehavioralRuleLift:(double)arg1;
- (void)setStdevBehavioralRuleMLScore:(double)arg1;
- (void)setStdevBehavioralRulePowerFactor:(double)arg1;
- (void)setStdevBehavioralRuleSupport:(double)arg1;
- (void)setTimeSinceLastContactViaIncomingCall:(int)arg1;
- (void)setTimeSinceLastContactViaIncomingText:(int)arg1;
- (void)setTimeSinceLastContactViaOutgoingCall:(int)arg1;
- (void)setTimeSinceLastContactViaOutgoingText:(int)arg1;
- (void)setTimeSinceLastContactViaShare:(int)arg1;
- (void)setWasShareRecipient:(bool)arg1;
- (double)stdevBehavioralRuleConfidence;
- (double)stdevBehavioralRuleConviction;
- (double)stdevBehavioralRuleLift;
- (double)stdevBehavioralRuleMLScore;
- (double)stdevBehavioralRulePowerFactor;
- (double)stdevBehavioralRuleSupport;
- (int)timeSinceLastContactViaIncomingCall;
- (id)timeSinceLastContactViaIncomingCallAsString:(int)arg1;
- (int)timeSinceLastContactViaIncomingText;
- (id)timeSinceLastContactViaIncomingTextAsString:(int)arg1;
- (int)timeSinceLastContactViaOutgoingCall;
- (id)timeSinceLastContactViaOutgoingCallAsString:(int)arg1;
- (int)timeSinceLastContactViaOutgoingText;
- (id)timeSinceLastContactViaOutgoingTextAsString:(int)arg1;
- (int)timeSinceLastContactViaShare;
- (id)timeSinceLastContactViaShareAsString:(int)arg1;
- (bool)wasShareRecipient;
- (void)writeTo:(id)arg1;

@end
