
@interface AAUISignInViewController : UIViewController <AKAppleIDAuthenticationInAppContextPasswordDelegate, RemoteUIControllerDelegate, UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate> {
    bool  __showsChildSignIn;
    UIStackView * _actionButtonsStackView;
    long long  _akServiceType;
    bool  _allowSkip;
    bool  _allowsAccountCreation;
    AAUIAppleLogoMicaView * _appleLogoMicaView;
    bool  _canEditUsername;
    UIColor * _cellBackgroundColor;
    bool  _childSetupFlow;
    NSArray * _compactConstraints;
    OBBoldTrayButton * _continueButton;
    <AAUISignInViewControllerDelegate> * _delegate;
    NSArray * _expandedConstraints;
    NSString * _footerText;
    UIImage * _headerImage;
    bool  _hideCreationAndForgotPasswordButton;
    bool  _isPhoneNumberLoginSupported;
    bool  _isProxEnabled;
    UIView * _logoContainerView;
    NSString * _messageLabel;
    double  _navigationBarHeightPortrait;
    AAUIOBHeaderView * _obHeaderView;
    UMUserPersona * _originalPersona;
    UMUserPersonaContext * _originalPersonaContext;
    AKBasicLoginTableViewCell * _passwordCell;
    id /* block */  _passwordHandler;
    NSArray * _privacyLinkIdentifiers;
    AAUIProximityAuthController * _proxController;
    bool  _shouldAnticipatePiggybacking;
    bool  _shouldShowSystemBackButton;
    bool  _showServiceIcons;
    bool  _showingPasswordCell;
    AAUISignInViewControllerTableFooterView * _tableFooterView;
    UITableViewHeaderFooterView * _tableHeaderView;
    UITableView * _tableView;
    long long  _tableViewStyle;
    NSString * _username;
    AKBasicLoginTableViewCell * _usernameCell;
}

@property (setter=_setAkServiceType:, nonatomic) long long _akServiceType;
@property (setter=_setShouldAnticipatePiggybacking:, nonatomic) bool _shouldAnticipatePiggybacking;
@property (setter=setShowsChildSignIn:, nonatomic) bool _showsChildSignIn;
@property (nonatomic) bool allowSkip;
@property (nonatomic) bool allowsAccountCreation;
@property (nonatomic, retain) AAUIAppleLogoMicaView *appleLogoMicaView;
@property (nonatomic) bool canEditUsername;
@property (nonatomic, retain) UIColor *cellBackgroundColor;
@property (getter=isChildSetupFlow, nonatomic) bool childSetupFlow;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <AAUISignInViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSString *footerText;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) UIImageView *headerImageView;
@property (nonatomic) bool hideCreationAndForgotPasswordButton;
@property (nonatomic) bool isPhoneNumberLoginSupported;
@property (setter=setProxEnabled:, nonatomic) bool isProxEnabled;
@property (nonatomic, retain) UIView *logoContainerView;
@property (nonatomic) NSString *messageLabel;
@property (nonatomic, copy) NSArray *privacyLinkIdentifiers;
@property (nonatomic, retain) AAUIProximityAuthController *proxController;
@property (nonatomic) bool shouldShowSystemBackButton;
@property (nonatomic) bool showServiceIcons;
@property (nonatomic) bool showingPasswordCell;
@property (readonly) Class superclass;
@property (nonatomic) long long tableViewStyle;
@property (nonatomic, copy) NSString *username;
@property (nonatomic, retain) AAUIBuddyView *view;

+ (bool)_isRunningInBridge;
+ (bool)_isRunningInSettings;
+ (void)phoneNumberSupportedWithCompletion:(id /* block */)arg1;

- (void).cxx_destruct;
- (void)_actionButtonSelected:(id)arg1;
- (id)_actionButtonsStackView;
- (long long)_akServiceType;
- (void)_attemptAuthentication;
- (void)_attemptAuthenticationWithContext:(id)arg1;
- (id)_authorizationValueForAuthenticationResults:(id)arg1;
- (id)_backBarButtonItem;
- (void)_beginObservingKeyboardWillShowNotifications;
- (void)_beginObservingSizeCategoryNotification;
- (void)_beginObservingTextFieldDidChangeNotifications;
- (id)_cancelBarButtonItem;
- (void)_cancelButtonSelected:(id)arg1;
- (void)_cancelPasswordDelegateIfNecessary;
- (void)_childSignInSelected:(id)arg1;
- (id)_continueButton;
- (void)_continueButtonSelected:(id)arg1;
- (id)_defaultHeaderImage;
- (void)_delegate_signInViewControllerDidCancel;
- (void)_delegate_signInViewControllerDidCompleteWithAuthenticationResults:(id)arg1;
- (void)_delegate_signInViewControllerDidSkip;
- (void)_endObservingKeyboardWillShowNotifications;
- (void)_endObservingSizeCategoryNotification;
- (void)_endObservingTextFieldDidChangeNotifications;
- (void)_formatUsernameAsPhoneNumberIfNeeded;
- (bool)_hasValidCredentials;
- (bool)_isGreenTeaCapable;
- (bool)_isPasswordFieldVisible;
- (void)_keyboardWillHide:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (double)_navigationBarHeight;
- (id)_passwordCell;
- (id)_passwordFieldIndexPath;
- (id)_prepareOBHeaderView;
- (void)_presentCreateAppleIDPane;
- (void)_presentForgotAppleIDPane;
- (void)_prewarmSignInFlowIfApplicable;
- (void)_repairCloudAccountWithAuthenticationResults:(id)arg1;
- (void)_resignFirstResponderForAppropriateTextField;
- (id)_serverFriendlyUsername:(id)arg1;
- (void)_setAkServiceType:(long long)arg1;
- (void)_setContinueButtonEnabled:(bool)arg1;
- (void)_setEnabled:(bool)arg1;
- (void)_setPasswordFieldHidden:(bool)arg1;
- (void)_setShouldAnticipatePiggybacking:(bool)arg1;
- (void)_setUsernameCellWaiting:(bool)arg1;
- (bool)_shouldAnticipatePiggybacking;
- (bool)_shouldDisableProximityAppleIDAdvertisement;
- (bool)_shouldShowChildSignButton;
- (bool)_showOnlyPassword;
- (bool)_showsChildSignIn;
- (id)_tableFooterView;
- (id)_tableHeaderView;
- (id)_tableView;
- (void)_textFieldDidChange:(id)arg1;
- (void)_updateContentInsetWithHeight:(double)arg1;
- (void)_updateExpandingViewInFooter;
- (void)_updateScrollIndicatorInsetWithHeight:(double)arg1;
- (id)_usernameCell;
- (bool)allowSkip;
- (bool)allowsAccountCreation;
- (id)appleLogoMicaView;
- (id)authenticationContext;
- (bool)canEditUsername;
- (id)cellBackgroundColor;
- (void)constrainView:(id)arg1 toFillHeaderFooterView:(id)arg2;
- (void)context:(id)arg1 needsPasswordWithCompletion:(id /* block */)arg2;
- (void)dealloc;
- (id)delegate;
- (id)footerText;
- (id)forgotButtonLocalizedString;
- (id)headerImageView;
- (bool)hideCreationAndForgotPasswordButton;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (bool)isChildSetupFlow;
- (bool)isPhoneNumberLoginSupported;
- (bool)isProxEnabled;
- (void)loadView;
- (id)logoContainerView;
- (id)messageLabel;
- (void)nextButtonTapped;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)passwordCellTapped:(id)arg1;
- (id)privacyLinkIdentifiers;
- (id)proxController;
- (bool)remoteUIController:(id)arg1 shouldLoadRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)setAllowSkip:(bool)arg1;
- (void)setAllowsAccountCreation:(bool)arg1;
- (void)setAppleLogoMicaView:(id)arg1;
- (void)setCanEditUsername:(bool)arg1;
- (void)setCellBackgroundColor:(id)arg1;
- (void)setChildSetupFlow:(bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFooterText:(id)arg1;
- (void)setHeaderImage:(id)arg1;
- (void)setHideCreationAndForgotPasswordButton:(bool)arg1;
- (void)setIsPhoneNumberLoginSupported:(bool)arg1;
- (void)setLogoContainerView:(id)arg1;
- (void)setMessageLabel:(id)arg1;
- (void)setPrivacyLinkIdentifiers:(id)arg1;
- (void)setProxController:(id)arg1;
- (void)setProxEnabled:(bool)arg1;
- (void)setShouldShowSystemBackButton:(bool)arg1;
- (void)setShowServiceIcons:(bool)arg1;
- (void)setShowingPasswordCell:(bool)arg1;
- (void)setShowsChildSignIn:(bool)arg1;
- (void)setTableViewStyle:(long long)arg1;
- (void)setUsername:(id)arg1;
- (bool)shouldShowSystemBackButton;
- (bool)showServiceIcons;
- (bool)showingPasswordCell;
- (void)sizeCategoryDidChange:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (bool)tableView:(id)arg1 shouldDrawTopSeparatorForSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableViewStyle;
- (bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2 replacementString:(id)arg3;
- (bool)textFieldShouldReturn:(id)arg1;
- (id)username;
- (void)usernameCellTapped:(id)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillLayoutSubviews;

@end
