
@interface GEOTransitSuggestedRoute : PBCodable <GEOCompanionCompatibility, NSCopying> {
    unsigned int  _absEndTime;
    unsigned int  _absStartTime;
    GEOAdvisoriesInfo * _advisoriesInfo;
    GEOTransitRouteDisplayStrings * _displayStrings;
    GEOTransitEngineDebugData * _engineDebugData;
    struct { 
        unsigned int has_absEndTime : 1; 
        unsigned int has_absStartTime : 1; 
        unsigned int has_rank : 1; 
        unsigned int has_travelTimeAggressiveEstimate : 1; 
        unsigned int has_travelTimeConservativeEstimate : 1; 
        unsigned int has_supportsRouteUpdates : 1; 
        unsigned int read_unknownFields : 1; 
        unsigned int read_routeBadges : 1; 
        unsigned int read_advisoriesInfo : 1; 
        unsigned int read_displayStrings : 1; 
        unsigned int read_engineDebugData : 1; 
        unsigned int read_routeHandle : 1; 
        unsigned int read_routePlanningArtworks : 1; 
        unsigned int read_sectionOptions : 1; 
        unsigned int read_sections : 1; 
        unsigned int read_steps : 1; 
        unsigned int read_transitIncidentMessage : 1; 
        unsigned int wrote_anyField : 1; 
    }  _flags;
    unsigned int  _rank;
    PBDataReader * _reader;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _readerLock;
    unsigned int  _readerMarkLength;
    unsigned int  _readerMarkPos;
    struct { 
        int *list; 
        unsigned long long count; 
        unsigned long long size; 
    }  _routeBadges;
    NSData * _routeHandle;
    NSMutableArray * _routePlanningArtworks;
    NSMutableArray * _sectionOptions;
    NSMutableArray * _sections;
    NSMutableArray * _steps;
    bool  _supportsRouteUpdates;
    GEOPBTransitRoutingIncidentMessage * _transitIncidentMessage;
    unsigned int  _travelTimeAggressiveEstimate;
    unsigned int  _travelTimeConservativeEstimate;
    PBUnknownFields * _unknownFields;
}

@property (nonatomic) unsigned int absEndTime;
@property (nonatomic) unsigned int absStartTime;
@property (nonatomic, retain) GEOAdvisoriesInfo *advisoriesInfo;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) GEOTransitRouteDisplayStrings *displayStrings;
@property (nonatomic, retain) GEOTransitEngineDebugData *engineDebugData;
@property (nonatomic) bool hasAbsEndTime;
@property (nonatomic) bool hasAbsStartTime;
@property (nonatomic, readonly) bool hasAdvisoriesInfo;
@property (nonatomic, readonly) bool hasDisplayStrings;
@property (nonatomic, readonly) bool hasEngineDebugData;
@property (nonatomic) bool hasRank;
@property (nonatomic, readonly) bool hasRouteHandle;
@property (nonatomic) bool hasSupportsRouteUpdates;
@property (nonatomic, readonly) bool hasTransitIncidentMessage;
@property (nonatomic) bool hasTravelTimeAggressiveEstimate;
@property (nonatomic) bool hasTravelTimeConservativeEstimate;
@property (readonly) unsigned long long hash;
@property (nonatomic) unsigned int rank;
@property (nonatomic, readonly) int*routeBadges;
@property (nonatomic, readonly) unsigned long long routeBadgesCount;
@property (nonatomic, retain) NSData *routeHandle;
@property (nonatomic, retain) NSMutableArray *routePlanningArtworks;
@property (nonatomic, retain) NSMutableArray *sectionOptions;
@property (nonatomic, retain) NSMutableArray *sections;
@property (nonatomic, retain) NSMutableArray *steps;
@property (readonly) Class superclass;
@property (nonatomic) bool supportsRouteUpdates;
@property (nonatomic, retain) GEOPBTransitRoutingIncidentMessage *transitIncidentMessage;
@property (nonatomic) unsigned int travelTimeAggressiveEstimate;
@property (nonatomic) unsigned int travelTimeConservativeEstimate;
@property (nonatomic, readonly) PBUnknownFields *unknownFields;
@property (getter=isWalkingOnlyRoute, nonatomic, readonly) bool walkingOnlyRoute;

+ (bool)isValid:(id)arg1;
+ (Class)routePlanningArtworkType;
+ (Class)sectionOptionType;
+ (Class)sectionType;
+ (Class)stepsType;

- (void).cxx_destruct;
- (int)StringAsRouteBadges:(id)arg1;
- (unsigned int)absEndTime;
- (unsigned int)absStartTime;
- (void)addRouteBadge:(int)arg1;
- (void)addRoutePlanningArtwork:(id)arg1;
- (void)addSection:(id)arg1;
- (void)addSectionOption:(id)arg1;
- (void)addSteps:(id)arg1;
- (id)advisoriesInfo;
- (void)clearRouteBadges;
- (void)clearRoutePlanningArtworks;
- (void)clearSectionOptions;
- (void)clearSections;
- (void)clearSteps;
- (void)clearUnknownFields:(bool)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayStrings;
- (id)engineDebugData;
- (bool)hasAbsEndTime;
- (bool)hasAbsStartTime;
- (bool)hasAdvisoriesInfo;
- (bool)hasDisplayStrings;
- (bool)hasEngineDebugData;
- (bool)hasGreenTeaWithValue:(bool)arg1;
- (bool)hasRank;
- (bool)hasRouteHandle;
- (bool)hasSupportsRouteUpdates;
- (bool)hasTransitIncidentMessage;
- (bool)hasTravelTimeAggressiveEstimate;
- (bool)hasTravelTimeConservativeEstimate;
- (unsigned long long)hash;
- (id)init;
- (id)initWithData:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (id)instanceCompatibleWithProtocolVersion:(unsigned long long)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isWalkingOnlyRoute;
- (id)jsonRepresentation;
- (void)mergeFrom:(id)arg1;
- (id)nextOptionForOption:(id)arg1 withRideIndex:(unsigned long long)arg2;
- (unsigned int)rank;
- (void)readAll:(bool)arg1;
- (bool)readFrom:(id)arg1;
- (int)routeBadgeAtIndex:(unsigned long long)arg1;
- (int*)routeBadges;
- (id)routeBadgesAsString:(int)arg1;
- (unsigned long long)routeBadgesCount;
- (id)routeHandle;
- (id)routePlanningArtworkAtIndex:(unsigned long long)arg1;
- (id)routePlanningArtworks;
- (unsigned long long)routePlanningArtworksCount;
- (id)sectionAtIndex:(unsigned long long)arg1;
- (id)sectionOptionAtIndex:(unsigned long long)arg1;
- (id)sectionOptions;
- (unsigned long long)sectionOptionsCount;
- (id)sections;
- (unsigned long long)sectionsCount;
- (void)setAbsEndTime:(unsigned int)arg1;
- (void)setAbsStartTime:(unsigned int)arg1;
- (void)setAdvisoriesInfo:(id)arg1;
- (void)setDisplayStrings:(id)arg1;
- (void)setEngineDebugData:(id)arg1;
- (void)setHasAbsEndTime:(bool)arg1;
- (void)setHasAbsStartTime:(bool)arg1;
- (void)setHasRank:(bool)arg1;
- (void)setHasSupportsRouteUpdates:(bool)arg1;
- (void)setHasTravelTimeAggressiveEstimate:(bool)arg1;
- (void)setHasTravelTimeConservativeEstimate:(bool)arg1;
- (void)setRank:(unsigned int)arg1;
- (void)setRouteBadges:(int*)arg1 count:(unsigned long long)arg2;
- (void)setRouteHandle:(id)arg1;
- (void)setRoutePlanningArtworks:(id)arg1;
- (void)setSectionOptions:(id)arg1;
- (void)setSections:(id)arg1;
- (void)setSteps:(id)arg1;
- (void)setSupportsRouteUpdates:(bool)arg1;
- (void)setTransitIncidentMessage:(id)arg1;
- (void)setTravelTimeAggressiveEstimate:(unsigned int)arg1;
- (void)setTravelTimeConservativeEstimate:(unsigned int)arg1;
- (id)steps;
- (id)stepsAtIndex:(unsigned long long)arg1;
- (unsigned long long)stepsCount;
- (bool)supportsRouteUpdates;
- (id)transitIncidentMessage;
- (unsigned int)travelTimeAggressiveEstimate;
- (unsigned int)travelTimeConservativeEstimate;
- (id)unknownFields;
- (void)writeTo:(id)arg1;

@end
