
@interface WiFiUsagePoorLinkSession : WiFiUsageSession {
    bool  _alerted;
    long long  _badLinkRssi;
    NSString * _bssidAtTD;
    double  _decision_ActiveProbe_Duration;
    double  _decision_AutoLeave_Duration;
    double  _decision_BeaconPER_Duration;
    double  _decision_FWTxPER_Duration;
    double  _decision_FastTD_Duration;
    double  _decision_GatewayARPFailure_Duration;
    double  _decision_SymptomsDNSError_Duration;
    double  _decision_TxPER_Duration;
    NSObject<OS_dispatch_source> * _endSessionTimer;
    long long  _goodLinkRssi;
    NSString * _interface;
    bool  _isLastDecisionStateValid;
    bool  _isLastFastTdVotesValid;
    bool  _isLastSuppressStateValid;
    bool  _justJoined;
    NSDate * _lastDecisionAt;
    NSDate * _lastFastTDVotesAt;
    NSDate * _lastJoinAt;
    NSDate * _lastLinkDownAt;
    NSDate * _lastSuppressAt;
    NSDate * _lastTDEval_AlertedAt;
    NSDate * _lastTDEval_ConfirmedAt;
    NSDate * _lastTDEval_ExecutedAt;
    double  _lastTDEval_TDEvalDuration;
    long long  _lastTDEval_rssiAtTD;
    double  _lastTDEval_waitOnRoamStatusDuration;
    NSString * _lastTdEval_EndedBy;
    NSString * _lastTdEval_StartedBy;
    bool  _lastTdRecommended;
    struct { 
        bool decision_TxPER; 
        bool decision_BeaconPER; 
        bool decision_FWTxPER; 
        bool decision_GatewayARPFailure; 
        bool decision_SymptomsDNSError; 
        bool decision_AutoLeave; 
        bool decision_ActiveProbe; 
        bool decision_FastTD; 
        int tdMode; 
        bool motionbasedAggressiveTDEnabled; 
        bool walkoutDetected; 
        bool waitForRoam; 
        bool edgeBSS; 
        bool appsUsingWiFi; 
        bool monitorMode; 
        long long autoLeaveRSSIthreshold; 
    }  _last_DecisionState;
    struct { 
        unsigned long long fastTD_voteCount; 
        bool fastTD_vote_recommendation; 
        bool fastTD_vote_TxPER; 
        bool fastTD_vote_BeaconPER; 
        bool fastTD_vote_FWTxPER; 
        bool fastTD_RTApp; 
        bool fastTD_Cheap5G; 
    }  _last_FastTdVotes;
    unsigned long long  _last_RSSIMode;
    struct { 
        bool aggressiveTDEnabled; 
        bool rnfAllowed; 
        bool fastTD; 
        bool suppress_SymptomDataStallScoreGood; 
        bool suppress_SymptomAppPolicyScore; 
        bool suppress_FastCheapCellular; 
        bool suppress_2dBGuard; 
        bool suppress_NoFGnetwApp; 
        bool suppress_TTR; 
        bool suppress_UserInput; 
        bool suppress_GoodAfterRoam; 
        bool defer_activeProbing; 
        bool defer_roaming; 
    }  _last_SuppressState;
    bool  _linkIsUp;
    bool  _nextJoinIsSameSSID;
    NSString * _nextJoinReason;
    bool  _nextJoinWhileDeferJoin;
    bool  _nextLinkUpIsSameBSSID;
    unsigned long long  _perBSSID_deferJoin;
    double  _perCoreRSSI_Core0_Duration;
    double  _perCoreRSSI_Core1_Duration;
    double  _perCoreRSSI_NotUsed_Duration;
    unsigned long long  _perSSID_deferJoin;
    NSObject<OS_dispatch_queue> * _queue;
    unsigned long long  _roamStatus_FailedFilteredOut_Count_BeforeTDWait;
    unsigned long long  _roamStatus_FailedFilteredOut_Count_WhileTDWait;
    unsigned long long  _roamStatus_FailedNotFound_Count_BeforeTDWait;
    unsigned long long  _roamStatus_FailedNotFound_Count_WhileTDWait;
    unsigned long long  _roamStatus_Failed_Count_BeforeTDWait;
    unsigned long long  _roamStatus_Failed_Count_WhileTDWait;
    unsigned long long  _roamStatus_Succeeded_Count_BeforeTDWait;
    unsigned long long  _roamStatus_Succeeded_Count_WhileTDWait;
    long long  _rssiAtJoin;
    long long  _rssiAtNextLinkUp;
    int  _sessionEndedBy;
    int  _sessionStartedBy;
    NSString * _ssidAtTD;
    double  _suppress_2dBGuard;
    double  _suppress_ActiveProbing;
    double  _suppress_FastCheapCellular_Duration;
    double  _suppress_GoodAfterRoam_Duration;
    double  _suppress_NoFgNetwApp_Duration;
    double  _suppress_Roam_Duration;
    double  _suppress_SymptomsAppPolicy_Duration;
    double  _suppress_SymptomsNODataStall_Duration;
    double  _suppress_TTR_Duration;
    double  _suppress_UserInput_Duration;
    bool  _tdConfirmed;
    double  _tdEvalDurationCumulative;
    bool  _tdExecuted;
    bool  _tdRecommendAtJoin;
    bool  _tdRecommendAtNextLinkUp;
    double  _timeSinceJoinATStart;
    double  _timeToNextJoin;
    bool  _toBeClosedAfterLQM;
    bool  _toBeClosedAfterTdLogicEnd;
    double  _vote_FastTD_BeaconPER_Duration;
    double  _vote_FastTD_FWTxPER_Duration;
    double  _vote_FastTD_Recommendation_Duration;
    double  _vote_FastTD_TXPER_Duration;
    unsigned long long  _waitOnRoamStatusDurationCumulative;
    bool  _waitingOnLinkUp;
}

@property (nonatomic) double decision_ActiveProbe_Duration;
@property (nonatomic) double decision_AutoLeave_Duration;
@property (nonatomic) double decision_BeaconPER_Duration;
@property (nonatomic) double decision_FWTxPER_Duration;
@property (nonatomic) double decision_FastTD_Duration;
@property (nonatomic) double decision_GatewayARPFailure_Duration;
@property (nonatomic) double decision_SymptomsDNSError_Duration;
@property (nonatomic) double decision_TxPER_Duration;
@property (nonatomic) bool isLastDecisionStateValid;
@property (nonatomic) bool isLastFastTdVotesValid;
@property (nonatomic) bool isLastSuppressStateValid;
@property (nonatomic, retain) NSDate *lastTDEval_AlertedAt;
@property (nonatomic, retain) NSDate *lastTDEval_ConfirmedAt;
@property (nonatomic, retain) NSDate *lastTDEval_ExecutedAt;
@property (nonatomic) double lastTDEval_TDEvalDuration;
@property (nonatomic) long long lastTDEval_rssiAtTD;
@property (nonatomic) double lastTDEval_waitOnRoamStatusDuration;
@property (nonatomic, retain) NSString *lastTdEval_EndedBy;
@property (nonatomic, retain) NSString *lastTdEval_StartedBy;
@property (nonatomic) struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; int x9; bool x10; bool x11; bool x12; bool x13; bool x14; bool x15; long long x16; } last_DecisionState;
@property (nonatomic) struct { unsigned long long x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; } last_FastTdVotes;
@property (nonatomic) unsigned long long last_RSSIMode;
@property (nonatomic) struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; bool x9; bool x10; bool x11; bool x12; bool x13; } last_SuppressState;
@property (nonatomic) bool nextJoinIsSameSSID;
@property (nonatomic, retain) NSString *nextJoinReason;
@property (nonatomic) bool nextJoinWhileDeferJoin;
@property (nonatomic) bool nextLinkUpIsSameBSSID;
@property (nonatomic) double perCoreRSSI_Core0_Duration;
@property (nonatomic) double perCoreRSSI_Core1_Duration;
@property (nonatomic) double perCoreRSSI_NotUsed_Duration;
@property (nonatomic) unsigned long long roamStatus_FailedFilteredOut_Count_BeforeTDWait;
@property (nonatomic) unsigned long long roamStatus_FailedFilteredOut_Count_WhileTDWait;
@property (nonatomic) unsigned long long roamStatus_FailedNotFound_Count_BeforeTDWait;
@property (nonatomic) unsigned long long roamStatus_FailedNotFound_Count_WhileTDWait;
@property (nonatomic) unsigned long long roamStatus_Failed_Count_BeforeTDWait;
@property (nonatomic) unsigned long long roamStatus_Failed_Count_WhileTDWait;
@property (nonatomic) unsigned long long roamStatus_Succeeded_Count_BeforeTDWait;
@property (nonatomic) unsigned long long roamStatus_Succeeded_Count_WhileTDWait;
@property (nonatomic) long long rssiAtJoin;
@property (nonatomic) long long rssiAtNextLinkUp;
@property (nonatomic) int sessionEndedBy;
@property (nonatomic) int sessionStartedBy;
@property (nonatomic) double suppress_2dBGuard;
@property (nonatomic) double suppress_ActiveProbing;
@property (nonatomic) double suppress_FastCheapCellular_Duration;
@property (nonatomic) double suppress_GoodAfterRoam_Duration;
@property (nonatomic) double suppress_NoFgNetwApp_Duration;
@property (nonatomic) double suppress_Roam_Duration;
@property (nonatomic) double suppress_SymptomsAppPolicy_Duration;
@property (nonatomic) double suppress_SymptomsNODataStall_Duration;
@property (nonatomic) double suppress_TTR_Duration;
@property (nonatomic) double suppress_UserInput_Duration;
@property (nonatomic) bool tdConfirmed;
@property (nonatomic) double tdEvalDurationCumulative;
@property (nonatomic) bool tdExecuted;
@property (nonatomic) bool tdRecommendAtJoin;
@property (nonatomic) bool tdRecommendAtNextLinkUp;
@property (nonatomic) double timeSinceJoinATStart;
@property (nonatomic) double timeToNextJoin;
@property (nonatomic) double vote_FastTD_BeaconPER_Duration;
@property (nonatomic) double vote_FastTD_FWTxPER_Duration;
@property (nonatomic) double vote_FastTD_Recommendation_Duration;
@property (nonatomic) double vote_FastTD_TXPER_Duration;
@property (nonatomic) unsigned long long waitOnRoamStatusDurationCumulative;

+ (id)describeWiFiUsageMonitor_tdDecisionState:(struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; int x9; bool x10; bool x11; bool x12; bool x13; bool x14; bool x15; long long x16; })arg1;
+ (id)describeWiFiUsageMonitor_tdExecState:(struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; bool x9; bool x10; bool x11; bool x12; bool x13; })arg1;
+ (id)describeWiFiUsageMonitor_tdFastTDState:(struct { unsigned long long x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; })arg1;
+ (id)sessionEndedBy:(int)arg1;
+ (id)sessionStartedBy:(int)arg1;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)decision_ActiveProbe_Duration;
- (double)decision_AutoLeave_Duration;
- (double)decision_BeaconPER_Duration;
- (double)decision_FWTxPER_Duration;
- (double)decision_FastTD_Duration;
- (double)decision_GatewayARPFailure_Duration;
- (double)decision_SymptomsDNSError_Duration;
- (double)decision_TxPER_Duration;
- (bool)driverDoesNotRecommendTd:(unsigned long long)arg1;
- (id)eventDictionary:(bool)arg1;
- (bool)expectsLQMUpdates;
- (void)faultEventDetected:(unsigned long long)arg1;
- (id)initWithInterfaceName:(id)arg1 onQueue:(id)arg2;
- (bool)isBadRssi:(long long)arg1;
- (bool)isGoodRssi:(long long)arg1;
- (bool)isLastDecisionStateValid;
- (bool)isLastFastTdVotesValid;
- (bool)isLastSuppressStateValid;
- (void)joinStateDidChange:(id)arg1 withReason:(unsigned long long)arg2 lastDisconnectReason:(long long)arg3 lastJoinFailure:(long long)arg4 andNetworkDetails:(id)arg5;
- (id)lastTDEval_AlertedAt;
- (id)lastTDEval_ConfirmedAt;
- (id)lastTDEval_ExecutedAt;
- (double)lastTDEval_TDEvalDuration;
- (long long)lastTDEval_rssiAtTD;
- (double)lastTDEval_waitOnRoamStatusDuration;
- (id)lastTdEval_EndedBy;
- (id)lastTdEval_StartedBy;
- (struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; int x9; bool x10; bool x11; bool x12; bool x13; bool x14; bool x15; long long x16; })last_DecisionState;
- (struct { unsigned long long x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; })last_FastTdVotes;
- (unsigned long long)last_RSSIMode;
- (struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; bool x9; bool x10; bool x11; bool x12; bool x13; })last_SuppressState;
- (void)linkQualityDidChange:(id)arg1;
- (void)linkStateDidChange:(bool)arg1 isInvoluntary:(bool)arg2 linkChangeReason:(long long)arg3 linkChangeSubreason:(long long)arg4 withNetworkDetails:(id)arg5;
- (id)metricName;
- (bool)nextJoinIsSameSSID;
- (id)nextJoinReason;
- (bool)nextJoinWhileDeferJoin;
- (bool)nextLinkUpIsSameBSSID;
- (double)perCoreRSSI_Core0_Duration;
- (double)perCoreRSSI_Core1_Duration;
- (double)perCoreRSSI_NotUsed_Duration;
- (unsigned long long)roamStatus_FailedFilteredOut_Count_BeforeTDWait;
- (unsigned long long)roamStatus_FailedFilteredOut_Count_WhileTDWait;
- (unsigned long long)roamStatus_FailedNotFound_Count_BeforeTDWait;
- (unsigned long long)roamStatus_FailedNotFound_Count_WhileTDWait;
- (unsigned long long)roamStatus_Failed_Count_BeforeTDWait;
- (unsigned long long)roamStatus_Failed_Count_WhileTDWait;
- (unsigned long long)roamStatus_Succeeded_Count_BeforeTDWait;
- (unsigned long long)roamStatus_Succeeded_Count_WhileTDWait;
- (void)roamingStateDidChange:(bool)arg1 reason:(unsigned long long)arg2 andStatus:(unsigned long long)arg3 andLatency:(unsigned long long)arg4 andRoamData:(id)arg5 andPingPongStats:(id)arg6;
- (long long)rssiAtJoin;
- (long long)rssiAtNextLinkUp;
- (void)sessionDidEnd:(int)arg1;
- (void)sessionDidStart:(int)arg1;
- (int)sessionEndedBy;
- (int)sessionStartedBy;
- (void)setDecision_ActiveProbe_Duration:(double)arg1;
- (void)setDecision_AutoLeave_Duration:(double)arg1;
- (void)setDecision_BeaconPER_Duration:(double)arg1;
- (void)setDecision_FWTxPER_Duration:(double)arg1;
- (void)setDecision_FastTD_Duration:(double)arg1;
- (void)setDecision_GatewayARPFailure_Duration:(double)arg1;
- (void)setDecision_SymptomsDNSError_Duration:(double)arg1;
- (void)setDecision_TxPER_Duration:(double)arg1;
- (void)setIsLastDecisionStateValid:(bool)arg1;
- (void)setIsLastFastTdVotesValid:(bool)arg1;
- (void)setIsLastSuppressStateValid:(bool)arg1;
- (void)setLastTDEval_AlertedAt:(id)arg1;
- (void)setLastTDEval_ConfirmedAt:(id)arg1;
- (void)setLastTDEval_ExecutedAt:(id)arg1;
- (void)setLastTDEval_TDEvalDuration:(double)arg1;
- (void)setLastTDEval_rssiAtTD:(long long)arg1;
- (void)setLastTDEval_waitOnRoamStatusDuration:(double)arg1;
- (void)setLastTdEval_EndedBy:(id)arg1;
- (void)setLastTdEval_StartedBy:(id)arg1;
- (void)setLast_DecisionState:(struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; int x9; bool x10; bool x11; bool x12; bool x13; bool x14; bool x15; long long x16; })arg1;
- (void)setLast_FastTdVotes:(struct { unsigned long long x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; })arg1;
- (void)setLast_RSSIMode:(unsigned long long)arg1;
- (void)setLast_SuppressState:(struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; bool x9; bool x10; bool x11; bool x12; bool x13; })arg1;
- (void)setNextJoinIsSameSSID:(bool)arg1;
- (void)setNextJoinReason:(id)arg1;
- (void)setNextJoinWhileDeferJoin:(bool)arg1;
- (void)setNextLinkUpIsSameBSSID:(bool)arg1;
- (void)setPerCoreRSSI_Core0_Duration:(double)arg1;
- (void)setPerCoreRSSI_Core1_Duration:(double)arg1;
- (void)setPerCoreRSSI_NotUsed_Duration:(double)arg1;
- (void)setRoamStatus_FailedFilteredOut_Count_BeforeTDWait:(unsigned long long)arg1;
- (void)setRoamStatus_FailedFilteredOut_Count_WhileTDWait:(unsigned long long)arg1;
- (void)setRoamStatus_FailedNotFound_Count_BeforeTDWait:(unsigned long long)arg1;
- (void)setRoamStatus_FailedNotFound_Count_WhileTDWait:(unsigned long long)arg1;
- (void)setRoamStatus_Failed_Count_BeforeTDWait:(unsigned long long)arg1;
- (void)setRoamStatus_Failed_Count_WhileTDWait:(unsigned long long)arg1;
- (void)setRoamStatus_Succeeded_Count_BeforeTDWait:(unsigned long long)arg1;
- (void)setRoamStatus_Succeeded_Count_WhileTDWait:(unsigned long long)arg1;
- (void)setRssiAtJoin:(long long)arg1;
- (void)setRssiAtNextLinkUp:(long long)arg1;
- (void)setSessionEndedBy:(int)arg1;
- (void)setSessionStartedBy:(int)arg1;
- (void)setSuppress_2dBGuard:(double)arg1;
- (void)setSuppress_ActiveProbing:(double)arg1;
- (void)setSuppress_FastCheapCellular_Duration:(double)arg1;
- (void)setSuppress_GoodAfterRoam_Duration:(double)arg1;
- (void)setSuppress_NoFgNetwApp_Duration:(double)arg1;
- (void)setSuppress_Roam_Duration:(double)arg1;
- (void)setSuppress_SymptomsAppPolicy_Duration:(double)arg1;
- (void)setSuppress_SymptomsNODataStall_Duration:(double)arg1;
- (void)setSuppress_TTR_Duration:(double)arg1;
- (void)setSuppress_UserInput_Duration:(double)arg1;
- (void)setTdConfirmed:(bool)arg1;
- (void)setTdEvalDurationCumulative:(double)arg1;
- (void)setTdExecuted:(bool)arg1;
- (void)setTdRecommendAtJoin:(bool)arg1;
- (void)setTdRecommendAtNextLinkUp:(bool)arg1;
- (void)setTimeSinceJoinATStart:(double)arg1;
- (void)setTimeToNextJoin:(double)arg1;
- (void)setVote_FastTD_BeaconPER_Duration:(double)arg1;
- (void)setVote_FastTD_FWTxPER_Duration:(double)arg1;
- (void)setVote_FastTD_Recommendation_Duration:(double)arg1;
- (void)setVote_FastTD_TXPER_Duration:(double)arg1;
- (void)setWaitOnRoamStatusDurationCumulative:(unsigned long long)arg1;
- (void)summarizeSession;
- (double)suppress_2dBGuard;
- (double)suppress_ActiveProbing;
- (double)suppress_FastCheapCellular_Duration;
- (double)suppress_GoodAfterRoam_Duration;
- (double)suppress_NoFgNetwApp_Duration;
- (double)suppress_Roam_Duration;
- (double)suppress_SymptomsAppPolicy_Duration;
- (double)suppress_SymptomsNODataStall_Duration;
- (double)suppress_TTR_Duration;
- (double)suppress_UserInput_Duration;
- (bool)tdConfirmed;
- (double)tdEvalDurationCumulative;
- (bool)tdExecuted;
- (void)tdLogic_alertedBy:(int)arg1;
- (void)tdLogic_badRssi:(long long)arg1 goodRSSI:(long long)arg2;
- (void)tdLogic_decisionState:(struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; int x9; bool x10; bool x11; bool x12; bool x13; bool x14; bool x15; long long x16; })arg1;
- (void)tdLogic_deferJoin:(unsigned long long)arg1 perBSSID:(unsigned long long)arg2;
- (void)tdLogic_end:(int)arg1 evalTime:(double)arg2 rssi:(long long)arg3 roamTime:(double)arg4;
- (void)tdLogic_execState:(struct { bool x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; bool x8; bool x9; bool x10; bool x11; bool x12; bool x13; })arg1;
- (void)tdLogic_fastTdState:(struct { unsigned long long x1; bool x2; bool x3; bool x4; bool x5; bool x6; bool x7; })arg1;
- (bool)tdRecommendAtJoin;
- (bool)tdRecommendAtNextLinkUp;
- (double)timeSinceJoinATStart;
- (double)timeToNextJoin;
- (void)triggerDisconnectAlerted:(bool)arg1 confirmed:(bool)arg2 executed:(bool)arg3;
- (double)vote_FastTD_BeaconPER_Duration;
- (double)vote_FastTD_FWTxPER_Duration;
- (double)vote_FastTD_Recommendation_Duration;
- (double)vote_FastTD_TXPER_Duration;
- (unsigned long long)waitOnRoamStatusDurationCumulative;

@end
